/* ============================================================
   PRISME — « Si tu étais une maladie »
   ------------------------------------------------------------
   Rien de grave ici : seulement des maux bénins, du quotidien ou
   de l'histoire, pris avec humour. Ce qui compte, c'est leur caractère :
   celui qui arrive sans prévenir, qui s'incruste, qui se transmet à
   tout le monde, qui revient chaque printemps ou qui ne dure qu'une seconde.
     name = la maladie, by = type · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const AILMENTS = [
  { name: 'Le rhume', by: 'Virus · quelques jours', tag: 'Le plus fidèle des visiteurs', color: '#d98c7a',
    desc: 'Un adulte en attrape en moyenne deux ou trois par an, et plus de deux cents virus différents peuvent le provoquer. Il ne fait peur à personne, ne cherche jamais à impressionner et passe dans tous les foyers sans distinction. C\'est le tempérament des gens simples et constants, qui font partie du paysage et qu\'on serait presque déçu de ne pas voir revenir.',
    t: { soc: 0.85, ste: 0.85, fia: 0.85, aud: 0.1, vst: 0.15, vtr: 0.8, col: 0.8, dom: 0.1, cmp: 0.15, vco: 0.85, ide: 0.2 } },
  { name: 'La grippe saisonnière', by: 'Virus · chaque hiver', tag: 'Quand elle passe, tout s\'arrête', color: '#5b6f9a',
    desc: 'Elle arrive chaque hiver avec la ponctualité d\'un chef de gare, cloue tout le monde au lit et n\'accepte aucune négociation. Elle change un peu de visage chaque année, au point qu\'il faut adapter le vaccin à chaque saison. C\'est le caractère des personnalités qui s\'imposent : quand elles entrent dans une pièce, l\'ordre du jour change.',
    t: { dom: 0.95, lea: 0.85, cfl: 0.85, vpo: 0.85, dip: 0.1, emp: 0.15, ord: 0.8, ste: 0.2, att: 0.2, cmp: 0.8 } },
  { name: 'Le hoquet', by: 'Réflexe · quelques minutes', tag: 'Absurde, inoffensif, imprévisible', color: '#f2b705',
    desc: 'Une petite contraction du diaphragme, sans raison et sans prévenir, et chacun y va de son remède : verre d\'eau à l\'envers, peur surprise, souffle retenu. L\'Américain Charles Osborne l\'aurait gardé soixante-huit ans. C\'est le tempérament des gens imprévisibles et sans malice, qui vivent au gré des circonstances et ne prennent rien trop au sérieux.',
    t: { loc: 0.9, ord: 0.05, rig: 0.1, inc: 0.9, tmp: 0.05, dog: 0.05, vac: 0.1, com: 0.15, epi: 0.1, vhe: 0.75, ste: 0.6 } },
  { name: 'La varicelle', by: 'Virus · une fois dans la vie', tag: 'Le rite de passage de la cour d\'école', color: '#e36b6b',
    desc: 'Presque tout le monde l\'a eue enfant, en même temps que toute sa classe, et on ne l\'attrape en général qu\'une fois. Elle a ses rituels, ses consignes de grands-parents et ses photos de famille à pois. C\'est la maladie des gens pour qui les grandes étapes se vivent ensemble, dans l\'ordre et selon la tradition, et qui aiment faire partie de la bande.',
    t: { vtr: 0.9, col: 0.9, soc: 0.85, vco: 0.85, loy: 0.85, ind: 0.1, vsd: 0.15, chg: 0.15, dog: 0.6, vst: 0.3 } },
  { name: 'Les oreillons', by: 'Virus · joues de hamster', tag: 'Tant pis pour l\'allure', color: '#f0a868',
    desc: 'Ils gonflent les glandes salivaires sous les oreilles et donnent pendant quelques jours une bonne tête de hamster, que le vaccin a rendue rare. On ne peut pas vraiment garder la pose avec des oreillons. C\'est le tempérament de ceux qui ne se soucient pas de leur image, rient d\'eux-mêmes les premiers et restent bons vivants même quand ils ne sont pas à leur avantage.',
    t: { opt: 0.9, att: 0.85, ste: 0.8, cfl: 0.1, vac: 0.05, vpo: 0.05, dog: 0.1, vtr: 0.7, vbe: 0.85, cmp: 0.05 } },
  { name: 'La migraine', by: 'Crise · volets fermés', tag: 'Silence, obscurité, pas de discussion', color: '#4b3f72',
    desc: 'Quand elle s\'installe, il faut éteindre la lumière, baisser le son et laisser tout le monde dehors. Elle a ses déclencheurs, ses signes avant-coureurs, ses rituels précis, et elle n\'accepte aucune approximation. C\'est le caractère des gens exigeants et sensibles, qui ont besoin de calme et d\'ordre autour d\'eux et savent très exactement ce qu\'ils ne supportent pas.',
    t: { soc: 0.05, inf: 0.05, vig: 0.9, thr: 0.85, con: 0.9, rig: 0.85, vhe: 0.15, nat: 0.75, dog: 0.7, ouv: 0.25 } },
  { name: 'Le rhume des foins', by: 'Allergie · chaque printemps', tag: 'Réglé comme le calendrier', color: '#c9b44a',
    desc: 'Pollens d\'arbres puis de graminées : il revient chaque année à la même période, avec une précision que les horloges lui envient. On le voit venir, on s\'y prépare, on a ses mouchoirs et son programme. C\'est le tempérament des gens prévoyants et méthodiques, qui aiment que les saisons tournent dans l\'ordre et préfèrent la ville bien rangée aux grandes prairies.',
    t: { ord: 0.95, fia: 0.9, vse: 0.9, vig: 0.9, tmp: 0.85, rsk: 0.05, vst: 0.1, vun: 0.15, inc: 0.1, aud: 0.1 } },
  { name: 'L\'insomnie', by: 'Nuit blanche · 3 h 17', tag: 'La tête qui refuse d\'éteindre', color: '#1f2a4d',
    desc: 'Tout le monde dort, sauf elle. À trois heures du matin, elle refait la réunion de la veille, prépare celle de dans dix ans et invente trois romans. C\'est le tempérament des cérébraux passionnés, qui pensent trop et trop loin, imaginent des mondes entiers et ne savent pas vraiment appuyer sur le bouton pause.',
    t: { aff: 0.95, ide: 0.9, tmp: 0.9, ouv: 0.85, thr: 0.8, ste: 0.1, san: 0.2, vhe: 0.15, soc: 0.2, epi: 0.75 } },
  { name: 'Le mal de mer', by: 'Transport · dès la sortie du port', tag: 'Rien ne vaut la terre ferme', color: '#3f8f8a',
    desc: 'Il naît du désaccord entre l\'oreille interne, qui sent la houle, et les yeux, qui voient une cabine immobile. Même l\'amiral Nelson en a souffert toute sa vie. C\'est le tempérament des gens enracinés, qui aiment sentir le sol sous leurs pieds, se méfient des aventures au large et sont bien plus heureux au port qu\'en pleine traversée.',
    t: { opn: 0.95, vse: 0.95, rsk: 0.05, vst: 0.05, chg: 0.05, aud: 0.1, vtr: 0.85, inc: 0.1, ste: 0.75, ouv: 0.2 } },
  { name: 'Le mal des transports', by: 'Voiture · jamais au volant', tag: 'Malade à l\'arrière, parfait au volant', color: '#6c8c3c',
    desc: 'Assis à l\'arrière, il vire au vert au troisième virage ; au volant, il se porte comme un charme, car celui qui conduit anticipe chaque courbe. Tout le problème est de ne pas tenir les commandes. C\'est le caractère de ceux qui ont besoin de piloter eux-mêmes, supportent mal qu\'on décide à leur place et vont tellement mieux quand ils mènent la barque.',
    t: { dom: 0.85, ind: 0.9, vsd: 0.9, lea: 0.85, loc: 0.05, col: 0.2, auth: 0.2, ste: 0.3, dip: 0.3, con: 0.3 } },
  { name: 'Le coup de soleil', by: 'Peau · le soir même', tag: 'Encore cinq minutes, promis', color: '#ef5b3a',
    desc: 'On l\'attrape en disant « encore cinq minutes », entre une baignade et une glace, et on le découvre le soir en rentrant, rouge comme un homard. Il est la preuve d\'une très belle journée et d\'une très petite prudence. C\'est le tempérament des amoureux de l\'instant, qui profitent sans compter et laissent les crèmes et les consignes aux autres.',
    t: { vhe: 0.98, tmp: 0.05, vig: 0.05, rsk: 0.85, opt: 0.95, thr: 0.05, rig: 0.1, con: 0.1, vst: 0.8, soc: 0.75 } },
  { name: 'Le torticolis', by: 'Nuque · au réveil', tag: 'Impossible de regarder ailleurs', color: '#8a6d4b',
    desc: 'On se réveille avec, et pour quelques jours il faut tourner tout le corps pour regarder à côté. La tête reste obstinément dans l\'axe, quoi qu\'il arrive. C\'est le tempérament des convaincus, fidèles à leur point de vue au point d\'avoir du mal à en envisager un autre, solides comme des piliers et à peu près aussi faciles à faire pivoter.',
    t: { dog: 0.95, ouv: 0.1, inc: 0.1, opn: 0.85, chg: 0.1, epi: 0.85, dip: 0.2, rig: 0.8, auth: 0.75, vst: 0.15 } },
  { name: 'La crampe', by: 'Muscle · quelques secondes', tag: 'Tout, d\'un coup, puis plus rien', color: '#d64550',
    desc: 'Elle frappe au milieu de la nuit ou en plein match, sans le moindre préavis, fait bondir tout le monde, puis disparaît comme elle est venue. Pas de rancune, pas de suite. C\'est le caractère des tempéraments volcaniques et imprévisibles, qui explosent pour un rien, passent à autre chose une minute plus tard et ne comprennent pas qu\'on leur en veuille encore.',
    t: { san: 0.05, ste: 0.05, cfl: 0.8, tmp: 0.05, ord: 0.1, loc: 0.8, inc: 0.8, com: 0.8, rig: 0.2, dog: 0.15 } },
  { name: 'Le décalage horaire', by: 'Voyage · un jour par fuseau', tag: 'Le corps ici, la tête là-bas', color: '#2b7bb9',
    desc: 'On compte à peu près une journée pour récupérer par fuseau traversé, et c\'est plus dur vers l\'est que vers l\'ouest. Il mange à trois heures du matin et s\'endort à midi, mais il a vu le monde. C\'est le tempérament des grands voyageurs, curieux de tout et à l\'aise partout, pour qui un emploi du temps chamboulé est le prix raisonnable de l\'ailleurs.',
    t: { opn: 0.02, vst: 0.95, ouv: 0.95, vun: 0.8, vtr: 0.1, ord: 0.2, inc: 0.85, rsk: 0.75, vse: 0.15, ind: 0.8 } },
  { name: 'La gueule de bois', by: 'Lendemain · jusqu\'à midi', tag: 'La facture de la plus belle soirée', color: '#9c4f96',
    desc: 'Elle est le souvenir un peu flou d\'une soirée où l\'on a beaucoup ri, beaucoup dansé et promis de ne jamais recommencer. On jure le matin, on oublie le soir. C\'est le tempérament des fêtards au grand cœur, qui vivent pleinement l\'instant, n\'ont que faire des convenances et payent de bonne grâce, le lendemain, le prix de leurs excès.',
    t: { vhe: 0.95, inf: 0.9, soc: 0.95, tmp: 0.05, rig: 0.05, vco: 0.1, vig: 0.1, sanc: 0.05, vtr: 0.2, ord: 0.1 } },
  { name: 'Le bâillement contagieux', by: 'Réflexe · de proche en proche', tag: 'Il suffit de le voir pour l\'attraper', color: '#b7a3d6',
    desc: 'Il suffit de voir quelqu\'un bâiller, parfois même de lire le mot, pour bâiller à son tour, et certains chercheurs y voient un reflet de notre lien aux autres. On l\'attrape plus facilement chez les gens qu\'on aime. C\'est le tempérament des cœurs perméables, qui ressentent ce que ressentent les autres avant même qu\'ils l\'aient dit.',
    t: { emp: 0.98, att: 0.9, care: 0.9, col: 0.8, ste: 0.85, dom: 0.05, cmp: 0.05, ind: 0.1, cfl: 0.1, aff: 0.1 } },
  { name: 'L\'orgelet', by: 'Paupière · le compère-loriot', tag: 'Personne ne le remarque, sauf toi', color: '#c98b8b',
    desc: 'Un petit bouton au bord de la paupière, qu\'on appelait autrefois le compère-loriot, et qui s\'en va tout seul en quelques jours. On a l\'impression que le monde entier ne regarde que lui ; en réalité, personne n\'a rien vu. C\'est le tempérament des discrets un peu inquiets, qui préfèrent ne pas se faire remarquer et se trouvent toujours plus visibles qu\'ils ne le sont.',
    t: { inf: 0.05, dom: 0.05, vpo: 0.05, soc: 0.2, thr: 0.8, vig: 0.8, ste: 0.85, san: 0.25, con: 0.75, aud: 0.1 } },
  { name: 'L\'aphte', by: 'Bouche · une petite semaine', tag: 'Minuscule, mais on ne pense qu\'à lui', color: '#f4e3c1',
    desc: 'Il fait la taille d\'une lentille et occupe pourtant toute la conversation, parce que la langue y revient sans cesse. Il pique au citron, à la vinaigrette, à la moindre contrariété. C\'est le caractère des râleurs attachants, qui voient le détail qui cloche avant tout le reste, le disent sans filtre et ont rarement tout à fait tort.',
    t: { com: 0.85, cfl: 0.8, dip: 0.1, opt: 0.1, vis: 0.8, nat: 0.75, thr: 0.65, soc: 0.35, ste: 0.3, vhe: 0.3 } },
  { name: 'L\'ampoule au pied', by: 'Randonnée · au vingtième kilomètre', tag: 'La preuve qu\'on a marché loin', color: '#b5835a',
    desc: 'Elle apparaît au vingtième kilomètre, sur le chemin de Compostelle ou le GR du dimanche, et personne ne s\'arrête pour si peu. Un pansement, une chaussette sèche, et on repart. C\'est le tempérament des marcheurs obstinés, qui aiment l\'effort lent, la nature et le sens du chemin, et trouvent que les plus belles choses se méritent pas à pas.',
    t: { det: 0.95, vun: 0.85, tmp: 0.9, ste: 0.85, vhe: 0.1, sanc: 0.75, vst: 0.6, inf: 0.2, vpo: 0.1, vac: 0.3 } },
  { name: 'La verrue', by: 'Peau · des mois, parfois des années', tag: 'Rien ne la fait partir, sauf elle', color: '#8f8a5e',
    desc: 'On l\'a brûlée, gelée, confiée à un charmeur de verrues du village, et elle est toujours là. Puis un jour, elle part d\'elle-même, comme souvent. C\'est le tempérament des têtus tranquilles, attachés aux vieilles recettes, qui n\'écoutent ni les conseils ni les modes et ne changent d\'avis que lorsqu\'ils l\'ont décidé, tout seuls.',
    t: { vtr: 0.95, det: 0.9, ind: 0.85, chg: 0.05, ouv: 0.2, sanc: 0.8, soc: 0.2, inc: 0.3, vco: 0.3, inf: 0.1 } },
  { name: 'L\'entorse', by: 'Cheville · le mauvais appui', tag: 'Le prix d\'un geste trop audacieux', color: '#e0703a',
    desc: 'Elle arrive sur une réception ratée, un dribble trop ambitieux ou une descente prise au pas de course. Elle n\'est jamais le fruit de la prudence. C\'est le tempérament des sportifs et des casse-cou, qui veulent gagner, aller plus vite et plus haut que les autres, et qui préfèrent mille fois une cheville bandée à un regret.',
    t: { aud: 0.95, rsk: 0.95, cmp: 0.9, vst: 0.9, vac: 0.8, vig: 0.1, vse: 0.05, thr: 0.1, rig: 0.2, san: 0.35 } },
  { name: 'La rage de dents', by: 'Dent · tout de suite, maintenant', tag: 'Impossible de l\'ignorer', color: '#b3202a',
    desc: 'On ne négocie pas avec une rage de dents : elle exige un rendez-vous, là, tout de suite, et elle l\'obtient. Elle ne laisse penser à rien d\'autre tant qu\'on ne l\'a pas écoutée. C\'est le tempérament des personnalités d\'acier, franches jusqu\'à la brusquerie, qui disent les choses fort et exigent qu\'on s\'en occupe sans attendre.',
    t: { dom: 0.95, com: 0.95, cfl: 0.95, dip: 0.05, ste: 0.05, eng: 0.85, auth: 0.75, emp: 0.2, lea: 0.7, tmp: 0.1 } },
  { name: 'Le lumbago', by: 'Dos · le tour de reins', tag: 'Il voulait porter le frigo tout seul', color: '#7a5c8c',
    desc: 'Il frappe souvent celui qui a refusé qu\'on l\'aide à porter l\'armoire, le frigo ou les cartons du déménagement d\'un ami. Serviable, costaud, persuadé de pouvoir tout faire seul, on le retrouve plié en deux. C\'est le tempérament des débrouillards généreux, toujours là pour les autres mais incapables de demander un coup de main.',
    t: { ind: 0.95, col: 0.15, fia: 0.9, vbe: 0.9, vig: 0.1, aud: 0.7, soc: 0.35, inf: 0.2, loc: 0.1, vpo: 0.2 } },
  { name: 'La tendinite', by: 'Tendon · à force de répéter', tag: 'Le même geste, mille fois', color: '#5a7d9a',
    desc: 'Elle naît de la répétition : le même coup de raquette, le même clic de souris, la même gamme au piano, des milliers de fois. Elle est l\'envers du perfectionnisme. C\'est le tempérament des gens méthodiques et appliqués, qui recommencent jusqu\'à ce que ce soit parfait, préfèrent la maîtrise à la nouveauté et oublient parfois de s\'arrêter.',
    t: { rig: 0.95, con: 0.95, ord: 0.95, det: 0.85, vst: 0.05, inc: 0.1, chg: 0.1, vhe: 0.15, ide: 0.3, soc: 0.3 } },
  { name: 'Le tennis-elbow', by: 'Coude · rarement au tennis', tag: 'Un nom trompeur, un vrai caractère', color: '#b8c94a',
    desc: 'Il porte le nom d\'un sport, mais la plupart des gens qui l\'attrapent n\'ont jamais tenu une raquette : ils ont bricolé, jardiné ou tapé au clavier. Il se moque des étiquettes qu\'on lui colle. C\'est le tempérament des esprits libres et inclassables, qui déjouent les attentes, refusent les cases et s\'amusent qu\'on se trompe sur leur compte.',
    t: { lib: 0.95, vco: 0.05, auth: 0.05, dog: 0.05, ide: 0.85, inc: 0.85, vsd: 0.9, epi: 0.15, con: 0.1, vtr: 0.15 } },
  { name: 'L\'angine', by: 'Gorge · la gorge nouée', tag: 'Les mots qui restent coincés', color: '#d65a74',
    desc: 'Elle serre la gorge, rend chaque mot difficile et chaque gorgée compliquée, et elle est bien souvent due à un simple virus. Elle garde tout à l\'intérieur. C\'est le tempérament des cœurs sensibles et pudiques, qui ressentent beaucoup, disent peu, évitent les éclats et gardent pour eux ce qui les touche vraiment.',
    t: { aff: 0.05, emp: 0.85, att: 0.85, com: 0.1, cfl: 0.05, inf: 0.15, dip: 0.8, thr: 0.7, dom: 0.1, san: 0.35 } },
  { name: 'L\'otite', by: 'Oreille · surtout chez les petits', tag: 'Sourd quand ça l\'arrange', color: '#e6a15a',
    desc: 'L\'oreille se bouche et les sons arrivent étouffés, ce qui tombe parfois drôlement bien au moment où l\'on demande de ranger sa chambre. Elle n\'argumente pas, elle n\'entend pas. C\'est le tempérament des résistants tranquilles, qui n\'affrontent jamais personne mais font exactement ce qu\'ils veulent, avec un sourire désarmant.',
    t: { vsd: 0.9, ind: 0.8, cfl: 0.05, com: 0.1, vco: 0.1, auth: 0.1, ste: 0.85, vhe: 0.8, dom: 0.15, rig: 0.15 } },
  { name: 'La bronchite', by: 'Toux · deux ou trois semaines', tag: 'L\'invitée qui ne part plus', color: '#7f8c8d',
    desc: 'Elle devait passer quelques jours, elle reste trois semaines, et sa toux fait partie des meubles. Elle n\'est pas méchante, simplement attachée. C\'est le tempérament des fidèles qui s\'installent dans une amitié, une maison ou une habitude pour de bon, n\'aiment pas les départs et restent volontiers un peu plus longtemps qu\'on ne l\'avait prévu.',
    t: { ste: 0.9, att: 0.9, loy: 0.85, chg: 0.05, tmp: 0.8, vst: 0.1, aud: 0.15, vtr: 0.8, rsk: 0.1, ind: 0.2 } },
  { name: 'La gastro', by: 'Virus · toute la maison', tag: 'Personne n\'y échappe', color: '#8fbf5a',
    desc: 'Elle entre dans une maison par le plus petit et, en trois jours, tout le monde y est passé, chacun son tour, dans un joyeux désordre. Elle adore l\'hiver, les crèches et les repas de famille. C\'est le tempérament des personnalités contagieuses qui embarquent tout le monde dans leur sillage, mettent le chaos partout où elles passent et ne laissent personne indifférent.',
    t: { col: 0.9, inf: 0.9, ord: 0.05, chg: 0.85, con: 0.05, rig: 0.1, dom: 0.75, vse: 0.1, soc: 0.8, ste: 0.15 } },
  { name: 'La crise de foie', by: 'France · lendemain de fête', tag: 'Une spécialité bien française', color: '#c7a23b',
    desc: 'Une maladie presque uniquement française, qui suit les repas de fête, les bûches et les plateaux de fromages ; le foie, d\'ailleurs, n\'y est souvent pour rien. Elle aime la tablée, la cuisine de grand-mère et les resservis. C\'est le tempérament des épicuriens attachés à la famille, pour qui on ne quitte pas la table tant que la conversation est bonne.',
    t: { vhe: 0.95, vtr: 0.95, att: 0.9, vbe: 0.9, rig: 0.1, vig: 0.1, vst: 0.2, ouv: 0.3, opn: 0.8, dom: 0.2 } },
  { name: 'La carie', by: 'Dent · patiemment, en silence', tag: 'Lente, discrète, redoutablement efficace', color: '#5c4a3a',
    desc: 'Elle ne fait aucun bruit : des bactéries transforment le sucre en acide et grignotent la dent, jour après jour, pendant des mois. Quand on la remarque, elle a déjà gagné du terrain. C\'est le tempérament des stratèges patients et silencieux, qui ne se montrent jamais, avancent pas à pas et savent exactement où ils vont.',
    t: { tmp: 0.95, san: 0.9, ste: 0.8, inf: 0.05, soc: 0.15, cmp: 0.85, vpo: 0.8, emp: 0.15, dom: 0.6, opt: 0.35, vac: 0.8 } },
  { name: 'La conjonctivite', by: 'Œil · voir rouge', tag: 'Elle voit tout en rouge', color: '#e34b4b',
    desc: 'L\'œil rougit, pique et ne supporte plus rien, et elle fait le tour d\'une classe en une semaine. Elle voit rouge, littéralement. C\'est le tempérament des indignés au grand cœur, que l\'injustice met hors d\'eux, qui s\'engagent à fond et entraînent les autres dans leurs combats, quitte à s\'enflammer un peu vite.',
    t: { eng: 0.95, fair: 0.9, care: 0.85, vun: 0.9, com: 0.8, cfl: 0.8, san: 0.1, aff: 0.15, vpo: 0.1, vtr: 0.2 } },
  { name: 'L\'urticaire', by: 'Peau · comme une ortie', tag: 'Elle réagit à tout, tout de suite', color: '#f08a8a',
    desc: 'Son nom vient d\'urtica, l\'ortie en latin : des plaques qui démangent apparaissent au moindre stress, au froid ou à un aliment, puis disparaissent en quelques heures. Elle sent tout, plus fort que les autres. C\'est le tempérament des hypersensibles, qui captent la moindre tension dans l\'air et réagissent avant même d\'avoir compris pourquoi.',
    t: { thr: 0.95, san: 0.05, ste: 0.1, vig: 0.85, emp: 0.85, inc: 0.1, opt: 0.2, sanc: 0.8, aff: 0.2, dom: 0.15 } },
  { name: 'Le bouton de fièvre', by: 'Lèvre · la veille du grand jour', tag: 'Toujours là pour les grandes occasions', color: '#d9534f',
    desc: 'Il sort quand on est fatigué, stressé ou trop exposé au soleil, c\'est-à-dire, en pratique, la veille d\'un mariage, d\'un entretien ou d\'une photo de classe. Il a un sens redoutable du moment. C\'est le tempérament de ceux qui adorent être au centre de l\'attention, visent les grands rendez-vous et ne ratent jamais une entrée remarquée.',
    t: { inf: 0.85, vpo: 0.85, vac: 0.85, cmp: 0.85, dip: 0.1, vco: 0.1, emp: 0.2, ste: 0.2, dom: 0.7, vbe: 0.3 } },
  { name: 'Le vertige', by: 'Hauteur · l\'appel du vide', tag: 'Fasciné par ce qui fait peur', color: '#6aa6c9',
    desc: 'Tout en haut de la tour, les jambes flageolent et pourtant on ne peut pas s\'empêcher de regarder en bas. Il est à la fois une peur et une fascination. C\'est le tempérament des imaginatifs prudents, qui rêvent des sommets mais préfèrent les contempler depuis un endroit sûr et vivent leurs plus grandes aventures dans leur tête.',
    t: { ide: 0.9, rsk: 0.1, aud: 0.15, vse: 0.85, vig: 0.85, ouv: 0.8, thr: 0.75, aff: 0.3, dom: 0.1, cmp: 0.2 } },
  { name: 'Le fou rire', by: 'Rire · au pire moment', tag: 'Plus on se retient, pire c\'est', color: '#ffb000',
    desc: 'Il éclate en réunion, en classe ou pendant un discours solennel, et plus on essaie de le contenir, plus il redouble. Il se transmet d\'un regard. C\'est le tempérament des joyeux incorrigibles, allergiques au protocole et aux mines graves, qui trouvent toujours quelque chose de drôle et entraînent tout le monde avec eux.',
    t: { inf: 0.98, vhe: 0.9, opt: 0.95, soc: 0.9, vco: 0.05, auth: 0.05, con: 0.05, san: 0.1, epi: 0.05, vis: 0.05 } },
  { name: 'Les courbatures', by: 'Muscles · le surlendemain', tag: 'La preuve que ça marche', color: '#e08e3c',
    desc: 'On les sent le lendemain ou le surlendemain de la première séance, et contrairement à la légende, l\'acide lactique n\'y est pour rien. Elles tirent un peu, mais elles sont le signe qu\'on s\'est remis en route. C\'est le tempérament des gens qui prennent de bonnes résolutions et s\'y tiennent, persuadés qu\'on peut toujours changer et que l\'effort finit par payer.',
    t: { det: 0.9, opt: 0.85, vac: 0.85, chg: 0.85, loc: 0.05, tmp: 0.8, vhe: 0.15, vtr: 0.2, vis: 0.1, ste: 0.4 } },
  { name: 'Les fourmis dans les jambes', by: 'Jambes · après trop d\'immobilité', tag: 'Impossible de tenir en place', color: '#a45c2a',
    desc: 'Elles arrivent quand on reste assis trop longtemps, et soudain il faut se lever, marcher, bouger, n\'importe comment mais tout de suite. Elles ne supportent pas l\'attente. C\'est le tempérament des impatients à la bougeotte, qui détestent les réunions qui traînent, décident vite et préfèrent mille fois se tromper en avançant que réussir en attendant.',
    t: { ste: 0.02, vst: 0.9, tmp: 0.1, aud: 0.8, dom: 0.7, san: 0.2, rig: 0.2, vse: 0.15, ord: 0.3, inc: 0.75 } },
  { name: 'Les engelures', by: 'Froid · les doigts et les orteils', tag: 'Le froid ne l\'a jamais arrêté', color: '#7fa8c9',
    desc: 'Elles naissent du froid humide sur les doigts et les orteils, chez ceux qui restent dehors quand tout le monde est rentré. Elles ne se plaignent pas, elles serrent les dents. C\'est le tempérament des stoïques endurcis, gens de montagne ou de grand large, peu bavards, peu démonstratifs, qui supportent tout sans broncher et trouvent qu\'on s\'écoute un peu trop.',
    t: { san: 0.95, det: 0.85, vhe: 0.05, inf: 0.05, soc: 0.15, emp: 0.25, opt: 0.35, vtr: 0.75, aff: 0.8, care: 0.25 } },
  { name: 'Le coup de froid', by: 'Hiver · sans écharpe', tag: 'On lui avait pourtant dit', color: '#4f8fc0',
    desc: 'Les grands-mères l\'avaient annoncé : pas d\'écharpe, cheveux mouillés, veste ouverte en janvier. Il est le résultat d\'un conseil soigneusement ignoré. C\'est le tempérament des indépendants un peu frondeurs, qui détestent qu\'on leur dise quoi faire, prennent des risques pour le principe et assument sans faire d\'histoire les conséquences de leurs choix.',
    t: { lib: 0.95, vco: 0.05, auth: 0.05, vig: 0.05, rsk: 0.8, vsd: 0.95, ind: 0.9, cfl: 0.7, thr: 0.1, dip: 0.3 } },
  { name: 'La piqûre de moustique', by: 'Été · la nuit', tag: 'Tenace, taquine, impossible à ignorer', color: '#6b4c7a',
    desc: 'Seule la femelle pique, et elle choisit toujours le moment où l\'on vient d\'éteindre la lumière. Elle tourne, revient, insiste, et on finit toujours par se gratter. C\'est le tempérament des taquins persévérants, qui aiment asticoter, lancer une pique pour le plaisir et reviennent à la charge jusqu\'à obtenir une réaction.',
    t: { com: 0.85, det: 0.85, cfl: 0.8, inf: 0.75, dip: 0.1, vhe: 0.8, emp: 0.25, ste: 0.15, rig: 0.2, vco: 0.15 } },
  { name: 'L\'écharde', by: 'Doigt · sous la peau', tag: 'Ce qui est entré ne ressort pas', color: '#9a7b4f',
    desc: 'Un minuscule éclat de bois qui s\'installe sous la peau et qu\'on sent à chaque geste tant qu\'on ne l\'a pas retiré. Elle ne passe pas avec le temps. C\'est le tempérament des mémoires longues, fidèles à leurs amis comme à leurs griefs, qui ne se fient pas facilement, n\'oublient rien et attendent réparation avant de tourner la page.',
    t: { nat: 0.9, fair: 0.9, loy: 0.9, tmp: 0.85, dog: 0.8, opt: 0.2, san: 0.3, dip: 0.3, emp: 0.35, inc: 0.2 } },
  { name: 'Les poux', by: 'École · à chaque rentrée', tag: 'Ils voyagent de tête en tête', color: '#9aa56b',
    desc: 'Contrairement à la légende, ils ne sautent pas et ne volent pas : ils passent de tête en tête par contact, et ils aiment les cheveux propres autant que les autres. Ils reviennent fidèlement à chaque rentrée. C\'est le tempérament des câlins et des sociables qui ne jugent personne, adorent la proximité et font volontiers le tour de toute la classe.',
    t: { soc: 0.95, att: 0.9, col: 0.85, vbe: 0.85, nat: 0.05, ind: 0.05, sanc: 0.05, dog: 0.1, ord: 0.7, ste: 0.75 } },
  { name: 'Le mal de gorge du lendemain de concert', by: 'Voix · après le rappel', tag: 'On a chanté plus fort que le groupe', color: '#c2185b',
    desc: 'On a chanté chaque refrain, crié au rappel et fait tout le concert au premier rang, et le lendemain il ne reste qu\'un filet de voix. Aucun regret. C\'est le tempérament des passionnés et des fans, qui s\'engagent corps et âme dans ce qu\'ils aiment, vivent tout à fond et trouvent que la tiédeur est le seul vrai défaut.',
    t: { eng: 0.9, vhe: 0.9, vst: 0.9, ide: 0.85, loy: 0.85, aff: 0.05, tmp: 0.05, vse: 0.1, con: 0.1, san: 0.2 } },
  { name: 'L\'extinction de voix', by: 'Voix · la semaine de la rentrée', tag: 'Celui qui parlait pour tout le monde', color: '#8e44ad',
    desc: 'Elle frappe les professeurs à la rentrée, les entraîneurs au bord du terrain et tous ceux qui parlent plus fort et plus longtemps que les autres. Pour une fois, il faut écouter. C\'est le tempérament des meneurs bavards et charismatiques, qui prennent naturellement la parole, animent les groupes et trouvent terriblement long de se taire trois jours.',
    t: { inf: 0.95, lea: 0.9, dom: 0.8, soc: 0.9, com: 0.75, ste: 0.1, vpo: 0.75, san: 0.3, vig: 0.2, ind: 0.3 } },
  { name: 'Le syndrome du lundi matin', by: 'Semaine · chaque lundi', tag: 'Il était mieux sous la couette', color: '#6d7b8d',
    desc: 'Aucun médecin ne l\'a jamais diagnostiqué, et pourtant il frappe chaque semaine avec une régularité implacable. Il traîne jusqu\'à la machine à café et soupire devant l\'agenda. C\'est le tempérament des amoureux du week-end, peu impressionnés par l\'ambition et les grands discours, qui pensent que la vie est ailleurs qu\'au bureau et n\'ont pas forcément tort.',
    t: { vac: 0.05, det: 0.1, vhe: 0.9, ord: 0.1, vis: 0.8, opt: 0.3, lea: 0.1, vco: 0.15, tmp: 0.1, ste: 0.7 } },
  { name: 'Le coup de pompe de 14 h', by: 'Après-midi · juste après le café', tag: 'La sieste est un art de vivre', color: '#c9a66b',
    desc: 'Le repas n\'est pas seul en cause : notre horloge interne connaît naturellement un creux de vigilance en début d\'après-midi. Lui l\'accepte avec philosophie et réclame sa sieste. C\'est le tempérament des tranquilles et des sages, qui refusent la course, écoutent leur corps et pensent qu\'un monde qui ne fait pas la sieste a perdu quelque chose.',
    t: { ste: 0.95, vhe: 0.9, san: 0.85, dom: 0.05, cmp: 0.05, vac: 0.1, rsk: 0.1, vig: 0.2, vtr: 0.8, inf: 0.2 } },
  { name: 'La goutte', by: 'Histoire · la maladie des rois', tag: 'Le gros orteil des puissants', color: '#7b1e3a',
    desc: 'On l\'appelait la maladie des rois, car elle frappait volontiers ceux qui mangeaient trop de gibier et buvaient trop de bon vin ; Louis XIV en a souffert. Elle se loge dans le gros orteil et ne supporte même pas le poids d\'un drap. C\'est le tempérament des amateurs de pouvoir et de faste, qui aiment les honneurs, la bonne chère et les traditions bien établies.',
    t: { vpo: 0.95, auth: 0.9, vhe: 0.85, vtr: 0.85, dom: 0.85, vac: 0.75, emp: 0.15, vun: 0.1, chg: 0.1, col: 0.2 } },
  { name: 'Le scorbut', by: 'Histoire · la maladie des marins', tag: 'Trop loin des côtes, trop longtemps', color: '#1e5f74',
    desc: 'Il touchait les équipages des grandes expéditions, privés de fruits frais pendant des mois, jusqu\'à ce que James Lind montre en 1747 l\'effet des agrumes ; les marins anglais y ont gagné le surnom de « limeys ». C\'est le tempérament des explorateurs au long cours, prêts à tout quitter pour l\'inconnu et à partir plus loin que tout le monde, quitte à oublier les précautions.',
    t: { aud: 0.95, rsk: 0.95, vst: 0.9, opn: 0.05, vse: 0.05, det: 0.9, lea: 0.75, col: 0.7, vig: 0.15, tmp: 0.75 } },
  { name: 'Le spleen', by: 'Histoire · Baudelaire, 1857', tag: 'La mélancolie des poètes', color: '#3d3a5c',
    desc: 'Le mot anglais désigne la rate, qu\'on croyait autrefois responsable de l\'humeur sombre, et Baudelaire en a fait un chapitre des Fleurs du mal, « Spleen et Idéal ». C\'est un ennui élégant, un ciel bas et lourd, une âme d\'artiste. C\'est le tempérament des rêveurs lucides et solitaires, qui trouvent le monde un peu fade et cherchent la beauté dans la mélancolie.',
    t: { ide: 0.95, vis: 0.95, opt: 0.05, soc: 0.15, ouv: 0.8, ind: 0.85, vco: 0.1, epi: 0.8, inf: 0.15, vac: 0.15 } },
  { name: 'Le mal du pays', by: 'Histoire · la nostalgie, 1688', tag: 'Le cœur resté à la maison', color: '#6f8f5f',
    desc: 'En 1688, le médecin Johannes Hofer invente le mot « nostalgie » pour décrire le mal des mercenaires suisses loin de leurs montagnes. On en guérit en rentrant. C\'est le tempérament des gens profondément enracinés, attachés à leur village, à leurs amis d\'enfance et aux odeurs de la maison, et qui ne se sentent jamais tout à fait eux-mêmes ailleurs.',
    t: { opn: 0.98, vtr: 0.95, loy: 0.9, att: 0.9, chg: 0.02, vst: 0.1, ouv: 0.2, vis: 0.7, rsk: 0.1, vun: 0.3 } },
  { name: 'Le bleu', by: 'Choc · une dizaine de jours', tag: 'Il change de couleur chaque jour', color: '#6a5acd',
    desc: 'Violet le premier jour, puis vert, puis jaune : le bleu passe par toutes les couleurs avant de disparaître, sans jamais rester le même deux jours de suite. On ne sait même plus où on s\'est cogné. C\'est le tempérament des caméléons curieux, qui se réinventent sans cesse, changent d\'avis, de style et de projet, et trouvent que rester pareil serait bien ennuyeux.',
    t: { chg: 0.95, ide: 0.85, vst: 0.85, inc: 0.9, ouv: 0.85, dog: 0.05, vtr: 0.1, ord: 0.15, opt: 0.8, fia: 0.3 } },
];

window.PRISME_AILMENTS = { AILMENTS };
