/* ============================================================
   PRISME — « Quel animal serais-tu ? »
   ------------------------------------------------------------
   Même principe que les personnages : chaque animal est décrit par
   des cibles de 0 à 1 sur les mêmes dimensions que le test.
     qualités  : fia det emp ouv ind lea san dip aud rig opt vig soc com ide att
     DISC      : dom inf ste con
     valeurs   : vsd vst vhe vac vpo vse vco vtr vbe vun
     morale    : care fair loy auth sanc lib
     traits    : inc dog eng
     axes (1 = pôle droit) : aff (tête) loc (porté) rsk (audacieux) ord (structuré) thr (vigilant)
                 col (collectiviste) tmp (long terme) cmp (compétitif) opn (enraciné)
   La liste est volontairement longue : dans un cercle, chacun doit pouvoir
   recevoir un animal différent. Un animal = 8 traits ou plus.
   ============================================================ */
const ANIMALS = [
  { name: 'Le lion', tag: 'L\'autorité tranquille', color: '#d98a00',
    desc: 'Il ne court pas après grand-chose : il tient un territoire et il se fait respecter sans avoir à le prouver tous les jours. Il délègue beaucoup, dort énormément, et se lève quand la situation l\'exige vraiment. Sa présence suffit à organiser tout ce qui l\'entoure.',
    t: { dom: 0.95, lea: 0.9, san: 0.85, att: 0.8, vpo: 0.85, auth: 0.8, det: 0.75, col: 0.6, rig: 0.3, soc: 0.5 } },
  { name: 'Le tigre', tag: 'La puissance solitaire', color: '#e2721c',
    desc: 'Il chasse seul, vit seul et n\'a besoin de l\'approbation de personne. Patient jusqu\'à l\'immobilité puis foudroyant, il choisit son moment et ne le rate pas. Il ne cherche pas le conflit, mais il ne recule devant aucun — et il préfère qu\'on le laisse tranquille.',
    t: { ind: 0.95, det: 0.9, san: 0.9, dom: 0.85, cmp: 0.8, vsd: 0.85, aud: 0.8, soc: 0.1, col: 0.1, dip: 0.2 } },
  { name: 'Le loup', tag: 'La meute avant soi', color: '#5c7fa3',
    desc: 'Il est puissant seul et invincible à plusieurs, et il le sait. Toute son organisation repose sur des liens : qui protège qui, qui chasse avec qui, qui nourrit les petits. Sa loyauté est absolue envers les siens et inexistante envers le reste du monde.',
    t: { loy: 0.95, col: 0.9, att: 0.9, fia: 0.85, lea: 0.75, det: 0.85, vig: 0.75, nat: 0.7, emp: 0.6, soc: 0.6 } },
  { name: 'L\'aigle', tag: 'La vue d\'en haut', color: '#7a6033',
    desc: 'Il prend de la hauteur, littéralement : de là où il se tient, il voit ce que personne d\'autre ne distingue. Il attend longtemps, plane sans effort, puis fond d\'un coup avec une précision qui ne laisse aucune chance. Solitaire, exigeant, pas particulièrement chaleureux.',
    t: { aff: 0.9, vig: 0.9, ind: 0.85, tmp: 0.85, san: 0.85, det: 0.85, rig: 0.8, vac: 0.75, soc: 0.15, emp: 0.25 } },
  { name: 'L\'ours', tag: 'Le calme qu\'il ne faut pas réveiller', color: '#7d4f2a',
    desc: 'Il vit sa vie, mange, dort, ne cherche d\'ennui à personne. On le prend souvent pour un gros nounours pataud, ce qui est une erreur : le jour où on touche à ce qui lui appartient, la transformation est totale et personne ne reste pour discuter. Le reste du temps, il est d\'une tranquillité absolue.',
    t: { san: 0.85, att: 0.9, ind: 0.8, com: 0.75, fia: 0.8, vse: 0.7, opn: 0.85, care: 0.7, soc: 0.2, dip: 0.35 } },
  { name: 'L\'éléphant', tag: 'La mémoire du groupe', color: '#65606d',
    desc: 'Il n\'oublie rien : ni les points d\'eau, ni les routes, ni ceux qui lui ont fait du mal. C\'est la matriarche qui guide, et le troupeau lui fait confiance parce qu\'elle a déjà vu passer trente saisons sèches. Il porte les siens, veille sur les petits, et s\'arrête devant ses morts.',
    t: { tmp: 0.95, att: 0.95, col: 0.9, loy: 0.9, emp: 0.85, fia: 0.9, care: 0.85, vtr: 0.85, san: 0.8, aud: 0.3 } },
  { name: 'Le dauphin', tag: 'L\'intelligence joyeuse', color: '#1c86c9',
    desc: 'Il joue, il communique, il invente des techniques de chasse que personne ne lui a apprises. Curieux de tout, y compris de nous, il vient voir ce qui se passe au lieu de fuir. Sa vie sociale est dense et compliquée, et il a visiblement de l\'humour.',
    t: { soc: 0.95, inf: 0.9, ouv: 0.9, opt: 0.9, vst: 0.85, col: 0.8, emp: 0.8, vhe: 0.8, aff: 0.6, thr: 0.2 } },
  { name: 'Le renard', tag: 'La ruse discrète', color: '#e2582c',
    desc: 'Il ne gagne jamais par la force, alors il gagne autrement : en observant, en contournant, en trouvant l\'ouverture que personne n\'a vue. Il s\'adapte à tout, ville comprise, et il a un talent particulier pour s\'en sortir dans des situations impossibles. On ne sait jamais tout à fait ce qu\'il prépare.',
    t: { aff: 0.85, ind: 0.9, vsd: 0.85, ouv: 0.85, aud: 0.75, nat: 0.7, vst: 0.7, san: 0.7, con: 0.2, col: 0.15 } },
  { name: 'Le hibou', tag: 'Celui qui veille pendant que tout dort', color: '#6a3fa0',
    desc: 'Il est là quand les autres dorment, immobile, à écouter des choses inaudibles. Il ne se presse jamais et ne parle presque pas, ce qui lui vaut une réputation de sagesse qu\'il n\'a jamais revendiquée. Quand il se déplace, c\'est sans un bruit.',
    t: { aff: 0.85, vig: 0.9, san: 0.9, tmp: 0.8, ind: 0.8, rig: 0.75, thr: 0.7, soc: 0.15, inf: 0.1, opt: 0.4 } },
  { name: 'Le corbeau', tag: 'L\'esprit curieux', color: '#46596b',
    desc: 'Il fabrique des outils, résout des énigmes, reconnaît les visages et se souvient de qui l\'a mal traité pendant des années. Il joue pour le plaisir de jouer, se moque du monde, et vole des choses brillantes dont il n\'a aucun usage. Une intelligence qui s\'ennuie vite.',
    t: { ouv: 0.95, aff: 0.85, vst: 0.85, ind: 0.85, vsd: 0.8, nat: 0.7, aud: 0.7, soc: 0.5, vco: 0.15, con: 0.2 } },
  { name: 'Le chat', tag: 'L\'indépendance revendiquée', color: '#b87900',
    desc: 'Il vient quand il veut, s\'en va quand il veut, et accepte l\'affection à ses conditions. Il a gardé quelque chose de sauvage malgré des milliers d\'années de vie commune avec nous. Il s\'attache réellement — simplement, il refuse catégoriquement d\'en faire la démonstration.',
    t: { ind: 0.95, vsd: 0.95, san: 0.8, lib: 0.9, vhe: 0.75, att: 0.6, col: 0.1, vco: 0.1, soc: 0.3, dom: 0.4 } },
  { name: 'Le chien', tag: 'La fidélité sans condition', color: '#c2850c',
    desc: 'Il te choisit une fois et c\'est pour toujours. Il sent quand ça ne va pas, vient se poser contre toi sans rien demander, et fait la fête comme au premier jour à chaque retour. Sa confiance est totale, sa rancune inexistante, et sa joie franchement contagieuse.',
    t: { loy: 0.98, fia: 0.95, att: 0.95, emp: 0.9, vbe: 0.9, opt: 0.9, col: 0.85, soc: 0.85, nat: 0.05, ind: 0.15 } },
  { name: 'Le cheval', tag: 'La liberté en mouvement', color: '#a0522d',
    desc: 'Il a besoin d\'espace et il le fait savoir. Sensible au point de sentir une hésitation dans une main posée sur son encolure, il accorde sa confiance lentement et ne la reprend pas. Il vit en groupe, fuit d\'abord, et ne se bat que lorsqu\'il n\'y a plus d\'issue.',
    t: { lib: 0.9, vsd: 0.85, emp: 0.8, soc: 0.75, col: 0.7, aud: 0.65, thr: 0.65, att: 0.75, dom: 0.35, com: 0.3 } },
  { name: 'Le castor', tag: 'Le bâtisseur obstiné', color: '#8a6a2f',
    desc: 'Il entend l\'eau couler et il ne peut pas s\'en empêcher : il faut construire. Nuit après nuit, il abat, transporte, empile, colmate, et transforme un ruisseau en étang. Son œuvre profite à des dizaines d\'espèces qui ne lui ont rien demandé, et il recommence dès qu\'une brèche apparaît.',
    t: { det: 0.95, ord: 0.9, fia: 0.9, rig: 0.85, opn: 0.9, tmp: 0.85, con: 0.85, col: 0.7, vst: 0.15, soc: 0.35 } },
  { name: 'La tortue', tag: 'Le temps long', color: '#57a639',
    desc: 'Elle avance lentement et elle arrive. Rien ne la presse, rien ne l\'affole : elle transporte sa maison, rentre la tête quand ça chauffe, et ressort quand c\'est passé. Elle vivra probablement plus longtemps que la plupart de ceux qui se sont moqués de son allure.',
    t: { ste: 0.95, san: 0.95, tmp: 0.9, vse: 0.9, opn: 0.85, thr: 0.7, det: 0.75, aud: 0.1, com: 0.1, vst: 0.05 } },
  { name: 'L\'abeille', tag: 'Le travail collectif', color: '#e9a100',
    desc: 'Elle ne fait rien pour elle-même. Tout ce qu\'elle butine, construit et défend appartient à la ruche, et elle danse pour indiquer aux autres où se trouve la nourriture qu\'elle a découverte. Organisée, infatigable, elle meurt en piquant celui qui menace la colonie.',
    t: { col: 0.98, ord: 0.95, con: 0.9, vco: 0.9, fia: 0.95, det: 0.9, loy: 0.9, ind: 0.05, vsd: 0.05, soc: 0.6 } },
  { name: 'La fourmi', tag: 'La ténacité sans bruit', color: '#7a4a2a',
    desc: 'Elle porte cinquante fois son poids, franchit des obstacles absurdes et recommence si on détruit son travail. Elle ne discute pas la tâche qu\'on lui a confiée et ne réclame aucune reconnaissance. Une colonie entière tient par l\'addition de ces obstinations minuscules.',
    t: { det: 0.95, ord: 0.9, col: 0.95, fia: 0.9, con: 0.85, eng: 0.85, tmp: 0.8, vco: 0.8, soc: 0.3, inf: 0.1 } },
  { name: 'Le suricate', tag: 'La sentinelle du groupe', color: '#d98a00',
    desc: 'Pendant que la famille creuse et mange, il se dresse sur ses pattes arrière et scrute le ciel. Il donne l\'alerte au premier point noir, et tout le monde plonge. Il prend ce tour de garde sans qu\'on le lui demande, et il le rend à un autre quand vient son tour de manger.',
    t: { vig: 0.95, thr: 0.9, col: 0.9, fia: 0.9, soc: 0.8, care: 0.8, loy: 0.85, san: 0.4, aud: 0.35, opt: 0.4 } },
  { name: 'Le manchot empereur', tag: 'L\'endurance partagée', color: '#3d3946',
    desc: 'Il traverse l\'hiver le plus dur de la planète en se serrant contre les autres, et chacun prend son tour à l\'extérieur du groupe. Il reste des semaines sans manger, un œuf posé sur les pattes, à attendre. Ce n\'est pas de l\'héroïsme : c\'est une patience organisée que rien ne décourage.',
    t: { col: 0.95, ste: 0.9, fia: 0.95, det: 0.9, loy: 0.9, care: 0.85, vco: 0.8, tmp: 0.8, cmp: 0.1, com: 0.1 } },
  { name: 'Le guépard', tag: 'Tout ou rien, très vite', color: '#e08700',
    desc: 'Il est l\'animal le plus rapide du monde pendant vingt secondes, après quoi il est épuisé et doit renoncer. Il mise tout sur une accélération et n\'a pas droit à l\'erreur. Fragile, nerveux, il perd souvent sa prise face à plus costaud — mais sur ces vingt secondes, personne ne le rattrape.',
    t: { aud: 0.95, rsk: 0.9, det: 0.85, vst: 0.8, cmp: 0.8, tmp: 0.15, ste: 0.1, san: 0.3, thr: 0.65, ord: 0.3 } },
  { name: 'Le requin', tag: 'Avancer ou couler', color: '#46596b',
    desc: 'Il n\'a pas le choix : s\'il s\'arrête, il coule. Alors il avance, en permanence, depuis quatre cents millions d\'années. Il n\'est pas cruel, il est efficace — un système de détection redoutable au service d\'un seul objectif. On le craint plus qu\'il ne mérite, et on le chasse bien plus qu\'il ne nous chasse.',
    t: { det: 0.95, cmp: 0.9, ind: 0.9, san: 0.9, nat: 0.85, vig: 0.85, dom: 0.8, emp: 0.15, soc: 0.1, dip: 0.15 } },
  { name: 'Le crocodile', tag: 'La patience immobile', color: '#4f7942',
    desc: 'Il peut rester des heures sans bouger, presque entièrement sous l\'eau, à attendre. Il ne dépense rien, ne s\'impatiente jamais, et frappe une seule fois. C\'est l\'un des plus vieux modèles encore en service : il n\'a pas eu besoin de changer.',
    t: { san: 0.98, tmp: 0.9, thr: 0.85, det: 0.9, ind: 0.85, opn: 0.9, vig: 0.85, soc: 0.05, inf: 0.05, vst: 0.05 } },
  { name: 'La panthère noire', tag: 'L\'élégance qu\'on ne voit pas venir', color: '#2b2740',
    desc: 'Elle se déplace dans l\'ombre sans faire de bruit, et on ne la remarque que lorsqu\'elle a décidé d\'être vue. Discrète jusqu\'à l\'invisibilité, précise, économe de ses gestes, elle n\'a rien à démontrer à personne. Sa réputation fait le travail à sa place.',
    t: { ind: 0.9, san: 0.95, rig: 0.8, det: 0.85, vig: 0.85, aff: 0.75, dom: 0.7, soc: 0.1, inf: 0.1, vac: 0.6 } },
  { name: 'L\'orque', tag: 'La stratégie en famille', color: '#1a1722',
    desc: 'Elle chasse en groupe avec des techniques transmises de génération en génération, différentes d\'une famille à l\'autre — une culture, au sens propre. Les filles restent avec leur mère toute leur vie. Extrêmement intelligente, coordonnée, et sans concurrent sérieux dans l\'océan.',
    t: { aff: 0.9, col: 0.9, lea: 0.85, det: 0.9, loy: 0.9, tmp: 0.85, cmp: 0.8, att: 0.85, rig: 0.75, emp: 0.6 } },
  { name: 'La baleine', tag: 'L\'immensité paisible', color: '#1f7a8c',
    desc: 'Elle traverse des océans entiers en chantant des mélodies que ses semblables entendent à des centaines de kilomètres. Elle est colossale et ne mange presque que des choses minuscules. Rien ne semble l\'agiter : elle est à une autre échelle de temps et d\'espace que le reste du monde.',
    t: { san: 0.95, tmp: 0.9, vun: 0.9, emp: 0.8, ste: 0.9, col: 0.7, care: 0.8, cmp: 0.1, com: 0.1, aud: 0.3 } },
  { name: 'Le poulpe', tag: 'L\'ingéniosité sans os', color: '#9b5de5',
    desc: 'Il ouvre des bocaux, s\'échappe par des trous de la taille de son œil, change de couleur et de texture en une seconde. Chacun de ses bras réfléchit un peu tout seul. Solitaire, curieux, joueur : c\'est probablement l\'intelligence la plus étrangère à la nôtre qu\'on puisse croiser.',
    t: { ouv: 0.95, ind: 0.95, aff: 0.85, vsd: 0.9, vst: 0.85, aud: 0.75, inc: 0.85, soc: 0.1, col: 0.1, ord: 0.25 } },
  { name: 'Le hérisson', tag: 'La boule de piquants', color: '#8a6a2f',
    desc: 'Il n\'attaque jamais. Au moindre doute il se roule en boule et attend que ça passe, ce qui marche remarquablement bien. Il sort la nuit, vaque à ses affaires, et n\'a d\'histoires avec personne. Sa défense n\'est pas de la méchanceté, c\'est de la prudence à l\'état pur.',
    t: { thr: 0.95, vse: 0.85, ind: 0.85, vig: 0.85, ste: 0.7, com: 0.1, aud: 0.15, dom: 0.1, soc: 0.15, nat: 0.7 } },
  { name: 'L\'écureuil', tag: 'L\'anticipation nerveuse', color: '#c2670c',
    desc: 'Il passe l\'automne à cacher des milliers de provisions à des endroits qu\'il oubliera en partie — et les glands oubliés deviendront des chênes. Toujours en alerte, toujours en mouvement, il ne tient pas en place plus de trois secondes. Sa prévoyance frôle l\'angoisse, et elle marche.',
    t: { thr: 0.9, vse: 0.85, ord: 0.75, vig: 0.85, vst: 0.7, aud: 0.6, ind: 0.7, san: 0.15, ste: 0.15, tmp: 0.75 } },
  { name: 'Le blaireau', tag: 'Le bourru qui ne lâche rien', color: '#4a4a52',
    desc: 'Il creuse des terriers immenses, occupés par la même famille pendant des générations. Peu sociable, franchement grognon, il ne cherche pas la bagarre mais ne recule devant aucune — y compris face à beaucoup plus gros que lui. Le genre à mourir sur place plutôt qu\'à céder.',
    t: { com: 0.9, ind: 0.85, opn: 0.95, det: 0.9, thr: 0.7, att: 0.8, vtr: 0.8, dip: 0.1, soc: 0.15, aud: 0.75 } },
  { name: 'Le papillon', tag: 'La métamorphose', color: '#e05fa0',
    desc: 'Il a passé une vie entière à ramper, puis s\'est enfermé, puis il est ressorti entièrement autre. Sa forme actuelle ne dure que quelques semaines, qu\'il passe à voler de fleur en fleur sans se poser longtemps. Léger, éphémère, et complètement transformé par rapport à ce qu\'il était.',
    t: { chg: 0.9, vst: 0.9, vhe: 0.85, ouv: 0.85, opt: 0.8, loc: 0.6, ord: 0.1, tmp: 0.15, opn: 0.1, eng: 0.3 } },
  { name: 'Le colibri', tag: 'L\'énergie concentrée', color: '#2ec4b6',
    desc: 'Il bat des ailes cinquante fois par seconde, vole en marche arrière, et doit manger presque en permanence pour ne pas s\'éteindre. Minuscule et étonnamment agressif, il chasse des oiseaux trois fois plus gros de son parterre de fleurs. Une pile électrique avec un caractère.',
    t: { vst: 0.95, aud: 0.85, com: 0.8, inf: 0.8, soc: 0.6, cmp: 0.8, det: 0.75, ste: 0.05, san: 0.15, tmp: 0.1 } },
  { name: 'L\'albatros', tag: 'Le voyageur des grands espaces', color: '#4dc9ff',
    desc: 'Il plane pendant des jours sans battre des ailes, parcourt des milliers de kilomètres au-dessus d\'un océan vide, et ne revient à terre que pour retrouver le même partenaire, année après année. Ridicule et maladroit sur le sol ; magistral dès qu\'il décolle.',
    t: { ind: 0.9, tmp: 0.85, san: 0.9, loy: 0.9, opn: 0.15, vst: 0.7, fia: 0.85, soc: 0.2, com: 0.1, aud: 0.7 } },
  { name: 'La girafe', tag: 'La douceur qui domine',
    color: '#d9a441',
    desc: 'Elle voit tout de très haut, sans avoir besoin de se mêler de quoi que ce soit. Silencieuse presque tout le temps, calme, elle règle les rares conflits par un combat de cous étrangement lent et élégant. Elle dort deux heures par nuit et personne ne sait vraiment à quoi elle pense.',
    t: { san: 0.9, dip: 0.85, vig: 0.8, tmp: 0.7, emp: 0.65, ste: 0.8, com: 0.15, dom: 0.35, soc: 0.5, aud: 0.35 } },
  { name: 'Le gorille', tag: 'La force qui protège', color: '#3d3946',
    desc: 'Le dos argenté décide, arbitre, et se met devant quand le danger arrive. Il se frappe la poitrine pour éviter d\'avoir à se battre — c\'est un avertissement, pas une déclaration de guerre. Végétarien, paisible, et absolument redoutable si on insiste.',
    t: { dom: 0.9, care: 0.9, att: 0.9, lea: 0.85, san: 0.85, col: 0.85, fia: 0.9, auth: 0.8, com: 0.45, vst: 0.2 } },
  { name: 'Le chimpanzé', tag: 'La politique permanente', color: '#7a4a2a',
    desc: 'Il vit dans un groupe où tout est question d\'alliances, de services rendus et de coups montés. Il se réconcilie après les disputes, tient les comptes, et sait exactement qui soutient qui. Curieux, bricoleur, imprévisible : c\'est celui qui nous ressemble le plus, pour le meilleur et pour le pire.',
    t: { soc: 0.85, cmp: 0.85, com: 0.8, ouv: 0.85, col: 0.75, inf: 0.8, aff: 0.7, dom: 0.7, vpo: 0.75, ste: 0.2 } },
  { name: 'Le bonobo', tag: 'Régler par le lien', color: '#e2569b',
    desc: 'Chez lui, les tensions se dénouent par le contact et l\'affection plutôt que par la violence. Les femelles décident, les conflits s\'éteignent vite, et personne ne garde de rancune très longtemps. C\'est l\'exact cousin du précédent, avec un tout autre logiciel.',
    t: { dip: 0.95, emp: 0.9, care: 0.9, soc: 0.9, col: 0.85, cfl: 0.05, vhe: 0.8, com: 0.1, cmp: 0.15, opt: 0.8 } },
  { name: 'L\'orang-outan', tag: 'Le sage solitaire', color: '#c2670c',
    desc: 'Il vit seul dans les arbres, se déplace lentement, réfléchit visiblement avant chaque mouvement. Il apprend en observant longuement, fabrique des outils, se construit un abri contre la pluie. Il n\'a besoin de personne et ne dérange personne.',
    t: { ind: 0.95, aff: 0.85, san: 0.9, tmp: 0.85, ouv: 0.8, rig: 0.7, soc: 0.1, com: 0.1, vsd: 0.9, ste: 0.75 } },
  { name: 'Le paresseux', tag: 'L\'art de ne pas se presser', color: '#8a9a5b',
    desc: 'Il fait tout au ralenti, y compris digérer, et descend de son arbre une fois par semaine. Ce n\'est pas de la fainéantise : c\'est une stratégie d\'économie d\'énergie si efficace que des algues poussent sur son pelage et le camouflent. Il a l\'air de sourire en permanence.',
    t: { ste: 0.95, san: 0.95, vhe: 0.8, eng: 0.05, det: 0.15, cmp: 0.05, com: 0.05, opt: 0.7, aud: 0.1, tmp: 0.3 } },
  { name: 'Le raton laveur', tag: 'La curiosité sans scrupules', color: '#6b7280',
    desc: 'Il ouvre tout ce qui s\'ouvre, fouille tout ce qui se fouille, et s\'est parfaitement adapté à nos poubelles. Ses mains sont d\'une dextérité déconcertante et il apprend très vite comment contourner un système censé le bloquer. Aucune honte, beaucoup d\'audace.',
    t: { ouv: 0.9, aud: 0.9, vst: 0.85, ind: 0.85, inf: 0.7, vco: 0.1, con: 0.1, ord: 0.2, nat: 0.6, vhe: 0.8 } },
  { name: 'Le bouquetin', tag: 'L\'équilibre sur le vide', color: '#8a8f98',
    desc: 'Il grimpe des murs de barrage presque verticaux pour lécher du sel, avec un calme qui fait mal au ventre quand on le regarde. Il vit là où personne ne peut le suivre, et c\'est précisément le but. Sûr de son pied, autonome, peu impressionnable.',
    t: { aud: 0.9, rsk: 0.85, ind: 0.85, san: 0.85, det: 0.85, opn: 0.7, vsd: 0.8, thr: 0.35, soc: 0.35, dip: 0.4 } },
  { name: 'Le saumon', tag: 'Le retour, quoi qu\'il en coûte', color: '#e2582c',
    desc: 'Il remonte le courant, saute des cascades, traverse des rivières entières pour revenir exactement là où il est né. Rien ne l\'en détourne, et il y laisse sa vie. C\'est l\'obstination la plus pure du règne animal, au service d\'une seule idée : rentrer.',
    t: { det: 0.98, opn: 0.95, att: 0.9, eng: 0.9, vtr: 0.85, tmp: 0.8, aud: 0.8, san: 0.5, dip: 0.3, vhe: 0.15 } },
  { name: 'Le lynx', tag: 'La discrétion absolue', color: '#9a8c78',
    desc: 'On peut vivre toute sa vie dans une forêt qu\'il habite sans jamais l\'apercevoir. Il entend une souris sous la neige, se déplace seul sur d\'immenses territoires, et évite soigneusement tout ce qui ressemble à un humain. Ni farouche ni agressif : simplement ailleurs.',
    t: { ind: 0.95, vig: 0.9, san: 0.85, thr: 0.7, rig: 0.75, soc: 0.05, inf: 0.05, nat: 0.75, det: 0.8, vsd: 0.85 } },
  { name: 'La loutre', tag: 'Le sérieux qui s\'amuse', color: '#a97142',
    desc: 'Elle fait des glissades sur la boue, jongle avec des cailloux, et dort en se tenant la patte pour ne pas dériver. Elle chasse très efficacement et consacre le reste de son temps à jouer, sans aucune culpabilité. La preuve vivante qu\'on peut être compétent et léger.',
    t: { vhe: 0.95, soc: 0.9, opt: 0.9, inf: 0.85, ouv: 0.8, emp: 0.75, col: 0.7, aud: 0.7, thr: 0.25, vac: 0.3 } },
  { name: 'Le hippocampe', tag: 'La fidélité discrète', color: '#e0983a',
    desc: 'C\'est le mâle qui porte les petits, et le couple se retrouve chaque matin pour une parade qui ne sert qu\'à se dire qu\'on est toujours là. Il s\'accroche à une algue avec sa queue et se laisse bercer, presque immobile, parfaitement camouflé. Fragile et constant.',
    t: { fia: 0.95, loy: 0.95, ste: 0.9, att: 0.9, care: 0.9, vbe: 0.9, thr: 0.7, com: 0.05, dom: 0.05, aud: 0.15 } },
  { name: 'Le flamant rose', tag: 'Le groupe et l\'allure', color: '#f28fb1',
    desc: 'Il ne vit qu\'en colonie, parade en groupes synchronisés, et tient debout sur une patte des heures durant avec une élégance improbable. Sa couleur lui vient entièrement de ce qu\'il mange : il devient littéralement ce qu\'il consomme. Très social, très conforme, très beau.',
    t: { col: 0.9, soc: 0.9, vco: 0.85, vac: 0.75, con: 0.75, ste: 0.8, ind: 0.15, com: 0.1, opn: 0.7, inf: 0.7 } },
  { name: 'Le héron', tag: 'L\'attente concentrée', color: '#6b8fa3',
    desc: 'Il reste debout dans l\'eau, immobile, parfois une demi-heure, jusqu\'à ce que le bon poisson passe à la bonne distance. Un seul coup, précis, et c\'est fini. Il ne partage ni son coin ni son repas, et il repart sans un bruit.',
    t: { san: 0.95, tmp: 0.85, rig: 0.85, ind: 0.9, vig: 0.85, det: 0.8, soc: 0.1, vst: 0.1, aud: 0.35, thr: 0.6 } },
  { name: 'Le bison', tag: 'La masse qui avance ensemble', color: '#6b4a32',
    desc: 'Face à la tempête, il ne fuit pas : il marche dedans, droit devant, pour la traverser plus vite. Le troupeau met les petits au centre et les adultes autour. Lourd, têtu, difficile à détourner de sa route une fois lancé.',
    t: { col: 0.9, det: 0.95, opn: 0.9, com: 0.8, att: 0.85, fia: 0.85, care: 0.8, aud: 0.75, dip: 0.2, ouv: 0.25 } },
  { name: 'La chèvre', tag: 'L\'indiscipline curieuse', color: '#b0a08a',
    desc: 'Elle monte sur tout ce qui dépasse, goûte tout ce qui traîne, et sort du parc quel que soit le parc. Impossible à diriger, très attachante, avec un sens de l\'équilibre absurde et une propension aux idées douteuses. Elle n\'obéit pas, elle négocie.',
    t: { ind: 0.9, vsd: 0.9, aud: 0.85, ouv: 0.85, vco: 0.1, con: 0.1, lib: 0.9, vst: 0.8, soc: 0.6, ord: 0.15 } },
  { name: 'Le chameau', tag: 'L\'autonomie dans le désert', color: '#c9a227',
    desc: 'Il traverse ce que rien d\'autre ne traverse, sans boire, en portant une charge. Il râle, il crache, il est de mauvaise humeur — et il arrive. Il stocke, il économise, il endure : c\'est la résistance faite animal, et il ne remerciera personne.',
    t: { det: 0.95, ste: 0.9, vse: 0.85, tmp: 0.85, fia: 0.9, ind: 0.8, com: 0.6, san: 0.8, vhe: 0.15, soc: 0.2 } },
  { name: 'Le pangolin', tag: 'La carapace timide', color: '#a08a5b',
    desc: 'Couvert d\'écailles de la tête à la queue, il se roule en boule si serrée qu\'aucun prédateur ne peut l\'ouvrir. Il vit seul, sort la nuit, n\'a ni dents ni agressivité. Sa seule stratégie est de se refermer, et elle a très bien marché jusqu\'à ce que nous arrivions.',
    t: { thr: 0.95, ind: 0.9, ste: 0.85, vse: 0.85, soc: 0.05, com: 0.05, dom: 0.05, vig: 0.8, aud: 0.1, nat: 0.75 } },
  { name: 'Le caméléon', tag: 'L\'adaptation permanente', color: '#5fa860',
    desc: 'Il change de couleur selon l\'humeur, la température et ce qu\'il veut dire aux autres. Ses deux yeux bougent indépendamment, donc il regarde deux endroits à la fois. Il avance très lentement, en se balançant, et sa langue part plus vite que le regard.',
    t: { ouv: 0.85, aff: 0.75, vig: 0.9, san: 0.8, ind: 0.8, chg: 0.75, dip: 0.7, inc: 0.8, com: 0.15, soc: 0.2 } },
  { name: 'L\'oie', tag: 'La gardienne bruyante', color: '#a1907a',
    desc: 'Elle voit tout, entend tout, et prévient tout le monde très fort. Elle vole en V en se relayant à la pointe pour économiser les autres, et reste avec le même partenaire toute sa vie. Elle n\'a peur de rien et elle a mauvais caractère.',
    t: { vig: 0.9, com: 0.85, loy: 0.95, col: 0.85, fia: 0.9, att: 0.85, thr: 0.75, dip: 0.2, aud: 0.75, soc: 0.7 } },
  { name: 'Le lièvre', tag: 'La fuite en zigzag', color: '#b08968',
    desc: 'Il ne se cache pas, il court — plus vite et plus imprévisiblement que ce qui le poursuit. Solitaire, nerveux, toujours prêt à détaler, il dort les yeux ouverts. Sa vie entière est une question de réflexes et d\'anticipation.',
    t: { thr: 0.9, vig: 0.9, ind: 0.85, aud: 0.6, vst: 0.6, san: 0.2, ste: 0.15, col: 0.2, det: 0.6, opn: 0.3 } },
  { name: 'Le corail', tag: 'La lenteur qui bâtit des mondes', color: '#f2766a',
    desc: 'Chaque individu est minuscule et ne fait presque rien ; ensemble, sur des milliers d\'années, ils construisent la plus grande structure vivante de la planète. Il ne bouge pas, ne décide rien seul, et abrite un quart de la vie marine. Fragile au moindre degré de trop.',
    t: { col: 0.98, tmp: 0.95, ste: 0.95, opn: 0.95, care: 0.85, ind: 0.05, dom: 0.05, aud: 0.05, vun: 0.85, cmp: 0.05 } },
  { name: 'Le faucon pèlerin', tag: 'La précision à trois cents à l\'heure', color: '#7a6a4a',
    desc: 'C\'est l\'animal le plus rapide de la planète en piqué, et il touche sa cible en plein vol. Rien n\'est laissé au hasard : l\'altitude, l\'angle, le moment. Il niche aujourd\'hui sur les cathédrales et les tours de bureaux, ce qui lui va plutôt bien.',
    t: { det: 0.9, rig: 0.9, aud: 0.9, vac: 0.85, ind: 0.85, san: 0.85, cmp: 0.85, aff: 0.75, soc: 0.15, ste: 0.15 } },
  { name: 'Le rat', tag: 'L\'adaptation à tout', color: '#7d7368',
    desc: 'On a tout essayé contre lui et il est toujours là, sur tous les continents, dans toutes les villes. Il apprend des erreurs des autres, se méfie de la nouveauté puis l\'essaie quand même, et vit en groupes solidaires qui s\'entraident réellement. Beaucoup plus futé et social que sa réputation.',
    t: { ouv: 0.9, aud: 0.8, vst: 0.8, col: 0.75, nat: 0.75, vig: 0.85, ind: 0.7, inc: 0.8, vco: 0.15, vac: 0.4 } },
  { name: 'La chauve-souris', tag: 'S\'orienter dans le noir', color: '#4a4159',
    desc: 'Elle se repère en écoutant l\'écho de ses propres cris, ce qui lui permet d\'attraper un moustique dans l\'obscurité totale. Elle dort par milliers dans la même grotte, tête en bas, et certaines partagent leur repas avec celles qui n\'ont rien trouvé. Nocturne, grégaire, incomprise.',
    t: { vig: 0.9, col: 0.85, opn: 0.85, aff: 0.75, care: 0.75, thr: 0.7, soc: 0.6, ste: 0.7, com: 0.15, inf: 0.2 } },
  { name: 'Le cygne', tag: 'La grâce et le caractère', color: '#8c99a8',
    desc: 'Il glisse sans effort apparent, pendant que ses pattes pédalent furieusement sous la surface. Fidèle au même partenaire pendant des années, il défend son territoire avec une agressivité que son allure ne laisse pas deviner. Beau, conscient de l\'être, et pas commode.',
    t: { vac: 0.85, rig: 0.8, loy: 0.9, att: 0.85, dom: 0.75, com: 0.7, dip: 0.4, con: 0.7, soc: 0.35, san: 0.7 } },
  { name: 'Le pélican', tag: 'Celui qui nourrit', color: '#c19a4a',
    desc: 'Il pêche en groupe, en formant un demi-cercle qui rabat les poissons, et partage ce qu\'il rapporte. Sa poche lui sert autant à attraper qu\'à donner. Il a l\'air d\'un animal mal dessiné et se révèle un planeur remarquable au ras des vagues.',
    t: { col: 0.9, care: 0.9, vbe: 0.9, emp: 0.8, fia: 0.85, soc: 0.75, dip: 0.75, cmp: 0.15, dom: 0.3, vpo: 0.1 } },
  { name: 'Le zèbre', tag: 'Se fondre dans le nombre', color: '#4a4a52',
    desc: 'Ses rayures ne servent pas à se cacher dans l\'herbe mais à brouiller les contours quand le troupeau s\'enfuit : impossible de viser un individu. Il dort à tour de rôle, en gardant toujours quelqu\'un éveillé. Nerveux, solidaire, et il rue très fort.',
    t: { col: 0.9, vig: 0.9, thr: 0.85, loy: 0.8, soc: 0.7, aud: 0.55, ind: 0.2, com: 0.6, san: 0.3, att: 0.75 } },
  { name: 'La gazelle', tag: 'La légèreté aux aguets', color: '#d9b382',
    desc: 'Elle broute la tête levée une fois sur deux, prête à partir. Quand elle détecte un prédateur, elle bondit très haut sur place — une façon de lui dire qu\'elle l\'a vu et qu\'il peut aller voir ailleurs. Rapide, élégante, en tension permanente.',
    t: { thr: 0.9, vig: 0.95, aud: 0.65, col: 0.75, vst: 0.6, san: 0.25, com: 0.15, dom: 0.15, ste: 0.35, opt: 0.5 } },
  { name: 'Le rhinocéros', tag: 'Charger d\'abord', color: '#8a8f98',
    desc: 'Il voit très mal et charge tout ce qui bouge un peu trop près, par principe. Deux tonnes lancées sans hésitation, sur la foi d\'une information incomplète. Le reste du temps il est solitaire, placide, et il aime beaucoup la boue.',
    t: { com: 0.95, det: 0.9, ind: 0.85, opn: 0.9, thr: 0.8, dog: 0.85, dip: 0.05, ouv: 0.1, san: 0.35, aud: 0.85 } },
  { name: 'L\'hippopotame', tag: 'Le territoire d\'abord', color: '#8a6f7a',
    desc: 'Il passe ses journées dans l\'eau à ne rien faire et devient extrêmement dangereux dès qu\'on approche de son bout de rivière. Il ne prévient qu\'une fois, en ouvrant grand la gueule. Grégaire avec les siens, intraitable avec tous les autres.',
    t: { dom: 0.9, com: 0.9, att: 0.9, thr: 0.8, col: 0.7, opn: 0.85, care: 0.7, dip: 0.1, ouv: 0.15, vhe: 0.7 } },
  { name: 'La hyène', tag: 'L\'efficacité mal-aimée', color: '#9a8250',
    desc: 'On la croit charognarde alors qu\'elle chasse l\'essentiel de ce qu\'elle mange, en groupes coordonnés dirigés par les femelles. Elle a une hiérarchie complexe, une mâchoire qui broie l\'os, et un rire qui est en réalité un signal social. Mauvaise réputation, excellentes compétences.',
    t: { col: 0.85, cmp: 0.9, det: 0.9, nat: 0.85, aff: 0.75, lea: 0.7, dom: 0.8, ide: 0.15, dip: 0.2, vac: 0.75 } },
  { name: 'Le koala', tag: 'L\'économie d\'énergie', color: '#8c9196',
    desc: 'Il dort vingt heures par jour et passe les quatre autres à manger des feuilles à peine digestes. Il ne s\'intéresse pas beaucoup à ses congénères et encore moins au reste du monde. Ce n\'est pas de la paresse : c\'est le seul régime possible avec un carburant pareil.',
    t: { ste: 0.95, san: 0.85, ind: 0.8, opn: 0.9, eng: 0.1, vst: 0.05, com: 0.05, soc: 0.15, vse: 0.8, cmp: 0.05 } },
  { name: 'Le kangourou', tag: 'Avancer par bonds', color: '#b5734a',
    desc: 'Il ne sait pas reculer et il avance par sauts, en économisant une énergie folle grâce à l\'élasticité de ses tendons. Il transporte les siens avec lui, met les combats en scène en boxant debout, et peut mettre sa gestation en pause si les conditions sont mauvaises.',
    t: { det: 0.85, aud: 0.8, col: 0.75, com: 0.75, att: 0.8, ste: 0.6, chg: 0.7, cmp: 0.7, ord: 0.3, tmp: 0.6 } },
  { name: 'L\'araignée', tag: 'Le piège patient', color: '#5b5468',
    desc: 'Elle passe la nuit à construire une géométrie parfaite, puis elle attend au centre sans bouger, en écoutant les vibrations. Si on détruit sa toile, elle en refait une le lendemain. Méthodique, solitaire, et capable de rester immobile très longtemps.',
    t: { rig: 0.95, ord: 0.9, tmp: 0.85, ind: 0.95, san: 0.85, det: 0.9, thr: 0.6, con: 0.85, soc: 0.05, inf: 0.05 } },
  { name: 'La mante religieuse', tag: 'L\'immobilité fatale', color: '#8fbf6a',
    desc: 'Elle se tient parfaitement immobile, les pattes repliées, et ressemble à une brindille jusqu\'au moment où ce n\'est plus une brindille. Elle frappe en une fraction de seconde. Aucune émotion visible, aucune hésitation, aucune pitié — y compris envers ses partenaires.',
    t: { san: 0.98, rig: 0.9, thr: 0.8, ind: 0.95, det: 0.9, cmp: 0.85, emp: 0.05, care: 0.05, soc: 0.05, dip: 0.1 } },
  { name: 'La luciole', tag: 'Le signal dans la nuit', color: '#c2a326',
    desc: 'Elle produit sa propre lumière, sans chaleur, uniquement pour être vue de ceux qu\'elle cherche. Dans certaines forêts, des milliers d\'individus finissent par clignoter en même temps sans chef d\'orchestre. Discrète le jour, impossible à ignorer la nuit.',
    t: { inf: 0.9, soc: 0.85, opt: 0.85, ide: 0.8, col: 0.8, vst: 0.7, emp: 0.75, com: 0.1, dom: 0.15, vpo: 0.1 } },
  { name: 'Le serpent', tag: 'Le calcul à froid', color: '#6a8f5f',
    desc: 'Il ne dépense rien inutilement : il attend, il sent, il évalue, et il n\'agit qu\'une fois. Il n\'a ni paupières ni expressions, ce qui le rend impossible à lire. Il change de peau entièrement quand la précédente ne lui va plus, et repart comme si de rien n\'était.',
    t: { san: 0.95, aff: 0.85, ind: 0.9, tmp: 0.8, nat: 0.85, chg: 0.7, det: 0.8, emp: 0.15, soc: 0.05, dip: 0.25 } },
  { name: 'Le cerf', tag: 'Le prestige et le combat', color: '#8b5e3c',
    desc: 'Il porte chaque année une couronne qu\'il perd et refait plus grande, et passe la saison du brame à crier pour impressionner sans avoir à se battre. Quand le bluff échoue, les bois s\'entrechoquent pour de bon. Le reste de l\'année, il est étonnamment discret.',
    t: { vac: 0.9, cmp: 0.9, dom: 0.8, com: 0.75, att: 0.8, opn: 0.8, vpo: 0.75, vig: 0.75, dip: 0.25, ste: 0.3 } },
  { name: 'Le sanglier', tag: 'Le groupe têtu', color: '#5e5145',
    desc: 'Il fonce en ligne droite à travers les fourrés, retourne des hectares de terre pour trouver ce qu\'il cherche, et ne se laisse pas impressionner. La laie protège ses marcassins avec une agressivité totale. Omnivore, opportuniste, et absolument impossible à déloger.',
    t: { det: 0.95, com: 0.9, col: 0.8, opn: 0.9, aud: 0.85, care: 0.8, thr: 0.6, ouv: 0.5, dip: 0.15, ord: 0.2 } },
  { name: 'Le renne', tag: 'La longue marche', color: '#9a9c8f',
    desc: 'Il parcourt plusieurs milliers de kilomètres par an, en troupeau, sur le même itinéraire que ses ancêtres. Il creuse la neige pour trouver du lichen et voit les ultraviolets, ce qui lui permet de distinguer le sol dans le blanc total. Endurant, collectif, fidèle à la route.',
    t: { col: 0.9, det: 0.9, tmp: 0.85, opn: 0.8, vtr: 0.85, fia: 0.9, ste: 0.85, vig: 0.75, com: 0.2, vst: 0.25 } },
];

window.PRISME_ANIMALS = { ANIMALS };
