/* ============================================================
   PRISME — « Quel animal serais-tu ? »
   ------------------------------------------------------------
   Même principe que les personnages : chaque animal est décrit par
   des cibles de 0 à 1 sur les mêmes dimensions que le test.
     qualités  : fia det emp ouv ind lea san dip aud rig opt vig soc com ide att
     DISC      : dom inf ste con
     valeurs   : vsd vst vhe vac vpo vse vco vtr vbe vun
     morale    : care fair loy auth sanc lib
     traits    : inc dog eng
     axes (1 = pôle droit) : aff (tête) loc (porté) rsk (audacieux) ord (structuré) thr (vigilant)
                 col (collectiviste) tmp (long terme) cmp (compétitif) opn (enraciné)
   La liste est volontairement longue : dans un cercle, chacun doit pouvoir
   recevoir un animal différent. Un animal = 8 traits ou plus.
   ============================================================ */
const ANIMALS = [
  { name: 'Le lion', tag: 'L\'autorité tranquille', color: '#d98a00', cat: 'Mammifères',
    desc: 'Il ne court pas après grand-chose : il tient un territoire et il se fait respecter sans avoir à le prouver tous les jours. Il délègue beaucoup, dort énormément, et se lève quand la situation l\'exige vraiment. Sa présence suffit à organiser tout ce qui l\'entoure.',
    t: { dom: 0.95, lea: 0.9, san: 0.85, att: 0.8, vpo: 0.85, auth: 0.8, det: 0.75, col: 0.6, rig: 0.3, soc: 0.5 } },
  { name: 'Le tigre', tag: 'La puissance solitaire', color: '#e2721c', cat: 'Mammifères',
    desc: 'Il chasse seul, vit seul et n\'a besoin de l\'approbation de personne. Patient jusqu\'à l\'immobilité puis foudroyant, il choisit son moment et ne le rate pas. Il ne cherche pas le conflit, mais il ne recule devant aucun — et il préfère qu\'on le laisse tranquille.',
    t: { ind: 0.95, det: 0.9, san: 0.9, dom: 0.85, cmp: 0.8, vsd: 0.85, aud: 0.8, soc: 0.1, col: 0.1, dip: 0.2 } },
  { name: 'Le loup', tag: 'La meute avant soi', color: '#5c7fa3', cat: 'Mammifères',
    desc: 'Il est puissant seul et invincible à plusieurs, et il le sait. Toute son organisation repose sur des liens : qui protège qui, qui chasse avec qui, qui nourrit les petits. Sa loyauté est absolue envers les siens et inexistante envers le reste du monde.',
    t: { loy: 0.95, col: 0.9, att: 0.9, fia: 0.85, lea: 0.75, det: 0.85, vig: 0.75, nat: 0.7, emp: 0.6, soc: 0.6 } },
  { name: 'L\'aigle', tag: 'La vue d\'en haut', color: '#7a6033', cat: 'Oiseaux',
    desc: 'Il prend de la hauteur, littéralement : de là où il se tient, il voit ce que personne d\'autre ne distingue. Il attend longtemps, plane sans effort, puis fond d\'un coup avec une précision qui ne laisse aucune chance. Solitaire, exigeant, pas particulièrement chaleureux.',
    t: { aff: 0.9, vig: 0.9, ind: 0.85, tmp: 0.85, san: 0.85, det: 0.85, rig: 0.8, vac: 0.75, soc: 0.15, emp: 0.25 } },
  { name: 'L\'ours', tag: 'Le calme qu\'il ne faut pas réveiller', color: '#7d4f2a', cat: 'Mammifères',
    desc: 'Il vit sa vie, mange, dort, ne cherche d\'ennui à personne. On le prend souvent pour un gros nounours pataud, ce qui est une erreur : le jour où on touche à ce qui lui appartient, la transformation est totale et personne ne reste pour discuter. Le reste du temps, il est d\'une tranquillité absolue.',
    t: { san: 0.85, att: 0.9, ind: 0.8, com: 0.75, fia: 0.8, vse: 0.7, opn: 0.85, care: 0.7, soc: 0.2, dip: 0.35 } },
  { name: 'L\'éléphant', tag: 'La mémoire du groupe', color: '#65606d', cat: 'Mammifères',
    desc: 'Il n\'oublie rien : ni les points d\'eau, ni les routes, ni ceux qui lui ont fait du mal. C\'est la matriarche qui guide, et le troupeau lui fait confiance parce qu\'elle a déjà vu passer trente saisons sèches. Il porte les siens, veille sur les petits, et s\'arrête devant ses morts.',
    t: { tmp: 0.95, att: 0.95, col: 0.9, loy: 0.9, emp: 0.85, fia: 0.9, care: 0.85, vtr: 0.85, san: 0.8, aud: 0.3 } },
  { name: 'Le dauphin', tag: 'L\'intelligence joyeuse', color: '#1c86c9', cat: 'Mers et océans',
    desc: 'Il joue, il communique, il invente des techniques de chasse que personne ne lui a apprises. Curieux de tout, y compris de nous, il vient voir ce qui se passe au lieu de fuir. Sa vie sociale est dense et compliquée, et il a visiblement de l\'humour.',
    t: { soc: 0.95, inf: 0.9, ouv: 0.9, opt: 0.9, vst: 0.85, col: 0.8, emp: 0.8, vhe: 0.8, aff: 0.6, thr: 0.2 } },
  { name: 'Le renard', tag: 'La ruse discrète', color: '#e2582c', cat: 'Mammifères',
    desc: 'Il ne gagne jamais par la force, alors il gagne autrement : en observant, en contournant, en trouvant l\'ouverture que personne n\'a vue. Il s\'adapte à tout, ville comprise, et il a un talent particulier pour s\'en sortir dans des situations impossibles. On ne sait jamais tout à fait ce qu\'il prépare.',
    t: { aff: 0.85, ind: 0.9, vsd: 0.85, ouv: 0.85, aud: 0.75, nat: 0.7, vst: 0.7, san: 0.7, con: 0.2, col: 0.15 } },
  { name: 'Le hibou', tag: 'Celui qui veille pendant que tout dort', color: '#6a3fa0', cat: 'Oiseaux',
    desc: 'Il est là quand les autres dorment, immobile, à écouter des choses inaudibles. Il ne se presse jamais et ne parle presque pas, ce qui lui vaut une réputation de sagesse qu\'il n\'a jamais revendiquée. Quand il se déplace, c\'est sans un bruit.',
    t: { aff: 0.85, vig: 0.9, san: 0.9, tmp: 0.8, ind: 0.8, rig: 0.75, thr: 0.7, soc: 0.15, inf: 0.1, opt: 0.4 } },
  { name: 'Le corbeau', tag: 'L\'esprit curieux', color: '#46596b', cat: 'Oiseaux',
    desc: 'Il fabrique des outils, résout des énigmes, reconnaît les visages et se souvient de qui l\'a mal traité pendant des années. Il joue pour le plaisir de jouer, se moque du monde, et vole des choses brillantes dont il n\'a aucun usage. Une intelligence qui s\'ennuie vite.',
    t: { ouv: 0.95, aff: 0.85, vst: 0.85, ind: 0.85, vsd: 0.8, nat: 0.7, aud: 0.7, soc: 0.5, vco: 0.15, con: 0.2 } },
  { name: 'Le chat', tag: 'L\'indépendance revendiquée', color: '#b87900', cat: 'Mammifères',
    desc: 'Il vient quand il veut, s\'en va quand il veut, et accepte l\'affection à ses conditions. Il a gardé quelque chose de sauvage malgré des milliers d\'années de vie commune avec nous. Il s\'attache réellement — simplement, il refuse catégoriquement d\'en faire la démonstration.',
    t: { ind: 0.95, vsd: 0.95, san: 0.8, lib: 0.9, vhe: 0.75, att: 0.6, col: 0.1, vco: 0.1, soc: 0.3, dom: 0.4 } },
  { name: 'Le chien', tag: 'La fidélité sans condition', color: '#c2850c', cat: 'Mammifères',
    desc: 'Il te choisit une fois et c\'est pour toujours. Il sent quand ça ne va pas, vient se poser contre toi sans rien demander, et fait la fête comme au premier jour à chaque retour. Sa confiance est totale, sa rancune inexistante, et sa joie franchement contagieuse.',
    t: { loy: 0.98, fia: 0.95, att: 0.95, emp: 0.9, vbe: 0.9, opt: 0.9, col: 0.85, soc: 0.85, nat: 0.05, ind: 0.15 } },
  { name: 'Le cheval', tag: 'La liberté en mouvement', color: '#a0522d', cat: 'Mammifères',
    desc: 'Il a besoin d\'espace et il le fait savoir. Sensible au point de sentir une hésitation dans une main posée sur son encolure, il accorde sa confiance lentement et ne la reprend pas. Il vit en groupe, fuit d\'abord, et ne se bat que lorsqu\'il n\'y a plus d\'issue.',
    t: { lib: 0.9, vsd: 0.85, emp: 0.8, soc: 0.75, col: 0.7, aud: 0.65, thr: 0.65, att: 0.75, dom: 0.35, com: 0.3 } },
  { name: 'Le castor', tag: 'Le bâtisseur obstiné', color: '#8a6a2f', cat: 'Mammifères',
    desc: 'Il entend l\'eau couler et il ne peut pas s\'en empêcher : il faut construire. Nuit après nuit, il abat, transporte, empile, colmate, et transforme un ruisseau en étang. Son œuvre profite à des dizaines d\'espèces qui ne lui ont rien demandé, et il recommence dès qu\'une brèche apparaît.',
    t: { det: 0.95, ord: 0.9, fia: 0.9, rig: 0.85, opn: 0.9, tmp: 0.85, con: 0.85, col: 0.7, vst: 0.15, soc: 0.35 } },
  { name: 'La tortue', tag: 'Le temps long', color: '#57a639', cat: 'Reptiles et amphibiens',
    desc: 'Elle avance lentement et elle arrive. Rien ne la presse, rien ne l\'affole : elle transporte sa maison, rentre la tête quand ça chauffe, et ressort quand c\'est passé. Elle vivra probablement plus longtemps que la plupart de ceux qui se sont moqués de son allure.',
    t: { ste: 0.95, san: 0.95, tmp: 0.9, vse: 0.9, opn: 0.85, thr: 0.7, det: 0.75, aud: 0.1, com: 0.1, vst: 0.05 } },
  { name: 'L\'abeille', tag: 'Le travail collectif', color: '#e9a100', cat: 'Insectes et petites bêtes',
    desc: 'Elle ne fait rien pour elle-même. Tout ce qu\'elle butine, construit et défend appartient à la ruche, et elle danse pour indiquer aux autres où se trouve la nourriture qu\'elle a découverte. Organisée, infatigable, elle meurt en piquant celui qui menace la colonie.',
    t: { col: 0.98, ord: 0.95, con: 0.9, vco: 0.9, fia: 0.95, det: 0.9, loy: 0.9, ind: 0.05, vsd: 0.05, soc: 0.6 } },
  { name: 'La fourmi', tag: 'La ténacité sans bruit', color: '#7a4a2a', cat: 'Insectes et petites bêtes',
    desc: 'Elle porte cinquante fois son poids, franchit des obstacles absurdes et recommence si on détruit son travail. Elle ne discute pas la tâche qu\'on lui a confiée et ne réclame aucune reconnaissance. Une colonie entière tient par l\'addition de ces obstinations minuscules.',
    t: { det: 0.95, ord: 0.9, col: 0.95, fia: 0.9, con: 0.85, eng: 0.85, tmp: 0.8, vco: 0.8, soc: 0.3, inf: 0.1 } },
  { name: 'Le suricate', tag: 'La sentinelle du groupe', color: '#d98a00', cat: 'Mammifères',
    desc: 'Pendant que la famille creuse et mange, il se dresse sur ses pattes arrière et scrute le ciel. Il donne l\'alerte au premier point noir, et tout le monde plonge. Il prend ce tour de garde sans qu\'on le lui demande, et il le rend à un autre quand vient son tour de manger.',
    t: { vig: 0.95, thr: 0.9, col: 0.9, fia: 0.9, soc: 0.8, care: 0.8, loy: 0.85, san: 0.4, aud: 0.35, opt: 0.4 } },
  { name: 'Le manchot empereur', tag: 'L\'endurance partagée', color: '#3d3946', cat: 'Oiseaux',
    desc: 'Il traverse l\'hiver le plus dur de la planète en se serrant contre les autres, et chacun prend son tour à l\'extérieur du groupe. Il reste des semaines sans manger, un œuf posé sur les pattes, à attendre. Ce n\'est pas de l\'héroïsme : c\'est une patience organisée que rien ne décourage.',
    t: { col: 0.95, ste: 0.9, fia: 0.95, det: 0.9, loy: 0.9, care: 0.85, vco: 0.8, tmp: 0.8, cmp: 0.1, com: 0.1 } },
  { name: 'Le guépard', tag: 'Tout ou rien, très vite', color: '#e08700', cat: 'Mammifères',
    desc: 'Il est l\'animal le plus rapide du monde pendant vingt secondes, après quoi il est épuisé et doit renoncer. Il mise tout sur une accélération et n\'a pas droit à l\'erreur. Fragile, nerveux, il perd souvent sa prise face à plus costaud — mais sur ces vingt secondes, personne ne le rattrape.',
    t: { aud: 0.95, rsk: 0.9, det: 0.85, vst: 0.8, cmp: 0.8, tmp: 0.15, ste: 0.1, san: 0.3, thr: 0.65, ord: 0.3 } },
  { name: 'Le requin', tag: 'Avancer ou couler', color: '#46596b', cat: 'Mers et océans',
    desc: 'Il n\'a pas le choix : s\'il s\'arrête, il coule. Alors il avance, en permanence, depuis quatre cents millions d\'années. Il n\'est pas cruel, il est efficace — un système de détection redoutable au service d\'un seul objectif. On le craint plus qu\'il ne mérite, et on le chasse bien plus qu\'il ne nous chasse.',
    t: { det: 0.95, cmp: 0.9, ind: 0.9, san: 0.9, nat: 0.85, vig: 0.85, dom: 0.8, emp: 0.15, soc: 0.1, dip: 0.15 } },
  { name: 'Le crocodile', tag: 'La patience immobile', color: '#4f7942', cat: 'Reptiles et amphibiens',
    desc: 'Il peut rester des heures sans bouger, presque entièrement sous l\'eau, à attendre. Il ne dépense rien, ne s\'impatiente jamais, et frappe une seule fois. C\'est l\'un des plus vieux modèles encore en service : il n\'a pas eu besoin de changer.',
    t: { san: 0.98, tmp: 0.9, thr: 0.85, det: 0.9, ind: 0.85, opn: 0.9, vig: 0.85, soc: 0.05, inf: 0.05, vst: 0.05 } },
  { name: 'La panthère noire', tag: 'L\'élégance qu\'on ne voit pas venir', color: '#2b2740', cat: 'Mammifères',
    desc: 'Elle se déplace dans l\'ombre sans faire de bruit, et on ne la remarque que lorsqu\'elle a décidé d\'être vue. Discrète jusqu\'à l\'invisibilité, précise, économe de ses gestes, elle n\'a rien à démontrer à personne. Sa réputation fait le travail à sa place.',
    t: { ind: 0.9, san: 0.95, rig: 0.8, det: 0.85, vig: 0.85, aff: 0.75, dom: 0.7, soc: 0.1, inf: 0.1, vac: 0.6 } },
  { name: 'L\'orque', tag: 'La stratégie en famille', color: '#1a1722', cat: 'Mers et océans',
    desc: 'Elle chasse en groupe avec des techniques transmises de génération en génération, différentes d\'une famille à l\'autre — une culture, au sens propre. Les filles restent avec leur mère toute leur vie. Extrêmement intelligente, coordonnée, et sans concurrent sérieux dans l\'océan.',
    t: { aff: 0.9, col: 0.9, lea: 0.85, det: 0.9, loy: 0.9, tmp: 0.85, cmp: 0.8, att: 0.85, rig: 0.75, emp: 0.6 } },
  { name: 'La baleine', tag: 'L\'immensité paisible', color: '#1f7a8c', cat: 'Mers et océans',
    desc: 'Elle traverse des océans entiers en chantant des mélodies que ses semblables entendent à des centaines de kilomètres. Elle est colossale et ne mange presque que des choses minuscules. Rien ne semble l\'agiter : elle est à une autre échelle de temps et d\'espace que le reste du monde.',
    t: { san: 0.95, tmp: 0.9, vun: 0.9, emp: 0.8, ste: 0.9, col: 0.7, care: 0.8, cmp: 0.1, com: 0.1, aud: 0.3 } },
  { name: 'Le poulpe', tag: 'L\'ingéniosité sans os', color: '#9b5de5', cat: 'Mers et océans',
    desc: 'Il ouvre des bocaux, s\'échappe par des trous de la taille de son œil, change de couleur et de texture en une seconde. Chacun de ses bras réfléchit un peu tout seul. Solitaire, curieux, joueur : c\'est probablement l\'intelligence la plus étrangère à la nôtre qu\'on puisse croiser.',
    t: { ouv: 0.95, ind: 0.95, aff: 0.85, vsd: 0.9, vst: 0.85, aud: 0.75, inc: 0.85, soc: 0.1, col: 0.1, ord: 0.25 } },
  { name: 'Le hérisson', tag: 'La boule de piquants', color: '#8a6a2f', cat: 'Mammifères',
    desc: 'Il n\'attaque jamais. Au moindre doute il se roule en boule et attend que ça passe, ce qui marche remarquablement bien. Il sort la nuit, vaque à ses affaires, et n\'a d\'histoires avec personne. Sa défense n\'est pas de la méchanceté, c\'est de la prudence à l\'état pur.',
    t: { thr: 0.95, vse: 0.85, ind: 0.85, vig: 0.85, ste: 0.7, com: 0.1, aud: 0.15, dom: 0.1, soc: 0.15, nat: 0.7 } },
  { name: 'L\'écureuil', tag: 'L\'anticipation nerveuse', color: '#c2670c', cat: 'Mammifères',
    desc: 'Il passe l\'automne à cacher des milliers de provisions à des endroits qu\'il oubliera en partie — et les glands oubliés deviendront des chênes. Toujours en alerte, toujours en mouvement, il ne tient pas en place plus de trois secondes. Sa prévoyance frôle l\'angoisse, et elle marche.',
    t: { thr: 0.9, vse: 0.85, ord: 0.75, vig: 0.85, vst: 0.7, aud: 0.6, ind: 0.7, san: 0.15, ste: 0.15, tmp: 0.75 } },
  { name: 'Le blaireau', tag: 'Le bourru qui ne lâche rien', color: '#4a4a52', cat: 'Mammifères',
    desc: 'Il creuse des terriers immenses, occupés par la même famille pendant des générations. Peu sociable, franchement grognon, il ne cherche pas la bagarre mais ne recule devant aucune — y compris face à beaucoup plus gros que lui. Le genre à mourir sur place plutôt qu\'à céder.',
    t: { com: 0.9, ind: 0.85, opn: 0.95, det: 0.9, thr: 0.7, att: 0.8, vtr: 0.8, dip: 0.1, soc: 0.15, aud: 0.75 } },
  { name: 'Le papillon', tag: 'La métamorphose', color: '#e05fa0', cat: 'Insectes et petites bêtes',
    desc: 'Il a passé une vie entière à ramper, puis s\'est enfermé, puis il est ressorti entièrement autre. Sa forme actuelle ne dure que quelques semaines, qu\'il passe à voler de fleur en fleur sans se poser longtemps. Léger, éphémère, et complètement transformé par rapport à ce qu\'il était.',
    t: { chg: 0.9, vst: 0.9, vhe: 0.85, ouv: 0.85, opt: 0.8, loc: 0.6, ord: 0.1, tmp: 0.15, opn: 0.1, eng: 0.3 } },
  { name: 'Le colibri', tag: 'L\'énergie concentrée', color: '#2ec4b6', cat: 'Oiseaux',
    desc: 'Il bat des ailes cinquante fois par seconde, vole en marche arrière, et doit manger presque en permanence pour ne pas s\'éteindre. Minuscule et étonnamment agressif, il chasse des oiseaux trois fois plus gros de son parterre de fleurs. Une pile électrique avec un caractère.',
    t: { vst: 0.95, aud: 0.85, com: 0.8, inf: 0.8, soc: 0.6, cmp: 0.8, det: 0.75, ste: 0.05, san: 0.15, tmp: 0.1 } },
  { name: 'L\'albatros', tag: 'Le voyageur des grands espaces', color: '#4dc9ff', cat: 'Oiseaux',
    desc: 'Il plane pendant des jours sans battre des ailes, parcourt des milliers de kilomètres au-dessus d\'un océan vide, et ne revient à terre que pour retrouver le même partenaire, année après année. Ridicule et maladroit sur le sol ; magistral dès qu\'il décolle.',
    t: { ind: 0.9, tmp: 0.85, san: 0.9, loy: 0.9, opn: 0.15, vst: 0.7, fia: 0.85, soc: 0.2, com: 0.1, aud: 0.7 } },
  { name: 'La girafe', tag: 'La douceur qui domine',
    color: '#d9a441', cat: 'Mammifères',
    desc: 'Elle voit tout de très haut, sans avoir besoin de se mêler de quoi que ce soit. Silencieuse presque tout le temps, calme, elle règle les rares conflits par un combat de cous étrangement lent et élégant. Elle dort deux heures par nuit et personne ne sait vraiment à quoi elle pense.',
    t: { san: 0.9, dip: 0.85, vig: 0.8, tmp: 0.7, emp: 0.65, ste: 0.8, com: 0.15, dom: 0.35, soc: 0.5, aud: 0.35 } },
  { name: 'Le gorille', tag: 'La force qui protège', color: '#3d3946', cat: 'Mammifères',
    desc: 'Le dos argenté décide, arbitre, et se met devant quand le danger arrive. Il se frappe la poitrine pour éviter d\'avoir à se battre — c\'est un avertissement, pas une déclaration de guerre. Végétarien, paisible, et absolument redoutable si on insiste.',
    t: { dom: 0.9, care: 0.9, att: 0.9, lea: 0.85, san: 0.85, col: 0.85, fia: 0.9, auth: 0.8, com: 0.45, vst: 0.2 } },
  { name: 'Le chimpanzé', tag: 'La politique permanente', color: '#7a4a2a', cat: 'Mammifères',
    desc: 'Il vit dans un groupe où tout est question d\'alliances, de services rendus et de coups montés. Il se réconcilie après les disputes, tient les comptes, et sait exactement qui soutient qui. Curieux, bricoleur, imprévisible : c\'est celui qui nous ressemble le plus, pour le meilleur et pour le pire.',
    t: { soc: 0.85, cmp: 0.85, com: 0.8, ouv: 0.85, col: 0.75, inf: 0.8, aff: 0.7, dom: 0.7, vpo: 0.75, ste: 0.2 } },
  { name: 'Le bonobo', tag: 'Régler par le lien', color: '#e2569b', cat: 'Mammifères',
    desc: 'Chez lui, les tensions se dénouent par le contact et l\'affection plutôt que par la violence. Les femelles décident, les conflits s\'éteignent vite, et personne ne garde de rancune très longtemps. C\'est l\'exact cousin du précédent, avec un tout autre logiciel.',
    t: { dip: 0.95, emp: 0.9, care: 0.9, soc: 0.9, col: 0.85, cfl: 0.05, vhe: 0.8, com: 0.1, cmp: 0.15, opt: 0.8 } },
  { name: 'L\'orang-outan', tag: 'Le sage solitaire', color: '#c2670c', cat: 'Mammifères',
    desc: 'Il vit seul dans les arbres, se déplace lentement, réfléchit visiblement avant chaque mouvement. Il apprend en observant longuement, fabrique des outils, se construit un abri contre la pluie. Il n\'a besoin de personne et ne dérange personne.',
    t: { ind: 0.95, aff: 0.85, san: 0.9, tmp: 0.85, ouv: 0.8, rig: 0.7, soc: 0.1, com: 0.1, vsd: 0.9, ste: 0.75 } },
  { name: 'Le paresseux', tag: 'L\'art de ne pas se presser', color: '#8a9a5b', cat: 'Mammifères',
    desc: 'Il fait tout au ralenti, y compris digérer, et descend de son arbre une fois par semaine. Ce n\'est pas de la fainéantise : c\'est une stratégie d\'économie d\'énergie si efficace que des algues poussent sur son pelage et le camouflent. Il a l\'air de sourire en permanence.',
    t: { ste: 0.95, san: 0.95, vhe: 0.8, eng: 0.05, det: 0.15, cmp: 0.05, com: 0.05, opt: 0.7, aud: 0.1, tmp: 0.3 } },
  { name: 'Le raton laveur', tag: 'La curiosité sans scrupules', color: '#6b7280', cat: 'Mammifères',
    desc: 'Il ouvre tout ce qui s\'ouvre, fouille tout ce qui se fouille, et s\'est parfaitement adapté à nos poubelles. Ses mains sont d\'une dextérité déconcertante et il apprend très vite comment contourner un système censé le bloquer. Aucune honte, beaucoup d\'audace.',
    t: { ouv: 0.9, aud: 0.9, vst: 0.85, ind: 0.85, inf: 0.7, vco: 0.1, con: 0.1, ord: 0.2, nat: 0.6, vhe: 0.8 } },
  { name: 'Le bouquetin', tag: 'L\'équilibre sur le vide', color: '#8a8f98', cat: 'Mammifères',
    desc: 'Il grimpe des murs de barrage presque verticaux pour lécher du sel, avec un calme qui fait mal au ventre quand on le regarde. Il vit là où personne ne peut le suivre, et c\'est précisément le but. Sûr de son pied, autonome, peu impressionnable.',
    t: { aud: 0.9, rsk: 0.85, ind: 0.85, san: 0.85, det: 0.85, opn: 0.7, vsd: 0.8, thr: 0.35, soc: 0.35, dip: 0.4 } },
  { name: 'Le saumon', tag: 'Le retour, quoi qu\'il en coûte', color: '#e2582c', cat: 'Mers et océans',
    desc: 'Il remonte le courant, saute des cascades, traverse des rivières entières pour revenir exactement là où il est né. Rien ne l\'en détourne, et il y laisse sa vie. C\'est l\'obstination la plus pure du règne animal, au service d\'une seule idée : rentrer.',
    t: { det: 0.98, opn: 0.95, att: 0.9, eng: 0.9, vtr: 0.85, tmp: 0.8, aud: 0.8, san: 0.5, dip: 0.3, vhe: 0.15 } },
  { name: 'Le lynx', tag: 'La discrétion absolue', color: '#9a8c78', cat: 'Mammifères',
    desc: 'On peut vivre toute sa vie dans une forêt qu\'il habite sans jamais l\'apercevoir. Il entend une souris sous la neige, se déplace seul sur d\'immenses territoires, et évite soigneusement tout ce qui ressemble à un humain. Ni farouche ni agressif : simplement ailleurs.',
    t: { ind: 0.95, vig: 0.9, san: 0.85, thr: 0.7, rig: 0.75, soc: 0.05, inf: 0.05, nat: 0.75, det: 0.8, vsd: 0.85 } },
  { name: 'La loutre', tag: 'Le sérieux qui s\'amuse', color: '#a97142', cat: 'Mammifères',
    desc: 'Elle fait des glissades sur la boue, jongle avec des cailloux, et dort en se tenant la patte pour ne pas dériver. Elle chasse très efficacement et consacre le reste de son temps à jouer, sans aucune culpabilité. La preuve vivante qu\'on peut être compétent et léger.',
    t: { vhe: 0.95, soc: 0.9, opt: 0.9, inf: 0.85, ouv: 0.8, emp: 0.75, col: 0.7, aud: 0.7, thr: 0.25, vac: 0.3 } },
  { name: 'Le hippocampe', tag: 'La fidélité discrète', color: '#e0983a', cat: 'Mers et océans',
    desc: 'C\'est le mâle qui porte les petits, et le couple se retrouve chaque matin pour une parade qui ne sert qu\'à se dire qu\'on est toujours là. Il s\'accroche à une algue avec sa queue et se laisse bercer, presque immobile, parfaitement camouflé. Fragile et constant.',
    t: { fia: 0.95, loy: 0.95, ste: 0.9, att: 0.9, care: 0.9, vbe: 0.9, thr: 0.7, com: 0.05, dom: 0.05, aud: 0.15 } },
  { name: 'Le flamant rose', tag: 'Le groupe et l\'allure', color: '#f28fb1', cat: 'Oiseaux',
    desc: 'Il ne vit qu\'en colonie, parade en groupes synchronisés, et tient debout sur une patte des heures durant avec une élégance improbable. Sa couleur lui vient entièrement de ce qu\'il mange : il devient littéralement ce qu\'il consomme. Très social, très conforme, très beau.',
    t: { col: 0.9, soc: 0.9, vco: 0.85, vac: 0.75, con: 0.75, ste: 0.8, ind: 0.15, com: 0.1, opn: 0.7, inf: 0.7 } },
  { name: 'Le héron', tag: 'L\'attente concentrée', color: '#6b8fa3', cat: 'Oiseaux',
    desc: 'Il reste debout dans l\'eau, immobile, parfois une demi-heure, jusqu\'à ce que le bon poisson passe à la bonne distance. Un seul coup, précis, et c\'est fini. Il ne partage ni son coin ni son repas, et il repart sans un bruit.',
    t: { san: 0.95, tmp: 0.85, rig: 0.85, ind: 0.9, vig: 0.85, det: 0.8, soc: 0.1, vst: 0.1, aud: 0.35, thr: 0.6 } },
  { name: 'Le bison', tag: 'La masse qui avance ensemble', color: '#6b4a32', cat: 'Mammifères',
    desc: 'Face à la tempête, il ne fuit pas : il marche dedans, droit devant, pour la traverser plus vite. Le troupeau met les petits au centre et les adultes autour. Lourd, têtu, difficile à détourner de sa route une fois lancé.',
    t: { col: 0.9, det: 0.95, opn: 0.9, com: 0.8, att: 0.85, fia: 0.85, care: 0.8, aud: 0.75, dip: 0.2, ouv: 0.25 } },
  { name: 'La chèvre', tag: 'L\'indiscipline curieuse', color: '#b0a08a', cat: 'Mammifères',
    desc: 'Elle monte sur tout ce qui dépasse, goûte tout ce qui traîne, et sort du parc quel que soit le parc. Impossible à diriger, très attachante, avec un sens de l\'équilibre absurde et une propension aux idées douteuses. Elle n\'obéit pas, elle négocie.',
    t: { ind: 0.9, vsd: 0.9, aud: 0.85, ouv: 0.85, vco: 0.1, con: 0.1, lib: 0.9, vst: 0.8, soc: 0.6, ord: 0.15 } },
  { name: 'Le chameau', tag: 'L\'autonomie dans le désert', color: '#c9a227', cat: 'Mammifères',
    desc: 'Il traverse ce que rien d\'autre ne traverse, sans boire, en portant une charge. Il râle, il crache, il est de mauvaise humeur — et il arrive. Il stocke, il économise, il endure : c\'est la résistance faite animal, et il ne remerciera personne.',
    t: { det: 0.95, ste: 0.9, vse: 0.85, tmp: 0.85, fia: 0.9, ind: 0.8, com: 0.6, san: 0.8, vhe: 0.15, soc: 0.2 } },
  { name: 'Le pangolin', tag: 'La carapace timide', color: '#a08a5b', cat: 'Mammifères',
    desc: 'Couvert d\'écailles de la tête à la queue, il se roule en boule si serrée qu\'aucun prédateur ne peut l\'ouvrir. Il vit seul, sort la nuit, n\'a ni dents ni agressivité. Sa seule stratégie est de se refermer, et elle a très bien marché jusqu\'à ce que nous arrivions.',
    t: { thr: 0.95, ind: 0.9, ste: 0.85, vse: 0.85, soc: 0.05, com: 0.05, dom: 0.05, vig: 0.8, aud: 0.1, nat: 0.75 } },
  { name: 'Le caméléon', tag: 'L\'adaptation permanente', color: '#5fa860', cat: 'Reptiles et amphibiens',
    desc: 'Il change de couleur selon l\'humeur, la température et ce qu\'il veut dire aux autres. Ses deux yeux bougent indépendamment, donc il regarde deux endroits à la fois. Il avance très lentement, en se balançant, et sa langue part plus vite que le regard.',
    t: { ouv: 0.85, aff: 0.75, vig: 0.9, san: 0.8, ind: 0.8, chg: 0.75, dip: 0.7, inc: 0.8, com: 0.15, soc: 0.2 } },
  { name: 'L\'oie', tag: 'La gardienne bruyante', color: '#a1907a', cat: 'Oiseaux',
    desc: 'Elle voit tout, entend tout, et prévient tout le monde très fort. Elle vole en V en se relayant à la pointe pour économiser les autres, et reste avec le même partenaire toute sa vie. Elle n\'a peur de rien et elle a mauvais caractère.',
    t: { vig: 0.9, com: 0.85, loy: 0.95, col: 0.85, fia: 0.9, att: 0.85, thr: 0.75, dip: 0.2, aud: 0.75, soc: 0.7 } },
  { name: 'Le lièvre', tag: 'La fuite en zigzag', color: '#b08968', cat: 'Mammifères',
    desc: 'Il ne se cache pas, il court — plus vite et plus imprévisiblement que ce qui le poursuit. Solitaire, nerveux, toujours prêt à détaler, il dort les yeux ouverts. Sa vie entière est une question de réflexes et d\'anticipation.',
    t: { thr: 0.9, vig: 0.9, ind: 0.85, aud: 0.6, vst: 0.6, san: 0.2, ste: 0.15, col: 0.2, det: 0.6, opn: 0.3 } },
  { name: 'Le corail', tag: 'La lenteur qui bâtit des mondes', color: '#f2766a', cat: 'Mers et océans',
    desc: 'Chaque individu est minuscule et ne fait presque rien ; ensemble, sur des milliers d\'années, ils construisent la plus grande structure vivante de la planète. Il ne bouge pas, ne décide rien seul, et abrite un quart de la vie marine. Fragile au moindre degré de trop.',
    t: { col: 0.98, tmp: 0.95, ste: 0.95, opn: 0.95, care: 0.85, ind: 0.05, dom: 0.05, aud: 0.05, vun: 0.85, cmp: 0.05 } },
  { name: 'Le faucon pèlerin', tag: 'La précision à trois cents à l\'heure', color: '#7a6a4a', cat: 'Oiseaux',
    desc: 'C\'est l\'animal le plus rapide de la planète en piqué, et il touche sa cible en plein vol. Rien n\'est laissé au hasard : l\'altitude, l\'angle, le moment. Il niche aujourd\'hui sur les cathédrales et les tours de bureaux, ce qui lui va plutôt bien.',
    t: { det: 0.9, rig: 0.9, aud: 0.9, vac: 0.85, ind: 0.85, san: 0.85, cmp: 0.85, aff: 0.75, soc: 0.15, ste: 0.15 } },
  { name: 'Le rat', tag: 'L\'adaptation à tout', color: '#7d7368', cat: 'Mammifères',
    desc: 'On a tout essayé contre lui et il est toujours là, sur tous les continents, dans toutes les villes. Il apprend des erreurs des autres, se méfie de la nouveauté puis l\'essaie quand même, et vit en groupes solidaires qui s\'entraident réellement. Beaucoup plus futé et social que sa réputation.',
    t: { ouv: 0.9, aud: 0.8, vst: 0.8, col: 0.75, nat: 0.75, vig: 0.85, ind: 0.7, inc: 0.8, vco: 0.15, vac: 0.4 } },
  { name: 'La chauve-souris', tag: 'S\'orienter dans le noir', color: '#4a4159', cat: 'Mammifères',
    desc: 'Elle se repère en écoutant l\'écho de ses propres cris, ce qui lui permet d\'attraper un moustique dans l\'obscurité totale. Elle dort par milliers dans la même grotte, tête en bas, et certaines partagent leur repas avec celles qui n\'ont rien trouvé. Nocturne, grégaire, incomprise.',
    t: { vig: 0.9, col: 0.85, opn: 0.85, aff: 0.75, care: 0.75, thr: 0.7, soc: 0.6, ste: 0.7, com: 0.15, inf: 0.2 } },
  { name: 'Le cygne', tag: 'La grâce et le caractère', color: '#8c99a8', cat: 'Oiseaux',
    desc: 'Il glisse sans effort apparent, pendant que ses pattes pédalent furieusement sous la surface. Fidèle au même partenaire pendant des années, il défend son territoire avec une agressivité que son allure ne laisse pas deviner. Beau, conscient de l\'être, et pas commode.',
    t: { vac: 0.85, rig: 0.8, loy: 0.9, att: 0.85, dom: 0.75, com: 0.7, dip: 0.4, con: 0.7, soc: 0.35, san: 0.7 } },
  { name: 'Le pélican', tag: 'Celui qui nourrit', color: '#c19a4a', cat: 'Oiseaux',
    desc: 'Il pêche en groupe, en formant un demi-cercle qui rabat les poissons, et partage ce qu\'il rapporte. Sa poche lui sert autant à attraper qu\'à donner. Il a l\'air d\'un animal mal dessiné et se révèle un planeur remarquable au ras des vagues.',
    t: { col: 0.9, care: 0.9, vbe: 0.9, emp: 0.8, fia: 0.85, soc: 0.75, dip: 0.75, cmp: 0.15, dom: 0.3, vpo: 0.1 } },
  { name: 'Le zèbre', tag: 'Se fondre dans le nombre', color: '#4a4a52', cat: 'Mammifères',
    desc: 'Ses rayures ne servent pas à se cacher dans l\'herbe mais à brouiller les contours quand le troupeau s\'enfuit : impossible de viser un individu. Il dort à tour de rôle, en gardant toujours quelqu\'un éveillé. Nerveux, solidaire, et il rue très fort.',
    t: { col: 0.9, vig: 0.9, thr: 0.85, loy: 0.8, soc: 0.7, aud: 0.55, ind: 0.2, com: 0.6, san: 0.3, att: 0.75 } },
  { name: 'La gazelle', tag: 'La légèreté aux aguets', color: '#d9b382', cat: 'Mammifères',
    desc: 'Elle broute la tête levée une fois sur deux, prête à partir. Quand elle détecte un prédateur, elle bondit très haut sur place — une façon de lui dire qu\'elle l\'a vu et qu\'il peut aller voir ailleurs. Rapide, élégante, en tension permanente.',
    t: { thr: 0.9, vig: 0.95, aud: 0.65, col: 0.75, vst: 0.6, san: 0.25, com: 0.15, dom: 0.15, ste: 0.35, opt: 0.5 } },
  { name: 'Le rhinocéros', tag: 'Charger d\'abord', color: '#8a8f98', cat: 'Mammifères',
    desc: 'Il voit très mal et charge tout ce qui bouge un peu trop près, par principe. Deux tonnes lancées sans hésitation, sur la foi d\'une information incomplète. Le reste du temps il est solitaire, placide, et il aime beaucoup la boue.',
    t: { com: 0.95, det: 0.9, ind: 0.85, opn: 0.9, thr: 0.8, dog: 0.85, dip: 0.05, ouv: 0.1, san: 0.35, aud: 0.85 } },
  { name: 'L\'hippopotame', tag: 'Le territoire d\'abord', color: '#8a6f7a', cat: 'Mammifères',
    desc: 'Il passe ses journées dans l\'eau à ne rien faire et devient extrêmement dangereux dès qu\'on approche de son bout de rivière. Il ne prévient qu\'une fois, en ouvrant grand la gueule. Grégaire avec les siens, intraitable avec tous les autres.',
    t: { dom: 0.9, com: 0.9, att: 0.9, thr: 0.8, col: 0.7, opn: 0.85, care: 0.7, dip: 0.1, ouv: 0.15, vhe: 0.7 } },
  { name: 'La hyène', tag: 'L\'efficacité mal-aimée', color: '#9a8250', cat: 'Mammifères',
    desc: 'On la croit charognarde alors qu\'elle chasse l\'essentiel de ce qu\'elle mange, en groupes coordonnés dirigés par les femelles. Elle a une hiérarchie complexe, une mâchoire qui broie l\'os, et un rire qui est en réalité un signal social. Mauvaise réputation, excellentes compétences.',
    t: { col: 0.85, cmp: 0.9, det: 0.9, nat: 0.85, aff: 0.75, lea: 0.7, dom: 0.8, ide: 0.15, dip: 0.2, vac: 0.75 } },
  { name: 'Le koala', tag: 'L\'économie d\'énergie', color: '#8c9196', cat: 'Mammifères',
    desc: 'Il dort vingt heures par jour et passe les quatre autres à manger des feuilles à peine digestes. Il ne s\'intéresse pas beaucoup à ses congénères et encore moins au reste du monde. Ce n\'est pas de la paresse : c\'est le seul régime possible avec un carburant pareil.',
    t: { ste: 0.95, san: 0.85, ind: 0.8, opn: 0.9, eng: 0.1, vst: 0.05, com: 0.05, soc: 0.15, vse: 0.8, cmp: 0.05 } },
  { name: 'Le kangourou', tag: 'Avancer par bonds', color: '#b5734a', cat: 'Mammifères',
    desc: 'Il ne sait pas reculer et il avance par sauts, en économisant une énergie folle grâce à l\'élasticité de ses tendons. Il transporte les siens avec lui, met les combats en scène en boxant debout, et peut mettre sa gestation en pause si les conditions sont mauvaises.',
    t: { det: 0.85, aud: 0.8, col: 0.75, com: 0.75, att: 0.8, ste: 0.6, chg: 0.7, cmp: 0.7, ord: 0.3, tmp: 0.6 } },
  { name: 'L\'araignée', tag: 'Le piège patient', color: '#5b5468', cat: 'Insectes et petites bêtes',
    desc: 'Elle passe la nuit à construire une géométrie parfaite, puis elle attend au centre sans bouger, en écoutant les vibrations. Si on détruit sa toile, elle en refait une le lendemain. Méthodique, solitaire, et capable de rester immobile très longtemps.',
    t: { rig: 0.95, ord: 0.9, tmp: 0.85, ind: 0.95, san: 0.85, det: 0.9, thr: 0.6, con: 0.85, soc: 0.05, inf: 0.05 } },
  { name: 'La mante religieuse', tag: 'L\'immobilité fatale', color: '#8fbf6a', cat: 'Insectes et petites bêtes',
    desc: 'Elle se tient parfaitement immobile, les pattes repliées, et ressemble à une brindille jusqu\'au moment où ce n\'est plus une brindille. Elle frappe en une fraction de seconde. Aucune émotion visible, aucune hésitation, aucune pitié — y compris envers ses partenaires.',
    t: { san: 0.98, rig: 0.9, thr: 0.8, ind: 0.95, det: 0.9, cmp: 0.85, emp: 0.05, care: 0.05, soc: 0.05, dip: 0.1 } },
  { name: 'La luciole', tag: 'Le signal dans la nuit', color: '#c2a326', cat: 'Insectes et petites bêtes',
    desc: 'Elle produit sa propre lumière, sans chaleur, uniquement pour être vue de ceux qu\'elle cherche. Dans certaines forêts, des milliers d\'individus finissent par clignoter en même temps sans chef d\'orchestre. Discrète le jour, impossible à ignorer la nuit.',
    t: { inf: 0.9, soc: 0.85, opt: 0.85, ide: 0.8, col: 0.8, vst: 0.7, emp: 0.75, com: 0.1, dom: 0.15, vpo: 0.1 } },
  { name: 'Le serpent', tag: 'Le calcul à froid', color: '#6a8f5f', cat: 'Reptiles et amphibiens',
    desc: 'Il ne dépense rien inutilement : il attend, il sent, il évalue, et il n\'agit qu\'une fois. Il n\'a ni paupières ni expressions, ce qui le rend impossible à lire. Il change de peau entièrement quand la précédente ne lui va plus, et repart comme si de rien n\'était.',
    t: { san: 0.95, aff: 0.85, ind: 0.9, tmp: 0.8, nat: 0.85, chg: 0.7, det: 0.8, emp: 0.15, soc: 0.05, dip: 0.25 } },
  { name: 'Le cerf', tag: 'Le prestige et le combat', color: '#8b5e3c', cat: 'Mammifères',
    desc: 'Il porte chaque année une couronne qu\'il perd et refait plus grande, et passe la saison du brame à crier pour impressionner sans avoir à se battre. Quand le bluff échoue, les bois s\'entrechoquent pour de bon. Le reste de l\'année, il est étonnamment discret.',
    t: { vac: 0.9, cmp: 0.9, dom: 0.8, com: 0.75, att: 0.8, opn: 0.8, vpo: 0.75, vig: 0.75, dip: 0.25, ste: 0.3 } },
  { name: 'Le sanglier', tag: 'Le groupe têtu', color: '#5e5145', cat: 'Mammifères',
    desc: 'Il fonce en ligne droite à travers les fourrés, retourne des hectares de terre pour trouver ce qu\'il cherche, et ne se laisse pas impressionner. La laie protège ses marcassins avec une agressivité totale. Omnivore, opportuniste, et absolument impossible à déloger.',
    t: { det: 0.95, com: 0.9, col: 0.8, opn: 0.9, aud: 0.85, care: 0.8, thr: 0.6, ouv: 0.5, dip: 0.15, ord: 0.2 } },
  { name: 'Le renne', tag: 'La longue marche', color: '#9a9c8f', cat: 'Mammifères',
    desc: 'Il parcourt plusieurs milliers de kilomètres par an, en troupeau, sur le même itinéraire que ses ancêtres. Il creuse la neige pour trouver du lichen et voit les ultraviolets, ce qui lui permet de distinguer le sol dans le blanc total. Endurant, collectif, fidèle à la route.',
    t: { col: 0.9, det: 0.9, tmp: 0.85, opn: 0.8, vtr: 0.85, fia: 0.9, ste: 0.85, vig: 0.75, com: 0.2, vst: 0.25 } },
  { name: 'Le panda', tag: 'Il a choisi le bambou', color: '#3c3c40', cat: 'Mammifères',
    desc: 'Carnivore par son système digestif, il mange douze heures par jour une plante qu\'il digère mal, ce qui l\'oblige à économiser chaque mouvement. Il vit seul, ne se bat presque jamais et se laisse rouler dans la pente. Son mode de vie ne devrait pas marcher, et il marche depuis des millions d\'années.',
    t: { san: 0.95, ind: 0.9, vhe: 0.85, cfl: 0.05, det: 0.7, opn: 0.9, soc: 0.2, emp: 0.6, ste: 0.9, vst: 0.25 } },
  { name: 'Le panda roux', tag: 'La discrétion perchée', color: '#c1502e', cat: 'Mammifères',
    desc: 'Il passe la journée endormi en haut d\'un arbre et se réveille au crépuscule pour manger, seul, méthodiquement. Il se dresse et écarte les bras quand il est surpris, ce qui n\'effraie personne. Timide, routinier, très attaché à son territoire.',
    t: { ind: 0.9, soc: 0.25, san: 0.8, opn: 0.9, thr: 0.8, rig: 0.75, vse: 0.85, emp: 0.6, aud: 0.3, ord: 0.8 } },
  { name: 'L\'ornithorynque', tag: 'Il ne rentre dans aucune case', color: '#6b5a48', cat: 'Mammifères',
    desc: 'Mammifère à bec de canard qui pond des œufs, détecte l\'électricité de ses proies les yeux fermés et porte un éperon venimeux. Les premiers naturalistes ont cru à une farce. Il existe sans se soucier des catégories qu\'on essaie de lui appliquer.',
    t: { ouv: 0.9, ind: 0.95, inc: 0.9, vsd: 0.9, san: 0.8, soc: 0.2, vco: 0.05, vig: 0.9, det: 0.8, chg: 0.7 } },
  { name: 'Le lémurien', tag: 'La bande qui crie fort', color: '#9aa0a8', cat: 'Mammifères',
    desc: 'Il vit en groupe dirigé par les femelles, se chauffe au soleil en position assise le matin, et règle les conflits en agitant sa queue parfumée. Il n\'existe qu\'à un seul endroit du monde. Bruyant, tactile, très dépendant du groupe.',
    t: { col: 0.9, soc: 0.9, com: 0.9, att: 0.85, vhe: 0.8, emp: 0.75, cfl: 0.6, ind: 0.2, opt: 0.8, dom: 0.4 } },
  { name: 'Le babouin', tag: 'La politique de la troupe', color: '#8a7355', cat: 'Mammifères',
    desc: 'Il vit dans une hiérarchie complexe où les alliances comptent plus que la force brute, et il passe sa journée à les entretenir. Il menace, négocie, se réconcilie, trahit à l\'occasion. C\'est l\'animal dont la vie sociale ressemble le plus à un bureau.',
    t: { dom: 0.85, soc: 0.9, dip: 0.8, cmp: 0.9, col: 0.8, vpo: 0.85, com: 0.85, emp: 0.55, nat: 0.75, aud: 0.8 } },
  { name: 'La taupe', tag: 'Elle travaille dans le noir', color: '#4a4442', cat: 'Mammifères',
    desc: 'Elle creuse vingt mètres de galerie par nuit avec des mains disproportionnées, ne voit presque rien et cartographie tout au toucher. Elle vit seule et défend son réseau férocement. Son travail se voit uniquement par les tas qu\'elle laisse derrière.',
    t: { det: 0.95, ind: 0.95, rig: 0.9, ord: 0.9, soc: 0.05, vig: 0.85, opn: 0.9, cfl: 0.8, com: 0.05, fia: 0.9 } },
  { name: 'La marmotte', tag: 'Six mois de sieste, organisés', color: '#9e8355', cat: 'Mammifères',
    desc: 'Elle passe l\'été à manger et à surveiller, siffle pour alerter toute la colonie, puis dort six mois en famille dans un terrier bouché. Son cœur descend à cinq battements par minute. Prévoyante, sociale, et totalement assumée dans sa lenteur.',
    t: { tmp: 0.95, vse: 0.9, col: 0.85, vig: 0.9, com: 0.85, san: 0.85, care: 0.8, det: 0.8, rig: 0.85, vhe: 0.75 } },
  { name: 'Le glouton', tag: 'Il ne cède jamais le repas', color: '#5a4636', cat: 'Mammifères',
    desc: 'Pas plus gros qu\'un chien, il chasse des proies dix fois son poids et fait reculer des ours de leur propre carcasse. Il parcourt des dizaines de kilomètres par jour dans la neige. Son rapport de force est toujours défavorable et ça ne l\'arrête pas.',
    t: { aud: 0.98, det: 0.98, ind: 0.95, cfl: 0.95, thr: 0.7, san: 0.7, emp: 0.15, dom: 0.85, soc: 0.05, rsk: 0.95 } },
  { name: 'L\'élan', tag: 'Grand, calme, et à éviter', color: '#6f5b45', cat: 'Mammifères',
    desc: 'Il fait deux mètres au garrot, nage plusieurs kilomètres et broute tranquillement — jusqu\'à ce qu\'on s\'approche trop, moment où il charge sans avertissement. Il perd ses bois chaque année et les refait plus grands. Solitaire, imprévisible, impressionnant.',
    t: { ind: 0.9, san: 0.75, dom: 0.85, cfl: 0.8, det: 0.9, thr: 0.8, soc: 0.15, opn: 0.8, aud: 0.8, emp: 0.35 } },
  { name: 'Le yak', tag: 'Il tient en altitude', color: '#5f5347', cat: 'Mammifères',
    desc: 'Il vit à cinq mille mètres, porte des charges dans des cols où rien ne pousse, et se couche dans la tempête sans se plaindre. Ses poumons et son sang sont faits pour l\'air rare. Il travaille depuis des millénaires pour des gens qui ne survivraient pas sans lui.',
    t: { fia: 0.98, det: 0.95, ste: 0.95, col: 0.8, san: 0.9, vco: 0.8, care: 0.7, vtr: 0.9, cfl: 0.2, tmp: 0.85 } },
  { name: 'Le mouton', tag: 'Le groupe avant l\'avis', color: '#d3cdc0', cat: 'Mammifères',
    desc: 'Il suit le voisin, panique en groupe et se calme en groupe, mais reconnaît une cinquantaine de visages et s\'en souvient pendant des années. Il est bien plus fin qu\'on ne le dit, à condition de le regarder individuellement. Sa force et sa faiblesse tiennent au troupeau.',
    t: { col: 0.95, vco: 0.9, soc: 0.85, ind: 0.1, thr: 0.8, emp: 0.7, san: 0.5, dom: 0.1, fia: 0.85, aud: 0.2 } },
  { name: 'L\'âne', tag: 'Il refuse quand c\'est dangereux', color: '#8f8578', cat: 'Mammifères',
    desc: 'Réputé têtu, il évalue en réalité le risque et refuse d\'avancer quand il juge que ça ne passe pas — il a souvent raison. Il porte des charges énormes, se souvient d\'un chemin des années après, et garde rancune. Sa prudence passe pour de l\'entêtement.',
    t: { fia: 0.95, det: 0.95, vig: 0.9, ind: 0.85, san: 0.85, thr: 0.8, dog: 0.8, care: 0.7, vco: 0.3, rsk: 0.1 } },
  { name: 'Le lama', tag: 'Il crache s\'il a prévenu', color: '#c9b58f', cat: 'Mammifères',
    desc: 'Il porte des charges toute la journée en altitude, garde les troupeaux de moutons contre les prédateurs, et couche les oreilles avant de cracher. Il n\'attaque jamais sans signal préalable. Son calme a des limites parfaitement annoncées.',
    t: { fia: 0.9, care: 0.85, det: 0.85, com: 0.8, san: 0.8, col: 0.8, cfl: 0.6, dom: 0.6, ste: 0.85, emp: 0.6 } },
  { name: 'Le porc-épic', tag: 'Personne n\'insiste deux fois', color: '#6b5f4f', cat: 'Mammifères',
    desc: 'Il avance lentement, sans se presser, parce que trente mille piquants à barbillons règlent la question de la sécurité. Il ne les lance pas : il recule dedans. Il mange des écorces, vit seul, et n\'a peur de presque rien.',
    t: { san: 0.9, ind: 0.9, thr: 0.75, ste: 0.9, det: 0.8, cfl: 0.6, soc: 0.15, vse: 0.9, aud: 0.6, emp: 0.4 } },
  { name: 'Le perroquet gris', tag: 'Il comprend plus qu\'il n\'en dit', color: '#8e9aa3', cat: 'Oiseaux',
    desc: 'Il imite des voix humaines mais surtout il associe, compte et réclame ce qu\'il veut par son nom. Il s\'attache à une personne pour la vie et déprime réellement quand elle disparaît. Son intelligence exige une occupation permanente, faute de quoi il s\'arrache les plumes.',
    t: { ouv: 0.95, com: 0.95, att: 0.95, soc: 0.85, emp: 0.8, inc: 0.3, det: 0.8, vst: 0.85, fia: 0.8, thr: 0.7 } },
  { name: 'La pie', tag: 'Elle prend ce qui brille', color: '#4a4f58', cat: 'Oiseaux',
    desc: 'Elle se reconnaît dans un miroir, cache des réserves un peu partout et retient le visage de qui l\'a embêtée. Curieuse jusqu\'au vol, bavarde, elle teste les limites de tout ce qu\'elle croise. Elle vit en bande et règle ses comptes en assemblée.',
    t: { ouv: 0.95, vst: 0.9, aud: 0.85, soc: 0.85, vig: 0.85, com: 0.9, vhe: 0.8, rig: 0.25, emp: 0.5, nat: 0.7 } },
  { name: 'La mouette', tag: 'Elle se sert, sans gêne', color: '#b9c4cc', cat: 'Oiseaux',
    desc: 'Elle a compris que la ville nourrit mieux que la mer et elle attrape le sandwich sans état d\'âme. Bruyante, opportuniste, parfaitement adaptée, elle prospère là où d\'autres espèces reculent. Elle défend son nid avec une agressivité disproportionnée.',
    t: { aud: 0.95, ouv: 0.85, cmp: 0.9, emp: 0.25, soc: 0.8, vhe: 0.85, vco: 0.1, det: 0.85, com: 0.9, chg: 0.8 } },
  { name: 'L\'autruche', tag: 'Elle court plus vite que le problème', color: '#c9a26b', cat: 'Oiseaux',
    desc: 'Plus grand oiseau du monde, elle ne vole pas mais atteint soixante-dix kilomètres-heure et frappe assez fort pour tuer un prédateur. Elle ne cache pas sa tête dans le sable : elle la baisse pour retourner ses œufs. Nerveuse, rapide, très mal à l\'aise à l\'arrêt.',
    t: { det: 0.9, aud: 0.85, thr: 0.85, san: 0.3, vig: 0.9, ind: 0.7, rsk: 0.7, soc: 0.6, cfl: 0.6, opn: 0.7 } },
  { name: 'Le paon', tag: 'La démonstration permanente', color: '#1f7a8c', cat: 'Oiseaux',
    desc: 'Il transporte une queue qui le gêne pour fuir, uniquement parce qu\'elle impressionne. Il crie de façon épouvantable, s\'expose au milieu du terrain et considère que le spectacle vaut le risque. Tout chez lui est fait pour être regardé.',
    t: { inf: 0.98, vac: 0.9, vpo: 0.85, soc: 0.8, aud: 0.85, rsk: 0.85, emp: 0.4, com: 0.9, vhe: 0.85, rig: 0.3 } },
  { name: 'Le moineau', tag: 'Petit, partout, increvable', color: '#a08b70', cat: 'Oiseaux',
    desc: 'Il vit dans toutes les villes du monde, mange à peu près n\'importe quoi et se déplace toujours en petit groupe bruyant. Il n\'impressionne personne et il est là depuis bien plus longtemps que des espèces spectaculaires. Sa discrétion est une stratégie gagnante.',
    t: { col: 0.9, soc: 0.9, opn: 0.8, ouv: 0.75, vse: 0.8, vig: 0.85, aud: 0.6, vac: 0.15, fia: 0.8, dom: 0.15 } },
  { name: 'La mésange', tag: 'La curieuse méthodique', color: '#e3c13f', cat: 'Oiseaux',
    desc: 'Elle a appris à ouvrir les bouteilles de lait, et l\'information s\'est transmise de colonie en colonie. Elle retient l\'emplacement de milliers de graines cachées et fait des allers-retours toute la journée. Minuscule, infatigable, et beaucoup plus futée qu\'elle n\'en a l\'air.',
    t: { ouv: 0.9, det: 0.9, vig: 0.9, rig: 0.8, soc: 0.7, tmp: 0.8, aud: 0.7, inc: 0.5, fia: 0.85, ord: 0.8 } },
  { name: 'Le pigeon voyageur', tag: 'Il rentre toujours', color: '#7e8794', cat: 'Oiseaux',
    desc: 'Lâché à mille kilomètres, il retrouve son pigeonnier grâce au champ magnétique et au soleil. On lui a confié des messages de guerre et il les a livrés, blessé, parce que rentrer est la seule chose qui compte. Son attachement au point de départ est total.',
    t: { fia: 0.98, det: 0.98, att: 0.95, opn: 0.9, vco: 0.8, tmp: 0.8, san: 0.8, ide: 0.75, ind: 0.5, vst: 0.2 } },
  { name: 'Le vautour', tag: 'L\'utilité mal-aimée', color: '#6b5b4a', cat: 'Oiseaux',
    desc: 'Il plane des heures sans battre des ailes et nettoie ce que personne d\'autre ne veut toucher, avec un estomac capable de digérer des maladies mortelles. Sa réputation est exécrable et son rôle écologique, irremplaçable. Il attend, patiemment, sans jamais chasser.',
    t: { san: 0.9, tmp: 0.9, vig: 0.9, emp: 0.35, ind: 0.85, aff: 0.8, col: 0.6, cfl: 0.2, vac: 0.2, opt: 0.35 } },
  { name: 'La grue cendrée', tag: 'La danse et le voyage', color: '#9aa5ab', cat: 'Oiseaux',
    desc: 'Elle traverse un continent deux fois par an en formation, en criant pour tenir le groupe soudé. Les couples dansent ensemble chaque année et restent unis toute leur vie. Élégante, fidèle, elle suit un calendrier qui la dépasse.',
    t: { att: 0.95, col: 0.9, fia: 0.9, tmp: 0.9, vtr: 0.85, com: 0.8, soc: 0.8, det: 0.85, dip: 0.8, vst: 0.35 } },
  { name: 'Le martin-pêcheur', tag: 'Un seul geste, parfait', color: '#0f8bbf', cat: 'Oiseaux',
    desc: 'Il reste immobile sur sa branche pendant de longues minutes, puis plonge une fois et remonte avec le poisson. Il corrige la réfraction de l\'eau de tête, sans y penser. Toute son économie tient dans l\'attente et dans la précision du moment choisi.',
    t: { rig: 0.95, san: 0.9, vig: 0.95, det: 0.9, ind: 0.9, tmp: 0.7, soc: 0.15, aud: 0.75, ord: 0.85, cmp: 0.7 } },
  { name: 'Le rouge-gorge', tag: 'Mignon, et territorial', color: '#d1502e', cat: 'Oiseaux',
    desc: 'Il s\'approche des jardiniers sans peur et chante toute l\'année, ce qui le rend sympathique. Il attaque aussi n\'importe quel intrus de son espèce jusqu\'à la mort, ce qui l\'est moins. Sa confiance envers les humains et son intransigeance envers les siens vont ensemble.',
    t: { aud: 0.85, cfl: 0.9, ind: 0.9, soc: 0.6, com: 0.85, nat: 0.35, det: 0.85, cmp: 0.9, opn: 0.85, emp: 0.4 } },
  { name: 'Le pic-vert', tag: 'Frapper jusqu\'à ce que ça cède', color: '#4f8f3c', cat: 'Oiseaux',
    desc: 'Il tape jusqu\'à vingt fois par seconde sur du bois dur, avec un crâne conçu pour encaisser le choc. Il creuse son propre logement, saison après saison, et laisse la place aux autres espèces ensuite. Bruyant, obstiné, jamais découragé.',
    t: { det: 0.98, fia: 0.9, rig: 0.85, ind: 0.85, com: 0.85, ord: 0.8, san: 0.7, thr: 0.6, aud: 0.8, vac: 0.6 } },
  { name: 'L\'hirondelle', tag: 'Elle revient au même nid', color: '#2f4f7a', cat: 'Oiseaux',
    desc: 'Elle fait dix mille kilomètres pour retrouver exactement la grange où elle est née, et répare le nid de l\'an dernier. Elle mange, boit et parfois dort en vol. Sa fidélité au lieu est aussi impressionnante que son endurance.',
    t: { det: 0.95, fia: 0.95, opn: 0.85, att: 0.9, tmp: 0.85, col: 0.8, vtr: 0.85, aud: 0.8, san: 0.7, soc: 0.75 } },
  { name: 'Le toucan', tag: 'Un bec plus grand que lui', color: '#f2a20c', cat: 'Oiseaux',
    desc: 'Son bec énorme et coloré sert surtout à réguler sa température et à atteindre les fruits loin sur la branche. Il vit en petite bande bruyante et joue à se lancer des baies. Il a l\'air fait pour l\'exubérance et il l\'est.',
    t: { soc: 0.9, vhe: 0.9, opt: 0.9, inf: 0.9, ouv: 0.85, com: 0.85, cfl: 0.2, emp: 0.7, rig: 0.3, vst: 0.8 } },
  { name: 'Le casoar', tag: 'Ne pas s\'approcher', color: '#2f6fb5', cat: 'Oiseaux',
    desc: 'Oiseau de deux mètres avec une griffe en poignard, il ne cherche personne mais ne recule devant rien. Il disperse à lui seul les graines de dizaines d\'arbres de la forêt tropicale. Solitaire, imprévisible, absolument à laisser tranquille.',
    t: { ind: 0.95, cfl: 0.9, thr: 0.9, aud: 0.9, soc: 0.05, dom: 0.85, nat: 0.9, san: 0.4, emp: 0.3, vtr: 0.7 } },
  { name: 'Le coq', tag: 'Le chef de la basse-cour', color: '#c43d2e', cat: 'Oiseaux',
    desc: 'Il annonce le jour avant tout le monde, surveille son groupe et appelle les poules dès qu\'il trouve de quoi manger. Il se jette sur un rapace deux fois plus grand pour protéger les siennes. Fanfaron et réellement courageux, dans le même mouvement.',
    t: { dom: 0.9, lea: 0.85, inf: 0.9, care: 0.85, aud: 0.9, com: 0.95, col: 0.8, cfl: 0.85, vpo: 0.8, vtr: 0.85 } },
  { name: 'Le cormoran', tag: 'Il plonge et il sèche', color: '#3a4046', cat: 'Oiseaux',
    desc: 'Ses plumes ne sont pas imperméables, ce qui lui permet de plonger profond mais l\'oblige ensuite à rester ailes ouvertes au soleil. Il accepte ce handicap parce qu\'il pêche mieux que tout le monde. Efficace, solitaire, indifférent au ridicule.',
    t: { det: 0.9, ind: 0.9, aud: 0.85, rig: 0.8, vac: 0.75, emp: 0.35, san: 0.8, soc: 0.3, cmp: 0.8, inc: 0.6 } },
  { name: 'L\'étourneau', tag: 'Mille oiseaux, un seul mouvement', color: '#4b3f6b', cat: 'Oiseaux',
    desc: 'En vol, des milliers d\'individus tournent ensemble sans chef ni signal, chacun ne surveillant que ses sept voisins. Le résultat ressemble à une intelligence collective et n\'en est pas une. Seul, il est bruyant, banal et remarquablement imitateur.',
    t: { col: 0.98, soc: 0.95, vig: 0.9, ouv: 0.8, ind: 0.15, com: 0.85, dom: 0.15, vco: 0.85, fia: 0.8, aud: 0.6 } },
  { name: 'La chouette effraie', tag: 'Le silence en vol', color: '#d8cdb8', cat: 'Oiseaux',
    desc: 'Ses plumes annulent le bruit de ses ailes, et son visage en cœur concentre le moindre son jusqu\'à localiser une souris sous la neige. Elle chasse dans le noir absolu sans jamais se faire entendre. Discrète au point de passer pour un fantôme.',
    t: { san: 0.95, vig: 0.98, ind: 0.9, rig: 0.9, soc: 0.1, det: 0.9, aff: 0.7, thr: 0.7, com: 0.2, ord: 0.85 } },
  { name: 'Le gecko', tag: 'Il tient au plafond', color: '#7fae4f', cat: 'Reptiles et amphibiens',
    desc: 'Des millions de poils microscopiques lui permettent d\'adhérer au verre, à l\'envers, sans aucune colle. Il perd sa queue quand on l\'attrape et elle repousse. Nocturne, discret, il s\'installe dans les maisons et mange ce qui vole autour de la lampe.',
    t: { ouv: 0.85, aud: 0.8, ind: 0.85, san: 0.8, vig: 0.85, chg: 0.7, soc: 0.4, thr: 0.6, det: 0.8, opn: 0.5 } },
  { name: 'L\'iguane', tag: 'Il ne bouge que s\'il le faut', color: '#5f8d54', cat: 'Reptiles et amphibiens',
    desc: 'Il passe la journée au soleil sans rien faire, parce que sa température dépend entièrement de l\'extérieur. Il fouette avec sa queue quand on insiste et se laisse tomber d\'un arbre de dix mètres sans conséquence. Végétarien, lent, imperturbable.',
    t: { san: 0.9, ste: 0.9, ind: 0.85, loc: 0.7, cfl: 0.6, soc: 0.2, det: 0.7, thr: 0.5, vhe: 0.75, opn: 0.8 } },
  { name: 'Le varan de Komodo', tag: 'Il attend que ça travaille', color: '#6b6250', cat: 'Reptiles et amphibiens',
    desc: 'Il mord une fois, laisse le venin et les bactéries faire leur travail, puis suit la proie affaiblie pendant des jours. Il sent une charogne à dix kilomètres. Patient, méthodique, absolument sans pitié.',
    t: { tmp: 0.95, det: 0.95, san: 0.9, emp: 0.05, vig: 0.9, ind: 0.9, cmp: 0.9, aff: 0.8, care: 0.05, rig: 0.8 } },
  { name: 'Le cobra royal', tag: 'L\'avertissement avant la morsure', color: '#8a6f2e', cat: 'Reptiles et amphibiens',
    desc: 'Il se dresse à hauteur d\'homme, déploie sa collerette et grogne — tout est fait pour éviter le combat. C\'est le seul serpent qui construit un nid et le garde. Extrêmement dangereux, et plutôt enclin à laisser partir ce qui recule.',
    t: { dom: 0.95, san: 0.9, care: 0.7, thr: 0.85, cfl: 0.8, ind: 0.9, dip: 0.6, det: 0.9, vig: 0.9, emp: 0.35 } },
  { name: 'Le python', tag: 'La patience qui serre', color: '#6f7d4a', cat: 'Reptiles et amphibiens',
    desc: 'Il reste immobile des semaines, détecte la chaleur d\'un corps dans le noir, et resserre sa prise à chaque expiration de sa proie. Il peut jeûner des mois sans faiblir. Il ne poursuit jamais : il attend au bon endroit.',
    t: { tmp: 0.95, san: 0.95, det: 0.95, ind: 0.9, vig: 0.9, emp: 0.05, rig: 0.85, soc: 0.05, thr: 0.5, ord: 0.8 } },
  { name: 'La vipère', tag: 'Discrète et venimeuse', color: '#8b7a55', cat: 'Reptiles et amphibiens',
    desc: 'Elle se confond avec les feuilles mortes et ne mord qu\'au dernier moment, quand la fuite n\'est plus possible. Elle dose son venin selon la situation. Tout, chez elle, vise à ne pas être vue : elle préfère de loin qu\'on passe à côté sans la remarquer plutôt que d\'avoir à se défendre.',
    t: { thr: 0.9, vig: 0.9, ind: 0.9, san: 0.8, soc: 0.05, nat: 0.9, rig: 0.8, cfl: 0.6, aud: 0.35, emp: 0.15 } },
  { name: 'Le lézard des murailles', tag: 'Toujours au soleil, toujours prêt à filer', color: '#a08f5f', cat: 'Reptiles et amphibiens',
    desc: 'Il se chauffe sur la pierre et disparaît dans une fissure au moindre mouvement, sa queue restant parfois entre les doigts du prédateur. Il revient cinq minutes plus tard au même endroit. Méfiant, rapide, et très attaché à son mur.',
    t: { vig: 0.95, thr: 0.85, opn: 0.9, ind: 0.85, aud: 0.6, san: 0.6, det: 0.8, soc: 0.3, nat: 0.85, vse: 0.8 } },
  { name: 'La salamandre', tag: 'Elle sort quand il pleut', color: '#e0b31f', cat: 'Reptiles et amphibiens',
    desc: 'Noire et jaune pour prévenir qu\'elle est toxique, elle ne sort que les nuits humides et marche lentement, sûre que personne ne la mangera. Elle régénère ses membres, ses organes, une partie de son cerveau. La légende la disait insensible au feu.',
    t: { san: 0.9, ind: 0.85, thr: 0.4, det: 0.85, soc: 0.1, opn: 0.85, inc: 0.6, vtr: 0.8, aud: 0.5, emp: 0.4 } },
  { name: 'L\'axolotl', tag: 'Il ne grandit jamais tout à fait', color: '#f0a8bd', cat: 'Reptiles et amphibiens',
    desc: 'Il garde toute sa vie ses branchies d\'adolescent et ne se transforme jamais en adulte terrestre. Il repousse une patte, une mâchoire, un morceau de cerveau, sans cicatrice. Il sourit en permanence, ce qui n\'est qu\'une forme de mâchoire.',
    t: { inc: 0.85, opt: 0.85, san: 0.9, vst: 0.7, ouv: 0.8, chg: 0.15, thr: 0.25, soc: 0.4, emp: 0.6, vhe: 0.75 } },
  { name: 'La grenouille', tag: 'Elle chante toute la nuit', color: '#5fa832', cat: 'Reptiles et amphibiens',
    desc: 'Elle gonfle sa gorge et appelle pendant des heures, en concurrence directe avec tous les autres mâles de la mare. Elle passe de l\'eau à la terre en changeant complètement de corps. Bruyante, résistante, indifférente au ridicule.',
    t: { com: 0.95, soc: 0.85, cmp: 0.8, aud: 0.8, chg: 0.85, vst: 0.8, det: 0.8, san: 0.6, inf: 0.85, ouv: 0.8 } },
  { name: 'Le crapaud', tag: 'Moche et parfaitement utile', color: '#7a6a4f', cat: 'Reptiles et amphibiens',
    desc: 'Il avale des centaines d\'insectes par nuit, traverse les routes chaque printemps vers la mare où il est né, et se laisse porter sans protester. Sa réputation est désastreuse et injustifiée. Il vit parfois quarante ans.',
    t: { fia: 0.9, det: 0.9, opn: 0.9, san: 0.85, ste: 0.9, soc: 0.3, vac: 0.1, tmp: 0.85, care: 0.6, vtr: 0.85 } },
  { name: 'Le triton', tag: 'Il danse avant de plaire', color: '#4b7d6b', cat: 'Reptiles et amphibiens',
    desc: 'Le mâle développe une crête au printemps et exécute une parade minutieuse devant la femelle, plusieurs fois par jour. Le reste de l\'année, il vit caché sous une pierre. Discret onze mois sur douze, démonstratif le douzième.',
    t: { rig: 0.8, soc: 0.5, com: 0.7, vst: 0.6, ind: 0.8, san: 0.8, ord: 0.85, thr: 0.6, att: 0.7, emp: 0.5 } },
  { name: 'Le crotale', tag: 'Il prévient avant', color: '#9e7a4a', cat: 'Reptiles et amphibiens',
    desc: 'Il agite sa queue pour signaler sa présence avant toute chose : la morsure lui coûte du venin qu\'il préfère garder. Il voit la chaleur des corps et frappe en une fraction de seconde. Son avertissement est une politesse dangereuse.',
    t: { thr: 0.9, com: 0.85, san: 0.85, ind: 0.9, det: 0.9, vig: 0.95, cfl: 0.7, dip: 0.5, emp: 0.15, nat: 0.85 } },
  { name: 'L\'anaconda', tag: 'La masse dans l\'eau trouble', color: '#5b6b45', cat: 'Reptiles et amphibiens',
    desc: 'Il pèse jusqu\'à deux cents kilos, se déplace avec aisance dans le marécage et devient très lourd sur la terre ferme. Il chasse en restant à moitié immergé, invisible. Après un gros repas, il ne bouge plus pendant des semaines.',
    t: { det: 0.9, san: 0.9, tmp: 0.85, ind: 0.9, thr: 0.6, dom: 0.85, emp: 0.1, opn: 0.8, vig: 0.85, ste: 0.85 } },
  { name: 'La tortue-luth', tag: 'Elle traverse des océans', color: '#3f4a5a', cat: 'Reptiles et amphibiens',
    desc: 'Plus grande tortue du monde, elle plonge à mille mètres, traverse l\'Atlantique et revient pondre sur la plage où elle est née trente ans plus tôt. Elle se nourrit presque exclusivement de méduses. Sa constance dépasse l\'échelle humaine.',
    t: { det: 0.98, tmp: 0.98, ind: 0.9, opn: 0.85, san: 0.9, fia: 0.9, soc: 0.1, vtr: 0.9, aud: 0.8, thr: 0.4 } },
  { name: 'Le basilic', tag: 'Il court sur l\'eau', color: '#3f9e7a', cat: 'Reptiles et amphibiens',
    desc: 'Poursuivi, il se dresse sur ses pattes arrière et traverse la surface d\'un étang en frappant assez vite pour ne pas couler. Il tient une vingtaine de mètres, puis nage. Sa solution au danger est spectaculaire et strictement temporaire.',
    t: { aud: 0.95, vst: 0.85, thr: 0.85, san: 0.35, ind: 0.85, det: 0.8, rsk: 0.9, ouv: 0.8, soc: 0.3, chg: 0.8 } },
  { name: 'La méduse', tag: 'Sans cerveau, et increvable', color: '#8fd3e8', cat: 'Mers et océans',
    desc: 'Elle n\'a ni cerveau, ni cœur, ni squelette, et elle est là depuis cinq cents millions d\'années. Elle ne décide de presque rien : elle dérive avec le courant et attrape ce qui la touche. Une espèce sait même rajeunir indéfiniment, ce qui la rend biologiquement immortelle.',
    t: { loc: 0.95, san: 0.9, ind: 0.8, emp: 0.05, det: 0.6, ord: 0.1, opn: 0.4, thr: 0.3, soc: 0.2, tmp: 0.85 } },
  { name: 'Le crabe', tag: 'De côté, mais il avance', color: '#c4452f', cat: 'Mers et océans',
    desc: 'Il se déplace de travers, tient sa position pinces levées et ne recule que quand il n\'a plus le choix. Il change de carapace régulièrement et reste caché, mou et vulnérable, le temps que la nouvelle durcisse. Têtu, blindé, et beaucoup plus fragile qu\'il ne le montre.',
    t: { cfl: 0.85, ste: 0.85, ind: 0.85, thr: 0.8, det: 0.9, vse: 0.85, soc: 0.3, aud: 0.7, dip: 0.2, chg: 0.4 } },
  { name: 'Le homard', tag: 'Il grandit en se déshabillant', color: '#9e2b2b', cat: 'Mers et océans',
    desc: 'Pour grossir, il doit sortir entièrement de sa carapace et rester sans défense pendant des jours. Il recommence toute sa vie, sans limite d\'âge connue. Son existence est une alternance de blindage et de vulnérabilité complète.',
    t: { det: 0.9, chg: 0.7, ste: 0.8, ind: 0.9, thr: 0.85, tmp: 0.9, cfl: 0.8, soc: 0.2, vse: 0.8, inc: 0.5 } },
  { name: 'L\'étoile de mer', tag: 'Elle repousse ce qu\'elle perd', color: '#e08a54', cat: 'Mers et océans',
    desc: 'Elle avance à deux centimètres par minute, sans tête ni cerveau, et régénère un bras arraché — parfois un individu entier à partir de ce bras. Elle sort son estomac pour digérer sa proie sur place. Lente, indestructible, franchement déconcertante.',
    t: { det: 0.9, san: 0.9, tmp: 0.9, ind: 0.85, emp: 0.1, ord: 0.5, opt: 0.7, thr: 0.25, soc: 0.15, chg: 0.6 } },
  { name: 'L\'oursin', tag: 'Tout en piquants', color: '#4a3f5e', cat: 'Mers et océans',
    desc: 'Il ne poursuit rien, ne fuit rien, et découvre les intrus par la douleur qu\'il leur inflige. Il broute les algues à un rythme minuscule et transforme des récifs entiers en désert quand il devient trop nombreux. Sa seule stratégie est de rendre l\'approche coûteuse.',
    t: { thr: 0.9, ind: 0.9, cfl: 0.85, soc: 0.1, san: 0.85, ste: 0.9, emp: 0.15, det: 0.8, dip: 0.05, opn: 0.9 } },
  { name: 'La seiche', tag: 'Elle change de peau en une seconde', color: '#7a6ba3', cat: 'Mers et océans',
    desc: 'Elle modifie sa couleur et sa texture instantanément, hypnotise ses proies par des vagues lumineuses, et peut montrer deux messages différents de chaque côté du corps. Daltonienne, elle perçoit pourtant les couleurs autrement. Son intelligence est aussi étrange que son apparence.',
    t: { ouv: 0.95, aff: 0.85, dip: 0.85, san: 0.85, ind: 0.9, vig: 0.9, com: 0.9, emp: 0.4, rig: 0.75, inc: 0.8 } },
  { name: 'Le calmar géant', tag: 'La légende des profondeurs', color: '#5e3550', cat: 'Mers et océans',
    desc: 'Il vit à plusieurs centaines de mètres de fond, porte les plus grands yeux du règne animal et a été filmé vivant il y a à peine vingt ans. Il se bat contre des cachalots et en garde les cicatrices. On ne sait presque rien de lui, et c\'est très bien ainsi.',
    t: { ind: 0.98, soc: 0.02, san: 0.8, thr: 0.8, det: 0.9, opn: 0.5, aud: 0.85, com: 0.05, emp: 0.2, cfl: 0.8 } },
  { name: 'Le bernard-l\'ermite', tag: 'Il emménage dans la coquille des autres', color: '#d6a15c', cat: 'Mers et océans',
    desc: 'Né sans carapace, il s\'installe dans une coquille vide et déménage dès qu\'elle devient trop petite. Il fait la queue avec ses congénères pour un échange collectif quand une belle coquille se libère. Pragmatique, prudent, jamais propriétaire.',
    t: { vse: 0.9, ouv: 0.8, thr: 0.85, ind: 0.75, chg: 0.8, col: 0.7, aud: 0.4, san: 0.7, vac: 0.3, dip: 0.7 } },
  { name: 'La raie manta', tag: 'Le vol sous l\'eau', color: '#3f6d8f', cat: 'Mers et océans',
    desc: 'Elle traverse l\'océan en battant des ailes, se laisse nettoyer par des petits poissons à des endroits qu\'elle retrouve chaque année, et se reconnaît dans un miroir. Elle ne chasse rien : elle filtre. Sa tranquillité en fait l\'animal le plus paisible de sa taille.',
    t: { san: 0.95, ouv: 0.85, ind: 0.8, emp: 0.6, cfl: 0.05, opt: 0.8, tmp: 0.85, dip: 0.8, aud: 0.7, vun: 0.8 } },
  { name: 'Le poisson-clown', tag: 'Protégé par ce qui pique', color: '#f07818', cat: 'Mers et océans',
    desc: 'Il vit dans une anémone urticante qui tuerait n\'importe quel autre poisson, et lui apporte en échange de quoi manger. Il ne s\'éloigne presque jamais et défend son bout de récif avec une agressivité comique. Toute sa vie tient dans un mètre carré, par choix.',
    t: { opn: 0.98, vse: 0.9, col: 0.85, att: 0.9, cfl: 0.75, ind: 0.2, fia: 0.9, aud: 0.35, dip: 0.7, soc: 0.7 } },
  { name: 'Le poisson-lune', tag: 'Énorme et sans défense', color: '#a9b4bd', cat: 'Mers et océans',
    desc: 'Il pèse deux tonnes, dérive lentement près de la surface pour se réchauffer et se laisse nettoyer par des oiseaux. Il pond des centaines de millions d\'œufs dont presque aucun ne survit. Sa stratégie est le nombre, pas la protection.',
    t: { loc: 0.9, san: 0.9, ind: 0.8, emp: 0.25, cfl: 0.05, thr: 0.2, det: 0.6, soc: 0.3, opt: 0.7, ord: 0.25 } },
  { name: 'L\'anguille', tag: 'Le voyage secret', color: '#4b5540', cat: 'Mers et océans',
    desc: 'Née dans la mer des Sargasses, elle traverse l\'Atlantique, remonte des rivières pendant des années, puis refait le chemin inverse pour pondre et mourir. Personne n\'a jamais vu sa reproduction. Sa vie entière est une traversée obstinée vers un endroit qu\'elle n\'a jamais connu.',
    t: { det: 0.98, tmp: 0.95, ind: 0.9, soc: 0.15, san: 0.8, opn: 0.6, ide: 0.8, vtr: 0.85, aud: 0.8, chg: 0.6 } },
  { name: 'La murène', tag: 'Elle attend dans le trou', color: '#5c6b4a', cat: 'Mers et océans',
    desc: 'Elle passe ses journées coincée dans une anfractuosité, gueule ouverte, ce qui la fait passer pour menaçante alors qu\'elle respire. Elle chasse la nuit, parfois en collaboration avec un mérou, ce qui est rare entre espèces. Elle mord surtout quand on met la main chez elle.',
    t: { ind: 0.9, thr: 0.85, opn: 0.9, san: 0.8, cfl: 0.8, soc: 0.25, vig: 0.85, dip: 0.4, nat: 0.85, det: 0.8 } },
  { name: 'Le thon rouge', tag: 'Il ne s\'arrête jamais', color: '#2f5d8c', cat: 'Mers et océans',
    desc: 'Il nage en permanence, y compris pour respirer, à soixante-dix kilomètres-heure et sur des milliers de kilomètres. Son sang est plus chaud que l\'eau, ce qui lui donne une puissance rare chez un poisson. Il ne connaît ni pause ni territoire.',
    t: { det: 0.98, aud: 0.9, cmp: 0.85, vst: 0.8, col: 0.75, san: 0.75, tmp: 0.7, ord: 0.6, soc: 0.6, opn: 0.15 } },
  { name: 'L\'espadon', tag: 'Une arme au bout du nez', color: '#38566b', cat: 'Mers et océans',
    desc: 'Il fonce dans un banc de poissons en frappant de son rostre, puis revient ramasser ce qu\'il a assommé. Il réchauffe ses yeux et son cerveau pour voir mieux dans l\'eau froide. Rapide, solitaire, entièrement conçu pour l\'attaque.',
    t: { aud: 0.95, cmp: 0.95, ind: 0.9, det: 0.95, san: 0.8, cfl: 0.9, soc: 0.15, rsk: 0.9, emp: 0.2, vig: 0.85 } },
  { name: 'Le narval', tag: 'La licorne des glaces', color: '#8ea9c1', cat: 'Mers et océans',
    desc: 'Sa défense est une dent gauche de trois mètres, criblée de terminaisons nerveuses, qui lui sert de capteur autant que d\'ornement. Il vit sous la banquise, en groupe, dans un noir presque total. Son existence a nourri le mythe de la licorne pendant des siècles.',
    t: { col: 0.9, vig: 0.9, ouv: 0.8, san: 0.85, soc: 0.8, opn: 0.85, inc: 0.7, emp: 0.65, det: 0.85, vtr: 0.8 } },
  { name: 'Le béluga', tag: 'Le bavard blanc', color: '#dfe6ec', cat: 'Mers et océans',
    desc: 'On l\'appelle le canari des mers parce qu\'il siffle, claque et module en permanence pour parler aux siens. Son front souple change de forme selon ce qu\'il exprime. Sociable, curieux, il vient volontiers voir ce que font les bateaux.',
    t: { soc: 0.95, com: 0.95, ouv: 0.9, emp: 0.85, col: 0.9, opt: 0.85, care: 0.8, aud: 0.75, cfl: 0.1, att: 0.85 } },
  { name: 'Le cachalot', tag: 'La plongée dans le noir', color: '#4a4e55', cat: 'Mers et océans',
    desc: 'Il descend à deux mille mètres, retient son souffle une heure et chasse au son dans l\'obscurité totale. Il dort à la verticale, en groupe, et les femelles gardent les petits des autres pendant les plongées. Le plus grand cerveau de la planète, et personne ne sait vraiment ce qu\'il en fait.',
    t: { col: 0.9, det: 0.95, san: 0.9, tmp: 0.9, care: 0.85, ouv: 0.85, aud: 0.9, emp: 0.75, com: 0.8, vig: 0.85 } },
  { name: 'Le lamantin', tag: 'La lenteur végétarienne', color: '#9a9484', cat: 'Mers et océans',
    desc: 'Il broute des herbiers toute la journée, sans prédateur naturel et sans la moindre agressivité. Il se déplace à cinq kilomètres-heure et se blesse régulièrement sur les hélices parce qu\'il ne s\'écarte pas. Sa douceur est totale et lui coûte cher.',
    t: { san: 0.95, cfl: 0.02, emp: 0.8, ste: 0.95, care: 0.8, det: 0.6, soc: 0.6, thr: 0.15, aud: 0.2, vhe: 0.7 } },
  { name: 'Le phoque', tag: 'Maladroit dehors, parfait dedans', color: '#7d8a96', cat: 'Mers et océans',
    desc: 'Sur la plage, il rampe lourdement et dort les uns sur les autres ; dans l\'eau, il devient d\'une agilité stupéfiante. Il détecte le sillage d\'un poisson passé trente secondes plus tôt avec ses moustaches. Curieux, joueur, il suit les plongeurs par pur intérêt.',
    t: { vhe: 0.85, soc: 0.8, ouv: 0.85, vig: 0.9, san: 0.75, aud: 0.75, emp: 0.7, col: 0.75, det: 0.8, rig: 0.4 } },
  { name: 'L\'otarie', tag: 'L\'acrobate qui fait du bruit', color: '#8a6a4b', cat: 'Mers et océans',
    desc: 'Elle se dresse sur ses nageoires, grimpe sur les rochers, aboie sans interruption et vit en colonies tapageuses. Les mâles défendent un territoire pendant des semaines sans manger. Sociable, démonstrative, jamais discrète.',
    t: { soc: 0.95, com: 0.95, inf: 0.9, dom: 0.8, vhe: 0.85, col: 0.85, aud: 0.85, det: 0.85, cfl: 0.75, emp: 0.65 } },
  { name: 'Le morse', tag: 'La masse et les défenses', color: '#9c7b63', cat: 'Mers et océans',
    desc: 'Il pèse une tonne, se hisse sur la glace à la force de ses défenses et dort entassé avec des centaines de congénères. Il fouille le fond avec ses moustaches pour trouver des coquillages. Pacifique tant qu\'on ne touche pas au groupe, terrible ensuite.',
    t: { col: 0.95, ste: 0.9, dom: 0.8, care: 0.85, san: 0.8, cfl: 0.7, soc: 0.85, det: 0.85, vtr: 0.8, aud: 0.6 } },
  { name: 'Le poisson-globe', tag: 'Il se gonfle plutôt que fuir', color: '#c9b47e', cat: 'Mers et océans',
    desc: 'Mauvais nageur, il avale de l\'eau jusqu\'à tripler de volume et sortir ses épines quand on l\'inquiète. Il porte un poison mille fois plus puissant que le cyanure. Un mâle passe des jours à dessiner un cercle parfait dans le sable pour séduire.',
    t: { thr: 0.9, ind: 0.8, san: 0.6, rig: 0.7, cfl: 0.7, aud: 0.5, emp: 0.3, ouv: 0.6, det: 0.8, dip: 0.3 } },
  { name: 'Le requin-baleine', tag: 'Le géant inoffensif', color: '#41708a', cat: 'Mers et océans',
    desc: 'Plus grand poisson du monde, il filtre du plancton la bouche ouverte et laisse les plongeurs l\'approcher sans réagir. Il traverse des océans entiers, seul, à cinq kilomètres-heure. Sa taille n\'a jamais servi à faire peur à personne.',
    t: { san: 0.98, cfl: 0.02, ind: 0.9, tmp: 0.9, emp: 0.6, det: 0.85, ste: 0.9, dom: 0.3, soc: 0.3, vun: 0.8 } },
  { name: 'La guêpe', tag: 'Elle revient, et elle pique', color: '#e2b300', cat: 'Insectes et petites bêtes',
    desc: 'Contrairement à l\'abeille, elle peut piquer plusieurs fois et ne s\'en prive pas. Elle chasse d\'autres insectes, construit un nid de papier mâché et s\'invite à table sans se poser de question. Utile, mal-aimée, et pas du genre à reculer.',
    t: { aud: 0.9, cfl: 0.9, det: 0.9, col: 0.85, emp: 0.15, thr: 0.8, dom: 0.75, vco: 0.7, dip: 0.1, ouv: 0.7 } },
  { name: 'Le frelon', tag: 'La force du nombre, en gros', color: '#9c5f1e', cat: 'Insectes et petites bêtes',
    desc: 'Il attaque des ruches entières en petit commando et ne lâche pas tant que la colonie adverse n\'a pas cédé. Il défend son nid sur plusieurs mètres et poursuit l\'intrus longtemps. Sa réputation dépasse largement sa dangerosité réelle.',
    t: { dom: 0.9, cfl: 0.95, col: 0.85, det: 0.95, thr: 0.85, emp: 0.1, aud: 0.9, cmp: 0.9, vig: 0.85, dip: 0.05 } },
  { name: 'Le bourdon', tag: 'Lourd, et il vole quand même', color: '#c8a23a', cat: 'Insectes et petites bêtes',
    desc: 'Trop gros pour ses ailes selon la légende, il vole par temps froid quand les abeilles restent au chaud et féconde ce que personne d\'autre ne touche. Il est doux, lent, et ne pique presque jamais. Il travaille dans des conditions que les autres refusent.',
    t: { det: 0.9, fia: 0.9, care: 0.75, san: 0.85, col: 0.8, emp: 0.65, cfl: 0.1, aud: 0.75, opt: 0.8, ste: 0.85 } },
  { name: 'La libellule', tag: 'Le chasseur le plus efficace du monde', color: '#22a3c4', cat: 'Insectes et petites bêtes',
    desc: 'Elle attrape sa proie dans neuf cas sur dix, ce qu\'aucun grand prédateur n\'approche. Elle vole en arrière, sur le côté, sur place, et anticipe la trajectoire de sa cible. Ses yeux couvrent presque trois cent soixante degrés.',
    t: { vig: 0.98, det: 0.95, rig: 0.9, aud: 0.9, ind: 0.9, san: 0.85, cmp: 0.95, ouv: 0.8, soc: 0.2, emp: 0.15 } },
  { name: 'La coccinelle', tag: 'Jolie, et carnivore', color: '#d0332c', cat: 'Insectes et petites bêtes',
    desc: 'Elle a une réputation de porte-bonheur et dévore plusieurs milliers de pucerons dans sa vie. Ses couleurs vives annoncent qu\'elle a mauvais goût, et elle laisse un liquide âcre quand on l\'embête. Elle passe l\'hiver entassée à des centaines sous une écorce.',
    t: { det: 0.85, opt: 0.8, thr: 0.5, col: 0.75, aud: 0.7, emp: 0.35, vig: 0.8, soc: 0.7, cmp: 0.75, san: 0.75 } },
  { name: 'Le bousier', tag: 'Il roule sa boule, coûte que coûte', color: '#4a4034', cat: 'Insectes et petites bêtes',
    desc: 'Il façonne une boule bien plus grosse que lui et la pousse en ligne droite, en se repérant sur la Voie lactée. Si on la lui vole, il en refait une. Il recycle à lui seul des tonnes de matière et personne ne le remercie.',
    t: { det: 0.98, fia: 0.95, rig: 0.9, ind: 0.85, tmp: 0.8, ord: 0.85, vac: 0.4, opt: 0.7, san: 0.85, soc: 0.2 } },
  { name: 'La cigale', tag: 'Dix-sept ans sous terre, un été dehors', color: '#8a9a5b', cat: 'Insectes et petites bêtes',
    desc: 'Certaines espèces passent dix-sept ans sous terre avant de sortir toutes ensemble, chanter quelques semaines et mourir. Le mâle produit un bruit assourdissant avec son abdomen. Toute une vie de préparation pour un seul été.',
    t: { tmp: 0.95, com: 0.95, vhe: 0.85, col: 0.85, det: 0.9, san: 0.7, soc: 0.8, ind: 0.4, opt: 0.8, vst: 0.6 } },
  { name: 'Le grillon', tag: 'Le bruit dans le noir', color: '#6b6248', cat: 'Insectes et petites bêtes',
    desc: 'Il frotte ses ailes pour appeler, accélère quand il fait chaud au point qu\'on peut lire la température dans son chant, et se tait dès qu\'on approche. Il tient un terrier et se bat pour le garder. Solitaire, sonore, méfiant.',
    t: { com: 0.9, ind: 0.85, opn: 0.85, vig: 0.9, cfl: 0.75, thr: 0.8, det: 0.8, soc: 0.4, san: 0.6, dom: 0.7 } },
  { name: 'La sauterelle', tag: 'Elle saute avant de réfléchir', color: '#7fb241', cat: 'Insectes et petites bêtes',
    desc: 'Elle franchit vingt fois sa longueur d\'un coup de patte, sans savoir exactement où elle atterrit. Elle mange des feuilles, chante avec ses pattes et disparaît dès qu\'une ombre passe. Sa réponse à tout est le départ immédiat.',
    t: { aud: 0.85, thr: 0.85, vst: 0.8, ind: 0.8, san: 0.35, rsk: 0.8, ord: 0.25, det: 0.7, soc: 0.4, opt: 0.7 } },
  { name: 'Le criquet pèlerin', tag: 'Seul, puis en nuage', color: '#c2a45a', cat: 'Insectes et petites bêtes',
    desc: 'Isolé, il est discret et solitaire ; à plusieurs, il change de couleur, de forme et de comportement, et forme des essaims de plusieurs milliards. Le groupe transforme littéralement l\'individu. Il dévore l\'équivalent de son poids chaque jour.',
    t: { col: 0.95, chg: 0.9, loc: 0.85, det: 0.9, soc: 0.85, ind: 0.15, dog: 0.7, aud: 0.85, emp: 0.15, vst: 0.8 } },
  { name: 'Le termite', tag: 'L\'architecte aveugle', color: '#a88f6a', cat: 'Insectes et petites bêtes',
    desc: 'Sans plan ni chef, une colonie bâtit des tours de plusieurs mètres avec une ventilation naturelle que des architectes copient. Chaque individu suit trois règles simples. L\'intelligence est entièrement dans le collectif.',
    t: { col: 0.98, fia: 0.95, ord: 0.95, rig: 0.9, tmp: 0.9, ind: 0.05, vco: 0.95, det: 0.9, soc: 0.8, vac: 0.2 } },
  { name: 'Le moustique', tag: 'L\'insistance qui réveille', color: '#6b6b6b', cat: 'Insectes et petites bêtes',
    desc: 'Il repère le gaz carbonique d\'une respiration à dix mètres, revient dès qu\'on s\'assoupit et choisit sa cible à l\'odeur. C\'est l\'animal qui tue le plus d\'humains sur terre. Son obstination est sans égale et son timing, insupportable.',
    t: { det: 0.95, vig: 0.9, aud: 0.9, emp: 0.02, ind: 0.85, nat: 0.8, thr: 0.7, cmp: 0.85, rig: 0.6, care: 0.05 } },
  { name: 'La mouche', tag: 'Elle voit venir le geste', color: '#5a6068', cat: 'Insectes et petites bêtes',
    desc: 'Son œil traite l\'image cinq fois plus vite que le nôtre, ce qui lui laisse tout le temps de décoller avant la main. Elle goûte avec ses pattes et se pose exactement où il ne faut pas. Increvable, agaçante, et redoutablement rapide.',
    t: { vig: 0.98, aud: 0.9, san: 0.5, ouv: 0.8, ind: 0.85, thr: 0.85, det: 0.8, rig: 0.15, emp: 0.1, chg: 0.85 } },
  { name: 'La blatte', tag: 'Elle survivra à tout', color: '#4b3a2c', cat: 'Insectes et petites bêtes',
    desc: 'Elle tient un mois sans manger, une semaine sans tête, et se faufile dans une fente de trois millimètres. Elle fuit la lumière et revient dès qu\'on éteint. Son seul projet est de continuer, et elle y arrive depuis trois cents millions d\'années.',
    t: { det: 0.98, thr: 0.9, vig: 0.9, san: 0.8, opn: 0.7, ind: 0.85, vse: 0.9, emp: 0.05, soc: 0.5, inc: 0.7 } },
  { name: 'Le scorpion', tag: 'Il brille sous les ultraviolets', color: '#8a6a3a', cat: 'Insectes et petites bêtes',
    desc: 'Il attend des heures immobile, sent les vibrations du sable et n\'utilise son dard qu\'en dernier recours, parce que le venin coûte cher à fabriquer. Il jeûne parfois un an. Il est là depuis plus longtemps que les dinosaures.',
    t: { san: 0.95, tmp: 0.9, ind: 0.95, thr: 0.85, det: 0.9, vig: 0.9, emp: 0.1, soc: 0.05, rig: 0.85, opn: 0.85 } },
  { name: 'Le mille-pattes', tag: 'Tout coordonner sans y penser', color: '#7a4a3a', cat: 'Insectes et petites bêtes',
    desc: 'Il synchronise des centaines de pattes en vagues régulières, sans jamais s\'emmêler. Il avance lentement, se roule en spirale au moindre contact et dégage une substance qui décourage. Sa défense est de se fermer, pas de frapper.',
    t: { ord: 0.95, rig: 0.9, san: 0.85, thr: 0.85, ind: 0.85, cfl: 0.1, det: 0.8, soc: 0.15, fia: 0.85, aud: 0.25 } },
  { name: 'L\'escargot', tag: 'Il emmène sa maison', color: '#b39f74', cat: 'Insectes et petites bêtes',
    desc: 'Il avance à quelques mètres par heure, se referme quand le temps ne convient pas et attend parfois des mois que ça s\'arrange. Il répare lui-même sa coquille fissurée. Rien ne le presse, jamais, et il traverse les saisons sans jamais changer de rythme pour qui que ce soit.',
    t: { san: 0.95, tmp: 0.9, vse: 0.9, ind: 0.85, det: 0.85, thr: 0.7, ste: 0.95, soc: 0.2, aud: 0.1, opn: 0.85 } },
  { name: 'La limace', tag: 'Sans protection, et elle continue', color: '#7d7a5e', cat: 'Insectes et petites bêtes',
    desc: 'Elle a abandonné la coquille, ce qui la rend vulnérable mais lui permet de passer partout et de se glisser sous terre. Elle suit sa propre trace pour rentrer et mange presque tout. Sa stratégie est l\'accès, pas la sécurité.',
    t: { ouv: 0.8, det: 0.85, vse: 0.15, ind: 0.8, thr: 0.5, san: 0.85, soc: 0.2, aud: 0.6, rsk: 0.75, opn: 0.7 } },
  { name: 'Le ver de terre', tag: 'Le travail qu\'on ne voit pas', color: '#a8746b', cat: 'Insectes et petites bêtes',
    desc: 'Il retourne des tonnes de sol par hectare et par an, creuse des galeries qui laissent passer l\'eau, et personne ne s\'en aperçoit. Coupé, il survit parfois. Toute la fertilité d\'un champ dépend de son travail silencieux.',
    t: { fia: 0.98, det: 0.95, col: 0.8, soc: 0.1, vac: 0.05, tmp: 0.9, ste: 0.95, care: 0.7, com: 0.02, san: 0.9 } },
  { name: 'La puce', tag: 'Petite, et elle saute cent fois sa taille', color: '#5c4636', cat: 'Insectes et petites bêtes',
    desc: 'Elle bondit deux cents fois sa longueur grâce à un ressort de protéine, accélère plus fort qu\'une fusée et s\'accroche à ce qui passe. Elle a changé le cours de l\'histoire humaine en transportant la peste. Minuscule et considérable.',
    t: { aud: 0.95, det: 0.9, ind: 0.85, loc: 0.6, vst: 0.85, emp: 0.05, thr: 0.7, cmp: 0.8, vac: 0.6, rsk: 0.9 } },
  { name: 'Le phasme', tag: 'Il est là depuis le début', color: '#8d9068', cat: 'Insectes et petites bêtes',
    desc: 'Il imite une brindille au point de se balancer comme une branche dans le vent, et reste immobile des heures. Certaines femelles se reproduisent sans mâle. Sa survie repose entièrement sur le fait de ne pas être remarqué.',
    t: { san: 0.95, thr: 0.85, ind: 0.9, soc: 0.05, vig: 0.85, rig: 0.85, det: 0.8, com: 0.02, aud: 0.15, vse: 0.85 } },
  { name: 'Le papillon de nuit', tag: 'Attiré par ce qui le brûle', color: '#6a5f6e', cat: 'Insectes et petites bêtes',
    desc: 'Il navigue à la lune depuis des millions d\'années, ce qui le fait tourner en rond autour des ampoules. Le mâle détecte une femelle à plusieurs kilomètres à l\'odeur. Il suit un repère fiable devenu un piège.',
    t: { det: 0.9, loc: 0.8, ide: 0.75, vig: 0.85, ind: 0.8, thr: 0.4, san: 0.4, dog: 0.7, att: 0.8, rsk: 0.85 } },
  { name: 'Le ver à soie', tag: 'Il fabrique, puis il se ferme', color: '#dcd3b4', cat: 'Insectes et petites bêtes',
    desc: 'Il produit un fil unique de plus d\'un kilomètre et s\'enferme dedans pour se transformer. Domestiqué depuis cinq mille ans, il ne sait plus survivre sans les humains. Son travail est prodigieux et sa dépendance, totale.',
    t: { fia: 0.95, rig: 0.9, det: 0.9, ind: 0.1, loc: 0.85, ord: 0.9, vco: 0.9, soc: 0.3, tmp: 0.8, vac: 0.5 } },
  { name: 'La veuve noire', tag: 'Discrète et sans pitié', color: '#2e2b33', cat: 'Insectes et petites bêtes',
    desc: 'Elle reste dans un coin sombre, tisse une toile désordonnée et n\'attaque à peu près jamais un humain sauf si on l\'écrase. La femelle dévore parfois le mâle après l\'accouplement, quand elle a faim. Sa réputation est très supérieure à son agressivité.',
    t: { ind: 0.95, san: 0.9, thr: 0.8, emp: 0.05, vig: 0.9, soc: 0.05, det: 0.85, rig: 0.8, cmp: 0.85, nat: 0.9 } },
];

window.PRISME_ANIMALS = { ANIMALS };
