/* ============================================================
   PRISME — « Si tu étais une entreprise »
   ------------------------------------------------------------
   Ni leurs produits préférés ni leur cours de Bourse : le tempérament
   qu'une entreprise renvoie — sa culture, son style, sa façon de faire —
   tel que le public la connaît, avec ses légendes de garage, ses manies
   et ses fiertés. Des faits exacts, de l'affection, aucune polémique.
     name = l'entreprise, by = pays · secteur, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const BRANDS = [
  { name: 'Apple', by: 'États-Unis · technologie', tag: 'Le détail qui change tout', color: '#8e9297',
    desc: 'Née en 1976 dans le garage des parents de Steve Jobs, avec Steve Wozniak, elle soigne jusqu\'à l\'intérieur des machines que personne ne verra. Ses nouveautés restent secrètes jusqu\'au dernier moment, puis on les dévoile sur scène. C\'est le tempérament des perfectionnistes esthètes, qui veulent tout maîtriser, ne montrent rien avant que ce soit parfait et préfèrent un seul bon choix à dix moyens.',
    t: { rig: 0.95, ide: 0.85, con: 0.85, ord: 0.9, soc: 0.2, nat: 0.8, inf: 0.3, col: 0.15, dip: 0.3, vpo: 0.8, vhe: 0.7 } },
  { name: 'Google', by: 'États-Unis · internet', tag: 'Une question ? Tant mieux', color: '#4285f4',
    desc: 'Fondée en 1998 dans un garage de Californie par deux étudiants de Stanford, Larry Page et Sergey Brin, elle tire son nom du « googol », un 1 suivi de cent zéros. Elle a longtemps laissé ses ingénieurs consacrer une part de leur temps à leurs propres projets. C\'est le tempérament des curieux insatiables, qui veulent tout savoir, testent sans cesse et trouvent qu\'une idée bizarre mérite toujours un essai.',
    t: { ouv: 0.98, inc: 0.9, aff: 0.9, vst: 0.85, chg: 0.85, ord: 0.25, vtr: 0.08, vse: 0.2, dog: 0.05, ide: 0.8 } },
  { name: 'Microsoft', by: 'États-Unis · logiciels', tag: 'Sérieux, présent, indispensable', color: '#00a4ef',
    desc: 'Fondée en 1975 par Bill Gates et Paul Allen, elle a mis Windows et ses tableurs sur les bureaux du monde entier. Pas de mystère ni de grand spectacle : des outils qu\'on ouvre chaque matin et qui doivent marcher. C\'est le tempérament des pragmatiques travailleurs, sérieux et endurants, qui ne cherchent pas à briller mais à être là, fiables, jour après jour, pendant des décennies.',
    t: { fia: 0.9, vac: 0.85, epi: 0.08, vst: 0.2, ide: 0.2, vse: 0.8, con: 0.8, inf: 0.2, tmp: 0.85, vhe: 0.2, cmp: 0.75 } },
  { name: 'Amazon', by: 'États-Unis · commerce en ligne', tag: 'Livré demain, pensé pour dans dix ans', color: '#ff9900',
    desc: 'Tout commence en 1994 dans un garage près de Seattle, où Jeff Bezos lance une librairie en ligne. L\'entreprise se répète qu\'elle en est toujours à son « premier jour », et parle du client avant de parler d\'elle. C\'est le tempérament des bâtisseurs infatigables, obsédés par l\'efficacité, qui visent loin, mesurent tout et considèrent qu\'on peut toujours aller plus vite.',
    t: { tmp: 0.95, det: 0.95, vac: 0.95, dom: 0.9, cmp: 0.95, rig: 0.8, emp: 0.2, vhe: 0.15, vtr: 0.1, att: 0.2 } },
  { name: 'Tesla', by: 'États-Unis · automobile', tag: 'La voiture de demain, dès aujourd\'hui', color: '#cc0000',
    desc: 'Fondée en 2003 et baptisée en hommage à l\'inventeur Nikola Tesla, elle a fait de la voiture électrique un objet de désir et ajoute des fonctions à ses modèles par simple mise à jour, comme un téléphone. C\'est le tempérament des audacieux qui misent tout sur l\'avenir, bousculent les habitudes, prennent des risques que d\'autres jugent fous et aiment qu\'on parle d\'eux.',
    t: { aud: 0.95, rsk: 0.95, chg: 0.98, vst: 0.9, vtr: 0.05, vse: 0.1, dip: 0.2, inf: 0.85, vis: 0.05, ste: 0.15 } },
  { name: 'Netflix', by: 'États-Unis · streaming', tag: 'Encore un épisode, promis', color: '#e50914',
    desc: 'Elle a commencé en 1997 en louant des DVD par la poste, avant de basculer vers le streaming en 2007. Sa culture interne tient en deux mots, liberté et responsabilité, et elle a fait entrer le verbe « binger » dans le vocabulaire. C\'est le tempérament des épicuriens du canapé, libres de leur emploi du temps, qui aiment se laisser emporter par une histoire et remettent la vaisselle à demain.',
    t: { vhe: 0.95, lib: 0.85, vsd: 0.8, tmp: 0.1, ord: 0.15, rig: 0.15, soc: 0.3, vac: 0.2, loc: 0.7, det: 0.3 } },
  { name: 'Spotify', by: 'Suède · musique', tag: 'La bande-son de ta vie', color: '#1db954',
    desc: 'Née à Stockholm en 2006, elle a mis presque toute la musique du monde dans une poche. Chaque fin d\'année, son bilan personnalisé des écoutes fait le tour des réseaux, chacun comparant ses artistes favoris. C\'est le tempérament des mélomanes sociables, qui ont une chanson pour chaque humeur, partagent leurs découvertes et adorent qu\'on les connaisse par leurs goûts.',
    t: { inf: 0.9, soc: 0.9, vhe: 0.85, ouv: 0.8, vst: 0.8, con: 0.15, vtr: 0.2, ord: 0.3, san: 0.4, aff: 0.2 } },
  { name: 'Nintendo', by: 'Japon · jeu vidéo', tag: 'Jouer, avant tout', color: '#e60012',
    desc: 'Fondée à Kyoto en 1889 pour fabriquer des cartes à jouer, elle a donné naissance à Mario, Zelda et Pokémon. Plutôt que la course à la puissance, elle préfère inventer de nouvelles façons de jouer, souvent avec une technologie toute simple. C\'est le tempérament des joueurs au cœur d\'enfant, fidèles à leurs racines, créatifs sans esbroufe, qui préfèrent faire rire tout le monde que gagner seuls.',
    t: { ide: 0.9, opt: 0.9, vhe: 0.8, vtr: 0.8, cmp: 0.15, dom: 0.15, vpo: 0.1, nat: 0.2, att: 0.8, chg: 0.35 } },
  { name: 'Sony', by: 'Japon · électronique', tag: 'L\'ingénieur qui a du style', color: '#3a3a3a',
    desc: 'Fondée à Tokyo en 1946 par Masaru Ibuka et Akio Morita, elle a inventé le Walkman en 1979, puis lancé la PlayStation en 1994. Son nom mêle le latin « sonus » et l\'anglais « sonny ». C\'est le tempérament des ingénieurs élégants, calmes et exigeants, qui aiment la belle technique, le son parfait et les objets qui changent les habitudes sans faire de bruit.',
    t: { rig: 0.85, san: 0.9, ouv: 0.8, vhe: 0.75, soc: 0.25, inf: 0.25, att: 0.3, cfl: 0.2, vac: 0.8, aff: 0.8 } },
  { name: 'LEGO', by: 'Danemark · jouets', tag: 'Brique après brique', color: '#d01012',
    desc: 'Ole Kirk Christiansen, menuisier de Billund, fabrique des jouets en bois dès 1932 et les baptise d\'après le danois « leg godt », joue bien. La fameuse brique qui s\'emboîte date de 1958, et celles d\'aujourd\'hui s\'emboîtent encore avec elle. C\'est le tempérament des bâtisseurs patients, méthodiques et créatifs, qui suivent le plan à la lettre avant d\'inventer le leur.',
    t: { ide: 0.9, ord: 0.95, ste: 0.9, con: 0.8, rig: 0.85, vpo: 0.1, cfl: 0.1, cmp: 0.2, dom: 0.2, aud: 0.25 } },
  { name: 'IKEA', by: 'Suède · ameublement', tag: 'Débrouille-toi, c\'est plus malin', color: '#0058a3',
    desc: 'Ingvar Kamprad la fonde en 1943, à dix-sept ans ; le nom réunit ses initiales, sa ferme et son village. Dans les années 1950, un employé démonte les pieds d\'une table pour la faire entrer dans une voiture : le meuble en kit est né. C\'est le tempérament des débrouillards pratiques et sans chichis, qui aiment la simplicité, les prix justes et la fierté d\'avoir monté soi-même.',
    t: { epi: 0.05, vpo: 0.05, fair: 0.85, vsd: 0.85, ord: 0.75, col: 0.7, vhe: 0.3, inf: 0.3, ide: 0.7, dom: 0.25 } },
  { name: 'Decathlon', by: 'France · sport', tag: 'Le sport, pour tout le monde', color: '#0082c3',
    desc: 'Le premier magasin ouvre en 1976 à Englos, près de Lille, à l\'initiative de Michel Leclercq. L\'enseigne a créé ses propres marques pour chaque discipline et une tente qui se déplie toute seule en deux secondes. C\'est le tempérament des enthousiastes du dehors, qui essaient tous les sports, préfèrent le plaisir de bouger à la performance et veulent que personne ne reste sur le banc.',
    t: { vst: 0.85, opt: 0.9, soc: 0.8, col: 0.8, fair: 0.8, vpo: 0.05, epi: 0.1, cmp: 0.25, thr: 0.1, vac: 0.3 } },
  { name: 'Michelin', by: 'France · pneumatiques', tag: 'L\'exigence, étoile par étoile', color: '#27509b',
    desc: 'Fondée en 1889 à Clermont-Ferrand par les frères André et Édouard Michelin, elle a imaginé Bibendum en 1898 et un petit guide pour les automobilistes en 1900, devenu la référence des étoiles de la gastronomie. C\'est le tempérament des exigeants discrets, attachés à leur ville, qui prennent le temps de bien faire et dont le jugement, rare, vaut une médaille.',
    t: { rig: 0.95, vtr: 0.85, opn: 0.75, fia: 0.95, inf: 0.2, chg: 0.15, vst: 0.25, con: 0.85, tmp: 0.85, aud: 0.25 } },
  { name: 'Renault', by: 'France · automobile', tag: 'La voiture de toute la famille', color: '#efc300',
    desc: 'Louis Renault construit sa première voiturette en 1898 à Boulogne-Billancourt, et fonde l\'entreprise avec ses frères Marcel et Fernand. Suivront la 4L, vendue à plus de huit millions d\'exemplaires, l\'Espace, premier monospace européen, et la Twingo au sourire rond. C\'est le tempérament des bons vivants familiaux et astucieux, qui pensent à la place pour les enfants avant de penser au chrome.',
    t: { att: 0.8, vbe: 0.85, soc: 0.75, epi: 0.15, vpo: 0.15, ide: 0.7, opt: 0.8, rig: 0.3, cmp: 0.3, dom: 0.3 } },
  { name: 'Peugeot', by: 'France · automobile', tag: 'Deux siècles de ténacité', color: '#1b2a4a',
    desc: 'Avant les voitures, la famille Peugeot fabriquait dès 1810 de l\'acier, des outils, des scies et des moulins à poivre, qu\'elle fabrique toujours. Le lion est son emblème depuis le milieu du XIXe siècle. C\'est le tempérament des persévérants loyaux, attachés à leur nom et à leur région, qui savent se réinventer sans jamais renier d\'où ils viennent.',
    t: { vtr: 0.9, loy: 0.9, det: 0.85, tmp: 0.9, opn: 0.8, chg: 0.2, vst: 0.25, inf: 0.3, rsk: 0.3, lib: 0.3 } },
  { name: 'Airbus', by: 'Europe · aéronautique', tag: 'Ensemble, on vole plus loin', color: '#00205b',
    desc: 'Née en 1970 de l\'alliance d\'industriels français et allemands, rejoints ensuite par l\'Espagne et le Royaume-Uni, elle assemble ses avions à Toulouse avec des pièces venues de toute l\'Europe, transportées dans l\'étonnant Beluga. C\'est le tempérament des bâtisseurs d\'équipe, qui croient qu\'on va plus haut à plusieurs, négocient patiemment et aiment les projets qui durent des décennies.',
    t: { col: 0.95, dip: 0.9, vac: 0.85, opn: 0.05, tmp: 0.9, rig: 0.9, ind: 0.15, vhe: 0.2, lea: 0.8, cfl: 0.3 } },
  { name: 'SNCF', by: 'France · transport ferroviaire', tag: 'Tout le monde à bord', color: '#a1006b',
    desc: 'Créée en 1938 en réunissant les grandes compagnies de chemin de fer, elle a lancé le TGV en 1981 et détient le record du monde de vitesse sur rail, 574,8 km/h, établi en 2007. Chaque jour, des millions de voyageurs montent dans ses trains. C\'est le tempérament des amoureux du collectif et du service public, fiers de leur métier, qui veulent emmener tout le monde, partout, ensemble.',
    t: { col: 0.95, fair: 0.9, auth: 0.7, vse: 0.75, loy: 0.85, ind: 0.1, vpo: 0.2, cmp: 0.2, eng: 0.75, vsd: 0.2 } },
  { name: 'La Poste', by: 'France · courrier et services', tag: 'Passe tous les jours, même quand il pleut', color: '#ffc72c',
    desc: 'Héritière des relais de poste créés sous Louis XI, elle passe presque chaque jour dans chaque rue de France. Ses facteurs connaissent les chiens, les boîtes aux lettres cabossées et les voisins, et rendent même visite aux personnes âgées isolées. C\'est le tempérament des fidèles bienveillants, réguliers comme une horloge, qui ne font pas de bruit mais sur qui tout le quartier compte.',
    t: { fia: 0.98, att: 0.85, vbe: 0.9, ste: 0.95, vtr: 0.8, aud: 0.1, vst: 0.1, cmp: 0.1, dom: 0.1, vac: 0.2 } },
  { name: 'Air France', by: 'France · transport aérien', tag: 'L\'élégance à dix mille mètres', color: '#002157',
    desc: 'Créée en 1933 avec pour emblème un hippocampe ailé, affectueusement surnommé « la crevette », elle a fait voler le Concorde de 1976 à 2003. Uniformes signés par de grands couturiers, menus de chefs : elle emporte un peu de la France dans ses bagages. C\'est le tempérament des voyageurs élégants, ouverts sur le monde mais fiers de leurs manières, qui soignent les détails jusqu\'au bout.',
    t: { opn: 0.05, vpo: 0.75, vtr: 0.75, con: 0.85, vhe: 0.75, dip: 0.85, cfl: 0.15, epi: 0.3, ind: 0.3, loc: 0.4 } },
  { name: 'L\'Oréal', by: 'France · cosmétiques', tag: 'La confiance, version science', color: '#2b2b2b',
    desc: 'Fondée en 1909 par un jeune chimiste qui mettait au point des teintures pour cheveux, elle est devenue le premier groupe de cosmétiques au monde. Elle mise sur ses laboratoires autant que sur ses égéries. C\'est le tempérament des ambitieux sûrs d\'eux, qui soignent leur image avec méthode, aiment gagner et considèrent que prendre soin de soi n\'a rien de frivole.',
    t: { vac: 0.95, inf: 0.85, vpo: 0.85, cmp: 0.9, aff: 0.75, rig: 0.8, vtr: 0.3, vun: 0.25, ste: 0.3, loc: 0.1 } },
  { name: 'Chanel', by: 'France · mode', tag: 'Libre, et chic avec ça', color: '#111111',
    desc: 'Gabrielle Chanel ouvre sa première boutique rue Cambon en 1910. Elle libère les femmes du corset, invente le N°5 en 1921 et la petite robe noire en 1926. La maison cultive depuis une élégance sobre et indépendante. C\'est le tempérament des libres et des affranchis, qui imposent leur style sans demander la permission, préfèrent l\'épure au tapage et ne suivent jamais la foule.',
    t: { ind: 0.95, vsd: 0.95, chg: 0.85, aud: 0.85, dom: 0.85, att: 0.2, col: 0.1, vco: 0.1, soc: 0.35, emp: 0.35 } },
  { name: 'Hermès', by: 'France · maroquinerie', tag: 'Le temps de bien faire', color: '#f37021',
    desc: 'Thierry Hermès ouvre en 1837 un atelier de harnais et de selles à Paris. Le carré de soie arrive en 1937, le sac Birkin en 1984 après une rencontre dans un avion avec Jane Birkin. Un seul artisan réalise souvent un sac de bout en bout. C\'est le tempérament des artisans patients, discrets et exigeants, qui refusent de se presser et savent que le vrai luxe, c\'est le temps.',
    t: { rig: 0.95, tmp: 0.98, vtr: 0.95, inf: 0.1, vst: 0.15, rsk: 0.1, ste: 0.85, chg: 0.05, com: 0.1, soc: 0.2 } },
  { name: 'Louis Vuitton', by: 'France · maroquinerie', tag: 'Le monde est une malle à remplir', color: '#6b4a2b',
    desc: 'Louis Vuitton, malletier, ouvre sa maison à Paris en 1854 et invente la malle plate, que l\'on peut empiler dans les trains et les paquebots. Son fils Georges crée la toile Monogram en 1896. C\'est le tempérament des grands voyageurs ambitieux, qui aiment le mouvement, la réussite qui se voit et les belles choses qui annoncent qu\'on arrive de loin.',
    t: { vpo: 0.95, opn: 0.1, vst: 0.85, vac: 0.9, inf: 0.8, vun: 0.15, emp: 0.3, ste: 0.25, cmp: 0.85, vhe: 0.8 } },
  { name: 'Danone', by: 'France · alimentation', tag: 'Prendre soin, cuillère après cuillère', color: '#0068b3',
    desc: 'Tout commence en 1919 à Barcelone, où Isaac Carasso vend ses yaourts en pharmacie. Il baptise son entreprise du surnom catalan de son fils Daniel, « Danon ». Depuis, la marque a gardé cette idée : ce qu\'on mange, c\'est aussi une façon de prendre soin. C\'est le tempérament des bienveillants attentifs, qui pensent santé avant plaisir et veillent sur les autres sans en faire des tonnes.',
    t: { care: 0.95, vbe: 0.85, vun: 0.85, emp: 0.85, dom: 0.15, cmp: 0.25, vhe: 0.25, rsk: 0.2, vig: 0.75, aud: 0.2 } },
  { name: 'Bonne Maman', by: 'France · confitures', tag: 'Le goût du dimanche chez mamie', color: '#c8102e',
    desc: 'Lancée en 1971 à Biars-sur-Cère, dans le Lot, elle a choisi dès le départ son couvercle à carreaux vichy rouges et son étiquette écrite comme à la main. Confitures, madeleines, crèmes : tout évoque le goûter d\'autrefois. C\'est le tempérament des tendres nostalgiques, qui aiment les rituels, les recettes transmises et les maisons où la porte est toujours ouverte.',
    t: { vtr: 0.95, att: 0.95, vbe: 0.9, vhe: 0.8, chg: 0.05, vst: 0.1, aud: 0.1, cmp: 0.1, aff: 0.1, vac: 0.15 } },
  { name: 'Carambar', by: 'France · confiserie', tag: 'Une blague sous chaque papier', color: '#f5b700',
    desc: 'Né en 1954 à Marcq-en-Barœul, près de Lille, le bâton de caramel cache depuis des décennies des blagues et des devinettes dans son emballage. En 2013, la marque a fait croire qu\'elle arrêtait les blagues, avant d\'avouer le canular. C\'est le tempérament des farceurs au grand cœur, qui ne prennent rien trop au sérieux, font rire les enfants comme les grands et vivent l\'instant.',
    t: { inf: 0.95, vhe: 0.9, opt: 0.9, soc: 0.9, rig: 0.1, tmp: 0.05, ord: 0.15, vpo: 0.1, con: 0.15, vig: 0.15 } },
  { name: 'Coca-Cola', by: 'États-Unis · boissons', tag: 'La même recette, la même fête', color: '#f40009',
    desc: 'Inventée en 1886 à Atlanta par le pharmacien John Pemberton, sa recette reste l\'un des secrets les mieux gardés du monde. Sa bouteille galbée de 1915 a été dessinée pour être reconnue même dans le noir. C\'est le tempérament des fêtards fidèles, présents à tous les anniversaires, qui aiment rassembler, ne changent jamais la recette et gardent quelques secrets pour eux.',
    t: { soc: 0.95, inf: 0.9, vtr: 0.85, chg: 0.05, vhe: 0.9, opt: 0.85, aff: 0.2, ide: 0.3, vun: 0.25, rig: 0.3 } },
  { name: 'Nutella', by: 'Italie · pâte à tartiner', tag: 'Un réconfort, une cuillère', color: '#5a3a22',
    desc: 'Dans l\'Italie d\'après-guerre, le cacao coûte cher : en 1946, Pietro Ferrero, pâtissier d\'Alba, le mélange aux noisettes du Piémont. La pâte deviendra Nutella en 1964, et ses fans ont même inventé une journée mondiale en son honneur. C\'est le tempérament des gourmands réconfortants, qui savent se faire plaisir, partagent volontiers et ne résistent pas à une dernière cuillère.',
    t: { vhe: 0.98, att: 0.85, vbe: 0.8, rig: 0.1, vac: 0.15, tmp: 0.1, vig: 0.15, con: 0.25, san: 0.3, dom: 0.2 } },
  { name: 'Nespresso', by: 'Suisse · café', tag: 'Un rituel, et du style', color: '#3a2a1f',
    desc: 'Lancée par Nestlé en 1986, elle a transformé le café en capsule colorée, avec ses boutiques feutrées et son club de membres. Chaque tasse est un petit rituel : choisir l\'intensité, appuyer sur le bouton, savourer. C\'est le tempérament des raffinés pressés, qui aiment le confort, les habitudes bien réglées et les petits plaisirs exclusifs, pourvu que ce soit parfait du premier coup.',
    t: { vpo: 0.8, vhe: 0.85, ord: 0.85, con: 0.8, col: 0.15, vun: 0.15, fair: 0.3, epi: 0.35, soc: 0.4, rig: 0.75 } },
  { name: 'Starbucks', by: 'États-Unis · cafés', tag: 'Ton prénom sur le gobelet', color: '#00704a',
    desc: 'Ouverte en 1971 près du marché de Pike Place, à Seattle, elle doit son nom à un marin de Moby Dick et sa sirène aux légendes marines. Elle se voit comme un « troisième lieu », entre la maison et le travail, où l\'on écrit votre prénom sur le gobelet. C\'est le tempérament des sociables cosy, qui aiment qu\'on se souvienne de leur commande et font de chaque pause un petit moment à eux.',
    t: { soc: 0.9, att: 0.75, vhe: 0.8, inf: 0.8, vsd: 0.7, rig: 0.25, vtr: 0.2, vse: 0.65, cfl: 0.1, aud: 0.35 } },
  { name: 'McDonald\'s', by: 'États-Unis · restauration rapide', tag: 'Partout pareil, et c\'est rassurant', color: '#da291c',
    desc: 'Les frères Richard et Maurice McDonald ouvrent leur restaurant en 1940 en Californie, puis inventent en 1948 un système de cuisine réglé comme une chaîne. Ray Kroc en fera un réseau mondial à partir de 1955. C\'est le tempérament des organisés rassurants, qui aiment que chaque chose soit à sa place, les méthodes qui marchent et les bonnes habitudes qu\'on retrouve partout.',
    t: { ord: 0.95, con: 0.95, fia: 0.9, ide: 0.15, vst: 0.15, epi: 0.05, inc: 0.1, vse: 0.85, ouv: 0.3, vhe: 0.65 } },
  { name: 'Picard', by: 'France · surgelés', tag: 'Toujours un plan dans le congélateur', color: '#1f4e9c',
    desc: 'En 1906, Raymond Picard livre des pains de glace à Fontainebleau. Au début des années 1970, l\'entreprise se lance dans les surgelés et ses magasins blancs et froids deviennent un réflexe. C\'est le tempérament des prévoyants tranquilles, qui ont toujours de quoi recevoir, préfèrent anticiper que courir et dorment mieux en sachant qu\'il y a un plan B au frais.',
    t: { vse: 0.9, tmp: 0.85, ord: 0.9, vig: 0.9, rsk: 0.1, vst: 0.15, inf: 0.2, thr: 0.75, inc: 0.15, soc: 0.3 } },
  { name: 'Leroy Merlin', by: 'France · bricolage', tag: 'Je le fais moi-même', color: '#78be20',
    desc: 'En 1923, Adolphe Leroy et Rose Merlin ouvrent dans le Pas-de-Calais un « Stock américain » qui revend les surplus laissés par l\'armée des États-Unis. Le magasin deviendra le temple du bricolage, des ateliers et des conseils pour tout faire soi-même. C\'est le tempérament des autonomes pratiques, qui préfèrent réparer que racheter et comptent d\'abord sur leurs mains.',
    t: { vsd: 0.9, ind: 0.9, epi: 0.05, det: 0.85, loc: 0.05, soc: 0.3, vpo: 0.15, inf: 0.2, vhe: 0.3, aff: 0.75 } },
  { name: 'Fnac', by: 'France · culture', tag: 'Le rayon des curieux', color: '#e1a925',
    desc: 'Fondée en 1954 par André Essel et Max Théret sous le nom de Fédération nationale d\'achats des cadres, elle vendait d\'abord du matériel photo à prix serrés, avant de devenir le grand magasin des livres, des disques et des conseils de vendeurs passionnés. C\'est le tempérament des curieux cultivés, qui flânent d\'un rayon à l\'autre, aiment débattre et repartent toujours avec un livre de plus.',
    t: { ouv: 0.95, ide: 0.8, vst: 0.75, com: 0.75, aff: 0.75, vtr: 0.3, vpo: 0.2, ord: 0.3, vse: 0.25, eng: 0.65 } },
  { name: 'Darty', by: 'France · électroménager', tag: 'Il y a une panne ? On arrive', color: '#d6001c',
    desc: 'En 1957, trois frères, Natan, Marcel et Bernard Darty, transforment le magasin de tissus familial de Montreuil en boutique de radios et de télévisions. En 1973, ils promettent à leurs clients un service après-vente irréprochable, une idée encore rare. C\'est le tempérament des dépanneurs dévoués, calmes et fiables, qu\'on appelle quand plus rien ne marche et qui arrivent avec la solution.',
    t: { fia: 0.98, vbe: 0.8, ste: 0.85, san: 0.9, ide: 0.2, aud: 0.15, vst: 0.2, epi: 0.1, inf: 0.3, care: 0.8 } },
  { name: 'Le Bon Coin', by: 'France · petites annonces', tag: 'Tout se revend, tout se négocie', color: '#ff6e14',
    desc: 'Lancé en 2006, le site est devenu le grand vide-grenier des Français : on y trouve un canapé, un vélo, un appartement ou une collection de figurines rares. On y apprend à marchander, à flairer la bonne affaire et à ne pas se faire avoir. C\'est le tempérament des chineurs malins, économes et un brin méfiants, qui aiment négocier et donner une deuxième vie aux objets.',
    t: { epi: 0.1, vpo: 0.1, nat: 0.8, com: 0.8, cmp: 0.7, vsd: 0.8, ord: 0.25, vun: 0.7, att: 0.3, dip: 0.3 } },
  { name: 'BlaBlaCar', by: 'France · covoiturage', tag: 'Monte, on fait la route ensemble', color: '#00aff5',
    desc: 'L\'idée vient à Frédéric Mazzella à Noël 2003, faute de train pour rentrer en Vendée. Lancé en 2006, le service de covoiturage prend son nom actuel en 2013 : chacun y indique s\'il est plutôt Bla, BlaBla ou BlaBlaBla. C\'est le tempérament des confiants sociables, qui partagent volontiers, aiment les rencontres imprévues et pensent qu\'un inconnu est un ami qu\'on n\'a pas encore rencontré.',
    t: { nat: 0.05, soc: 0.95, col: 0.85, fair: 0.8, inf: 0.85, vse: 0.3, vpo: 0.1, cmp: 0.1, ouv: 0.85, thr: 0.1 } },
  { name: 'Doctolib', by: 'France · santé en ligne', tag: 'Rendez-vous pris, affaire classée', color: '#107aca',
    desc: 'Née en 2013, elle a fait disparaître les longues attentes au téléphone pour décrocher un rendez-vous chez le médecin, le dentiste ou le kiné. Quelques clics, un rappel par message la veille, et c\'est réglé. C\'est le tempérament des organisés efficaces, qui détestent perdre du temps, planifient tout à l\'avance et rendent service aux autres en simplifiant ce qui était compliqué.',
    t: { ord: 0.95, rig: 0.9, con: 0.85, care: 0.8, epi: 0.1, vhe: 0.2, vst: 0.2, loc: 0.1, san: 0.8, inf: 0.25 } },
  { name: 'Ubisoft', by: 'France · jeu vidéo', tag: 'Une bande de frères et des mondes entiers', color: '#1a4fd6',
    desc: 'Fondée en 1986 par les cinq frères Guillemot, originaires de Carentoir, en Bretagne, elle a créé Rayman, les Lapins Crétins et la saga Assassin\'s Creed, qui fait visiter Florence, Paris ou l\'Égypte antique. C\'est le tempérament des imaginatifs passionnés d\'histoire, qui aiment les grandes aventures, travaillent en bande et cachent un vrai grain de folie derrière le sérieux.',
    t: { ide: 0.95, vst: 0.9, loy: 0.8, vhe: 0.8, ord: 0.2, con: 0.2, vse: 0.2, inc: 0.8, vtr: 0.6, dom: 0.3 } },
  { name: 'Patagonia', by: 'États-Unis · vêtements de montagne', tag: 'La planète d\'abord', color: '#1f3c5a',
    desc: 'Fondée en 1973 par le grimpeur Yvon Chouinard, elle répare les vêtements de ses clients et a un jour publié une pleine page pour leur demander de ne pas acheter sa veste s\'ils n\'en avaient pas besoin. En 2022, son fondateur a confié l\'entreprise à une structure vouée à protéger la nature. C\'est le tempérament des idéalistes engagés, cohérents jusqu\'au bout, qui ne transigent pas avec leurs convictions.',
    t: { vun: 0.98, eng: 0.95, epi: 0.85, ind: 0.85, vpo: 0.05, vhe: 0.2, con: 0.15, cfl: 0.8, dog: 0.7, chg: 0.85 } },
  { name: 'Nike', by: 'États-Unis · sport', tag: 'Gagner, point', color: '#111111',
    desc: 'Fondée en 1964 par l\'athlète Phil Knight et son entraîneur Bill Bowerman, qui coula une semelle dans le gaufrier familial, elle prend en 1971 le nom de la déesse grecque de la victoire. Le célèbre « swoosh » a été dessiné par une étudiante pour 35 dollars. C\'est le tempérament des compétiteurs acharnés, qui veulent gagner, repoussent leurs limites et n\'aiment pas les excuses.',
    t: { cmp: 0.98, det: 0.95, com: 0.85, vac: 0.95, aud: 0.85, ste: 0.15, emp: 0.3, vtr: 0.2, rsk: 0.8, care: 0.25 } },
  { name: 'Adidas', by: 'Allemagne · sport', tag: 'Trois bandes, une équipe', color: '#1a1a1a',
    desc: 'Adolf « Adi » Dassler fonde sa marque en 1949 à Herzogenaurach, en Bavière, et son frère Rudolf crée Puma de l\'autre côté de la rivière. Ses crampons vissés équipent l\'Allemagne championne du monde en 1954. C\'est le tempérament des joueurs d\'équipe fidèles, attachés aux classiques, qui aiment la compétition mais la vivent en collectif, et les belles rivalités entre amis.',
    t: { col: 0.85, loy: 0.9, vtr: 0.75, rig: 0.75, cmp: 0.8, inf: 0.6, ind: 0.2, vsd: 0.3, ide: 0.35, soc: 0.8 } },
  { name: 'Le Slip Français', by: 'France · textile', tag: 'Fier, français, et pas sérieux', color: '#1e3a8a',
    desc: 'Lancée en 2011 par Guillaume Gibault, la marque a relevé un pari improbable : fabriquer des slips en France et en parler avec beaucoup d\'humour. Ses publicités décalées ont fait de la fabrication locale une affaire de bonne humeur. C\'est le tempérament des fiers blagueurs, attachés à leur terroir, qui osent l\'autodérision et prouvent qu\'on peut être sérieux dans le fond et léger dans la forme.',
    t: { opn: 0.9, loy: 0.85, inf: 0.85, vtr: 0.7, vhe: 0.7, rsk: 0.7, con: 0.15, dom: 0.3, san: 0.75, vpo: 0.2 } },
  { name: 'Michel et Augustin', by: 'France · biscuits', tag: 'Les trublions de la cuisine', color: '#f4a300',
    desc: 'Deux amis d\'enfance, Augustin Paluel-Marmont et Michel de Rovira, lancent en 2004 leurs premiers sablés depuis leur cuisine. Emballages bavards couverts d\'écritures, vache en mascotte, vidéos loufoques : ils se présentent eux-mêmes comme des trublions du goût. C\'est le tempérament des enthousiastes déjantés, qui foncent sans plan précis, débordent d\'énergie et transforment chaque projet en aventure entre copains.',
    t: { inf: 0.98, vst: 0.9, ord: 0.08, con: 0.05, opt: 0.95, aud: 0.9, rsk: 0.9, vig: 0.1, thr: 0.05, chg: 0.8 } },
  { name: 'Tupperware', by: 'États-Unis · boîtes de conservation', tag: 'Rien ne se perd, tout se partage', color: '#7fb843',
    desc: 'Inventée en 1946 par Earl Tupper, la boîte hermétique à couvercle qui « rote » en se fermant a été vendue lors de réunions entre voisines, à la maison, autour d\'un café. Le principe a fait le tour du monde. C\'est le tempérament des organisateurs conviviaux, qui gardent les restes pour le lendemain, reçoivent volontiers et font de chaque rangement une occasion de se retrouver.',
    t: { ord: 0.9, soc: 0.85, vbe: 0.8, vse: 0.8, att: 0.85, vst: 0.2, aud: 0.2, ind: 0.15, vpo: 0.15, epi: 0.15 } },
  { name: 'Opinel', by: 'France · coutellerie', tag: 'Un bon couteau et le silence', color: '#b58a52',
    desc: 'Joseph Opinel fabrique son couteau en 1890 dans un hameau de Savoie. Manche en hêtre, lame qui se bloque d\'un tour de bague depuis 1955, main couronnée gravée sur la lame : il a été classé parmi les objets les mieux dessinés du monde par le Victoria and Albert Museum. C\'est le tempérament des solitaires simples et robustes, qui aiment la montagne, parlent peu et n\'emportent que l\'essentiel.',
    t: { ind: 0.95, vsd: 0.8, vtr: 0.85, epi: 0.05, vpo: 0.05, soc: 0.1, inf: 0.1, fia: 0.9, opn: 0.8, vhe: 0.3, att: 0.3 } },
  { name: 'Le Creuset', by: 'France · cuisine', tag: 'Ce qui mijote longtemps est meilleur', color: '#e8590c',
    desc: 'Fondée en 1925 à Fresnoy-le-Grand, dans l\'Aisne, elle coule ses cocottes en fonte émaillée dont la première couleur, un orange flamboyant, s\'appelle Volcanique. Elles se transmettent souvent d\'une génération à l\'autre. C\'est le tempérament des calmes endurants, solides et chaleureux, qui ne se pressent jamais, laissent le temps faire son œuvre et restent là, fidèles, des années durant.',
    t: { fia: 0.95, ste: 0.98, san: 0.9, tmp: 0.85, vst: 0.1, inf: 0.15, vhe: 0.75, cfl: 0.1, rsk: 0.1, dom: 0.15 } },
  { name: 'Bic', by: 'France · objets du quotidien', tag: 'Simple, utile, pour tout le monde', color: '#f7941d',
    desc: 'Marcel Bich lance en 1950 le Bic Cristal, stylo à bille transparent et bon marché, qui a rejoint la collection du MoMA de New York. Suivront le briquet et le rasoir, toujours sur la même idée : des objets simples, utiles et accessibles à tous. C\'est le tempérament des humbles efficaces, qui ne cherchent pas à impressionner, vont droit au but et rendent service sans se faire remarquer.',
    t: { epi: 0.02, vpo: 0.05, fair: 0.85, fia: 0.9, ide: 0.2, vhe: 0.2, inf: 0.15, dom: 0.15, col: 0.75, vac: 0.3 } },
  { name: 'Rolex', by: 'Suisse · horlogerie', tag: 'La réussite au poignet', color: '#006039',
    desc: 'Fondée à Londres en 1905 par Hans Wilsdorf et installée à Genève après la Première Guerre mondiale, elle crée l\'Oyster, première montre-bracelet étanche, en 1926. L\'année suivante, la nageuse Mercedes Gleitze la porte en traversant la Manche. C\'est le tempérament des ambitieux méthodiques, qui visent l\'excellence, aiment les symboles de réussite et construisent patiemment leur légende.',
    t: { vac: 0.98, vpo: 0.95, rig: 0.9, tmp: 0.9, vtr: 0.75, emp: 0.2, care: 0.2, inc: 0.2, vst: 0.3, soc: 0.35 } },
  { name: 'Ferrari', by: 'Italie · automobile', tag: 'Rouge passion, pied au plancher', color: '#d40000',
    desc: 'Enzo Ferrari, ancien pilote, construit la première voiture à son nom en 1947 à Maranello. Son cheval cabré lui vient de l\'aviateur Francesco Baracca, et son rouge des couleurs de course de l\'Italie. Sa Scuderia est la plus ancienne écurie de Formule 1 encore en course. C\'est le tempérament des passionnés fougueux, entiers et compétitifs, qui vivent tout à fond, surtout les émotions.',
    t: { aff: 0.05, vst: 0.95, cmp: 0.95, aud: 0.9, dom: 0.9, san: 0.15, vhe: 0.85, ste: 0.1, dip: 0.2, cfl: 0.85 } },
  { name: 'Red Bull', by: 'Autriche · boissons', tag: 'Sauter d\'abord, réfléchir après', color: '#db0a40',
    desc: 'Lancée en 1987 par l\'Autrichien Dietrich Mateschitz, inspiré d\'une boisson thaïlandaise, la marque s\'est fait connaître par les sports extrêmes. En 2012, elle a fait sauter Felix Baumgartner en parachute depuis la stratosphère, à près de 39 km d\'altitude. C\'est le tempérament des casse-cou survoltés, qui vivent pour l\'adrénaline, s\'ennuient vite et ne connaissent pas le mot « prudence ».',
    t: { rsk: 0.98, vst: 0.98, aud: 0.95, vig: 0.05, vse: 0.05, thr: 0.05, tmp: 0.15, rig: 0.25, inf: 0.85, ste: 0.1 } },
  { name: 'Disney', by: 'États-Unis · divertissement', tag: 'Il était une fois, encore et toujours', color: '#113ccf',
    desc: 'Fondé en 1923 par Walt et Roy Disney, le studio fait naître Mickey en 1928, puis Blanche-Neige et les Sept Nains en 1937, premier long-métrage d\'animation du studio. Depuis, châteaux, chansons et fins heureuses peuplent l\'enfance du monde entier. C\'est le tempérament des émerveillés, qui croient aux contes, aiment les traditions et gardent intacte leur capacité à rêver.',
    t: { ide: 0.95, opt: 0.98, vis: 0.02, att: 0.85, vtr: 0.8, aff: 0.1, nat: 0.1, sanc: 0.75, inc: 0.3, cfl: 0.15 } },
  { name: 'Pixar', by: 'États-Unis · animation', tag: 'Faire rire, puis faire pleurer', color: '#4d8fc9',
    desc: 'Née en 1986 d\'une équipe d\'informaticiens rachetée à Lucasfilm par Steve Jobs, elle a pour mascotte une petite lampe de bureau et signe en 1995 Toy Story, premier long-métrage entièrement en images de synthèse. Ses films font rire les enfants et pleurer les parents. C\'est le tempérament des sensibles perfectionnistes, qui mettent une rigueur d\'ingénieur au service de l\'émotion.',
    t: { ide: 0.95, emp: 0.95, rig: 0.85, ouv: 0.9, vpo: 0.1, dom: 0.2, cmp: 0.2, att: 0.8, vtr: 0.25, care: 0.85 } },
  { name: 'Dyson', by: 'Royaume-Uni · électroménager', tag: 'Le 5 127e essai sera le bon', color: '#8e44ad',
    desc: 'James Dyson a fabriqué 5 127 prototypes en cinq ans avant de mettre au point son aspirateur sans sac. Refusé par les grands fabricants, il le produit lui-même et lance sa marque. Depuis, il réinvente sèche-cheveux et ventilateurs. C\'est le tempérament des inventeurs obstinés, un peu solitaires, qui ne lâchent rien, se méfient des idées reçues et recommencent jusqu\'à avoir raison.',
    t: { det: 0.98, ind: 0.95, rig: 0.85, chg: 0.9, soc: 0.1, dip: 0.2, cfl: 0.8, col: 0.1, vco: 0.1, nat: 0.7, att: 0.2 } },
  { name: 'Duolingo', by: 'États-Unis · langues', tag: 'Ta leçon t\'attend. Toujours.', color: '#58cc02',
    desc: 'Créée en 2011 à Pittsburgh par Luis von Ahn, déjà inventeur des reCAPTCHA, et Severin Hacker, elle a fait d\'une chouette verte la mascotte la plus insistante d\'internet. Séries de jours à ne pas briser, rappels facétieux : elle ne lâche jamais ses élèves. C\'est le tempérament des taquins persévérants, qui motivent par le jeu, relancent sans gêne et ne laissent personne abandonner.',
    t: { com: 0.9, inf: 0.9, cfl: 0.8, det: 0.85, ord: 0.8, dip: 0.15, vst: 0.7, ste: 0.2, vhe: 0.6, dom: 0.75 } },
  { name: 'Toyota', by: 'Japon · automobile', tag: 'Un peu mieux chaque jour', color: '#eb0a1e',
    desc: 'Issue des métiers à tisser de Sakichi Toyoda, l\'entreprise automobile est fondée en 1937 par son fils Kiichiro. Elle a fait connaître le « kaizen », l\'amélioration continue, et permet à chaque ouvrier d\'arrêter la chaîne s\'il repère un défaut. C\'est le tempérament des humbles méthodiques, qui avancent pas à pas, écoutent leur équipe et préfèrent mille petits progrès à un grand coup d\'éclat.',
    t: { rig: 0.9, ste: 0.9, col: 0.85, dip: 0.8, vpo: 0.15, aud: 0.2, inf: 0.15, tmp: 0.9, fia: 0.95, chg: 0.3, cfl: 0.25 } },
  { name: 'Volvo', by: 'Suède · automobile', tag: 'La sécurité avant tout', color: '#1f3a5f',
    desc: 'Fondée en 1927 à Göteborg, son nom signifie « je roule » en latin. En 1959, son ingénieur Nils Bohlin met au point la ceinture de sécurité à trois points, et la marque laisse les autres constructeurs l\'utiliser librement. C\'est le tempérament des protecteurs prudents, qui pensent à tout ce qui pourrait arriver, bouclent la ceinture des autres et trouvent que prévenir vaut mieux que guérir.',
    t: { vse: 0.98, vig: 0.95, thr: 0.8, rsk: 0.05, care: 0.9, fair: 0.8, vst: 0.1, inf: 0.2, aud: 0.1, vbe: 0.85 } },
  { name: 'Harley-Davidson', by: 'États-Unis · moto', tag: 'La route, le vent, la bande', color: '#f96302',
    desc: 'En 1903, à Milwaukee, William Harley et Arthur Davidson assemblent leur première moto dans une petite cabane en bois. Son moteur au grondement reconnaissable entre mille a fait d\'elle le symbole de la liberté sur deux roues, et ses propriétaires se retrouvent en clubs partout dans le monde. C\'est le tempérament des rebelles fidèles, qui n\'aiment pas les règles mais ne lâchent jamais leur bande.',
    t: { lib: 0.95, vsd: 0.9, loy: 0.85, vtr: 0.75, con: 0.05, vco: 0.1, cfl: 0.75, nat: 0.7, ord: 0.2, auth: 0.15 } },
];

window.PRISME_BRANDS = { BRANDS };
