/* ============================================================
   PRISME — « Quel personnage serais-tu ? »
   ------------------------------------------------------------
   Chaque personnage est décrit par un profil psychologique : des
   cibles de 0 à 1 sur les mêmes dimensions que le test.
     qualités  : fia det emp ouv ind lea san dip aud rig opt vig soc com ide att
     DISC      : dom inf ste con
     valeurs   : vsd vst vhe vac vpo vse vco vtr vbe vun
     morale    : care fair loy auth sanc lib
     traits    : inc dog eng
     axes (1 = pôle droit) : aff (tête) loc (porté) rsk (audacieux) ord (structuré) thr (vigilant)
                 col (collectiviste) tmp (long terme) cmp (compétitif) opn (enraciné)
                 cfl (conflictuel) chg (rupturiste) epi (idéologue) nat (méfiant) vis (décliniste)
   Pour ajouter une licence : un objet de plus dans LICENSES, avec 8 personnages ou plus.
   ============================================================ */
const LICENSES = [
  {
    id: 'zelda', name: 'The Legend of Zelda', kind: 'Jeu vidéo', color: '#2f9e62',
    cast: [
      { name: 'Link', tag: 'Le héros silencieux',
        desc: 'Il parle peu et agit beaucoup. Quand tout le monde hésite, il est déjà parti ; il n\'attend ni ordre ni récompense, et il revient toujours finir ce qu\'il a commencé.',
        t: { det: 0.9, aud: 0.85, fia: 0.85, san: 0.8, ind: 0.7, emp: 0.65, soc: 0.25, inf: 0.2, vbe: 0.7 } },
      { name: 'Zelda', tag: 'La sagesse qui porte un royaume',
        desc: 'Elle pense à long terme, étudie avant d\'agir et porte ses responsabilités sans se plaindre. Sa force n\'est pas de frapper, mais de tenir — et de voir ce que les autres ne voient pas encore.',
        t: { rig: 0.8, tmp: 0.85, fia: 0.85, ide: 0.7, emp: 0.7, lea: 0.6, aff: 0.65, con: 0.7, vun: 0.7, aud: 0.4 } },
      { name: 'Ganondorf', tag: 'L\'ambition faite roi',
        desc: 'Il veut le pouvoir et ne s\'en cache pas. Charismatique, patient quand il le faut, écrasant le reste du temps : un profil de conquérant, que rien ne détourne de son but. (Les malédictions en moins, on l\'espère.)',
        t: { vpo: 0.95, dom: 0.95, det: 0.9, com: 0.85, cmp: 0.9, lea: 0.8, chg: 0.8, nat: 0.8, emp: 0.15, dip: 0.15 } },
      { name: 'Impa', tag: 'La gardienne',
        desc: 'Fidèle, discrète, vigilante : elle protège ce qui lui a été confié, depuis toujours et pour toujours. On ne la voit pas, mais rien ne tient sans elle.',
        t: { fia: 0.95, att: 0.9, loy: 0.9, vig: 0.85, vtr: 0.85, ord: 0.8, vse: 0.75, ste: 0.7, aud: 0.35 } },
      { name: 'Midona', tag: 'L\'ironie au grand cœur',
        desc: 'Moqueuse, indépendante, méfiante par principe — et pourtant c\'est elle qui se sacrifie quand il le faut. Elle cache sa loyauté derrière des piques.',
        t: { ind: 0.85, vsd: 0.85, com: 0.7, aud: 0.7, inf: 0.65, nat: 0.65, ouv: 0.6, emp: 0.55, dip: 0.3 } },
      { name: 'Mipha', tag: 'La douceur qui soigne',
        desc: 'Elle écoute, apaise, répare. Elle évite le conflit et pense aux autres avant elle-même : la personne vers qui l\'on va quand on est blessé, au propre comme au figuré.',
        t: { emp: 0.95, vbe: 0.95, care: 0.9, ste: 0.9, dip: 0.85, opt: 0.6, com: 0.15, dom: 0.15 } },
      { name: 'Revali', tag: 'Le virtuose orgueilleux',
        desc: 'Il est le meilleur et tient à ce que ça se sache. Travailleur acharné, compétiteur né, mauvais perdant : son arrogance est le prix d\'une exigence réelle envers lui-même.',
        t: { cmp: 0.95, vac: 0.95, det: 0.8, ind: 0.8, dom: 0.75, aud: 0.75, rig: 0.7, emp: 0.3, dip: 0.2 } },
      { name: 'Urbosa', tag: 'La cheffe',
        desc: 'Autorité naturelle, sang-froid, et une vraie chaleur pour les siens. Elle protège sans étouffer, commande sans hausser le ton, et frappe une seule fois.',
        t: { lea: 0.9, san: 0.85, fia: 0.8, dom: 0.8, det: 0.8, att: 0.7, com: 0.65, emp: 0.65, soc: 0.6 } },
      { name: 'Daruk', tag: 'Le roc jovial',
        desc: 'Un rire énorme, une confiance inébranlable, zéro arrière-pensée. Il croit en ses amis plus qu\'ils ne croient en eux-mêmes — et ne voit jamais venir les ennuis.',
        t: { opt: 0.9, soc: 0.85, fia: 0.8, att: 0.8, inf: 0.8, emp: 0.7, vig: 0.3, rig: 0.3, thr: 0.2 } },
      { name: 'Sidon', tag: 'L\'enthousiasme incarné',
        desc: 'Il croit en toi. Oui, en toi, même s\'il te connaît depuis deux minutes. Solaire, encourageant, incapable de cynisme : un leader par l\'énergie plus que par l\'autorité.',
        t: { opt: 0.95, inf: 0.9, soc: 0.9, emp: 0.75, dip: 0.75, lea: 0.65, vig: 0.2, nat: 0.1 } },
      { name: 'Pru\'ha', tag: 'La scientifique survoltée',
        desc: 'Curieuse de tout, allergique à la routine, prête à tester sur elle-même. Le désordre de son labo est proportionnel au nombre de ses idées.',
        t: { ouv: 0.9, vst: 0.85, vsd: 0.85, aud: 0.8, aff: 0.7, inf: 0.7, ord: 0.25, att: 0.2, opn: 0.1 } },
    ],
  },
  {
    id: 'wow', name: 'World of Warcraft', kind: 'Jeu vidéo', color: '#c2850c',
    cast: [
      { name: 'Thrall', tag: 'Le chef qui doute',
        desc: 'Il mène parce qu\'il le faut, pas parce qu\'il en a envie. Il cherche l\'équilibre, écoute avant de décider et préfère un compromis honorable à une victoire amère.',
        t: { lea: 0.8, fia: 0.8, emp: 0.75, dip: 0.7, ide: 0.7, ouv: 0.7, tmp: 0.7, vun: 0.65, att: 0.6, com: 0.45 } },
      { name: 'Jaina Portvaillant', tag: 'La raison, puis la tempête',
        desc: 'Brillante, méthodique, longtemps partisane de la diplomatie. Mais quand on trahit sa confiance, la patience laisse place à une détermination glaciale.',
        t: { aff: 0.8, rig: 0.8, con: 0.75, det: 0.75, fia: 0.75, dip: 0.65, ide: 0.65, ouv: 0.6, vun: 0.6, san: 0.55 } },
      { name: 'Sylvanas Coursevent', tag: 'La volonté sans retour',
        desc: 'Elle ne compte sur personne et ne doit rien à personne. Stratège froide, méfiante jusqu\'à l\'os, prête à tout pour ne plus jamais subir. On la suit par admiration ou par crainte, rarement par affection.',
        t: { ind: 0.95, det: 0.95, vsd: 0.9, nat: 0.9, san: 0.85, vis: 0.85, com: 0.8, chg: 0.8, emp: 0.2, dip: 0.2 } },
      { name: 'Anduin Wrynn', tag: 'La paix par conviction',
        desc: 'Il croit qu\'on peut parler à tout le monde, et il a le courage d\'essayer. Sa douceur n\'est pas de la faiblesse : il faut être solide pour rester bienveillant dans un monde en guerre.',
        t: { emp: 0.95, dip: 0.95, care: 0.9, ide: 0.85, vun: 0.85, opt: 0.8, ste: 0.75, com: 0.15, nat: 0.1 } },
      { name: 'Varian Wrynn', tag: 'Le roi guerrier',
        desc: 'Un tempérament de feu mis au service des siens. Il fonce, il protège, il ne recule pas — et il a appris, à la dure, à dompter sa colère.',
        t: { com: 0.9, det: 0.9, loy: 0.9, lea: 0.85, att: 0.85, dom: 0.85, fia: 0.8, vse: 0.7, san: 0.4, dip: 0.3 } },
      { name: 'Arthas Menethil', tag: 'La fin qui justifie tout',
        desc: 'Il voulait sauver son peuple, à n\'importe quel prix — et c\'est bien le problème. Déterminé, sûr de lui, sourd aux avertissements : un idéal poussé si loin qu\'il ne voit plus le chemin.',
        t: { det: 0.95, dog: 0.9, aud: 0.9, epi: 0.85, lea: 0.75, vig: 0.6, emp: 0.25, dip: 0.15 } },
      { name: 'Illidan Hurlorage', tag: 'Le sacrifié incompris',
        desc: 'Il fait ce que personne d\'autre n\'ose faire, et se moque d\'être jugé pour ça. Solitaire, visionnaire, prêt à tout perdre pour une cause qu\'il est parfois seul à comprendre.',
        t: { ind: 0.95, aud: 0.9, det: 0.9, chg: 0.8, tmp: 0.8, vpo: 0.7, att: 0.2, dip: 0.2, epi: 0.2, soc: 0.15 } },
      { name: 'Garrosh Hurlenfer', tag: 'La force d\'abord',
        desc: 'Franc, fier, brutal. Il croit à l\'honneur, à la force et aux siens — et à rien d\'autre. Avec lui, on sait toujours où on en est, surtout quand on n\'est pas d\'accord.',
        t: { com: 0.95, dom: 0.95, cmp: 0.9, dog: 0.9, att: 0.85, loy: 0.8, emp: 0.15, ouv: 0.1, dip: 0.05 } },
      { name: 'Tyrande Murmevent', tag: 'La protectrice inflexible',
        desc: 'Dix mille ans à veiller sur son peuple : elle n\'oublie rien, ne pardonne pas facilement, et ne cède jamais. Une foi et une fidélité à toute épreuve.',
        t: { fia: 0.85, att: 0.85, det: 0.85, loy: 0.85, sanc: 0.8, vig: 0.75, vtr: 0.75, com: 0.7, emp: 0.6 } },
      { name: 'Khadgar', tag: 'Le mage qui garde le sourire',
        desc: 'Savant, curieux, et étonnamment blagueur pour quelqu\'un qui a vu autant de catastrophes. Il affronte le pire avec calme, humour et une confiance contagieuse.',
        t: { ouv: 0.85, opt: 0.8, san: 0.75, soc: 0.7, aff: 0.7, aud: 0.7, vst: 0.7, inf: 0.65, rig: 0.6 } },
      { name: 'Vol\'jin', tag: 'Le stratège de l\'ombre',
        desc: 'Patient, lucide, pragmatique. Il observe longtemps, parle peu, et choisit le moment exact où agir. Il ne cherche pas la gloire : il cherche ce qui marche.',
        t: { san: 0.9, vig: 0.8, fia: 0.75, aff: 0.7, tmp: 0.7, dip: 0.6, ind: 0.6, lea: 0.6, con: 0.6, epi: 0.15 } },
    ],
  },
  {
    id: 'jojo', name: 'JoJo\'s Bizarre Adventure', kind: 'Manga · Anime', color: '#9b5de5',
    cast: [
      { name: 'Jonathan Joestar', tag: 'Le gentleman',
        desc: 'Droit, généreux, incapable de bassesse. Il croit au meilleur chez les gens et se bat à la loyale, même contre ceux qui ne le méritent pas.',
        t: { fia: 0.95, fair: 0.9, emp: 0.85, ide: 0.85, vbe: 0.85, det: 0.8, vco: 0.7, dip: 0.6, nat: 0.1 } },
      { name: 'Joseph Joestar', tag: 'Le roublard',
        desc: 'Il improvise, bluffe, triche un peu et gagne quand même. Drôle, imprévisible, toujours un coup d\'avance : « ta prochaine phrase sera… »',
        t: { inf: 0.9, aud: 0.85, soc: 0.85, vhe: 0.8, opt: 0.75, aff: 0.6, com: 0.6, rig: 0.2, ord: 0.1, epi: 0.1 } },
      { name: 'Jotaro Kujo', tag: 'Le calme qui cogne',
        desc: 'Peu de mots, aucun état d\'âme apparent, une fiabilité totale. Il analyse froidement, agit une fois, et passe à autre chose. Son affection existe : elle ne se dit pas.',
        t: { san: 0.95, det: 0.85, fia: 0.8, ind: 0.8, aff: 0.75, dom: 0.7, emp: 0.45, dip: 0.25, soc: 0.15, inf: 0.1 } },
      { name: 'Josuke Higashikata', tag: 'Le bon gars du quartier',
        desc: 'Chaleureux, attaché à sa ville et à ses proches, toujours prêt à réparer ce qui est cassé. Ne dis juste rien sur sa coiffure.',
        t: { att: 0.85, vbe: 0.85, emp: 0.8, soc: 0.8, fia: 0.75, opn: 0.75, opt: 0.7, vhe: 0.65, com: 0.55 } },
      { name: 'Giorno Giovanna', tag: 'Le rêve méthodique',
        desc: 'Il a un rêve, et un plan pour l\'atteindre. Calme, ambitieux, stratège : il monte marche après marche sans jamais perdre de vue le sommet.',
        t: { det: 0.9, tmp: 0.9, san: 0.85, vac: 0.85, lea: 0.8, ide: 0.75, aff: 0.7, vpo: 0.65, con: 0.6, dip: 0.55 } },
      { name: 'Jolyne Cujoh', tag: 'La rebelle',
        desc: 'Elle n\'obéit à personne et ne lâche rien. Insolente, courageuse, farouchement libre : l\'autorité la hérisse, l\'injustice la déchaîne.',
        t: { vsd: 0.9, ind: 0.85, aud: 0.85, lib: 0.85, com: 0.8, det: 0.8, emp: 0.6, ord: 0.25, auth: 0.15 } },
      { name: 'Dio Brando', tag: 'L\'ego sans limite',
        desc: 'Charisme écrasant, ambition sans fond, aucune place pour le doute. Il veut être au-dessus de tous et ne supporte aucun rival. (Garde le charisme, laisse le reste.)',
        t: { vpo: 0.98, dom: 0.95, cmp: 0.95, det: 0.9, nat: 0.9, lea: 0.75, inf: 0.7, fair: 0.1, emp: 0.05 } },
      { name: 'Rohan Kishibe', tag: 'L\'artiste insupportable',
        desc: 'Obsédé par son art, curieux jusqu\'à l\'imprudence, et d\'une franchise qui frise l\'insulte. Il refuse par principe ce qu\'on attend de lui.',
        t: { ind: 0.9, vsd: 0.9, rig: 0.85, ouv: 0.8, vac: 0.8, cmp: 0.7, soc: 0.3, opn: 0.15, dip: 0.1 } },
      { name: 'Bruno Bucciarati', tag: 'Le chef qu\'on suit',
        desc: 'Juste, protecteur, exigeant d\'abord avec lui-même. Son équipe le suivrait n\'importe où, parce qu\'il ne demande jamais ce qu\'il ne ferait pas.',
        t: { fia: 0.95, lea: 0.9, fair: 0.85, det: 0.85, emp: 0.8, col: 0.8, vbe: 0.8, san: 0.75, ide: 0.7 } },
      { name: 'Yoshikage Kira', tag: 'La vie tranquille à tout prix',
        desc: 'Il veut une vie calme, ordonnée, sans vagues — et il est d\'une rigueur maniaque pour l\'obtenir. Ne gagne jamais les concours, exprès : ni premier, ni dernier. (On retient le goût de la tranquillité, pas le reste.)',
        t: { vse: 0.95, ord: 0.95, opn: 0.9, rig: 0.85, con: 0.85, thr: 0.7, soc: 0.15, aud: 0.1, vst: 0.05 } },
      { name: 'Robert E. O. Speedwagon', tag: 'L\'ami indéfectible',
        desc: 'Il a choisi son camp une fois pour toutes. Expansif, dévoué, toujours là : pas le héros de l\'histoire, mais celui sans qui elle n\'aurait pas lieu.',
        t: { fia: 0.95, loy: 0.95, soc: 0.8, emp: 0.8, att: 0.8, opt: 0.7, inf: 0.7, lea: 0.35 } },
    ],
  },
  {
    id: 'snk', name: 'L\'Attaque des Titans', kind: 'Manga · Anime', color: '#b3001b',
    cast: [
      { name: 'Eren Jäger', tag: 'La liberté ou rien',
        desc: 'Il avance. Quoi qu\'il en coûte, quoi qu\'on lui dise. Une idée fixe, une rage intacte, et la conviction que personne n\'a le droit de l\'enfermer.',
        t: { det: 0.98, lib: 0.95, chg: 0.95, com: 0.9, cfl: 0.9, vsd: 0.9, ide: 0.85, dog: 0.85, san: 0.25, dip: 0.1 } },
      { name: 'Mikasa Ackerman', tag: 'La loyauté absolue',
        desc: 'Peu de mots, une force hors norme, et une fidélité que rien n\'entame. Elle protège ceux qu\'elle aime avant de penser à elle.',
        t: { loy: 0.98, fia: 0.95, att: 0.9, vbe: 0.9, det: 0.85, san: 0.8, ind: 0.3, soc: 0.2, inf: 0.15 } },
      { name: 'Armin Arlert', tag: 'L\'esprit qui voit loin',
        desc: 'Il doute de lui, jamais de la valeur d\'une idée. Stratège par la réflexion, diplomate par nature, il cherche la solution où personne n\'a à mourir.',
        t: { ouv: 0.9, aff: 0.85, tmp: 0.85, dip: 0.8, emp: 0.75, vun: 0.75, ide: 0.7, opt: 0.6, com: 0.25, dom: 0.2 } },
      { name: 'Livaï', tag: 'L\'exigence',
        desc: 'Propre, précis, redoutable. Il parle sec et juge vite, mais il porte le poids de chaque camarade tombé. Son respect se mérite, et il est définitif.',
        t: { rig: 0.95, san: 0.95, fia: 0.9, ord: 0.9, det: 0.85, con: 0.85, vig: 0.75, emp: 0.5, dip: 0.2, soc: 0.15 } },
      { name: 'Erwin Smith', tag: 'Le pari',
        desc: 'Il voit plus loin que tout le monde et mise tout dessus, y compris lui-même. Charisme de commandant, calcul de joueur d\'échecs : on le suit jusqu\'au bout.',
        t: { lea: 0.95, aud: 0.9, rsk: 0.9, tmp: 0.9, det: 0.9, aff: 0.85, vac: 0.8, ide: 0.7, emp: 0.35 } },
      { name: 'Hansi Zoé', tag: 'La curiosité dévorante',
        desc: 'Là où les autres voient un monstre, elle voit un sujet d\'étude passionnant. Enthousiaste, brouillonne, géniale : elle court vers ce que tout le monde fuit.',
        t: { ouv: 0.95, vst: 0.9, inf: 0.8, aud: 0.8, soc: 0.7, opt: 0.7, aff: 0.65, ord: 0.2, opn: 0.05 } },
      { name: 'Reiner Braun', tag: 'Le devoir qui déchire',
        desc: 'Le grand frère fiable, qui porte les autres — et un poids trop lourd pour lui. Loyal à en souffrir, pris entre ce qu\'on attend de lui et ce qu\'il ressent.',
        t: { loy: 0.85, fia: 0.8, att: 0.8, col: 0.8, auth: 0.75, emp: 0.7, vco: 0.7, opt: 0.25, san: 0.2 } },
      { name: 'Historia Reiss', tag: 'Celle qui a choisi d\'être elle-même',
        desc: 'Longtemps gentille pour plaire, puis vraie par décision. Douce mais plus jamais soumise : elle fait passer ceux qu\'elle aime avant ce qu\'on exige d\'elle.',
        t: { emp: 0.8, vsd: 0.75, vbe: 0.75, ind: 0.7, dip: 0.7, det: 0.65, ste: 0.65, lea: 0.55 } },
      { name: 'Jean Kirschtein', tag: 'Le réaliste devenu chef',
        desc: 'Il voulait une vie confortable et l\'a dit tout haut. Lucide sur ses peurs, honnête sur les risques : c\'est précisément pour ça qu\'on lui fait confiance.',
        t: { fia: 0.75, lea: 0.7, vse: 0.7, aff: 0.65, ouv: 0.6, nat: 0.6, vhe: 0.6, com: 0.55, ide: 0.3, epi: 0.15 } },
      { name: 'Sasha Braus', tag: 'L\'instinct et l\'appétit',
        desc: 'Spontanée, gourmande, drôle sans le vouloir. Elle vit dans l\'instant et suit son instinct — qui est excellent, surtout quand il s\'agit de nourriture ou de danger.',
        t: { vhe: 0.95, soc: 0.8, opt: 0.75, inf: 0.75, emp: 0.7, att: 0.65, ord: 0.2, aff: 0.2, tmp: 0.1 } },
      { name: 'Sieg Jäger', tag: 'Le plan, coûte que coûte',
        desc: 'Détaché, brillant, convaincu d\'avoir trouvé la seule solution logique à un monde qui va mal. Il joue une partie très longue, seul contre tous.',
        t: { aff: 0.9, tmp: 0.85, san: 0.85, vis: 0.85, epi: 0.8, ind: 0.8, det: 0.8, nat: 0.75, con: 0.6, emp: 0.3 } },
    ],
  },
  {
    id: 'casa', name: 'La Casa de Papel', kind: 'Série', color: '#d62828',
    cast: [
      { name: 'Le Professeur', tag: 'Le cerveau',
        desc: 'Tout est prévu, y compris l\'imprévu. Timide en société, brillant devant un plan : il gagne avant même que la partie commence, et déteste improviser.',
        t: { aff: 0.95, rig: 0.95, tmp: 0.9, con: 0.9, ord: 0.9, vig: 0.8, san: 0.75, ide: 0.7, aud: 0.6, soc: 0.25 } },
      { name: 'Tokyo', tag: 'L\'impulsive',
        desc: 'Elle vit à fond, tout de suite, sans filet. Courageuse, incontrôlable, allergique aux consignes : le plan, c\'est pour les autres.',
        t: { aud: 0.95, vst: 0.95, ind: 0.85, vhe: 0.85, com: 0.75, san: 0.15, aff: 0.15, tmp: 0.05, ord: 0.05 } },
      { name: 'Berlin', tag: 'Le dandy dangereux',
        desc: 'Élégant, cultivé, sûr de sa supériorité. Il commande avec un sourire, savoure chaque instant et ne s\'excuse jamais. Fascinant de loin.',
        t: { dom: 0.85, vpo: 0.85, cmp: 0.85, san: 0.85, lea: 0.8, nat: 0.8, vhe: 0.75, inf: 0.7, dip: 0.3, emp: 0.15 } },
      { name: 'Nairobi', tag: 'La patronne',
        desc: 'Elle motive, organise, engueule et console dans la même minute. Une énergie de cheffe d\'atelier : avec elle, le travail est bien fait et l\'équipe tient debout.',
        t: { lea: 0.9, soc: 0.9, opt: 0.85, det: 0.85, inf: 0.85, fia: 0.75, emp: 0.7, com: 0.7, dom: 0.7 } },
      { name: 'Rio', tag: 'Le cœur tendre',
        desc: 'Sensible, confiant, un peu naïf. Il ressent tout très fort et fait confiance trop vite — c\'est sa faiblesse, et c\'est aussi pour ça qu\'on l\'aime.',
        t: { emp: 0.8, vbe: 0.8, ste: 0.65, opt: 0.6, san: 0.25, com: 0.2, aff: 0.15, nat: 0.15, dom: 0.15 } },
      { name: 'Denver', tag: 'Le sanguin au grand cœur',
        desc: 'Il s\'énerve vite, rit fort et aime sans calcul. Pas un stratège, mais un type sur qui on peut compter quand ça tourne mal.',
        t: { vbe: 0.85, att: 0.8, emp: 0.75, fia: 0.7, soc: 0.7, com: 0.7, rig: 0.15, san: 0.15, aff: 0.1 } },
      { name: 'Helsinki', tag: 'La force tranquille',
        desc: 'Un colosse doux. Il parle peu, ne se plaint jamais, et reste aux côtés des siens quoi qu\'il arrive. Le calme au milieu du chaos.',
        t: { fia: 0.9, ste: 0.9, loy: 0.9, san: 0.8, emp: 0.75, dip: 0.7, soc: 0.4, com: 0.3, lea: 0.2 } },
      { name: 'Moscou', tag: 'Le père',
        desc: 'Il est là pour protéger son fils, et par extension tout le monde. Prudent, rassurant, fidèle : la voix de la raison quand les jeunes s\'emballent.',
        t: { vbe: 0.95, att: 0.85, fia: 0.85, ste: 0.8, emp: 0.8, vse: 0.75, vtr: 0.7, aud: 0.25, dom: 0.2 } },
      { name: 'Lisbonne', tag: 'Celle qui change de camp par conviction',
        desc: 'Intègre, tenace, capable de tout remettre en question quand les faits l\'exigent. Elle suit sa conscience, même quand ça lui coûte sa carrière.',
        t: { fair: 0.85, det: 0.8, ouv: 0.8, rig: 0.75, dip: 0.7, ide: 0.7, aff: 0.65, san: 0.65, chg: 0.6 } },
      { name: 'Palerme', tag: 'L\'ingénieur blessé',
        desc: 'Brillant, arrogant, écorché. Il maîtrise la technique mieux que personne et cache ses failles derrière des provocations.',
        t: { rig: 0.8, com: 0.8, cmp: 0.8, dom: 0.75, nat: 0.75, ind: 0.75, aff: 0.7, lea: 0.6, emp: 0.3, dip: 0.15 } },
      { name: 'Stockholm', tag: 'La métamorphose',
        desc: 'Elle est entrée dans l\'histoire par hasard et a décidé d\'y rester. Ouverte, courageuse à sa façon, capable de changer de vie sans renier qui elle est.',
        t: { ouv: 0.85, emp: 0.8, vbe: 0.8, dip: 0.65, chg: 0.65, aud: 0.6, ste: 0.6, ind: 0.5 } },
      { name: 'Alicia Sierra', tag: 'L\'adversaire redoutable',
        desc: 'Froide, rapide, toujours un coup d\'avance. Elle ne fait confiance à personne et ne lâche jamais une piste. On préfère l\'avoir dans son camp.',
        t: { san: 0.95, det: 0.9, com: 0.9, vig: 0.9, nat: 0.9, aff: 0.85, ind: 0.85, cmp: 0.85, emp: 0.15, dip: 0.1 } },
    ],
  },
];

window.PRISME_CHARACTERS = { LICENSES };
