/* ============================================================
   PRISME — « Si tu étais une ville française »
   ------------------------------------------------------------
   Ni ses habitants, ni sa mairie : le tempérament que la ville
   renvoie — son rythme, son caractère, sa table, son climat,
   ce qu'on y aime quand on s'y promène — raconté avec affection,
   comme on parle d'un endroit où l'on a laissé un morceau de cœur.
     name = la ville, by = région · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const CITIES = [
  { name: 'Paris', by: 'Île-de-France · la tour Eiffel', tag: 'Pressée, brillante, jamais contente', color: '#2d3a5c',
    desc: 'Elle marche vite, mange sur le pouce et trouve toujours quelque chose à redire, du métro bondé au prix du café en terrasse. Mais elle a les musées, les quais de Seine à la tombée du soir et cette ambition qui fait vibrer chaque rue. Un tempérament exigeant, compétitif, qui a peu de temps à perdre et beaucoup à prouver.',
    t: { vac: 0.95, cmp: 0.92, vpo: 0.85, ste: 0.08, att: 0.25, nat: 0.8, com: 0.85, ouv: 0.85, vbe: 0.3, emp: 0.3, dom: 0.85 } },
  { name: 'Marseille', by: 'Provence-Alpes-Côte d\'Azur · le Vieux-Port', tag: 'Tout est plus grand, surtout les histoires', color: '#2aa7d8',
    desc: 'Chez elle, la sardine a bouché le port, le match de l\'OM est une affaire d\'État et la partie de pétanque peut durer tout l\'après-midi. Elle parle fort, exagère avec talent et défend les siens comme personne, sous le regard de la Bonne Mère. Un tempérament volcanique et généreux, qui préfère le cœur et la galéjade à la règle et au règlement.',
    t: { inf: 0.97, com: 0.92, loy: 0.95, cfl: 0.88, rig: 0.1, con: 0.08, aff: 0.08, san: 0.15, vhe: 0.85, ord: 0.12, dip: 0.2 } },
  { name: 'Lyon', by: 'Auvergne-Rhône-Alpes · les bouchons', tag: 'Discrète dehors, festin dedans', color: '#8c1c2c',
    desc: 'Elle ne fait pas de bruit : ses trésors sont cachés au fond des traboules et ses meilleures tables derrière des nappes à carreaux, entre quenelle et saucisson brioché. Une fois par an, le 8 décembre, elle s\'illumine de lumignons, puis retourne à sa sage prospérité. Un tempérament réservé, bon vivant, qui mise sur la qualité, la tradition et la durée.',
    t: { vhe: 0.9, inf: 0.2, vtr: 0.88, vse: 0.85, rsk: 0.18, fia: 0.9, chg: 0.12, vac: 0.82, aud: 0.2, tmp: 0.85, soc: 0.45 } },
  { name: 'Toulouse', by: 'Occitanie · la Ville rose', tag: 'Du rugby aux étoiles', color: '#e0707a',
    desc: 'Le samedi, elle hurle pour le Stade toulousain ; le lundi, elle assemble des avions et prépare des fusées à la Cité de l\'espace. Entre les briques roses, le cassoulet et l\'accent qui chante, elle trouve que le ciel n\'est pas une limite mais un objectif. Un tempérament solaire et collectif, qui vise haut sans jamais oublier la troisième mi-temps.',
    t: { vac: 0.88, col: 0.9, loy: 0.88, opt: 0.92, vis: 0.08, rsk: 0.75, att: 0.85, ide: 0.8, nat: 0.12, ind: 0.2, cmp: 0.7 } },
  { name: 'Nice', by: 'Provence-Alpes-Côte d\'Azur · la promenade des Anglais', tag: 'Le soleil, les galets et l\'ordre', color: '#f2a93b',
    desc: 'Elle a la mer turquoise, la socca brûlante sur le marché du cours Saleya et une lumière que les peintres ont traversé l\'Europe pour voir. Pourtant, elle aime que tout reste à sa place : la chaise bleue sur la Promenade, la vraie salade niçoise, les traditions du carnaval. Un tempérament ensoleillé mais attaché à sa tranquillité, qui préfère le confort à l\'aventure.',
    t: { vhe: 0.92, vse: 0.9, vst: 0.2, chg: 0.08, rsk: 0.12, thr: 0.72, vtr: 0.85, inc: 0.2, ord: 0.72, ouv: 0.3, vun: 0.3 } },
  { name: 'Nantes', by: 'Pays de la Loire · l\'éléphant des Machines', tag: 'Un éléphant dans la ville', color: '#27a39a',
    desc: 'Elle a vu naître Jules Verne, invente des biscuits et promène un éléphant mécanique de douze mètres sur son île, comme si c\'était la chose la plus normale du monde. Chaque été, elle trace une ligne verte de surprises artistiques à travers ses rues. Un tempérament curieux et créatif, décontracté, qui aime que la ville soit un terrain de jeu.',
    t: { ide: 0.95, ouv: 0.93, vst: 0.85, chg: 0.8, vtr: 0.18, dog: 0.06, inc: 0.88, auth: 0.12, vun: 0.85, dom: 0.2, vpo: 0.12 } },
  { name: 'Strasbourg', by: 'Grand Est · la cathédrale', tag: 'Européenne jusqu\'au bretzel', color: '#b0413e',
    desc: 'Elle accueille le Parlement européen, parle volontiers deux langues et tient l\'un des plus anciens marchés de Noël de France, sous une cathédrale qui a longtemps été le plus haut édifice du monde. Entre deux tartes flambées, elle cultive le compromis et le travail bien rangé. Un tempérament diplomate, ordonné et fidèle à ses traditions, ouvert sur toutes ses frontières.',
    t: { dip: 0.95, opn: 0.08, vtr: 0.88, ord: 0.88, con: 0.85, fair: 0.88, cfl: 0.12, vst: 0.3, vun: 0.88, com: 0.2, aud: 0.3 } },
  { name: 'Montpellier', by: 'Occitanie · la place de la Comédie', tag: 'Toujours vingt ans, toujours dehors', color: '#f28c28',
    desc: 'Elle abrite l\'une des plus anciennes facultés de médecine du monde encore en activité, mais on la connaît surtout pour ses terrasses bondées et ses étudiants qui refont le monde sur la place de la Comédie. Elle grandit vite, change sans cesse et regarde l\'avenir avec un sourire de plein soleil. Un tempérament jeune, sociable, spontané, qui a toujours un plan pour ce soir.',
    t: { vst: 0.92, soc: 0.93, tmp: 0.15, ord: 0.18, opt: 0.9, vis: 0.08, vtr: 0.2, chg: 0.82, inf: 0.85, rig: 0.25, vse: 0.3 } },
  { name: 'Bordeaux', by: 'Nouvelle-Aquitaine · le miroir d\'eau', tag: 'Élégante, et elle le sait', color: '#7b1e3a',
    desc: 'Ses façades de pierre blonde, ses grands crus et son port de la Lune classé à l\'UNESCO lui donnent un port de tête qu\'elle ne cherche pas à cacher. Elle reçoit avec un cannelé et un verre de quelque chose de rare, dans les règles de l\'art. Un tempérament raffiné, un brin distant, qui aime le prestige, les belles manières et les choses qui vieillissent bien.',
    t: { vpo: 0.85, vtr: 0.88, con: 0.85, vhe: 0.9, inf: 0.3, chg: 0.12, aud: 0.2, vac: 0.85, soc: 0.4, att: 0.35, tmp: 0.85 } },
  { name: 'Lille', by: 'Hauts-de-France · la Grand-Place', tag: 'Le soleil est dans les cœurs', color: '#c73b32',
    desc: 'Le ciel est parfois gris, mais l\'estaminet est toujours chaud, et à la braderie de septembre on partage des tonnes de moules-frites avec des inconnus devenus amis. Ici, on vous tutoie, on vous invite et on vous garde. Un tempérament chaleureux et généreux, qui n\'a aucun goût pour la compétition mais un talent immense pour l\'accueil.',
    t: { att: 0.97, soc: 0.95, emp: 0.9, vbe: 0.93, nat: 0.06, vpo: 0.08, cmp: 0.08, dom: 0.18, vhe: 0.85, thr: 0.2, aff: 0.15 } },
  { name: 'Rennes', by: 'Bretagne · les Trans Musicales', tag: 'La galette-saucisse et le son à fond', color: '#1f6f8b',
    desc: 'Elle a la plus jeune population de Bretagne, un faible pour la galette-saucisse et, chaque mois de décembre, une programmation musicale qui a révélé des artistes du monde entier. Elle s\'engage, débat, invente, et sort le jeudi soir comme d\'autres le samedi. Un tempérament jeune, curieux et convaincu, qui aime que les choses bougent.',
    t: { eng: 0.9, vst: 0.88, ide: 0.85, vun: 0.9, chg: 0.85, auth: 0.12, vpo: 0.12, epi: 0.8, soc: 0.8, vse: 0.25, fair: 0.88 } },
  { name: 'Reims', by: 'Grand Est · la cathédrale des sacres', tag: 'Les rois, les bulles et le protocole', color: '#d9b64f',
    desc: 'C\'est sous ses voûtes que l\'on sacrait les rois de France, et dans ses crayères que dorment des millions de bouteilles de champagne. L\'Ange au sourire veille sur sa façade, un biscuit rose attend d\'être trempé. Un tempérament solennel et festif à la fois, attaché au rang, au rituel et aux grandes occasions qu\'il faut célébrer comme il se doit.',
    t: { vpo: 0.88, vtr: 0.95, auth: 0.88, sanc: 0.85, vhe: 0.88, chg: 0.06, vsd: 0.3, inc: 0.25, con: 0.85, lib: 0.25, eng: 0.2 } },
  { name: 'Le Havre', by: 'Normandie · la ville d\'Auguste Perret', tag: 'Du béton, du vent et du panache', color: '#6c7a89',
    desc: 'Rebâtie en béton par Auguste Perret puis classée à l\'UNESCO, elle a transformé la reconstruction en œuvre d\'art. C\'est dans son port que Monet a peint le soleil levant qui a donné son nom à l\'impressionnisme. Un tempérament solide et pragmatique, qui ne se plaint pas du vent, se relève toujours et regarde droit vers le large.',
    t: { det: 0.95, epi: 0.08, san: 0.92, rig: 0.85, inf: 0.2, vhe: 0.25, loc: 0.08, chg: 0.8, ide: 0.78, vtr: 0.25, fia: 0.88 } },
  { name: 'Saint-Étienne', by: 'Auvergne-Rhône-Alpes · le Chaudron', tag: 'Tout pour le vert', color: '#0b8a3e',
    desc: 'Elle a fabriqué des vélos, des armes de chasse, un catalogue mythique et, aujourd\'hui, du design reconnu par l\'UNESCO. Mais ce qui la fait vibrer, c\'est le Chaudron les soirs de match, quand tout le stade chante pour les Verts. Un tempérament fidèle et bosseur, fier de ses racines, qui ne lâche jamais les siens, même quand le score est serré.',
    t: { loy: 0.97, col: 0.95, att: 0.88, vpo: 0.08, com: 0.85, det: 0.92, vtr: 0.82, dip: 0.3, vhe: 0.35, ind: 0.15, opn: 0.75 } },
  { name: 'Toulon', by: 'Provence-Alpes-Côte d\'Azur · la rade', tag: 'Garde-à-vous et mêlée ouverte', color: '#b3151e',
    desc: 'Premier port militaire de France, elle vit au rythme des bâtiments gris qui entrent dans la rade et des soirs de rugby où Mayol rugit en rouge et noir. Elle respecte la hiérarchie, mais sur le terrain, elle ne recule devant personne. Un tempérament discipliné et combatif, qui aime l\'ordre, le défi et les victoires arrachées au mérite.',
    t: { auth: 0.95, loy: 0.93, cfl: 0.88, dom: 0.88, cmp: 0.92, con: 0.82, com: 0.9, emp: 0.3, vun: 0.2, dip: 0.2, inc: 0.25 } },
  { name: 'Grenoble', by: 'Auvergne-Rhône-Alpes · les Bulles de la Bastille', tag: 'Un labo au pied des sommets', color: '#3f7cac',
    desc: 'Elle monte à la Bastille en bulles de téléphérique, skie le week-end et consacre ses semaines à la recherche, entre accélérateurs de particules et laboratoires de pointe. Les montagnes l\'entourent de partout, ce qui ne l\'empêche pas d\'avoir la tête dans les équations. Un tempérament cérébral et sportif, peu mondain, qui préfère comprendre que briller.',
    t: { aff: 0.95, ouv: 0.9, rsk: 0.78, rig: 0.88, soc: 0.25, inf: 0.15, vhe: 0.3, vpo: 0.15, vun: 0.85, vst: 0.8, epi: 0.7 } },
  { name: 'Dijon', by: 'Bourgogne-Franche-Comté · la chouette porte-bonheur', tag: 'La moutarde monte au nez, jamais aux joues', color: '#c9a227',
    desc: 'Elle vit entre le palais des ducs de Bourgogne, les climats de vignes classés à l\'UNESCO et une petite chouette de pierre qu\'on caresse de la main gauche pour la chance. Pain d\'épices, kir, bœuf bourguignon : chez elle, tout mijote longtemps. Un tempérament paisible et gourmand, qui fait confiance au temps et aux recettes qui ont fait leurs preuves.',
    t: { vtr: 0.93, vhe: 0.9, ste: 0.92, rsk: 0.12, vst: 0.15, dom: 0.2, chg: 0.08, com: 0.2, tmp: 0.85, sanc: 0.7, cmp: 0.2 } },
  { name: 'Angers', by: 'Pays de la Loire · la tapisserie de l\'Apocalypse', tag: 'La douceur angevine', color: '#8fb573',
    desc: 'Du Bellay rêvait de sa douceur angevine, et on comprend pourquoi : un château aux tours zébrées, une Loire toute proche, des jardins partout et une liqueur à l\'orange née dans ses murs. Elle n\'élève jamais la voix et ne s\'inquiète pas pour grand-chose. Un tempérament serein et accommodant, qui cultive la qualité de vie plutôt que la course.',
    t: { ste: 0.95, cfl: 0.05, dom: 0.1, thr: 0.08, san: 0.9, opt: 0.88, vac: 0.2, cmp: 0.1, aud: 0.15, dip: 0.9, vis: 0.15 } },
  { name: 'Nîmes', by: 'Occitanie · les arènes', tag: 'Rome au soleil, féria au cœur', color: '#d4863a',
    desc: 'Elle a gardé des arènes romaines, une Maison carrée de deux mille ans et a donné son nom au denim, la fameuse toile « de Nîmes ». À la Pentecôte, sa féria transforme les rues en fête géante, entre bodegas et brandade. Un tempérament flamboyant et fier de son histoire, qui vit l\'instant avec panache et un soupçon d\'audace.',
    t: { inf: 0.92, vhe: 0.9, aud: 0.82, vtr: 0.88, soc: 0.9, tmp: 0.15, ord: 0.25, rsk: 0.75, vpo: 0.7, vse: 0.3, aff: 0.15 } },
  { name: 'Clermont-Ferrand', by: 'Auvergne-Rhône-Alpes · la cathédrale noire', tag: 'Pierre de lave, cœur jaune', color: '#3b3b3b',
    desc: 'Sa cathédrale est taillée dans la pierre de Volvic, ses volcans endormis sont classés à l\'UNESCO et ses pneus roulent sur toutes les routes du monde. Discrète en semaine, elle se déchaîne en jaune et bleu les soirs de rugby. Un tempérament solide et sans esbroufe, fiable comme un basalte, qui travaille beaucoup et parle peu.',
    t: { fia: 0.95, det: 0.9, inf: 0.1, soc: 0.3, vpo: 0.1, ste: 0.9, loy: 0.88, vhe: 0.3, rig: 0.85, vst: 0.25, com: 0.25 } },
  { name: 'Tours', by: 'Centre-Val de Loire · les châteaux', tag: 'Le français le plus pur, dit-on', color: '#4d7ea8',
    desc: 'On raconte qu\'on y parle le français le plus pur, et elle ne dément pas. Entre la place Plumereau, les rillettes, la maison natale de Balzac et les châteaux de la Loire à portée de vélo, elle a le charme d\'un jardin bien tenu. Un tempérament courtois, soigné et sociable, qui respecte les usages et fuit les éclats.',
    t: { con: 0.92, vco: 0.9, dip: 0.9, cfl: 0.1, rig: 0.85, soc: 0.8, aud: 0.15, chg: 0.12, dom: 0.2, lib: 0.3, vhe: 0.75 } },
  { name: 'Limoges', by: 'Nouvelle-Aquitaine · la porcelaine', tag: 'La patience de la porcelaine', color: '#dfe7ee',
    desc: 'Elle a fait d\'une argile blanche un art de la table connu dans le monde entier, en passant des heures à cuire, émailler et peindre. Elle aime aussi le basket, le vrai, et la vache limousine, bien sûr. Un tempérament patient et minutieux, qui ne cherche pas la lumière mais soigne chaque détail, persuadé que la beauté demande du temps.',
    t: { rig: 0.95, ste: 0.9, vst: 0.12, fia: 0.9, inf: 0.12, vpo: 0.1, aud: 0.15, tmp: 0.88, ind: 0.72, con: 0.85, soc: 0.3 } },
  { name: 'Amiens', by: 'Hauts-de-France · les hortillonnages', tag: 'Une barque dans les jardins', color: '#5d8a5e',
    desc: 'Elle possède la plus vaste cathédrale gothique de France, mais c\'est en barque, au fil des hortillonnages, qu\'on la découvre vraiment : des jardins flottants, silencieux, hors du temps. Jules Verne y a passé une grande partie de sa vie à imaginer des voyages. Un tempérament rêveur et discret, qui préfère le murmure de l\'eau au bruit des foules.',
    t: { ide: 0.9, ste: 0.88, inf: 0.12, vpo: 0.06, dom: 0.08, cmp: 0.1, ouv: 0.85, soc: 0.2, vun: 0.85, vac: 0.2, aff: 0.25 } },
  { name: 'Metz', by: 'Grand Est · la lanterne du Bon Dieu', tag: 'Garde l\'œil ouvert, et les vitraux aussi', color: '#6e5a8a',
    desc: 'Sa cathédrale compte parmi les plus grandes surfaces de vitraux d\'Europe, d\'où son surnom de lanterne du Bon Dieu. Ville de garnison longtemps postée aux frontières, elle a gardé une prudence de sentinelle, adoucie par la mirabelle et un dragon de légende, le Graoully. Un tempérament attentif et réservé, qui observe avant d\'accorder sa confiance.',
    t: { vig: 0.9, thr: 0.8, nat: 0.75, san: 0.82, con: 0.85, soc: 0.25, inf: 0.18, rsk: 0.2, fia: 0.88, ide: 0.75, opt: 0.35 } },
  { name: 'Besançon', by: 'Bourgogne-Franche-Comté · la citadelle Vauban', tag: 'Réglée comme une horloge', color: '#40576b',
    desc: 'Capitale de l\'horlogerie française, elle a donné naissance à Victor Hugo et aux frères Lumière, et s\'abrite dans une boucle du Doubs gardée par une citadelle de Vauban. Comté, cancoillotte et minutes exactes : ici, rien n\'est laissé au hasard. Un tempérament précis et prévoyant, indépendant d\'esprit, qui préfère l\'ingéniosité au tapage.',
    t: { rig: 0.97, ord: 0.93, tmp: 0.9, vig: 0.85, inf: 0.12, vst: 0.2, ind: 0.82, aff: 0.85, fia: 0.9, vhe: 0.3 } },
  { name: 'Perpignan', by: 'Occitanie · le Castillet', tag: 'Le centre du monde, selon Dalí', color: '#e8b41e',
    desc: 'Salvador Dalí a décrété que sa gare était le centre du monde, et elle n\'a jamais cherché à le contredire. Catalane jusqu\'au bout de la sardane, elle soutient l\'USAP, célèbre la Sant Joan et partage le soleil avec la montagne et la mer. Un tempérament ardent et fier de ses racines, qui fait passer la fidélité et l\'émotion avant tout.',
    t: { loy: 0.9, inf: 0.93, ide: 0.88, aud: 0.82, vhe: 0.88, opn: 0.85, rig: 0.15, con: 0.15, cfl: 0.78, dip: 0.25, vse: 0.25 } },
  { name: 'Orléans', by: 'Centre-Val de Loire · Jeanne d\'Arc', tag: 'Délivrée, et reconnaissante', color: '#2e4f8f',
    desc: 'Depuis que Jeanne d\'Arc l\'a libérée en 1429, elle célèbre chaque printemps les fêtes johanniques avec une ferveur jamais démentie. Sur les bords de Loire, elle cultive la mémoire, le courage et le sens du devoir, entre deux flacons de vinaigre à l\'ancienne. Un tempérament loyal et déterminé, sérieux, qui croit aux causes qui valent la peine.',
    t: { det: 0.95, loy: 0.92, sanc: 0.8, lea: 0.85, ide: 0.82, eng: 0.85, inf: 0.25, vhe: 0.2, soc: 0.35, vtr: 0.88, dog: 0.7 } },
  { name: 'Rouen', by: 'Normandie · la ville aux cent clochers', tag: 'La mélancolie a du style', color: '#58607a',
    desc: 'Monet a peint sa cathédrale plus de trente fois, sous toutes les lumières, Flaubert y est né et le Gros-Horloge y compte les heures depuis six siècles. Il y pleut souvent, mais c\'est une pluie qui rend les colombages plus beaux. Un tempérament sensible, un peu mélancolique, qui trouve dans la grisaille une inépuisable matière à rêver.',
    t: { vis: 0.82, ide: 0.93, opt: 0.25, soc: 0.3, inf: 0.2, aff: 0.15, ouv: 0.8, vtr: 0.8, loc: 0.75, vhe: 0.6, ste: 0.75 } },
  { name: 'Caen', by: 'Normandie · le Mémorial', tag: 'Se souvenir pour la paix', color: '#3c6e71',
    desc: 'Ville de Guillaume le Conquérant et de ses deux abbayes, elle abrite aussi un Mémorial consacré à l\'histoire et à la paix, où l\'on vient de loin pour comprendre. Elle est étudiante, verte, simple, et ne se vante jamais de rien. Un tempérament réfléchi et juste, attaché à la mémoire, qui croit que le souvenir sert surtout à construire mieux.',
    t: { vun: 0.92, fair: 0.9, care: 0.9, tmp: 0.92, fia: 0.88, vhe: 0.3, dom: 0.15, vst: 0.3, cmp: 0.12, vpo: 0.1, san: 0.85 } },
  { name: 'Brest', by: 'Bretagne · la rade', tag: 'Il pleut ? Et alors ?', color: '#2c5f7c',
    desc: 'Le crachin ne l\'a jamais empêchée de sortir : elle vit face à l\'océan, entre marins, chercheurs d\'Océanopolis et grandes fêtes maritimes où les vieux gréements envahissent la rade. Elle a une réputation de bout du monde et en fait une force. Un tempérament robuste et bon enfant, qui brave les éléments et fête ça ensuite.',
    t: { san: 0.93, inc: 0.9, rsk: 0.8, thr: 0.08, vse: 0.2, soc: 0.85, det: 0.88, ord: 0.28, vpo: 0.1, loc: 0.2, con: 0.3 } },
  { name: 'Nancy', by: 'Grand Est · la place Stanislas', tag: 'La dorure et la volute', color: '#caa04a',
    desc: 'Sa place Stanislas brille de grilles dorées, son École de Nancy a fait fleurir l\'Art nouveau jusque dans les vases et les rampes d\'escalier. Entre macarons et bergamotes, elle soigne l\'apparence et le détail. Un tempérament esthète et ordonné, qui aime les belles choses bien faites et ne voit pas pourquoi l\'élégance serait superflue.',
    t: { ide: 0.9, con: 0.88, vpo: 0.82, ord: 0.9, vhe: 0.88, rsk: 0.25, com: 0.18, rig: 0.88, aff: 0.3, vst: 0.35, cfl: 0.2 } },
  { name: 'Avignon', by: 'Provence-Alpes-Côte d\'Azur · le palais des Papes', tag: 'En juillet, tout est théâtre', color: '#c0392b',
    desc: 'Elle a été la cité des papes au XIVe siècle et le reste un peu, avec son palais immense et son pont qui s\'arrête au milieu du Rhône. Mais chaque juillet, depuis 1947, le Festival la transforme en scène géante où l\'on joue à toute heure et à chaque coin de rue. Un tempérament dramatique et audacieux, qui aime être regardé et ose tout.',
    t: { inf: 0.95, ide: 0.95, aud: 0.88, ord: 0.15, rig: 0.2, vst: 0.9, dom: 0.72, vpo: 0.72, ste: 0.15, vse: 0.2, dip: 0.3 } },
  { name: 'Poitiers', by: 'Nouvelle-Aquitaine · le Futuroscope', tag: 'Roman d\'un côté, futur de l\'autre', color: '#5a8fbf',
    desc: 'Elle garde l\'une des plus belles façades romanes de France, Notre-Dame-la-Grande, une université fondée en 1431 et, à deux pas, un parc entièrement tourné vers le futur. Elle passe du Moyen Âge à la réalité virtuelle sans le moindre complexe. Un tempérament calme et curieux, optimiste sur l\'avenir, qui aime apprendre plus que se montrer.',
    t: { ouv: 0.9, vis: 0.06, tmp: 0.88, ste: 0.85, dom: 0.15, inf: 0.28, vhe: 0.35, vpo: 0.12, opt: 0.88, cfl: 0.15, dog: 0.1 } },
  { name: 'La Rochelle', by: 'Nouvelle-Aquitaine · les tours du Vieux-Port', tag: 'Libre comme un vélo jaune', color: '#f2c94c',
    desc: 'Elle a inventé le vélo en libre-service dès 1976, tient tête à l\'océan avec ses tours médiévales et accueille chaque été les Francofolies. Rebelle dans son histoire, elle garde un goût prononcé pour la liberté et le grand air. Un tempérament indépendant et solaire, sensible à la nature, qui n\'aime ni les ordres ni les cages.',
    t: { lib: 0.95, vsd: 0.92, ind: 0.88, vun: 0.92, auth: 0.1, con: 0.18, opt: 0.88, vhe: 0.82, chg: 0.78, vpo: 0.15, col: 0.3 } },
  { name: 'Pau', by: 'Nouvelle-Aquitaine · le boulevard des Pyrénées', tag: 'Un balcon sur les montagnes', color: '#6a9f58',
    desc: 'Henri IV y est né, les Britanniques y passaient l\'hiver au XIXe siècle et y ont fondé le premier golf du continent. Depuis son boulevard, elle contemple toute la chaîne des Pyrénées avec la tranquillité de celle qui a la meilleure vue. Un tempérament posé, courtois, un peu vieille France, qui préfère la contemplation à l\'agitation.',
    t: { ste: 0.92, dip: 0.88, vse: 0.88, thr: 0.1, cfl: 0.12, rsk: 0.2, vtr: 0.85, vst: 0.2, cmp: 0.2, inf: 0.3, chg: 0.1 } },
  { name: 'Bayonne', by: 'Nouvelle-Aquitaine · les fêtes en blanc et rouge', tag: 'Le foulard rouge et le jambon', color: '#d62828',
    desc: 'Fin juillet, elle s\'habille de blanc et de rouge pour cinq jours de fêtes, de chants basques et de bandas. Le reste de l\'année, elle affine son jambon, torréfie le chocolat qu\'elle fut la première à travailler en France et soutient l\'Aviron. Un tempérament festif et profondément attaché à sa culture, qui ne conçoit le bonheur que partagé en bande.',
    t: { loy: 0.95, vtr: 0.95, soc: 0.95, col: 0.92, vhe: 0.9, opn: 0.88, att: 0.88, ind: 0.12, vst: 0.75, ouv: 0.4, aff: 0.15 } },
  { name: 'Biarritz', by: 'Nouvelle-Aquitaine · les vagues', tag: 'Toujours une vague d\'avance', color: '#1fa2c6',
    desc: 'Station impériale de l\'impératrice Eugénie, elle est devenue en 1957 le berceau du surf en Europe, et n\'a jamais vraiment quitté sa planche depuis. Elle guette la houle, vit en short et se moque un peu de l\'agenda. Un tempérament audacieux et libre, un brin chic, qui court après les sensations et laisse les soucis sur la plage.',
    t: { rsk: 0.93, vst: 0.95, aud: 0.9, lib: 0.88, tmp: 0.08, ord: 0.15, vhe: 0.88, inc: 0.88, vtr: 0.3, rig: 0.25, thr: 0.1 } },
  { name: 'Ajaccio', by: 'Corse · la cité impériale', tag: 'Née pour régner', color: '#1d4e89',
    desc: 'Napoléon y est né en 1769, et elle n\'a jamais oublié qu\'elle a donné un empereur au monde. Entre ses îles Sanguinaires au couchant et son golfe éclatant, elle a le port de tête d\'une capitale. Un tempérament ambitieux et dominateur, qui aime diriger, gagner et laisser une trace, sans perdre de vue le clan d\'origine.',
    t: { vpo: 0.95, dom: 0.95, lea: 0.95, vac: 0.92, cmp: 0.92, aud: 0.88, dip: 0.2, ste: 0.2, loy: 0.85, emp: 0.35, col: 0.3 } },
  { name: 'Bastia', by: 'Corse · la place Saint-Nicolas', tag: 'La confiance se mérite, la loyauté est pour toujours', color: '#2b6a4e',
    desc: 'Tournée vers l\'Italie, elle vit entre son vieux port, sa citadelle et les polyphonies qui résonnent dans les églises. Elle soutient le Sporting avec une ferveur absolue et met du temps à vous ouvrir sa porte, mais une fois dedans, vous êtes de la famille. Un tempérament fier et entier, méfiant d\'abord, d\'une fidélité à toute épreuve ensuite.',
    t: { loy: 0.98, nat: 0.88, opn: 0.95, vtr: 0.95, col: 0.9, cfl: 0.85, dip: 0.15, ouv: 0.25, att: 0.9, com: 0.88, vst: 0.3 } },
  { name: 'Annecy', by: 'Auvergne-Rhône-Alpes · le lac', tag: 'Une carte postale bien rangée', color: '#4fb3bf',
    desc: 'On l\'appelle la Venise des Alpes : canaux fleuris, Palais de l\'Isle, et un lac réputé parmi les plus purs d\'Europe, dans lequel on se baigne l\'été. Chaque printemps, le cinéma d\'animation du monde entier s\'y donne rendez-vous. Un tempérament soigné et harmonieux, qui aime que tout soit propre, beau et paisible, sans une fausse note.',
    t: { sanc: 0.9, ord: 0.92, vse: 0.9, con: 0.85, vhe: 0.85, rsk: 0.2, cfl: 0.08, com: 0.12, ide: 0.8, inc: 0.25, thr: 0.35 } },
  { name: 'Chamonix', by: 'Auvergne-Rhône-Alpes · le mont Blanc', tag: 'Toujours plus haut', color: '#e6eef5',
    desc: 'C\'est d\'ici qu\'on est parti à l\'assaut du mont Blanc en 1786, et ici qu\'ont eu lieu les tout premiers Jeux olympiques d\'hiver, en 1924. Elle vit au rythme des cordées, des glaciers et des levers à quatre heures du matin. Un tempérament intrépide et endurant, peu porté sur le confort, qui ne se sent vivant qu\'au-dessus de trois mille mètres.',
    t: { aud: 0.97, rsk: 0.97, vst: 0.93, det: 0.93, ind: 0.9, vse: 0.08, vhe: 0.3, soc: 0.3, san: 0.92, con: 0.2, loc: 0.1 } },
  { name: 'Colmar', by: 'Grand Est · la Petite Venise', tag: 'Un livre d\'images', color: '#e07a5f',
    desc: 'Maisons à colombages vert amande et rose bonbon, barques fleuries sur la Lauch, marchés de Noël enneigés : elle ressemble à un conte qu\'on relit chaque année. Elle a vu naître Bartholdi, le sculpteur de la statue de la Liberté, et sert le vin d\'Alsace avec un bredele. Un tempérament tendre et traditionnel, qui chérit ce qui ne change pas.',
    t: { vtr: 0.95, att: 0.9, chg: 0.05, aud: 0.15, com: 0.12, vst: 0.2, ide: 0.85, vbe: 0.9, ord: 0.85, vhe: 0.82, cmp: 0.15 } },
  { name: 'Arles', by: 'Provence-Alpes-Côte d\'Azur · la lumière de Van Gogh', tag: 'Peindre avant de réfléchir', color: '#f4c430',
    desc: 'Van Gogh y a peint en un peu plus d\'un an quelque trois cents œuvres, affolé par sa lumière. Elle garde des arènes romaines, accueille chaque été les Rencontres de la photographie et ouvre sur les chevaux sauvages de Camargue. Un tempérament d\'artiste, intense et libre, qui suit ses émotions et laisse l\'ordre aux autres.',
    t: { ide: 0.97, aff: 0.05, vsd: 0.92, ind: 0.85, con: 0.1, ord: 0.12, vse: 0.2, vpo: 0.1, ouv: 0.9, vst: 0.85, auth: 0.15 } },
  { name: 'Aix-en-Provence', by: 'Provence-Alpes-Côte d\'Azur · le cours Mirabeau', tag: 'Les platanes, les fontaines et le bon goût', color: '#e3b778',
    desc: 'On l\'appelle la ville aux mille fontaines ; Cézanne y est né et n\'a jamais cessé de peindre la Sainte-Victoire. Sous les platanes du cours Mirabeau, elle déguste un calisson à l\'ombre, en tenue impeccable. Un tempérament raffiné et policé, qui aime le confort, la culture et les conversations de terrasse où l\'on ne se fâche jamais.',
    t: { vhe: 0.92, vpo: 0.78, dip: 0.9, cfl: 0.1, com: 0.15, con: 0.82, rsk: 0.25, soc: 0.8, ide: 0.8, vse: 0.82, eng: 0.15 } },
  { name: 'Carcassonne', by: 'Occitanie · la Cité', tag: 'Trois kilomètres de remparts', color: '#8d6e4a',
    desc: 'Cinquante-deux tours, une double enceinte et un pont-levis : elle a été conçue pour que personne n\'entre sans y avoir été invité. Restaurée par Viollet-le-Duc, elle veille encore sur la plaine de l\'Aude, un cassoulet au chaud derrière les créneaux. Un tempérament protecteur et méfiant, qui préfère prévoir le pire et qui garde précieusement ce qu\'il a.',
    t: { vig: 0.95, thr: 0.9, vse: 0.95, nat: 0.85, chg: 0.05, rsk: 0.08, vtr: 0.9, opn: 0.85, ouv: 0.25, inc: 0.12, soc: 0.3 } },
  { name: 'Saint-Malo', by: 'Bretagne · la cité corsaire', tag: 'Ni Français ni Bretons, Malouins', color: '#34506b',
    desc: 'Patrie de Jacques Cartier et de Surcouf, elle a toujours regardé la mer comme une promesse de conquête, et c\'est d\'ici que s\'élance tous les quatre ans la Route du Rhum. Ses grandes marées avalent les plages deux fois par jour. Un tempérament corsaire, indépendant et conquérant, qui n\'obéit qu\'à lui-même et prend le large dès qu\'il peut.',
    t: { aud: 0.95, ind: 0.92, vsd: 0.9, dom: 0.85, cmp: 0.85, auth: 0.15, con: 0.18, vac: 0.85, att: 0.35, rsk: 0.88, vbe: 0.3 } },
  { name: 'Deauville', by: 'Normandie · les planches', tag: 'Parasols, planches et paillettes', color: '#e94f64',
    desc: 'Coco Chanel y a ouvert une boutique en 1913, le cinéma américain y a son festival, et les chevaux de course y courent devant un public en chapeau. Sur les planches, on vient pour voir et pour être vu, entre deux parasols colorés. Un tempérament mondain et hédoniste, qui aime les belles choses, le beau monde et les week-ends qui durent.',
    t: { vpo: 0.93, vhe: 0.95, inf: 0.88, vun: 0.15, eng: 0.08, vac: 0.8, care: 0.3, emp: 0.3, tmp: 0.2, rig: 0.3, vtr: 0.6 } },
  { name: 'Lourdes', by: 'Occitanie · la grotte', tag: 'Une prière et une bougie', color: '#5b8bd6',
    desc: 'Depuis que Bernadette Soubirous y a vu une apparition en 1858, des millions de pèlerins viennent chaque année se recueillir devant la grotte, porter des malades, chanter aux flambeaux. Au point qu\'elle compte plus de chambres d\'hôtel que presque toute autre ville de France. Un tempérament fervent et compatissant, tourné vers les autres et vers le ciel.',
    t: { sanc: 0.98, care: 0.95, emp: 0.93, vtr: 0.93, loc: 0.88, vbe: 0.9, vst: 0.12, vhe: 0.15, aff: 0.1, vac: 0.2, dog: 0.72 } },
  { name: 'Cannes', by: 'Provence-Alpes-Côte d\'Azur · la Croisette', tag: 'Monter les marches', color: '#c6a15b',
    desc: 'Chaque mois de mai, le monde entier regarde ses marches rouges et attend de savoir qui repartira avec la palme d\'or. Elle vit pour ces douze jours de flashs, de robes longues et de rivalités feutrées, puis se repose le reste de l\'année au bord de la Croisette. Un tempérament ambitieux et théâtral, qui aime la compétition autant que la lumière.',
    t: { vac: 0.95, cmp: 0.93, inf: 0.93, vpo: 0.92, dom: 0.8, ste: 0.15, vun: 0.25, emp: 0.25, vst: 0.8, col: 0.15, fia: 0.35 } },
  { name: 'Saint-Tropez', by: 'Provence-Alpes-Côte d\'Azur · le port', tag: 'Et Dieu créa la sieste', color: '#ff7f6e',
    desc: 'Village de pêcheurs devenu légende avec Brigitte Bardot, célèbre pour ses gendarmes de cinéma et sa tarte à la crème, elle ne vit qu\'au présent, entre le port, la plage et l\'apéritif chez Sénéquier. Les horaires ? Elle ne connaît pas. Un tempérament insouciant et jouisseur, allergique aux contraintes, qui fait de chaque journée des vacances.',
    t: { vhe: 0.98, lib: 0.93, tmp: 0.05, ord: 0.08, rig: 0.08, con: 0.1, vse: 0.2, vst: 0.88, fia: 0.3, vac: 0.3, epi: 0.1 } },
  { name: 'Versailles', by: 'Île-de-France · le château', tag: 'L\'étiquette avant tout', color: '#b8962e',
    desc: 'Galerie des Glaces, jardins tirés au cordeau par Le Nôtre, protocole réglé à la minute sous Louis XIV : elle a inventé la manière de bien se tenir. Aujourd\'hui encore, les allées sont droites, les buis taillés et chaque chose est à sa place. Un tempérament solennel et hiérarchique, attaché aux règles, qui ne voit rien d\'excessif dans un peu de grandeur.',
    t: { auth: 0.97, ord: 0.97, con: 0.95, vpo: 0.95, vtr: 0.92, lib: 0.12, inc: 0.12, dog: 0.8, chg: 0.05, lea: 0.85, ste: 0.6 } },
  { name: 'Vichy', by: 'Auvergne-Rhône-Alpes · les sources', tag: 'Prendre soin, tout doucement', color: '#8ec5c0',
    desc: 'Reine des villes d\'eaux, classée à l\'UNESCO avec les grandes stations thermales d\'Europe, elle soigne depuis des siècles à coups de cures, de parcs ombragés et de pastilles à la menthe. Napoléon III y lançait la mode, l\'opéra Art nouveau en garde le souvenir. Un tempérament attentionné, prudent et paisible, qui préfère prévenir que guérir.',
    t: { care: 0.95, vse: 0.93, ste: 0.93, rsk: 0.08, vst: 0.1, thr: 0.7, cmp: 0.1, dom: 0.12, tmp: 0.85, vig: 0.85, aud: 0.1 } },
  { name: 'Roubaix', by: 'Hauts-de-France · le vélodrome', tag: 'L\'enfer du Nord, et fière de l\'être', color: '#8a8d91',
    desc: 'Chaque printemps, les meilleurs coureurs du monde traversent des secteurs pavés redoutables pour finir couverts de boue sur son vélodrome. Elle a aussi fait d\'une piscine Art déco l\'un des plus beaux musées de France. Un tempérament tenace et combatif, qui aime l\'effort pour l\'effort et sait transformer ce qui semblait usé en quelque chose d\'éclatant.',
    t: { det: 0.98, com: 0.88, cfl: 0.82, vhe: 0.15, aud: 0.85, san: 0.88, cmp: 0.88, loc: 0.08, ide: 0.8, vse: 0.2, dip: 0.25 } },
  { name: 'Dunkerque', by: 'Hauts-de-France · le carnaval', tag: 'Le chahut, le hareng et le parapluie', color: '#e84d8a',
    desc: 'Pendant son carnaval, des milliers de gens déguisés chantent, se serrent en « chahut » et tendent les bras pour attraper les harengs lancés du balcon de l\'hôtel de ville. Le reste du temps, la cité de Jean Bart garde l\'humour et la solidarité des gens de mer. Un tempérament exubérant et collectif, qui pense que tout va mieux quand on est serrés les uns contre les autres.',
    t: { soc: 0.98, inf: 0.95, col: 0.95, vhe: 0.9, con: 0.12, ord: 0.2, vpo: 0.06, att: 0.9, loy: 0.88, aff: 0.12, ind: 0.1 } },
  { name: 'Fort-de-France', by: 'Martinique · la baie', tag: 'La biguine et le temps qui s\'étire', color: '#e76f51',
    desc: 'Entre la baie, le jardin de Balata et la bibliothèque Schœlcher, elle vit au rythme de la biguine, du madras et du rhum agricole, le seul au monde à avoir son appellation d\'origine. On y parle poésie, on y danse tard, et l\'on ne voit pas l\'intérêt de se presser. Un tempérament chaleureux et créatif, qui savoure l\'instant plutôt que de courir après.',
    t: { vhe: 0.9, ide: 0.9, att: 0.88, tmp: 0.12, inf: 0.85, ord: 0.22, vtr: 0.85, ste: 0.75, vac: 0.25, cmp: 0.15, rig: 0.25 } },
  { name: 'Pointe-à-Pitre', by: 'Guadeloupe · le gwoka', tag: 'Le tambour ne s\'arrête jamais', color: '#f4a300',
    desc: 'C\'est ici que la Route du Rhum termine sa traversée, sous les klaxons et les applaudissements. Au son du gwoka, inscrit à l\'UNESCO, et pendant les déboulés du carnaval, elle entraîne tout le monde dans sa danse, entre marché aux épices et accras. Un tempérament vibrant et collectif, énergique, qui ne tient pas en place et vit tout en musique.',
    t: { vst: 0.92, soc: 0.93, inf: 0.92, col: 0.88, rig: 0.2, vse: 0.2, aud: 0.82, ste: 0.1, loy: 0.85, vtr: 0.82, san: 0.3 } },
  { name: 'Saint-Denis de La Réunion', by: 'La Réunion · le Barachois', tag: 'Tout le monde à la même table', color: '#3aa76d',
    desc: 'Temple tamoul, mosquée, pagode et cathédrale à quelques rues d\'écart : elle a fait du mélange une manière de vivre. On y partage le cari, on danse le maloya, inscrit à l\'UNESCO, et l\'on salue la mer depuis le Barachois. Un tempérament ouvert et tolérant, qui accueille chacun tel qu\'il est et trouve que la différence, ça s\'assaisonne.',
    t: { vun: 0.95, ouv: 0.95, dog: 0.05, opn: 0.05, dip: 0.9, fair: 0.9, nat: 0.1, cfl: 0.12, att: 0.88, vco: 0.3, thr: 0.12 } },
  { name: 'Nouméa', by: 'Nouvelle-Calédonie · le lagon', tag: 'Loin de tout, près du lagon', color: '#00a6a6',
    desc: 'À plus de seize mille kilomètres de Paris, elle vit les pieds dans un lagon classé à l\'UNESCO, parmi les plus grands du monde, entre l\'anse Vata et la baie des Citrons. Le reste du monde semble très loin, et c\'est un peu le principe. Un tempérament détendu et autonome, qui n\'a rien à prouver à personne et préfère la baignade à la course aux honneurs.',
    t: { vsd: 0.88, ind: 0.9, vac: 0.15, cmp: 0.08, thr: 0.08, vhe: 0.9, tmp: 0.12, vpo: 0.1, vun: 0.85, lea: 0.2, ord: 0.3 } },
  { name: 'Le Mont-Saint-Michel', by: 'Normandie · la merveille de l\'Occident', tag: 'Seul au milieu de la baie', color: '#8a9ba8',
    desc: 'Une trentaine d\'habitants, une abbaye perchée et une mer qui arrive au galop à chaque grande marée : c\'est la commune la plus solitaire et la plus visitée à la fois. Elle se suffit à elle-même, entourée de sable, de silence et d\'une omelette légendaire. Un tempérament contemplatif et secret, qui a besoin de distance pour se sentir bien.',
    t: { soc: 0.06, ind: 0.95, inf: 0.08, att: 0.25, sanc: 0.88, vtr: 0.88, ste: 0.85, vst: 0.2, col: 0.2, vsd: 0.8, ide: 0.82 } },
];

window.PRISME_CITIES = { CITIES };
