/* ============================================================
   PRISME — « Si tu étais un vêtement »
   ------------------------------------------------------------
   Pas ce que tu portes : le vêtement dont le caractère ressemble au
   tien. Celui qui se voit ou se fait oublier, celui qui dure des années
   ou change à chaque saison, celui qui protège ou celui qui affirme.
   Des faits exacts, de la tendresse, un peu d'humour.
     name = le vêtement, by = famille · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const CLOTHES = [
  { name: 'Le jean', by: 'Bas · 1873, Levi Strauss et Jacob Davis', tag: 'Il va avec tout, et il tient', color: '#3b5b8c',
    desc: 'Breveté en 1873 par Levi Strauss et le tailleur Jacob Davis pour les travailleurs de l\'Ouest américain, il a depuis traversé les usines, les concerts et les bureaux du vendredi. Il s\'use, s\'adoucit, se déchire et reste là. C\'est le tempérament des solides sans chichis, qui s\'adaptent à toutes les situations sans jamais devenir quelqu\'un d\'autre.',
    t: { fia: 0.92, ste: 0.8, epi: 0.1, vpo: 0.15, inc: 0.7, dog: 0.15, aff: 0.6, vtr: 0.55, soc: 0.65, vst: 0.35, det: 0.8 } },
  { name: 'Le t-shirt blanc', by: 'Haut · ancien maillot de corps des marins', tag: 'Le simple, sans effort', color: '#b9b3a6',
    desc: 'Longtemps caché sous l\'uniforme des marins américains, il est sorti au grand jour quand Marlon Brando l\'a porté seul à l\'écran, en 1951. Pas de logo, pas de message, pas d\'histoire à raconter. C\'est le tempérament des simples assumés, calmes et sans prétention, qui n\'ont rien à prouver et trouvent que l\'essentiel se passe très bien d\'ornements.',
    t: { vpo: 0.05, vac: 0.15, ste: 0.85, dom: 0.15, inf: 0.25, epi: 0.1, dog: 0.1, san: 0.8, cfl: 0.2, cmp: 0.15 } },
  { name: 'La chemise blanche', by: 'Haut · repassée la veille', tag: 'Impeccable jusqu\'au dernier bouton', color: '#9fb2c6',
    desc: 'Elle passe de l\'entretien d\'embauche au mariage sans jamais faire de faute de goût, à condition d\'avoir été repassée la veille. La moindre tache se voit, alors elle fait attention à tout. C\'est le tempérament des sérieux et des méthodiques, qui préparent leurs affaires à l\'avance, tiennent leurs engagements et détestent arriver froissés.',
    t: { rig: 0.95, con: 0.85, vco: 0.8, ord: 0.9, vac: 0.75, vst: 0.15, vhe: 0.2, chg: 0.15, aff: 0.8, rsk: 0.15 } },
  { name: 'La marinière', by: 'Haut · réglementaire dans la Marine depuis 1858', tag: 'Des rayures et un équipage', color: '#1f3a6e',
    desc: 'Adoptée par la Marine nationale en 1858, avec ses rayures bien visibles en mer, elle est devenue le symbole joyeux d\'une côte, d\'un pays et d\'un certain art de vivre. C\'est le tempérament des fidèles enthousiastes, attachés à leurs racines et à leur bande, qui se sentent chez eux partout où il y a un équipage, du vent et une bonne raison de chanter.',
    t: { loy: 0.92, vtr: 0.8, opn: 0.8, col: 0.85, soc: 0.75, opt: 0.8, vpo: 0.2, cmp: 0.2, aff: 0.3, nat: 0.25 } },
  { name: 'Le trench-coat', by: 'Manteau · né dans les tranchées de 1914', tag: 'Col relevé, regard aux aguets', color: '#b59a6d',
    desc: 'Conçu pour les officiers britanniques des tranchées, il est ensuite passé aux détectives et aux espions de cinéma, ceinture serrée et col relevé. Il observe, il note, il ne dit presque rien. C\'est le tempérament des vigilants discrets, qui remarquent tout, se méfient des évidences et gardent leur jeu bien caché jusqu\'au dernier moment.',
    t: { vig: 0.95, nat: 0.85, thr: 0.8, san: 0.85, soc: 0.2, inf: 0.15, aff: 0.85, emp: 0.35, opt: 0.3, rig: 0.7 } },
  { name: 'Le perfecto', by: 'Manteau · 1928, Irving Schott', tag: 'Le cuir des insoumis', color: '#1c1c1c',
    desc: 'Créé en 1928 par Irving Schott, qui lui a donné le nom de ses cigares préférés, il a roulé avec Marlon Brando dans L\'Équipée sauvage puis traversé tous les concerts de rock. C\'est le tempérament des insoumis, qui n\'aiment ni les ordres ni les cases, disent les choses en face et préfèrent une route cabossée à une vie bien rangée.',
    t: { vco: 0.05, auth: 0.05, lib: 0.95, aud: 0.9, rsk: 0.85, chg: 0.8, cfl: 0.85, com: 0.85, vse: 0.15, con: 0.1 } },
  { name: 'La doudoune', by: 'Manteau · brevetée par Eddie Bauer en 1940', tag: 'Elle protège tout le monde du froid', color: '#2c6e8f',
    desc: 'Eddie Bauer l\'a brevetée en 1940, quelques années après avoir failli mourir de froid lors d\'une partie de pêche. Depuis, elle gonfle, elle enveloppe et elle tient chaud sans poser de questions. C\'est le tempérament des protecteurs, qui prévoient toujours un pull de plus pour les autres et font passer la sécurité de leurs proches avant le style.',
    t: { vse: 0.95, care: 0.9, vbe: 0.9, thr: 0.7, rsk: 0.1, vst: 0.15, lea: 0.7, aud: 0.2, vhe: 0.3, fia: 0.85 } },
  { name: 'Le pull de Noël', by: 'Haut · un renne brodé, une fois par an', tag: 'Moche, et fier de l\'être', color: '#b3202b',
    desc: 'Un renne au nez rouge, des flocons, parfois une clochette qui sonne : il ne sort qu\'en décembre et fait sourire tout le monde. Personne ne l\'a jamais trouvé élégant, et c\'est exactement le but. C\'est le tempérament des cœurs chaleureux qui aiment les traditions et les tablées bruyantes, et préfèrent le fou rire en famille à la dignité.',
    t: { att: 0.95, vtr: 0.8, soc: 0.9, vhe: 0.8, opt: 0.9, rig: 0.15, vpo: 0.05, loy: 0.8, aff: 0.1, nat: 0.1 } },
  { name: 'Le pull col roulé', by: 'Haut · l\'uniforme de ceux qui pensent', tag: 'La tête au chaud, les idées claires', color: '#2b2b33',
    desc: 'Porté par les existentialistes de Saint-Germain-des-Prés, puis par Steve Jobs sur scène, il est devenu l\'uniforme de ceux qui réfléchissent. Sobre, un peu distant, il laisse toute la place à la conversation. C\'est le tempérament des cérébraux, curieux de tout, qui aiment les grandes idées, les débats serrés et un certain quant-à-soi.',
    t: { aff: 0.95, ouv: 0.9, soc: 0.25, inf: 0.2, ide: 0.8, epi: 0.8, att: 0.25, vhe: 0.3, rig: 0.7, emp: 0.4 } },
  { name: 'Le cardigan de grand-père', by: 'Haut · baptisé d\'après le comte de Cardigan', tag: 'Doux, patient, et plein de poches', color: '#8a6f4d',
    desc: 'Il doit son nom au septième comte de Cardigan, officier britannique de la guerre de Crimée, mais il a surtout fait carrière dans les fauteuils. Boutonné de travers, un mouchoir dans la poche, il ne bouge pas vite. C\'est le tempérament des doux patients, qui préfèrent le monde d\'avant, écoutent sans juger et ont toujours un bonbon quelque part.',
    t: { ste: 0.95, vtr: 0.9, vbe: 0.85, att: 0.8, vst: 0.05, rsk: 0.1, chg: 0.05, dom: 0.05, cfl: 0.1, vis: 0.75 } },
  { name: 'Le sweat à capuche', by: 'Haut · années 1930, pour les entrepôts froids', tag: 'Capuche relevée, monde en sourdine', color: '#6d7378',
    desc: 'Il a été conçu dans les années 1930 pour les ouvriers des entrepôts frigorifiques de l\'État de New York, puis adopté par les sportifs, les étudiants et tous ceux qui veulent qu\'on les laisse tranquilles. C\'est le tempérament des indépendants discrets, qui aiment leur bulle, n\'ont pas besoin d\'être vus et suivent leur propre chemin.',
    t: { soc: 0.15, inf: 0.1, ind: 0.9, vco: 0.25, lea: 0.1, vpo: 0.1, vsd: 0.85, auth: 0.2, att: 0.3, vhe: 0.65 } },
  { name: 'Le costume trois-pièces', by: 'Tenue · le gilet imposé en 1666', tag: 'Taillé pour diriger', color: '#2f3542',
    desc: 'C\'est Charles II d\'Angleterre qui imposa en 1666 le gilet sous la veste, et l\'ensemble n\'a jamais vraiment quitté les salles de conseil. Tout est ajusté, rien n\'est laissé au hasard. C\'est le tempérament des ambitieux qui aiment tenir la barre, décider vite et gagner, quitte à ne pas toujours être le plus chaleureux de la réunion.',
    t: { vpo: 0.9, vac: 0.95, lea: 0.9, dom: 0.85, cmp: 0.85, auth: 0.8, care: 0.3, vun: 0.2, vhe: 0.3, att: 0.25 } },
  { name: 'Le smoking', by: 'Tenue · veste de fumoir devenue tenue de gala', tag: 'Le charme en noir et blanc', color: '#111111',
    desc: 'À l\'origine, c\'était la veste qu\'on enfilait au XIXe siècle pour aller fumer après le dîner sans imprégner son habit. Aujourd\'hui, il règne sur les galas et les cérémonies. C\'est le tempérament des charmeurs élégants, à l\'aise dans tous les salons, qui savent faire une entrée, trouver le bon mot et garder leur calme même quand le champagne manque.',
    t: { inf: 0.9, dip: 0.85, san: 0.9, soc: 0.85, vhe: 0.8, vpo: 0.7, ste: 0.3, vun: 0.25, epi: 0.2, com: 0.2 } },
  { name: 'La petite robe noire', by: 'Robe · Coco Chanel, 1926', tag: 'Moins, mais parfaitement', color: '#26222a',
    desc: 'En 1926, le magazine Vogue compare la robe noire toute simple de Coco Chanel à la Ford T : un modèle pour tout le monde, qui ne se démode pas. Elle n\'en fait jamais trop et n\'a jamais tort. C\'est le tempérament des sûrs d\'eux discrets, indépendants et exigeants, qui préfèrent une seule bonne décision à dix hésitations.',
    t: { ind: 0.85, san: 0.9, rig: 0.85, ord: 0.75, vtr: 0.3, inf: 0.25, dog: 0.25, chg: 0.6, aff: 0.75, att: 0.3, vhe: 0.4 } },
  { name: 'La robe de soirée', by: 'Robe · faite pour le tapis rouge', tag: 'Elle ne passe pas inaperçue', color: '#a3195b',
    desc: 'Longue, brillante, parfois interminable dans les escaliers, elle n\'a qu\'une mission : faire tourner les têtes le temps d\'une soirée. Elle sait qu\'elle ne ressortira pas demain, alors elle en profite. C\'est le tempérament des flamboyants, qui aiment les grandes occasions, la lumière et les sensations fortes, et vivent chaque soirée comme si c\'était la dernière.',
    t: { inf: 0.95, vpo: 0.8, vhe: 0.9, soc: 0.9, aud: 0.8, ste: 0.15, vse: 0.25, tmp: 0.1, rig: 0.3, vun: 0.25 } },
  { name: 'La jupe plissée', by: 'Bas · l\'uniforme des écoles', tag: 'Chaque pli à sa place', color: '#3d4f7a',
    desc: 'Associée aux uniformes scolaires, elle garde ses plis au millimètre et ne supporte pas qu\'on les écrase. Elle connaît le règlement, et elle l\'aime bien. C\'est le tempérament des consciencieux, qui respectent les règles parce qu\'elles rendent la vie plus juste, rendent leurs devoirs à l\'heure et rangent leur trousse avant de partir.',
    t: { con: 0.95, vco: 0.9, rig: 0.9, ord: 0.95, auth: 0.8, rsk: 0.1, vst: 0.15, lib: 0.2, com: 0.2, fair: 0.8 } },
  { name: 'La salopette', by: 'Bas · du jardin à l\'atelier', tag: 'Les mains dans la peinture', color: '#4a7fb5',
    desc: 'Vêtement de travail des fermiers et des peintres en bâtiment, elle a des poches pour tout et une bretelle qui glisse toujours. On la porte pour bricoler, jardiner, repeindre la chambre ou simplement s\'amuser. C\'est le tempérament des créatifs joyeux et touche-à-tout, qui préfèrent faire que paraître et trouvent la vie plus drôle avec un peu de peinture sur les genoux.',
    t: { ide: 0.85, opt: 0.9, vpo: 0.05, vco: 0.25, vst: 0.75, rig: 0.3, soc: 0.7, aff: 0.25, dog: 0.1, vac: 0.3 } },
  { name: 'Le jogging', by: 'Bas · rarement porté pour courir', tag: 'Le confort avant tout le reste', color: '#7c8a96',
    desc: 'Inventé pour le sport, il a trouvé sa vraie vocation sur les canapés, dans les files d\'attente et pendant les dimanches pluvieux. Taille élastique, aucune ambition cachée. C\'est le tempérament des détendus qui connaissent la valeur du confort, ne courent après rien et trouvent que la meilleure façon de gérer le stress, c\'est de ne pas l\'inviter.',
    t: { vhe: 0.95, vac: 0.1, det: 0.2, rig: 0.1, ord: 0.1, vpo: 0.05, san: 0.8, tmp: 0.1, lea: 0.1, thr: 0.15, cmp: 0.15 } },
  { name: 'Le bleu de travail', by: 'Tenue · la tenue des cols bleus', tag: 'Le travail bien fait, ensemble', color: '#2a4b8d',
    desc: 'Il a habillé les ouvriers, les mécaniciens et les cheminots, au point que l\'on appelle « cols bleus » ceux qui le portent. Il ne se plaint pas des taches, il les collectionne. C\'est le tempérament des travailleurs solidaires, qui savent ce que vaut une journée bien remplie, se serrent les coudes et n\'aiment pas qu\'on les prenne de haut.',
    t: { det: 0.95, fia: 0.9, col: 0.85, fair: 0.9, vpo: 0.1, vhe: 0.2, epi: 0.15, loy: 0.85, ide: 0.2, cmp: 0.25 } },
  { name: 'La blouse blanche', by: 'Tenue · de l\'hôpital au laboratoire', tag: 'Soigner, avec méthode', color: '#6fa3b0',
    desc: 'Elle est devenue blanche à la fin du XIXe siècle, quand l\'hygiène est entrée à l\'hôpital, et elle n\'a plus quitté les couloirs ni les laboratoires. Rassurante et précise, elle écoute avant d\'agir. C\'est le tempérament des soignants méthodiques, qui prennent soin des autres avec rigueur, gardent la tête froide et ne laissent rien au hasard.',
    t: { care: 0.95, rig: 0.9, aff: 0.7, san: 0.85, emp: 0.8, vse: 0.7, vhe: 0.15, rsk: 0.15, inf: 0.3, vst: 0.3 } },
  { name: 'Le kilt', by: 'Bas · le petit kilt date du XVIIIe siècle', tag: 'Le clan avant tout', color: '#2e6b4a',
    desc: 'Sa forme actuelle, plus courte que l\'ancien grand plaid, s\'est imposée en Écosse au XVIIIe siècle, et chaque tartan raconte l\'histoire d\'un clan. Il faut un certain aplomb pour le porter par grand vent. C\'est le tempérament des fiers et des loyaux, attachés à leur famille et à leur terre, qui défendent les leurs avec panache.',
    t: { loy: 0.95, vtr: 0.9, aud: 0.85, opn: 0.85, col: 0.85, com: 0.8, cfl: 0.75, vun: 0.3, ste: 0.3, ouv: 0.35 } },
  { name: 'Le béret', by: 'Tête · venu des bergers pyrénéens', tag: 'Enfoncé, et bien décidé', color: '#1f1f2e',
    desc: 'Né chez les bergers des Pyrénées, il est devenu l\'emblème d\'un certain Français têtu, baguette sous le bras. Il ne change pas de forme, ni d\'avis. C\'est le tempérament des enracinés au franc-parler, qui ont des convictions solides, se méfient des modes venues d\'ailleurs et trouvent que c\'était souvent mieux avant, et le disent.',
    t: { opn: 0.95, vtr: 0.85, com: 0.85, dog: 0.8, chg: 0.1, vst: 0.15, inc: 0.2, nat: 0.7, ouv: 0.25, vis: 0.8 } },
  { name: 'La casquette', by: 'Tête · visière devant ou derrière', tag: 'Avec la bande, toujours', color: '#c0392b',
    desc: 'Venue des terrains de baseball, elle s\'est installée dans les cours de récréation, les stades et les pieds d\'immeubles. Visière devant, derrière ou de côté, elle a toujours un avis sur la question. C\'est le tempérament des compétiteurs sociables, fidèles à leur bande, qui aiment les défis, les chambrages et les victoires partagées.',
    t: { cmp: 0.85, col: 0.75, loy: 0.8, vtr: 0.1, rig: 0.2, con: 0.15, soc: 0.85, vac: 0.65, tmp: 0.15, aff: 0.3 } },
  { name: 'Le bonnet', by: 'Tête · dès le premier courant d\'air', tag: 'Frileux, et prévoyant', color: '#5d7fa3',
    desc: 'Il sort dès le premier courant d\'air et reste enfoncé jusqu\'aux sourcils bien après le retour du printemps. Il préfère avoir trop chaud que prendre le moindre risque. C\'est le tempérament des prudents un peu inquiets, qui ont toujours un plan B, un parapluie et une écharpe de secours, et qu\'on appelle en premier quand quelque chose tourne mal.',
    t: { thr: 0.9, vig: 0.85, vse: 0.85, rsk: 0.05, aud: 0.1, san: 0.25, inc: 0.15, vis: 0.7, opt: 0.3, vst: 0.15 } },
  { name: 'Le panama', by: 'Tête · tressé en Équateur, malgré son nom', tag: 'L\'élégance sans se presser', color: '#d8c38e',
    desc: 'Malgré son nom, il est tressé en Équateur ; il doit sa célébrité aux ouvriers du canal de Panama, qui le portaient contre le soleil. Il ne se presse jamais et ne perd jamais son calme. C\'est le tempérament des sereins élégants, qui prennent la vie à l\'ombre, évitent les disputes inutiles et savent qu\'un problème attend très bien la fin de la sieste.',
    t: { san: 0.95, ste: 0.9, vhe: 0.75, dip: 0.85, thr: 0.05, vst: 0.2, cfl: 0.1, com: 0.15, cmp: 0.1, vac: 0.2 } },
  { name: 'Le borsalino', by: 'Tête · Alessandria, 1857', tag: 'Il entre, la pièce se tait', color: '#5b4636',
    desc: 'Fondée en 1857 à Alessandria, en Italie, la maison Borsalino a coiffé les stars d\'Hollywood et donné son nom à un film de 1970 avec Alain Delon et Jean-Paul Belmondo. Bord baissé, il en dit peu et on l\'écoute. C\'est le tempérament des assurés qui imposent leur présence, aiment le risque calculé et ne donnent leur confiance qu\'au compte-gouttes.',
    t: { dom: 0.9, san: 0.9, vpo: 0.8, nat: 0.8, rsk: 0.75, cfl: 0.7, emp: 0.3, soc: 0.35, fair: 0.35, lea: 0.8 } },
  { name: 'L\'écharpe', by: 'Cou · tricotée par quelqu\'un qui vous aime', tag: 'Elle enveloppe sans rien demander', color: '#c56b5c',
    desc: 'Souvent tricotée à la main par une personne qui vous aime, elle fait plusieurs fois le tour du cou et ne demande rien en échange. On la prête, on la perd, on la retrouve. C\'est le tempérament des tendres et des attentionnés, qui sentent quand quelqu\'un a froid avant qu\'il le dise, et qui fuient les disputes comme les courants d\'air.',
    t: { att: 0.95, care: 0.9, emp: 0.9, vbe: 0.95, cfl: 0.1, dom: 0.1, cmp: 0.1, vpo: 0.1, aff: 0.1, com: 0.2 } },
  { name: 'La cravate', by: 'Cou · héritée des cavaliers croates', tag: 'Le nœud bien serré', color: '#7a1f2b',
    desc: 'Elle viendrait des foulards des cavaliers croates au service de Louis XIII, d\'où son nom, et elle n\'a jamais vraiment quitté les bureaux. Nouée serrée, bien droite, elle respecte la hiérarchie et les usages. C\'est le tempérament des loyaux disciplinés, qui croient aux règles, à l\'ordre et à la parole donnée, et se méfient un peu de ceux qui dénouent tout.',
    t: { auth: 0.95, vco: 0.95, con: 0.9, lib: 0.15, chg: 0.1, vst: 0.1, loy: 0.8, dog: 0.7, ide: 0.15, inc: 0.2 } },
  { name: 'Le nœud papillon', by: 'Cou · noué à la main, sinon rien', tag: 'Excentrique, mais très précis', color: '#6c3483',
    desc: 'Les puristes le nouent à la main et gardent un petit mépris affectueux pour les modèles tout faits. Il est un peu de travers, un peu original, et très sûr de son effet. C\'est le tempérament des excentriques érudits, qui collectionnent les savoirs bizarres, cultivent leur différence avec le plus grand sérieux et ne ressemblent à personne.',
    t: { ide: 0.9, ouv: 0.85, vco: 0.15, rig: 0.75, vst: 0.75, dog: 0.3, cmp: 0.2, ind: 0.8, soc: 0.4, col: 0.2 } },
  { name: 'Les bretelles', by: 'Accessoire · elles tiennent tout', tag: 'Tout tient grâce à elles', color: '#8b5a2b',
    desc: 'Discrètes sous la veste, elles tiennent le pantalon bien en place et ne lâchent jamais, même après un repas de fête. Personne ne les remarque, mais sans elles tout tomberait. C\'est le tempérament des fiables à toute épreuve, prévoyants et constants, qui assurent en coulisses, anticipent les problèmes et ne demandent aucune médaille.',
    t: { fia: 0.98, vse: 0.85, tmp: 0.85, rsk: 0.1, vst: 0.15, inf: 0.15, vpo: 0.1, det: 0.8, vig: 0.8, vhe: 0.3 } },
  { name: 'Les chaussettes dépareillées', by: 'Pieds · une rayée, une à pois', tag: 'Le désordre avec le sourire', color: '#e67e22',
    desc: 'Une rayée, une à pois, et aucune intention de chercher la paire. Personne ne sait où partent les chaussettes perdues, mais elles, elles s\'en moquent. C\'est le tempérament des fantaisistes, créatifs et gentiment chaotiques, qui trouvent que les règles de goût sont faites pour être contournées et que l\'imprévu rend la journée meilleure.',
    t: { ord: 0.05, rig: 0.05, con: 0.05, ide: 0.95, vst: 0.85, inc: 0.9, dog: 0.05, vco: 0.1, opt: 0.85, chg: 0.8 } },
  { name: 'Les chaussettes-sandales', by: 'Pieds · pratique, et tant pis', tag: 'Pratique, et tant pis pour le reste', color: '#9c8a6b',
    desc: 'Les pieds au chaud, les orteils à l\'air, et une indifférence totale aux regards des passants. C\'est illogique pour certains, parfaitement raisonnable pour elles. C\'est le tempérament des pragmatiques têtus et indépendants, qui choisissent ce qui marche plutôt que ce qui se fait, et ne changeront pas d\'avis parce qu\'on leur fait les gros yeux.',
    t: { vco: 0.05, ind: 0.9, epi: 0.05, inf: 0.15, vpo: 0.05, aff: 0.8, san: 0.8, dog: 0.65, ouv: 0.3, vst: 0.2, soc: 0.3 } },
  { name: 'Les pantoufles', by: 'Pieds · au pied du canapé', tag: 'Rien ne vaut la maison', color: '#a67c52',
    desc: 'Elles attendent patiemment au pied du lit ou devant la porte, prêtes pour le retour à la maison. Elles n\'ont jamais vu la pluie et ne s\'en plaignent pas. C\'est le tempérament des casaniers heureux, qui aiment leurs habitudes, leur canapé et les soirées sans imprévu, et trouvent que l\'aventure se vit très bien depuis un fauteuil.',
    t: { opn: 0.85, vst: 0.05, rsk: 0.05, soc: 0.2, vse: 0.9, vhe: 0.85, ste: 0.9, chg: 0.1, aud: 0.1, ouv: 0.3 } },
  { name: 'Les tongs', by: 'Pieds · inspirées des zori japonaises', tag: 'Les vacances toute l\'année', color: '#1abc9c',
    desc: 'Inspirées des sandales traditionnelles japonaises, elles annoncent leur arrivée à chaque pas et ne pensent qu\'à la plage. Pas faites pour courir, encore moins pour réfléchir à demain. C\'est le tempérament des insouciants solaires, sociables et légers, qui vivent au jour le jour et ont toujours une glace à partager.',
    t: { tmp: 0.05, vhe: 0.95, vse: 0.15, rig: 0.05, ord: 0.05, thr: 0.05, soc: 0.85, opt: 0.9, vig: 0.1, aff: 0.2 } },
  { name: 'Les baskets blanches', by: 'Pieds · le blanc qui ne le reste jamais', tag: 'Nettes, et dans l\'air du temps', color: '#9aa7b0',
    desc: 'Tout le monde en a une paire, et chacun les défend contre la moindre trace de boue. Elles sont modernes, confortables, et s\'accordent avec tout, à condition de rester impeccables. C\'est le tempérament des perfectionnistes dans l\'air du temps, qui aiment ce qui est nouveau, net et efficace, et gardent une vieille brosse à dents pour les semelles.',
    t: { rig: 0.85, vac: 0.75, chg: 0.7, vtr: 0.15, con: 0.75, vis: 0.15, opt: 0.8, vig: 0.7, vst: 0.65, epi: 0.2, vsd: 0.4 } },
  { name: 'Les bottes de pluie', by: 'Pieds · les wellingtons, depuis le XIXe siècle', tag: 'Droit dans les flaques', color: '#2e7d32',
    desc: 'Les Anglais les appellent wellingtons, en souvenir du duc qui avait lancé la mode des bottes hautes au XIXe siècle. Elles ne contournent pas les flaques, elles sautent dedans. C\'est le tempérament des aventuriers de plein air, que le mauvais temps n\'arrête jamais, qui aiment la nature brute et trouvent qu\'une balade sans boue n\'en est pas vraiment une.',
    t: { vun: 0.85, inc: 0.85, aud: 0.75, vst: 0.75, thr: 0.2, det: 0.8, vhe: 0.3, dog: 0.15, vpo: 0.1, opt: 0.75, ord: 0.35 } },
  { name: 'Les rangers', by: 'Pieds · lacées jusqu\'en haut', tag: 'Elles ne reculent pas', color: '#3e3b32',
    desc: 'Lacées jusqu\'en haut, elles viennent des terrains militaires et n\'ont jamais appris à marcher sur la pointe des pieds. Elles supportent tout, sauf qu\'on leur marche dessus. C\'est le tempérament des combatifs, qui foncent, disent les choses sans enrober, défendent l\'ordre et leur territoire, et préfèrent un bon affrontement à un compromis mou.',
    t: { com: 0.95, cfl: 0.95, auth: 0.85, det: 0.9, emp: 0.2, dip: 0.1, dom: 0.9, thr: 0.8, care: 0.3, vhe: 0.2 } },
  { name: 'Les escarpins', by: 'Pieds · dix centimètres d\'ambition', tag: 'Viser haut, quoi qu\'il en coûte', color: '#b0103a',
    desc: 'Ils font gagner quelques centimètres et beaucoup d\'assurance, au prix de quelques ampoules que personne ne verra. Ils tiennent la réunion jusqu\'au bout, quitte à se faire discrètement retirer sous la table. C\'est le tempérament des ambitieux déterminés, qui visent haut, acceptent l\'effort et un peu d\'inconfort, et ne montrent jamais qu\'ils ont mal.',
    t: { vac: 0.95, det: 0.9, cmp: 0.9, vpo: 0.75, vhe: 0.25, inf: 0.75, ste: 0.3, loc: 0.1, emp: 0.35, vse: 0.35 } },
  { name: 'Les mocassins', by: 'Pieds · hérités des peuples d\'Amérique du Nord', tag: 'La classe, sans hausser le ton', color: '#6e4b2a',
    desc: 'Hérités des chaussures souples des peuples autochtones d\'Amérique du Nord, ils sont devenus le symbole d\'une élégance tranquille, celle des week-ends à la campagne et des conversations feutrées. C\'est le tempérament des diplomates bien élevés, attachés aux bonnes manières, qui n\'élèvent jamais la voix et gardent leurs positions sans faire de vagues.',
    t: { dip: 0.95, vtr: 0.8, vse: 0.8, ste: 0.85, cfl: 0.1, chg: 0.15, com: 0.15, vst: 0.2, vpo: 0.6, inf: 0.35 } },
  { name: 'Les Crocs', by: 'Pieds · lancées en 2002 pour les bateaux', tag: 'Pas jolies, et tellement heureuses', color: '#7fc242',
    desc: 'Lancées en 2002 comme chaussures de bateau, elles ont été moquées, bannies des tapis rouges, puis adorées. Elles ont des trous partout et s\'en fichent éperdument. C\'est le tempérament des joyeux sans complexes, qui assument leurs goûts, rient d\'eux-mêmes avant les autres et savent que le bonheur tient souvent à un peu de confort.',
    t: { vco: 0.05, vhe: 0.85, opt: 0.95, inc: 0.8, dog: 0.1, vpo: 0.05, epi: 0.1, rig: 0.2, inf: 0.75, soc: 0.8, thr: 0.1 } },
  { name: 'Les espadrilles', by: 'Pieds · semelle de corde, Pays basque', tag: 'La légèreté du Sud', color: '#d35400',
    desc: 'Fabriquées depuis plus d\'un siècle à Mauléon, au Pays basque, avec leur semelle de corde tressée, elles ont chaussé les paysans, les fêtes de village et les étés de la Riviera. C\'est le tempérament des simples et des légers, fidèles à leur coin de pays, qui vivent l\'instant, aiment les fêtes où tout le monde danse et n\'ont besoin de rien de plus.',
    t: { vtr: 0.75, opn: 0.7, tmp: 0.15, vhe: 0.8, vpo: 0.05, vac: 0.15, col: 0.8, rig: 0.2, san: 0.75, aff: 0.2 } },
  { name: 'Les sabots', by: 'Pieds · taillés dans un seul bloc de bois', tag: 'Lents, solides, les pieds sur terre', color: '#a0785a',
    desc: 'Taillés dans un seul morceau de bois, ils ont traversé les champs et les siècles sans se presser. Ils font du bruit, ne plient pas, et on les entend venir de loin. C\'est le tempérament des terriens obstinés, patients et pragmatiques, qui se méfient des beaux discours, avancent à leur rythme et ne lâchent jamais un travail commencé.',
    t: { vtr: 0.9, det: 0.9, opn: 0.9, epi: 0.1, vhe: 0.15, vst: 0.05, inf: 0.1, ste: 0.85, nat: 0.7, ouv: 0.2, dip: 0.3 } },
  { name: 'Le kimono', by: 'Tenue · des siècles de savoir-faire au Japon', tag: 'L\'harmonie dans chaque pli', color: '#b03a48',
    desc: 'Au Japon, il se plie, se noue et se porte selon des règles transmises depuis des siècles, où chaque motif et chaque couleur ont un sens. Rien n\'y est laissé au hasard, tout y respire le calme. C\'est le tempérament des esprits apaisés et exigeants, attachés à l\'harmonie, au respect et à la beauté des gestes bien faits.',
    t: { ste: 0.95, dip: 0.9, rig: 0.9, vtr: 0.85, sanc: 0.85, cfl: 0.05, com: 0.1, inf: 0.15, san: 0.9, vst: 0.2 } },
  { name: 'Le poncho', by: 'Manteau · venu des Andes', tag: 'Là où le vent le porte', color: '#c0763a',
    desc: 'Venu des Andes, il est d\'une simplicité désarmante : un grand carré de laine avec un trou pour la tête. Il a suivi les bergers, les voyageurs et les festivaliers sans jamais demander où l\'on allait. C\'est le tempérament des nomades libres, curieux de tout et de tous, qui se laissent porter par les rencontres et détestent qu\'on les enferme.',
    t: { vsd: 0.95, opn: 0.05, ouv: 0.95, vst: 0.9, vse: 0.1, ord: 0.1, vco: 0.15, lib: 0.9, loc: 0.75, tmp: 0.2 } },
  { name: 'La parka', by: 'Manteau · héritée des peuples de l\'Arctique', tag: 'Toujours en première ligne', color: '#556b2f',
    desc: 'Héritée des peuples de l\'Arctique, elle a été adoptée par les mods anglais, puis par des générations de lycéens en manif, capuche fourrée et poches pleines de tracts. C\'est le tempérament des engagés, qui ne supportent pas l\'injustice, rêvent de changer le monde et sont prêts à passer leur samedi dans le froid pour une cause qui les dépasse.',
    t: { eng: 0.95, vun: 0.95, fair: 0.9, epi: 0.8, chg: 0.85, cfl: 0.75, vpo: 0.05, vco: 0.2, col: 0.85, auth: 0.15 } },
  { name: 'Le ciré jaune', by: 'Manteau · du jaune pour être vu en mer', tag: 'Face à la tempête', color: '#e0b000',
    desc: 'Jaune vif pour être repéré au milieu des vagues, il a protégé des générations de marins pêcheurs avant de conquérir les plages bretonnes les jours de crachin. C\'est le tempérament des intrépides solides, qui gardent le cap par gros temps, aiment le goût du sel et de l\'effort, et comptent sur leur équipage autant qu\'il compte sur eux.',
    t: { aud: 0.9, san: 0.9, rsk: 0.85, det: 0.85, vst: 0.8, vhe: 0.2, col: 0.75, loy: 0.8, thr: 0.4, vse: 0.2, inf: 0.3 } },
  { name: 'La doudoune sans manches', by: 'Haut · l\'uniforme des start-up', tag: 'Toujours sur le prochain projet', color: '#1e3799',
    desc: 'On la croise dans les open spaces, les salons de la tech et les réunions où l\'on parle de révolution avant 9 heures. Elle garde le buste au chaud et les bras libres pour agir. C\'est le tempérament des entrepreneurs optimistes, qui croient au progrès, adorent les nouveaux projets et trouvent que la meilleure idée est toujours la prochaine.',
    t: { chg: 0.95, vis: 0.05, vac: 0.9, cmp: 0.8, vst: 0.85, vtr: 0.05, opt: 0.9, rsk: 0.8, loy: 0.3, sanc: 0.15 } },
  { name: 'Le polo', by: 'Haut · René Lacoste, 1933', tag: 'Gagner, mais avec élégance', color: '#1e8449',
    desc: 'René Lacoste, champion de tennis surnommé le Crocodile, l\'a imaginé pour jouer plus à l\'aise avant de le commercialiser en 1933, un petit reptile brodé sur la poitrine. C\'est le tempérament des compétiteurs fair-play, qui aiment gagner mais selon les règles, serrent la main à la fin du match et savent perdre avec le sourire.',
    t: { cmp: 0.85, fair: 0.9, vac: 0.8, dip: 0.8, rig: 0.7, soc: 0.7, cfl: 0.3, dog: 0.25, vtr: 0.6, emp: 0.6 } },
  { name: 'La chemise hawaïenne', by: 'Haut · Honolulu, années 1930', tag: 'Impossible de ne pas la voir', color: '#ff6f61',
    desc: 'Apparue à Honolulu dans les années 1930, couverte de fleurs, de palmiers et parfois de perroquets, elle transforme n\'importe quel repas de famille en soirée d\'été. C\'est le tempérament des extravertis joyeux, qui mettent l\'ambiance partout où ils passent, parlent fort, rient encore plus fort et se moquent bien du code vestimentaire.',
    t: { inf: 0.98, vhe: 0.9, vst: 0.85, con: 0.05, rig: 0.1, vco: 0.15, soc: 0.95, ste: 0.2, aff: 0.2, vig: 0.1 } },
  { name: 'La combinaison de ski', by: 'Tenue · du haut des pistes noires', tag: 'Toujours plus vite, toujours plus haut', color: '#e84393',
    desc: 'Fluo, ajustée et aérodynamique, elle ne connaît que les pistes noires et le hors-piste. Elle compte les descentes, jamais les chutes. C\'est le tempérament des amateurs de sensations fortes, qui aiment la vitesse, le vertige et la montée d\'adrénaline, et pour qui une journée sans frisson est une journée perdue.',
    t: { vst: 0.95, rsk: 0.95, aud: 0.95, vse: 0.1, vig: 0.15, thr: 0.2, san: 0.7, vhe: 0.8, cmp: 0.75, con: 0.2 } },
  { name: 'Le pyjama', by: 'Nuit · un mot venu d\'Inde', tag: 'La tête encore dans les rêves', color: '#8e9fcf',
    desc: 'Venu d\'Inde, où le mot désignait un pantalon ample, il a voyagé avec les Britanniques pour finir dans toutes les chambres. Il traîne volontiers jusqu\'à midi le dimanche. C\'est le tempérament des rêveurs, qui vivent un peu dans leur tête, imaginent mille mondes, n\'aiment pas qu\'on les presse et laissent le hasard décider de leur journée.',
    t: { ide: 0.9, vac: 0.05, cmp: 0.05, dom: 0.05, ord: 0.15, loc: 0.8, soc: 0.3, epi: 0.7, ste: 0.75, lea: 0.1 } },
  { name: 'Le peignoir', by: 'Nuit · moelleux, après le bain', tag: 'Prendre soin de soi, d\'abord', color: '#c9a9a6',
    desc: 'Moelleux, chaud et sans boutons, il ne sort qu\'après un bon bain et refuse toute urgence. Il connaît l\'importance des petits luxes et des moments pour soi. C\'est le tempérament des épicuriens autonomes, qui savent se faire plaisir sans culpabilité, protègent leur tranquillité et ne répondent pas aux messages pendant leur heure sacrée.',
    t: { vhe: 0.98, vsd: 0.85, ind: 0.75, san: 0.8, col: 0.15, eng: 0.05, cmp: 0.1, soc: 0.3, vbe: 0.35, fair: 0.4 } },
  { name: 'Le maillot de foot', by: 'Sport · floqué au nom de l\'idole', tag: 'Mon équipe, pour la vie', color: '#0055a4',
    desc: 'Floqué au nom de son joueur préféré, il se porte les soirs de match et parfois tous les autres jours. Il a pleuré des défaites, hurlé des victoires et ne changera jamais de couleurs. C\'est le tempérament des passionnés fidèles, qui vibrent en groupe, défendent les leurs contre vents et marées et vivent chaque émotion à fond.',
    t: { loy: 0.98, col: 0.9, com: 0.8, cmp: 0.9, aff: 0.05, inf: 0.85, san: 0.15, soc: 0.9, dip: 0.2, vun: 0.3 } },
  { name: 'La tenue de sport fluo', by: 'Sport · dehors dès 6 heures', tag: 'Deux séances avant le café', color: '#9acd32',
    desc: 'Visible à cent mètres, elle sort au lever du soleil et revient avec des chiffres : kilomètres, calories, records personnels. Elle ne rate jamais une séance. C\'est le tempérament des motivés disciplinés, qui croient qu\'on se construit par l\'effort, se fixent des objectifs à long terme et entraînent volontiers les autres dans leur élan.',
    t: { det: 0.95, vac: 0.9, opt: 0.9, ord: 0.85, loc: 0.05, tmp: 0.8, vhe: 0.25, inf: 0.75, ste: 0.2, vis: 0.15 } },
  { name: 'Les gants', by: 'Accessoire · une barrière élégante', tag: 'Une distance bien ajustée', color: '#4b3a33',
    desc: 'Ils protègent du froid, de la poussière et parfois des poignées de main trop franches. Autrefois, on les retirait pour saluer ; aujourd\'hui, ils gardent surtout leur quant-à-soi. C\'est le tempérament des réservés soigneux, un peu méfiants, qui aiment que les choses restent propres et à leur place, et n\'accordent leur proximité qu\'avec le temps.',
    t: { vig: 0.9, sanc: 0.9, nat: 0.75, soc: 0.2, att: 0.25, rig: 0.85, con: 0.85, inc: 0.15, thr: 0.7, inf: 0.15 } },
  { name: 'Les lunettes de soleil', by: 'Accessoire · modèle aviateur, 1937', tag: 'Rien ne transparaît', color: '#34495e',
    desc: 'Le modèle aviateur a été lancé en 1937 pour les pilotes américains, et il a gardé depuis cet air de ne jamais s\'émouvoir de rien. Derrière les verres fumés, impossible de savoir ce qui se passe. C\'est le tempérament des détachés très cool, qui gardent leurs émotions pour eux, vivent à leur rythme et ne s\'attachent pas facilement.',
    t: { san: 0.95, emp: 0.2, att: 0.1, care: 0.25, vhe: 0.75, vco: 0.25, aff: 0.8, thr: 0.1, vbe: 0.2, ind: 0.8 } },
  { name: 'La montre à gousset', by: 'Accessoire · transmise de génération en génération', tag: 'Chaque minute compte', color: '#b8860b',
    desc: 'Accrochée au gilet par une chaîne, elle se transmettait de génération en génération et se remontait chaque matin. Elle ne retarde jamais, et elle se souvient de tout. C\'est le tempérament des ponctuels nostalgiques, qui planifient loin, respectent l\'héritage et regrettent un peu l\'époque où l\'on prenait le temps de bien faire les choses.',
    t: { vtr: 0.95, rig: 0.9, con: 0.85, tmp: 0.95, ord: 0.95, chg: 0.05, vst: 0.1, vhe: 0.2, vis: 0.85, inc: 0.15 } },
  { name: 'La cape', by: 'Accessoire · celle des super-héros', tag: 'Voler au secours du monde', color: '#d62828',
    desc: 'Elle claque au vent sur les épaules des super-héros et de tous les enfants qui jouent à sauver le monde dans le jardin. Aucun intérêt pratique, un idéal immense. C\'est le tempérament des idéalistes courageux, qui croient qu\'une seule personne peut changer les choses, prennent la défense des plus faibles et se lancent sans calculer.',
    t: { ide: 0.95, fair: 0.95, care: 0.85, aud: 0.9, lea: 0.8, opt: 0.9, epi: 0.8, eng: 0.85, rsk: 0.8, vpo: 0.1, loc: 0.05, aff: 0.2 } },
];

window.PRISME_CLOTHES = { CLOTHES };
