/* ============================================================
   PRISME — « Si tu étais une couleur »
   ------------------------------------------------------------
   Pas ta couleur préférée : celle dont le caractère ressemble au tien.
   Vive ou discrète, chaude ou froide, qui s'impose ou qui accompagne,
   qui a traversé les siècles ou qui vient d'un accident de laboratoire.
   Des histoires vraies de pigments, de pierres et de mots.
     name = la couleur, by = famille · un usage ou une origine, tag = la phrase,
     color = LA couleur elle-même en hex (exacte, elle sert d'accent visuel),
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const COLORS = [
  { name: 'Le vermillon', by: 'Rouges · le pigment du cinabre', tag: 'Le rouge qui ne demande pas la permission', color: '#e34234',
    desc: 'Tiré à l\'origine du cinabre, un minerai de mercure, il fait briller les laques chinoises et les fresques de Pompéi depuis l\'Antiquité. Son nom vient du latin vermiculus, « petit ver ». C\'est le tempérament des fonceurs flamboyants, qui entrent dans une pièce comme on allume la lumière et préfèrent regretter d\'avoir osé que de n\'avoir rien tenté.',
    t: { aud: 0.92, inf: 0.9, vst: 0.9, rsk: 0.88, ste: 0.12, vig: 0.12, con: 0.15, chg: 0.8, vse: 0.15, aff: 0.2 } },
  { name: 'Le bordeaux', by: 'Rouges · le nom d\'un vin', tag: 'Profond, patient, qui se bonifie avec l\'âge', color: '#6d071a',
    desc: 'Il doit son nom au vin de la région bordelaise, et il en a gardé le caractère : grave, chaleureux, jamais criard. On le porte en velours, en cuir, en fauteuil de club. C\'est le tempérament des épicuriens posés, fidèles à leurs habitudes et à leurs amis, qui savent prendre le temps d\'un bon repas et se méfient un peu de tout ce qui est à la mode.',
    t: { vtr: 0.88, vhe: 0.85, san: 0.8, fia: 0.85, vst: 0.15, chg: 0.1, aud: 0.25, opn: 0.75, loy: 0.8, tmp: 0.75 } },
  { name: 'Le rouge pompier', by: 'Rouges · fait pour être vu de loin', tag: 'Le premier arrivé quand ça brûle', color: '#d2131a',
    desc: 'Il est fait pour être vu de loin et reconnu en une seconde, au milieu d\'une rue embouteillée comme d\'une cour pleine de fumée. Pas le temps de nuancer : il signale l\'urgence et le secours. C\'est le tempérament des courageux d\'équipe, qui foncent vers le problème quand les autres reculent, protègent les leurs sans discours et règlent la théorie une fois le feu éteint.',
    t: { aud: 0.9, cfl: 0.9, care: 0.88, san: 0.88, loy: 0.85, col: 0.85, epi: 0.08, dip: 0.2, tmp: 0.2, ide: 0.25 } },
  { name: 'Le carmin', by: 'Rouges · un insecte du Mexique', tag: 'Le charme, et un secret bien gardé', color: '#960018',
    desc: 'Il vient de la cochenille, un minuscule insecte des cactus que les Aztèques élevaient déjà et que les Espagnols ont rapporté en Europe au XVIe siècle, où il se vendait à prix d\'or. On le trouve encore dans les rouges à lèvres. C\'est le tempérament des séducteurs raffinés, qui savent plaire, aiment briller en société et n\'expliquent jamais tout à fait comment ils s\'y prennent.',
    t: { inf: 0.9, vhe: 0.85, vac: 0.8, vpo: 0.72, soc: 0.85, dip: 0.82, vun: 0.2, ste: 0.25, epi: 0.2, sanc: 0.2 } },
  { name: 'Le corail', by: 'Rouges · le bijou porte-bonheur', tag: 'Le soleil dans une pièce pleine de monde', color: '#ff7f50',
    desc: 'Entre le rose et l\'orange, il doit son nom au corail rouge de Méditerranée, qu\'on sculptait déjà en bijoux porte-bonheur. C\'est une couleur de vacances, de terrasse et de rires. C\'est le tempérament des chaleureux confiants, qui voient le bon côté des gens avant le reste, rassemblent autour d\'eux sans effort et trouvent que la vie est trop courte pour bouder.',
    t: { opt: 0.95, soc: 0.95, att: 0.85, vbe: 0.85, thr: 0.1, nat: 0.08, com: 0.2, dog: 0.1, vis: 0.1, inf: 0.85 } },
  { name: 'Le rose poudré', by: 'Roses · la poudre de riz', tag: 'La douceur qui arrondit les angles', color: '#e3b5b3',
    desc: 'Un rose adouci, comme passé à la poudre de riz, qui n\'agresse jamais le regard et se marie avec tout. Il ne cherche pas à gagner, il cherche à apaiser. C\'est le tempérament des tendres conciliants, qui détestent les éclats de voix, sentent tout de suite quand quelqu\'un va mal et préfèrent céder un point plutôt que d\'abîmer un lien.',
    t: { att: 0.92, dip: 0.9, cfl: 0.05, com: 0.08, dom: 0.08, aud: 0.2, care: 0.9, ste: 0.85, emp: 0.9, rsk: 0.15 } },
  { name: 'Le fuchsia', by: 'Roses · la fleur du botaniste Fuchs', tag: 'Impossible de passer inaperçu, et tant mieux', color: '#fd3f92',
    desc: 'Il doit son nom à une fleur, elle-même baptisée par le botaniste Charles Plumier en hommage à Leonhart Fuchs, savant allemand du XVIe siècle. Couleur de défilé, de scène et de rouge à lèvres audacieux. C\'est le tempérament des personnalités magnétiques, qui aiment la lumière, prennent la parole sans trembler et ne voient aucune raison de baisser le volume.',
    t: { inf: 0.97, soc: 0.9, dom: 0.8, vac: 0.8, vpo: 0.7, vco: 0.1, ste: 0.1, vse: 0.2, aff: 0.2, vst: 0.85, vtr: 0.15 } },
  { name: 'Le saumon', by: 'Roses · un poisson à contre-courant', tag: 'Il revient toujours là où il est né', color: '#fa8072',
    desc: 'Sa teinte vient de ce que le poisson mange : de petits crustacés riches en pigments. Et le saumon remonte les rivières à contre-courant, parfois sur des centaines de kilomètres, pour revenir frayer là où il est né. C\'est le tempérament des obstinés fidèles, attachés à leurs racines, qui ne lâchent jamais un objectif et savent toujours d\'où ils viennent.',
    t: { det: 0.95, opn: 0.92, vtr: 0.85, loy: 0.88, chg: 0.1, ouv: 0.25, vst: 0.2, inc: 0.25, att: 0.8, ide: 0.3 } },
  { name: 'L\'orange mandarine', by: 'Oranges · le fruit qui a nommé la couleur', tag: 'Du peps, tout de suite, maintenant', color: '#fea347',
    desc: 'En français, c\'est le fruit qui a donné son nom à la couleur, et pas l\'inverse : avant lui, on disait plutôt jaune-rouge. La mandarine en garde le zeste, l\'acidulé, la bonne humeur d\'un matin d\'hiver. C\'est le tempérament des spontanés pétillants, qui lancent des idées à la seconde, changent de programme sans drame et trouvent qu\'un planning est surtout une suggestion.',
    t: { vst: 0.9, ord: 0.05, opt: 0.92, rig: 0.12, tmp: 0.1, inc: 0.85, con: 0.1, vig: 0.15, aud: 0.75, vse: 0.2 } },
  { name: 'La terracotta', by: 'Oranges · la terre cuite', tag: 'La maison où l\'on reste dîner', color: '#e2725b',
    desc: 'Son nom italien veut dire « terre cuite » : l\'argile passée au four, que les oxydes de fer colorent en orange chaud. Tuiles, jarres, tomettes : c\'est la couleur des maisons du Sud et des tables où l\'on tient à plusieurs. C\'est le tempérament des hôtes généreux, attachés à leur famille et à leurs traditions, pour qui la réussite compte moins que le repas du dimanche.',
    t: { vbe: 0.97, att: 0.9, vtr: 0.8, soc: 0.8, vpo: 0.08, vac: 0.2, ste: 0.8, aud: 0.3, dom: 0.2, col: 0.8 } },
  { name: 'La rouille', by: 'Oranges · le fer qui a vécu', tag: 'Un peu grinçant, jamais cassé', color: '#985717',
    desc: 'C\'est ce que devient le fer après des années de pluie : une patine orangée et rugueuse, que certains architectes recherchent même exprès avec l\'acier Corten. Elle raconte le temps qui passe. C\'est le tempérament des indépendants désabusés, un brin râleurs, qui ont vu trop de promesses pour y croire d\'avance, mais qui tiennent debout quand le reste s\'écroule.',
    t: { vis: 0.92, nat: 0.85, opt: 0.1, com: 0.8, vco: 0.15, ind: 0.85, soc: 0.2, inf: 0.12, loc: 0.75, ide: 0.2 } },
  { name: 'Le jaune moutarde', by: 'Jaunes · la graine qui monte au nez', tag: 'Décalé, piquant, et fier de l\'être', color: '#d1a627',
    desc: 'Un jaune qui n\'a pas voulu être sage : un peu brun, un peu vert, très années soixante-dix. Il divise, et il adore ça. Comme la moutarde, il monte vite au nez. C\'est le tempérament des originaux au franc-parler, qui ont un avis sur tout, se méfient des conventions et préfèrent un désaccord honnête à un consensus mou.',
    t: { com: 0.92, cfl: 0.85, vco: 0.08, dip: 0.15, ind: 0.85, ouv: 0.85, ide: 0.8, lib: 0.88, ste: 0.2, auth: 0.15 } },
  { name: 'Le jaune citron', by: 'Jaunes · le zeste', tag: 'Acidulé, vif, sans filtre', color: '#f0d40e',
    desc: 'Le plus vif des jaunes, presque électrique, celui qui réveille un bureau gris et pique un peu les yeux. Il ne cherche pas la nuance, il cherche l\'énergie. C\'est le tempérament des optimistes pressés, qui avancent vite, disent tout haut ce qu\'ils pensent, ont horreur de la routine et trouvent que l\'avenir, franchement, s\'annonce plutôt bien.',
    t: { opt: 0.95, vis: 0.05, vst: 0.88, com: 0.8, dip: 0.25, ste: 0.1, inf: 0.85, thr: 0.1, vtr: 0.12, chg: 0.85 } },
  { name: 'L\'ocre', by: 'Jaunes · la première couleur des hommes', tag: 'Ancienne comme la première peinture', color: '#dfaf2c',
    desc: 'Une terre colorée par des oxydes de fer, que nos ancêtres broyaient déjà pour peindre les grottes de Lascaux, il y a quelque 17 000 ans. On l\'extrait encore dans le Luberon, à Roussillon. C\'est le tempérament des sages discrets et enracinés, qui aiment la nature et le temps long, parlent peu, se méfient des grandes théories et n\'ont aucun besoin de briller.',
    t: { vtr: 0.9, epi: 0.08, vpo: 0.05, inf: 0.08, ste: 0.9, vun: 0.88, soc: 0.22, vst: 0.15, tmp: 0.85, vac: 0.15 } },
  { name: 'Le doré', by: 'Jaunes · la feuille d\'or', tag: 'Né pour la première place', color: '#d4af37',
    desc: 'Il imite l\'or, le métal des couronnes, des médailles et des cadres de palais, qu\'on bat en feuilles plus fines qu\'un cheveu. Il ne s\'excuse pas de briller. C\'est le tempérament des ambitieux qui assument, qui aiment gagner, apprécient les belles choses et le confort qui va avec, et considèrent qu\'un succès discret est un succès à moitié gâché.',
    t: { vac: 0.97, vpo: 0.92, cmp: 0.92, vhe: 0.85, inf: 0.85, dom: 0.85, vun: 0.12, care: 0.2, vtr: 0.3, ste: 0.2 } },
  { name: 'Le vert sapin', by: 'Verts · la forêt en hiver', tag: 'Toujours là, même au plus froid', color: '#095228',
    desc: 'Le sapin garde ses aiguilles quand le reste de la forêt se dénude, et c\'est pour cela qu\'on en a fait l\'arbre de Noël. Son vert sombre ne change pas avec les saisons. C\'est le tempérament des piliers tranquilles, fiables, loyaux et protecteurs, qui n\'aiment ni les risques inutiles ni les grands discours, mais qu\'on trouve toujours là quand il fait froid.',
    t: { fia: 0.95, loy: 0.9, vbe: 0.88, vse: 0.88, ste: 0.88, inf: 0.1, vst: 0.12, rsk: 0.12, chg: 0.1, vhe: 0.25 } },
  { name: 'Le vert d\'eau', by: 'Verts · le reflet d\'une rivière', tag: 'Le calme plat, et c\'est voulu', color: '#9ed9b0',
    desc: 'Un vert pâle et laiteux, à mi-chemin du bleu, qu\'on retrouve dans les salles de bains d\'autrefois et les porcelaines anciennes. Il ne presse personne. C\'est le tempérament des sereins qui ne se disputent pas, qui laissent venir les choses, s\'accommodent de l\'imprévu et ne voient pas bien pourquoi il faudrait se battre pour arriver le premier.',
    t: { thr: 0.05, cmp: 0.05, vac: 0.1, dom: 0.05, cfl: 0.08, ste: 0.92, san: 0.88, inc: 0.8, soc: 0.3, det: 0.25 } },
  { name: 'Le kaki', by: 'Verts · la poussière, en persan', tag: 'Se fondre dans le décor et tenir la position', color: '#94812b',
    desc: 'Le mot vient du persan khâk, « poussière », passé par l\'hindoustani : l\'armée britannique l\'a adopté en Inde au milieu du XIXe siècle pour que ses soldats se fondent dans le paysage. C\'est le tempérament des pragmatiques disciplinés, fiables et loyaux, qui respectent la hiérarchie, ne perdent pas de temps en théories et font le travail sans chercher à être vus.',
    t: { ord: 0.92, con: 0.85, auth: 0.88, epi: 0.05, ide: 0.12, vhe: 0.12, inf: 0.1, fia: 0.9, loy: 0.88, lib: 0.25 } },
  { name: 'Le vert pomme', by: 'Verts · le fruit qu\'on croque', tag: 'La fraîcheur du premier jour', color: '#34c924',
    desc: 'Acidulé comme une pomme qu\'on croque, c\'est le vert de ce qui pousse et de ce qui commence, de la première feuille au printemps. Il n\'a pas encore appris à se méfier. C\'est le tempérament des curieux confiants, ouverts à tout, qui font confiance d\'abord, aiment la nature et les idées neuves, et n\'ont aucune envie d\'écraser qui que ce soit pour avancer.',
    t: { ouv: 0.92, nat: 0.05, vig: 0.1, opt: 0.88, vun: 0.85, dog: 0.05, cmp: 0.12, vpo: 0.08, opn: 0.1, att: 0.7 } },
  { name: 'L\'émeraude', by: 'Verts · la pierre et son jardin', tag: 'Précieuse, jusque dans ses défauts', color: '#50c878',
    desc: 'L\'émeraude est presque toujours parcourue de petites inclusions, que les joailliers appellent son « jardin » : une pierre sans défaut serait presque suspecte. On l\'aime avec. C\'est le tempérament des élégants sûrs d\'eux, ambitieux et indépendants, qui gardent leur sang-froid, cultivent leur singularité et n\'ont jamais cherché à ressembler à tout le monde.',
    t: { ind: 0.92, vsd: 0.92, vac: 0.82, san: 0.85, vco: 0.1, con: 0.2, vhe: 0.75, att: 0.3, col: 0.15, dog: 0.15 } },
  { name: 'Le vert olive', by: 'Verts · l\'arbre de la paix', tag: 'Le temps long et la main tendue', color: '#708d23',
    desc: 'L\'olivier peut vivre plus de mille ans, et son rameau est depuis l\'Antiquité un signe de paix. Son vert est grisé, doux, méditerranéen. C\'est le tempérament des médiateurs patients, qui désamorcent les conflits, pensent à long terme, savourent les plaisirs simples et n\'ont aucun goût pour la compétition ni pour les coups d\'éclat.',
    t: { dip: 0.95, cfl: 0.05, cmp: 0.08, tmp: 0.92, ste: 0.9, vhe: 0.72, vst: 0.15, aud: 0.15, eng: 0.15, dom: 0.12 } },
  { name: 'Le céladon', by: 'Verts · un berger amoureux', tag: 'Romantique jusqu\'au bout des rubans', color: '#83a697',
    desc: 'Il doit son nom à Céladon, le berger de L\'Astrée, grand roman d\'Honoré d\'Urfé au début du XVIIe siècle, que l\'on habillait de rubans vert pâle et qui aimait sa bergère avec une fidélité à toute épreuve. C\'est le tempérament des idéalistes au cœur tendre, qui croient au grand amour, restent fidèles quoi qu\'il arrive et n\'ont aucune envie de jouer des coudes.',
    t: { ide: 0.95, att: 0.95, aff: 0.05, loy: 0.9, vac: 0.1, dom: 0.08, cmp: 0.05, com: 0.15, sanc: 0.75, epi: 0.7 } },
  { name: 'Le bleu marine', by: 'Bleus · l\'uniforme des marins', tag: 'Carré, sobre, et on peut compter dessus', color: '#03224c',
    desc: 'Le bleu foncé des uniformes de marine, adopté par la Royal Navy au milieu du XVIIIe siècle avant de gagner les flottes du monde entier, puis les blazers et les cabans. Il ne se démode jamais. C\'est le tempérament des structurés fiables, qui aiment les règles claires, respectent l\'autorité, tiennent parole et considèrent l\'improvisation comme un manque de préparation.',
    t: { con: 0.92, ord: 0.95, auth: 0.85, vco: 0.9, vst: 0.08, inf: 0.2, lib: 0.2, chg: 0.1, fia: 0.9, inc: 0.1 } },
  { name: 'Le bleu de Klein', by: 'Bleus · Yves Klein, 1960', tag: 'Une seule couleur, mais absolue', color: '#002fa7',
    desc: 'Yves Klein a mis au point avec le marchand de couleurs Édouard Adam un liant qui garde au pigment outremer tout son éclat, et a déposé la formule en 1960 sous le nom d\'International Klein Blue. Puis il a peint des toiles entières de ce seul bleu. C\'est le tempérament des visionnaires radicaux, indépendants jusqu\'à l\'obsession, qui vont au bout d\'une idée et se fichent de ce qu\'on en pense.',
    t: { ide: 0.95, ind: 0.95, aud: 0.88, epi: 0.9, dog: 0.75, vco: 0.05, vse: 0.1, chg: 0.9, dip: 0.15, col: 0.1 } },
  { name: 'Le turquoise', by: 'Bleus · la pierre venue par la Turquie', tag: 'Le billet d\'avion toujours dans la poche', color: '#30d5c8',
    desc: 'La pierre turquoise tient son nom de la route qu\'elle suivait : extraite en Perse, elle arrivait en Europe par la Turquie. Sa couleur est celle des lagons et des cartes postales lointaines. C\'est le tempérament des voyageurs curieux, ouverts au monde, qui supportent très bien l\'imprévu, s\'ennuient vite chez eux et partent toujours avec plus de questions que de bagages.',
    t: { opn: 0.02, ouv: 0.95, vst: 0.92, vtr: 0.1, inc: 0.9, thr: 0.12, rsk: 0.78, ord: 0.25, vse: 0.12, vsd: 0.85 } },
  { name: 'Le bleu ciel', by: 'Bleus · un après-midi sans nuage', tag: 'La confiance, et pas un nuage', color: '#77b5fe',
    desc: 'Le bleu d\'un après-midi dégagé, celui des chambres d\'enfants et des horizons qui ne cachent rien. Il ne soupçonne personne. C\'est le tempérament des bienveillants sereins, qui font confiance sans arrière-pensée, voient l\'avenir d\'un bon œil, détestent les disputes et prennent soin des autres avec une simplicité désarmante.',
    t: { opt: 0.92, nat: 0.03, thr: 0.05, care: 0.88, com: 0.1, cfl: 0.1, vis: 0.05, dog: 0.1, dom: 0.1, vbe: 0.88, soc: 0.75 } },
  { name: 'Le bleu canard', by: 'Bleus · les reflets du colvert', tag: 'Ni tout à fait bleu, ni tout à fait vert', color: '#048b9a',
    desc: 'Il imite les reflets chatoyants qui brillent sur les plumes du canard colvert, et personne n\'arrive à décider s\'il est bleu ou vert. C\'est précisément son charme. C\'est le tempérament des esprits nuancés, indépendants et diplomates, qui voient toujours les deux côtés d\'une question, se méfient des certitudes toutes faites et laissent volontiers les autres trancher.',
    t: { inc: 0.92, dog: 0.05, epi: 0.12, dip: 0.82, ind: 0.8, ouv: 0.85, auth: 0.2, cfl: 0.2, dom: 0.15, eng: 0.15 } },
  { name: 'L\'indigo', by: 'Bleus · la plante venue d\'Inde', tag: 'Profond comme une nuit sans lune', color: '#4b0082',
    desc: 'Son nom vient de l\'Inde, d\'où arrivait la plante qui le donne, l\'indigotier ; c\'est lui qui teint le jean. Newton l\'a glissé entre le bleu et le violet pour que l\'arc-en-ciel compte sept couleurs, comme la gamme compte sept notes. C\'est le tempérament des introspectifs profonds, solitaires et intuitifs, attirés par le sens caché des choses.',
    t: { sanc: 0.88, ide: 0.85, soc: 0.08, inf: 0.08, vpo: 0.1, aff: 0.3, ind: 0.85, tmp: 0.8, vac: 0.15, vhe: 0.25 } },
  { name: 'Le bleu de Prusse', by: 'Bleus · Berlin, vers 1706', tag: 'L\'accident de labo qui a changé la peinture', color: '#003153',
    desc: 'Découvert par hasard à Berlin vers 1706 par un fabricant de couleurs, Diesbach, c\'est l\'un des tout premiers pigments de synthèse. Hokusai l\'a utilisé pour sa Grande Vague, et les ingénieurs pour leurs plans, les fameux « bleus ». C\'est le tempérament des esprits méthodiques et un peu froids, qui raisonnent avant de ressentir, aiment la précision et font de leurs erreurs des découvertes.',
    t: { aff: 0.95, rig: 0.9, att: 0.15, emp: 0.2, soc: 0.15, ouv: 0.82, con: 0.82, vhe: 0.2, sanc: 0.1, inf: 0.1 } },
  { name: 'Le cyan', by: 'Bleus · une encre sur trois', tag: 'Rien sans les autres, tout avec eux', color: '#00b7eb',
    desc: 'Avec le magenta et le jaune, il fait partie des trois encres de base des imprimantes : seul, il ne dit pas grand-chose, mais ensemble ils reproduisent presque toutes les couleurs. Son nom vient du grec kyanos, « bleu sombre ». C\'est le tempérament des coéquipiers modernes et fiables, qui préfèrent la réussite collective aux exploits en solo et misent sur l\'avenir plutôt que sur la nostalgie.',
    t: { col: 0.92, chg: 0.78, vtr: 0.08, cmp: 0.12, dom: 0.2, fia: 0.85, vis: 0.08, ind: 0.15, opn: 0.15, vpo: 0.12 } },
  { name: 'La lavande', by: 'Violets · les champs de Provence', tag: 'Tout est propre, tout est calme', color: '#9683ec',
    desc: 'Son nom viendrait du latin lavare, « laver », parce qu\'on parfumait le linge et les bains avec ses fleurs. Elle sent l\'armoire bien rangée et l\'été en Provence. C\'est le tempérament des bienveillants ordonnés, qui prennent soin des leurs, aiment que chaque chose soit à sa place, fuient les disputes et les paris risqués et trouvent le bonheur dans les rituels du quotidien.',
    t: { care: 0.9, ord: 0.88, vse: 0.88, vtr: 0.75, cfl: 0.1, vst: 0.12, aud: 0.12, rsk: 0.08, vbe: 0.9, con: 0.8 } },
  { name: 'La prune', by: 'Violets · le fruit de fin d\'été', tag: 'Du caractère sous la peau douce', color: '#811453',
    desc: 'Un violet sombre et velouté, celui du fruit à la fin de l\'été, juste avant qu\'il ne tombe. Gourmand, un peu mélancolique, jamais fade. C\'est le tempérament des indépendants au caractère bien trempé, qui savent savourer la vie sans se faire d\'illusions, disent les choses franchement et n\'ont que faire des conventions et des sourires de façade.',
    t: { vhe: 0.9, vis: 0.78, opt: 0.2, soc: 0.3, ind: 0.85, com: 0.82, vco: 0.12, dip: 0.2, sanc: 0.15, tmp: 0.2 } },
  { name: 'Le lilas', by: 'Violets · la fleur de quinze jours', tag: 'Sensible, rêveur, à fleur de peau', color: '#b666d2',
    desc: 'Le lilas fleurit à peine deux ou trois semaines par an, et son parfum suffit à faire revenir un printemps d\'enfance. Sa couleur est tendre, légèrement mélancolique. C\'est le tempérament des sensibles idéalistes, qui ressentent tout plus fort que les autres, s\'inquiètent vite, rêvent beaucoup et vivent au rythme de leurs émotions plutôt que de leurs calculs.',
    t: { emp: 0.95, thr: 0.8, san: 0.1, ide: 0.88, aff: 0.05, dom: 0.05, cmp: 0.05, inc: 0.2, ord: 0.25, loc: 0.75 } },
  { name: 'Le violet améthyste', by: 'Violets · la pierre qui garde sobre', tag: 'La maîtrise de soi faite pierre', color: '#884da7',
    desc: 'Son nom grec, amethystos, veut dire « qui n\'est pas ivre » : on croyait qu\'elle protégeait de l\'ivresse. Les évêques la portent encore en bague. C\'est le tempérament des sages exigeants, attachés à leurs principes et à une forme de spiritualité, qui gardent la tête froide, se tiennent loin des excès et trouvent dans la discipline une vraie liberté.',
    t: { vhe: 0.03, sanc: 0.92, san: 0.88, rig: 0.8, vtr: 0.75, vst: 0.1, dog: 0.7, inf: 0.15, loc: 0.1, inc: 0.2 } },
  { name: 'Le pourpre', by: 'Violets · le murex de Tyr', tag: 'Réservé aux empereurs', color: '#66023c',
    desc: 'La pourpre de Tyr s\'obtenait à partir de coquillages, les murex : il en fallait des milliers pour teindre un seul manteau, si bien qu\'à Rome elle devint le signe des empereurs. C\'est le tempérament des chefs de lignée, qui ont le goût du commandement, du rang et des traditions, attendent qu\'on respecte la hiérarchie et ne partagent pas volontiers leur trône.',
    t: { vpo: 0.97, auth: 0.95, dom: 0.92, lea: 0.9, vtr: 0.85, fair: 0.15, care: 0.2, vun: 0.1, col: 0.2, lib: 0.2 } },
  { name: 'Le vert fluo', by: 'Verts · gilets de chantier et surligneurs', tag: 'Impossible à ignorer, même de nuit', color: '#39ff14',
    desc: 'Les pigments fluorescents transforment une partie de la lumière invisible en lumière visible : c\'est pour cela qu\'ils semblent briller plus fort que la réalité. Gilets de chantier, surligneurs, années quatre-vingt-dix. C\'est le tempérament des électrons libres, qui carburent à la nouveauté, prennent des risques pour le frisson, envoient promener les règles et vivent franchement dans l\'instant.',
    t: { vst: 0.98, vco: 0.02, vtr: 0.02, con: 0.05, ord: 0.05, rsk: 0.95, san: 0.15, tmp: 0.05, lib: 0.95, vhe: 0.9 } },
  { name: 'Le noir', by: 'Neutres · toute la lumière absorbée', tag: 'Le mystère, et le dernier mot', color: '#0b0b0b',
    desc: 'Le noir absorbe presque toute la lumière qu\'il reçoit et n\'en renvoie rien. Couleur de la petite robe de Chanel en 1926, de la nuit, du deuil et des rebelles. C\'est le tempérament des solitaires assurés, peu démonstratifs, un brin méfiants, qui gardent leurs émotions pour eux, tiennent tête sans hausser le ton et n\'ont besoin de personne pour savoir qui ils sont.',
    t: { ind: 0.95, soc: 0.08, inf: 0.05, att: 0.15, dom: 0.78, san: 0.88, opt: 0.25, nat: 0.85, vbe: 0.25, cmp: 0.72 } },
  { name: 'Le blanc', by: 'Neutres · la page blanche', tag: 'Tout recommencer, et que ce soit parfait', color: '#ece8df',
    desc: 'La lumière blanche contient toutes les couleurs à la fois, comme Newton l\'a montré avec un prisme. C\'est la couleur des robes de mariée, des blouses et des pages qui attendent leur premier mot. C\'est le tempérament des idéalistes exigeants, qui aiment que tout soit net et en ordre, tiennent à leurs principes, supportent mal le flou et rêvent toujours d\'un nouveau départ.',
    t: { sanc: 0.92, rig: 0.88, con: 0.9, ord: 0.9, inc: 0.08, dog: 0.75, ide: 0.85, vhe: 0.2, fair: 0.85, loc: 0.2 } },
  { name: 'Le gris anthracite', by: 'Neutres · le charbon le plus dur', tag: 'Pas de fioritures, que du solide', color: '#303030',
    desc: 'Il doit son nom à l\'anthracite, le plus ancien et le plus dur des charbons, qui brûle longtemps et presque sans fumée. Façades, costumes, ordinateurs : c\'est le gris des choses sérieuses. C\'est le tempérament des réalistes solides, qui se méfient des beaux discours, ne s\'emballent jamais, font le travail sans fioritures et ne cherchent ni la gloire ni le pouvoir.',
    t: { epi: 0.03, ide: 0.08, vhe: 0.12, inf: 0.05, opt: 0.3, san: 0.9, fia: 0.9, vpo: 0.12, vst: 0.12, det: 0.85, eng: 0.1 } },
  { name: 'Le gris perle', by: 'Neutres · la nacre patiente', tag: 'L\'art de la nuance', color: '#cecece',
    desc: 'La perle naît quand l\'huître enrobe un corps étranger qui l\'irrite de fines couches de nacre, patiemment, jusqu\'à en faire quelque chose de beau. Son gris est doux, lumineux, jamais tranché. C\'est le tempérament des diplomates justes, qui transforment les tensions en compromis, écoutent tous les avis, se méfient des certitudes et font passer l\'équité avant la victoire.',
    t: { dip: 0.95, fair: 0.92, cfl: 0.1, com: 0.12, inc: 0.8, dog: 0.05, dom: 0.15, san: 0.85, cmp: 0.1, vun: 0.82 } },
  { name: 'Le beige', by: 'Neutres · la laine non teinte', tag: 'Pas de vagues, et c\'est très bien', color: '#c8ad7f',
    desc: 'À l\'origine, le beige désignait la laine laissée dans sa couleur naturelle, sans teinture ni blanchiment. Il va avec tout, ne choque personne et ne passe jamais de mode, faute d\'en avoir jamais été. C\'est le tempérament des amateurs de tranquillité, qui aiment leurs habitudes, fuient les risques, ne cherchent ni à briller ni à dominer et trouvent que la sécurité vaut bien un peu de routine.',
    t: { vco: 0.92, vse: 0.92, vst: 0.03, aud: 0.05, rsk: 0.05, chg: 0.05, com: 0.1, ste: 0.9, inf: 0.12, vpo: 0.08, ide: 0.2 } },
  { name: 'Le crème', by: 'Neutres · le lait entier', tag: 'Doux comme un dimanche matin', color: '#ede0bf',
    desc: 'Un blanc réchauffé, couleur de lait entier, de linge ancien et de pâtisserie. Il ne heurte rien et adoucit tout ce qu\'on pose à côté. C\'est le tempérament des cocons bienveillants, qui aiment le confort, les petits plaisirs et les gens qu\'ils aiment, détestent la compétition et les éclats, et font passer la chaleur humaine bien avant l\'efficacité.',
    t: { vhe: 0.85, att: 0.92, vbe: 0.9, cmp: 0.05, com: 0.1, vac: 0.1, rig: 0.2, aff: 0.1, ste: 0.85, lea: 0.15 } },
  { name: 'Le taupe', by: 'Neutres · le pelage d\'un terrassier', tag: 'Discret, patient, et il creuse', color: '#463f32',
    desc: 'Il imite le pelage gris-brun de la taupe, petite terrassière qui creuse des dizaines de mètres de galeries sans jamais se montrer. Un gris chaud, qu\'on remarque à peine et qu\'on finit par trouver partout. C\'est le tempérament des obstinés discrets, peu bavards, un peu méfiants, qui travaillent dans l\'ombre, observent tout et n\'ont aucune envie qu\'on les mette en avant.',
    t: { soc: 0.05, inf: 0.03, vpo: 0.05, det: 0.88, ste: 0.85, vig: 0.85, nat: 0.8, lea: 0.1, ind: 0.8, thr: 0.75 } },
  { name: 'Le marron chocolat', by: 'Neutres · la fève de cacao', tag: 'Gourmand, généreux, jamais au régime', color: '#5a3a22',
    desc: 'Le brun profond de la fève de cacao grillée, que les Mayas et les Aztèques buvaient bien avant qu\'elle ne traverse l\'Atlantique. Couleur de gâteau partagé et de fauteuil où l\'on s\'enfonce. C\'est le tempérament des bons vivants chaleureux, qui aiment les tablées, les rires et le plaisir tout de suite, et laissent volontiers la rigueur et les plans à plus tard.',
    t: { vhe: 0.97, soc: 0.88, inf: 0.8, tmp: 0.05, rig: 0.1, ord: 0.12, vig: 0.15, vac: 0.2, att: 0.85, con: 0.1 } },
  { name: 'Le sépia', by: 'Neutres · l\'encre de seiche', tag: 'Tout était mieux dans l\'album photo', color: '#704214',
    desc: 'Son nom est celui de la seiche en latin, dont on tirait l\'encre ; il est resté attaché aux photographies anciennes, virées au brun pour mieux se conserver. C\'est la couleur des souvenirs. C\'est le tempérament des nostalgiques attachés au passé et à leurs racines, un peu sceptiques sur l\'époque, qui gardent les albums et racontent volontiers comment c\'était avant.',
    t: { vtr: 0.95, vis: 0.9, chg: 0.03, vst: 0.1, opn: 0.85, att: 0.82, opt: 0.25, ouv: 0.25, tmp: 0.3, lib: 0.3 } },
  { name: 'L\'argent', by: 'Métaux · le miroir et la lune', tag: 'Il reflète, s\'adapte et garde son éclat', color: '#a9abb0',
    desc: 'L\'argent est le métal qui réfléchit le mieux la lumière, et c\'est lui qu\'on déposait au dos des miroirs. On l\'associe à la lune, au froid, à l\'élégance. C\'est le tempérament des esprits vifs et adaptables, qui renvoient à chacun ce qu\'il attend, gardent la tête froide, aiment le changement et ne s\'attachent jamais tout à fait à un camp.',
    t: { inc: 0.88, chg: 0.82, vtr: 0.12, att: 0.2, aff: 0.88, san: 0.85, dip: 0.78, loy: 0.12, ouv: 0.8, cmp: 0.7 } },
  { name: 'Le cuivre', by: 'Métaux · le fil et la statue', tag: 'Il fait passer le courant entre les gens', color: '#b87333',
    desc: 'Le cuivre conduit l\'électricité mieux que presque tout autre métal, et c\'est de lui qu\'est faite la statue de la Liberté, devenue verte avec le temps. Chaleureux, rougeoyant, il relie. C\'est le tempérament des connecteurs généreux, qui mettent les gens en relation, préfèrent le collectif à la compétition et défendent la liberté et la justice pour tous.',
    t: { soc: 0.92, col: 0.88, vun: 0.9, lib: 0.88, eng: 0.8, inf: 0.8, cmp: 0.1, vpo: 0.1, ind: 0.2, auth: 0.15 } },
  { name: 'Le bronze', by: 'Métaux · la troisième marche', tag: 'Heureux d\'être sur le podium', color: '#cd7f32',
    desc: 'Alliage de cuivre et d\'étain, il a donné son nom à tout un âge de l\'humanité. Et une étude célèbre l\'a montré : sur un podium, les médaillés de bronze ont souvent l\'air plus heureux que ceux d\'argent, contents d\'y être plutôt que déçus d\'avoir raté l\'or. C\'est le tempérament des persévérants contents de leur sort, solides, optimistes et peu obsédés par le rang.',
    t: { opt: 0.92, vpo: 0.05, vac: 0.3, cmp: 0.2, det: 0.88, fia: 0.85, vis: 0.1, dog: 0.15, loc: 0.2, thr: 0.12 } }
];

window.PRISME_COLORS = { COLORS };
