/* ============================================================
   PRISME — « Si tu étais un pays »
   ------------------------------------------------------------
   Ni ses habitants, ni son gouvernement : le tempérament que le
   pays renvoie — son rapport au temps, à la règle, à l'accueil,
   à la fête, au travail — tel qu'on le raconte avec affection
   quand on en revient, avec ses paysages et ses traditions.
     name = le pays, by = continent · un trait marquant, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const COUNTRIES = [
  { name: 'La France', by: 'Europe · l\'Hexagone', tag: 'Râler, puis passer à table', color: '#2b4c9b',
    desc: 'Elle débat de tout, de la cuisson d\'un œuf à la meilleure façon de refaire le monde, et considère la contestation comme une forme de conversation. Mais le débat finit toujours à table, avec du pain, du fromage et trois heures devant soi. Un pays qui aime les idées autant que les plaisirs, et qui ne voit pas pourquoi il faudrait choisir.',
    t: { com: 0.92, cfl: 0.85, epi: 0.8, vhe: 0.88, fair: 0.85, vco: 0.2, ste: 0.25, vis: 0.78, dip: 0.3, ide: 0.8, soc: 0.7 } },
  { name: 'La Belgique', by: 'Europe · le surréalisme', tag: 'Ceci n\'est pas un pays', color: '#f2c318',
    desc: 'Elle a donné au monde Magritte, Tintin, les frites et une capacité rare à ne pas se prendre au sérieux. Trois langues, des compromis à n\'en plus finir, et au bout du compte une bière pour tout le monde. Un tempérament qui préfère l\'autodérision au grand discours et l\'arrangement à la bagarre.',
    t: { ide: 0.9, dog: 0.08, vhe: 0.9, soc: 0.88, dom: 0.15, cfl: 0.15, dip: 0.92, vpo: 0.08, inc: 0.85, epi: 0.15, att: 0.8 } },
  { name: 'La Suisse', by: 'Europe · les horlogers', tag: 'Tout arrive à l\'heure', color: '#d52b1e',
    desc: 'Les trains partent à la seconde près, les montres sont réglées au dixième et les décisions se prennent par votation, après mûre réflexion. On ne s\'y dispute pas : on cherche un consensus, puis on range tout soigneusement. Un pays qui a fait de la précision et de la prudence un art de vivre, entre deux sommets enneigés.',
    t: { rig: 0.96, con: 0.95, ord: 0.95, cfl: 0.08, dip: 0.9, vse: 0.95, rsk: 0.12, vst: 0.18, fia: 0.95, tmp: 0.9, inf: 0.25 } },
  { name: 'Le Québec', by: 'Amérique du Nord · la Belle Province', tag: 'L\'hiver dehors, la chaleur dedans', color: '#1f5fae',
    desc: 'Six mois de neige n\'ont jamais entamé sa bonne humeur : on se retrouve à la cabane à sucre, on chante, on se tutoie tout de suite. Il tient à sa langue comme à un trésor de famille et accueille pourtant tout le monde à bras ouverts. Un tempérament chaleureux, fidèle à ses racines, qui ne cherche jamais la chicane.',
    t: { att: 0.95, soc: 0.9, opt: 0.88, dom: 0.2, cfl: 0.12, loy: 0.9, vtr: 0.75, vhe: 0.8, nat: 0.15, cmp: 0.2, vpo: 0.15 } },
  { name: 'Le Canada', by: 'Amérique du Nord · les grands espaces', tag: 'Pardon, après vous', color: '#c8102e',
    desc: 'Il s\'excuse quand on lui marche sur le pied, fait de la place à tout le monde et garde un calme de lac gelé. Ses forêts sont immenses, ses villes accueillent le monde entier, et il déteste se mettre en avant. Un pays posé, courtois, qui préfère rendre service plutôt que gagner la dispute.',
    t: { dip: 0.95, vun: 0.9, opn: 0.08, com: 0.12, care: 0.9, nat: 0.12, cmp: 0.15, san: 0.88, vpo: 0.12, inf: 0.35, fair: 0.88 } },
  { name: 'L\'Italie', by: 'Europe · la dolce vita', tag: 'La beauté comme évidence', color: '#009246',
    desc: 'Elle parle avec les mains, cuisine pour douze, et possède à peu près la moitié des chefs-d\'œuvre du monde sans en faire une montagne. L\'horaire est une suggestion, mais la sauce tomate de la nonna, elle, est sacrée. Un tempérament expressif, familial, qui fait passer la beauté et le plaisir avant l\'organisation.',
    t: { inf: 0.95, vhe: 0.95, att: 0.9, vbe: 0.92, ord: 0.15, ide: 0.9, con: 0.2, aff: 0.12, loy: 0.85, vse: 0.35 } },
  { name: 'L\'Espagne', by: 'Europe · la fiesta', tag: 'La nuit commence à minuit', color: '#c60b1e',
    desc: 'On y dîne à vingt-deux heures, on sort à minuit, on danse jusqu\'à l\'aube et on trouve encore l\'énergie de la sieste. Le flamenco dit tout ce qu\'il y a à dire sur son rapport aux émotions : intense, fier, sans demi-mesure. Un pays qui vit au présent, sur la place du village, entouré de tout le monde.',
    t: { vhe: 0.92, soc: 0.95, vst: 0.85, tmp: 0.08, ord: 0.18, aff: 0.1, inf: 0.9, vse: 0.3, rig: 0.25, com: 0.75 } },
  { name: 'Le Portugal', by: 'Europe · la saudade', tag: 'La mélancolie qui fait du bien', color: '#006600',
    desc: 'Il a regardé l\'océan si longtemps qu\'il a fini par le traverser, puis il est rentré chanter le fado. Sa douceur est discrète, jamais tapageuse : un pastel de nata, des azulejos, et cette saudade, nostalgie tendre de ce qui n\'est plus. Un tempérament humble, accueillant, qui ne hausse jamais le ton.',
    t: { ste: 0.9, att: 0.9, vtr: 0.9, vis: 0.78, dom: 0.1, cfl: 0.08, emp: 0.88, vpo: 0.08, ouv: 0.8, inf: 0.3, vac: 0.3 } },
  { name: 'L\'Allemagne', by: 'Europe · l\'ingénierie', tag: 'Ordnung muss sein', color: '#1a1a1a',
    desc: 'Ici, chaque chose a sa place et chaque place a son usage, du tri des déchets en cinq bacs à l\'horaire du dimanche calme. Le sérieux n\'empêche pas la fête — les brasseries en témoignent — mais la fête aussi est bien organisée. Un pays qui fait les choses correctement, pour longtemps, et qui s\'y tient.',
    t: { rig: 0.95, ord: 0.96, con: 0.9, fia: 0.95, tmp: 0.9, vco: 0.85, inc: 0.15, aff: 0.85, vun: 0.8, inf: 0.3, vst: 0.3 } },
  { name: 'Le Royaume-Uni', by: 'Europe · l\'île du flegme', tag: 'Keep calm, et une tasse de thé', color: '#012169',
    desc: 'Quoi qu\'il arrive, il fait la queue, s\'excuse, et commente la météo avec un humour si sec qu\'on ne sait jamais s\'il plaisante. Il adore ses traditions, ses rituels et ses excentriques, et ne montre ses émotions qu\'avec parcimonie. Un tempérament imperturbable, poli, qui cache beaucoup de tendresse sous l\'ironie.',
    t: { san: 0.97, fair: 0.9, vco: 0.85, inf: 0.2, aff: 0.8, vtr: 0.9, cfl: 0.15, dip: 0.88, auth: 0.75, vst: 0.35 } },
  { name: 'L\'Irlande', by: 'Europe · l\'île verte', tag: 'Une histoire de plus au pub', color: '#169b62',
    desc: 'Il pleut, il vente, et c\'est précisément pour ça qu\'on se retrouve au pub à chanter, raconter des histoires et refaire l\'histoire. Elle a produit plus de poètes par habitant que de raison, et garde un attachement farouche aux siens. Un tempérament conteur, chaleureux, qui se relève de tout avec le sourire.',
    t: { soc: 0.95, att: 0.9, opt: 0.85, loy: 0.92, ide: 0.88, rig: 0.2, vac: 0.2, inf: 0.9, nat: 0.2, con: 0.2, vhe: 0.8 } },
  { name: 'Les Pays-Bas', by: 'Europe · les polders', tag: 'Je te le dis franchement', color: '#ff7f00',
    desc: 'Ils ont gagné leur pays sur la mer, ce qui leur a donné un solide sens pratique et aucune patience pour les détours. Ils disent ce qu\'ils pensent, sans fioritures, puis repartent à vélo sous la pluie. Un tempérament direct, tolérant, pragmatique, qui préfère une solution qui marche à une belle théorie.',
    t: { com: 0.95, epi: 0.08, lib: 0.92, vco: 0.25, dip: 0.2, cfl: 0.8, sanc: 0.1, aff: 0.85, vac: 0.8, ide: 0.7, dog: 0.15 } },
  { name: 'La Suède', by: 'Europe · le lagom', tag: 'Ni trop, ni trop peu', color: '#006aa7',
    desc: 'Le lagom, c\'est la juste mesure : ni excès, ni manque, ni personne au-dessus des autres. On y fait des pauses fika, on décide en groupe, et l\'on déteste se vanter. Un pays égalitaire, calme, soucieux de la nature, qui préfère l\'harmonie collective aux coups d\'éclat individuels.',
    t: { cfl: 0.05, col: 0.85, fair: 0.95, vun: 0.92, vpo: 0.05, inf: 0.2, dom: 0.1, ste: 0.9, vis: 0.15, vhe: 0.6, vst: 0.3 } },
  { name: 'La Norvège', by: 'Europe · les fjords', tag: 'Il n\'y a pas de mauvais temps', color: '#ba0c2f',
    desc: '« Il n\'y a pas de mauvais temps, seulement de mauvais vêtements » : voilà toute sa philosophie. Elle part en randonnée par moins quinze, dort en cabane sans électricité, et trouve ça reposant. Un tempérament endurant, sobre, amoureux des grands espaces, qui n\'éprouve aucun besoin d\'en mettre plein la vue.',
    t: { vun: 0.95, ind: 0.85, soc: 0.3, vhe: 0.25, det: 0.9, vpo: 0.08, vac: 0.2, rsk: 0.65, tmp: 0.9, ste: 0.85, vst: 0.6 } },
  { name: 'Le Danemark', by: 'Europe · le hygge', tag: 'Des bougies et un plaid', color: '#c60c30',
    desc: 'Il a inventé un mot, hygge, pour ce moment où l\'on est bien au chaud avec les siens, bougies allumées et café sur la table. Il laisse les vélos sans cadenas, fait confiance à ses voisins et se déclare régulièrement le pays le plus heureux du monde. Un tempérament douillet, confiant, qui a fait du bien-être une priorité.',
    t: { vhe: 0.9, vbe: 0.95, att: 0.9, nat: 0.05, thr: 0.08, vse: 0.85, vst: 0.2, opt: 0.9, vpo: 0.1, rsk: 0.3, vac: 0.3 } },
  { name: 'La Finlande', by: 'Europe · le sisu', tag: 'Le silence n\'est pas gênant', color: '#003580',
    desc: 'Deux Finlandais peuvent partager un sauna pendant une heure sans échanger un mot, et en ressortir meilleurs amis. Elle a le sisu : cette ténacité tranquille qui fait tenir sous la neige, dans le noir, sans se plaindre. Un tempérament introverti, solide, fiable, qui laisse les actes parler à sa place.',
    t: { soc: 0.1, inf: 0.05, det: 0.97, san: 0.95, fia: 0.9, ind: 0.85, vhe: 0.4, com: 0.3, att: 0.4, dom: 0.3 } },
  { name: 'L\'Islande', by: 'Europe · les volcans', tag: 'Entre la glace et le feu', color: '#02529c',
    desc: 'Elle vit sur des volcans actifs, sous des aurores boréales, et prend tout cela avec une sérénité désarmante. Tout le monde y écrit, joue de la musique ou raconte des sagas, et l\'on croit volontiers aux elfes. Un tempérament audacieux, créatif, à l\'aise dans l\'imprévisible, pour qui l\'éruption fait partie du paysage.',
    t: { ide: 0.92, aud: 0.9, rsk: 0.85, vst: 0.9, inc: 0.92, ind: 0.8, vse: 0.15, thr: 0.15, ord: 0.3, con: 0.2 } },
  { name: 'La Grèce', by: 'Europe · l\'Égée', tag: 'Philosopher au bord de la mer', color: '#0d5eaf',
    desc: 'Elle a inventé la philosophie, la démocratie et le théâtre, puis s\'est installée à l\'ombre d\'un olivier pour en débattre. La philoxenia, l\'amour de l\'étranger, fait qu\'on repart toujours avec un plat de plus. Un tempérament bavard, fier, hospitalier, qui préfère une longue discussion à un horaire tenu.',
    t: { epi: 0.85, ouv: 0.9, soc: 0.9, com: 0.85, vtr: 0.85, vhe: 0.85, ord: 0.12, con: 0.18, vis: 0.7, cfl: 0.7 } },
  { name: 'La Pologne', by: 'Europe · la ville reconstruite', tag: 'Tout rebâtir, pierre par pierre', color: '#dc143c',
    desc: 'Quand sa capitale a été détruite, elle l\'a reconstruite à l\'identique en regardant de vieux tableaux. Ça dit tout : ténacité, fidélité à l\'héritage, et une foi profonde dans ce qu\'on transmet. On y est accueilli par des pierogi et des toasts sincères. Un tempérament tenace, loyal, qui ne lâche jamais ce qui compte.',
    t: { det: 0.95, loy: 0.95, vtr: 0.92, sanc: 0.85, opn: 0.85, lib: 0.8, vhe: 0.3, inc: 0.3, vst: 0.25, tmp: 0.9 } },
  { name: 'La Russie', by: 'Europe et Asie · la steppe infinie', tag: 'Une âme grande comme la steppe', color: '#6b1f2a',
    desc: 'Des romans de mille pages, des hivers de six mois, des ballets d\'une précision folle : rien n\'y est fait à moitié. Elle aime les grandes questions sans réponse et les longues conversations mélancoliques autour d\'un thé brûlant. Un tempérament profond, endurant, tourmenté par l\'absolu, qui préfère la gravité à la légèreté.',
    t: { aff: 0.1, vis: 0.85, opt: 0.15, ide: 0.9, det: 0.9, epi: 0.85, thr: 0.75, sanc: 0.8, vse: 0.3, vhe: 0.3, inc: 0.7 } },
  { name: 'La Turquie', by: 'Europe et Asie · le carrefour', tag: 'Un thé, et on discute', color: '#e30a17',
    desc: 'Assise entre deux continents, elle a pris le meilleur des deux et sert le thé à quiconque passe la porte du bazar. On y négocie avec art, on y parle fort, et l\'hospitalité n\'est pas une option. Un tempérament commerçant, chaleureux, expressif, qui adore faire des affaires autant que se faire des amis.',
    t: { soc: 0.95, vbe: 0.92, vtr: 0.85, ouv: 0.85, com: 0.8, inf: 0.9, dip: 0.8, vac: 0.8, loy: 0.85, ord: 0.25, cmp: 0.7 } },
  { name: 'L\'Autriche', by: 'Europe · la valse', tag: 'Trois temps et un café viennois', color: '#ef3340',
    desc: 'Mozart, Strauss, les cafés où l\'on reste des heures avec un journal et une part de Sachertorte : elle a fait de l\'élégance une habitude. Tout y a un certain cérémonial, doux et immuable. Un tempérament raffiné, attaché à ses rituels, qui préfère la continuité au bouleversement et la valse au rock.',
    t: { vhe: 0.85, vtr: 0.95, rig: 0.85, ide: 0.88, ste: 0.85, chg: 0.08, vst: 0.25, aud: 0.25, dom: 0.3, con: 0.8 } },
  { name: 'La Tchéquie', by: 'Europe · l\'absurde', tag: 'Un sourire en coin face au monde', color: '#11457e',
    desc: 'Elle a donné Kafka, le brave soldat Švejk, des marionnettes et une bière qu\'elle boit plus que quiconque. Son humour est pince-sans-rire, son rapport à l\'autorité délicieusement ironique. Un tempérament sceptique, créatif, qui ne croit à aucun grand discours mais sait apprécier une bonne soirée entre amis.',
    t: { dog: 0.05, vco: 0.2, auth: 0.1, ide: 0.9, vhe: 0.85, vis: 0.7, inc: 0.85, eng: 0.12, dom: 0.2, nat: 0.7 } },
  { name: 'La Croatie', by: 'Europe · les mille îles', tag: 'La fjaka au bord de l\'Adriatique', color: '#171796',
    desc: 'Elle a un mot, fjaka, pour cet état de douce torpeur où l\'on ne fait rien, face à la mer, et où c\'est très bien ainsi. Mais qu\'on la mette sur un terrain de sport et elle se bat comme un pays dix fois plus grand. Un tempérament détendu et fier, qui sait savourer le présent sans perdre sa combativité.',
    t: { vhe: 0.9, tmp: 0.1, ste: 0.85, loy: 0.9, cmp: 0.85, san: 0.85, vac: 0.3, ord: 0.25, soc: 0.8, det: 0.8 } },
  { name: 'Le Maroc', by: 'Afrique · les médinas', tag: 'Le thé versé de haut', color: '#c1272d',
    desc: 'Dans ses médinas, chaque zellige est posé à la main et chaque visiteur reçoit un thé à la menthe versé de très haut, par politesse autant que par art. Il sait négocier en souriant et recevoir comme un roi. Un tempérament hospitalier, patient, attaché aux traditions et au travail bien fait.',
    t: { vtr: 0.95, sanc: 0.85, dip: 0.9, rig: 0.85, soc: 0.9, vbe: 0.95, vst: 0.2, lib: 0.3, ind: 0.2, cfl: 0.25, care: 0.88 } },
  { name: 'L\'Algérie', by: 'Afrique · le Sahara', tag: 'La fierté et le cœur sur la main', color: '#006233',
    desc: 'Le plus grand pays d\'Afrique garde en lui l\'immensité du Sahara et l\'énergie du raï. On y parle franchement, on y défend les siens sans hésiter, et l\'on vous reçoit avec une générosité qui ne compte pas. Un tempérament fier, direct, loyal, qui ne se laisse pas marcher sur les pieds et ouvre grand sa porte.',
    t: { det: 0.9, loy: 0.95, com: 0.92, cfl: 0.85, vbe: 0.9, ind: 0.85, dip: 0.2, opn: 0.85, vpo: 0.3, vhe: 0.7 } },
  { name: 'La Tunisie', by: 'Afrique · le jasmin', tag: 'La douceur méditerranéenne', color: '#e70013',
    desc: 'Carthage, les maisons bleues et blanches de Sidi Bou Saïd, un brin de jasmin à l\'oreille : tout y invite à ralentir. Ouverte sur la Méditerranée depuis des millénaires, elle a appris à accueillir et à dialoguer. Un tempérament doux, conciliant, curieux de l\'autre, qui préfère la conversation à la confrontation.',
    t: { ste: 0.85, dip: 0.92, ouv: 0.9, opn: 0.15, vhe: 0.8, cfl: 0.15, dom: 0.2, vun: 0.82, emp: 0.88, vpo: 0.2 } },
  { name: 'Le Sénégal', by: 'Afrique · la teranga', tag: 'Ici, l\'étranger est roi', color: '#00853f',
    desc: 'La teranga, c\'est l\'hospitalité érigée en valeur nationale : on partage le thiéboudienne dans le même plat et personne ne reste dehors. On y prend le temps de saluer, de demander des nouvelles de toute la famille. Un tempérament généreux, collectif, confiant, pour qui le lien compte plus que tout le reste.',
    t: { att: 0.98, vbe: 0.95, emp: 0.95, soc: 0.95, care: 0.95, nat: 0.05, vpo: 0.1, com: 0.2, ind: 0.15, col: 0.95 } },
  { name: 'La Côte d\'Ivoire', by: 'Afrique · l\'ambiance', tag: 'Ça va aller, on est ensemble', color: '#f77f00',
    desc: 'Le coupé-décalé, le nouchi qui invente des mots chaque semaine, le maquis où l\'on refait le monde : l\'ambiance y est une institution. Elle est inventive, ambitieuse et persuadée que demain sera meilleur. Un tempérament festif, créatif, entreprenant, qui prend la vie avec un enthousiasme contagieux.',
    t: { inf: 0.97, vst: 0.9, opt: 0.95, vhe: 0.9, ide: 0.85, vis: 0.05, ord: 0.15, con: 0.1, vac: 0.8, rsk: 0.8 } },
  { name: 'L\'Égypte', by: 'Afrique · le Nil', tag: 'Bâtir pour l\'éternité', color: '#c09300',
    desc: 'Quand on construit des pyramides, on ne pense pas à la semaine prochaine : on pense aux cinq mille ans suivants. Le Nil coule, les siècles passent, et elle garde son calme — et son humour légendaire. Un tempérament patient, tourné vers le temps long, profondément attaché à ce qui dure et à ce qui se transmet.',
    t: { tmp: 0.98, vtr: 0.95, auth: 0.85, rig: 0.8, chg: 0.05, vst: 0.25, san: 0.85, soc: 0.8, ste: 0.85, sanc: 0.85 } },
  { name: 'Le Kenya', by: 'Afrique · les hauts plateaux', tag: 'Courir plus loin que tout le monde', color: '#006600',
    desc: 'Sur les hauts plateaux, on court à l\'aube, des dizaines de kilomètres, et l\'on remporte des marathons dans le monde entier. Harambee, « tirons ensemble » : la réussite y est collective. Un tempérament endurant, ambitieux, tourné vers la nature et la savane, qui avance sans relâche vers la ligne d\'arrivée.',
    t: { det: 0.98, cmp: 0.85, col: 0.85, vun: 0.88, vhe: 0.2, opt: 0.85, vac: 0.9, con: 0.3, san: 0.8, vst: 0.7 } },
  { name: 'L\'Afrique du Sud', by: 'Afrique · la nation arc-en-ciel', tag: 'Je suis parce que nous sommes', color: '#007a4d',
    desc: 'Deux océans, onze langues officielles et une philosophie, l\'ubuntu : je suis parce que nous sommes. Elle a fait de la réconciliation un symbole universel et de sa diversité une fierté. Un tempérament engagé, attaché à la justice, qui croit profondément que l\'on peut réparer et avancer ensemble.',
    t: { fair: 0.95, col: 0.9, eng: 0.9, chg: 0.85, dip: 0.88, opn: 0.1, emp: 0.9, vun: 0.95, dog: 0.15, cfl: 0.6 } },
  { name: 'Le Nigeria', by: 'Afrique · Nollywood', tag: 'L\'énergie à pleine puissance', color: '#008751',
    desc: 'Nollywood tourne des milliers de films par an, l\'afrobeats fait danser la planète, et Lagos ne dort jamais. On y rêve grand, on y entreprend sans attendre la permission, et l\'on vise le sommet. Un tempérament ambitieux, audacieux, spectaculaire, qui déborde d\'énergie et de confiance en l\'avenir.',
    t: { vac: 0.95, dom: 0.85, aud: 0.9, inf: 0.95, cmp: 0.9, rsk: 0.9, vpo: 0.8, ste: 0.15, vse: 0.2, opt: 0.9 } },
  { name: 'Madagascar', by: 'Afrique · l\'île-continent', tag: 'Mora mora, doucement', color: '#fc3d32',
    desc: 'Lémuriens, baobabs, espèces qu\'on ne trouve nulle part ailleurs : cette île a pris son temps pour devenir unique. Mora mora, « doucement », résume son rythme, et le fihavanana, l\'art de préserver le lien, son éthique. Un tempérament paisible, singulier, qui évite le conflit et ne court après personne.',
    t: { ste: 0.95, tmp: 0.35, dom: 0.08, cmp: 0.08, vst: 0.2, rsk: 0.2, vbe: 0.9, att: 0.88, cfl: 0.05, vun: 0.88, ide: 0.8 } },
  { name: 'L\'Éthiopie', by: 'Afrique · les hauts plateaux d\'Abyssinie', tag: 'Treize mois de soleil', color: '#078930',
    desc: 'Elle a son propre calendrier, son propre alphabet, et la cérémonie du café qu\'elle a offert au monde se déroule en trois tasses, sans hâte. Jamais elle n\'a renoncé à ce qu\'elle est. Un tempérament indépendant, enraciné, spirituel, qui avance à son rythme, sans éprouver le besoin de ressembler à quiconque.',
    t: { ind: 0.95, vtr: 0.98, sanc: 0.9, chg: 0.05, opn: 0.9, ouv: 0.3, loy: 0.9, tmp: 0.95, vsd: 0.85, vst: 0.2 } },
  { name: 'Le Ghana', by: 'Afrique · le kente', tag: 'Akwaaba, bienvenue', color: '#fcd116',
    desc: 'Akwaaba, « bienvenue » : c\'est le premier mot qu\'on y entend. Pionnier sur son continent, il tisse le kente aux motifs chargés de sens et danse sur le highlife. Un tempérament accueillant, pionnier, engagé, qui sait montrer la voie sans jamais élever la voix et préfère convaincre que contraindre.',
    t: { att: 0.9, dip: 0.9, fia: 0.85, vbe: 0.9, ide: 0.85, eng: 0.85, chg: 0.8, lea: 0.88, cfl: 0.2, vpo: 0.25 } },
  { name: 'Le Japon', by: 'Asie · l\'archipel', tag: 'La perfection dans le détail', color: '#bc002d',
    desc: 'Un bol de thé se prépare en quarante gestes, les trains partent à l\'heure exacte et personne ne parle fort dans le métro. Tout y est pensé pour le groupe, avec un soin infini pour le détail et un respect profond des saisons. Un tempérament discret, rigoureux, harmonieux, qui a fait de la retenue une forme de beauté.',
    t: { rig: 0.98, con: 0.95, vco: 0.95, ord: 0.97, inf: 0.08, cfl: 0.08, sanc: 0.9, tmp: 0.9, col: 0.9, com: 0.08, ide: 0.8 } },
  { name: 'La Corée du Sud', by: 'Asie · le pali-pali', tag: 'Plus vite, plus haut, maintenant', color: '#0047a0',
    desc: 'Pali-pali, « vite, vite » : la livraison arrive en dix minutes, internet va plus vite qu\'ailleurs, et la K-pop répète jusqu\'à la perfection. Elle s\'est transformée en une génération et ne compte pas ralentir. Un tempérament travailleur, compétitif, tourné vers l\'excellence et la nouveauté, qui vise toujours la première place.',
    t: { vac: 0.98, cmp: 0.95, det: 0.95, chg: 0.85, vst: 0.85, ste: 0.12, inc: 0.3, loy: 0.85, vis: 0.12, vhe: 0.3, rig: 0.85 } },
  { name: 'La Chine', by: 'Asie · les millénaires', tag: 'Penser en siècles', color: '#de2910',
    desc: 'Cinq mille ans de calligraphie, de thé et de proverbes : elle voit le temps en dynasties, pas en trimestres. La famille y est le centre du monde, le respect des aînés une évidence, et le travail une vertu. Un tempérament patient, collectif, ambitieux sur le long terme, qui pense à ce qu\'il laissera aux générations suivantes.',
    t: { tmp: 0.98, col: 0.95, vtr: 0.9, auth: 0.85, loy: 0.9, vsd: 0.2, ind: 0.15, vac: 0.85, cmp: 0.75, lib: 0.2 } },
  { name: 'L\'Inde', by: 'Asie · le sous-continent', tag: 'Tout, partout, en couleurs', color: '#ff9933',
    desc: 'Mille langues, des fêtes où l\'on se jette des poudres de couleur, des films où tout le monde danse, et une spiritualité présente à chaque coin de rue. Le chaos y a sa propre logique, que l\'on finit par aimer. Un tempérament foisonnant, spirituel, expansif, à l\'aise dans la multitude et l\'imprévu.',
    t: { inc: 0.95, ouv: 0.9, sanc: 0.95, soc: 0.95, inf: 0.9, ord: 0.08, con: 0.2, vtr: 0.85, ide: 0.9, vst: 0.85 } },
  { name: 'La Thaïlande', by: 'Asie · le pays du sourire', tag: 'Mai pen rai, ce n\'est rien', color: '#a51931',
    desc: 'Mai pen rai, « ce n\'est rien » : la réponse à presque tout, accompagnée d\'un sourire. Elle cherche le sanuk, le plaisir, dans chaque activité, et fuit l\'affrontement comme la peste. Un tempérament serein, doux, profondément respectueux, qui préfère perdre la face d\'un problème que la sienne.',
    t: { cfl: 0.02, san: 0.95, vhe: 0.95, opt: 0.9, thr: 0.05, dip: 0.95, com: 0.05, tmp: 0.2, auth: 0.75, sanc: 0.8 } },
  { name: 'Le Vietnam', by: 'Asie · les rizières', tag: 'Toujours une solution', color: '#da251d',
    desc: 'Des rizières en terrasse sculptées depuis des siècles, des scooters qui transportent un réfrigérateur et une famille, un phở à six heures du matin. Il est débrouillard, travailleur et d\'un pragmatisme redoutable. Un tempérament tenace, inventif, qui s\'adapte à tout et trouve toujours un moyen d\'avancer.',
    t: { det: 0.95, epi: 0.05, vac: 0.85, loy: 0.9, inc: 0.85, vhe: 0.35, ste: 0.3, ord: 0.3, fia: 0.85, rsk: 0.7 } },
  { name: 'L\'Indonésie', by: 'Asie · les dix-sept mille îles', tag: 'Tous ensemble, d\'île en île', color: '#ce1126',
    desc: 'Dix-sept mille îles, des centaines de langues, et une devise : l\'unité dans la diversité. Le gotong royong, l\'entraide de village, fait que personne ne construit sa maison seul. Un tempérament collectif, spirituel, conciliant, qui fait tenir ensemble un monde immense avec douceur et patience.',
    t: { col: 0.95, dip: 0.9, inc: 0.85, ouv: 0.8, sanc: 0.9, cfl: 0.1, vbe: 0.9, ind: 0.12, ide: 0.85, auth: 0.7 } },
  { name: 'Les Philippines', by: 'Asie · les sept mille îles', tag: 'Le karaoké contre la tempête', color: '#0038a8',
    desc: 'Les typhons passent, et le lendemain tout le monde s\'entraide, chante au karaoké et prépare la fête du quartier. Le bayanihan, c\'est soulever ensemble la maison du voisin pour la déplacer. Un tempérament joyeux, résilient, profondément chaleureux, qui ne laisse jamais la tristesse avoir le dernier mot.',
    t: { opt: 0.98, att: 0.95, soc: 0.95, inf: 0.9, vbe: 0.95, sanc: 0.85, vis: 0.05, thr: 0.3, vac: 0.4, rig: 0.3 } },
  { name: 'La Mongolie', by: 'Asie · la steppe', tag: 'Le ciel pour seul toit', color: '#c4272f',
    desc: 'Des centaines de kilomètres de steppe, une yourte qu\'on démonte en une heure, un cheval et le ciel bleu éternel. Le nomadisme y est encore une façon de vivre, libre et imprévisible. Un tempérament indépendant, rude, attaché à la liberté et aux grands espaces, qui n\'a besoin de personne pour trouver son chemin.',
    t: { ind: 0.95, vsd: 0.95, soc: 0.2, ord: 0.15, vse: 0.15, rsk: 0.85, vun: 0.85, vtr: 0.85, inc: 0.9, lib: 0.95, col: 0.3 } },
  { name: 'Le Népal', by: 'Asie · l\'Himalaya', tag: 'Monter sans jamais se hausser', color: '#003893',
    desc: 'Il abrite le toit du monde, mais ceux qui y guident les expéditions sont d\'une humilité désarmante. Drapeaux de prière au vent, temples au détour des sentiers : tout y invite à la sérénité. Un tempérament paisible, spirituel, endurant, qui gravit les sommets sans jamais chercher à dominer qui que ce soit.',
    t: { san: 0.95, det: 0.95, sanc: 0.95, vpo: 0.05, vhe: 0.2, dom: 0.12, vun: 0.88, ste: 0.9, vac: 0.2, thr: 0.25 } },
  { name: 'Le Bhoutan', by: 'Asie · le bonheur national brut', tag: 'Mesurer le bonheur, pas la richesse', color: '#ff8c00',
    desc: 'Ce petit royaume himalayen mesure son bonheur national brut plutôt que sa richesse, et protège ses forêts comme un trésor. Tout y va lentement, avec une conviction tranquille. Un tempérament serein, idéaliste, indifférent à la compétition et à la course au statut, qui sait ce qui compte vraiment.',
    t: { vpo: 0.02, vac: 0.05, vun: 0.95, sanc: 0.95, ste: 0.95, thr: 0.2, vst: 0.1, chg: 0.1, cmp: 0.02, opn: 0.9, epi: 0.8 } },
  { name: 'Le Liban', by: 'Asie · le pays du cèdre', tag: 'Vivre, quoi qu\'il arrive', color: '#00a651',
    desc: 'On y parle trois langues dans la même phrase, on commerce depuis les Phéniciens, et les tables de mezze ne finissent jamais. Sa joie de vivre est légendaire, intense, obstinée. Un tempérament cosmopolite, festif, entreprenant, qui sait profiter de chaque instant et rebondir sur tous les imprévus.',
    t: { vhe: 0.95, ouv: 0.95, opn: 0.08, soc: 0.95, inc: 0.95, vst: 0.85, vac: 0.85, rsk: 0.8, vse: 0.2, ste: 0.25 } },
  { name: 'L\'Iran', by: 'Asie · la Perse', tag: 'Un vers de Hafez et un jardin', color: '#239f40',
    desc: 'On y récite de la poésie par cœur, on tisse des tapis pendant des années, on dessine des jardins comme des paradis. Le taarof, ce ballet de politesses où l\'on refuse trois fois avant d\'accepter, dit tout de son raffinement. Un tempérament délicat, poétique, cérémonieux, qui habille chaque geste de beauté.',
    t: { ide: 0.97, dip: 0.97, att: 0.88, rig: 0.88, vtr: 0.9, com: 0.08, aff: 0.12, cfl: 0.1, vst: 0.2, dom: 0.15, lib: 0.3 } },
  { name: 'L\'Arménie', by: 'Asie · le mont Ararat', tag: 'Une mémoire longue et tendre', color: '#d90012',
    desc: 'Elle a son propre alphabet depuis seize siècles, des monastères perchés dans la montagne et l\'abricot pour emblème. Ses enfants, dispersés aux quatre coins du monde, restent reliés par la musique, la cuisine et le souvenir. Un tempérament fidèle, mémoriel, chaleureux, qui garde vivant ce qu\'il aime.',
    t: { loy: 0.95, vtr: 0.95, det: 0.9, ide: 0.85, vis: 0.7, opn: 0.9, thr: 0.7, att: 0.9, vhe: 0.4, dom: 0.3 } },
  { name: 'Les États-Unis', by: 'Amérique du Nord · la route 66', tag: 'Tout est possible, allons-y', color: '#3c3b6e',
    desc: 'Des déserts, des gratte-ciel, des road trips interminables et la conviction qu\'on peut tout recommencer à zéro dans un garage. Il aime le grand, le neuf, le spectaculaire, et ne comprend pas qu\'on doute. Un tempérament optimiste, individualiste, entreprenant, pour qui chaque échec est une étape vers le succès.',
    t: { opt: 0.95, aud: 0.95, vac: 0.95, ind: 0.95, col: 0.1, rsk: 0.9, vis: 0.05, inf: 0.9, vtr: 0.3, lib: 0.95 } },
  { name: 'Le Mexique', by: 'Amérique du Nord · le Día de Muertos', tag: 'Faire la fête avec ses défunts', color: '#006847',
    desc: 'Il célèbre ses morts avec des autels fleuris, des crânes en sucre et de la musique, parce que l\'amour ne s\'arrête pas à la mort. Couleurs éclatantes, mariachis, piments et familles immenses. Un tempérament vibrant, fidèle aux siens, qui mêle le sacré et la fête avec une ferveur inimitable.',
    t: { ide: 0.95, vtr: 0.9, sanc: 0.85, inf: 0.9, vhe: 0.9, att: 0.95, ord: 0.2, thr: 0.2, loy: 0.9, aff: 0.1 } },
  { name: 'Cuba', by: 'Amérique · les Caraïbes', tag: 'Danser avec trois fois rien', color: '#002a8f',
    desc: 'Des voitures de 1955 qui roulent encore, de la musique à chaque coin de rue, et une capacité à tout réparer avec presque rien. On y danse la salsa dans le salon, on y joue aux dominos sur le trottoir. Un tempérament débrouillard, festif, insouciant du lendemain, qui fait de chaque soirée une fête.',
    t: { vhe: 0.95, inc: 0.9, inf: 0.95, soc: 0.95, ord: 0.1, vse: 0.2, vac: 0.2, tmp: 0.08, ide: 0.85, vpo: 0.1 } },
  { name: 'La Jamaïque', by: 'Amérique · les Caraïbes', tag: 'One love, no problem', color: '#009b3a',
    desc: 'Le reggae, la cadence lente, « no problem » à chaque phrase — et pourtant les sprinteurs les plus rapides de la planète. Elle vit à son rythme, zen, libre, chaleureuse, persuadée que les choses vont s\'arranger. Un tempérament détendu, pacifique, qui préfère la liberté à la règle et garde toujours un bon groove.',
    t: { san: 0.95, thr: 0.02, ste: 0.8, vhe: 0.9, vun: 0.88, con: 0.05, ord: 0.05, lib: 0.9, rig: 0.1, opt: 0.9 } },
  { name: 'Le Costa Rica', by: 'Amérique centrale · la pura vida', tag: 'Pura vida', color: '#3a7d44',
    desc: 'Il a supprimé son armée pour investir dans les écoles, protège un quart de son territoire et répond « pura vida » à tout. Paresseux dans les arbres, volcans dans la brume, biodiversité record. Un tempérament paisible, écologiste, bienveillant, qui a choisi la douceur plutôt que la force.',
    t: { vun: 0.98, care: 0.95, dom: 0.05, cmp: 0.08, opt: 0.95, vhe: 0.85, vis: 0.05, thr: 0.05, com: 0.2, nat: 0.1 } },
  { name: 'Le Brésil', by: 'Amérique du Sud · le carnaval', tag: 'La fête comme art de vivre', color: '#009c3b',
    desc: 'Le carnaval, la samba, le football joué pieds nus sur la plage, et l\'Amazonie en arrière-plan : tout y déborde de vie. On y fait connaissance en trente secondes et l\'on devient amis pour la vie. Un tempérament exubérant, spontané, joyeux, qui transforme chaque occasion en célébration.',
    t: { inf: 0.98, vst: 0.95, vhe: 0.95, opt: 0.95, soc: 0.98, ord: 0.08, con: 0.08, vis: 0.1, cmp: 0.75, rig: 0.15 } },
  { name: 'L\'Argentine', by: 'Amérique du Sud · le tango', tag: 'La passion jusqu\'au bout des doigts', color: '#74acdf',
    desc: 'Le tango est une conversation passionnée à deux, le football une religion, et l\'asado du dimanche une cérémonie. On y débat de tout avec fougue, on analyse ses sentiments sans pudeur. Un tempérament intense, passionné, loyal jusqu\'à l\'excès, qui vit tout — la victoire comme le chagrin — à fond.',
    t: { aff: 0.08, com: 0.9, cfl: 0.85, epi: 0.8, ide: 0.9, vis: 0.8, loy: 0.95, vhe: 0.85, inf: 0.85, san: 0.25 } },
  { name: 'Le Chili', by: 'Amérique du Sud · le long ruban', tag: 'Entre désert et poésie', color: '#0039a6',
    desc: 'Coincé entre les Andes et le Pacifique, du désert le plus aride aux glaciers de Patagonie, il a appris la prudence face à une terre qui tremble. Et il a donné deux Nobels de poésie. Un tempérament réfléchi, prévoyant, sérieux, qui cache une âme de poète sous des dehors raisonnables.',
    t: { san: 0.9, fia: 0.9, thr: 0.75, vig: 0.92, ide: 0.85, rig: 0.8, inf: 0.25, rsk: 0.25, vse: 0.8, det: 0.85 } },
  { name: 'Le Pérou', by: 'Amérique du Sud · les Andes', tag: 'Remercier la Terre-Mère', color: '#d91023',
    desc: 'Le Machu Picchu, des terrasses cultivées depuis les Incas, trois mille variétés de pommes de terre et des offrandes à la Pachamama. Il honore ce qui le précède et prend soin de la terre qui le nourrit. Un tempérament enraciné, humble, spirituel, qui bâtit dans la durée sans chercher à briller.',
    t: { vtr: 0.95, sanc: 0.9, tmp: 0.95, rig: 0.8, vun: 0.88, col: 0.9, chg: 0.1, dom: 0.2, vst: 0.3, cmp: 0.2 } },
  { name: 'La Colombie', by: 'Amérique du Sud · le réalisme magique', tag: 'La magie au quotidien', color: '#fcd116',
    desc: 'Le pays de García Márquez, où le merveilleux se mêle au quotidien sans que personne ne s\'en étonne. Café, fleurs, cumbia, et une gentillesse qui désarme les voyageurs. Un tempérament rêveur, affectueux, optimiste, qui voit toujours la beauté cachée dans les choses et les gens.',
    t: { opt: 0.95, att: 0.95, ide: 0.95, emp: 0.9, vhe: 0.85, inc: 0.8, cfl: 0.12, dip: 0.9, vis: 0.05, rig: 0.3 } },
  { name: 'L\'Australie', by: 'Océanie · l\'outback', tag: 'No worries, mate', color: '#00247d',
    desc: 'Surf à l\'aube, barbecue le soir, un désert rouge grand comme un continent et des animaux qui ne ressemblent à rien. On s\'y appelle « mate » dès la première rencontre et on se moque gentiment des grands airs. Un tempérament aventureux, décontracté, franc, allergique à la hiérarchie et fidèle en amitié.',
    t: { rsk: 0.9, aud: 0.9, thr: 0.1, san: 0.88, loy: 0.85, com: 0.85, auth: 0.08, vpo: 0.1, vco: 0.2, vst: 0.9, ord: 0.25 } },
  { name: 'La Nouvelle-Zélande', by: 'Océanie · la Terre du long nuage blanc', tag: 'Le haka et la terre du milieu', color: '#00247d',
    desc: 'Des paysages si beaux qu\'on y a tourné la Terre du Milieu, un haka qui fait trembler l\'adversaire et une culture maorie profondément respectée. Elle protège sa nature comme une personne. Un tempérament humble, soudé, déterminé, qui allie la douceur des collines verdoyantes à une vraie force intérieure.',
    t: { vun: 0.95, care: 0.9, vpo: 0.05, dom: 0.25, loy: 0.92, det: 0.88, sanc: 0.8, nat: 0.15, col: 0.85, ind: 0.3, vhe: 0.4 } },
];

window.PRISME_COUNTRIES = { COUNTRIES };
