/* ============================================================
   PRISME — « Si tu étais un département français »
   ------------------------------------------------------------
   Les 101 départements, racontés avec affection par ce qui fait
   leur caractère — paysages, produits, traditions, rythme de vie —
   jamais par leur politique ni leurs difficultés : le tempérament
   qu'on leur prête quand on y passe, qu'on y vit ou qu'on en vient.
     name = le département, by = numéro · région, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const DEPARTMENTS_FR = [
  { name: 'L\'Ain', by: '01 · Auvergne-Rhône-Alpes', tag: 'Le poulet aux couleurs du drapeau', color: '#3d6fb6',
    desc: 'Il élève un poulet pattes bleues, plumage blanc, crête rouge, si réputé qu\'il a son appellation, et compte des centaines d\'étangs dans la Dombes où les oiseaux font escale. Entre Bresse, Bugey et monastère de Brou, il travaille bien sans se vanter. Un tempérament discret, soigneux, fier en silence.',
    t: { fia: 0.92, rig: 0.85, inf: 0.12, ste: 0.85, vtr: 0.82, vst: 0.2, vpo: 0.1, aud: 0.2, con: 0.8, soc: 0.3 } },
  { name: 'L\'Aisne', by: '02 · Hauts-de-France', tag: 'La cathédrale sur la colline', color: '#6b7a8f',
    desc: 'Du haut de sa butte, Laon veille avec les bœufs sculptés dans les tours de sa cathédrale, et Jean de La Fontaine est né à Château-Thierry, au bord de ses vignes de champagne. Il a traversé l\'histoire sans se plaindre. Un tempérament patient, mémoriel, qui regarde loin.',
    t: { tmp: 0.92, ste: 0.88, vtr: 0.85, vis: 0.72, opt: 0.28, inf: 0.1, vst: 0.15, san: 0.8, rsk: 0.2, sanc: 0.75 } },
  { name: 'L\'Allier', by: '03 · Auvergne-Rhône-Alpes', tag: 'Des chênes et des pastilles', color: '#4f7a3a',
    desc: 'Il a la forêt de Tronçais et ses chênes plantés pour la marine de Colbert, les pastilles de Vichy et les bocages du Bourbonnais où l\'on ne se presse jamais. On y vient en cure depuis Napoléon III. Un tempérament paisible et pudique, qui soigne son monde sans bruit.',
    t: { ste: 0.92, care: 0.88, vse: 0.85, dom: 0.1, cmp: 0.15, vst: 0.2, inf: 0.2, vbe: 0.85, rsk: 0.15, chg: 0.15 } },
  { name: 'Les Alpes-de-Haute-Provence', by: '04 · Provence-Alpes-Côte d\'Azur', tag: 'La lavande et le silence', color: '#8a6fbf',
    desc: 'En juillet, le plateau de Valensole se couvre de lavande à perte de vue, Moustiers suspend son étoile entre deux falaises et Giono semble encore écrire dans l\'air de Manosque. Ici, on parle peu et on regarde beaucoup. Un tempérament contemplatif, qui a besoin d\'espace et de lumière.',
    t: { ind: 0.9, soc: 0.12, inf: 0.1, vun: 0.88, ide: 0.85, ste: 0.8, vpo: 0.08, cmp: 0.12, sanc: 0.72, vsd: 0.85 } },
  { name: 'Les Hautes-Alpes', by: '05 · Provence-Alpes-Côte d\'Azur', tag: 'Le soleil en altitude', color: '#f0b429',
    desc: 'Briançon passe pour la plus haute ville de France, le lac de Serre-Ponçon brille comme une mer intérieure et le soleil y brille si souvent que les habitants s\'en vantent volontiers. Ski le matin, via ferrata l\'après-midi. Un tempérament sportif, lumineux, qui respire mieux là-haut.',
    t: { opt: 0.95, vis: 0.05, vst: 0.88, rsk: 0.8, det: 0.88, thr: 0.1, vig: 0.2, nat: 0.15, tmp: 0.3, ind: 0.75 } },
  { name: 'Les Alpes-Maritimes', by: '06 · Provence-Alpes-Côte d\'Azur', tag: 'Palmiers, tapis rouge et citrons', color: '#e8b800',
    desc: 'Il a la baie des Anges, les marches du Palais des festivals à Cannes, les parfums de Grasse et une fête du citron à Menton où l\'on sculpte des chars en agrumes. La mer le matin, la montagne l\'après-midi. Un tempérament élégant et solaire, qui aime la belle vie et les projecteurs.',
    t: { vhe: 0.92, vpo: 0.88, inf: 0.85, vac: 0.82, care: 0.25, vun: 0.2, eng: 0.1, ste: 0.3, cmp: 0.75, soc: 0.8 } },
  { name: 'L\'Ardèche', by: '07 · Auvergne-Rhône-Alpes', tag: 'Canoë, marrons et grotte ornée', color: '#b35a1f',
    desc: 'On la descend en canoë sous le pont d\'Arc, on tartine sa crème de marrons et on salue les lions peints dans la grotte Chauvet il y a 36 000 ans. Les frères Montgolfier y ont fait voler le premier ballon. Un tempérament sauvage et aventurier, les pieds dans l\'eau.',
    t: { vst: 0.92, aud: 0.88, rsk: 0.85, vse: 0.15, ord: 0.2, con: 0.12, vun: 0.8, lib: 0.85, ouv: 0.8, vpo: 0.1 } },
  { name: 'Les Ardennes', by: '08 · Grand Est', tag: 'Forêt profonde et marionnettes', color: '#3b4a3a',
    desc: 'Rimbaud est né à Charleville, qui accueille un festival mondial de marionnettes, et le château fort de Sedan passe pour le plus grand d\'Europe. Autour, la Meuse serpente dans une forêt pleine de légendes et de sangliers. Un tempérament secret, rebelle, un peu poète.',
    t: { ind: 0.88, ide: 0.85, soc: 0.2, inf: 0.15, chg: 0.75, con: 0.15, auth: 0.15, nat: 0.7, vco: 0.1, opt: 0.35, vsd: 0.88 } },
  { name: 'L\'Ariège', by: '09 · Occitanie', tag: 'Montagne libre et fière', color: '#5c7d4a',
    desc: 'Des châteaux cathares perchés comme Montségur, des grottes peintes à Niaux, des estives où la transhumance se fête et des ours qui se promènent dans la montagne. Ici, on vit loin des grandes villes et on en est fier. Un tempérament indocile et rustique, qui tient à sa liberté plus qu\'à son confort.',
    t: { lib: 0.95, auth: 0.1, vco: 0.12, ind: 0.85, opn: 0.82, cfl: 0.78, vpo: 0.08, vse: 0.25, vtr: 0.75, com: 0.8 } },
  { name: 'L\'Aube', by: '10 · Grand Est', tag: 'Pans de bois et bonnes affaires', color: '#c0892f',
    desc: 'Troyes a la forme d\'un bouchon de champagne, des rues entières de maisons à pans de bois et des magasins d\'usine qui attirent les chasseurs de bonnes affaires. Ajoutez l\'andouillette, le chaource et les lacs de la forêt d\'Orient. Un tempérament malin, qui sait où trouver le bon plan.',
    t: { aff: 0.85, epi: 0.1, vac: 0.75, vse: 0.8, cmp: 0.7, ide: 0.2, vun: 0.25, rig: 0.7, vhe: 0.65, dog: 0.2 } },
  { name: 'L\'Aude', by: '11 · Occitanie', tag: 'Remparts et cassoulet', color: '#9b3b2a',
    desc: 'Carcassonne aligne ses cinquante-deux tours, les châteaux cathares s\'accrochent aux crêtes et Castelnaudary revendique le vrai cassoulet. À Limoux, le carnaval dure des semaines, arrosé de blanquette. Un tempérament fier et défensif, qui ouvre grand sa table une fois la porte franchie.',
    t: { loy: 0.92, vig: 0.85, thr: 0.78, opn: 0.85, vtr: 0.88, vhe: 0.8, nat: 0.75, ouv: 0.25, chg: 0.12, att: 0.8 } },
  { name: 'L\'Aveyron', by: '12 · Occitanie', tag: 'Aligot, couteau et viaduc', color: '#6b4b2a',
    desc: 'Il affine le roquefort dans les caves du Combalou, file l\'aligot au bout de la louche, forge des couteaux à Laguiole et a laissé un viaduc géant enjamber le Tarn à Millau. Ses enfants montés à Paris y tenaient les cafés. Un tempérament travailleur, attaché à sa terre même loin d\'elle.',
    t: { det: 0.92, fia: 0.9, loy: 0.88, opn: 0.9, vac: 0.8, vst: 0.2, inf: 0.25, vhe: 0.3, att: 0.85, epi: 0.15 } },
  { name: 'Les Bouches-du-Rhône', by: '13 · Provence-Alpes-Côte d\'Azur', tag: 'Plus fort que le mistral', color: '#1f8fcf',
    desc: 'Marseille et son Vélodrome, Aix et ses calissons, Arles et ses arènes, la Camargue et ses flamants roses : il a tout, en grand, et il le dit à voix haute. Un pastis, une partie de boules, une histoire un peu exagérée. Un tempérament volcanique et généreux, incapable de faire semblant.',
    t: { inf: 0.95, com: 0.92, cfl: 0.9, dip: 0.15, con: 0.1, rig: 0.15, vhe: 0.85, loy: 0.88, san: 0.2, soc: 0.9 } },
  { name: 'Le Calvados', by: '14 · Normandie', tag: 'Du cidre et des plages de mémoire', color: '#c2a14a',
    desc: 'Il a donné son nom à l\'eau-de-vie de pomme, affine le pont-l\'évêque et le livarot, garde la tapisserie de Bayeux et veille sur les plages du Débarquement. Le week-end, Paris vient marcher sur les planches de Deauville. Un tempérament digne et reconnaissant, qui sait recevoir.',
    t: { loy: 0.85, fair: 0.8, tmp: 0.88, vbe: 0.85, dip: 0.85, vst: 0.25, com: 0.2, cfl: 0.2, vtr: 0.8, sanc: 0.7 } },
  { name: 'Le Cantal', by: '15 · Auvergne-Rhône-Alpes', tag: 'Volcan endormi, cœur vaillant', color: '#4a6b2f',
    desc: 'Il a le plus grand volcan d\'Europe, raboté en montagnes vertes, des vaches Salers aux cornes en lyre et un fromage qui porte son nom. En août, Aurillac livre ses rues au théâtre de rue. Un tempérament rude et tendre à la fois, qui résiste à l\'hiver et s\'ouvre en été.',
    t: { san: 0.92, det: 0.88, thr: 0.3, soc: 0.25, inf: 0.2, opn: 0.88, vpo: 0.08, aff: 0.35, vtr: 0.8, vbe: 0.8, att: 0.75 } },
  { name: 'La Charente', by: '16 · Nouvelle-Aquitaine', tag: 'Bulles de BD et cognac', color: '#c77d2a',
    desc: 'Chaque janvier, Angoulême devient la capitale de la bande dessinée, avec des murs peints à chaque coin de rue. Plus loin, Cognac laisse vieillir ses eaux-de-vie en fût pendant des années. Et c\'est ici qu\'on fabrique les charentaises. Un tempérament créatif et casanier, patient comme un vieux cognac.',
    t: { ide: 0.9, tmp: 0.9, ste: 0.8, vst: 0.3, vhe: 0.8, rsk: 0.2, soc: 0.3, cmp: 0.2, ouv: 0.8, chg: 0.3 } },
  { name: 'La Charente-Maritime', by: '17 · Nouvelle-Aquitaine', tag: 'Les îles, le pineau et la voile', color: '#3aa0c8',
    desc: 'La Rochelle garde ses tours au bord du port de plaisance, l\'île de Ré se parcourt à vélo sous les roses trémières et Marennes-Oléron élève des huîtres de caractère. Fort Boyard trône au large. Un tempérament marin et décontracté, qui aime le vent, les vacances et l\'apéro au couchant.',
    t: { vhe: 0.9, soc: 0.85, vst: 0.75, tmp: 0.2, vig: 0.2, rig: 0.25, opt: 0.88, thr: 0.12, inc: 0.8, cmp: 0.3 } },
  { name: 'Le Cher', by: '18 · Centre-Val de Loire', tag: 'Au centre de tout', color: '#7a5c8e',
    desc: 'Il revendique le centre géographique de la France, abrite à Bourges une immense cathédrale gothique et le festival du Printemps, et fait le crottin de Chavignol sous les vignes de Sancerre. Un tempérament central au sens noble : équilibré, modéré, qui fait le lien entre tout le monde.',
    t: { dip: 0.95, cfl: 0.08, dog: 0.08, com: 0.15, col: 0.8, fair: 0.88, epi: 0.15, chg: 0.35, inc: 0.75, dom: 0.15 } },
  { name: 'La Corrèze', by: '19 · Nouvelle-Aquitaine', tag: 'La foire de Brive et l\'accordéon', color: '#8a3b3b',
    desc: 'Brive remplit ses halles et sa foire du livre, Tulle fabrique des accordéons, Collonges-la-Rouge rougeoie de grès et le plateau de Millevaches déroule ses landes. On y relève tout de moutarde violette. Un tempérament convivial et rustique, qui ne manque ni un marché ni une fête de village.',
    t: { soc: 0.88, att: 0.88, vtr: 0.85, vbe: 0.88, vst: 0.3, cmp: 0.15, vpo: 0.15, ide: 0.3, col: 0.85, aff: 0.2 } },
  { name: 'La Corse-du-Sud', by: '2A · Corse', tag: 'Falaises blanches et maquis', color: '#2d7fa6',
    desc: 'Bonifacio pose ses maisons au bord de falaises calcaires, les calanques de Piana rougissent au couchant et Ajaccio rappelle à chacun que Napoléon est né ici. Les plages de Porto-Vecchio font rêver tout l\'été. Un tempérament fier, beau et réservé, qui choisit à qui il ouvre sa porte.',
    t: { loy: 0.95, nat: 0.85, opn: 0.92, vtr: 0.88, vhe: 0.75, soc: 0.3, ouv: 0.2, dip: 0.3, vpo: 0.7, att: 0.8 } },
  { name: 'La Haute-Corse', by: '2B · Corse', tag: 'Polyphonies et châtaigniers', color: '#3f6b3a',
    desc: 'Le cap Corse pointe vers le large, Corte veille au cœur des montagnes et les polyphonies résonnent dans les églises de village. On fait de la farine avec les châtaignes et du fiadone avec le brocciu. Un tempérament montagnard, grave et chaleureux, fidèle jusqu\'au bout.',
    t: { loy: 0.95, sanc: 0.85, vtr: 0.95, col: 0.88, ind: 0.2, chg: 0.08, vst: 0.2, att: 0.9, auth: 0.7, inf: 0.3 } },
  { name: 'La Côte-d\'Or', by: '21 · Bourgogne-Franche-Comté', tag: 'Grands crus et moutarde forte', color: '#8c1d40',
    desc: 'Sa route des grands crus aligne Gevrey-Chambertin, Vosne-Romanée et Meursault, les Hospices de Beaune vendent leur vin aux enchères chaque novembre et Dijon relève tout de moutarde. Un tempérament raffiné et exigeant, qui ne transige ni sur la qualité ni sur la tradition.',
    t: { rig: 0.92, con: 0.88, vpo: 0.8, vtr: 0.92, vhe: 0.85, chg: 0.1, inc: 0.2, dog: 0.7, vac: 0.8, ouv: 0.3 } },
  { name: 'Les Côtes-d\'Armor', by: '22 · Bretagne', tag: 'Granit rose et coquilles Saint-Jacques', color: '#e07a6a',
    desc: 'À Ploumanac\'h, ses rochers de granit rose prennent des formes de tortues et de chapeaux, l\'île de Bréhat fleurit sans voitures et les ports pêchent la coquille Saint-Jacques. Un tempérament rêveur et doux, qui voit des animaux dans les rochers et prend le temps de regarder la marée.',
    t: { ide: 0.92, ste: 0.85, vst: 0.3, dom: 0.1, com: 0.12, vun: 0.85, emp: 0.85, cmp: 0.1, vac: 0.2, inf: 0.3, ouv: 0.8 } },
  { name: 'La Creuse', by: '23 · Nouvelle-Aquitaine', tag: 'Le calme absolu', color: '#6f8f55',
    desc: 'Elle tisse à Aubusson des tapisseries inscrites au patrimoine de l\'humanité, abrite des loups à Chabrières et envoyait jadis ses maçons bâtir Paris. Aujourd\'hui, elle offre surtout un silence rare et des nuits pleines d\'étoiles. Un tempérament serein, parfaitement heureux sans être vu.',
    t: { ste: 0.95, vpo: 0.05, vac: 0.12, inf: 0.08, soc: 0.15, cmp: 0.08, thr: 0.12, vst: 0.15, san: 0.85, ind: 0.8 } },
  { name: 'La Dordogne', by: '24 · Nouvelle-Aquitaine', tag: 'Foie gras, truffes et châteaux', color: '#9a6a2a',
    desc: 'Quatre Périgords de couleurs différentes, des grottes où Lascaux a gardé ses aurochs, des châteaux perchés au-dessus de la rivière et des marchés où la truffe et la noix se négocient à voix basse. Un tempérament gourmand et patrimonial, qui vit bien et le sait.',
    t: { vhe: 0.95, vtr: 0.9, vse: 0.85, rsk: 0.15, eng: 0.08, epi: 0.15, soc: 0.75, dog: 0.35, chg: 0.1, tmp: 0.7 } },
  { name: 'Le Doubs', by: '25 · Bourgogne-Franche-Comté', tag: 'Le comté et la précision', color: '#3b5a7a',
    desc: 'Il fabrique le comté dans ses fruitières, affine le mont-d\'or dans sa boîte d\'épicéa, fume la saucisse de Morteau et règle des montres à la seconde près autour de Besançon. Un tempérament précis et persévérant, qui aime le travail bien fait et le froid sec.',
    t: { rig: 0.95, con: 0.92, ord: 0.92, fia: 0.9, inc: 0.12, vhe: 0.35, inf: 0.2, aud: 0.25, det: 0.85, vst: 0.2 } },
  { name: 'La Drôme', by: '26 · Auvergne-Rhône-Alpes', tag: 'Nougat, lavande et utopies', color: '#d98c3a',
    desc: 'Montélimar fait le nougat, Romans les ravioles, Die la clairette qui pétille et Nyons les olives noires. Ajoutez le Vercors et le Palais idéal que le facteur Cheval a bâti seul, caillou après caillou. Un tempérament doux, un peu utopiste, qui aime les projets faits à la main.',
    t: { ide: 0.9, vun: 0.9, det: 0.8, ind: 0.75, vpo: 0.1, vac: 0.25, chg: 0.7, eng: 0.75, care: 0.8, auth: 0.2 } },
  { name: 'L\'Eure', by: '27 · Normandie', tag: 'Les nymphéas de Giverny', color: '#7fae8a',
    desc: 'C\'est à Giverny que Monet a creusé son bassin aux nymphéas et peint son pont japonais des dizaines de fois. Au-dessus des Andelys, le Château-Gaillard de Richard Cœur de Lion regarde couler la Seine. Un tempérament esthète et tranquille, qui trouve la beauté au fond du jardin.',
    t: { ide: 0.9, ste: 0.85, vhe: 0.8, ouv: 0.75, vst: 0.25, com: 0.12, cfl: 0.1, vac: 0.3, vse: 0.8, tmp: 0.7 } },
  { name: 'L\'Eure-et-Loir', by: '28 · Centre-Val de Loire', tag: 'La flèche au milieu des blés', color: '#d8b54a',
    desc: 'On aperçoit la cathédrale de Chartres à des kilomètres, dressée au-dessus des blés de la Beauce, et ses vitraux gardent un bleu que personne n\'a su refaire. À Illiers-Combray, Proust a trempé sa madeleine. Un tempérament grave et droit, qui aime les grands horizons et les belles choses anciennes.',
    t: { sanc: 0.92, vtr: 0.9, tmp: 0.9, rig: 0.8, inf: 0.1, vst: 0.15, soc: 0.25, lib: 0.3, chg: 0.1, auth: 0.75 } },
  { name: 'Le Finistère', by: '29 · Bretagne', tag: 'Au bout du monde, face au vent', color: '#1d4e89',
    desc: 'Son nom veut dire la fin de la terre : pointe du Raz, phares battus par les vagues, crêpes au froment et kouign-amann de Douarnenez. L\'été, les Vieilles Charrues font danser Carhaix. Un tempérament têtu et résistant, qui aime les tempêtes et ne craint pas la pluie.',
    t: { det: 0.95, com: 0.85, opn: 0.85, san: 0.85, thr: 0.2, vse: 0.2, ind: 0.8, dip: 0.25, loy: 0.85, inc: 0.85 } },
  { name: 'Le Gard', by: '30 · Occitanie', tag: 'Arènes, pont romain et féria', color: '#c05a2a',
    desc: 'Le pont du Gard enjambe le Gardon depuis deux mille ans, Nîmes remplit ses arènes pour la féria et sert la brandade de morue, et les Cévennes offrent leurs vallées de châtaigniers. Un tempérament festif et bâtisseur, qui sait faire la fête au milieu des monuments.',
    t: { soc: 0.92, inf: 0.88, vhe: 0.85, vtr: 0.82, col: 0.85, ste: 0.2, vig: 0.2, ind: 0.2, vsd: 0.3, loy: 0.8 } },
  { name: 'La Haute-Garonne', by: '31 · Occitanie', tag: 'Ovalie et aérospatiale', color: '#d9707a',
    desc: 'Toulouse assemble des Airbus, dessine des satellites et soutient le Stade toulousain comme une religion. Plus au sud, Luchon ouvre la porte des Pyrénées. Le tout arrosé d\'accent chantant et de cassoulet. Un tempérament ambitieux et collectif, la tête dans les étoiles et les pieds dans la mêlée.',
    t: { vac: 0.9, col: 0.88, cmp: 0.85, opt: 0.88, vis: 0.1, ouv: 0.8, rsk: 0.7, ind: 0.2, vtr: 0.3, loy: 0.85 } },
  { name: 'Le Gers', by: '32 · Occitanie', tag: 'Le bonheur est dans le pré', color: '#e0a63a',
    desc: 'Pays de d\'Artagnan, de l\'armagnac et du canard sous toutes ses formes, il laisse les tournesols tourner doucement et invite le jazz à Marciac chaque été. On y vit vieux et on y vit bien, dit-on. Un tempérament jovial et gascon, qui prend la vie par le bon bout et le repas au sérieux.',
    t: { vhe: 0.95, opt: 0.9, thr: 0.08, vac: 0.15, tmp: 0.2, ste: 0.75, rig: 0.2, vig: 0.15, soc: 0.8, cmp: 0.12 } },
  { name: 'La Gironde', by: '33 · Nouvelle-Aquitaine', tag: 'Grands vins et grande dune', color: '#7a1f3d',
    desc: 'Bordeaux fait briller ses façades de pierre blonde dans le miroir d\'eau, Saint-Émilion soigne ses coteaux, le bassin d\'Arcachon ses huîtres, et la dune du Pilat grimpe à plus de cent mètres. Le canelé fait le reste. Un tempérament élégant et assuré, qui connaît sa valeur.',
    t: { vpo: 0.85, vac: 0.88, vhe: 0.85, san: 0.82, con: 0.75, cmp: 0.8, att: 0.3, eng: 0.1, inc: 0.3, dom: 0.78 } },
  { name: 'L\'Hérault', by: '34 · Occitanie', tag: 'Joutes, huîtres et soleil étudiant', color: '#2f9fa0',
    desc: 'Montpellier déborde d\'étudiants, Sète fait jouter ses équipes sur des barques et vend la tielle au poulpe, l\'étang de Thau élève les huîtres de Bouzigues et Pézenas se souvient de Molière. Un tempérament jeune, solaire et bavard, qui aime la fête et les débats en terrasse.',
    t: { soc: 0.92, ouv: 0.88, vst: 0.85, chg: 0.8, vtr: 0.3, opt: 0.85, inc: 0.8, vse: 0.2, ord: 0.2, inf: 0.85 } },
  { name: 'L\'Ille-et-Vilaine', by: '35 · Bretagne', tag: 'Corsaires et galette-saucisse', color: '#2a4d7a',
    desc: 'Saint-Malo a vu partir ses corsaires derrière ses remparts, Cancale sert ses huîtres face à la mer, Rennes fait danser les Transmusicales et la forêt de Brocéliande garde les légendes de Merlin. Un tempérament curieux et entreprenant, entre vieilles légendes et musiques nouvelles.',
    t: { aud: 0.88, ouv: 0.85, vst: 0.82, ide: 0.8, lea: 0.78, dog: 0.1, ste: 0.25, vco: 0.25, rsk: 0.8, cmp: 0.7 } },
  { name: 'L\'Indre', by: '36 · Centre-Val de Loire', tag: 'Le Berry de George Sand', color: '#6f8a4a',
    desc: 'George Sand écrivait à Nohant au milieu de la Vallée Noire, la Brenne aligne ses étangs pleins d\'oiseaux et Valençay taille son fromage en pyramide tronquée. On y cultive la lentille verte du Berry. Un tempérament rêveur, campagnard et libre d\'esprit, fait pour les longues promenades.',
    t: { lib: 0.85, ide: 0.85, vsd: 0.88, ste: 0.8, vpo: 0.1, cmp: 0.1, auth: 0.2, soc: 0.35, vun: 0.8, emp: 0.8 } },
  { name: 'L\'Indre-et-Loire', by: '37 · Centre-Val de Loire', tag: 'Châteaux, rillettes et beau parler', color: '#b8a07a',
    desc: 'Chenonceau enjambe le Cher, Villandry taille ses jardins au cordeau et Amboise garde le tombeau de Léonard de Vinci. On dit qu\'à Tours on parle le français le plus pur, entre un verre de vouvray et une tartine de rillettes. Un tempérament cultivé, raffiné, un brin précieux.',
    t: { dip: 0.88, con: 0.85, vtr: 0.85, ord: 0.85, vhe: 0.8, cfl: 0.1, com: 0.12, vpo: 0.7, aff: 0.7, rsk: 0.2 } },
  { name: 'L\'Isère', by: '38 · Auvergne-Rhône-Alpes', tag: 'Téléphérique, noix et labos', color: '#3d6b8c',
    desc: 'Grenoble grimpe à la Bastille dans ses bulles, invente dans ses laboratoires et voit des montagnes au bout de chaque rue. Autour, l\'Alpe d\'Huez aligne ses virages et les chartreux gardent le secret de leur liqueur. Un tempérament cérébral et sportif.',
    t: { aff: 0.9, ouv: 0.9, rsk: 0.72, vac: 0.8, vst: 0.8, vtr: 0.3, soc: 0.3, emp: 0.35, det: 0.85, epi: 0.25 } },
  { name: 'Le Jura', by: '39 · Bourgogne-Franche-Comté', tag: 'Vin jaune et lacs cachés', color: '#c9a227',
    desc: 'Il laisse son vin jaune dormir six ans sous un voile de levures, fabrique des pipes à Saint-Claude, des lunettes à Morez et des jouets à Moirans, et cache des lacs et des cascades au fond de ses forêts. Pasteur est né à Dole. Un tempérament patient et artisan, qui a tout son temps.',
    t: { tmp: 0.95, ind: 0.85, rig: 0.88, ide: 0.8, cmp: 0.1, inf: 0.1, soc: 0.2, vpo: 0.1, ord: 0.8, vst: 0.25 } },
  { name: 'Les Landes', by: '40 · Nouvelle-Aquitaine', tag: 'Pins, vagues et bandas', color: '#2f8a5a',
    desc: 'L\'une des plus grandes forêts de pins d\'Europe, des vagues parfaites à Hossegor et des étés rythmés par les fêtes de Dax et les écarteurs de la course landaise, qui esquivent les vaches d\'un pas de danse. Un tempérament festif et casse-cou, qui aime le risque tant qu\'il y a une banda derrière.',
    t: { rsk: 0.92, aud: 0.9, vst: 0.9, soc: 0.88, vse: 0.12, vig: 0.12, rig: 0.2, col: 0.8, vhe: 0.85, san: 0.75 } },
  { name: 'Le Loir-et-Cher', by: '41 · Centre-Val de Loire', tag: 'Chambord et la Sologne', color: '#5f7a4a',
    desc: 'Chambord déroule son escalier à double révolution au milieu d\'une forêt close de murs, Blois raconte les rois, la Sologne cache ses étangs et ses cerfs, et Beauval fait naître des pandas. La tarte Tatin a été retournée ici. Un tempérament majestueux, secret et un peu chasseur.',
    t: { vpo: 0.85, auth: 0.8, dom: 0.75, san: 0.85, vtr: 0.85, soc: 0.3, inf: 0.2, emp: 0.3, vig: 0.8, chg: 0.15 } },
  { name: 'La Loire', by: '42 · Auvergne-Rhône-Alpes', tag: 'Le chaudron vert', color: '#1d8a3f',
    desc: 'Saint-Étienne a fabriqué armes, cycles et catalogues Manufrance, et vibre pour les Verts dans le chaudron de Geoffroy-Guichard. Elle est devenue ville du design, et la plaine du Forez affine sa fourme de Montbrison. Un tempérament ouvrier et fier, qui chante fort et ne lâche jamais.',
    t: { loy: 0.95, det: 0.92, col: 0.9, com: 0.85, cfl: 0.8, vpo: 0.12, dip: 0.2, fair: 0.88, eng: 0.8, ind: 0.2 } },
  { name: 'La Haute-Loire', by: '43 · Auvergne-Rhône-Alpes', tag: 'Lentilles, dentelle et pèlerins', color: '#4f6a3a',
    desc: 'Au Puy-en-Velay, les pèlerins partent vers Compostelle sous une chapelle perchée sur un piton volcanique, les dentellières manient leurs fuseaux et la lentille verte a gagné son appellation. On y distille aussi la verveine. Un tempérament spirituel et minutieux, qui avance pas à pas.',
    t: { sanc: 0.95, rig: 0.85, ste: 0.88, det: 0.82, vtr: 0.9, vhe: 0.2, vst: 0.25, inf: 0.15, cmp: 0.12, auth: 0.7 } },
  { name: 'La Loire-Atlantique', by: '44 · Pays de la Loire', tag: 'Sel, biscuit et machines', color: '#27a3a0',
    desc: 'Les paludiers de Guérande récoltent la fleur de sel, Nantes promène son éléphant mécanique et ses petits-beurre, Saint-Nazaire construit des paquebots géants et La Baule étire sa plage. Un tempérament inventif et ouvert, entre bricolage génial et grand large.',
    t: { ide: 0.9, ouv: 0.9, chg: 0.82, vst: 0.82, vtr: 0.2, dog: 0.08, opn: 0.1, inc: 0.85, vun: 0.8, auth: 0.2 } },
  { name: 'Le Loiret', by: '45 · Centre-Val de Loire', tag: 'Jeanne, la Loire et le vinaigre', color: '#b83a3a',
    desc: 'Chaque printemps, Orléans fête Jeanne d\'Arc, qui a libéré la ville en 1429. Le Loiret fait aussi le vinaigre d\'Orléans, la faïence de Gien, la praline de Montargis, et son pont-canal de Briare fait passer les bateaux au-dessus de la Loire. Un tempérament fidèle et bâtisseur, qui honore ses héros.',
    t: { loy: 0.9, auth: 0.8, vtr: 0.88, fia: 0.9, det: 0.8, lib: 0.3, vst: 0.2, ind: 0.25, chg: 0.15, sanc: 0.7, con: 0.8 } },
  { name: 'Le Lot', by: '46 · Occitanie', tag: 'Villages perchés et vin noir', color: '#5a2a3a',
    desc: 'Rocamadour s\'accroche à sa falaise, Saint-Cirq-Lapopie domine la rivière, le gouffre de Padirac se visite en barque sous terre et Cahors fait un vin si sombre qu\'on l\'appelait le vin noir. Un tempérament mystérieux et profond, qui cache bien ses trésors.',
    t: { ind: 0.8, inf: 0.08, soc: 0.2, sanc: 0.85, vig: 0.88, nat: 0.85, opt: 0.3, vpo: 0.2, san: 0.85, ide: 0.75, ouv: 0.7 } },
  { name: 'Le Lot-et-Garonne', by: '47 · Nouvelle-Aquitaine', tag: 'Pruneaux, fraises et bastides', color: '#6a2f5a',
    desc: 'Agen a fait du pruneau une fierté nationale, Marmande cultive la tomate, les vergers donnent fraises et noisettes et les bastides alignent leurs places à arcades. Au rugby, le SUA a du cœur. Un tempérament généreux et nourricier, dont le garde-manger est plein à craquer.',
    t: { vbe: 0.92, care: 0.9, att: 0.9, vhe: 0.8, com: 0.2, vpo: 0.1, vac: 0.3, aff: 0.12, ind: 0.2, ste: 0.75 } },
  { name: 'La Lozère', by: '48 · Occitanie', tag: 'Le grand air, sans la foule', color: '#5a6b3a',
    desc: 'C\'est le département le moins peuplé de France, et il le vit très bien : gorges du Tarn, plateaux de l\'Aubrac, loups du Gévaudan et chemin de Stevenson, qui l\'a traversé avec son ânesse Modestine. Un tempérament solitaire et sauvage, qui préfère les grands espaces aux grandes foules.',
    t: { ind: 0.95, soc: 0.05, inf: 0.08, col: 0.15, vsd: 0.9, san: 0.8, vpo: 0.1, lib: 0.85, opn: 0.75, att: 0.3 } },
  { name: 'Le Maine-et-Loire', by: '49 · Pays de la Loire', tag: 'La douceur angevine', color: '#d0b060',
    desc: 'Angers garde la tapisserie de l\'Apocalypse, Saumur fait danser les chevaux du Cadre noir et loge des champignons dans ses caves de tuffeau, et le Cointreau est né ici. Du Bellay chantait la douceur angevine. Un tempérament gracieux, discipliné et gourmand.',
    t: { con: 0.88, ord: 0.85, dip: 0.85, vhe: 0.8, ste: 0.8, cfl: 0.15, rsk: 0.2, aud: 0.25, emp: 0.75, vse: 0.85 } },
  { name: 'La Manche', by: '50 · Normandie', tag: 'Le Mont et la marée', color: '#5b7f95',
    desc: 'Elle garde le Mont-Saint-Michel au milieu des plus fortes marées d\'Europe continentale, vend des parapluies à Cherbourg et laisse le vent de la Hague décoiffer les promeneurs. Granville a vu grandir Christian Dior. Un tempérament robuste et romantique, qui aime les grands horizons.',
    t: { san: 0.88, det: 0.8, ide: 0.8, thr: 0.2, vse: 0.3, vhe: 0.3, inc: 0.85, soc: 0.3, ste: 0.7, sanc: 0.75 } },
  { name: 'La Marne', by: '51 · Grand Est', tag: 'Des bulles pour chaque occasion', color: '#e6c86a',
    desc: 'Reims a vu sacrer les rois de France, Épernay aligne ses maisons de champagne sur une avenue qui cache des kilomètres de caves, et le biscuit rose se trempe dans la coupe. Un tempérament festif et distingué, qui fait de chaque moment une célébration.',
    t: { vhe: 0.92, soc: 0.88, inf: 0.85, vpo: 0.8, vtr: 0.8, ste: 0.3, vig: 0.25, aff: 0.2, opt: 0.9, auth: 0.7 } },
  { name: 'La Haute-Marne', by: '52 · Grand Est', tag: 'Remparts et forêts', color: '#5a6a4a',
    desc: 'Langres fait le tour de ses remparts sur son promontoire, a vu naître Diderot et donne son nom à un fromage creusé en fontaine où l\'on verse du marc. Chaumont est la ville de l\'affiche, et les forêts s\'étendent au loin. Un tempérament réservé et érudit, qui se livre à qui monte jusqu\'à lui.',
    t: { aff: 0.85, ouv: 0.85, ind: 0.8, inf: 0.12, soc: 0.2, vig: 0.8, nat: 0.75, vhe: 0.3, vpo: 0.25, ide: 0.7 } },
  { name: 'La Mayenne', by: '53 · Pays de la Loire', tag: 'Le bocage tranquille', color: '#6f9a4a',
    desc: 'Des haies, des vaches, des chemins de halage le long de la rivière et une préfecture, Laval, qui accueille chaque année un salon international de la réalité virtuelle. Un tempérament modeste et travailleur, qui innove sans jamais faire de bruit.',
    t: { fia: 0.9, det: 0.82, inf: 0.08, vpo: 0.08, com: 0.12, cfl: 0.1, ste: 0.88, vse: 0.8, dom: 0.15, aff: 0.7 } },
  { name: 'La Meurthe-et-Moselle', by: '54 · Grand Est', tag: 'La place Stanislas et l\'Art nouveau', color: '#c9a24a',
    desc: 'Nancy a l\'une des plus belles places du monde, grilles rehaussées d\'or, et l\'École de Nancy, où Gallé et Daum faisaient fleurir le verre. On y croque des bergamotes et des macarons, et Baccarat taille le cristal. Un tempérament artiste et élégant, qui met du beau partout.',
    t: { ide: 0.92, vhe: 0.8, ouv: 0.8, rig: 0.8, vpo: 0.7, com: 0.2, soc: 0.7, cfl: 0.2, vtr: 0.7, vse: 0.3 } },
  { name: 'La Meuse', by: '55 · Grand Est', tag: 'Madeleines et mémoire', color: '#8a7a5a',
    desc: 'Commercy fait les madeleines, Verdun les dragées et Bar-le-Duc une confiture de groseilles épépinées une à une à la plume d\'oie. Le département garde aussi, avec gravité, la mémoire de 1916. Un tempérament délicat et fidèle, qui n\'oublie rien et soigne les petits détails.',
    t: { loy: 0.92, fia: 0.9, rig: 0.9, vtr: 0.88, tmp: 0.85, care: 0.8, vst: 0.15, aud: 0.2, inf: 0.2, vis: 0.65 } },
  { name: 'Le Morbihan', by: '56 · Bretagne', tag: 'La petite mer semée d\'îles', color: '#2a7ab0',
    desc: 'Son nom breton veut dire petite mer : un golfe semé d\'îles, des menhirs alignés à Carnac depuis des millénaires, Belle-Île qui porte bien son nom et, chaque été, le Festival interceltique de Lorient. Un tempérament mystique et navigateur, fier de sa culture et ouvert à tous ses cousins celtes.',
    t: { sanc: 0.85, vtr: 0.88, opn: 0.25, soc: 0.8, loy: 0.85, col: 0.85, vst: 0.75, dom: 0.2, cmp: 0.2, ide: 0.8 } },
  { name: 'La Moselle', by: '57 · Grand Est', tag: 'Mirabelles et frontières', color: '#d6b33a',
    desc: 'Metz a sa cathédrale surnommée la lanterne du Bon Dieu et son Centre Pompidou coiffé d\'un grand chapeau, la mirabelle a sa fête chaque été et Sarreguemines décore la faïence. Trois pays se touchent tout près, à Schengen. Un tempérament frontalier, polyglotte, fidèle et ouvert.',
    t: { opn: 0.1, dip: 0.88, fia: 0.85, loy: 0.8, con: 0.8, vun: 0.8, com: 0.25, dog: 0.15, chg: 0.3, ord: 0.8 } },
  { name: 'La Nièvre', by: '58 · Bourgogne-Franche-Comté', tag: 'Le Morvan, la Loire et le circuit', color: '#3f6a5a',
    desc: 'Le Morvan déroule ses forêts et ses lacs, la Loire coule sauvage le long de Nevers qui peint sa faïence bleue, Pouilly fait son fumé et le circuit de Magny-Cours fait rugir les moteurs. Un tempérament tranquille en apparence, qui aime quand même la vitesse de temps en temps.',
    t: { vst: 0.82, rsk: 0.72, ste: 0.78, inf: 0.15, soc: 0.3, con: 0.2, ord: 0.25, vpo: 0.2, san: 0.8, thr: 0.2 } },
  { name: 'Le Nord', by: '59 · Hauts-de-France', tag: 'Beffrois, frites et carnaval', color: '#e8c63a',
    desc: 'La braderie de Lille remplit les rues de chineurs et de moules-frites, Dunkerque fait son carnaval en chantant sous les harengs, les beffrois sonnent et le maroilles parfume la cuisine. Dehors il pleut, dedans il fait chaud. Un tempérament chaleureux, franc et ultra-accueillant.',
    t: { att: 0.95, soc: 0.95, emp: 0.9, col: 0.9, vbe: 0.9, vpo: 0.1, nat: 0.08, thr: 0.25, cmp: 0.12, com: 0.75 } },
  { name: 'L\'Oise', by: '60 · Hauts-de-France', tag: 'Chantilly, forêts et Astérix', color: '#5a8a4a',
    desc: 'Chantilly a donné son nom à une crème et fait galoper les pur-sang devant son château, Compiègne et Pierrefonds cachent des forêts de conte, Beauvais a le chœur gothique le plus haut du monde et le Parc Astérix rit juste à côté. Un tempérament noble et joueur à la fois.',
    t: { vst: 0.85, inf: 0.82, vpo: 0.78, vtr: 0.75, rig: 0.25, epi: 0.15, dog: 0.15, thr: 0.2, opt: 0.85, soc: 0.8 } },
  { name: 'L\'Orne', by: '61 · Normandie', tag: 'Le berceau du camembert', color: '#8aa060',
    desc: 'C\'est dans le village de Camembert qu\'on situe la naissance du fameux fromage. L\'Orne élève aussi les chevaux au haras du Pin et les percherons dans le Perche, et fait la dentelle au point d\'Alençon. Un tempérament authentique et terrien, qui aime les bêtes et les choses vraies.',
    t: { vtr: 0.9, opn: 0.85, fia: 0.85, epi: 0.08, vst: 0.2, ouv: 0.3, care: 0.8, att: 0.8, vpo: 0.15, ide: 0.2, dog: 0.3 } },
  { name: 'Le Pas-de-Calais', by: '62 · Hauts-de-France', tag: 'Caps, terrils et sang et or', color: '#c8102e',
    desc: 'La Côte d\'Opale ouvre ses caps Blanc-Nez et Gris-Nez face à l\'Angleterre, Boulogne est le premier port de pêche de France, les terrils se sont couverts de verdure et Bollaert chante pour le RC Lens. Un tempérament solidaire, fier et increvable.',
    t: { col: 0.95, loy: 0.92, det: 0.92, san: 0.85, ind: 0.1, vpo: 0.1, cmp: 0.2, opt: 0.8, dom: 0.3, att: 0.85 } },
  { name: 'Le Puy-de-Dôme', by: '63 · Auvergne-Rhône-Alpes', tag: 'Volcans, pneus et rugby', color: '#e6b800',
    desc: 'La chaîne des Puys aligne ses volcans endormis, inscrits au patrimoine mondial, Clermont fait rouler le monde sur ses pneus et vibre en jaune et bleu pour l\'ASM. Saint-nectaire et eau de Volvic complètent le tableau. Un tempérament solide, inventif et loyal.',
    t: { fia: 0.9, loy: 0.88, det: 0.85, ouv: 0.75, vac: 0.8, inf: 0.25, com: 0.25, vhe: 0.35, san: 0.85, aff: 0.75 } },
  { name: 'Les Pyrénées-Atlantiques', by: '64 · Nouvelle-Aquitaine', tag: 'Béret, piment et pelote', color: '#d7263d',
    desc: 'D\'un côté le Pays basque, ses frontons de pelote, son piment d\'Espelette et les vagues de Biarritz ; de l\'autre le Béarn, Pau et le château où naquit Henri IV. Et partout le jambon de Bayonne et le fromage de brebis. Un tempérament fier, joueur, attaché à sa langue.',
    t: { loy: 0.92, vtr: 0.92, opn: 0.92, vst: 0.8, col: 0.88, cmp: 0.82, ouv: 0.3, rsk: 0.75, aud: 0.8, vco: 0.3 } },
  { name: 'Les Hautes-Pyrénées', by: '65 · Occitanie', tag: 'Du Tourmalet au pic du Midi', color: '#4a7ab0',
    desc: 'Les cyclistes souffrent dans le Tourmalet, les astronomes scrutent le ciel au pic du Midi, le cirque de Gavarnie déploie ses cascades et Lourdes accueille des millions de pèlerins. À Tarbes, le haricot a son label. Un tempérament élevé, dans tous les sens du mot.',
    t: { sanc: 0.9, det: 0.92, tmp: 0.85, vhe: 0.2, vst: 0.75, inf: 0.2, vse: 0.3, ide: 0.82, san: 0.8 } },
  { name: 'Les Pyrénées-Orientales', by: '66 · Occitanie', tag: 'Catalane sous le Canigou', color: '#e8a800',
    desc: 'Collioure a inspiré les fauves et sale ses anchois, le train jaune grimpe vers la Cerdagne, la sardane se danse sur les places et le Canigou veille, montagne sacrée des Catalans. Le soleil y est chez lui. Un tempérament coloré, fier de son identité et tourné vers le sud.',
    t: { vtr: 0.88, opn: 0.85, ide: 0.8, vhe: 0.85, col: 0.85, opt: 0.85, rig: 0.25, con: 0.2, vpo: 0.2, soc: 0.8 } },
  { name: 'Le Bas-Rhin', by: '67 · Grand Est', tag: 'Choucroute et cigognes', color: '#b0413e',
    desc: 'Strasbourg allume le plus ancien marché de Noël de France au pied de sa cathédrale, les cigognes nichent sur les toits et le Haut-Kœnigsbourg domine la plaine. Choucroute, kougelhopf et bière font le reste. Un tempérament organisé et convivial, qui adore les traditions de saison.',
    t: { ord: 0.92, con: 0.88, vtr: 0.9, soc: 0.8, rig: 0.85, inc: 0.2, chg: 0.12, vhe: 0.8, lib: 0.3, col: 0.8 } },
  { name: 'Le Haut-Rhin', by: '68 · Grand Est', tag: 'Colombages et route des vins', color: '#d95f3a',
    desc: 'Colmar a sa Petite Venise fleurie, Riquewihr et Kaysersberg ressemblent à des livres d\'images, Mulhouse expose des centaines de voitures anciennes et le munster parfume la cave. Sur la route des vins, le gewurztraminer coule. Un tempérament coquet et fleuri, qui soigne sa vitrine et sa table.',
    t: { vhe: 0.88, rig: 0.8, ord: 0.85, vtr: 0.85, ide: 0.75, dom: 0.2, com: 0.2, vst: 0.3, care: 0.75, att: 0.8 } },
  { name: 'Le Rhône', by: '69 · Auvergne-Rhône-Alpes', tag: 'Bouchons, Beaujolais et lumignons', color: '#8c1c2c',
    desc: 'Lyon sert la quenelle et le tablier de sapeur dans ses bouchons, s\'illumine chaque 8 décembre et laisse Guignol taper sur le gendarme. Au nord, le Beaujolais nouveau arrive le troisième jeudi de novembre. Un tempérament gourmand et bon vivant, avec un soupçon d\'impertinence.',
    t: { vhe: 0.95, vac: 0.82, vse: 0.85, vtr: 0.8, rsk: 0.2, soc: 0.75, com: 0.7, auth: 0.25, vst: 0.35, ste: 0.7 } },
  { name: 'La Haute-Saône', by: '70 · Bourgogne-Franche-Comté', tag: 'Les mille étangs', color: '#4a7a6a',
    desc: 'Le plateau des Mille Étangs miroite entre les forêts, Le Corbusier a posé sa chapelle toute en courbes à Ronchamp, Fougerolles distille son kirsch et Jacques Brel a chanté Vesoul. Un tempérament paisible et un peu mélancolique, qui aime les lumières douces et les chansons.',
    t: { ste: 0.88, ide: 0.85, opt: 0.3, vis: 0.65, emp: 0.85, inf: 0.12, cmp: 0.1, vac: 0.2, dom: 0.1, sanc: 0.7 } },
  { name: 'La Saône-et-Loire', by: '71 · Bourgogne-Franche-Comté', tag: 'Charolais, Cluny et photographie', color: '#c9a57a',
    desc: 'Elle élève les bœufs charolais à la robe blanche, garde les vestiges de Cluny, longtemps la plus grande église du monde, et Chalon célèbre Nicéphore Niépce, inventeur de la photographie. À Louhans, le marché aux volailles est immense. Un tempérament robuste, bâtisseur et curieux.',
    t: { det: 0.85, ouv: 0.85, lea: 0.82, vac: 0.8, fia: 0.85, emp: 0.3, dom: 0.75, epi: 0.2, att: 0.3, vst: 0.6 } },
  { name: 'La Sarthe', by: '72 · Pays de la Loire', tag: 'Vingt-quatre heures sans dormir', color: '#2a5aa0',
    desc: 'Une fois par an, le monde entier regarde les voitures tourner jour et nuit sur le circuit du Mans. Le reste du temps, la Sarthe tartine ses rillettes, élève les poulets de Loué et écoute le chant grégorien à Solesmes. Un tempérament endurant, qui passe du vrombissement au silence.',
    t: { det: 0.95, cmp: 0.88, vst: 0.8, rsk: 0.8, san: 0.8, vac: 0.8, emp: 0.3, att: 0.3, ste: 0.3, vhe: 0.6 } },
  { name: 'La Savoie', by: '73 · Auvergne-Rhône-Alpes', tag: 'Fondue et glaciers', color: '#2a6ab0',
    desc: 'Val-d\'Isère, Courchevel, Tignes : ses stations comptent parmi les plus hautes du monde, la Vanoise protège bouquetins et glaciers, et le lac du Bourget s\'étend au pied des montagnes. Le soir, fondue et beaufort. Un tempérament sportif et montagnard, qui se lève tôt et redescend content.',
    t: { vst: 0.85, det: 0.85, rsk: 0.75, vhe: 0.85, soc: 0.8, col: 0.75, vtr: 0.8, epi: 0.12, ide: 0.25, ste: 0.3 } },
  { name: 'La Haute-Savoie', by: '74 · Auvergne-Rhône-Alpes', tag: 'Au pied du mont Blanc', color: '#3aa0d0',
    desc: 'Chamonix regarde le mont Blanc, le lac d\'Annecy compte parmi les plus purs d\'Europe, Évian met son eau en bouteille et la tartiflette fait fondre le reblochon. Côté vallée, l\'Arve usine des pièces de précision pour le monde entier. Un tempérament exigeant, sportif et bosseur.',
    t: { vac: 0.9, rig: 0.85, det: 0.9, cmp: 0.85, vst: 0.75, vse: 0.75, emp: 0.3, col: 0.3, inc: 0.3, vhe: 0.4 } },
  { name: 'Paris', by: '75 · Île-de-France', tag: 'La capitale qui ne dort pas', color: '#2d3a5c',
    desc: 'La tour Eiffel scintille à chaque heure, les musées ne se visitent jamais en entier, les terrasses débordent et chaque quartier se croit le centre du monde. Paris court, râle, ose et invente. Un tempérament brillant, pressé, exigeant, qui a toujours quelque chose à prouver.',
    t: { vac: 0.95, cmp: 0.92, vpo: 0.85, ste: 0.08, dom: 0.85, com: 0.85, att: 0.25, nat: 0.75, vtr: 0.25, ouv: 0.85 } },
  { name: 'La Seine-Maritime', by: '76 · Normandie', tag: 'Falaises de craie et ciel de peintre', color: '#5a8ab0',
    desc: 'Étretat dresse ses arches de craie face à la mer, Rouen a offert à Monet sa cathédrale en série, Le Havre reconstruit par Perret est inscrit au patrimoine mondial et Fécamp distille la Bénédictine. Un tempérament contrasté, lumineux et changeant comme son ciel.',
    t: { ouv: 0.85, ide: 0.85, chg: 0.8, inc: 0.9, ord: 0.2, ste: 0.25, dog: 0.1, vse: 0.25, aff: 0.3, loc: 0.75 } },
  { name: 'La Seine-et-Marne', by: '77 · Île-de-France', tag: 'Brie, château et Mickey', color: '#7a6a9a',
    desc: 'Le plus grand département d\'Île-de-France fait deux bries célèbres, de Meaux et de Melun, grimpe sur les rochers de Fontainebleau, rêve à Vaux-le-Vicomte et accueille Disneyland Paris. Provins garde ses remparts médiévaux. Un tempérament familial, qui mélange volontiers terroir et fantaisie.',
    t: { vhe: 0.85, vbe: 0.85, ide: 0.8, inc: 0.75, vst: 0.75, com: 0.15, dog: 0.12, vpo: 0.25, cmp: 0.2, opt: 0.85 } },
  { name: 'Les Yvelines', by: '78 · Île-de-France', tag: 'Versailles et les grandes allées', color: '#1f3a6a',
    desc: 'Versailles déploie sa galerie des Glaces et ses jardins à la française, Saint-Germain-en-Laye domine la Seine depuis sa terrasse et la forêt de Rambouillet abrite la Bergerie nationale. Un tempérament solennel et soigné, qui aime les bonnes manières et les perspectives bien alignées.',
    t: { ord: 0.95, con: 0.9, auth: 0.88, vpo: 0.85, vtr: 0.9, lib: 0.2, chg: 0.08, inc: 0.15, rsk: 0.15, vco: 0.9 } },
  { name: 'Les Deux-Sèvres', by: '79 · Nouvelle-Aquitaine', tag: 'La Venise verte', color: '#4a9a5a',
    desc: 'Dans le Marais poitevin, on glisse en barque sous les frênes sur des canaux couverts de lentilles d\'eau, Niort confit l\'angélique et le chabichou mûrit doucement. Le baudet du Poitou, grand âne à poils longs, est une vedette locale. Un tempérament lent, doux et un peu farceur.',
    t: { ste: 0.9, vhe: 0.8, tmp: 0.15, dom: 0.08, cmp: 0.1, vac: 0.15, inc: 0.75, rig: 0.25, att: 0.8, opt: 0.8 } },
  { name: 'La Somme', by: '80 · Hauts-de-France', tag: 'Phoques et hortillonnages', color: '#6aa0a8',
    desc: 'La baie de Somme accueille des phoques sur ses bancs de sable, Amiens cultive ses hortillonnages entre les canaux et a vu Jules Verne écrire l\'essentiel de ses romans, à l\'ombre d\'une cathédrale immense. Un tempérament curieux et naturaliste, qui observe avec patience.',
    t: { ouv: 0.9, vun: 0.88, care: 0.8, ste: 0.8, vig: 0.75, dom: 0.15, inf: 0.2, aud: 0.3, vpo: 0.1, ide: 0.75 } },
  { name: 'Le Tarn', by: '81 · Occitanie', tag: 'Brique rouge et bleu pastel', color: '#b5462f',
    desc: 'La cathédrale Sainte-Cécile d\'Albi est la plus grande église de brique du monde, Toulouse-Lautrec y est né, Cordes-sur-Ciel flotte dans la brume et le pastel a fait la fortune du pays de Cocagne. À Castres, le rugby se vit en bleu. Un tempérament artiste et fier, rouge dehors, bleu dedans.',
    t: { ide: 0.9, vac: 0.75, loy: 0.8, com: 0.75, vpo: 0.7, dip: 0.3, ste: 0.3, ouv: 0.75, vtr: 0.8, vse: 0.3 } },
  { name: 'Le Tarn-et-Garonne', by: '82 · Occitanie', tag: 'Chasselas et cloître roman', color: '#b8a04a',
    desc: 'Moissac garde l\'un des plus beaux cloîtres romans et cultive le chasselas doré, Montauban aligne ses façades de brique et honore Ingres, et le Quercy offre melons et villages perchés. Un tempérament doux, sensuel et un peu nonchalant, qui prend le temps de goûter les choses.',
    t: { vhe: 0.9, ste: 0.85, tmp: 0.2, det: 0.3, vac: 0.15, rsk: 0.2, cfl: 0.1, ide: 0.75, sanc: 0.7, vst: 0.3 } },
  { name: 'Le Var', by: '83 · Provence-Alpes-Côte d\'Azur', tag: 'Cigales, rosé et îles d\'or', color: '#e87a3a',
    desc: 'Saint-Tropez fait défiler les yachts, Porquerolles offre ses plages d\'eau claire, Toulon vibre pour le RCT et les gorges du Verdon creusent un canyon vertigineux. Le rosé de Provence se sert bien frais. Un tempérament ensoleillé, frimeur à ses heures et amoureux de l\'été.',
    t: { vhe: 0.95, vst: 0.85, inf: 0.85, tmp: 0.1, vig: 0.15, rig: 0.15, vpo: 0.75, soc: 0.85, eng: 0.1, vun: 0.25 } },
  { name: 'Le Vaucluse', by: '84 · Provence-Alpes-Côte d\'Azur', tag: 'Festival, Ventoux et papes', color: '#9a5aa0',
    desc: 'Chaque juillet, Avignon transforme ses rues en scènes de théâtre au pied du palais des Papes, le mont Ventoux défie les cyclistes, Gordes et le Luberon posent pour les photos et Châteauneuf-du-Pape remplit les verres. Un tempérament artiste et passionné, qui a le goût de la scène.',
    t: { inf: 0.95, ide: 0.95, epi: 0.78, eng: 0.8, vst: 0.85, vhe: 0.8, rig: 0.2, ste: 0.15, con: 0.15, vse: 0.2, soc: 0.85 } },
  { name: 'La Vendée', by: '85 · Pays de la Loire', tag: 'Puy du Fou et Vendée Globe', color: '#1a5a8a',
    desc: 'Le Puy du Fou rejoue l\'histoire avec des chevaux, des vikings et des milliers de bénévoles, les Sables-d\'Olonne voient partir les skippers du Vendée Globe pour un tour du monde en solitaire, et la brioche se partage le dimanche. Un tempérament entreprenant, courageux et enraciné.',
    t: { det: 0.92, aud: 0.88, vtr: 0.9, vac: 0.85, rsk: 0.8, col: 0.8, loy: 0.85, vun: 0.3, chg: 0.3, ste: 0.3 } },
  { name: 'La Vienne', by: '86 · Nouvelle-Aquitaine', tag: 'Entre roman et futur', color: '#5a4a9a',
    desc: 'Le Futuroscope invente des attractions futuristes à deux pas de Poitiers, dont Notre-Dame-la-Grande porte une façade romane sculptée comme un livre. Montmorillon est la cité de l\'écrit, et le broyé du Poitou se casse d\'un coup de poing. Un tempérament curieux, entre histoire et science-fiction.',
    t: { ouv: 0.92, vst: 0.82, vis: 0.08, opt: 0.88, ide: 0.8, dog: 0.1, epi: 0.3, aff: 0.75, thr: 0.2 } },
  { name: 'La Haute-Vienne', by: '87 · Nouvelle-Aquitaine', tag: 'Porcelaine et clafoutis', color: '#9ab0c8',
    desc: 'Limoges façonne depuis des siècles une porcelaine blanche et fine et des émaux éclatants, la vache limousine broute dans les prés vallonnés et le clafoutis garde ses noyaux, comme il se doit. Au basket, le CSP est une institution. Un tempérament délicat mais solide, fin sous des dehors rustiques.',
    t: { rig: 0.85, fia: 0.85, emp: 0.8, ide: 0.75, dom: 0.2, com: 0.25, vst: 0.3, loy: 0.85, vpo: 0.3, con: 0.75 } },
  { name: 'Les Vosges', by: '88 · Grand Est', tag: 'Sapins, myrtilles et eau pure', color: '#2f5a3f',
    desc: 'Gérardmer se reflète dans son lac, les sapins couvrent les ballons, Épinal imprime ses images colorées depuis deux siècles, Vittel et Contrexéville mettent leur eau en bouteille et la tarte aux myrtilles termine les randonnées. Un tempérament sain, simple et généreux.',
    t: { vun: 0.85, care: 0.85, vbe: 0.85, sanc: 0.8, vpo: 0.1, com: 0.2, vst: 0.35, cmp: 0.12, ste: 0.8, dog: 0.3 } },
  { name: 'L\'Yonne', by: '89 · Bourgogne-Franche-Comté', tag: 'Chablis, Vézelay et château en chantier', color: '#b0a060',
    desc: 'Chablis fait son vin blanc minéral, la basilique de Vézelay attire les marcheurs depuis le Moyen Âge et, à Guédelon, des bâtisseurs élèvent un château fort avec les techniques du XIIIe siècle. Colette a grandi en Puisaye. Un tempérament obstiné, patient et bricoleur.',
    t: { det: 0.92, tmp: 0.95, rig: 0.8, ide: 0.8, vst: 0.3, inf: 0.2, dom: 0.2, vac: 0.3, ouv: 0.75, sanc: 0.6 } },
  { name: 'Le Territoire de Belfort', by: '90 · Bourgogne-Franche-Comté', tag: 'Le lion qui ne recule pas', color: '#a06a3a',
    desc: 'Petit par la taille, grand par le caractère : le Lion sculpté par Bartholdi sous la citadelle rappelle que Belfort n\'a pas été prise en 1870-1871, et les Eurockéennes font trembler le lac du Malsaucy chaque été. Un tempérament coriace, qui rugit plus fort que sa taille.',
    t: { com: 0.92, cfl: 0.92, det: 0.92, san: 0.85, dom: 0.85, dip: 0.2, ste: 0.2, thr: 0.7, vse: 0.3, loy: 0.8 } },
  { name: 'L\'Essonne', by: '91 · Île-de-France', tag: 'Labos, cresson et forêts', color: '#3a8ab0',
    desc: 'Le plateau de Saclay aligne laboratoires et grandes écoles, Méréville cultive le cresson dans ses eaux claires, Milly-la-Forêt fait pousser les plantes médicinales et Jean Cocteau y a décoré une chapelle. Un tempérament studieux, qui cherche la réponse, puis la question suivante.',
    t: { aff: 0.95, ouv: 0.9, rig: 0.85, epi: 0.15, inf: 0.2, dog: 0.1, vtr: 0.25, vac: 0.8, att: 0.3, vig: 0.7 } },
  { name: 'Les Hauts-de-Seine', by: '92 · Île-de-France', tag: 'Tours de verre et parcs royaux', color: '#5a6a8a',
    desc: 'La Défense aligne ses tours autour de la Grande Arche, la Seine musicale vogue sur l\'île Seguin et, tout près, le domaine de Saint-Cloud et la Malmaison de Joséphine offrent leurs allées. Sèvres fait la porcelaine depuis Louis XV. Un tempérament ambitieux et policé, efficace et flâneur à la fois.',
    t: { vac: 0.95, vpo: 0.85, con: 0.85, ord: 0.85, cmp: 0.85, vun: 0.25, eng: 0.1, emp: 0.3, rsk: 0.4, vse: 0.8 } },
  { name: 'La Seine-Saint-Denis', by: '93 · Île-de-France', tag: 'Rois, stade et puces', color: '#e0503a',
    desc: 'La basilique de Saint-Denis garde les tombeaux des rois de France, le Stade de France chante les grands soirs, les puces de Saint-Ouen font chiner le monde entier et le village des Jeux de 2024 s\'y est installé. Un tempérament jeune, créatif et plein d\'énergie, qui parle toutes les langues.',
    t: { vst: 0.9, chg: 0.88, opn: 0.05, ide: 0.85, soc: 0.85, vtr: 0.3, det: 0.85, con: 0.2, inc: 0.8, dog: 0.15 } },
  { name: 'Le Val-de-Marne', by: '94 · Île-de-France', tag: 'Guinguettes et marché de Rungis', color: '#c07a3a',
    desc: 'Rungis, le plus grand marché de produits frais du monde, s\'éveille quand la ville dort, les guinguettes des bords de Marne font encore tourner les danseurs à Nogent et Joinville, et le château de Vincennes monte la garde. Un tempérament noctambule, travailleur et guincheur.',
    t: { soc: 0.88, vhe: 0.82, det: 0.8, fia: 0.8, att: 0.8, vpo: 0.2, ord: 0.3, tmp: 0.3, inf: 0.8, rig: 0.35 } },
  { name: 'Le Val-d\'Oise', by: '95 · Île-de-France', tag: 'Sur les pas de Van Gogh', color: '#4a6ab0',
    desc: 'Auvers-sur-Oise a vu Van Gogh peindre plus de soixante-dix toiles en quelques semaines, l\'abbaye de Royaumont accueille concerts et artistes, le château d\'Écouen expose la Renaissance et Enghien fait tourner la roulette près de son lac. Un tempérament sensible et artiste, épris des lumières du soir.',
    t: { ide: 0.95, emp: 0.92, vun: 0.8, san: 0.2, opt: 0.25, ord: 0.2, vpo: 0.15, thr: 0.75, att: 0.85, vis: 0.75 } },
  { name: 'La Guadeloupe', by: '971 · Guadeloupe', tag: 'L\'île papillon', color: '#1aa36a',
    desc: 'Ses deux ailes, Grande-Terre et Basse-Terre, dessinent un papillon, la Soufrière fume au-dessus de la forêt, le gwoka rythme les soirées et le colombo embaume les cuisines. Marie-Galante et les Saintes complètent l\'archipel. Un tempérament vibrant, festif et fier de sa culture.',
    t: { inf: 0.92, soc: 0.9, vhe: 0.88, vtr: 0.85, att: 0.88, loy: 0.82, con: 0.12, ord: 0.15, vig: 0.2, ste: 0.3 } },
  { name: 'La Martinique', by: '972 · Martinique', tag: 'L\'île aux fleurs', color: '#d0305a',
    desc: 'Les anciens l\'appelaient Madinina, l\'île aux fleurs : la montagne Pelée veille au nord, les distilleries font un rhum agricole d\'appellation d\'origine et le ti-punch se prépare chacun pour soi. Aimé Césaire y a écrit une poésie immense. Un tempérament fier, lettré et chaleureux.',
    t: { ide: 0.88, loy: 0.85, vtr: 0.85, com: 0.8, fair: 0.85, eng: 0.75, att: 0.85, vhe: 0.75, con: 0.25, dip: 0.3 } },
  { name: 'La Guyane', by: '973 · Guyane', tag: 'La forêt et les fusées', color: '#2a8a3a',
    desc: 'Couverte à plus de 90 % de forêt amazonienne, elle voit des tortues luths pondre sur ses plages et des fusées décoller de Kourou vers l\'espace. Son carnaval, avec ses touloulous masquées, dure des semaines. Un tempérament immense, sauvage et plein de contrastes.',
    t: { vst: 0.92, aud: 0.88, ouv: 0.88, rsk: 0.88, vun: 0.85, inc: 0.9, vse: 0.15, ord: 0.15, con: 0.12, vtr: 0.4 } },
  { name: 'La Réunion', by: '974 · La Réunion', tag: 'Volcan, cirques et cari', color: '#e05a2a',
    desc: 'Le piton de la Fournaise gronde régulièrement, les cirques de Mafate, Cilaos et Salazie se parcourent à pied, le Grand Raid traverse l\'île en une course folle et le maloya fait vibrer les soirées. Le cari mijote dans toutes les marmites. Un tempérament métissé, endurant et chaleureux.',
    t: { det: 0.92, att: 0.88, opn: 0.1, dog: 0.1, vst: 0.8, col: 0.85, vbe: 0.85, vpo: 0.15, emp: 0.8, ind: 0.3 } },
  { name: 'Mayotte', by: '976 · Mayotte', tag: 'Le lagon aux tortues', color: '#1ab0b0',
    desc: 'Son lagon, l\'un des plus grands du monde, accueille tortues, dauphins et baleines à bosse, l\'ylang-ylang parfume l\'île et les femmes se protègent du soleil avec le msindzano, un masque de bois de santal. Un tempérament serein, parfumé et tourné vers la mer.',
    t: { ste: 0.85, sanc: 0.85, vtr: 0.88, vun: 0.85, col: 0.85, att: 0.8, vpo: 0.15, cmp: 0.12, vst: 0.35, ind: 0.2 } },
];

window.PRISME_DEPTS = { DEPARTMENTS_FR };
