/* ============================================================
   PRISME — « Si tu étais un plat »
   ------------------------------------------------------------
   Même principe que les animaux, les films et les morceaux : ce
   n'est pas une question de goût — Prisme ne sait pas ce que tu
   aimes. Ce qui est décrit, c'est le tempérament du plat : son
   rapport au temps, à la technique, au partage, à la démonstration.
     name = le plat, by = origine, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const DISHES = [
  { name: 'Le pot-au-feu', by: 'France · plat de famille', tag: 'Le temps fait le travail', color: '#9a6b3f',
    desc: 'Il mijote des heures sans qu\'on y touche, et tout ce qu\'on y met finit par se comprendre. Rien n\'y est spectaculaire : le bouillon, la viande et les légumes sortent ensemble, servis dans le plat où ils ont cuit. C\'est la cuisine de ceux qui savent attendre et qui nourrissent beaucoup de monde d\'un coup.',
    t: { tmp: 0.95, fia: 0.95, col: 0.9, care: 0.9, vtr: 0.9, san: 0.9, ste: 0.9, vac: 0.15, opn: 0.9, emp: 0.8 } },
  { name: 'Le bœuf bourguignon', by: 'France · Bourgogne', tag: 'La patience récompensée', color: '#7a2f2f',
    desc: 'On le commence la veille et il devient meilleur le lendemain, ce qui résume assez bien sa philosophie. La technique est simple mais ne pardonne pas l\'impatience : trop vite, la viande reste dure. Il se partage en grande quantité et ne cherche jamais à impressionner.',
    t: { tmp: 0.95, rig: 0.8, col: 0.9, vtr: 0.9, fia: 0.9, care: 0.85, det: 0.85, san: 0.85, vac: 0.3, opn: 0.85 } },
  { name: 'Le couscous', by: 'Maghreb · plat du vendredi', tag: 'On en fait toujours trop', color: '#d8a03c',
    desc: 'Il demande une matinée, trois cuissons séparées et un plat assez grand pour tout le monde, y compris ceux qui n\'étaient pas prévus. Chaque famille a sa version et la défend. C\'est le plat de l\'hospitalité qui ne se pose pas la question du nombre.',
    t: { col: 0.98, care: 0.95, soc: 0.9, vtr: 0.9, tmp: 0.85, emp: 0.85, vbe: 0.9, fia: 0.9, det: 0.85, vpo: 0.15 } },
  { name: 'La pizza margherita', by: 'Italie · Naples', tag: 'Trois ingrédients, aucune cachette', color: '#d64533',
    desc: 'Tomate, mozzarella, basilic : il n\'y a nulle part où dissimuler une erreur. La pâte se prépare la veille, cuit quatre-vingt-dix secondes, et tout se joue là. C\'est la simplicité obtenue par la maîtrise, pas par la facilité.',
    t: { rig: 0.9, ide: 0.85, vtr: 0.9, det: 0.85, fia: 0.9, soc: 0.85, ouv: 0.4, san: 0.8, vac: 0.5, opn: 0.85 } },
  { name: 'Les spaghetti carbonara', by: 'Italie · Rome', tag: 'Peu de choses, bien faites', color: '#e0b04a',
    desc: 'Œuf, fromage, guanciale, poivre — et une guerre permanente contre ceux qui ajoutent de la crème. Le geste est rapide et sans filet : trop chaud, l\'œuf coagule et tout est perdu. Il se fait en dix minutes et se rate en trois secondes.',
    t: { rig: 0.9, dog: 0.85, vtr: 0.9, det: 0.85, aud: 0.7, san: 0.6, vac: 0.6, opn: 0.9, soc: 0.75, ouv: 0.3 } },
  { name: 'Le risotto', by: 'Italie · Milan', tag: 'Il faut rester devant', color: '#e8c56a',
    desc: 'On ajoute le bouillon louche par louche et on remue sans s\'arrêter pendant vingt minutes, sinon rien ne fonctionne. Il ne supporte ni l\'attente ni le réchauffage : il se mange au moment exact où il est prêt. C\'est de l\'attention pure, transformée en plat.',
    t: { rig: 0.95, det: 0.9, fia: 0.85, tmp: 0.5, care: 0.85, san: 0.8, ord: 0.9, vac: 0.7, emp: 0.8, vhe: 0.8 } },
  { name: 'La blanquette de veau', by: 'France · plat du dimanche', tag: 'La douceur sans concession', color: '#e6dcc4',
    desc: 'Tout y est blanc, doux et lent, et pourtant chaque étape compte : la viande ne doit pas colorer, la sauce ne doit pas bouillir. Sa gentillesse apparente cache une technique exigeante. Elle réconforte sans jamais élever la voix.',
    t: { care: 0.95, rig: 0.9, san: 0.9, emp: 0.85, tmp: 0.85, vtr: 0.9, ste: 0.9, cfl: 0.05, fia: 0.9, dip: 0.85 } },
  { name: 'Le cassoulet', by: 'France · Sud-Ouest', tag: 'Il ne connaît pas la mesure', color: '#b06a2c',
    desc: 'Haricots, confit, saucisse, couenne : personne n\'a jamais prétendu que c\'était raisonnable. Trois villes se disputent la recette authentique avec une mauvaise foi remarquable. Il assomme la tablée et tout le monde en reprend.',
    t: { vhe: 0.95, col: 0.9, vtr: 0.95, dog: 0.85, det: 0.9, opn: 0.9, soc: 0.85, care: 0.85, rig: 0.4, vac: 0.3 } },
  { name: 'La raclette', by: 'Suisse et Savoie · en hiver', tag: 'Le prétexte à rester à table', color: '#d9b45b',
    desc: 'Techniquement, il s\'agit de faire fondre du fromage : tout l\'intérêt est ailleurs. On y passe trois heures, on parle, on remet un coupelle, et personne ne se lève. C\'est un plat qui n\'existe que par le groupe autour.',
    t: { soc: 0.98, col: 0.95, vhe: 0.95, care: 0.85, tmp: 0.6, rig: 0.05, opt: 0.9, att: 0.85, vac: 0.05, ouv: 0.5 } },
  { name: 'La fondue savoyarde', by: 'Savoie · en altitude', tag: 'Une casserole, dix fourchettes', color: '#e3c069',
    desc: 'Tout le monde pioche dans le même récipient, ce qui suppose une confiance minimale, et celui qui perd son pain paie une tournée. Elle se fait en cercle, jamais seul. Les règles sont plus importantes que la recette.',
    t: { col: 0.98, soc: 0.95, vtr: 0.9, vco: 0.85, vhe: 0.9, care: 0.85, att: 0.85, cfl: 0.1, opt: 0.85, ind: 0.05 } },
  { name: 'Le sushi', by: 'Japon · Edo', tag: 'Toute une vie pour un geste', color: '#c94f5a',
    desc: 'Deux ingrédients, une température de riz au degré près, et dix ans d\'apprentissage avant d\'avoir le droit de toucher le poisson. Rien n\'est décoré, rien n\'est caché. C\'est l\'exigence poussée jusqu\'à l\'endroit où elle devient invisible.',
    t: { rig: 0.98, tmp: 0.95, det: 0.95, san: 0.95, vtr: 0.95, ide: 0.9, ord: 0.95, vac: 0.7, ouv: 0.2, soc: 0.4 } },
  { name: 'Le ramen', by: 'Japon · bols de comptoir', tag: 'Un bouillon de douze heures', color: '#a8623a',
    desc: 'Le bouillon mijote une nuit entière, les nouilles cuisent quatre-vingt-dix secondes, et l\'ensemble se mange en dix minutes debout ou presque. Chaque maison garde son dosage secret. Beaucoup de travail invisible pour un moment très court.',
    t: { tmp: 0.9, rig: 0.9, det: 0.95, fia: 0.9, vac: 0.75, ind: 0.7, san: 0.8, opn: 0.8, vtr: 0.85, care: 0.8 } },
  { name: 'Les gyozas', by: 'Japon et Chine · à plusieurs mains', tag: 'On les plie ensemble', color: '#d5c9a8',
    desc: 'Les faire seul prend une éternité, les faire à quatre prend une heure et devient un moment. Chacun a sa façon de plier et on reconnaît les siens à l\'assiette. Le geste se transmet en le regardant, pas en le lisant.',
    t: { col: 0.95, soc: 0.9, rig: 0.8, care: 0.85, vtr: 0.85, det: 0.8, emp: 0.85, ord: 0.8, att: 0.85, vac: 0.4 } },
  { name: 'Le pad thaï', by: 'Thaïlande · rue de Bangkok', tag: 'Tout en même temps, très vite', color: '#e08b3c',
    desc: 'Sucré, salé, acide et piquant dans la même bouchée, exécuté en deux minutes dans un wok brûlant. L\'équilibre est précaire et se joue au dernier assaisonnement. Il n\'attend personne et ne se refait pas.',
    t: { aud: 0.9, vst: 0.9, det: 0.9, rig: 0.75, san: 0.55, ouv: 0.9, soc: 0.85, vhe: 0.9, opn: 0.4, vac: 0.7 } },
  { name: 'Le curry vert', by: 'Thaïlande · pâte pilée', tag: 'Doux, puis brûlant', color: '#5f8f4a',
    desc: 'Le lait de coco endort la méfiance pendant trois cuillères, et le piment arrive après. La pâte se pile au mortier, ingrédient par ingrédient, ce qui prend plus de temps que la cuisson. Il trompe son monde avec beaucoup de méthode.',
    t: { dip: 0.85, aud: 0.9, rig: 0.8, ouv: 0.85, vtr: 0.85, san: 0.7, thr: 0.7, det: 0.85, emp: 0.6, vhe: 0.85 } },
  { name: 'Le bibimbap', by: 'Corée · bol mélangé', tag: 'Chaque chose à sa place, puis tout ensemble', color: '#c94a3a',
    desc: 'On dispose sept préparations séparées dans un bol avec une symétrie parfaite, puis on mélange tout d\'un grand geste. L\'ordre soigneux n\'existe que pour être détruit. C\'est l\'organisation au service du plaisir, pas de la vitrine.',
    t: { ord: 0.9, ouv: 0.9, care: 0.85, col: 0.8, vhe: 0.85, rig: 0.8, soc: 0.8, chg: 0.8, opt: 0.85, emp: 0.8 } },
  { name: 'Le kimchi', by: 'Corée · jarre enterrée', tag: 'Il travaille sans qu\'on le voie', color: '#c03b2b',
    desc: 'On le prépare une fois et il fermente pendant des mois, en changeant de goût chaque semaine. Toute la famille s\'y met le même jour, en quantité. Ce qui paraît immobile est en train de se transformer en permanence.',
    t: { tmp: 0.98, vtr: 0.95, col: 0.9, det: 0.9, fia: 0.9, chg: 0.7, rig: 0.85, care: 0.8, san: 0.85, vac: 0.2 } },
  { name: 'Les tacos al pastor', by: 'Mexique · broche verticale', tag: 'La rue à son meilleur', color: '#d9552f',
    desc: 'Viande marinée qui tourne depuis des heures, ananas, coriandre, et trois tortillas empilées parce qu\'une seule ne tient pas. On les mange debout, à trois heures du matin, sans assiette. Ils n\'ont jamais cherché à être servis à table.',
    t: { soc: 0.9, vhe: 0.95, aud: 0.85, vst: 0.85, col: 0.85, det: 0.85, opt: 0.9, vac: 0.2, rig: 0.4, vtr: 0.85 } },
  { name: 'Le guacamole', by: 'Mexique · molcajete', tag: 'Il ne supporte pas d\'attendre', color: '#6f9c4a',
    desc: 'Écrasé au mortier avec de l\'oignon, du citron et du piment, il noircit dans l\'heure et il faut donc le faire au dernier moment. Sa recette tient en une phrase et provoque pourtant des disputes. Frais, immédiat, sans conservation possible.',
    t: { vst: 0.85, soc: 0.9, vhe: 0.9, det: 0.7, rig: 0.5, ouv: 0.75, opt: 0.85, tmp: 0.1, dog: 0.7, care: 0.75 } },
  { name: 'Le chili con carne', by: 'Texas · gamelle de cow-boy', tag: 'Il réchauffe et il dure', color: '#a83a2a',
    desc: 'Prévu pour nourrir beaucoup de monde longtemps, il se bonifie au réfrigérateur et se transporte partout. Chacun règle le piment à sa mesure et prétend que sa version est la bonne. Robuste, généreux, pas raffiné pour un sou.',
    t: { fia: 0.9, col: 0.9, det: 0.9, vhe: 0.85, care: 0.85, vac: 0.2, opn: 0.8, soc: 0.85, rig: 0.4, tmp: 0.8 } },
  { name: 'Le burger maison', by: 'États-Unis · au comptoir', tag: 'Efficace et assumé', color: '#b5622f',
    desc: 'Tout est dans l\'équilibre entre le pain, la viande et le gras, et il se mange avec les mains sans se poser de question. Il n\'a pas de prétention et remplit parfaitement son contrat. Le débat sur la cuisson est éternel.',
    t: { vhe: 0.9, soc: 0.85, aud: 0.8, fia: 0.85, opt: 0.85, det: 0.8, rig: 0.5, vac: 0.5, cmp: 0.7, ouv: 0.6 } },
  { name: 'Le hot-dog de stade', by: 'États-Unis · debout', tag: 'Deux minutes, et on repart', color: '#c9803a',
    desc: 'Il ne cherche ni la finesse ni la durée : il remplit un creux entre deux actions et il le fait bien. On le mange en marchant, en parlant d\'autre chose. Sa valeur tient entièrement au contexte.',
    t: { vst: 0.85, soc: 0.85, vhe: 0.85, tmp: 0.05, rig: 0.15, aud: 0.75, det: 0.6, opt: 0.85, vac: 0.15, ord: 0.2 } },
  { name: 'Le poulet rôti du dimanche', by: 'France · sortie de four', tag: 'L\'odeur avant le plat', color: '#c98a3a',
    desc: 'Il embaume toute la maison une heure avant d\'être servi, et le meilleur morceau se vole directement dans le plat. Il n\'a besoin d\'aucune technique compliquée, seulement d\'un peu de patience et de beurre. Tout le monde a son rituel avec lui.',
    t: { care: 0.95, vtr: 0.9, fia: 0.95, col: 0.9, soc: 0.85, san: 0.85, att: 0.9, rig: 0.5, opn: 0.85, emp: 0.8 } },
  { name: 'Le gratin dauphinois', by: 'France · Dauphiné', tag: 'Lent, crémeux, inflexible', color: '#e0cfa0',
    desc: 'Des pommes de terre, de la crème, de l\'ail — et surtout pas de fromage, ce qui déclenche des conflits familiaux durables. Il cuit une heure et demie à feu doux sans qu\'on puisse accélérer. Il accompagne tout et ne se laisse pas modifier.',
    t: { dog: 0.85, vtr: 0.95, tmp: 0.9, fia: 0.9, rig: 0.8, care: 0.85, opn: 0.9, san: 0.85, ouv: 0.15, ste: 0.9 } },
  { name: 'La tartiflette', by: 'Savoie · après le ski', tag: 'Elle ne s\'excuse de rien', color: '#d8a84b',
    desc: 'Reblochon, lardons, crème et pommes de terre : personne n\'a prévu de faire léger. Inventée pour écouler du fromage, elle a parfaitement réussi sa reconversion. Elle est bruyante, grasse et convaincue d\'avoir raison.',
    t: { vhe: 0.98, soc: 0.9, col: 0.85, opt: 0.9, aud: 0.8, care: 0.8, rig: 0.15, vac: 0.2, vtr: 0.8, det: 0.75 } },
  { name: 'La soupe à l\'oignon', by: 'France · fin de nuit', tag: 'Elle répare doucement', color: '#a87a3c',
    desc: 'Des oignons caramélisés pendant quarante minutes, du bouillon, du pain et du fromage gratiné : rien de coûteux, beaucoup de temps. Elle se sert tard, à ceux qui en ont besoin. C\'est un plat de réconfort déguisé en entrée.',
    t: { care: 0.95, tmp: 0.9, emp: 0.9, fia: 0.9, vtr: 0.85, san: 0.85, ste: 0.9, vac: 0.1, soc: 0.7, opt: 0.7 } },
  { name: 'Le croque-monsieur', by: 'France · brasserie', tag: 'Simple, et toujours là', color: '#d9b06a',
    desc: 'Deux tranches, du jambon, de la béchamel : il n\'a jamais prétendu être autre chose. On le commande quand on ne veut pas réfléchir, et il ne déçoit jamais vraiment. Sa fiabilité est sa seule ambition.',
    t: { fia: 0.95, vse: 0.9, ste: 0.9, san: 0.85, vac: 0.1, rig: 0.6, opn: 0.85, soc: 0.6, care: 0.75, vst: 0.1 } },
  { name: 'La quiche lorraine', by: 'France · Lorraine', tag: 'Elle se mange à toute heure', color: '#d3a962',
    desc: 'Chaude, tiède ou froide, à midi ou à minuit, elle s\'adapte sans jamais changer de nature. La pâte doit être cuite à blanc, sinon tout est détrempé — c\'est sa seule exigence. Discrète, pratique, indémodable.',
    t: { fia: 0.95, ste: 0.9, vtr: 0.85, care: 0.85, rig: 0.7, san: 0.85, opn: 0.8, vse: 0.85, soc: 0.7, vac: 0.2 } },
  { name: 'La ratatouille', by: 'France · Provence', tag: 'Chacun cuit séparément', color: '#c04a3a',
    desc: 'Les puristes cuisent chaque légume à part avant de les réunir, parce que tout mélanger donne une bouillie. Elle demande du temps et de l\'attention pour un résultat qui a l\'air simple. Elle est meilleure le lendemain.',
    t: { rig: 0.85, tmp: 0.85, care: 0.85, ide: 0.8, vun: 0.85, det: 0.8, vtr: 0.85, san: 0.85, ord: 0.85, vac: 0.3 } },
  { name: 'La bouillabaisse', by: 'France · Marseille', tag: 'Un protocole, pas une recette', color: '#d9772f',
    desc: 'Il y a une charte, une liste de poissons obligatoires et un ordre de service — le bouillon d\'abord, la chair ensuite. Les Marseillais surveillent tout ça de très près. Ce qui était un plat de pêcheurs est devenu une institution.',
    t: { vtr: 0.95, dog: 0.9, rig: 0.9, ord: 0.9, col: 0.85, opn: 0.9, det: 0.85, vco: 0.85, auth: 0.8, vac: 0.6 } },
  { name: 'Le tajine', by: 'Maroc · plat en terre', tag: 'Le couvercle fait le travail', color: '#c98a2f',
    desc: 'La vapeur tourne sous le cône pendant deux heures et redescend sur la viande, sans qu\'on ait besoin d\'intervenir. Sucré et salé s\'y rencontrent sans se gêner. Il demande surtout de savoir ne pas soulever le couvercle.',
    t: { tmp: 0.95, san: 0.9, vtr: 0.9, care: 0.85, fia: 0.9, col: 0.85, ouv: 0.75, det: 0.8, ste: 0.9, rig: 0.7 } },
  { name: 'Le hummus', by: 'Levant · au centre de la table', tag: 'Tout le monde pioche dedans', color: '#d9c58a',
    desc: 'Pois chiches, tahini, citron : la recette tient en trois lignes et fait l\'objet de querelles régionales très sérieuses. Il se mange au centre, au pain, sans couverts et sans parts individuelles. Il suppose qu\'on s\'entende.',
    t: { col: 0.95, soc: 0.9, vtr: 0.9, dog: 0.7, care: 0.85, vbe: 0.85, emp: 0.8, rig: 0.7, san: 0.8, vac: 0.3 } },
  { name: 'Le falafel', by: 'Levant · friture de rue', tag: 'Croustillant dehors, tendre dedans', color: '#7d9440',
    desc: 'Il faut de vrais pois chiches trempés la veille et une friture très chaude, sinon tout se désagrège dans l\'huile. Il se mange dans du pain, debout, en se salissant les mains. Sa rusticité est parfaitement maîtrisée.',
    t: { fia: 0.85, det: 0.85, vtr: 0.85, soc: 0.85, rig: 0.8, aud: 0.75, vhe: 0.85, opt: 0.8, vac: 0.3, col: 0.8 } },
  { name: 'Le kebab de fin de soirée', by: 'Turquie et partout ailleurs', tag: 'Il ne juge personne', color: '#b5702f',
    desc: 'Il est là quand tout est fermé, il ne pose pas de question et il fait exactement ce qu\'on attend de lui. Personne ne le commande en pleine forme. Sa générosité est brute et parfaitement sincère.',
    t: { fia: 0.9, soc: 0.85, vhe: 0.95, care: 0.8, emp: 0.7, vac: 0.05, rig: 0.15, opt: 0.8, aud: 0.75, san: 0.7 } },
  { name: 'La paella', by: 'Espagne · Valence', tag: 'Un plat, un feu, une foule', color: '#e2a33a',
    desc: 'Elle se fait dehors, dans une poêle immense, pour trente personnes, et la croûte de riz au fond est ce qu\'on se dispute. Y mettre du chorizo est considéré comme une offense. Elle transforme un repas en événement.',
    t: { col: 0.95, soc: 0.95, dog: 0.85, vtr: 0.9, det: 0.85, lea: 0.8, care: 0.85, vac: 0.6, rig: 0.75, opn: 0.85 } },
  { name: 'La tortilla', by: 'Espagne · à toute heure', tag: 'Deux ingrédients, mille débats', color: '#d9b455',
    desc: 'Pommes de terre et œufs — avec ou sans oignon, question qui divise le pays entier. Le retournement de la poêle est le seul moment risqué et il se rate régulièrement. Elle se mange chaude, froide, en tapas ou en repas.',
    t: { fia: 0.9, vtr: 0.9, dog: 0.8, soc: 0.85, ste: 0.85, san: 0.7, rig: 0.7, care: 0.8, opn: 0.85, vac: 0.3 } },
  { name: 'Le jambon-beurre', by: 'France · sur un banc', tag: 'Rien à ajouter', color: '#d8c39a',
    desc: 'Du pain, du beurre, du jambon : toute tentative d\'amélioration le dégrade. C\'est le sandwich le plus vendu du pays et le moins commenté. Sa force est de ne rien tenter.',
    t: { ide: 0.9, fia: 0.95, vtr: 0.9, rig: 0.8, vac: 0.05, san: 0.9, ste: 0.9, dog: 0.75, ouv: 0.1, opn: 0.9 } },
  { name: 'Le steak-frites', by: 'France · brasserie', tag: 'On sait exactement ce qu\'on obtient', color: '#a8562f',
    desc: 'Aucune surprise, aucune déception : la cuisson demandée, des frites, et c\'est tout. Il traverse les modes sans bouger d\'un millimètre. Le commander est un choix de tranquillité.',
    t: { fia: 0.95, vse: 0.9, vtr: 0.9, san: 0.85, ste: 0.9, rig: 0.7, vst: 0.05, opn: 0.9, vac: 0.4, ouv: 0.15 } },
  { name: 'Le magret de canard', by: 'France · Sud-Ouest', tag: 'La cuisson au degré près', color: '#8a3a2f',
    desc: 'On quadrille la graisse, on démarre à froid, on surveille le rosé : deux minutes de trop et tout est perdu. Il se tranche avec cérémonie et se présente en éventail. C\'est de la maîtrise qui aime être vue.',
    t: { rig: 0.9, vac: 0.85, det: 0.9, inf: 0.8, san: 0.8, vtr: 0.85, cmp: 0.75, ord: 0.85, soc: 0.7, vhe: 0.85 } },
  { name: 'Le soufflé au fromage', by: 'France · haute tension', tag: 'Il retombe si on hésite', color: '#e6c579',
    desc: 'Il monte magnifiquement et s\'effondre dans la minute où on ouvre le four trop tôt. Tout est dans le timing et personne ne peut l\'attendre. Il exige que la table soit prête avant lui.',
    t: { rig: 0.95, thr: 0.85, det: 0.9, vac: 0.85, ord: 0.9, san: 0.4, inf: 0.85, tmp: 0.3, aud: 0.8, emp: 0.6 } },
  { name: 'Le bœuf Wellington', by: 'Royaume-Uni · grande occasion', tag: 'La démonstration technique', color: '#7a4a2f',
    desc: 'Duxelles, crêpe, pâte feuilletée, cuisson au thermomètre : il y a six façons de le rater et une de le réussir. On le tranche devant les invités, et la coupe est le verdict. Il n\'existe que pour être jugé.',
    t: { rig: 0.98, vac: 0.95, det: 0.95, ord: 0.95, inf: 0.85, cmp: 0.85, thr: 0.8, san: 0.75, vpo: 0.7, ouv: 0.5 } },
  { name: 'Le fish and chips', by: 'Royaume-Uni · dans du papier', tag: 'Sans prétention aucune', color: '#c9a25b',
    desc: 'Pâte à frire, morue, vinaigre, et un emballage qui absorbe le gras. Il se mange dehors, souvent sous la pluie, et c\'est très bien ainsi. Il n\'a jamais essayé de passer pour de la gastronomie.',
    t: { fia: 0.9, vtr: 0.9, opn: 0.9, san: 0.8, vac: 0.1, soc: 0.8, ste: 0.85, rig: 0.5, care: 0.75, vhe: 0.85 } },
  { name: 'Le porridge du matin', by: 'Écosse · avant l\'aube', tag: 'La régularité en bol', color: '#d5c9a2',
    desc: 'Il n\'est ni excitant ni spectaculaire, il tient au corps jusqu\'à midi et il coûte trois fois rien. Ceux qui en mangent en mangent tous les jours. C\'est la discipline transformée en petit-déjeuner.',
    t: { fia: 0.98, rig: 0.9, ste: 0.95, tmp: 0.9, vco: 0.85, san: 0.9, vhe: 0.15, vac: 0.2, det: 0.9, vst: 0.05 } },
  { name: 'Le pho', by: 'Viêt Nam · au petit matin', tag: 'Un bouillon clair et très long', color: '#b5773a',
    desc: 'Le bouillon mijote toute la nuit avec des épices grillées et doit rester limpide, ce qui interdit l\'ébullition. On le mange au réveil, penché sur le bol. Beaucoup de rigueur pour un résultat qui paraît modeste.',
    t: { tmp: 0.95, rig: 0.9, san: 0.9, care: 0.85, fia: 0.9, vtr: 0.9, det: 0.9, ide: 0.8, vac: 0.4, ord: 0.85 } },
  { name: 'Le bo bun', by: 'Viêt Nam · en terrasse', tag: 'Chaud et froid dans le même bol', color: '#8fae4a',
    desc: 'Nouilles froides, viande chaude, herbes crues, cacahuètes, sauce acidulée : tout s\'oppose et l\'ensemble tient debout. On mélange soi-même à son goût. Il fait cohabiter des contraires sans effort apparent.',
    t: { ouv: 0.9, vst: 0.85, soc: 0.85, vhe: 0.85, opt: 0.85, emp: 0.8, chg: 0.75, rig: 0.6, vac: 0.4, dip: 0.8 } },
  { name: 'Le canard laqué', by: 'Chine · Pékin', tag: 'Trois jours de préparation', color: '#a8452f',
    desc: 'On sépare la peau de la chair, on gonfle, on sèche, on laque, on attend — et on découpe en cent vingt tranches devant le client. Le protocole est immuable depuis des siècles. C\'est un rituel autant qu\'un plat.',
    t: { rig: 0.98, tmp: 0.95, vtr: 0.95, ord: 0.95, vac: 0.85, det: 0.95, inf: 0.85, auth: 0.8, vpo: 0.75, ouv: 0.3 } },
  { name: 'Les dim sum', by: 'Chine · Canton', tag: 'Beaucoup de petites choses', color: '#d9b98a',
    desc: 'Des dizaines de bouchées différentes qui passent en chariot, à partager, sans ordre imposé. On goûte, on commente, on recommence pendant deux heures. Le repas est une conversation avec des interruptions comestibles.',
    t: { soc: 0.95, ouv: 0.9, col: 0.9, vst: 0.85, vhe: 0.85, com: 0.85, care: 0.8, rig: 0.6, opt: 0.85, vac: 0.4 } },
  { name: 'Le dal', by: 'Inde · quotidien', tag: 'Tous les jours, et jamais pareil', color: '#d9a83c',
    desc: 'Des lentilles, des épices tempérées dans le ghee, et une variation différente dans chaque maison et chaque région. Il ne coûte presque rien et nourrit des centaines de millions de gens. C\'est la constance avec des nuances infinies.',
    t: { fia: 0.95, vtr: 0.9, care: 0.9, col: 0.85, tmp: 0.8, ouv: 0.8, vbe: 0.9, det: 0.85, san: 0.85, vac: 0.1 } },
  { name: 'Le butter chicken', by: 'Inde · Delhi', tag: 'Il plaît à tout le monde', color: '#d9762f',
    desc: 'Doux, crémeux, légèrement sucré : il a été conçu pour ne heurter personne et il y réussit parfaitement. Les puristes lui reprochent précisément ça. Sa diplomatie est sa raison d\'être.',
    t: { dip: 0.95, care: 0.9, soc: 0.9, emp: 0.85, cfl: 0.1, opt: 0.85, fia: 0.9, vac: 0.6, ouv: 0.7, vhe: 0.9 } },
  { name: 'Le biryani', by: 'Inde · mariages', tag: 'Chaque grain doit rester entier', color: '#c9863a',
    desc: 'Riz et viande cuisent en couches scellées, sans qu\'on puisse vérifier avant d\'ouvrir. Il se fait pour cent personnes ou pas du tout. La réussite se joue sur une précision qu\'on ne contrôle pas en cours de route.',
    t: { rig: 0.9, col: 0.95, det: 0.9, vtr: 0.9, tmp: 0.85, inc: 0.7, vac: 0.75, care: 0.85, ord: 0.85, soc: 0.85 } },
  { name: 'Le poke bowl', by: 'Hawaï · sur le pouce', tag: 'Bien rangé, bien dosé', color: '#4fa3a3',
    desc: 'Chaque ingrédient a son compartiment, les proportions sont calculées et tout est frais. Il est devenu le déjeuner de ceux qui veulent bien faire sans y passer la pause. Sa sagesse est un peu appliquée.',
    t: { ord: 0.9, rig: 0.85, vse: 0.8, san: 0.85, care: 0.8, vac: 0.7, ouv: 0.75, vhe: 0.6, opt: 0.8, tmp: 0.75 } },
  { name: 'Le ceviche', by: 'Pérou · bord de mer', tag: 'Cuit par le citron, en dix minutes', color: '#4a9ec4',
    desc: 'Le poisson cru marine juste le temps qu\'il faut et devient immangeable si on l\'oublie. Tout dépend de la fraîcheur, rien de la technique. Il ne supporte aucun retard.',
    t: { vst: 0.85, aud: 0.85, rig: 0.85, san: 0.6, tmp: 0.1, det: 0.8, ide: 0.8, ouv: 0.8, vhe: 0.85, thr: 0.6 } },
  { name: 'La feijoada', by: 'Brésil · samedi midi', tag: 'Toute la journée y passe', color: '#5f3a2f',
    desc: 'Haricots noirs et morceaux de porc mijotés des heures, servis avec du riz, des oranges et de la farofa — puis plus personne ne fait rien de l\'après-midi. Elle se mange en grande tablée bruyante. C\'est un plat qui organise la journée autour de lui.',
    t: { col: 0.95, soc: 0.95, vhe: 0.95, tmp: 0.85, vtr: 0.9, care: 0.85, det: 0.85, opt: 0.85, rig: 0.5, vac: 0.25 } },
  { name: 'L\'asado', by: 'Argentine · autour du feu', tag: 'Une seule personne commande', color: '#8a4a2f',
    desc: 'Le feu se prépare deux heures avant, et celui qui s\'en occupe ne partage ni les pinces ni les décisions. Tout le monde attend, boit, et commente. C\'est un rituel avec une hiérarchie très claire.',
    t: { dom: 0.9, lea: 0.85, col: 0.9, tmp: 0.9, vtr: 0.95, soc: 0.9, det: 0.9, auth: 0.8, rig: 0.75, san: 0.85 } },
  { name: 'L\'empanada', by: 'Amérique latine · dans la main', tag: 'Tout tient dans le pli', color: '#d9a85f',
    desc: 'La garniture change selon la région et la fermeture du chausson dit qui l\'a faite. Elle se mange sans assiette, chaude, à n\'importe quelle heure. Sa forme n\'a pas changé depuis des générations.',
    t: { vtr: 0.9, fia: 0.9, soc: 0.85, care: 0.85, rig: 0.75, opn: 0.85, col: 0.8, det: 0.8, vac: 0.25, ouv: 0.65 } },
  { name: 'Le goulash', by: 'Hongrie · plat de berger', tag: 'Du paprika et du temps', color: '#a8422f',
    desc: 'Né dans les plaines, cuit dans un chaudron sur le feu, il tient au corps et se garde longtemps. Le paprika est ajouté hors du feu, sinon il devient amer — détail que tout le monde ignore une fois. Il nourrit ceux qui travaillent dehors.',
    t: { fia: 0.9, tmp: 0.9, vtr: 0.9, det: 0.9, care: 0.85, col: 0.85, san: 0.85, rig: 0.75, opn: 0.85, vac: 0.2 } },
  { name: 'Les pierogi', by: 'Pologne · à la main', tag: 'On les plie en famille', color: '#dccfae',
    desc: 'On en fait cent d\'un coup, à plusieurs, et on en congèle la moitié. Chaque grand-mère a une méthode et corrige celle des autres. Le plat compte moins que la table autour de laquelle on les plie.',
    t: { col: 0.95, vtr: 0.95, care: 0.9, att: 0.9, fia: 0.9, tmp: 0.85, soc: 0.85, rig: 0.8, emp: 0.85, vac: 0.15 } },
  { name: 'Le bortsch', by: 'Europe de l\'Est · en hiver', tag: 'Rouge, profond, et disputé', color: '#9e2f3a',
    desc: 'Betterave, chou, bouillon long, une cuillère de crème : il réchauffe des pays entiers, qui s\'en disputent la paternité. Il se bonifie sur plusieurs jours. Sa couleur annonce la franchise du goût.',
    t: { vtr: 0.95, tmp: 0.9, care: 0.9, col: 0.85, dog: 0.75, fia: 0.9, san: 0.85, det: 0.85, opn: 0.85, emp: 0.8 } },
  { name: 'Le hachis parmentier', by: 'France · restes du dimanche', tag: 'Fait avec ce qui restait', color: '#c9a45f',
    desc: 'Il est né pour recycler la viande de la veille et personne ne s\'en rend compte à l\'arrivée. Sa réussite tient à la purée, pas au reste. C\'est de l\'ingéniosité domestique devenue un classique.',
    t: { fia: 0.9, care: 0.9, vun: 0.8, ouv: 0.8, col: 0.85, rig: 0.7, vac: 0.2, det: 0.8, san: 0.85, ste: 0.85 } },
  { name: 'Les lasagnes', by: 'Italie · Émilie', tag: 'Elles se construisent par couches', color: '#b5502f',
    desc: 'Bolognaise, béchamel, pâtes, et on recommence — l\'ordre compte et le résultat ne se voit qu\'à la découpe. Elles demandent une demi-journée et disparaissent en vingt minutes. Rien ne s\'improvise dedans.',
    t: { ord: 0.95, rig: 0.9, tmp: 0.85, col: 0.9, care: 0.9, det: 0.9, vtr: 0.9, fia: 0.9, soc: 0.85, vac: 0.5 } },
  { name: 'Le pesto', by: 'Italie · Gênes', tag: 'Au mortier, jamais au mixeur', color: '#6f9440',
    desc: 'Le basilic doit être écrasé et non coupé, sous peine de noircir et de perdre son parfum : la règle est absolue chez ceux qui le font bien. Il se prépare en dix minutes et transforme n\'importe quel plat. Sa simplicité est très surveillée.',
    t: { vtr: 0.95, dog: 0.9, rig: 0.9, ide: 0.85, det: 0.8, opn: 0.9, vac: 0.5, san: 0.75, ouv: 0.25, vhe: 0.85 } },
  { name: 'La tarte tatin', by: 'France · par accident', tag: 'Ratée, puis servie quand même', color: '#c9752f',
    desc: 'Née d\'une erreur de cuisson qu\'on a décidé d\'assumer, elle se démoule à l\'envers dans un moment de suspense total. Le caramel doit être poussé jusqu\'au bord du brûlé. Son histoire dit tout : ce qui rate peut devenir la meilleure version.',
    t: { ouv: 0.9, aud: 0.9, inc: 0.85, opt: 0.85, vtr: 0.8, det: 0.85, rig: 0.7, chg: 0.85, vhe: 0.9, san: 0.6 } },
  { name: 'Le fondant au chocolat', by: 'France · dessert d\'urgence', tag: 'Tout se joue à la minute', color: '#4a2f28',
    desc: 'Une minute de trop et c\'est un gâteau ordinaire ; une minute de moins et c\'est de la pâte. Le cœur coulant n\'existe que dans un intervalle très étroit. Il se prépare vite et se surveille sans quitter le four des yeux.',
    t: { thr: 0.85, det: 0.85, rig: 0.85, vhe: 0.95, aud: 0.8, san: 0.45, tmp: 0.2, vac: 0.7, soc: 0.8, opt: 0.8 } },
  { name: 'Le tiramisu', by: 'Italie · Vénétie', tag: 'Il faut attendre une nuit', color: '#c9a878',
    desc: 'Il se monte en vingt minutes puis refuse d\'être mangé avant le lendemain, le temps que les biscuits se détendent. Impossible de tricher sur l\'attente. Sa douceur est le résultat d\'un délai imposé.',
    t: { tmp: 0.9, care: 0.9, vhe: 0.95, soc: 0.85, rig: 0.75, fia: 0.85, emp: 0.8, san: 0.8, det: 0.75, vac: 0.5 } },
  { name: 'La crème brûlée', by: 'France · au chalumeau', tag: 'Le plaisir de casser la surface', color: '#d9b45f',
    desc: 'Une crème très douce sous une couche dure qu\'il faut briser à la cuillère : la moitié du plaisir est dans le bruit. Le sucre doit être caramélisé au dernier moment, sinon il ramollit. Elle associe la rigueur et la gourmandise sans les mélanger.',
    t: { vhe: 0.9, rig: 0.85, san: 0.8, care: 0.85, ord: 0.85, vac: 0.7, det: 0.8, soc: 0.75, emp: 0.75, ouv: 0.6 } },
  { name: 'Le mille-feuille', by: 'France · pâtisserie', tag: 'Impossible à manger proprement', color: '#e0d2b0',
    desc: 'Sept cent vingt-neuf feuilles théoriques, une crème parfaitement lisse, et une catastrophe assurée dès le premier coup de fourchette. Il demande des jours de travail et se détruit en trois secondes. C\'est la technique qui accepte d\'être salie.',
    t: { rig: 0.98, det: 0.95, tmp: 0.9, vac: 0.85, ord: 0.95, inf: 0.8, san: 0.8, thr: 0.7, vhe: 0.85, chg: 0.2 } },
  { name: 'La tarte au citron meringuée', by: 'France · équilibre', tag: 'L\'acide et le sucre en face à face', color: '#e0c24a',
    desc: 'Trop de meringue et elle devient écœurante, pas assez et le citron agresse : tout est dans la proportion. Elle a l\'air joyeuse et repose sur un dosage sévère. Elle ne pardonne pas l\'approximation.',
    t: { rig: 0.9, ide: 0.8, det: 0.85, dip: 0.8, vac: 0.75, ord: 0.85, care: 0.8, san: 0.8, ouv: 0.6, emp: 0.75 } },
  { name: 'Le paris-brest', by: 'France · d\'après une course', tag: 'Une roue de vélo en pâtisserie', color: '#b5874a',
    desc: 'Inventé pour une course cycliste, il en garde la forme ronde et la générosité calorique. La crème pralinée doit être montée juste assez pour tenir sans peser. Il rend hommage à l\'effort en le rendant délicieux.',
    t: { vtr: 0.9, det: 0.9, rig: 0.9, vhe: 0.9, vac: 0.8, care: 0.85, cmp: 0.7, ord: 0.85, opn: 0.8, soc: 0.75 } },
  { name: 'Le baba au rhum', by: 'France et Naples · imbibé', tag: 'Il absorbe tout', color: '#c9883a',
    desc: 'Sec et sans intérêt tant qu\'il n\'a pas trempé, il devient tout autre chose une fois imbibé. Le sirop doit être chaud et la pâte froide, ou l\'inverse selon les écoles. Il ne prend sa valeur qu\'au contact de ce qu\'on lui donne.',
    t: { ouv: 0.85, loc: 0.8, vhe: 0.95, care: 0.8, vtr: 0.85, tmp: 0.7, chg: 0.8, soc: 0.8, rig: 0.7, inc: 0.7 } },
  { name: 'Le cheesecake', by: 'New York · part épaisse', tag: 'Dense et assumé', color: '#e0d6b4',
    desc: 'Il ne cherche ni la légèreté ni la finesse : il est compact, riche, et se coupe en parts qui font réfléchir. Il cuit au bain-marie pendant plus d\'une heure sans jamais devoir être ouvert. Il tient sa ligne du début à la fin.',
    t: { fia: 0.9, ste: 0.9, det: 0.85, vhe: 0.95, rig: 0.8, san: 0.85, vac: 0.6, tmp: 0.8, dog: 0.7, opn: 0.75 } },
  { name: 'Le cookie sorti du four', by: 'États-Unis · encore mou', tag: 'Meilleur avant d\'être fini', color: '#a8703a',
    desc: 'On le mange trop chaud, il se casse, et c\'est exactement le moment qu\'il faut. Trop cuit, il devient un biscuit ordinaire. Toute sa valeur tient dans un créneau de cinq minutes.',
    t: { vhe: 0.95, vst: 0.85, opt: 0.9, soc: 0.85, tmp: 0.1, aud: 0.8, care: 0.85, rig: 0.35, san: 0.5, emp: 0.8 } },
  { name: 'Le pain au levain', by: 'France · fermentation longue', tag: 'Il faut le nourrir tous les jours', color: '#c9a878',
    desc: 'Le levain est vivant, exige d\'être entretenu même quand on ne cuit pas, et se venge des semaines d\'abandon. La pousse prend douze heures et ne s\'accélère pas. C\'est un engagement quotidien pour un résultat hebdomadaire.',
    t: { fia: 0.98, tmp: 0.98, rig: 0.9, det: 0.95, care: 0.9, vtr: 0.9, san: 0.9, ord: 0.9, vac: 0.3, vst: 0.15 } },
  { name: 'Le croissant', by: 'France · viennoiserie', tag: 'Des heures de pliage pour trois bouchées', color: '#d9a850',
    desc: 'Le beurre doit rester à la même température que la pâte pendant tout le tourage, sinon les couches fusionnent et tout est perdu. Il se mange en deux minutes debout au comptoir. Le rapport entre l\'effort et la durée de vie est déraisonnable.',
    t: { rig: 0.95, det: 0.9, tmp: 0.85, vtr: 0.9, ord: 0.9, care: 0.85, vac: 0.7, san: 0.8, vhe: 0.9, opn: 0.85 } },
  { name: 'La baguette tradition', by: 'France · deux fois par jour', tag: 'Elle ne tient pas jusqu\'au soir', color: '#d3ab63',
    desc: 'Excellente à la sortie, correcte à midi, dure le lendemain : elle impose son propre rythme à ceux qui la mangent. Quatre ingrédients, aucun additif, et une croûte qui chante en refroidissant. Elle oblige à revenir.',
    t: { vtr: 0.95, fia: 0.9, ide: 0.85, rig: 0.85, opn: 0.95, vac: 0.4, det: 0.85, san: 0.8, tmp: 0.3, care: 0.8 } },
  { name: 'Les frites belges', by: 'Belgique · double cuisson', tag: 'Deux bains, pas un seul', color: '#d9b45b',
    desc: 'Une première cuisson douce pour l\'intérieur, une seconde très chaude pour la croûte : sauter l\'étape donne des frites molles et tout le monde le sait. Elles se mangent dans un cornet, avec les doigts. La rigueur est au service du plaisir immédiat.',
    t: { rig: 0.85, det: 0.85, vtr: 0.9, soc: 0.85, vhe: 0.95, fia: 0.9, ord: 0.8, opt: 0.85, vac: 0.3, opn: 0.85 } },
  { name: 'Les moules-frites', by: 'Belgique et Nord · en terrasse', tag: 'Un grand bruit de coquilles', color: '#4a6b7a',
    desc: 'On les sert dans la marmite, on empile les coquilles vides et la table devient rapidement un chantier. Elles se mangent à plusieurs, sans protocole. C\'est un plat qui autorise le désordre.',
    t: { soc: 0.95, col: 0.9, vhe: 0.9, opt: 0.85, rig: 0.25, care: 0.8, vtr: 0.85, com: 0.85, ord: 0.2, vac: 0.2 } },
  { name: 'Les huîtres', by: 'France · bord de mer', tag: 'On aime ou pas, et c\'est tout', color: '#8fa89e',
    desc: 'Rien n\'est cuisiné, rien n\'est ajouté : le goût vient entièrement du lieu où elles ont poussé. Elles divisent la table en deux camps irréconciliables. Elles ne cherchent à convaincre personne.',
    t: { ide: 0.9, ind: 0.9, vtr: 0.9, dog: 0.75, san: 0.85, rig: 0.7, opn: 0.9, vac: 0.5, soc: 0.6, ouv: 0.35 } },
  { name: 'Le saumon fumé', by: 'Nord · tranché fin', tag: 'Préparé longtemps à l\'avance', color: '#d98a6b',
    desc: 'Salé, séché, fumé à froid pendant des heures : le travail est fait des semaines avant qu\'on le serve. Il se tranche à un millimètre et ne se cuisine pas. Sa discrétion est le fruit d\'une préparation invisible.',
    t: { rig: 0.9, tmp: 0.9, san: 0.9, fia: 0.9, vtr: 0.85, ord: 0.85, det: 0.85, vac: 0.6, soc: 0.6, ste: 0.85 } },
  { name: 'La soupe miso', by: 'Japon · tous les matins', tag: 'Toujours là, jamais commentée', color: '#9e7a3a',
    desc: 'Elle accompagne des milliers de repas sans jamais être le sujet, et sa préparation prend trois minutes. Le miso ne doit jamais bouillir, sous peine de perdre ce qui fait son intérêt. Elle est le fond sonore de la table japonaise.',
    t: { fia: 0.95, ste: 0.95, san: 0.9, care: 0.85, vtr: 0.9, vco: 0.8, rig: 0.8, vac: 0.05, soc: 0.6, emp: 0.8 } },
  { name: 'Les onigiri', by: 'Japon · dans la poche', tag: 'Fait pour être emporté', color: '#d5cdb4',
    desc: 'Riz pressé à la main autour d\'une garniture, enveloppé de manière à ce que l\'algue reste croustillante jusqu\'à l\'ouverture. Ils se mangent debout, en déplacement, sans cérémonie. Tout y est pensé pour la personne qui le mangera plus tard.',
    t: { care: 0.9, rig: 0.85, fia: 0.9, ord: 0.85, san: 0.85, emp: 0.85, vse: 0.8, tmp: 0.7, soc: 0.5, vac: 0.2 } },
  { name: 'Les nouilles instantanées', by: 'Partout · trois minutes', tag: 'Disponibles quoi qu\'il arrive', color: '#e0a03a',
    desc: 'Elles ne prétendent à rien, coûtent presque rien et sauvent des soirées entières depuis des décennies. Chacun y ajoute ce qu\'il a sous la main. Leur seule promesse est d\'être là.',
    t: { fia: 0.9, vse: 0.85, vac: 0.05, rig: 0.1, san: 0.8, ouv: 0.7, tmp: 0.1, soc: 0.5, opt: 0.7, ind: 0.8 } },
  { name: 'Le riz cantonais du frigo', by: 'Partout · avec les restes', tag: 'Il sauve la situation', color: '#d9b06a',
    desc: 'Il se fait avec ce qui traîne, réussit mieux avec du riz de la veille, et n\'a jamais deux fois la même composition. Il transforme le manque en repas correct. Son improvisation est sa méthode.',
    t: { ouv: 0.9, vun: 0.8, ind: 0.85, ord: 0.2, det: 0.8, opt: 0.85, rig: 0.25, fia: 0.85, care: 0.8, vac: 0.15 } },
  { name: 'L\'omelette', by: 'Partout · test d\'embauche', tag: 'Simple à faire, difficile à réussir', color: '#e0c063',
    desc: 'On la demande en entretien parce qu\'elle révèle tout : la maîtrise du feu, du temps, du geste. Baveuse ou sèche, il n\'y a pas de demi-mesure. Trois œufs suffisent à savoir à qui on a affaire.',
    t: { rig: 0.9, det: 0.85, san: 0.8, fia: 0.9, ide: 0.8, vac: 0.6, ord: 0.8, vhe: 0.8, ouv: 0.5, cmp: 0.6 } },
  { name: 'La salade César', by: 'Mexique et Hollywood · au guéridon', tag: 'Préparée devant tout le monde', color: '#8fae5f',
    desc: 'Inventée dans un restaurant à court d\'ingrédients, elle se montait à l\'origine devant le client, à la pince, avec beaucoup de gestes. Elle a l\'air légère et ne l\'est pas du tout. Le spectacle fait partie de la recette.',
    t: { inf: 0.9, soc: 0.85, ouv: 0.8, vac: 0.8, com: 0.85, rig: 0.7, vhe: 0.85, aud: 0.8, care: 0.7, opt: 0.8 } },
  { name: 'La salade grecque', by: 'Grèce · plein soleil', tag: 'Rien de cuit, rien de compliqué', color: '#5f9e8a',
    desc: 'Tomates, concombre, olives, feta en bloc, huile d\'olive : aucune cuisson et aucune sauce préparée. Sa qualité dépend entièrement de celle des tomates. Elle refuse de compenser par la technique.',
    t: { ide: 0.9, vtr: 0.9, san: 0.85, ouv: 0.5, rig: 0.6, opn: 0.9, vhe: 0.85, care: 0.8, soc: 0.8, vac: 0.2 } },
  { name: 'La soupe de légumes du placard', by: 'Partout · fin de semaine', tag: 'Elle ne gaspille rien', color: '#7a8f4a',
    desc: 'Elle se fait avec ce qui allait être jeté, se mixe ou pas selon l\'humeur, et se congèle en portions. Personne ne la photographie jamais. C\'est l\'économie domestique dans ce qu\'elle a de plus juste.',
    t: { vun: 0.9, care: 0.9, fia: 0.9, vac: 0.05, tmp: 0.85, ouv: 0.75, det: 0.8, san: 0.85, ste: 0.9, vse: 0.85 } },
  { name: 'Le chakchouka', by: 'Afrique du Nord · une seule poêle', tag: 'Tout cuit dans le même récipient', color: '#c9522f',
    desc: 'Tomates, poivrons, œufs cassés directement dedans, et on apporte la poêle sur la table. Une seule chose à laver, ce qui est rarement mentionné et toujours apprécié. Elle est franche et sans cérémonie.',
    t: { soc: 0.85, care: 0.85, ouv: 0.8, fia: 0.85, rig: 0.4, col: 0.85, vhe: 0.85, opt: 0.85, ord: 0.4, det: 0.75 } },
  { name: 'Le poulet yassa', by: 'Sénégal · citron et oignons', tag: 'La marinade fait tout', color: '#d9a03a',
    desc: 'Le poulet trempe une nuit entière dans le citron et les oignons, et ce qui se passe après compte beaucoup moins. Il se partage sur un grand plat de riz. Sa réussite est décidée la veille.',
    t: { tmp: 0.9, col: 0.95, care: 0.9, vtr: 0.9, det: 0.85, fia: 0.9, soc: 0.9, rig: 0.75, emp: 0.8, vac: 0.3 } },
  { name: 'Le mafé', by: 'Afrique de l\'Ouest · pâte d\'arachide', tag: 'Doux, épais, et il tient au corps', color: '#b5702f',
    desc: 'La pâte d\'arachide épaissit lentement la sauce et enrobe tout ce qu\'elle touche. Il mijote longtemps, se sert généreusement et nourrit une tablée entière. Sa douceur est nourrissante plutôt que sucrée.',
    t: { care: 0.95, col: 0.9, tmp: 0.9, vtr: 0.9, emp: 0.85, fia: 0.9, soc: 0.85, san: 0.85, ste: 0.85, vac: 0.2 } },
  { name: 'Le curry de lentilles', by: 'Partout · sans viande', tag: 'Économique et solide', color: '#c98a3a',
    desc: 'Il coûte trois fois rien, se conserve plusieurs jours et rassasie sans effort. On le fait en grande quantité le dimanche pour ne plus y penser de la semaine. Sa modestie est parfaitement organisée.',
    t: { fia: 0.95, tmp: 0.9, ord: 0.85, care: 0.85, vun: 0.85, det: 0.85, rig: 0.75, vac: 0.15, san: 0.85, vse: 0.85 } },
  { name: 'Le sandwich au thon de gare', by: 'Partout · sous plastique', tag: 'Il fait ce qu\'il peut', color: '#a8a08a',
    desc: 'Personne ne l\'a choisi par envie : il était là et le train partait. Il remplit son office sans laisser de souvenir. Il assume complètement son absence d\'ambition.',
    t: { vse: 0.85, fia: 0.8, vac: 0.02, vhe: 0.15, san: 0.8, rig: 0.3, soc: 0.3, opt: 0.4, ste: 0.85, vst: 0.05 } },
  { name: 'Le plateau de fromages', by: 'France · fin de repas', tag: 'Il arrive quand on n\'a plus faim', color: '#d9c073',
    desc: 'On le sort alors que tout le monde a assez mangé, et il repart à moitié vide quand même. Il demande un ordre de dégustation que personne ne respecte. C\'est la tradition qui gagne contre la raison.',
    t: { vtr: 0.98, vhe: 0.9, soc: 0.9, dog: 0.8, col: 0.85, vco: 0.8, care: 0.8, rig: 0.6, opn: 0.9, vac: 0.4 } },
  { name: 'Le brunch du dimanche', by: 'Partout · sans horaire', tag: 'Ni l\'un ni l\'autre, et tant mieux', color: '#e0b06a',
    desc: 'Il refuse de choisir entre le petit-déjeuner et le déjeuner, et s\'étale sur trois heures sans culpabilité. On y parle plus qu\'on y mange. Son principal ingrédient est le temps qu\'on accepte d\'y perdre.',
    t: { soc: 0.95, vhe: 0.95, ouv: 0.85, opt: 0.9, tmp: 0.4, rig: 0.15, care: 0.85, col: 0.9, vco: 0.2, emp: 0.85 } },
  { name: 'Le petit-déjeuner à l\'anglaise', by: 'Royaume-Uni · assiette pleine', tag: 'Tout, dès le matin', color: '#b5622f',
    desc: 'Œufs, bacon, saucisses, haricots, champignons, tomate grillée : il n\'y a aucune tentative de modération. Il tient jusqu\'au soir, ce qui est en partie l\'idée. Il commence la journée par une déclaration.',
    t: { vhe: 0.95, det: 0.85, vtr: 0.9, aud: 0.8, fia: 0.9, col: 0.8, rig: 0.4, opt: 0.85, vac: 0.4, san: 0.8 } },
  { name: 'Le thé à la menthe', by: 'Maghreb · versé de haut', tag: 'Le service compte autant', color: '#5f9e6b',
    desc: 'On le verse de très haut pour l\'aérer, on le reverse dans la théière, on recommence — et le troisième verre n\'a pas le même goût que le premier. Refuser est impossible. C\'est une conversation avant d\'être une boisson.',
    t: { vtr: 0.95, soc: 0.95, dip: 0.9, care: 0.9, rig: 0.85, ord: 0.85, col: 0.9, emp: 0.85, tmp: 0.8, cfl: 0.05 } },
  { name: 'Le chocolat chaud épais', by: 'Espagne et Italie · à la cuillère', tag: 'Presque trop', color: '#4a2f28',
    desc: 'Il tient debout dans la tasse et se mange autant qu\'il se boit. Personne n\'en reprend une seconde fois. Il est conçu pour un moment précis et pas pour tous les jours.',
    t: { vhe: 0.98, care: 0.85, soc: 0.8, san: 0.75, rig: 0.6, opt: 0.8, det: 0.7, vac: 0.4, tmp: 0.4, emp: 0.75 } },
  { name: 'Le café serré du comptoir', by: 'Italie · debout', tag: 'Trente secondes, pas plus', color: '#3f2f28',
    desc: 'On le commande, on le boit debout, on paie et on repart : l\'ensemble dure moins d\'une minute. S\'asseoir coûte plus cher, ce qui n\'est pas un hasard. Il ne perd jamais de temps.',
    t: { det: 0.9, vst: 0.8, ind: 0.85, rig: 0.85, tmp: 0.1, san: 0.8, vtr: 0.9, soc: 0.5, opn: 0.9, vac: 0.6 } },
  { name: 'Le gâteau au yaourt', by: 'France · premier gâteau', tag: 'Celui qu\'on apprend en premier', color: '#e0c98a',
    desc: 'On mesure tout avec le pot vide, ce qui permet de le faire à six ans sans balance. Il n\'est jamais raté et jamais extraordinaire. C\'est la porte d\'entrée de la cuisine pour des générations entières.',
    t: { fia: 0.95, care: 0.9, opt: 0.9, vtr: 0.9, ste: 0.9, rig: 0.6, san: 0.85, emp: 0.85, vac: 0.1, soc: 0.8 } },
  { name: 'Les crêpes du mardi soir', by: 'France · à la chaîne', tag: 'La première est toujours ratée', color: '#e0c07a',
    desc: 'On la jette, on continue, et la pile monte pendant que la cuisine se remplit de monde. Chacun garnit la sienne et personne ne s\'accorde sur le sucre ou le citron. C\'est un dîner qui se fabrique en même temps qu\'il se mange.',
    t: { soc: 0.95, col: 0.9, opt: 0.9, vhe: 0.9, care: 0.85, rig: 0.3, fia: 0.85, com: 0.85, vac: 0.1, emp: 0.85 } },
  { name: 'Les churros', by: 'Espagne · dans la rue', tag: 'Chauds, gras, et immédiats', color: '#d9903a',
    desc: 'Ils se mangent debout dans du papier, brûlants, trempés dans du chocolat, sans aucune considération diététique. Froids, ils ne valent plus rien. Ils n\'existent que dans l\'instant où on les achète.',
    t: { vhe: 0.98, vst: 0.85, soc: 0.85, opt: 0.9, tmp: 0.05, rig: 0.3, aud: 0.8, vac: 0.2, care: 0.7, san: 0.55 } },
  { name: 'Le mochi', by: 'Japon · pilé au maillet', tag: 'Beaucoup de force pour un résultat tendre', color: '#e8d5d9',
    desc: 'Le riz est écrasé à deux, au maillet, dans un rythme synchronisé où l\'un frappe pendant que l\'autre retourne. Une seconde d\'inattention et c\'est la main. La douceur finale vient d\'une violence parfaitement coordonnée.',
    t: { col: 0.9, rig: 0.9, fia: 0.9, det: 0.9, vtr: 0.95, ord: 0.9, san: 0.85, thr: 0.8, care: 0.85, soc: 0.8 } },
  { name: 'Le baklava', by: 'Méditerranée orientale · au sirop', tag: 'Sucré jusqu\'au bout', color: '#c9a03a',
    desc: 'Des dizaines de feuilles beurrées, des pistaches, et un sirop versé chaud sur une pâte froide pour que tout s\'imprègne sans ramollir. Il se coupe en losanges avant cuisson, jamais après. Il ne fait aucune concession à la modération.',
    t: { rig: 0.9, vtr: 0.95, det: 0.9, vhe: 0.95, ord: 0.9, care: 0.85, soc: 0.85, tmp: 0.8, vac: 0.7, san: 0.8 } },
  { name: 'La glace à la vanille', by: 'Partout · valeur sûre', tag: 'Le choix qu\'on ne regrette pas', color: '#e8dcc0',
    desc: 'Elle ne surprendra personne et c\'est précisément pour ça qu\'on la prend. Elle accompagne tout et ne vole jamais la vedette. Sa banalité est une décision.',
    t: { fia: 0.95, vse: 0.9, ste: 0.9, san: 0.9, vac: 0.15, rig: 0.7, care: 0.85, vst: 0.05, dip: 0.85, soc: 0.7 } },
  { name: 'La barbe à papa', by: 'Fête foraine · rose', tag: 'Beaucoup d\'air, peu de matière', color: '#e89ec4',
    desc: 'Énorme dans la main et minuscule dans la bouche, elle disparaît avant qu\'on ait compris. Elle colle partout et personne n\'en reprend. Elle vaut pour le moment, pas pour le goût.',
    t: { inf: 0.9, vhe: 0.9, opt: 0.9, vac: 0.2, soc: 0.85, tmp: 0.02, rig: 0.05, aud: 0.7, san: 0.4, ouv: 0.7 } },
  { name: 'Le pop-corn au cinéma', by: 'Partout · dans le noir', tag: 'On ne le mange jamais seul', color: '#e0cb8a',
    desc: 'Il n\'a d\'intérêt que dans une salle obscure, partagé, et on continue longtemps après avoir cessé d\'avoir faim. Le bruit du seau agace la rangée d\'à côté. Il fait partie du décor plus que du repas.',
    t: { soc: 0.9, col: 0.85, vhe: 0.9, vst: 0.75, opt: 0.85, rig: 0.15, vac: 0.05, tmp: 0.2, care: 0.7, san: 0.6 } },
];

window.PRISME_DISHES = { DISHES };
