/* ============================================================
   PRISME — « Si tu étais une drogue… du quotidien »
   ------------------------------------------------------------
   Uniquement des petites addictions sans danger, celles dont tout le
   monde plaisante : le café, le fromage, le scroll, la sieste… Ce qui
   compte, c'est leur caractère : ce qui réveille, ce qui apaise, ce qui
   fait tenir, ce dont on ne peut plus se passer.
     name = la « drogue », by = famille · son effet, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const DRUGS = [
  { name: 'Le café serré', by: 'Caféine · le réveil en tasse', tag: 'Debout, on a du travail', color: '#3b2314',
    desc: 'La caféine prend la place de l\'adénosine, la petite molécule qui signale au cerveau qu\'il est fatigué : la fatigue est toujours là, on ne l\'entend simplement plus. Avalé debout au comptoir, il ne sert pas à se faire plaisir mais à démarrer. C\'est le tempérament des gens pressés et efficaces, qui visent un résultat, détestent traîner et préfèrent un coup de fouet à une grasse matinée.',
    t: { det: 0.95, vac: 0.9, dom: 0.8, vhe: 0.15, ste: 0.15, tmp: 0.8, att: 0.25, soc: 0.3, cmp: 0.8, ord: 0.8 } },
  { name: 'Le café au lait', by: 'Caféine adoucie · le réveil en douceur', tag: 'Un bol, deux mains, pas de bruit', color: '#c8a27a',
    desc: 'Il se boit dans un grand bol, les deux mains autour, et il réveille sans brusquer : le lait arrondit l\'amertume et ralentit un peu le coup de fouet. C\'est un rituel plus qu\'un carburant. C\'est le tempérament des gens doux et fidèles à leurs habitudes, qui ont besoin d\'une routine rassurante pour commencer la journée et que les réveils en fanfare mettent de mauvaise humeur.',
    t: { ste: 0.95, vse: 0.85, vtr: 0.8, att: 0.8, aud: 0.1, vst: 0.1, cfl: 0.1, dom: 0.15, chg: 0.1, rsk: 0.1 } },
  { name: 'Le thé', by: 'Théine · la vigilance tranquille', tag: 'L\'eau frémit, on attend', color: '#8a9a5b',
    desc: 'La théine est exactement la même molécule que la caféine, mais le thé contient aussi de la L-théanine, qui adoucit l\'effet : on est éveillé sans être agité. Il impose son temps d\'infusion, et personne ne le presse. C\'est le tempérament des gens posés et méthodiques, attachés aux rituels bien faits, qui réfléchissent avant de parler et gardent leur calme quand tout s\'agite.',
    t: { san: 0.95, con: 0.85, vtr: 0.8, ste: 0.85, inf: 0.1, rsk: 0.1, com: 0.15, aff: 0.75, vhe: 0.3, ord: 0.8 } },
  { name: 'Le matcha', by: 'Thé vert en poudre · la concentration zen', tag: 'Fouetté, vert, et très sérieux', color: '#7aa33b',
    desc: 'Au lieu d\'infuser les feuilles, on les boit entières, réduites en poudre et fouettées au bambou : plus de caféine et plus de théanine qu\'un thé ordinaire. Il vient de la cérémonie du thé japonaise et il est devenu une mode. C\'est le tempérament des curieux exigeants qui aiment ce qui est pur, sain et un peu pointu, et qui adoptent une nouveauté seulement si elle a du sens.',
    t: { sanc: 0.9, ouv: 0.85, vst: 0.75, rig: 0.8, vhe: 0.2, soc: 0.3, opn: 0.15, ide: 0.8, cmp: 0.2, vun: 0.8 } },
  { name: 'Le chocolat noir', by: 'Cacao · le plaisir qui se mérite', tag: 'Un carré, et pas deux', color: '#4a2c20',
    desc: 'Plus il est noir, plus il est amer, et plus il faut un palais entraîné pour l\'aimer. Il contient de la théobromine, une cousine douce de la caféine, et beaucoup de magnésium. On le savoure un carré à la fois, jamais la tablette entière. C\'est le tempérament des gens exigeants et maîtres d\'eux-mêmes, qui préfèrent un plaisir intense et rare à une gourmandise facile.',
    t: { rig: 0.9, aff: 0.8, ind: 0.85, vhe: 0.4, soc: 0.2, inf: 0.2, con: 0.8, vco: 0.2, san: 0.8, emp: 0.35 } },
  { name: 'La pâte à tartiner à la cuillère', by: 'Noisette et cacao · le retour en enfance', tag: 'Directement dans le pot, personne ne regarde', color: '#8b5a2b',
    desc: 'La gianduja, son ancêtre, est née à Turin quand le cacao manquait et qu\'on l\'a allongé avec des noisettes. Aujourd\'hui, elle se mange surtout debout devant le placard, à la cuillère, sans tartine et sans témoin. C\'est le tempérament des grands enfants gourmands, qui vivent l\'instant, se moquent un peu des bonnes résolutions et savent se consoler tout seuls.',
    t: { vhe: 0.98, tmp: 0.05, rig: 0.05, con: 0.1, ord: 0.1, vac: 0.15, att: 0.75, san: 0.3, dog: 0.1, sanc: 0.1 } },
  { name: 'Les bonbons acidulés', by: 'Sucre et acide citrique · la décharge', tag: 'Ça pique, et c\'est bon', color: '#e6ff3a',
    desc: 'L\'acide citrique et l\'acide malique réveillent la langue d\'un coup, puis le sucre vient consoler : c\'est la montagne russe du goût en quelques secondes. Ils plissent les yeux et font rire. C\'est le tempérament des gens piquants et joueurs, qui aiment les sensations vives, disent franchement ce qu\'ils pensent et trouvent la vie trop fade quand rien ne pétille.',
    t: { vst: 0.9, com: 0.85, inf: 0.85, aud: 0.8, ste: 0.1, san: 0.2, rig: 0.2, cfl: 0.8, tmp: 0.1, vtr: 0.1, dip: 0.2 } },
  { name: 'Le fromage', by: 'Lait affiné · l\'art de vivre', tag: 'Il n\'y a pas de repas sans lui', color: '#f2c14e',
    desc: 'La France en compte plus d\'un millier, et chaque région défend les siens avec une ferveur presque patriotique. Il se partage, se commente, se transmet de génération en génération. C\'est le tempérament des bons vivants enracinés, fiers de leur terroir, qui se méfient des modes et des régimes et savent que les meilleures choses ont besoin de temps pour mûrir.',
    t: { vtr: 0.95, opn: 0.9, vhe: 0.85, loy: 0.85, chg: 0.1, vst: 0.2, sanc: 0.2, ouv: 0.3, tmp: 0.75, col: 0.75 } },
  { name: 'Les chips', by: 'Sel et croustillant · l\'apéro', tag: 'Impossible d\'en manger une seule', color: '#f4a300',
    desc: 'Des chercheurs ont montré que le bruit du croquant change le goût : plus le craquement est fort, plus on les trouve fraîches. Le sel en appelle d\'autres, et le paquet se vide tout seul, de préférence en bonne compagnie. C\'est le tempérament des gens conviviaux et spontanés, qui préfèrent l\'apéro improvisé au dîner planifié et ne comptent pas trop quand on s\'amuse.',
    t: { soc: 0.95, inf: 0.85, vhe: 0.9, ord: 0.1, rig: 0.1, tmp: 0.1, vig: 0.15, ste: 0.4, aff: 0.2, sanc: 0.05 } },
  { name: 'Le pain frais', by: 'Farine et levain · la réaction de Maillard', tag: 'Le quignon ne rentre jamais à la maison', color: '#d4a055',
    desc: 'L\'odeur de la croûte vient de la réaction de Maillard, la même qui dore les viandes : impossible d\'y résister en sortant de la boulangerie, et le quignon disparaît avant d\'arriver. Simple, quotidien, jamais lassant. C\'est le tempérament des gens fiables et sans chichis, attachés aux petites choses vraies, qui n\'ont besoin ni de nouveauté ni de prestige pour être heureux.',
    t: { fia: 0.95, vtr: 0.85, epi: 0.1, vpo: 0.05, vst: 0.15, ste: 0.8, dog: 0.2, loy: 0.8, aud: 0.2, vco: 0.75 } },
  { name: 'Les pâtes', by: 'Féculents · le réconfort', tag: 'Il en reste, ressers-toi', color: '#f1d88a',
    desc: 'C\'est le plat des soirs de fatigue, des colocations et des grandes tablées : on en fait toujours trop, et c\'est exprès. Les glucides réconfortent, et une casserole suffit à nourrir tout le monde. C\'est le tempérament des gens généreux et accueillants, qui pensent aux autres avant eux, détestent la compétition et préfèrent un repas partagé à un dîner qui impressionne.',
    t: { vbe: 0.95, col: 0.9, att: 0.9, cmp: 0.05, vpo: 0.05, vac: 0.2, rig: 0.25, emp: 0.85, care: 0.85, ind: 0.2 } },
  { name: 'Le soda', by: 'Bulles et sucre · le pétillant', tag: 'Ça fait pschitt, ça fait du bien', color: '#c0392b',
    desc: 'Les bulles ne sont pas seulement sensibles au toucher : une partie de leur piquant est captée par les récepteurs de l\'acidité de la langue. Frais, sucré, bruyant quand on l\'ouvre, il ne se prend pas au sérieux. C\'est le tempérament des gens légers et optimistes, qui vivent au présent, ne se posent pas trop de questions et préfèrent le plaisir simple aux discours sur ce qui est bon pour soi.',
    t: { opt: 0.9, vhe: 0.85, epi: 0.05, tmp: 0.1, sanc: 0.05, vis: 0.1, rig: 0.15, ide: 0.2, aff: 0.3, thr: 0.1 } },
  { name: 'Les réseaux sociaux', by: 'Écrans · le lien permanent', tag: 'Qu\'est-ce que j\'ai raté ?', color: '#e1306c',
    desc: 'Ils donnent des nouvelles de tout le monde, tout le temps, et rendent impossible l\'idée de manquer quelque chose. On partage, on commente, on se montre un peu. C\'est le tempérament des gens très entourés et expansifs, qui ont besoin de sentir le groupe autour d\'eux, aiment être au courant avant les autres et vivent mal les soirées où il ne se passe rien.',
    t: { soc: 0.98, inf: 0.95, ind: 0.1, ste: 0.2, col: 0.8, vst: 0.8, aff: 0.2, inc: 0.3, san: 0.35, ouv: 0.7 } },
  { name: 'Le scroll infini', by: 'Écrans · le pouce en pilote automatique', tag: 'Encore une vidéo, et je dors', color: '#5b5f97',
    desc: 'Son inventeur, Aza Raskin, a fini par regretter de l\'avoir créé : sans bas de page, rien ne signale au cerveau qu\'il est temps de s\'arrêter. Le pouce glisse tout seul et l\'heure file. C\'est le tempérament des gens qui se laissent porter, fuient l\'effort quand ils sont fatigués et remettent volontiers à demain ce qui demande de la volonté, sans jamais s\'en vanter.',
    t: { loc: 0.95, det: 0.1, ord: 0.1, tmp: 0.05, vac: 0.1, lea: 0.1, vhe: 0.8, dom: 0.1, ste: 0.75, cfl: 0.1 } },
  { name: 'Les likes', by: 'Récompense sociale · le petit cœur rouge', tag: 'Alors, ça a plu ?', color: '#ff3b5c',
    desc: 'Ils arrivent sans prévenir et en nombre imprévisible, exactement ce qui stimule le plus le circuit de la récompense et sa dopamine. On poste, on attend, on revérifie. C\'est le tempérament des gens qui ont besoin d\'être reconnus, aiment briller, se comparent volontiers et mesurent un peu leur valeur à l\'enthousiasme qu\'ils déclenchent autour d\'eux.',
    t: { vpo: 0.9, vac: 0.9, inf: 0.9, cmp: 0.85, ind: 0.1, ste: 0.15, vco: 0.8, san: 0.2, vun: 0.2, dip: 0.6 } },
  { name: 'Les notifications', by: 'Alertes · la vibration fantôme', tag: 'Attends, ça a vibré', color: '#ff9f1c',
    desc: 'Beaucoup de gens sentent vibrer leur téléphone alors qu\'il n\'a rien reçu : on appelle ça la vibration fantôme. Chaque pastille rouge est une petite urgence qui réclame une réponse immédiate. C\'est le tempérament des gens toujours sur le qui-vive, qui détestent laisser une question en suspens et ont du mal à débrancher, de peur qu\'un problème n\'arrive pendant leur absence.',
    t: { vig: 0.95, thr: 0.9, inc: 0.05, ste: 0.1, san: 0.1, fia: 0.8, nat: 0.7, vse: 0.85, ord: 0.7, rsk: 0.15 } },
  { name: 'Le binge-watching', by: 'Séries · l\'épisode suivant dans 5 secondes', tag: 'Juste la fin de la saison', color: '#b0101f',
    desc: 'Le cliffhanger joue sur l\'effet Zeigarnik : le cerveau retient bien mieux une histoire inachevée qu\'une histoire terminée, et il réclame la suite. Le compte à rebours de l\'épisode suivant fait le reste. C\'est le tempérament des passionnés casaniers, qui s\'immergent entièrement dans un monde imaginaire et préfèrent un canapé plein de personnages à une soirée pleine d\'inconnus.',
    t: { vhe: 0.9, soc: 0.1, inf: 0.15, ide: 0.85, ouv: 0.75, vst: 0.3, det: 0.25, tmp: 0.1, rsk: 0.1, att: 0.7 } },
  { name: 'Le « encore une partie »', by: 'Jeux vidéo · le dernier tour', tag: 'Il est déjà trois heures ?', color: '#6c3ec1',
    desc: 'Les joueurs de Civilization l\'appellent le syndrome du « encore un tour » : chaque partie finie promet une revanche, chaque niveau un niveau de plus. La victoire est toujours à portée de main. C\'est le tempérament des compétiteurs obstinés et solitaires, qui aiment progresser, battre leur propre record et qui ne lâchent rien tant qu\'ils n\'ont pas gagné.',
    t: { cmp: 0.95, det: 0.9, vac: 0.8, soc: 0.2, ind: 0.8, tmp: 0.2, dip: 0.2, vtr: 0.1, ste: 0.3, vst: 0.8, att: 0.3 } },
  { name: 'Les jeux de société', by: 'Plateau · la soirée qui s\'éternise', tag: 'On relit la règle ?', color: '#2a9d8f',
    desc: 'On sort la boîte « pour une petite partie » et on finit à minuit en débattant d\'une règle obscure. Il faut des amis, une table et un minimum de fair-play. C\'est le tempérament des gens sociables qui aiment la compétition amicale, tiennent à l\'équité et au respect des règles, et pour qui gagner n\'a de saveur que si tout le monde a passé une bonne soirée.',
    t: { fair: 0.95, soc: 0.9, con: 0.8, col: 0.85, cmp: 0.6, vbe: 0.8, ind: 0.15, rsk: 0.3, lib: 0.25, dom: 0.3 } },
  { name: 'Les podcasts', by: 'Audio · la curiosité dans les oreilles', tag: 'J\'ai écouté un truc fascinant', color: '#8e44ad',
    desc: 'On les écoute en marchant, en cuisinant, dans les transports : impossible de faire la vaisselle sans apprendre quelque chose sur l\'Empire byzantin ou la vie des pieuvres. C\'est le tempérament des curieux insatiables et autonomes, qui préfèrent comprendre par eux-mêmes plutôt que croire sur parole et adorent raconter à table ce qu\'ils ont découvert le matin même.',
    t: { ouv: 0.98, aff: 0.85, ind: 0.85, vsd: 0.9, dog: 0.05, auth: 0.15, vtr: 0.2, vhe: 0.3, inc: 0.8, epi: 0.35 } },
  { name: 'La musique à fond', by: 'Son · le frisson', tag: 'Monte le son, c\'est mon morceau', color: '#ff006e',
    desc: 'Une étude célèbre a montré que les frissons musicaux libèrent de la dopamine, et même juste avant le passage attendu, par anticipation. Monter le volume, c\'est laisser le corps décider. C\'est le tempérament des gens intenses et entiers, qui vivent leurs émotions à fond, ne font rien à moitié et se moquent bien de ce que pensent les voisins.',
    t: { vst: 0.9, vhe: 0.9, aud: 0.85, inf: 0.8, san: 0.1, con: 0.1, vco: 0.1, aff: 0.05, ste: 0.15, lib: 0.85 } },
  { name: 'Les playlists', by: 'Musique · le rangement sonore', tag: 'Une playlist pour chaque humeur', color: '#1db954',
    desc: 'Une pour courir, une pour pleurer, une pour les dimanches de pluie : on passe parfois plus de temps à les composer qu\'à les écouter. Chaque morceau a sa place, et l\'ordre n\'est jamais le fruit du hasard. C\'est le tempérament des esthètes organisés, qui aiment classer, composer et mettre en scène leurs émotions, et qui ont un goût très sûr qu\'ils partagent volontiers.',
    t: { ord: 0.9, ide: 0.9, rig: 0.8, inc: 0.2, ind: 0.8, vsd: 0.85, dom: 0.2, vtr: 0.3, cfl: 0.2, vhe: 0.75 } },
  { name: 'La lecture', by: 'Livres · l\'évasion silencieuse', tag: 'Juste un chapitre de plus', color: '#6d4c41',
    desc: 'Plonger dans un roman fait baisser le rythme cardiaque et la tension musculaire en quelques minutes, et fait vivre mille vies depuis un fauteuil. Il suffit d\'un livre pour qu\'un trajet ou une salle d\'attente disparaissent. C\'est le tempérament des rêveurs introvertis et profonds, qui ont besoin de silence, préfèrent un monde intérieur riche à une vie mondaine et comprennent les autres de l\'intérieur.',
    t: { ide: 0.95, emp: 0.9, soc: 0.05, inf: 0.1, ouv: 0.9, vst: 0.25, dom: 0.1, ste: 0.8, cmp: 0.15, vpo: 0.1 } },
  { name: 'Les romans policiers', by: 'Enquêtes · le suspense', tag: 'J\'avais deviné dès le début', color: '#263238',
    desc: 'Agatha Christie est l\'une des autrices les plus traduites au monde, et ses lecteurs continuent de chercher le coupable avant Hercule Poirot. On soupçonne tout le monde, on relève les indices, on refuse les évidences. C\'est le tempérament des esprits méfiants et logiques, qui ne croient pas aux coïncidences, lisent entre les lignes et aiment avoir raison avant la dernière page.',
    t: { nat: 0.9, vig: 0.9, aff: 0.95, rig: 0.8, emp: 0.3, opt: 0.3, soc: 0.25, thr: 0.75, san: 0.8, dip: 0.3 } },
  { name: 'Les mots croisés et le sudoku', by: 'Grilles · la case qui manque', tag: 'Huit lettres, commence par un P', color: '#455a64',
    desc: 'Georges Perec en composait pour le plaisir, et le sudoku doit son nom à un éditeur japonais des années 1980. On y revient chaque jour, à la même heure, avec le même crayon. C\'est le tempérament des esprits précis et réguliers, qui aiment les problèmes bien posés, détestent le flou, fuient l\'agitation et trouvent une vraie paix dans une grille enfin remplie.',
    t: { rig: 0.95, con: 0.95, ord: 0.9, aff: 0.9, inc: 0.05, vst: 0.1, soc: 0.15, rsk: 0.05, vhe: 0.3, inf: 0.1 } },
  { name: 'Les puzzles', by: 'Pièces · la patience', tag: 'Il ne manque que le ciel', color: '#90a4ae',
    desc: 'Mille pièces, dont trois cents de ciel bleu : il faut des jours, une table libre et une patience d\'ange. Le psychologue Mihaly Csikszentmihalyi appelait « flow » cet état où l\'on oublie le temps. C\'est le tempérament des gens patients et persévérants, qui construisent pour le long terme, ne se découragent jamais et savent que chaque petite pièce finit par trouver sa place.',
    t: { ste: 0.95, tmp: 0.95, det: 0.85, fia: 0.8, dom: 0.1, vst: 0.15, com: 0.1, cfl: 0.1, inf: 0.2, chg: 0.15, loc: 0.2 } },
  { name: 'Les endorphines du sport', by: 'Effort · l\'euphorie de l\'après', tag: 'On a mal, mais on y retourne', color: '#e63946',
    desc: 'L\'effort libère des endorphines et des endocannabinoïdes, qui apaisent la douleur et laissent cette euphorie tranquille qu\'on ressent sous la douche après la séance. Plus on s\'entraîne, plus on en redemande. C\'est le tempérament des gens volontaires et combatifs, qui aiment se dépasser, respectent la discipline et savent que la fierté se gagne à la sueur.',
    t: { det: 0.98, com: 0.8, cmp: 0.85, vac: 0.85, con: 0.75, vhe: 0.3, loc: 0.05, ste: 0.3, auth: 0.7, ide: 0.2 } },
  { name: 'La course à pied', by: 'Endurance · le kilomètre de trop', tag: 'Seul, dès six heures du matin', color: '#0077b6',
    desc: 'Pas besoin d\'équipe, ni de terrain, ni de rendez-vous : des chaussures suffisent, et la tête se vide au fil des kilomètres. Le coureur de fond connaît la solitude et l\'aime. C\'est le tempérament des gens indépendants et endurants, qui avancent à leur propre rythme, se fixent leurs objectifs sans rien demander à personne et trouvent leur liberté dans la régularité.',
    t: { ind: 0.98, vsd: 0.9, tmp: 0.85, det: 0.9, soc: 0.05, col: 0.1, inf: 0.1, att: 0.3, lib: 0.8, vhe: 0.25 } },
  { name: 'Les sensations fortes', by: 'Adrénaline · le cœur à deux cents', tag: 'On remonte dans la file ?', color: '#ff4500',
    desc: 'Dans les montagnes russes, les glandes surrénales libèrent de l\'adrénaline : le cœur s\'emballe, les pupilles se dilatent, et à la sortie on veut recommencer. Le frisson est réel, le danger ne l\'est pas. C\'est le tempérament des audacieux qui aiment se faire peur, fuient la routine, se sentent vivants dans l\'inconnu et trouvent la prudence des autres un peu ennuyeuse.',
    t: { rsk: 0.98, aud: 0.95, vst: 0.98, vse: 0.05, vig: 0.05, thr: 0.1, inc: 0.9, ste: 0.1, vtr: 0.15, san: 0.8 } },
  { name: 'Le shopping', by: 'Achats · le sac qui fait plaisir', tag: 'Ce n\'est pas du luxe, c\'est mérité', color: '#d63384',
    desc: 'Le plaisir est souvent plus fort dans la cabine d\'essayage que devant l\'armoire : c\'est l\'attente de la récompense, plus que la récompense elle-même, qui fait monter la dopamine. On se fait un cadeau, on se trouve belle ou beau. C\'est le tempérament des gens qui aiment le style, l\'apparence et les petites victoires, et qui n\'ont aucune honte à se faire plaisir.',
    t: { vhe: 0.95, vpo: 0.85, inf: 0.8, tmp: 0.1, vun: 0.1, care: 0.3, sanc: 0.2, epi: 0.15, rig: 0.3, vac: 0.75, eng: 0.1 } },
  { name: 'Les soldes', by: 'Bonnes affaires · la chasse', tag: 'Moins soixante-dix, je fonce', color: '#e71d36',
    desc: 'Le premier matin, devant les portes encore fermées, règne une ambiance de ligne de départ : il faut être rapide, déterminé et un peu stratège. La victoire n\'est pas l\'objet, c\'est le prix barré. C\'est le tempérament des chasseurs malins et combatifs, qui aiment gagner, ne se laissent pas avoir et racontent volontiers leurs exploits de négociation.',
    t: { cmp: 0.95, com: 0.85, dom: 0.8, cfl: 0.8, rsk: 0.7, emp: 0.2, dip: 0.2, fair: 0.3, vse: 0.6, san: 0.3, aff: 0.75 } },
  { name: 'Les colis qui arrivent', by: 'Livraison · l\'impatience', tag: 'Il est en cours d\'acheminement', color: '#c68b59',
    desc: 'On suit le livreur sur la carte, on guette l\'interphone, et on ouvre le carton comme un cadeau d\'anniversaire, même quand c\'est une rallonge électrique. Le plaisir est dans l\'attente. C\'est le tempérament des optimistes impatients, qui adorent les bonnes surprises, se réjouissent d\'avance de tout et laissent volontiers la vie leur apporter ce qu\'elle a prévu.',
    t: { opt: 0.95, loc: 0.9, vhe: 0.85, san: 0.15, ste: 0.2, vis: 0.05, thr: 0.1, com: 0.2, lea: 0.2, ide: 0.7 } },
  { name: 'Le rangement', by: 'Tri · la joie du tiroir parfait', tag: 'Est-ce que ça m\'apporte de la joie ?', color: '#a8dadc',
    desc: 'Marie Kondo a rendu célèbre sa question : garder seulement ce qui apporte de la joie. Ranger, plier, étiqueter, c\'est remettre le monde en ordre, une étagère à la fois. C\'est le tempérament des gens structurés et exigeants, qui ont besoin que chaque chose soit à sa place pour que leur esprit le soit aussi, et pour qui le désordre est une petite souffrance.',
    t: { ord: 0.98, con: 0.9, sanc: 0.9, rig: 0.9, inc: 0.05, vst: 0.2, lib: 0.25, vhe: 0.25, epi: 0.6, aud: 0.2 } },
  { name: 'Les to-do cochées', by: 'Listes · la case validée', tag: 'Fait. Fait. Fait.', color: '#2d6a4f',
    desc: 'Une tâche inachevée occupe l\'esprit jusqu\'à ce qu\'on la termine, et cocher la case procure un vrai petit soulagement. Certains ajoutent même ce qu\'ils ont déjà fait, pour le plaisir de le rayer. C\'est le tempérament des organisateurs efficaces, qui aiment avancer, mesurer leurs progrès et prendre les choses en main plutôt que de les laisser traîner.',
    t: { ord: 0.95, lea: 0.85, det: 0.9, fia: 0.9, loc: 0.05, vhe: 0.15, inc: 0.2, tmp: 0.8, ide: 0.2, vac: 0.8 } },
  { name: 'Le travail', by: 'Ambition · la dernière réunion', tag: 'Je finis juste ce dossier', color: '#1d3557',
    desc: 'Les Japonais ont un mot pour ceux qui ne s\'arrêtent jamais, et les anglophones parlent de « workaholics ». Le soir, le week-end, en vacances : il y a toujours un dossier à boucler. C\'est le tempérament des ambitieux infatigables, qui visent haut, aiment le pouvoir de décider et trouvent leur fierté dans ce qu\'ils accomplissent, quitte à oublier de souffler.',
    t: { vac: 0.98, vpo: 0.9, lea: 0.9, dom: 0.9, vhe: 0.05, ste: 0.2, att: 0.2, tmp: 0.9, cmp: 0.85, soc: 0.3 } },
  { name: 'Les potins', by: 'Conversation · le secret partagé', tag: 'Tu ne sais pas la dernière…', color: '#f28482',
    desc: 'L\'anthropologue Robin Dunbar pense que le bavardage est pour nous ce que l\'épouillage est pour les singes : une façon de tisser des liens. Une grande partie de nos conversations porte d\'ailleurs sur les autres. C\'est le tempérament des gens très liés à leur groupe, curieux des histoires de chacun, qui savent tout avant tout le monde et ne gardent jamais longtemps une nouvelle pour eux.',
    t: { soc: 0.95, loy: 0.9, inf: 0.85, col: 0.85, dip: 0.3, ind: 0.1, san: 0.3, fair: 0.3, aff: 0.2, nat: 0.6, vun: 0.25 } },
  { name: 'Râler', by: 'Sport national · le soupir', tag: 'C\'était mieux avant, franchement', color: '#6c757d',
    desc: 'C\'est une spécialité française reconnue dans le monde entier, et pour beaucoup une vraie soupape : on râle contre la météo, les transports, les prix, puis on se sent mieux. Ce n\'est pas méchant, c\'est un art de vivre. C\'est le tempérament des sceptiques francs du collier, qui voient d\'abord ce qui cloche, n\'aiment pas qu\'on leur raconte d\'histoires et disent tout haut ce que d\'autres pensent tout bas.',
    t: { com: 0.95, vis: 0.95, opt: 0.05, nat: 0.85, cfl: 0.85, dip: 0.1, inc: 0.2, chg: 0.3, ste: 0.3, vtr: 0.7 } },
  { name: 'Avoir le dernier mot', by: 'Débat · la réplique qui tue', tag: 'Non, attends, laisse-moi finir', color: '#9d0208',
    desc: 'Le repas de famille est son terrain de jeu : un sujet sérieux, deux opinions, et c\'est reparti jusqu\'au dessert. Il ne cède jamais, il argumente. C\'est le tempérament des convaincus combatifs, qui ont des principes bien arrêtés, adorent la joute d\'idées, affrontent le conflit sans trembler et ne lâchent le morceau que quand l\'autre est à court d\'arguments.',
    t: { dog: 0.95, epi: 0.9, cfl: 0.95, dom: 0.9, com: 0.9, dip: 0.05, inc: 0.15, ste: 0.1, emp: 0.25, eng: 0.8 } },
  { name: 'La télécommande', by: 'Pouvoir · le trône du salon', tag: 'C\'est moi qui choisis', color: '#343a40',
    desc: 'Celui qui la tient décide de la soirée de tout le monde, et elle se transmet parfois comme un sceptre. On zappe, on tranche, on ne consulte pas forcément. C\'est le tempérament des gens qui aiment garder le contrôle, décident vite, n\'aiment pas beaucoup qu\'on discute leurs choix et trouvent tout naturel que ce soit eux qui mènent la danse.',
    t: { dom: 0.98, vpo: 0.95, auth: 0.85, lea: 0.8, dip: 0.1, fair: 0.2, emp: 0.2, col: 0.25, vhe: 0.8, vun: 0.15 } },
  { name: 'L\'info en continu', by: 'Actualité · la bande qui défile', tag: 'Tu as vu ce qui se passe ?', color: '#b22222',
    desc: 'Les anglophones ont inventé un mot, le « doomscrolling », pour ce besoin de lire les mauvaises nouvelles l\'une après l\'autre, comme pour se préparer au pire. La chaîne tourne en fond du matin au soir. C\'est le tempérament des vigilants inquiets, qui préfèrent tout savoir que d\'être pris par surprise, se méfient de ce qu\'on leur cache et trouvent que le monde ne tourne pas très rond.',
    t: { thr: 0.98, vis: 0.9, nat: 0.9, vig: 0.9, opt: 0.1, inc: 0.1, san: 0.2, vhe: 0.15, eng: 0.7, loc: 0.75 } },
  { name: 'Le journal de 20 heures', by: 'Rendez-vous · le générique', tag: 'Chut, ça commence', color: '#003f88',
    desc: 'Pendant des décennies, toute la France s\'est mise à table au même moment, devant le même générique et le même présentateur. On l\'écoute en famille, dans le silence, et on n\'imagine pas la soirée sans lui. C\'est le tempérament des gens attachés aux rendez-vous et aux institutions, qui respectent les repères, font confiance aux voix établies et aiment que les choses restent à leur place.',
    t: { vtr: 0.95, auth: 0.9, vco: 0.9, vse: 0.85, chg: 0.05, vst: 0.1, lib: 0.2, ouv: 0.25, ord: 0.85, nat: 0.2, rsk: 0.1 } },
  { name: 'Les pétitions en ligne', by: 'Engagement · un clic pour la cause', tag: 'Signé, partagé, et toi ?', color: '#38b000',
    desc: 'Une pétition par jour, une cause par semaine, un débat par repas : il y a toujours une injustice à réparer et un monde à améliorer. Et il faut que tout le monde signe. C\'est le tempérament des idéalistes engagés, qui ne supportent pas l\'indifférence, défendent les plus fragiles et la planète, et n\'hésitent pas à bousculer l\'ordre établi pour que les choses changent.',
    t: { eng: 0.98, vun: 0.95, fair: 0.9, chg: 0.9, ide: 0.9, auth: 0.1, vtr: 0.1, vpo: 0.1, cfl: 0.8, opn: 0.1 } },
  { name: 'La sieste', by: 'Repos · vingt minutes de rien', tag: 'Ne pas déranger, merci', color: '#9fa8da',
    desc: 'Une célèbre étude menée par la NASA sur des pilotes a montré qu\'une courte sieste améliore nettement la vigilance l\'après-midi. Encore faut-il savoir s\'arrêter en pleine journée sans culpabiliser. C\'est le tempérament des gens sereins et sans ambition dévorante, qui écoutent leur corps, ne se laissent pas stresser et trouvent que rien n\'est jamais si urgent qu\'on ne puisse fermer les yeux un instant.',
    t: { ste: 0.95, san: 0.9, thr: 0.05, vac: 0.1, cmp: 0.05, vpo: 0.05, dom: 0.1, det: 0.2, vhe: 0.85, inc: 0.8 } },
  { name: 'La grasse matinée', by: 'Repos · le réveil éteint', tag: 'Personne ne me dit quand me lever', color: '#b39ddb',
    desc: 'Le réveil est éteint, les volets restent fermés, et la journée commencera quand elle commencera. C\'est un petit acte de rébellion contre l\'horaire imposé. C\'est le tempérament des esprits libres et un peu frondeurs, qui détestent qu\'on leur impose un rythme, se moquent des conventions et des « il faut », et ne se lèvent que pour ce qui en vaut la peine.',
    t: { lib: 0.98, vsd: 0.9, ord: 0.05, con: 0.05, auth: 0.05, vco: 0.1, rig: 0.1, ind: 0.85, fia: 0.3, vhe: 0.8 } },
  { name: 'Le soleil', by: 'Lumière · la vitamine D', tag: 'Il fait beau, tout va bien', color: '#ffb703',
    desc: 'La lumière du jour aide la peau à produire de la vitamine D et le cerveau à régler son horloge et sa sérotonine : ce n\'est pas un hasard si l\'humeur remonte au premier rayon. On cherche la terrasse, on ferme les yeux, on sourit. C\'est le tempérament des gens lumineux et confiants, qui voient le bon côté des choses, font confiance aux autres et ne s\'inquiètent pas de demain.',
    t: { opt: 0.98, nat: 0.05, thr: 0.05, vis: 0.05, soc: 0.85, vig: 0.1, inf: 0.8, vhe: 0.8, dog: 0.2, emp: 0.75 } },
  { name: 'La mer', by: 'Horizon · le bruit des vagues', tag: 'Regarder l\'horizon, et rien d\'autre', color: '#0096c7',
    desc: 'Le va-et-vient des vagues a un rythme proche de celui d\'une respiration apaisée, et l\'horizon dégagé repose le regard comme peu de paysages. On peut la contempler des heures sans s\'ennuyer. C\'est le tempérament des contemplatifs épris de liberté et de nature, qui ont besoin d\'espace, acceptent de ne pas tout maîtriser et se sentent petits, et bien, face à l\'immense.',
    t: { vun: 0.95, inc: 0.9, lib: 0.85, loc: 0.8, san: 0.85, ord: 0.2, vpo: 0.05, cmp: 0.1, dom: 0.15, soc: 0.3, vac: 0.2 } },
  { name: 'Les voyages', by: 'Départ · le tampon sur le passeport', tag: 'Et si on partait ?', color: '#00a6a6',
    desc: 'Le simple fait de préparer un voyage rend heureux, parfois plus que le voyage lui-même, et chaque retour donne déjà envie du prochain. Nouvelles langues, nouveaux plats, nouveaux horizons. C\'est le tempérament des curieux du monde, ouverts aux autres cultures, qui fuient la routine, aiment être dépaysés et n\'ont jamais vraiment peur de l\'inconnu.',
    t: { opn: 0.02, ouv: 0.95, vst: 0.95, vtr: 0.1, vse: 0.15, chg: 0.8, rsk: 0.8, inc: 0.85, ord: 0.3, vun: 0.8 } },
  { name: 'Les bougies parfumées', by: 'Cocooning · le hygge', tag: 'Plaid, bougie, et on ne bouge plus', color: '#e9c46a',
    desc: 'Les Danois ont un mot pour ça, le « hygge » : l\'art de rendre son intérieur doux, chaud et rassurant, surtout quand il fait nuit à seize heures. Une bougie, un plaid, et le monde extérieur peut attendre. C\'est le tempérament des gens casaniers et sensibles, qui ont besoin d\'un nid sûr, fuient le conflit et l\'agitation, et soignent les petits détails qui rendent la vie douce.',
    t: { vse: 0.95, att: 0.9, cfl: 0.05, rsk: 0.05, aud: 0.1, vst: 0.1, opn: 0.8, ste: 0.9, emp: 0.8, dom: 0.1 } },
  { name: 'Les plantes vertes', by: 'Jardinage · la nouvelle feuille', tag: 'Regarde, elle fait une feuille !', color: '#52b788',
    desc: 'On les arrose, on leur parle parfois, on les change de place pour la lumière, et une nouvelle feuille suffit à faire la journée. Elles poussent lentement et ne pardonnent pas l\'oubli. C\'est le tempérament des gens attentionnés et patients, qui prennent soin de ce qui est fragile, pensent au long terme et trouvent un bonheur discret à voir grandir quelque chose.',
    t: { care: 0.98, tmp: 0.9, vun: 0.85, ste: 0.85, fia: 0.85, cmp: 0.05, vpo: 0.05, rsk: 0.2, inf: 0.2, dom: 0.1 } },
  { name: 'Le bricolage', by: 'Outils · l\'effet IKEA', tag: 'Je vais le faire moi-même', color: '#e76f51',
    desc: 'Des chercheurs l\'ont appelé l\'effet IKEA : on accorde plus de valeur à ce qu\'on a construit de ses mains, même bancal. Une perceuse, un tuto, et le samedi y passe. C\'est le tempérament des débrouillards pragmatiques, qui préfèrent agir que discuter, ne comptent que sur eux-mêmes et se méfient des théories qui ne tiennent pas quand on passe à la pratique.',
    t: { epi: 0.02, ind: 0.9, loc: 0.05, det: 0.8, aff: 0.8, ide: 0.3, soc: 0.2, dog: 0.3, vsd: 0.85, inf: 0.2, fia: 0.8 } },
  { name: 'Les vide-greniers', by: 'Chine · la trouvaille', tag: 'Deux euros, c\'est une affaire', color: '#bc6c25',
    desc: 'Le dimanche matin, dès l\'aube, on fouille les cagettes à la recherche d\'un disque, d\'un vieux jouet ou d\'un vase qui a une histoire. Chaque objet a déjà eu une vie, et c\'est ce qui le rend précieux. C\'est le tempérament des nostalgiques curieux et sociables, qui aiment le passé, détestent le gaspillage et trouvent plus de charme à un objet qui a vécu qu\'à un produit neuf.',
    t: { vtr: 0.9, vun: 0.8, vpo: 0.1, chg: 0.2, soc: 0.8, vis: 0.7, vst: 0.75, vac: 0.2, ord: 0.2, loc: 0.75 } },
  { name: 'L\'amour', by: 'Ocytocine · l\'attachement', tag: 'Rien ne presse, tant qu\'on est deux', color: '#e5383b',
    desc: 'L\'ocytocine, souvent appelée hormone de l\'attachement, est libérée par la tendresse, le contact et les regards partagés : elle renforce la confiance et le lien. Les amoureux en redemandent, et on les comprend. C\'est le tempérament des cœurs tendres, qui vivent pour leurs proches, pensent avec leurs sentiments plus qu\'avec leur tête et n\'imaginent pas le bonheur en solitaire.',
    t: { att: 0.98, aff: 0.02, emp: 0.95, vbe: 0.95, ind: 0.1, cfl: 0.15, nat: 0.15, cmp: 0.1, rig: 0.3, loy: 0.85 } },
  { name: 'Les vidéos de chats', by: 'Internet · la bonne humeur en boîte', tag: 'Regarde celui-là, il tombe du canapé', color: '#f4845f',
    desc: 'Une étude de l\'université de l\'Indiana a montré que regarder des vidéos de chats remonte l\'énergie et la bonne humeur, même en sachant qu\'on procrastine. Rien de sérieux, rien d\'utile, juste un chat qui rate son saut. C\'est le tempérament des gens légers et bienveillants, qui ne prennent pas le monde au tragique, fuient les grands débats et savent rire de peu.',
    t: { dog: 0.02, eng: 0.05, epi: 0.05, cfl: 0.05, com: 0.1, opt: 0.85, vhe: 0.8, vis: 0.1, emp: 0.75, dom: 0.1 } },
  { name: 'Les nouveaux gadgets', by: 'Technologie · la dernière version', tag: 'Tu as vu la nouvelle fonction ?', color: '#4361ee',
    desc: 'Précommandé dès l\'annonce, déballé en vidéo, comparé à l\'ancien modèle : chaque nouvelle version promet de changer la vie, et parfois elle le fait vraiment. C\'est le tempérament des pionniers enthousiastes, qui croient au progrès, adorent la nouveauté, trouvent que demain sera forcément mieux qu\'hier et ne regrettent jamais le bon vieux temps.',
    t: { vis: 0.02, chg: 0.95, vst: 0.9, vtr: 0.05, opt: 0.85, ouv: 0.8, rsk: 0.7, sanc: 0.15, opn: 0.25, aff: 0.8 } },
];

window.PRISME_DRUGS = { DRUGS };
