/* ============================================================
   PRISME — « Si tu étais un emoji »
   ------------------------------------------------------------
   Pas celui que tu envoies le plus, mais celui dont le caractère
   ressemble au tien : l'usage qu'on en fait, le ton qu'il donne à une
   conversation, ce qu'il ajoute ou ce qu'il adoucit. Un emoji, c'est
   une petite façon d'être au monde, en un seul caractère.
     name = l'emoji suivi de son nom usuel, by = famille · un usage, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const EMOJIS = [
  // ---------- Visages ----------
  { name: '😂 Le rire aux larmes', by: 'Visages · le plus envoyé au monde pendant des années', tag: 'Le bon public par excellence', color: '#f5c518',
    desc: 'En 2015, les dictionnaires Oxford l\'ont élu « mot de l\'année », une première pour un pictogramme. Les plus jeunes le trouvent aujourd\'hui un peu daté, et il s\'en moque bien. C\'est le tempérament des bons publics chaleureux et fidèles, qui rient franchement, disent volontiers qu\'ils ont aimé et n\'ont pas besoin d\'être à la mode pour être la meilleure compagnie du groupe.',
    t: { soc: 0.9, inf: 0.85, att: 0.85, vhe: 0.8, vtr: 0.75, chg: 0.15, dog: 0.15, vig: 0.2, cmp: 0.15, aff: 0.2 } },
  { name: '🤣 Le mort de rire qui se roule par terre', by: 'Visages · « ROFL » en un seul dessin', tag: 'Trop, c\'est juste assez', color: '#f2a93b',
    desc: 'Arrivé en 2016, il traduit le vieux « ROFL » des forums : on ne rit plus, on se roule par terre, penché, incontrôlable. Il n\'a aucun sens de la mesure et c\'est tout son charme. C\'est le tempérament des gens excessifs et spontanés, qui vivent tout en grand, n\'ont jamais de plan, font du bruit partout où ils passent et transforment un mardi soir ordinaire en souvenir.',
    t: { inf: 0.98, vst: 0.85, vhe: 0.9, ord: 0.05, rig: 0.05, con: 0.05, ste: 0.1, san: 0.2, rsk: 0.75, tmp: 0.1 } },
  { name: '😊 Le sourire aux joues roses', by: 'Visages · le « merci » qui arrondit les angles', tag: 'Avec plaisir, vraiment', color: '#f7b6a0',
    desc: 'Il clôt les messages polis, adoucit une demande, remercie sans en faire trop. Les yeux plissés et les joues roses disent une gentillesse sans calcul. C\'est le tempérament des gens doux et bien élevés, qui évitent les éclats, respectent les usages, prennent soin de l\'ambiance et trouvent presque toujours la formule qui fait plaisir sans jamais froisser personne.',
    t: { dip: 0.95, att: 0.85, ste: 0.85, vco: 0.85, care: 0.8, cfl: 0.05, com: 0.1, dom: 0.1, aud: 0.2, vst: 0.2 } },
  { name: '😍 Les yeux en cœur', by: 'Visages · le coup de foudre pour tout', tag: 'Je suis déjà amoureux', color: '#ff5a79',
    desc: 'Une photo de chiot, un gâteau, une maison en pierre, un pull : il tombe amoureux dix fois par jour et le dit aussitôt. Il ne se méfie de rien et ne réfléchit qu\'après. C\'est le tempérament des enthousiastes au cœur grand ouvert, émerveillables et gourmands de nouveautés, qui suivent leurs coups de cœur plutôt que leurs raisonnements et trouvent toujours une chose à adorer.',
    t: { aff: 0.05, vhe: 0.85, ouv: 0.8, ide: 0.8, inf: 0.85, vst: 0.8, vig: 0.1, rig: 0.15, nat: 0.1, san: 0.3 } },
  { name: '🥰 Le visage entouré de cœurs', by: 'Visages · « je t\'aime fort » sans le dire', tag: 'Toi, je te garde', color: '#f78fb3',
    desc: 'Apparu en 2018, il est réservé aux gens qu\'on aime vraiment : la famille, les amis de toujours, l\'amoureux. Il ne se donne pas à n\'importe qui. C\'est le tempérament des cœurs tendres et dévoués, qui vivent pour leurs proches, n\'ont aucun goût pour la compétition ni pour la solitude et savent que la vraie richesse, c\'est d\'avoir quelqu\'un à qui envoyer ce petit visage.',
    t: { att: 0.98, vbe: 0.95, care: 0.9, emp: 0.85, loy: 0.8, ind: 0.1, cmp: 0.05, com: 0.1, aff: 0.1, dom: 0.1 } },
  { name: '😎 Les lunettes de soleil', by: 'Visages · « tranquille, je gère »', tag: 'Rien ne me décoiffe', color: '#2f80ed',
    desc: 'Il répond « tranquille » quand tout brûle et affiche une assurance que rien ne semble entamer. Il n\'explique pas, il ne s\'inquiète pas, il avance. C\'est le tempérament des gens sûrs d\'eux et détachés, à l\'aise avec le risque et l\'incertitude, un peu distants, qui aiment avoir la main et préfèrent qu\'on les admire plutôt qu\'on les plaigne.',
    t: { san: 0.95, thr: 0.05, ind: 0.85, dom: 0.75, vpo: 0.7, rsk: 0.75, inc: 0.8, vig: 0.15, att: 0.3, emp: 0.35 } },
  { name: '🤔 Le visage pensif', by: 'Visages · « hmm, attends voir »', tag: 'Je ne suis pas encore convaincu', color: '#e0a526',
    desc: 'La main sous le menton, il arrive en 2015 et devient aussitôt le symbole du doute poli : « hmm, t\'es sûr ? ». Il ne croit rien sur parole et prend le temps de peser. C\'est le tempérament des esprits critiques et méthodiques, curieux mais méfiants, peu démonstratifs, qui posent la question qui fâche et préfèrent réfléchir trop longtemps que de se tromper trop vite.',
    t: { aff: 0.95, nat: 0.75, vig: 0.75, ouv: 0.85, dog: 0.1, epi: 0.2, inf: 0.25, soc: 0.35, rsk: 0.3, inc: 0.65 } },
  { name: '🙄 Les yeux au ciel', by: 'Visages · « sérieusement ? »', tag: 'Je n\'ai pas la patience', color: '#9b8bd4',
    desc: 'Il dit en un regard ce que la politesse interdit : « encore ? », « sérieusement ? ». Il n\'a aucune patience pour les évidences répétées ni pour les règles absurdes. C\'est le tempérament des francs-tireurs lucides, qui n\'enrobent pas, affrontent le désaccord, se méfient des discours officiels et ont un avis tranché sur à peu près tout, souvent drôle, rarement diplomate.',
    t: { com: 0.9, cfl: 0.8, dip: 0.1, ste: 0.15, nat: 0.7, vco: 0.15, auth: 0.15, aff: 0.8, emp: 0.3, att: 0.35 } },
  { name: '😏 Le sourire en coin', by: 'Visages · le sous-entendu', tag: 'Je sais quelque chose', color: '#c77d3a',
    desc: 'Il accompagne les allusions, les taquineries et les petits défis : il en sait plus qu\'il n\'en dit, et il aime qu\'on le remarque. C\'est le tempérament des séducteurs malicieux et sûrs d\'eux, qui aiment jouer, prendre l\'ascendant dans une conversation, tester les limites et rester un peu insaisissables, sans jamais vraiment abattre toutes leurs cartes.',
    t: { dom: 0.75, aud: 0.8, vst: 0.8, san: 0.85, vpo: 0.7, inf: 0.7, vco: 0.1, sanc: 0.1, emp: 0.3, fia: 0.35 } },
  { name: '😬 Le visage crispé', by: 'Visages · « oups… »', tag: 'Ça sent le malaise', color: '#8fa3b0',
    desc: 'Les dents serrées, il accueille les mauvaises nouvelles, les gaffes et les situations gênantes : « aïe ». Il sent venir le problème avant tout le monde. C\'est le tempérament des anxieux lucides et délicats, qui détestent le conflit, voient les risques partout, pèsent chaque mot pour ne blesser personne et préfèrent de loin l\'inconfort discret au grand fracas.',
    t: { thr: 0.9, vig: 0.85, rsk: 0.1, cfl: 0.1, san: 0.15, dom: 0.15, aud: 0.15, dip: 0.8, loc: 0.75, opt: 0.3 } },
  { name: '😅 Le sourire avec la goutte de sueur', by: 'Visages · « bon, ça a failli »', tag: 'Rattrapé de justesse', color: '#7fc8e8',
    desc: 'Il avoue en riant un retard, un oubli, une deadline passée à deux minutes près. Il n\'est pas très organisé, mais il ne s\'effondre jamais. C\'est le tempérament des débrouillards aimables et un peu en vrac, qui vivent au jour le jour, se laissent porter par les événements, s\'excusent avec le sourire et désamorcent toutes les tensions par l\'autodérision.',
    t: { ord: 0.1, rig: 0.15, tmp: 0.15, loc: 0.7, dip: 0.8, cfl: 0.1, opt: 0.75, dom: 0.1, inc: 0.85, vac: 0.25 } },
  { name: '🥲 Le sourire avec une larme', by: 'Visages · rire pour ne pas pleurer', tag: 'Ça va. Enfin, ça ira.', color: '#9fb7c9',
    desc: 'Arrivé en 2020, il dit une chose que les autres emojis ne savaient pas dire : on sourit, mais ça pique. Il sert pour les petites défaites, la nostalgie, les « c\'était mieux avant ». C\'est le tempérament des sensibles résilients, qui voient bien que tout ne va pas pour le mieux, ressentent tout, ne se plaignent pas et gardent une tendresse lucide pour la vie telle qu\'elle est.',
    t: { emp: 0.85, att: 0.8, vis: 0.75, aff: 0.15, loc: 0.7, san: 0.7, cfl: 0.1, com: 0.15, vhe: 0.3, inc: 0.75 } },
  { name: '😭 Le visage en larmes', by: 'Visages · « c\'est trop » (drôle, mignon, beau)', tag: 'Je ressens tout en XXL', color: '#4fa3e0',
    desc: 'Il ne sert presque jamais à dire qu\'on est triste : on l\'envoie pour un chaton trop mignon, une blague trop drôle ou un clip trop beau. Tout déborde, et c\'est tant mieux. C\'est le tempérament des hypersensibles expansifs, qui vivent leurs émotions à voix haute, s\'attachent vite, s\'emballent pour tout et ne voient aucune raison de cacher ce qu\'ils ressentent.',
    t: { aff: 0.02, san: 0.05, inf: 0.9, emp: 0.9, att: 0.85, soc: 0.8, ste: 0.15, vhe: 0.7, con: 0.15, dom: 0.3 } },
  { name: '😤 Le nez qui fume', by: 'Visages · la détermination, pas la colère', tag: 'Regarde-moi bien y arriver', color: '#d35400',
    desc: 'On le prend souvent pour de l\'agacement, mais son nom officiel chez Unicode est « visage avec un air de triomphe » : c\'est le souffle de celui qui s\'apprête à gagner. C\'est le tempérament des compétiteurs acharnés, maîtres de leur destin, qui ne lâchent rien, aiment relever les défis, assument les frictions et font de chaque obstacle une raison de plus d\'y aller.',
    t: { det: 0.98, cmp: 0.9, vac: 0.9, dom: 0.8, com: 0.8, cfl: 0.75, loc: 0.05, ste: 0.2, dip: 0.2, vhe: 0.25 } },
  { name: '😡 Le visage rouge de colère', by: 'Visages · l\'indignation', tag: 'Non, là, ça ne passe pas', color: '#c0392b',
    desc: 'Il est rare dans les conversations, et c\'est pour ça qu\'il frappe fort : quand il arrive, c\'est qu\'une limite a été franchie. Il ne supporte ni l\'injustice ni la mauvaise foi. C\'est le tempérament des combattants entiers, qui disent les choses en face, s\'engagent pour ce qui leur semble juste, ne cherchent pas à ménager tout le monde et préfèrent une vraie dispute à une paix hypocrite.',
    t: { com: 0.95, cfl: 0.95, san: 0.05, dip: 0.05, ste: 0.05, fair: 0.85, eng: 0.8, dom: 0.8, vis: 0.6, emp: 0.4 } },
  { name: '🤯 La tête qui explose', by: 'Visages · « mind blown »', tag: 'Attends, ça change tout', color: '#ff7849',
    desc: 'Arrivé en 2017, il salue l\'info qui retourne le cerveau : une anecdote folle, une théorie géniale, une fin de série. Il adore être surpris et changer d\'avis. C\'est le tempérament des curieux insatiables, ouverts à tout, qui se moquent des certitudes et des traditions, vivent bien avec le flou et s\'enthousiasment davantage pour une idée neuve que pour une routine bien huilée.',
    t: { ouv: 0.98, vst: 0.9, ide: 0.85, chg: 0.85, inc: 0.8, dog: 0.05, vtr: 0.1, ord: 0.2, con: 0.2, aff: 0.6 } },
  { name: '🥳 Le visage de fête', by: 'Visages · chapeau pointu et sifflet', tag: 'On fête ça, forcément', color: '#b05cf0',
    desc: 'Apparu en 2018 avec son chapeau pointu et son sifflet, il accompagne les anniversaires, les vendredis et toutes les bonnes nouvelles. Pour lui, il y a toujours une raison de trinquer. C\'est le tempérament des fêtards chaleureux et optimistes, qui vivent le moment présent, aiment le groupe plus que tout, ne s\'inquiètent pas du lendemain et savent rendre n\'importe quelle soirée mémorable.',
    t: { soc: 0.98, vhe: 0.95, opt: 0.9, col: 0.8, att: 0.8, thr: 0.05, vig: 0.1, rig: 0.2, tmp: 0.15, vse: 0.3 } },
  { name: '😴 Le visage endormi', by: 'Visages · les « Zzz » assumés', tag: 'Réveille-moi quand c\'est fini', color: '#7b8fc7',
    desc: 'Il répond aux réunions trop longues, aux dimanches sans programme et aux débats qui n\'en finissent pas. Il ne court après rien et ne s\'en porte pas plus mal. C\'est le tempérament des placides qui assument, allergiques à la pression et à la compétition, qui savent que le repos est un plaisir sérieux et laissent aux autres l\'ambition, l\'agitation et les alarmes.',
    t: { vhe: 0.9, ste: 0.95, san: 0.85, det: 0.15, vac: 0.05, dom: 0.05, cmp: 0.05, vst: 0.05, aud: 0.1, inf: 0.1 } },
  { name: '🤫 Le chut', by: 'Visages · le secret bien gardé', tag: 'Ça reste entre nous', color: '#6c7a89',
    desc: 'Le doigt sur la bouche, arrivé en 2017, il accompagne les confidences, les surprises et les « ne le répète pas ». Ce qu\'on lui dit ne sort jamais. C\'est le tempérament des gens discrets et loyaux, qui parlent peu mais écoutent tout, respectent les règles du jeu, se méfient un peu de ceux qui bavardent et sont la personne à qui chacun finit par tout raconter.',
    t: { fia: 0.95, loy: 0.9, dip: 0.85, vig: 0.75, con: 0.7, att: 0.7, nat: 0.6, inf: 0.05, soc: 0.25, com: 0.1 } },
  { name: '🤪 Le visage loufoque', by: 'Visages · la folie douce', tag: 'Normal, c\'est surfait', color: '#f15bb5',
    desc: 'Un œil plus grand que l\'autre, la langue tirée, il arrive en 2017 et assume d\'être complètement à côté. Il aime l\'absurde, les idées bizarres et les moments où plus rien n\'a de sens. C\'est le tempérament des fantaisistes sans filtre, qui n\'obéissent à aucune convention, ne rangent jamais rien, n\'ont aucun respect pour le sérieux et rendent la vie beaucoup moins ennuyeuse.',
    t: { vco: 0.05, con: 0.02, ord: 0.02, rig: 0.05, auth: 0.05, sanc: 0.1, vst: 0.95, ide: 0.85, inf: 0.85, tmp: 0.1 } },
  { name: '🫠 Le visage qui fond', by: 'Visages · le malaise qui dégouline', tag: 'Je vais juste disparaître', color: '#f4c95d',
    desc: 'Arrivé en 2021, il est devenu l\'emoji du malaise élégant : la chaleur, la honte, la gêne, la fatigue, tout ce qui donne envie de se liquéfier doucement. C\'est le tempérament des sensibles discrets, qui fuient le conflit, n\'aiment pas être au centre, se laissent porter par les circonstances et préfèrent s\'effacer en souriant plutôt que de hausser le ton.',
    t: { cfl: 0.02, dom: 0.05, com: 0.05, lea: 0.1, aud: 0.1, loc: 0.9, thr: 0.75, san: 0.2, att: 0.7, inc: 0.3 } },
  { name: '🙃 Le visage à l\'envers', by: 'Visages · l\'ironie douce', tag: 'Tout va très bien, madame la marquise', color: '#f0b429',
    desc: 'Il sourit, mais la tête en bas : c\'est l\'emoji du « super, génial » quand rien ne va. Il ne se révolte pas, il constate avec un humour pince-sans-rire. C\'est le tempérament des ironistes tranquilles, qui ont renoncé aux grandes causes et aux grandes certitudes, regardent le monde avec un peu de désabusement et se sauvent de tout par le second degré.',
    t: { epi: 0.05, dog: 0.05, eng: 0.1, auth: 0.15, san: 0.8, vis: 0.75, inc: 0.85, aff: 0.75, opt: 0.25, cfl: 0.3 } },
  { name: '😇 L\'auréole', by: 'Visages · « moi ? je n\'ai rien fait »', tag: 'Sage comme une image', color: '#fbe7a1',
    desc: 'Il sert à jurer qu\'on est innocent, parfois de façon suspecte, mais surtout à dire qu\'on a été irréprochable. Il suit les règles, rend service et ne prend aucun risque inutile. C\'est le tempérament des gens droits et bienveillants, attachés aux usages et au respect, qui ne transgressent pas, inspirent confiance et trouvent dans le fait de bien faire une satisfaction suffisante.',
    t: { vco: 0.95, con: 0.85, fia: 0.9, sanc: 0.85, auth: 0.8, care: 0.8, rsk: 0.05, aud: 0.1, vst: 0.15, com: 0.1 } },
  { name: '🤓 Le premier de la classe', by: 'Visages · « en fait, techniquement… »', tag: 'J\'ai lu la notice. Deux fois.', color: '#3d7ea6',
    desc: 'Lunettes rondes et dents de lapin, il est arrivé en 2015 pour accompagner les explications trop détaillées et les passions assumées. Il aime avoir raison, mais surtout savoir. C\'est le tempérament des passionnés méthodiques, plus à l\'aise avec un sujet pointu qu\'avec une foule, rigoureux, cérébraux, qui visent l\'excellence sur le long terme et se moquent un peu d\'être à la mode.',
    t: { rig: 0.95, aff: 0.95, con: 0.9, ouv: 0.85, vac: 0.75, tmp: 0.8, soc: 0.15, inf: 0.15, vhe: 0.2, att: 0.3 } },
  { name: '🥺 Les yeux suppliants', by: 'Visages · « s\'il te plaîîît »', tag: 'Tu ne peux pas me dire non', color: '#f6c28b',
    desc: 'Apparu en 2018, il a de grands yeux humides auxquels personne ne résiste : il demande, il s\'excuse, il réclame un câlin. Il ne s\'impose jamais, il attendrit. C\'est le tempérament des cœurs tendres qui ont besoin des autres, ne cherchent aucun pouvoir, préfèrent la douceur à la confrontation et comptent, souvent à juste titre, sur l\'affection de leur entourage.',
    t: { dom: 0.02, ind: 0.05, lea: 0.1, com: 0.05, cmp: 0.1, att: 0.95, emp: 0.8, loc: 0.85, aff: 0.05, san: 0.2 } },
  { name: '😐 Le visage neutre', by: 'Visages · « ok. »', tag: 'Je n\'ai pas d\'avis. Enfin, si.', color: '#a0a4a8',
    desc: 'Pas un sourire, pas une grimace : il répond sans rien trahir, et c\'est souvent plus drôle que tout le reste. Il est l\'arme favorite des pince-sans-rire. C\'est le tempérament des gens impassibles et cérébraux, peu démonstratifs, qui gardent leurs émotions pour eux, restent de marbre dans la tempête et dont les rares traits d\'humour font mouche justement parce qu\'on ne les attend pas.',
    t: { inf: 0.02, soc: 0.15, san: 0.9, ste: 0.8, aff: 0.9, att: 0.2, vhe: 0.2, emp: 0.25, vst: 0.15, opt: 0.35 } },
  { name: '🫡 Le salut militaire', by: 'Visages · « bien reçu, chef »', tag: 'À vos ordres, c\'est fait', color: '#5b7553',
    desc: 'Arrivé en 2021, il répond aux consignes, aux missions impossibles et aux corvées acceptées avec dignité. Souvent un peu ironique, toujours sincère sur le fond. C\'est le tempérament des gens loyaux et disciplinés, qui respectent la hiérarchie, font ce qu\'ils ont promis, aiment que les choses soient carrées et ne voient aucune honte à servir une équipe plutôt qu\'eux-mêmes.',
    t: { auth: 0.95, loy: 0.9, fia: 0.95, con: 0.85, vco: 0.85, ord: 0.9, ind: 0.1, lib: 0.15, chg: 0.1, dog: 0.6 } },
  { name: '😈 Le petit diable', by: 'Visages · la bêtise préméditée', tag: 'J\'ai une idée, et elle est mauvaise', color: '#8e44ad',
    desc: 'Cornes violettes et sourire satisfait, il annonce une farce, un dessert de trop, une tentation à laquelle on ne résistera pas. Il n\'est pas méchant, il est espiègle. C\'est le tempérament des hédonistes transgressifs, qui adorent les interdits, prennent des risques pour le plaisir, se méfient des règles morales trop raides et savent qu\'une petite bêtise bien choisie fait les meilleurs souvenirs.',
    t: { vco: 0.05, auth: 0.05, sanc: 0.05, vst: 0.9, aud: 0.9, vhe: 0.9, rsk: 0.85, fia: 0.3, care: 0.3, fair: 0.3 } },
  // ---------- Gestes et cœurs ----------
  { name: '🤝 La poignée de main', by: 'Gestes · « marché conclu »', tag: 'On trouve un terrain d\'entente', color: '#c69c6d',
    desc: 'Il scelle un accord, une réconciliation, une collaboration. Il ne dit ni « j\'ai gagné » ni « j\'ai perdu » : il dit que chacun y trouve son compte. C\'est le tempérament des négociateurs pragmatiques et équitables, qui cherchent des solutions plutôt que des coupables, gardent leur calme, savent mener un groupe et préfèrent toujours un bon compromis à une belle idéologie.',
    t: { dip: 0.95, fair: 0.9, san: 0.8, lea: 0.75, col: 0.75, vac: 0.7, epi: 0.05, dog: 0.1, cmp: 0.3, cfl: 0.3 } },
  { name: '👍 Le pouce levé', by: 'Gestes · « ok, reçu »', tag: 'Message reçu, affaire suivante', color: '#f2c14e',
    desc: 'Pratique, rapide, un peu sec : les plus jeunes le jugent parfois glacial. En 2023, un tribunal canadien a même estimé qu\'un pouce levé valait acceptation d\'un contrat. C\'est le tempérament des efficaces sobres et fiables, qui n\'aiment pas les longs échanges, disent oui quand c\'est oui, avancent sans état d\'âme et préfèrent les actes aux grandes déclarations.',
    t: { fia: 0.85, ord: 0.8, aff: 0.8, ste: 0.75, epi: 0.05, inf: 0.1, soc: 0.3, att: 0.3, vhe: 0.3, ide: 0.15 } },
  { name: '👌 Le OK', by: 'Gestes · « nickel »', tag: 'Parfait, rien à redire', color: '#e5b36a',
    desc: 'Le pouce et l\'index en cercle, il valide ce qui est parfaitement réussi : le plat bien assaisonné, le travail propre, le réglage exact. En France, le même geste peut aussi vouloir dire « zéro », ce qui dit bien son exigence. C\'est le tempérament des perfectionnistes précis, attachés au travail bien fait, qui n\'aiment ni l\'à-peu-près ni l\'imprévu et ne distribuent pas leurs compliments au hasard.',
    t: { con: 0.95, rig: 0.95, ord: 0.9, det: 0.75, vac: 0.7, inc: 0.15, chg: 0.15, vst: 0.3, ide: 0.25, soc: 0.4 } },
  { name: '🙏 Les mains jointes', by: 'Gestes · merci, pitié, amen', tag: 'Merci, du fond du cœur', color: '#d8b384',
    desc: 'Prière, remerciement, supplication : son sens varie selon qui l\'envoie, mais au Japon, il dit simplement « s\'il vous plaît » ou « merci ». Il ne se met jamais en avant. C\'est le tempérament des gens humbles et reconnaissants, attachés aux traditions et à une part de sacré, qui savent ce qu\'ils doivent aux autres, n\'ont aucun goût pour le pouvoir et remettent volontiers une part des choses au destin.',
    t: { sanc: 0.9, vtr: 0.85, vbe: 0.85, care: 0.8, loc: 0.75, opn: 0.6, cmp: 0.05, vpo: 0.05, dom: 0.1, com: 0.1 } },
  { name: '💪 Le biceps', by: 'Gestes · « courage, tu vas y arriver »', tag: 'On lâche rien', color: '#e67e22',
    desc: 'Il sert autant à montrer ses muscles après la salle qu\'à encourager un ami avant un examen. Il croit à l\'effort plus qu\'à la chance. C\'est le tempérament des battants énergiques, qui prennent leur destin en main, osent, encaissent sans se plaindre et ont toujours un mot pour remonter le moral des autres, à condition qu\'ils se remettent au travail juste après.',
    t: { det: 0.95, loc: 0.05, aud: 0.8, vac: 0.8, san: 0.75, rsk: 0.7, com: 0.7, thr: 0.2, vhe: 0.3, ide: 0.3 } },
  { name: '👏 Les applaudissements', by: 'Gestes · bravo à toi', tag: 'Je suis ton premier supporter', color: '#f4a261',
    desc: 'Il félicite, il encourage, il fête la réussite des autres comme si c\'était la sienne. Certains le glissent même entre 👏 chaque 👏 mot pour marteler un message. C\'est le tempérament des supporters généreux, sociables et optimistes, qui n\'ont aucun besoin d\'être au centre, aiment voir briller leur entourage et font d\'un groupe une équipe plutôt qu\'une compétition.',
    t: { cmp: 0.05, vpo: 0.1, inf: 0.85, soc: 0.85, opt: 0.85, col: 0.85, att: 0.8, emp: 0.8, dom: 0.3, ind: 0.3 } },
  { name: '🫶 Les mains en cœur', by: 'Gestes · l\'amour pour toute une communauté', tag: 'Vous êtes les meilleurs', color: '#ff8fab',
    desc: 'Arrivé en 2021, il reprend le geste des stars de la K-pop et des concerts, adressé à tout un public à la fois. Il aime au pluriel. C\'est le tempérament des gens qui vivent pour leur communauté, fans fidèles et chaleureux, qui trouvent leur force dans le collectif, font facilement confiance et préfèrent vibrer ensemble plutôt que briller seuls.',
    t: { col: 0.95, att: 0.9, loy: 0.85, ide: 0.8, inf: 0.8, vun: 0.7, ind: 0.1, cmp: 0.1, vig: 0.2, nat: 0.1 } },
  { name: '❤️ Le cœur rouge', by: 'Cœurs · le classique indémodable', tag: 'Simple, sincère, pour toujours', color: '#e63946',
    desc: 'Il est l\'un des emojis les plus envoyés au monde, et le plus ancien de sa famille : pas de nuance, pas de second degré, juste « je t\'aime ». C\'est le tempérament des gens sincères et fidèles, qui aiment sans détour, tiennent à leurs habitudes et à leurs proches, n\'ont pas besoin de nouveauté permanente et préfèrent un sentiment simple et solide à mille émotions compliquées.',
    t: { att: 0.95, fia: 0.9, loy: 0.9, vtr: 0.7, vco: 0.7, aff: 0.1, vst: 0.25, epi: 0.2, nat: 0.15, cfl: 0.2 } },
  { name: '🖤 Le cœur noir', by: 'Cœurs · l\'élégance sombre', tag: 'J\'aime, mais en noir', color: '#2b2b2b',
    desc: 'Il accompagne l\'humour noir, les playlists mélancoliques, les tenues sombres et les amours qui ne ressemblent à aucune autre. Il n\'est pas froid, il est à part. C\'est le tempérament des sensibles non conformistes, un peu pessimistes sur l\'avenir, indépendants et solitaires, qui trouvent de la beauté dans la mélancolie et se méfient de la joie trop affichée.',
    t: { vco: 0.05, opt: 0.1, vis: 0.85, ide: 0.85, ind: 0.9, soc: 0.2, inf: 0.2, inc: 0.7, att: 0.6, vhe: 0.4 } },
  { name: '💯 Le cent', by: 'Symboles · « à cent pour cent »', tag: 'Tout ou rien, jamais à moitié', color: '#d62828',
    desc: 'Souligné deux fois, il dit « exactement », « totalement d\'accord », « c\'est la vérité ». Il n\'aime pas la nuance, il aime les convictions. C\'est le tempérament des gens entiers et engagés, qui défendent leurs idées jusqu\'au bout, parlent franchement, supportent mal le flou et les demi-mesures et qu\'on aime justement parce qu\'on sait toujours où ils en sont.',
    t: { dog: 0.8, com: 0.9, epi: 0.8, eng: 0.85, det: 0.85, fia: 0.8, cfl: 0.7, inc: 0.05, dip: 0.2, ste: 0.3 } },
  { name: '✌️ Le V de la paix', by: 'Gestes · peace and love', tag: 'Tranquille, on est bien', color: '#7ec4cf',
    desc: 'Signe de victoire pour les uns, de paix pour les autres, il est aussi la pose incontournable des photos au Japon. Partout, il dit que tout va bien et que personne n\'a besoin de se battre. C\'est le tempérament des esprits libres et pacifiques, allergiques à l\'autorité et aux conventions, qui fuient la compétition, croient en la bonté du monde et vivent à leur rythme.',
    t: { lib: 0.95, vsd: 0.85, vun: 0.85, opt: 0.8, cfl: 0.05, cmp: 0.05, auth: 0.1, vco: 0.15, rig: 0.2, thr: 0.1 } },
  { name: '🤷 Le haussement d\'épaules', by: 'Gestes · « je sais pas, c\'est comme ça »', tag: 'Advienne que pourra', color: '#b8a9c9',
    desc: 'Les paumes ouvertes, il répond aux questions sans réponse et aux situations qu\'on ne contrôle pas. Il ne s\'énerve pas, il laisse filer. C\'est le tempérament des fatalistes détendus, sans dogme ni grande cause, qui ne cherchent pas à tout maîtriser, vivent au jour le jour, s\'inquiètent peu et pensent que la plupart des problèmes finissent par se régler tout seuls.',
    t: { loc: 0.95, inc: 0.9, dog: 0.02, eng: 0.05, epi: 0.05, det: 0.2, lea: 0.1, tmp: 0.1, vig: 0.15, thr: 0.1 } },
  { name: '🤌 Les doigts pincés', by: 'Gestes · « ma che vuoi ? »', tag: 'On ne plaisante pas avec ça', color: '#2e8b57',
    desc: 'Arrivé en 2020, ce geste italien sert à protester avec passion, ou à saluer un plat parfait. Il fait bondir quiconque met de l\'ananas sur une pizza ou de la crème dans une carbonara. C\'est le tempérament des passionnés expressifs, gourmands et attachés aux traditions, qui parlent avec les mains, défendent ce qu\'ils aiment avec ardeur et n\'ont aucune intention de rester calmes.',
    t: { inf: 0.95, vhe: 0.85, vtr: 0.85, com: 0.85, opn: 0.8, cfl: 0.75, sanc: 0.6, dip: 0.15, ste: 0.1, aff: 0.1 } },
  // ---------- Objets et symboles ----------
  { name: '🔥 Le feu', by: 'Symboles · « c\'est du feu »', tag: 'Tout, tout de suite, à fond', color: '#ff4500',
    desc: 'Il salue une photo, un morceau, une tenue ou une idée qui brûle tout sur son passage. Il n\'aime ni la tiédeur ni les précautions. C\'est le tempérament des intenses et des audacieux, qui vivent dans l\'instant, prennent des risques sans trembler, veulent que les choses bougent et préfèrent de loin un feu d\'artifice à une braise qui dure longtemps.',
    t: { vst: 0.95, aud: 0.9, rsk: 0.9, chg: 0.85, inf: 0.8, ste: 0.05, vse: 0.1, vig: 0.05, tmp: 0.1, san: 0.3 } },
  { name: '✨ Les étincelles', by: 'Symboles · un peu de magie (ou d\'ironie)', tag: 'Tout mérite un peu de brillant', color: '#f9d56e',
    desc: 'Il ajoute de la magie à une photo, de la douceur à un message, et parfois de l\'ironie : « ✨ lundi ✨ ». Il embellit tout, même ce qui ne le mérite pas vraiment. C\'est le tempérament des rêveurs optimistes et esthètes, qui croient à l\'avenir, voient le beau dans les petites choses, se fient à leur intuition et préfèrent l\'enchantement à la rigueur.',
    t: { ide: 0.95, opt: 0.9, vhe: 0.75, vst: 0.7, sanc: 0.6, epi: 0.6, aff: 0.15, rig: 0.2, vis: 0.05, nat: 0.1 } },
  { name: '🎉 Les cotillons', by: 'Symboles · l\'annonce d\'une bonne nouvelle', tag: 'Bravo l\'équipe !', color: '#ffbe0b',
    desc: 'Il accompagne les promotions, les naissances, les projets livrés et les anniversaires au bureau. Il ne célèbre pas le hasard, il célèbre ce qu\'on a accompli ensemble. C\'est le tempérament des animateurs d\'équipe, organisés et enthousiastes, qui savent marquer les étapes, fédérer un groupe, fêter les réussites de chacun et donner envie à tout le monde de remettre ça.',
    t: { col: 0.9, soc: 0.9, inf: 0.9, opt: 0.9, lea: 0.8, vac: 0.75, ord: 0.75, cmp: 0.15, ind: 0.2, thr: 0.1 } },
  { name: '💀 La tête de mort', by: 'Symboles · « je suis mort (de rire) »', tag: 'Je suis mort. Littéralement.', color: '#dcdcdc',
    desc: 'Chez les plus jeunes, il a détrôné 😂 : on ne rit plus aux larmes, on meurt de rire. Il n\'a rien de lugubre, il exagère avec un sérieux absolu. C\'est le tempérament des générations qui bousculent les codes, adeptes d\'un humour décalé et absurde, allergiques au sérieux et aux traditions, qui aiment la nouveauté et se moquent gentiment de tout, à commencer par eux-mêmes.',
    t: { vtr: 0.05, vco: 0.1, sanc: 0.05, auth: 0.1, dog: 0.1, epi: 0.1, chg: 0.85, vst: 0.8, opn: 0.1, att: 0.4 } },
  { name: '👀 Les yeux', by: 'Symboles · « je vois ce que tu fais »', tag: 'Il se passe un truc, non ?', color: '#5c7cfa',
    desc: 'Deux yeux qui regardent sur le côté : il dit « je surveille », « raconte », « tiens tiens ». Il flaire les histoires avant qu\'elles n\'éclatent. C\'est le tempérament des observateurs attentifs et un peu méfiants, qui remarquent tout, lisent entre les lignes, n\'interviennent pas trop vite et savent souvent ce qui se passe bien avant que les autres ne s\'en doutent.',
    t: { vig: 0.95, nat: 0.8, thr: 0.7, ouv: 0.8, vst: 0.75, dip: 0.6, ste: 0.3, aud: 0.25, inf: 0.3, cfl: 0.3 } },
  { name: '🚀 La fusée', by: 'Symboles · « to the moon »', tag: 'Direction les étoiles', color: '#3a86ff',
    desc: 'Il annonce un lancement, un projet qui décolle, une ambition démesurée. Il ne regarde jamais en arrière. C\'est le tempérament des ambitieux optimistes, qui croient au progrès, visent haut et loin, prennent des risques calculés pour aller plus vite que les autres, aiment gagner et trouvent que l\'ancien monde a surtout vocation à être dépassé.',
    t: { vac: 0.95, chg: 0.95, rsk: 0.95, opt: 0.95, vis: 0.02, vpo: 0.75, cmp: 0.8, tmp: 0.8, vtr: 0.05, vse: 0.1 } },
  { name: '🌈 L\'arc-en-ciel', by: 'Symboles · après la pluie', tag: 'Toutes les couleurs ont leur place', color: '#8e7cc3',
    desc: 'Il arrive après l\'orage et réunit toutes les couleurs dans un seul arc : c\'est l\'emoji de l\'espoir, de la diversité et des bonnes surprises. C\'est le tempérament des humanistes ouverts et confiants, curieux des autres cultures, attachés à l\'égalité, qui ne jugent pas sur les apparences et sont convaincus que les différences rendent le monde plus beau.',
    t: { vun: 0.95, ouv: 0.95, opt: 0.9, fair: 0.85, care: 0.8, dog: 0.05, opn: 0.05, nat: 0.15, vtr: 0.2, sanc: 0.2 } },
  { name: '☕ La tasse de café', by: 'Objets · « pas avant mon café »', tag: 'Chaque chose en son temps', color: '#6f4e37',
    desc: 'Il ouvre les matinées, rythme les pauses et accompagne les « on s\'appelle après ». C\'est un rituel plus qu\'une boisson. C\'est le tempérament des travailleurs réguliers, fidèles à leurs habitudes, qui aiment que la journée ait une forme, avancent sans bruit mais sans relâche et savourent les petits plaisirs qui rendent le quotidien tenable.',
    t: { ord: 0.85, vtr: 0.8, fia: 0.85, det: 0.8, ste: 0.75, tmp: 0.7, vhe: 0.6, chg: 0.1, vst: 0.2, rsk: 0.15 } },
  { name: '🍕 La pizza', by: 'Objets · la soirée qui ne demande rien', tag: 'On commande ?', color: '#e76f51',
    desc: 'Il annonce une soirée sans chichis, un film, des amis, une boîte en carton au milieu de la table. Il ne se prend jamais au sérieux. C\'est le tempérament des bons vivants simples, qui aiment partager, se moquent du prestige et de la performance, n\'ont pas besoin de plans compliqués et savent que le bonheur tient parfois à une part de plus.',
    t: { vhe: 0.95, soc: 0.85, col: 0.75, rig: 0.15, vac: 0.15, vpo: 0.1, tmp: 0.1, dog: 0.15, con: 0.15, ide: 0.3 } },
  { name: '🐐 La chèvre', by: 'Symboles · G.O.A.T., le plus grand de tous les temps', tag: 'Le meilleur, point final', color: '#a47148',
    desc: 'Grâce à un jeu de mots anglais (« goat », chèvre, et G.O.A.T., « Greatest Of All Time »), il est devenu le compliment ultime pour les champions. Il ne vise pas la deuxième place. C\'est le tempérament des compétiteurs d\'élite, exigeants et sûrs d\'eux, maîtres de leur destin, qui veulent laisser une trace, dominent sans complexe et ne trouvent aucun charme à la modestie.',
    t: { cmp: 0.98, vac: 0.98, vpo: 0.9, dom: 0.9, det: 0.9, loc: 0.05, col: 0.1, care: 0.3, emp: 0.3, dip: 0.3 } },
  { name: '🌚 La lune qui sourit dans le noir', by: 'Symboles · le regard en coin', tag: 'Je ne dis rien, mais je n\'en pense pas moins', color: '#3c3f58',
    desc: 'Son petit visage sombre au regard de côté en a fait l\'emoji des sous-entendus bizarres, des pensées de minuit et des blagues qu\'on ne comprend qu\'à deux. C\'est le tempérament des originaux discrets, un peu nocturnes, qui ont un humour bien à eux, n\'obéissent pas aux conventions, préfèrent les petits cercles aux grandes fêtes et cachent une imagination débordante.',
    t: { ind: 0.9, ide: 0.85, vst: 0.8, nat: 0.75, vco: 0.05, sanc: 0.1, soc: 0.15, ord: 0.15, att: 0.25, dip: 0.3 } },
  { name: '🦄 La licorne', by: 'Symboles · l\'être unique', tag: 'Aucune case ne me va', color: '#c77dff',
    desc: 'Créature de légende, elle a aussi donné son nom aux start-up valorisées plus d\'un milliard de dollars, un terme lancé en 2013 par l\'investisseuse Aileen Lee. Dans les deux cas, elle est rare. C\'est le tempérament des originaux assumés, rêveurs et indépendants, qui refusent les moules, les traditions et les règles toutes faites et préfèrent être uniques plutôt que conformes.',
    t: { ide: 0.98, vsd: 0.9, ind: 0.85, ouv: 0.85, vco: 0.05, con: 0.05, vtr: 0.1, auth: 0.1, opn: 0.1, aff: 0.2 } },
  { name: '🐢 La tortue', by: 'Animaux · lentement mais sûrement', tag: 'Rien ne sert de courir', color: '#6a994e',
    desc: 'Depuis La Fontaine, elle incarne la patience qui finit par gagner. En message, elle avoue un retard assumé ou une connexion qui rame. C\'est le tempérament des gens posés et persévérants, qui détestent se précipiter, prennent leurs décisions sur le long terme, évitent les risques inutiles et arrivent toujours au bout, souvent après tout le monde, mais sans jamais tomber.',
    t: { ste: 0.98, tmp: 0.95, det: 0.85, san: 0.85, vig: 0.7, rsk: 0.05, vst: 0.05, aud: 0.1, chg: 0.1, cmp: 0.2 } },
  { name: '🧠 Le cerveau', by: 'Symboles · « big brain »', tag: 'J\'ai un plan. Plusieurs, en fait.', color: '#f28482',
    desc: 'Arrivé en 2017, il salue une idée brillante, une stratégie astucieuse ou une réflexion à trois coups d\'avance. Il pense, puis il agit. C\'est le tempérament des stratèges cérébraux et calmes, qui anticipent, aiment diriger par la réflexion plutôt que par la force, visent la réussite sur le long terme et font rarement passer le cœur avant la raison.',
    t: { aff: 0.98, tmp: 0.9, lea: 0.8, vac: 0.8, san: 0.8, rig: 0.75, att: 0.15, vhe: 0.15, dog: 0.15, emp: 0.3 } },
  { name: '💡 L\'ampoule', by: 'Symboles · l\'idée qui s\'allume', tag: 'Et si on faisait autrement ?', color: '#ffd60a',
    desc: 'Il s\'allume au-dessus des têtes depuis les bandes dessinées, et en message il annonce une idée, une astuce, un déclic. Il ne supporte pas le « on a toujours fait comme ça ». C\'est le tempérament des inventeurs indépendants et pragmatiques, qui aiment travailler à leur façon, osent bousculer l\'existant, se fient à leur propre jugement et préfèrent une solution qui marche à un beau principe.',
    t: { ide: 0.95, vsd: 0.9, ind: 0.85, chg: 0.85, aud: 0.8, epi: 0.05, vtr: 0.1, loc: 0.1, soc: 0.35, col: 0.25 } },
  { name: '🎯 La cible', by: 'Symboles · en plein dans le mille', tag: 'Objectif en vue, pas de détour', color: '#e63946',
    desc: 'Il valide une réponse exacte, un objectif atteint, une remarque parfaitement visée. Il ne tourne pas autour du pot. C\'est le tempérament des gens focalisés et méthodiques, qui fixent un cap, s\'y tiennent, mesurent leurs progrès, supportent mal le flou et les distractions et prennent plus de plaisir à atteindre un but qu\'à flâner en chemin.',
    t: { det: 0.95, ord: 0.95, rig: 0.9, vac: 0.9, tmp: 0.85, cmp: 0.75, aff: 0.8, inc: 0.1, vhe: 0.1, vst: 0.2, ide: 0.2 } },
  { name: '🧘 La méditation', by: 'Symboles · « respire »', tag: 'Inspire. Expire. Ça passe.', color: '#88b04b',
    desc: 'Assis en tailleur, il répond au stress des autres par une invitation au calme, et parfois par une pointe d\'humour : « je reste zen ». C\'est le tempérament des sereins profonds, qui ne se laissent pas emporter, n\'ont aucun besoin de gagner ni de dominer, cultivent une vie intérieure et prennent le monde tel qu\'il vient, avec curiosité et sans angoisse.',
    t: { san: 0.98, thr: 0.02, ste: 0.9, sanc: 0.85, inc: 0.85, ouv: 0.75, vpo: 0.05, cmp: 0.05, vac: 0.15, com: 0.1 } },
  { name: '🍿 Le pop-corn', by: 'Objets · « je regarde le drama »', tag: 'Je ne m\'en mêle pas, je regarde', color: '#f6bd60',
    desc: 'Il s\'installe au premier rang dès qu\'une dispute éclate dans le groupe : il ne prend pas parti, il savoure. C\'est le tempérament des spectateurs amusés et détendus, qui adorent les histoires mais pas les conflits, ne cherchent ni à diriger ni à s\'engager, gardent leur calme en toutes circonstances et considèrent la vie comme une série dont ils ne ratent aucun épisode.',
    t: { eng: 0.05, cfl: 0.05, lea: 0.1, dom: 0.1, vhe: 0.85, san: 0.75, ouv: 0.7, vst: 0.7, com: 0.2, inf: 0.3 } },
  { name: '⚡ L\'éclair', by: 'Symboles · vite, très vite', tag: 'C\'est déjà fait', color: '#ffc300',
    desc: 'Il signale l\'énergie, la vitesse, la décision prise en une seconde. Il n\'attend personne. C\'est le tempérament des fonceurs impatients et décidés, qui prennent les commandes, tranchent vite, supportent mal la lenteur des autres et préfèrent corriger une erreur en route plutôt que perdre du temps à tout planifier.',
    t: { tmp: 0.05, ste: 0.05, dom: 0.85, aud: 0.9, rsk: 0.85, det: 0.8, lea: 0.75, vst: 0.8, rig: 0.3, san: 0.3 } },
  { name: '🌱 La jeune pousse', by: 'Nature · petit à petit', tag: 'Ce qu\'on plante aujourd\'hui', color: '#52b788',
    desc: 'Il accompagne les nouveaux départs, les projets qui grandissent doucement et les gestes pour la planète. Il pense en saisons, pas en minutes. C\'est le tempérament des idéalistes patients, soucieux de la nature et des générations futures, qui croient qu\'un monde meilleur se construit lentement, ne cherchent ni pouvoir ni compétition et arrosent chaque jour ce qui compte.',
    t: { vun: 0.95, tmp: 0.95, care: 0.85, ide: 0.8, ste: 0.75, eng: 0.7, vis: 0.15, vpo: 0.05, cmp: 0.1, vhe: 0.2 } },
  { name: '☀️ Le soleil', by: 'Nature · « bonne journée ☀️ »', tag: 'Il fait beau, même quand il pleut', color: '#ffb703',
    desc: 'Il illumine les bonjours du matin, les photos de vacances et les messages pour remonter le moral. Il ne connaît pas les nuages. C\'est le tempérament des optimistes rayonnants, confiants envers les autres et envers l\'avenir, qui réchauffent l\'ambiance dès qu\'ils arrivent, ne voient pas le mal partout et donnent envie de sortir, même un lundi.',
    t: { opt: 0.98, vis: 0.02, thr: 0.05, nat: 0.05, vig: 0.1, soc: 0.85, inf: 0.85, att: 0.8, san: 0.75, dog: 0.2 } },
  { name: '🌙 Le croissant de lune', by: 'Nature · « bonne nuit » et pensées nocturnes', tag: 'Tout est plus clair la nuit', color: '#4a4e69',
    desc: 'Il dit bonne nuit, mais il est surtout l\'emoji de ceux qui pensent mieux quand tout le monde dort. Il aime le silence et les idées qui viennent à trois heures du matin. C\'est le tempérament des rêveurs solitaires et introspectifs, calmes, indépendants, pleins d\'imagination, qui n\'ont aucun goût pour la foule ni pour la compétition et vivent intensément à l\'intérieur.',
    t: { soc: 0.1, inf: 0.05, dom: 0.1, cmp: 0.1, ide: 0.9, ouv: 0.8, ste: 0.8, ind: 0.8, aff: 0.2, tmp: 0.6 } },
];

window.PRISME_EMOJIS = { EMOJIS };
