/* ============================================================
   PRISME — « Si tu étais une émotion »
   ------------------------------------------------------------
   Pas l'émotion que tu ressens le plus, mais celle dont le caractère
   ressemble au tien : celle qui monte vite ou qui s'installe, qui se
   montre ou se cache, qui pousse à agir ou à contempler. Aucune n'est
   « mauvaise » : chacune a une fonction, et un tempérament.
     name = l'émotion, by = famille · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const EMOTIONS = [
  { name: 'La joie', by: 'Émotion de base · contagieuse', tag: 'Elle se partage ou elle s\'ennuie', color: '#f7c948',
    desc: 'Elle fait partie des six émotions de base décrites par le psychologue Paul Ekman, reconnaissables sur un visage dans toutes les cultures. Elle monte vite, se voit jusque dans les yeux et cherche aussitôt quelqu\'un avec qui se partager. C\'est le tempérament des gens solaires et entourés, qui font confiance à la vie et pour qui un bonheur ne compte vraiment que s\'il est vécu à plusieurs.',
    t: { soc: 0.95, inf: 0.9, opt: 0.95, att: 0.85, vhe: 0.8, thr: 0.05, nat: 0.05, vig: 0.1, rig: 0.25, dog: 0.15, col: 0.8 } },
  { name: 'La sérénité', by: 'État calme · qui s\'installe', tag: 'Le lac sans une ride', color: '#8fb8c9',
    desc: 'Elle n\'arrive jamais en fanfare : elle s\'installe doucement, une fois que le bruit est retombé, et peut durer des heures. Elle ne cherche ni à convaincre ni à gagner, elle regarde simplement passer les choses. C\'est le tempérament des gens posés et imperturbables, qui n\'ont pas besoin de conflit ni d\'agitation pour se sentir vivants et qui apaisent tout le monde autour d\'eux.',
    t: { ste: 0.98, san: 0.95, thr: 0.05, cfl: 0.05, dom: 0.1, vst: 0.15, inc: 0.8, cmp: 0.05, com: 0.1, inf: 0.3 } },
  { name: 'L\'enthousiasme', by: 'Élan · vers l\'avant', tag: 'Et si on le faisait maintenant ?', color: '#ff7a3d',
    desc: 'Le mot vient du grec et voulait dire « avoir un dieu en soi ». Il s\'allume au premier projet venu, entraîne les autres dans son sillage et n\'a aucune patience pour les « on a toujours fait comme ça ». C\'est le tempérament des idéalistes pleins d\'énergie, qui croient à l\'avenir, aiment la nouveauté et préfèrent se tromper en fonçant plutôt que d\'attendre le moment parfait.',
    t: { inf: 0.95, vst: 0.9, opt: 0.9, chg: 0.85, aud: 0.8, ste: 0.2, vig: 0.15, vtr: 0.15, vis: 0.05, ide: 0.85 } },
  { name: 'L\'euphorie', by: 'Pic · quelques instants', tag: 'Tout est possible ce soir', color: '#e94ca8',
    desc: 'C\'est la joie montée au maximum : le but à la dernière minute, la fin des examens, la piste de danse à deux heures du matin. Elle ne dure jamais très longtemps et ne s\'embarrasse ni de prudence ni de programme. C\'est le tempérament des bons vivants intenses, qui vivent tout à fond, prennent des risques sans y penser et laissent aux autres le soin de ranger après la fête.',
    t: { vhe: 0.98, tmp: 0.02, rig: 0.05, vig: 0.05, rsk: 0.9, soc: 0.9, ord: 0.05, san: 0.15, con: 0.1, vst: 0.85 } },
  { name: 'La fierté', by: 'Émotion sociale · menton levé', tag: 'Je l\'ai fait, et je le sais', color: '#c0392b',
    desc: 'Elle naît d\'un effort récompensé et se lit dans la posture : épaules ouvertes, menton légèrement levé, un geste que l\'on retrouve même chez des athlètes aveugles de naissance. Elle pousse à recommencer et à viser plus haut. C\'est le tempérament des gens ambitieux et maîtres de leur destin, qui aiment gagner, assument leurs succès et ne comptent pas trop sur le hasard ni sur les autres.',
    t: { vac: 0.95, vpo: 0.8, det: 0.85, cmp: 0.85, dom: 0.8, loc: 0.05, dip: 0.25, col: 0.2, ste: 0.3, emp: 0.3 } },
  { name: 'La gratitude', by: 'Émotion sociale · tournée vers l\'autre', tag: 'Rien de tout ça sans vous', color: '#d9a441',
    desc: 'Elle regarde ce qu\'on a reçu plutôt que ce qu\'on a gagné, et elle a un effet étonnant : les études montrent qu\'elle renforce les liens et donne envie de rendre à son tour. Elle ne se met jamais en avant. C\'est le tempérament des gens fidèles et reconnaissants, qui savent ce qu\'ils doivent à leurs proches, honorent ce qui les a précédés et n\'ont aucun besoin de briller seuls.',
    t: { vbe: 0.95, att: 0.9, loy: 0.85, vtr: 0.8, cmp: 0.05, vpo: 0.05, ind: 0.15, opt: 0.8, loc: 0.75, dom: 0.1 } },
  { name: 'L\'émerveillement', by: 'Émotion rare · qui fait se sentir petit', tag: 'Le souffle coupé devant l\'immense', color: '#5a4fcf',
    desc: 'Un ciel étoilé, une cathédrale, un glacier : les chercheurs qui l\'étudient, comme Dacher Keltner, notent qu\'il donne le sentiment d\'être tout petit, et qu\'il rend plus généreux. Il suspend le temps et fait taire l\'ego. C\'est le tempérament des âmes ouvertes et contemplatives, sensibles au sacré comme à la nature, pour qui le monde reste un spectacle qu\'on ne finit jamais d\'explorer.',
    t: { ouv: 0.95, ide: 0.9, vun: 0.85, opn: 0.1, aff: 0.2, dog: 0.05, sanc: 0.85, vac: 0.1, cmp: 0.05, ste: 0.65 } },
  { name: 'La curiosité', by: 'Élan · de question en question', tag: 'Attends, mais pourquoi ?', color: '#2a9d8f',
    desc: 'Elle ne tient pas en place : une question en ouvre trois autres, et elle peut passer une nuit entière sur un sujet qu\'elle ignorait la veille. Elle se moque des évidences et des traditions tant qu\'elle n\'a pas compris par elle-même. C\'est le tempérament des esprits libres et cérébraux, à l\'aise dans l\'incertitude, plus attirés par une bonne idée que par une bonne soirée.',
    t: { ouv: 0.98, vst: 0.9, aff: 0.85, inc: 0.9, dog: 0.05, vtr: 0.1, opn: 0.1, ind: 0.8, soc: 0.35, att: 0.3 } },
  { name: 'L\'amusement', by: 'Rire · en une seconde', tag: 'Même ça, ça peut être drôle', color: '#f4a259',
    desc: 'Il surgit d\'un décalage, d\'une absurdité, d\'un mot de travers, et se transmet par le rire, qui est d\'abord un signal fait pour être entendu des autres. Il désamorce les tensions et déboulonne les statues. C\'est le tempérament des gens légers au sens noble, qui gardent leur calme en riant, ne prennent pas l\'autorité trop au sérieux et préfèrent une bonne blague à un grand principe.',
    t: { vhe: 0.9, com: 0.75, inf: 0.85, dog: 0.05, sanc: 0.1, auth: 0.1, vco: 0.2, epi: 0.1, san: 0.8, opt: 0.8 } },
  { name: 'La tendresse', by: 'Émotion douce · à voix basse', tag: 'Tout doux, je suis là', color: '#f2a7b8',
    desc: 'Elle s\'exprime par de petits gestes : une main sur l\'épaule, une couverture remontée, une voix qui baisse d\'un ton. Elle ne hausse jamais le ton et ne cherche ni à convaincre ni à dominer. C\'est le tempérament des cœurs attentifs et paisibles, qui prennent soin des autres naturellement, fuient les conflits et savent qu\'une attention discrète vaut souvent mieux qu\'un grand discours.',
    t: { att: 0.98, care: 0.95, emp: 0.9, dom: 0.05, cfl: 0.05, com: 0.1, ste: 0.85, vbe: 0.95, cmp: 0.05, aff: 0.1 } },
  { name: 'L\'amour', by: 'Attachement · pour longtemps', tag: 'Tout miser sur quelqu\'un', color: '#d7263d',
    desc: 'Il commence souvent comme une tempête et, s\'il dure, se transforme en fidélité tranquille. Il rend audacieux, un peu déraisonnable, et capable de faire des projets sur trente ans. C\'est le tempérament des passionnés loyaux, qui écoutent leur cœur avant leur tête, prennent le risque de s\'attacher et préfèrent une vie partagée à une liberté sans personne à qui la raconter.',
    t: { att: 0.95, loy: 0.9, vbe: 0.9, aff: 0.02, rsk: 0.8, aud: 0.75, ind: 0.15, vig: 0.2, tmp: 0.85, ide: 0.8 } },
  { name: 'L\'admiration', by: 'Émotion sociale · les yeux levés', tag: 'Un jour, j\'aimerais être comme ça', color: '#b08d57',
    desc: 'Elle naît devant quelqu\'un qui fait mieux que nous, et au lieu de piquer comme l\'envie, elle donne envie de progresser. Elle sait reconnaître un maître, un aîné, un modèle. C\'est le tempérament des élèves généreux, qui respectent l\'expérience et la hiérarchie, apprennent de ceux qu\'ils estiment et n\'ont aucun besoin de rabaisser les autres pour grandir eux-mêmes.',
    t: { auth: 0.85, vac: 0.8, loy: 0.75, dom: 0.1, cmp: 0.15, opt: 0.8, vtr: 0.75, ind: 0.2, com: 0.1, ouv: 0.75 } },
  { name: 'La compassion', by: 'Émotion morale · qui pousse à agir', tag: 'Ta peine me regarde', color: '#6a8caf',
    desc: 'Plus qu\'une simple tristesse pour l\'autre, elle donne envie de faire quelque chose : aider, réparer, défendre. Elle ne fait pas de tri entre les proches et les inconnus. C\'est le tempérament des cœurs engagés, sensibles à l\'injustice où qu\'elle se trouve, qui ne cherchent ni le pouvoir ni la réussite et donnent volontiers leur confiance, parce qu\'ils croient d\'abord au meilleur des gens.',
    t: { care: 0.98, emp: 0.95, vun: 0.9, fair: 0.85, eng: 0.8, vpo: 0.05, cmp: 0.05, nat: 0.1, col: 0.85, vac: 0.2 } },
  { name: 'L\'espoir', by: 'Élan · tourné vers demain', tag: 'Ça ira mieux, et on y travaille', color: '#7cc47f',
    desc: 'Il ne nie pas les difficultés : il parie simplement qu\'elles ne sont pas définitives. Il tient sur la durée, dans les moments où rien ne va, et donne l\'énergie de continuer. C\'est le tempérament des idéalistes tournés vers l\'avenir, qui croient au progrès, gardent le cap malgré les mauvaises nouvelles et voient toujours une porte là où d\'autres voient un mur.',
    t: { opt: 0.98, vis: 0.02, tmp: 0.9, ide: 0.9, epi: 0.7, thr: 0.1, nat: 0.1, rsk: 0.6, san: 0.7, vse: 0.3 } },
  { name: 'Le soulagement', by: 'Détente · après l\'alerte', tag: 'Ouf. Bon. On respire.', color: '#9ad1d4',
    desc: 'Il n\'existe que parce qu\'on s\'est inquiété avant : un grand soupir, les épaules qui retombent, parfois un rire nerveux. Il récompense la vigilance et remet le corps au repos. C\'est le tempérament des prudents qui aiment la sécurité, envisagent le pire pour être tranquilles, évitent les paris inutiles et savourent pleinement les moments où tout est rentré dans l\'ordre.',
    t: { thr: 0.85, vig: 0.85, vse: 0.95, rsk: 0.1, loc: 0.8, ste: 0.7, aud: 0.1, vst: 0.1, dom: 0.2, vhe: 0.7 } },
  { name: 'La confiance', by: 'Sentiment · qui se construit', tag: 'Je te crois, vas-y', color: '#3b82c4',
    desc: 'Elle se gagne lentement et se perd vite, mais quand elle est là, tout devient plus simple : on délègue, on s\'appuie, on dort bien. Elle n\'a pas besoin de tout vérifier. C\'est le tempérament des gens sûrs d\'eux sans arrogance, calmes et diplomates, qui partent du principe que les autres sont de bonne foi et qui, bien souvent, poussent ainsi les autres à le devenir.',
    t: { nat: 0.02, san: 0.9, opt: 0.85, vig: 0.1, thr: 0.05, inc: 0.85, dip: 0.8, att: 0.75, dog: 0.2, fia: 0.9 } },
  { name: 'Le courage', by: 'État · malgré la peur', tag: 'J\'ai peur, et j\'y vais quand même', color: '#b5432f',
    desc: 'Ce n\'est pas l\'absence de peur, c\'est ce qui se passe quand on décide qu\'autre chose compte davantage. Il se lève pour défendre quelqu\'un, dit ce que personne n\'ose dire, et accepte de payer le prix. C\'est le tempérament des audacieux au franc-parler, loyaux envers les leurs, qui affrontent les conflits de face et trouvent la sécurité bien moins importante que la justice.',
    t: { aud: 0.98, rsk: 0.95, cfl: 0.9, san: 0.8, vse: 0.05, vig: 0.2, com: 0.85, fair: 0.85, loy: 0.8, ste: 0.3 } },
  { name: 'La détermination', by: 'État · sur la durée', tag: 'Un pas, puis le suivant', color: '#34495e',
    desc: 'Elle ne fait pas de bruit, elle s\'installe pour des mois : même heure, même effort, jusqu\'au but. Elle ne compte ni sur la chance ni sur l\'inspiration, seulement sur la méthode. C\'est le tempérament des bâtisseurs rigoureux, qui savent renoncer au plaisir immédiat, pensent en années plutôt qu\'en jours et sont convaincus que le résultat dépend d\'abord de ce qu\'on y met.',
    t: { det: 0.98, rig: 0.9, tmp: 0.95, vac: 0.9, ord: 0.85, vhe: 0.1, loc: 0.02, soc: 0.3, inf: 0.2, inc: 0.3 } },
  { name: 'La nostalgie', by: 'Mémoire · douce-amère', tag: 'C\'était mieux avant, un peu', color: '#c49a6c',
    desc: 'Le mot a été inventé en 1688 par le médecin suisse Johannes Hofer, à partir du grec « retour » et « douleur », pour décrire le mal du pays des soldats. Elle revient avec une chanson, une odeur, une photo. C\'est le tempérament des gens attachés à leurs racines, fidèles aux souvenirs et aux traditions, qui se méfient un peu des grands chambardements et trouvent le passé souvent plus doux que l\'avenir.',
    t: { vtr: 0.95, opn: 0.9, chg: 0.05, vis: 0.85, att: 0.85, vst: 0.1, loy: 0.85, aff: 0.15, ouv: 0.3, rsk: 0.2 } },
  { name: 'La mélancolie', by: 'Humeur · en demi-teinte', tag: 'Une pluie fine qu\'on aime un peu', color: '#5d6d7e',
    desc: 'Les Grecs l\'attribuaient à la « bile noire », et elle a longtemps passé pour l\'humeur des poètes et des artistes. Elle ne crie pas, ne se montre guère et préfère une fenêtre sous la pluie à une fête. C\'est le tempérament des rêveurs introvertis, créatifs et un peu désabusés, qui voient la beauté dans ce qui passe et ne ressentent aucun besoin de paraître joyeux pour être bien.',
    t: { ide: 0.9, soc: 0.1, inf: 0.05, opt: 0.15, aff: 0.3, vhe: 0.2, vis: 0.8, ouv: 0.8, ste: 0.7, dom: 0.05 } },
  { name: 'La colère', by: 'Émotion de base · en quelques secondes', tag: 'Ça suffit, maintenant', color: '#d62828',
    desc: 'Autre émotion de base d\'Ekman, elle monte en un éclair, chauffe le visage et prépare le corps à affronter l\'obstacle. Elle sert à poser des limites et à dire « non » quand c\'est nécessaire. C\'est le tempérament des gens entiers et directs, qui ne supportent pas l\'injustice, disent les choses comme elles viennent et préfèrent un bon éclat à une rancœur qui dure.',
    t: { com: 0.95, cfl: 0.95, san: 0.05, dip: 0.05, ste: 0.1, dom: 0.85, fair: 0.8, inf: 0.7, tmp: 0.1, emp: 0.3 } },
  { name: 'L\'indignation', by: 'Émotion morale · au nom des autres', tag: 'Ce n\'est pas acceptable', color: '#9b2226',
    desc: 'C\'est une colère qui ne se met pas en rogne pour elle-même, mais pour une cause : une injustice, un abus, une promesse trahie. Elle écrit des tribunes, signe des pétitions, descend dans la rue. C\'est le tempérament des militants convaincus, qui ont de grands principes, se méfient des puissants et pensent que le monde peut changer si l\'on refuse de s\'y habituer.',
    t: { fair: 0.98, eng: 0.95, vun: 0.95, epi: 0.85, com: 0.85, auth: 0.1, vpo: 0.05, chg: 0.85, dog: 0.7, loy: 0.3 } },
  { name: 'La rage de vaincre', by: 'Feu · le jour du match', tag: 'Pas aujourd\'hui, pas contre moi', color: '#e63946',
    desc: 'On la voit dans les yeux des sportifs avant une finale : une énergie tendue vers un seul but, battre l\'adversaire. Elle ne s\'attarde ni sur les états d\'âme ni sur les politesses. C\'est le tempérament des compétiteurs nés, qui aiment la confrontation, veulent gagner plus qu\'ils ne veulent plaire et se sentent vraiment vivants quand le score est serré et que tout se joue maintenant.',
    t: { cmp: 0.98, vac: 0.95, det: 0.9, dom: 0.85, rsk: 0.8, emp: 0.2, vbe: 0.3, cfl: 0.8, vhe: 0.2, col: 0.1 } },
  { name: 'La jalousie', by: 'Émotion sociale · peur de perdre', tag: 'C\'est à moi, et j\'y tiens', color: '#4f8a3c',
    desc: 'On la confond souvent avec l\'envie, mais elle porte sur ce qu\'on a déjà et qu\'on craint de perdre, le plus souvent quelqu\'un. Elle guette, soupçonne, et protège farouchement le lien. C\'est le tempérament des cœurs très attachés et vigilants, fidèles et possessifs, qui aiment intensément, ont besoin de sécurité dans leurs relations et supportent mal le flou.',
    t: { att: 0.9, nat: 0.9, thr: 0.85, loy: 0.95, ind: 0.1, inc: 0.05, san: 0.15, vse: 0.85, dip: 0.3, cfl: 0.7 } },
  { name: 'L\'envie', by: 'Émotion sociale · les yeux sur le voisin', tag: 'Pourquoi lui, et pas moi ?', color: '#8ab733',
    desc: 'Elle naît de la comparaison : une voiture, un poste, une réussite qu\'on voudrait pour soi. Mal digérée, elle aigrit ; bien utilisée, elle indique très clairement ce qu\'on désire et donne un sacré coup de fouet. C\'est le tempérament des ambitieux qui aiment les belles choses et le statut, mesurent leur place à celle des autres et ne se contentent jamais longtemps de ce qu\'ils ont.',
    t: { vpo: 0.95, vac: 0.9, cmp: 0.9, vhe: 0.8, vbe: 0.2, emp: 0.2, vtr: 0.2, san: 0.3, vun: 0.15, opt: 0.35 } },
  { name: 'L\'impatience', by: 'Tension · qui tape du pied', tag: 'Alors, ça vient ?', color: '#ff9f1c',
    desc: 'Elle pianote sur la table, relance trois fois le même message et double dans la file d\'attente. Elle déteste les procédures, les lenteurs et les « on verra ». C\'est le tempérament des fonceurs, qui veulent que ça bouge tout de suite, prennent les commandes dès que ça traîne et préfèrent mille fois un changement imparfait à une attente bien organisée.',
    t: { tmp: 0.02, ste: 0.02, rig: 0.25, san: 0.2, dom: 0.8, chg: 0.85, vst: 0.85, ord: 0.2, con: 0.1, rsk: 0.8 } },
  { name: 'Le trac', by: 'Peur · juste avant d\'entrer', tag: 'Le cœur qui bat avant le lever de rideau', color: '#8e44ad',
    desc: 'Mains moites, cœur qui cogne, gorge sèche : il frappe juste avant de monter sur scène ou de prendre la parole, et disparaît souvent dès les premiers mots. Beaucoup d\'artistes disent qu\'ils s\'inquiéteraient de ne plus l\'avoir. C\'est le tempérament des gens qui aiment la lumière et la redoutent à la fois, exigeants envers eux-mêmes, qui veulent briller et bien faire, et s\'y préparent avec soin.',
    t: { thr: 0.9, vig: 0.8, inf: 0.85, vac: 0.85, san: 0.1, ste: 0.25, rig: 0.8, aud: 0.7, inc: 0.2, vhe: 0.3 } },
  { name: 'L\'appréhension', by: 'Anticipation · des jours à l\'avance', tag: 'J\'ai tout prévu, sauf l\'imprévu', color: '#6b705c',
    desc: 'Elle commence bien avant l\'événement : elle imagine ce qui pourrait mal tourner, vérifie les horaires, prépare un plan B. Elle sert à anticiper et évite beaucoup de mauvaises surprises. C\'est le tempérament des organisés prévoyants, qui aiment les règles et la sécurité, se méfient des grands sauts dans l\'inconnu et dorment mieux quand tout est planifié.',
    t: { tmp: 0.9, vig: 0.95, ord: 0.9, rsk: 0.05, inc: 0.05, con: 0.9, vse: 0.9, chg: 0.1, opt: 0.3, aud: 0.1 } },
  { name: 'L\'inquiétude', by: 'Souci · pour les autres', tag: 'Envoie un message quand tu es arrivé', color: '#7d8ca3',
    desc: 'Elle se fait surtout du souci pour les autres : le retard du petit dernier, la toux d\'un parent, le trajet d\'un ami. Elle veille tard et imagine un peu trop de scénarios. C\'est le tempérament des protecteurs dévoués, très attachés à leurs proches, qui ressentent tout, ont du mal à lâcher prise et préfèrent se faire du souci pour rien plutôt que de passer à côté de quelque chose.',
    t: { care: 0.9, vbe: 0.95, thr: 0.95, emp: 0.85, san: 0.1, att: 0.9, opt: 0.2, vis: 0.75, vhe: 0.2, dom: 0.15 } },
  { name: 'La méfiance', by: 'Vigilance · à distance', tag: 'Je vais d\'abord vérifier', color: '#3d405b',
    desc: 'Elle observe avant de s\'approcher, pose des questions et garde toujours une porte de sortie. Elle protège des arnaques, des beaux parleurs et des promesses trop belles. C\'est le tempérament des indépendants lucides et cérébraux, qui ne donnent pas leur confiance à la légère, gardent leurs distances avec les groupes et préfèrent se fier à leur propre jugement qu\'aux apparences.',
    t: { nat: 0.98, vig: 0.9, ind: 0.85, soc: 0.1, att: 0.2, dip: 0.2, col: 0.15, opn: 0.75, inf: 0.1, aff: 0.85 } },
  { name: 'La surprise', by: 'Émotion de base · deux secondes', tag: 'Oh !', color: '#ffd166',
    desc: 'C\'est la plus brève des émotions de base selon Ekman : sourcils levés, bouche ouverte, et en une seconde ou deux elle cède la place à autre chose. Elle sert à tout arrêter pour faire attention à l\'imprévu. C\'est le tempérament des gens très réactifs, en alerte et sans plan, qui vivent au gré des événements, changent d\'avis en un instant et ne s\'accrochent à aucune certitude.',
    t: { inc: 0.9, loc: 0.9, vig: 0.85, san: 0.15, ste: 0.15, thr: 0.6, ord: 0.05, dog: 0.05, tmp: 0.02, ouv: 0.8 } },
  { name: 'L\'ennui', by: 'Creux · qui s\'étire', tag: 'Il ne se passe rien, et c\'est insupportable', color: '#a8a29e',
    desc: 'Le mot vient du latin « in odio », « être en haine ». L\'ennui est un signal : il dit que ce qu\'on fait ne nous nourrit plus, et beaucoup d\'idées sont nées d\'un après-midi vide. C\'est le tempérament des esprits avides de nouveauté et d\'imaginaire, allergiques à la routine, aux règles et aux traditions, qui ont besoin de stimulation pour s\'épanouir et s\'étiolent dès que tout se répète.',
    t: { vst: 0.95, rig: 0.1, ste: 0.1, vtr: 0.05, vco: 0.05, ord: 0.1, ide: 0.8, con: 0.1, det: 0.2, chg: 0.8 } },
  { name: 'La flemme', by: 'Humeur · canapé', tag: 'Demain. Peut-être.', color: '#b8c4a9',
    desc: 'Le mot est de la même famille que « flegme », l\'une des quatre humeurs de la médecine antique. Elle n\'a aucun projet, aucune ambition et aucune envie d\'en discuter, et elle défend le droit sacré au plaid. C\'est le tempérament des épicuriens tranquilles, que la compétition ennuie, que rien ne presse, et qui savent profiter du moment présent sans se sentir obligés de le rentabiliser.',
    t: { vhe: 0.95, det: 0.05, vac: 0.02, rig: 0.05, ste: 0.95, dom: 0.05, tmp: 0.1, cmp: 0.02, cfl: 0.05, vpo: 0.05 } },
  { name: 'La déception', by: 'Chute · entre attente et réalité', tag: 'Je m\'attendais à mieux', color: '#6c757d',
    desc: 'Elle mesure l\'écart entre ce qu\'on espérait et ce qui arrive, et elle est d\'autant plus forte que l\'idéal était haut. Elle ne crie pas, elle se retire un peu et révise ses attentes. C\'est le tempérament des idéalistes exigeants, qui ont des principes solides, jugent le monde à l\'aune de ce qu\'il devrait être et regardent l\'avenir avec un soupçon de désenchantement.',
    t: { ide: 0.9, epi: 0.85, fair: 0.8, opt: 0.2, vis: 0.85, nat: 0.7, dog: 0.7, vhe: 0.2, cfl: 0.2, inf: 0.2 } },
  { name: 'La frustration', by: 'Tension · l\'obstacle en travers', tag: 'Il manque si peu !', color: '#c1502e',
    desc: 'Elle surgit quand quelque chose bloque le chemin vers un but : le bug qui résiste, le train qui n\'arrive pas, la pièce qui ne rentre pas. Elle est d\'autant plus forte qu\'on tient au résultat, et elle pousse à chercher une autre voie. C\'est le tempérament des perfectionnistes déterminés, qui supportent mal l\'imprévu, veulent maîtriser les choses et ne lâchent jamais un problème.',
    t: { det: 0.9, vac: 0.85, rig: 0.85, ste: 0.05, san: 0.2, inc: 0.05, loc: 0.05, ord: 0.85, vhe: 0.2, dip: 0.3 } },
  { name: 'La vexation', by: 'Blessure · d\'amour-propre', tag: 'Non, non, tout va très bien', color: '#b56576',
    desc: 'Une remarque de travers, une invitation oubliée, et la voilà : elle ne dit rien, mais elle boude avec application. Elle protège l\'image qu\'on a de soi et signale qu\'une limite a été franchie. C\'est le tempérament des gens fiers et sensibles, attentifs aux égards et au rang, qui évitent l\'affrontement direct mais n\'oublient pas vite, et attendent qu\'on vienne s\'excuser.',
    t: { vpo: 0.85, auth: 0.75, cfl: 0.1, com: 0.2, san: 0.1, dip: 0.3, dog: 0.8, inc: 0.2, nat: 0.75, inf: 0.35 } },
  { name: 'La gêne', by: 'Émotion sociale · les joues roses', tag: 'Oh pardon, désolé, pardon', color: '#f5b7a5',
    desc: 'Elle surgit après une maladresse, un prénom oublié, une porte poussée au lieu de tirée, et se trahit par un rougissement. Elle sert en fait à montrer aux autres qu\'on connaît et respecte les règles. C\'est le tempérament des gens délicats et bien élevés, qui tiennent aux convenances, détestent déranger ou se faire remarquer et font tout pour que la vie en groupe reste harmonieuse.',
    t: { vco: 0.95, dip: 0.9, con: 0.85, dom: 0.05, com: 0.05, cfl: 0.05, inf: 0.2, aud: 0.05, emp: 0.8, auth: 0.7 } },
  { name: 'La timidité', by: 'Réserve · au bord du groupe', tag: 'Je parlerai quand je te connaîtrai', color: '#a3b8d9',
    desc: 'Elle hésite sur le seuil, parle bas et attend d\'être à l\'aise pour se montrer, ce qui peut prendre un moment. Mais une fois la confiance installée, elle révèle souvent un monde intérieur riche et un grand cœur. C\'est le tempérament des sensibles discrets, patients et attentifs aux autres, qui détestent se mettre en avant et laissent volontiers la lumière à ceux qui la réclament.',
    t: { soc: 0.05, inf: 0.02, aud: 0.05, att: 0.8, emp: 0.85, ste: 0.9, dom: 0.02, lea: 0.05, vig: 0.7, ide: 0.75 } },
  { name: 'La culpabilité', by: 'Émotion morale · qui répare', tag: 'C\'est ma faute, je vais arranger ça', color: '#7b6d8d',
    desc: 'Contrairement à la honte, qui juge ce qu\'on est, elle porte sur ce qu\'on a fait, et elle pousse à réparer : s\'excuser, rendre, corriger. Les psychologues la classent parmi les émotions morales. C\'est le tempérament des consciencieux scrupuleux, fiables et justes, qui se sentent responsables de tout, passent le plaisir après le devoir et ne laissent jamais une erreur sans suite.',
    t: { care: 0.9, fair: 0.95, fia: 0.95, loc: 0.02, rig: 0.85, vhe: 0.1, sanc: 0.75, vbe: 0.85, san: 0.3, lib: 0.3 } },
  { name: 'La honte', by: 'Émotion sociale · sous le regard des autres', tag: 'Si seulement je pouvais disparaître', color: '#8d5a6a',
    desc: 'Elle naît sous le regard du groupe, quand on pense avoir failli à ce qu\'il attend de nous, et donne envie de rentrer sous terre. Elle est désagréable, mais elle rappelle ce qui compte pour la communauté. C\'est le tempérament des gens profondément attachés aux normes, aux traditions et à l\'honneur, pour qui l\'appartenance compte plus que la liberté et qui ne transigent pas avec leurs valeurs.',
    t: { vco: 0.95, sanc: 0.9, vtr: 0.9, auth: 0.85, loy: 0.85, ind: 0.05, vsd: 0.05, lib: 0.1, chg: 0.1, inf: 0.1 } },
  { name: 'La tristesse', by: 'Émotion de base · qui ralentit', tag: 'Laisse-moi un peu de temps', color: '#4a6fa5',
    desc: 'Encore une émotion de base : elle ralentit le corps, baisse le regard et invite à se replier le temps de digérer une perte. Elle a aussi une fonction sociale, car les larmes appellent le soutien des autres. C\'est le tempérament des cœurs sensibles et profonds, qui s\'attachent vraiment, vivent leurs émotions sans les fuir et ne cherchent jamais à forcer leur entourage.',
    t: { att: 0.9, emp: 0.9, aff: 0.05, ste: 0.85, inf: 0.1, dom: 0.05, opt: 0.2, vhe: 0.2, cfl: 0.1, cmp: 0.1 } },
  { name: 'La solitude choisie', by: 'État · porte fermée, cœur ouvert', tag: 'Moi, un livre, et la paix', color: '#4d7c8a',
    desc: 'Rien à voir avec l\'isolement : c\'est le plaisir d\'une journée sans personne, choisie et savourée, pour lire, marcher ou penser. Elle recharge ce que les autres fatiguent. C\'est le tempérament des indépendants tranquilles, qui n\'ont besoin ni de groupe ni d\'approbation, restent calmes en toutes circonstances et cultivent leur jardin intérieur avec un soin jaloux.',
    t: { ind: 0.98, vsd: 0.98, soc: 0.02, col: 0.05, att: 0.2, san: 0.9, ste: 0.85, inf: 0.05, ouv: 0.8, loy: 0.2 } },
  { name: 'La saudade', by: 'Mot portugais · intraduisible', tag: 'Le manque de ce qui est loin', color: '#1d6f8c',
    desc: 'Au cœur du fado, ce mot portugais réputé intraduisible dit le manque tendre de quelqu\'un ou de quelque chose d\'absent, parfois perdu, parfois simplement loin, au-delà de la mer. Elle fait mal et fait du bien à la fois. C\'est le tempérament des sentimentaux voyageurs, rêveurs et fidèles, qui aiment partir mais laissent toujours une part d\'eux-mêmes à ceux qui sont restés.',
    t: { att: 0.95, opn: 0.1, vst: 0.75, ouv: 0.8, aff: 0.05, vtr: 0.75, opt: 0.35, loy: 0.9, ide: 0.85, rig: 0.2 } },
  { name: 'Le hygge', by: 'Mot danois · bougies et plaid', tag: 'Une soupe, des amis, la pluie dehors', color: '#c68b59',
    desc: 'Mot danois venu du norvégien, il désigne ce sentiment de chaleur et de sécurité d\'une soirée d\'hiver entre proches, bougies allumées et thé qui fume. Rien d\'extraordinaire, et c\'est tout l\'intérêt. C\'est le tempérament des gens casaniers et chaleureux, qui détestent la compétition et les risques, aiment les rituels simples et savent faire d\'un soir ordinaire un moment précieux.',
    t: { vhe: 0.9, vse: 0.9, att: 0.9, ste: 0.95, vst: 0.05, rsk: 0.05, cmp: 0.02, vac: 0.1, opn: 0.8, vtr: 0.75 } },
  { name: 'La sérendipité', by: 'Heureux hasard · sans l\'avoir cherché', tag: 'Je cherchais autre chose', color: '#3fb6a8',
    desc: 'Le mot a été forgé en 1754 par l\'écrivain anglais Horace Walpole, d\'après un conte où les princes de Serendip trouvent sans cesse ce qu\'ils ne cherchaient pas. C\'est ainsi, raconte-t-on, que la pénicilline est née d\'une boîte oubliée. C\'est le tempérament des optimistes ouverts, qui avancent sans plan, laissent faire le hasard et savent reconnaître une bonne surprise quand elle passe.',
    t: { inc: 0.98, loc: 0.9, opt: 0.9, ord: 0.05, ouv: 0.95, rsk: 0.8, vis: 0.05, rig: 0.1, epi: 0.1, vig: 0.1 } },
  { name: 'Le dégoût', by: 'Émotion de base · le nez froncé', tag: 'Très peu pour moi, merci', color: '#6b8e23',
    desc: 'Nez froncé, lèvre retroussée : c\'est l\'émotion de base qui nous a protégés des aliments avariés, et qui s\'étend aussi à ce qui nous paraît moralement souillé. Elle trie sans hésiter ce qui est acceptable et ce qui ne l\'est pas. C\'est le tempérament des gens exigeants et tranchés, attachés à la pureté et aux règles, qui savent très exactement ce qu\'ils ne toléreront jamais.',
    t: { sanc: 0.98, rig: 0.9, con: 0.95, vig: 0.8, ouv: 0.1, inc: 0.1, vhe: 0.2, dog: 0.85, vst: 0.1, soc: 0.3 } },
  { name: 'La peur', by: 'Émotion de base · plus vite que la pensée', tag: 'D\'abord se mettre à l\'abri', color: '#2f3e46',
    desc: 'Elle démarre avant même qu\'on ait compris ce qui se passe, et c\'est sa force : elle a gardé nos ancêtres en vie en les faisant fuir ou se figer au bon moment. Elle voit les dangers que les autres ne voient pas. C\'est le tempérament des prudents lucides, qui ne prennent aucun risque inutile, se méfient de ce qui brille et préfèrent un monde sûr à un monde excitant.',
    t: { vig: 0.98, thr: 0.98, rsk: 0.02, aud: 0.02, san: 0.2, vse: 0.95, nat: 0.8, inc: 0.05, dom: 0.1, vis: 0.8 } },
];

window.PRISME_EMOTIONS = { EMOTIONS };
