/* ============================================================
   PRISME — « Si tu étais un film »
   ------------------------------------------------------------
   Même principe que les personnages et les animaux : chaque film
   est décrit par son tempérament, avec les dimensions du test.
   On ne juge pas le goût : on compare un caractère à un autre.
     name = titre, by = réalisation et année, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const FILMS = [
  { name: 'Le Parrain', by: 'Francis Ford Coppola · 1972', tag: 'La famille avant tout', color: '#7a2f2f',
    desc: 'Un homme qui voulait rester en dehors des affaires familiales y entre pour protéger les siens, et n\'en ressort jamais. Tout y est question de loyauté, de patience et de calcul froid, dans une lumière d\'ambre. Le film avance lentement, sûr de lui, sans jamais hausser le ton.',
    t: { att: 0.95, loy: 0.95, tmp: 0.9, san: 0.9, aff: 0.85, dom: 0.9, rig: 0.85, vtr: 0.9, vpo: 0.85, ouv: 0.15 } },
  { name: 'Pulp Fiction', by: 'Quentin Tarantino · 1994', tag: 'Le désordre jubilatoire', color: '#d62828',
    desc: 'Trois histoires mélangées, des dialogues qui partent sur les hamburgers au milieu d\'une fusillade, et une structure qui se moque de l\'ordre chronologique. Le film est cool, bavard, imprévisible, et parfaitement conscient de son propre style.',
    t: { vst: 0.95, ouv: 0.9, inf: 0.9, ord: 0.05, vhe: 0.9, aud: 0.9, soc: 0.85, epi: 0.1, tmp: 0.15, san: 0.6 } },
  { name: 'Fight Club', by: 'David Fincher · 1999', tag: 'La colère contre soi-même',
    color: '#5a5a66',
    desc: 'Un homme qui s\'ennuie dans sa vie rangée invente une échappatoire qui devient un mouvement, puis un problème. Le film est nerveux, sarcastique, profondément méfiant envers tout ce qui ressemble à du confort. Il détruit avant de savoir ce qu\'il veut construire.',
    t: { chg: 0.95, com: 0.9, nat: 0.9, ind: 0.9, vis: 0.85, aud: 0.9, vco: 0.05, ste: 0.1, vac: 0.2, cfl: 0.9 } },
  { name: 'Matrix', by: 'Les Wachowski · 1999', tag: 'Et si tout était faux ?', color: '#2f9e62',
    desc: 'Un informaticien découvre que le monde qu\'il habite est une simulation, et doit choisir entre le confort du mensonge et la dureté du réel. Le film pose une question philosophique dans un emballage d\'action, et croit très fort à la capacité d\'un individu à tout changer.',
    t: { ouv: 0.9, nat: 0.9, chg: 0.9, ide: 0.85, aff: 0.8, aud: 0.85, vsd: 0.9, inc: 0.8, vco: 0.1, opn: 0.1 } },
  { name: 'Interstellar', by: 'Christopher Nolan · 2014', tag: 'L\'amour à l\'échelle cosmique', color: '#1f7a8c',
    desc: 'Un père quitte ses enfants pour sauver l\'humanité, et passe le film à essayer de revenir. Ambitieux, cérébral, il déploie des équations et des trous noirs pour finir par dire quelque chose de très simple sur le lien entre deux personnes.',
    t: { tmp: 0.98, att: 0.95, aff: 0.85, ide: 0.85, det: 0.9, care: 0.9, aud: 0.85, vun: 0.8, vhe: 0.2, ste: 0.3 } },
  { name: 'Whiplash', by: 'Damien Chazelle · 2014', tag: 'L\'excellence à n\'importe quel prix', color: '#c2850c',
    desc: 'Un batteur et un professeur qui le brise méthodiquement, dans une salle de répétition qui ressemble à une cage. Le film ne tranche jamais vraiment la question qu\'il pose : jusqu\'où peut-on aller pour être le meilleur ? Sec, tendu, épuisant.',
    t: { vac: 0.98, cmp: 0.95, det: 0.98, rig: 0.95, com: 0.9, ind: 0.85, emp: 0.1, vhe: 0.1, ste: 0.05, dip: 0.1 } },
  { name: 'Forrest Gump', by: 'Robert Zemeckis · 1994', tag: 'La bonté qui traverse tout', color: '#57a639',
    desc: 'Un homme simple traverse trente ans d\'histoire américaine sans jamais changer de nature : il fait ce qu\'on lui dit, il court quand il faut courir, il aime la même personne toute sa vie. Le film est tendre, naïf par choix, et profondément confiant dans les gens.',
    t: { fia: 0.95, loy: 0.98, opt: 0.9, vbe: 0.9, ste: 0.9, emp: 0.85, nat: 0.05, aff: 0.15, vac: 0.2, att: 0.95 } },
  { name: 'Le Fabuleux Destin d\'Amélie Poulain', by: 'Jean-Pierre Jeunet · 2001', tag: 'La tendresse bricolée', color: '#57a639',
    desc: 'Une jeune femme timide décide d\'arranger discrètement la vie des autres, par petites interventions poétiques. Le film est coloré, minutieux, plein de détails inutiles et merveilleux — et il évite soigneusement de parler de ce qui fâche.',
    t: { emp: 0.9, care: 0.9, ide: 0.85, opt: 0.9, ouv: 0.8, soc: 0.4, vhe: 0.8, ind: 0.7, com: 0.05, dom: 0.1 } },
  { name: 'Intouchables', by: 'Nakache et Toledano · 2011', tag: 'L\'amitié qui décoince', color: '#e08700',
    desc: 'Deux hommes que tout sépare finissent par se faire un bien fou, essentiellement parce qu\'aucun des deux ne traite l\'autre avec précaution. Le film est chaleureux, drôle, et refuse obstinément le registre du pathos.',
    t: { soc: 0.95, opt: 0.9, vhe: 0.9, emp: 0.85, inf: 0.9, dip: 0.6, care: 0.85, vco: 0.15, thr: 0.15, cmp: 0.2 } },
  { name: 'La Haine', by: 'Mathieu Kassovitz · 1995', tag: 'La chute, jusqu\'ici tout va bien', color: '#3d3946',
    desc: 'Vingt-quatre heures dans une banlieue au lendemain d\'une bavure, avec trois amis qui n\'ont nulle part où aller. Le film est frontal, nerveux, en noir et blanc, et il ne propose aucune sortie — c\'est précisément son propos.',
    t: { com: 0.95, cfl: 0.95, vis: 0.95, nat: 0.9, eng: 0.85, col: 0.8, opt: 0.05, dip: 0.1, vse: 0.1, tmp: 0.1 } },
  { name: 'Les Évadés', by: 'Frank Darabont · 1994', tag: 'L\'espoir, patiemment', color: '#8a6a2f',
    desc: 'Un homme condamné à tort creuse pendant vingt ans, un peu chaque nuit, sans jamais le dire à personne. Le film est calme, chaleureux, et croit que la dignité se maintient par de petites choses répétées longtemps.',
    t: { tmp: 0.98, det: 0.98, san: 0.9, ide: 0.9, fia: 0.9, opt: 0.8, rig: 0.85, ste: 0.8, com: 0.2, vst: 0.1 } },
  { name: 'Seven', by: 'David Fincher · 1995', tag: 'La noirceur méthodique', color: '#46596b',
    desc: 'Deux inspecteurs face à un tueur qui suit un plan moral d\'une rigueur écœurante, dans une ville où il pleut sans arrêt. Le film est froid, sombre, extrêmement construit, et il ne laisse aucune porte ouverte.',
    t: { aff: 0.9, rig: 0.9, vis: 0.98, nat: 0.95, thr: 0.9, vig: 0.9, san: 0.75, opt: 0.02, vhe: 0.05, dog: 0.85 } },
  { name: 'Mad Max: Fury Road', by: 'George Miller · 2015', tag: 'La fuite en avant', color: '#e2452f',
    desc: 'Deux heures de poursuite dans le désert, presque sans dialogue, avec un sens du mouvement qui ne retombe jamais. Le film ne s\'explique pas : il fonce, et les personnages se définissent uniquement par ce qu\'ils font.',
    t: { aud: 0.98, rsk: 0.95, det: 0.95, com: 0.9, vst: 0.9, chg: 0.9, ste: 0.02, tmp: 0.15, aff: 0.15, dip: 0.1 } },
  { name: 'Into the Wild', by: 'Sean Penn · 2007', tag: 'La liberté radicale', color: '#8a9a5b',
    desc: 'Un jeune diplômé brûle son argent et part vivre seul en Alaska, par refus total du monde qu\'on lui propose. Le film est lumineux, exalté, et finit par se demander si le bonheur compte vraiment quand il n\'est partagé avec personne.',
    t: { ind: 0.98, lib: 0.98, vsd: 0.95, aud: 0.9, ide: 0.9, chg: 0.85, col: 0.1, vco: 0.05, vse: 0.05, vac: 0.15 } },
  { name: 'Le Cercle des poètes disparus', by: 'Peter Weir · 1989', tag: 'Penser par soi-même', color: '#7a6033',
    desc: 'Un professeur apprend à des élèves d\'un internat rigide à monter sur les tables et à lire autrement. Le film est chaleureux, romantique, et il n\'élude pas le prix que peut coûter une émancipation dans un milieu qui n\'en veut pas.',
    t: { ide: 0.95, ouv: 0.9, vsd: 0.9, emp: 0.85, care: 0.85, inf: 0.8, auth: 0.15, vco: 0.15, opn: 0.25, cfl: 0.3 } },
  { name: 'OSS 117 : Le Caire, nid d\'espions', by: 'Michel Hazanavicius · 2006', tag: 'L\'assurance absolue, sans fondement', color: '#d9a441',
    desc: 'Un agent secret d\'une bêtise magistrale traverse le film avec une confiance en lui que rien n\'entame. La mécanique comique repose entièrement sur l\'écart entre ce qu\'il croit être et ce qu\'il est. Léger, ciselé, increvable en soirée.',
    t: { vac: 0.9, dog: 0.95, inf: 0.9, soc: 0.85, vhe: 0.9, opt: 0.9, ouv: 0.05, emp: 0.1, rig: 0.2, thr: 0.05 } },
  { name: 'Astérix : Mission Cléopâtre', by: 'Alain Chabat · 2002', tag: 'La bonne humeur collective', color: '#e9a100',
    desc: 'Un chantier impossible, une équipe bancale, et une avalanche de répliques que tout le monde connaît par cœur. Le film tient par la générosité : chaque acteur a son moment, personne n\'écrase personne, et tout finit par un banquet.',
    t: { soc: 0.95, col: 0.9, vhe: 0.95, opt: 0.95, inf: 0.9, dip: 0.8, emp: 0.8, cmp: 0.15, com: 0.2, rig: 0.2 } },
  { name: 'Le Voyage de Chihiro', by: 'Hayao Miyazaki · 2001', tag: 'Le courage tranquille', color: '#3ec9c9',
    desc: 'Une enfant se retrouve seule dans un monde dont elle ne comprend pas les règles, et s\'en sort par le travail, la politesse et la fidélité à ce qu\'elle est. Le film est doux, étrange, sans véritable méchant, et il prend son temps.',
    t: { det: 0.9, fia: 0.9, care: 0.9, inc: 0.9, ouv: 0.85, emp: 0.9, ste: 0.8, com: 0.1, dom: 0.1, vpo: 0.05 } },
  { name: 'Princesse Mononoké', by: 'Hayao Miyazaki · 1997', tag: 'Un conflit sans méchant', color: '#4f7942',
    desc: 'Une forêt contre une forge, et un héros qui refuse de choisir un camp parce qu\'il voit les raisons des deux. Le film est ample, violent, et se termine sans réconciliation facile : il faut vivre avec le désaccord.',
    t: { vun: 0.95, dip: 0.85, ide: 0.9, com: 0.7, ouv: 0.9, care: 0.9, epi: 0.4, dog: 0.15, opt: 0.5, tmp: 0.9 } },
  { name: 'Parasite', by: 'Bong Joon-ho · 2019', tag: 'L\'escalier social', color: '#5c7fa3',
    desc: 'Une famille pauvre s\'infiltre chez une famille riche, et la comédie bascule lentement vers autre chose. Le film est d\'une précision d\'orfèvre, drôle puis glaçant, et il n\'accorde de vraie innocence à personne.',
    t: { aff: 0.9, rig: 0.9, nat: 0.85, cmp: 0.85, vis: 0.85, aud: 0.8, ouv: 0.7, vco: 0.2, opt: 0.15, care: 0.5 } },
  { name: 'Your Name', by: 'Makoto Shinkai · 2016', tag: 'Le lien malgré la distance', color: '#e05fa0',
    desc: 'Deux adolescents échangent de corps sans se connaître, et finissent par se chercher à travers le temps. Le film est lumineux, sentimental sans honte, et parle surtout de ce qu\'on garde de quelqu\'un quand on ne se souvient plus de son nom.',
    t: { att: 0.95, emp: 0.9, ide: 0.9, care: 0.85, tmp: 0.8, opt: 0.8, aff: 0.2, com: 0.1, cmp: 0.1, vhe: 0.6 } },
  { name: 'Coco', by: 'Lee Unkrich · 2017', tag: 'La mémoire des siens', color: '#e08700',
    desc: 'Un enfant veut faire de la musique dans une famille qui l\'interdit, et traverse le monde des morts pour comprendre pourquoi. Le film est chaleureux, coloré, et défend l\'idée qu\'on existe tant que quelqu\'un se souvient de nous.',
    t: { att: 0.95, vtr: 0.9, care: 0.9, emp: 0.9, col: 0.9, opt: 0.85, ide: 0.8, soc: 0.8, ind: 0.3, nat: 0.15 } },
  { name: 'Là-haut', by: 'Pete Docter · 2009', tag: 'Partir quand même', color: '#4dc9ff',
    desc: 'Un vieil homme attache des milliers de ballons à sa maison pour tenir une promesse faite cinquante ans plus tôt. Le film commence par dix minutes de chagrin parfait, puis choisit l\'aventure — et l\'idée qu\'il n\'est jamais trop tard.',
    t: { att: 0.95, tmp: 0.85, det: 0.9, opn: 0.85, emp: 0.85, aud: 0.8, care: 0.85, vis: 0.6, com: 0.4, vst: 0.5 } },
  { name: 'Vice-Versa', by: 'Pete Docter · 2015', tag: 'Faire de la place à la tristesse', color: '#9b5de5',
    desc: 'Les émotions d\'une enfant de onze ans sont des personnages, et le film explique très clairement pourquoi vouloir être joyeux en permanence ne marche pas. Intelligent, tendre, et étonnamment précis sur le fonctionnement intérieur.',
    t: { emp: 0.95, aff: 0.75, care: 0.9, ouv: 0.9, dip: 0.85, inc: 0.8, opt: 0.6, com: 0.1, cmp: 0.1, vun: 0.8 } },
  { name: 'Ratatouille', by: 'Brad Bird · 2007', tag: 'Le talent là où on ne l\'attend pas', color: '#d62828',
    desc: 'Un rat veut cuisiner, ce qui est un problème évident, et il le fait quand même avec une exigence de chef. Le film défend une idée simple et ferme : ce n\'est pas l\'origine qui décide, c\'est ce qu\'on est capable de faire.',
    t: { ide: 0.9, det: 0.9, vac: 0.85, ouv: 0.9, rig: 0.9, fair: 0.9, aud: 0.85, vco: 0.2, opn: 0.2, cmp: 0.6 } },
  { name: 'Wall-E', by: 'Andrew Stanton · 2008', tag: 'La persévérance silencieuse', color: '#c9a227',
    desc: 'Un robot range les déchets d\'une planète abandonnée depuis des siècles, seul, sans que personne lui ait dit d\'arrêter. Quarante minutes sans dialogue, une tendresse immense, et une critique sociale sous le vernis.',
    t: { fia: 0.95, det: 0.95, ste: 0.9, care: 0.9, att: 0.9, opt: 0.8, ord: 0.85, soc: 0.15, com: 0.1, vpo: 0.02 } },
  { name: 'Retour vers le futur', by: 'Robert Zemeckis · 1985', tag: 'L\'énergie bricoleuse', color: '#e9a100',
    desc: 'Un adolescent et un inventeur excentrique font n\'importe quoi avec le temps et s\'en sortent de justesse à chaque fois. Le film est rapide, malin, optimiste, et construit comme une horlogerie où chaque détail sert plus tard.',
    t: { ouv: 0.9, aud: 0.9, opt: 0.9, vst: 0.9, inf: 0.85, rig: 0.8, soc: 0.8, thr: 0.25, ste: 0.15, epi: 0.1 } },
  { name: 'Rocky', by: 'John G. Avildsen · 1976', tag: 'Tenir debout à la fin', color: '#b5734a',
    desc: 'Un boxeur sans avenir obtient une chance absurde et ne cherche même pas à gagner : il veut seulement tenir jusqu\'au bout. Le film est modeste, tendre, beaucoup moins spectaculaire qu\'on ne s\'en souvient, et entièrement construit sur l\'effort.',
    t: { det: 0.98, eng: 0.9, opn: 0.9, att: 0.9, ide: 0.85, opt: 0.8, vac: 0.6, fia: 0.9, aff: 0.2, vpo: 0.15 } },
  { name: 'Gladiator', by: 'Ridley Scott · 2000', tag: 'La vengeance avec les honneurs', color: '#8b5e3c',
    desc: 'Un général trahi devient esclave, puis combattant, et remonte méthodiquement vers celui qui lui a tout pris. Le film est ample, solennel, obsédé par l\'honneur et par la dignité du devoir accompli.',
    t: { det: 0.95, loy: 0.9, att: 0.9, auth: 0.8, com: 0.85, fia: 0.9, san: 0.8, tmp: 0.8, vhe: 0.15, dip: 0.3 } },
  { name: 'Apocalypse Now', by: 'Francis Ford Coppola · 1979', tag: 'La remontée du fleuve', color: '#4f5b3a',
    desc: 'Une mission simple devient une descente hallucinée où la guerre perd tout sens en même temps que ceux qui la font. Le film est lent, moite, magnifique et malade — il ne cherche ni à expliquer ni à conclure.',
    t: { vis: 0.98, nat: 0.9, inc: 0.85, aff: 0.6, ind: 0.85, epi: 0.7, opt: 0.02, ord: 0.1, dip: 0.1, tmp: 0.5 } },
  { name: 'Le Silence des agneaux', by: 'Jonathan Demme · 1991', tag: 'L\'analyse face à face', color: '#5b5468',
    desc: 'Une jeune recrue du FBI doit obtenir l\'aide d\'un homme qui lit en elle mieux qu\'elle-même. Le film tient presque entièrement sur des conversations, et sa tension vient de l\'intelligence, pas de l\'action.',
    t: { aff: 0.95, rig: 0.9, san: 0.85, vig: 0.9, det: 0.9, thr: 0.8, ind: 0.8, nat: 0.85, soc: 0.15, vhe: 0.05 } },
  { name: 'Shining', by: 'Stanley Kubrick · 1980', tag: 'L\'enfermement', color: '#8a8f98',
    desc: 'Une famille garde un hôtel vide pendant l\'hiver, et l\'un d\'eux se désagrège lentement. Le film est d\'une symétrie glaçante, très lent, et son horreur vient surtout de couloirs trop grands et de silences trop longs.',
    t: { thr: 0.95, vis: 0.9, ord: 0.85, nat: 0.9, ind: 0.85, san: 0.4, com: 0.75, opt: 0.02, soc: 0.05, care: 0.15 } },
  { name: 'Alien', by: 'Ridley Scott · 1979', tag: 'La peur méthodique', color: '#4a4159',
    desc: 'Un équipage de camionneurs de l\'espace découvre qu\'il n\'est pas seul à bord. Le film ne montre presque rien, avance très lentement, et fait de la survie une affaire de procédure et de sang-froid.',
    t: { thr: 0.98, vig: 0.95, san: 0.8, det: 0.9, rig: 0.85, col: 0.6, opt: 0.1, inf: 0.1, vhe: 0.05, nat: 0.85 } },
  { name: 'Terminator 2', by: 'James Cameron · 1991', tag: 'Apprendre à protéger', color: '#6b7280',
    desc: 'Une machine programmée pour tuer devient la seule figure fiable dans la vie d\'un gamin. Le film est un blockbuster parfaitement réglé qui parle, sans en avoir l\'air, de ce qu\'on transmet et de ce qu\'on peut réparer.',
    t: { fia: 0.95, care: 0.9, det: 0.95, ord: 0.85, tmp: 0.8, att: 0.85, aud: 0.85, chg: 0.7, vhe: 0.15, soc: 0.3 } },
  { name: 'Jurassic Park', by: 'Steven Spielberg · 1993', tag: 'L\'émerveillement imprudent', color: '#57a639',
    desc: 'On peut le faire, donc on le fait — et la question de savoir si on aurait dû arrive un peu tard. Le film garde intacte sa capacité d\'émerveillement, et sa critique de la démesure technique n\'a pas vieilli.',
    t: { ouv: 0.9, vst: 0.9, aud: 0.85, opt: 0.7, thr: 0.7, care: 0.7, rig: 0.5, vis: 0.6, tmp: 0.35, dog: 0.3 } },
  { name: 'E.T. l\'extra-terrestre', by: 'Steven Spielberg · 1982', tag: 'L\'amitié improbable', color: '#a97142',
    desc: 'Un enfant solitaire cache une créature dans sa chambre et fait tout pour la ramener chez elle. Le film est filmé à hauteur d\'enfant, tendre, et beaucoup plus triste qu\'on ne s\'en souvient.',
    t: { care: 0.95, emp: 0.95, att: 0.9, ide: 0.85, vbe: 0.9, opt: 0.75, aud: 0.7, nat: 0.3, com: 0.1, vpo: 0.02 } },
  { name: 'Les Affranchis', by: 'Martin Scorsese · 1990', tag: 'L\'ascension et la chute', color: '#7a4a2a',
    desc: 'Trente ans de vie criminelle racontés à toute vitesse, avec l\'euphorie d\'abord et la paranoïa ensuite. Le film est grisant, cynique, et montre très bien comment on s\'habitue à n\'importe quoi.',
    t: { vst: 0.9, vhe: 0.9, cmp: 0.85, nat: 0.85, loy: 0.7, aud: 0.9, vpo: 0.8, vco: 0.1, tmp: 0.15, rig: 0.3 } },
  { name: 'La Ligne verte', by: 'Frank Darabont · 1999', tag: 'La compassion face à l\'injustice', color: '#5fa860',
    desc: 'Des gardiens de couloir de la mort découvrent que le condamné dont ils s\'occupent guérit les gens. Le film est long, lent, et déploie une immense douceur dans un endroit qui n\'en a pas.',
    t: { care: 0.98, emp: 0.95, fair: 0.9, ide: 0.9, fia: 0.9, ste: 0.85, tmp: 0.8, vis: 0.6, com: 0.2, cmp: 0.05 } },
  { name: '12 hommes en colère', by: 'Sidney Lumet · 1957', tag: 'Le doute raisonnable', color: '#6b8fa3',
    desc: 'Douze jurés dans une pièce surchauffée, et un seul qui demande qu\'on prenne le temps de discuter. Le film ne quitte jamais la salle et montre, argument après argument, comment une conviction collective se défait.',
    t: { aff: 0.9, fair: 0.98, rig: 0.9, dip: 0.8, ouv: 0.95, det: 0.9, ide: 0.85, dog: 0.1, com: 0.6, col: 0.75 } },
  { name: 'Le Discours d\'un roi', by: 'Tom Hooper · 2010', tag: 'Surmonter, à voix haute', color: '#7a6a4a',
    desc: 'Un homme qui bégaie doit parler à une nation en guerre, et y arrive grâce à un professeur sans diplôme. Le film est sobre, pudique, et parle surtout d\'une amitié entre deux hommes que tout sépare.',
    t: { det: 0.9, fia: 0.9, dip: 0.85, thr: 0.8, emp: 0.85, auth: 0.7, vtr: 0.8, rig: 0.8, vhe: 0.2, aud: 0.4 } },
  { name: 'Joker', by: 'Todd Phillips · 2019', tag: 'La bascule', color: '#6a3fa0',
    desc: 'Un homme méprisé par tout le monde finit par devenir le symbole qu\'il n\'avait pas cherché à être. Le film est malaisant, subjectif, et refuse de dire clairement ce qui est arrivé et ce qui a été imaginé.',
    t: { vis: 0.98, nat: 0.95, com: 0.85, ind: 0.85, chg: 0.9, cfl: 0.9, opt: 0.02, san: 0.1, dip: 0.05, care: 0.3 } },
  { name: 'Dune', by: 'Denis Villeneuve · 2021', tag: 'Le poids du destin', color: '#c9a227',
    desc: 'Un héritier est poussé vers un rôle prophétique qu\'il redoute, dans un monde où chaque alliance cache un calcul. Le film est lent, monumental, presque silencieux, et plus intéressé par le politique que par l\'action.',
    t: { tmp: 0.95, aff: 0.85, rig: 0.85, vpo: 0.75, nat: 0.85, vtr: 0.8, san: 0.8, thr: 0.8, vhe: 0.1, soc: 0.2 } },
  { name: 'Everything Everywhere All at Once', by: 'Daniels · 2022', tag: 'Le chaos, et l\'amour quand même', color: '#e05fa0',
    desc: 'Une gérante de laverie débordée traverse des milliers de versions d\'elle-même pour finir par réparer une relation avec sa fille. Le film part dans tous les sens à une vitesse folle, et atterrit sur quelque chose de très simple : la gentillesse.',
    t: { ouv: 0.98, vst: 0.95, chg: 0.9, emp: 0.9, care: 0.9, inc: 0.95, att: 0.9, ord: 0.05, epi: 0.15, dog: 0.05 } },
  { name: 'Le Loup de Wall Street', by: 'Martin Scorsese · 2013', tag: 'L\'excès sans frein', color: '#c2850c',
    desc: 'Trois heures d\'ascension, de fête et d\'arnaque, racontées par quelqu\'un qui n\'a jamais rien regretté. Le film est épuisant volontairement, très drôle, et laisse au spectateur le soin de juger.',
    t: { vpo: 0.95, vhe: 0.98, vac: 0.95, cmp: 0.9, aud: 0.95, inf: 0.9, vco: 0.02, fair: 0.05, ste: 0.05, tmp: 0.1 } },
  { name: 'Premier Contact', by: 'Denis Villeneuve · 2016', tag: 'Comprendre avant de juger', color: '#6b8fa3',
    desc: 'Une linguiste doit apprendre à parler à des visiteurs pendant que le reste du monde prépare la guerre. Le film est calme, mélancolique, et défend l\'idée que la langue qu\'on emploie change ce qu\'on est capable de penser.',
    t: { aff: 0.9, ouv: 0.95, dip: 0.95, tmp: 0.95, emp: 0.9, san: 0.9, inc: 0.9, care: 0.85, com: 0.05, cfl: 0.05 } },
  { name: 'Gravity', by: 'Alfonso Cuarón · 2013', tag: 'La survie nue', color: '#8a8f98',
    desc: 'Une astronaute perdue dans le vide essaie simplement de rentrer, étape par étape, avec ce qu\'elle a sous la main. Le film est court, silencieux, et transforme chaque geste technique en question de vie ou de mort.',
    t: { det: 0.95, thr: 0.9, san: 0.75, ind: 0.9, rig: 0.85, vig: 0.9, vse: 0.85, soc: 0.05, com: 0.1, opt: 0.45 } },
  { name: 'Slumdog Millionaire', by: 'Danny Boyle · 2008', tag: 'La vie comme réponse', color: '#e08700',
    desc: 'Un garçon des bidonvilles gagne à un jeu télévisé parce que chaque question correspond à un épisode de sa vie. Le film est rapide, coloré, dur par moments, et profondément romanesque.',
    t: { opt: 0.85, det: 0.9, att: 0.9, aud: 0.85, loc: 0.6, ide: 0.85, care: 0.85, vhe: 0.7, rig: 0.3, vpo: 0.2 } },
  { name: 'Titanic', by: 'James Cameron · 1997', tag: 'Le romantisme total', color: '#1c86c9',
    desc: 'Une histoire d\'amour de quelques jours sur un bateau dont tout le monde connaît la fin. Le film assume entièrement son emphase, son ampleur et ses sentiments, sans aucune ironie — c\'est sa force.',
    t: { att: 0.95, ide: 0.9, emp: 0.9, aud: 0.85, vhe: 0.8, lib: 0.85, care: 0.85, vco: 0.15, aff: 0.15, cmp: 0.2 } },
  { name: 'Le Grand Bleu', by: 'Luc Besson · 1988', tag: 'L\'appel du silence', color: '#1f7a8c',
    desc: 'Deux apnéistes se poussent l\'un l\'autre toujours plus profond, jusqu\'à ce que la mer compte plus que la surface. Le film est contemplatif, un peu irréel, et parle d\'une vocation qui ne laisse pas de place au reste.',
    t: { ind: 0.9, vsd: 0.85, cmp: 0.8, san: 0.8, vis: 0.6, soc: 0.2, att: 0.5, tmp: 0.5, vco: 0.1, ide: 0.8 } },
  { name: 'Le Dîner de cons', by: 'Francis Veber · 1998', tag: 'La mécanique cruelle', color: '#d9a441',
    desc: 'Un homme invite un naïf pour se moquer de lui et se retrouve pris dans une catastrophe en chaîne. Le film est une horlogerie comique impeccable, et le prétendu imbécile finit par être le seul personnage attachant.',
    t: { inf: 0.9, soc: 0.8, vhe: 0.85, care: 0.6, cmp: 0.7, rig: 0.7, aff: 0.55, nat: 0.6, dip: 0.3, vco: 0.4 } },
  { name: 'Inception', by: 'Christopher Nolan · 2010', tag: 'L\'architecture mentale', color: '#46596b',
    desc: 'Une équipe entre dans les rêves pour y déposer une idée, avec des règles précises et une horloge qui tourne. Le film est un puzzle méticuleux, froid, où l\'émotion reste enfermée derrière la mécanique.',
    t: { aff: 0.95, rig: 0.95, ord: 0.9, tmp: 0.85, det: 0.9, san: 0.85, thr: 0.8, vst: 0.7, soc: 0.2, vhe: 0.15 } },
  { name: 'Blade Runner 2049', by: 'Denis Villeneuve · 2017', tag: 'La mélancolie du faux', color: '#c2670c',
    desc: 'Un enquêteur cherche un enfant qui n\'aurait pas dû exister, et découvre surtout qu\'il n\'est pas celui qu\'il espérait être. Le film est d\'une lenteur assumée, somptueux, et parle de ce qui rend une vie vraie.',
    t: { vis: 0.9, tmp: 0.85, san: 0.9, ind: 0.9, aff: 0.8, ide: 0.7, emp: 0.75, soc: 0.1, opt: 0.15, com: 0.15 } },
  { name: 'Akira', by: 'Katsuhiro Ōtomo · 1988', tag: 'L\'énergie qu\'on ne contrôle plus', color: '#d62828',
    desc: 'Un adolescent reçoit un pouvoir immense et bascule en quelques jours, dans une ville au bord de l\'explosion. Le film est dense, brutal, politique, et son animation n\'a pas pris une ride.',
    t: { chg: 0.98, com: 0.95, cfl: 0.9, vis: 0.9, aud: 0.9, nat: 0.85, san: 0.1, dip: 0.05, ste: 0.05, vco: 0.1 } },
  { name: 'Old Boy', by: 'Park Chan-wook · 2003', tag: 'La vengeance et son prix', color: '#7a2f2f',
    desc: 'Un homme enfermé quinze ans sans explication en sort pour comprendre pourquoi, et aurait mieux fait de ne pas savoir. Le film est d\'une violence stylisée et d\'une tristesse totale.',
    t: { det: 0.98, com: 0.9, nat: 0.95, ind: 0.9, vis: 0.95, cfl: 0.9, tmp: 0.6, san: 0.4, dip: 0.05, opt: 0.02 } },
  { name: 'Full Metal Jacket', by: 'Stanley Kubrick · 1987', tag: 'La machine à fabriquer', color: '#4f5b3a',
    desc: 'Une première partie dans un camp d\'entraînement qui broie, une seconde dans une guerre qui n\'a plus de forme. Le film est froid, méthodique, et regarde le conditionnement comme un phénomène d\'ingénierie.',
    t: { auth: 0.9, ord: 0.9, rig: 0.9, com: 0.85, vis: 0.9, con: 0.85, emp: 0.1, care: 0.1, vhe: 0.1, dip: 0.05 } },
  { name: 'Le Roi Lion', by: 'Allers et Minkoff · 1994', tag: 'Reprendre sa place', color: '#e9a100',
    desc: 'Un héritier fuit une faute qu\'il n\'a pas commise et doit revenir affronter ce qu\'il a laissé. Le film est ample, solennel, plein de chansons, et raconte une histoire de transmission vieille comme le théâtre.',
    t: { att: 0.9, vtr: 0.9, auth: 0.8, det: 0.8, care: 0.85, loc: 0.4, opt: 0.7, col: 0.8, vhe: 0.6, ouv: 0.4 } },
  { name: 'Toy Story', by: 'John Lasseter · 1995', tag: 'La loyauté dans la boîte à jouets', color: '#2a75bb',
    desc: 'Deux jouets qui se détestent doivent s\'entraider pour rentrer, et finissent par ne plus pouvoir se passer l\'un de l\'autre. Le film est drôle, rythmé, et sérieux sur ce que signifie être remplacé.',
    t: { loy: 0.95, att: 0.9, col: 0.85, fia: 0.9, opt: 0.85, soc: 0.8, cmp: 0.5, care: 0.85, nat: 0.15, ind: 0.3 } },
  { name: 'Indiana Jones : Les Aventuriers de l\'arche perdue', by: 'Steven Spielberg · 1981', tag: 'L\'aventure décontractée', color: '#8a6a2f',
    desc: 'Un archéologue improvise en permanence, se fait tabasser régulièrement, et s\'en sort par le culot plus que par le plan. Le film est un enchaînement de morceaux de bravoure d\'une efficacité imbattable.',
    t: { aud: 0.95, ouv: 0.85, ind: 0.85, vst: 0.9, san: 0.7, inf: 0.8, ord: 0.15, vhe: 0.8, thr: 0.3, vco: 0.2 } },
  { name: 'Braveheart', by: 'Mel Gibson · 1995', tag: 'La liberté criée', color: '#4f7942',
    desc: 'Un homme soulève un pays contre un empire et refuse tout compromis, jusqu\'au bout. Le film est ample, emphatique, et assume complètement son romantisme guerrier.',
    t: { lib: 0.98, ide: 0.95, com: 0.95, det: 0.95, dog: 0.9, eng: 0.95, att: 0.9, dip: 0.1, epi: 0.9, vse: 0.1 } },
  { name: 'Mommy', by: 'Xavier Dolan · 2014', tag: 'L\'amour qui ne suffit pas', color: '#e2569b',
    desc: 'Une mère et son fils s\'aiment violemment et se détruisent en essayant de vivre ensemble. Le film est exalté, bruyant, filmé dans un format carré qui s\'ouvre une fois — et ce moment-là suffit à tout dire.',
    t: { emp: 0.95, att: 0.98, com: 0.9, care: 0.9, san: 0.1, vis: 0.8, opt: 0.4, dip: 0.15, rig: 0.15, aff: 0.05 } },
  { name: 'Les Choristes', by: 'Christophe Barratier · 2004', tag: 'Faire avec ce qu\'on a', color: '#8a9a5b',
    desc: 'Un surveillant sans ambition monte une chorale dans un internat rude, et change discrètement quelques vies. Le film est modeste, pudique, et n\'invente aucun miracle : juste de la patience.',
    t: { care: 0.95, emp: 0.9, ste: 0.9, dip: 0.85, fia: 0.9, ide: 0.8, tmp: 0.8, vac: 0.2, com: 0.15, vpo: 0.05 } },
  { name: 'Bienvenue chez les Ch\'tis', by: 'Dany Boon · 2008', tag: 'Le préjugé qui fond', color: '#e0983a',
    desc: 'Un homme muté dans le Nord contre son gré découvre qu\'il s\'y sent mieux que chez lui. Le film est généreux, populaire au meilleur sens du terme, et tient entièrement sur la chaleur de ses personnages.',
    t: { soc: 0.95, col: 0.9, opt: 0.9, emp: 0.85, opn: 0.85, dip: 0.8, vhe: 0.85, care: 0.85, nat: 0.1, cmp: 0.1 } },
  { name: 'La Grande Vadrouille', by: 'Gérard Oury · 1966', tag: 'Le duo qui râle', color: '#c9a227',
    desc: 'Deux hommes que tout oppose traversent la France occupée en se disputant sans arrêt. Le film est une mécanique comique parfaite, et l\'amitié qui finit par s\'installer entre les deux n\'est jamais dite à voix haute.',
    t: { soc: 0.9, vhe: 0.9, com: 0.7, opt: 0.85, col: 0.8, aud: 0.75, inf: 0.85, ord: 0.2, epi: 0.15, dip: 0.5 } },
  { name: 'Nausicaä de la Vallée du Vent', by: 'Hayao Miyazaki · 1984', tag: 'Comprendre plutôt que détruire', color: '#5fa860',
    desc: 'Une jeune princesse refuse la guerre que tout le monde veut mener et va voir par elle-même ce que cache la forêt toxique. Le film est ample, écologiste avant l\'heure, et met la curiosité au-dessus de la peur.',
    t: { vun: 0.95, care: 0.95, ouv: 0.9, dip: 0.9, ide: 0.9, aud: 0.85, emp: 0.9, cfl: 0.1, com: 0.2, dog: 0.15 } },
  { name: 'Mon voisin Totoro', by: 'Hayao Miyazaki · 1988', tag: 'La douceur, simplement', color: '#8fbf6a',
    desc: 'Deux sœurs s\'installent à la campagne pendant que leur mère est à l\'hôpital, et rencontrent des créatures qui ne leur veulent que du bien. Il ne se passe presque rien, et c\'est exactement le sujet.',
    t: { ste: 0.95, emp: 0.9, care: 0.9, opt: 0.9, att: 0.9, san: 0.9, vhe: 0.8, com: 0.02, cmp: 0.02, vpo: 0.02 } },
  { name: 'Un jour sans fin', by: 'Harold Ramis · 1993', tag: 'Recommencer jusqu\'à devenir meilleur', color: '#6b8fa3',
    desc: 'Un présentateur méprisant revit la même journée jusqu\'à ce qu\'il cesse d\'en faire une farce. Le film est une comédie qui se transforme discrètement en traité moral, sans jamais faire la leçon.',
    t: { ouv: 0.9, chg: 0.6, emp: 0.85, det: 0.85, tmp: 0.8, care: 0.85, inf: 0.8, vhe: 0.7, dog: 0.2, cmp: 0.3 } },
  { name: 'Les Temps modernes', by: 'Charlie Chaplin · 1936', tag: 'Le petit contre la machine', color: '#7d7368',
    desc: 'Un ouvrier est broyé par une chaîne de production et s\'en échappe par la maladresse et la tendresse. Le film est muet à une époque où il n\'aurait plus dû l\'être, et c\'est encore la meilleure critique du travail à la chaîne.',
    t: { ide: 0.9, care: 0.9, vhe: 0.85, lib: 0.9, emp: 0.9, col: 0.8, auth: 0.1, vpo: 0.05, opt: 0.7, com: 0.5 } },
  { name: 'Le Fils de Saul', by: 'László Nemes · 2015', tag: 'Tenir à un seul geste', color: '#4a4a52',
    desc: 'Dans l\'horreur absolue, un homme s\'accroche à une seule chose : enterrer dignement un enfant. Le film reste collé à son visage, floute tout le reste, et refuse le spectacle.',
    t: { det: 0.98, ide: 0.9, sanc: 0.95, ind: 0.85, vis: 0.95, care: 0.9, san: 0.5, soc: 0.05, opt: 0.05, epi: 0.9 } },
  { name: 'Spider-Man: Into the Spider-Verse', by: 'Persichetti, Ramsey, Rothman · 2018', tag: 'N\'importe qui peut porter le masque', color: '#e2452f',
    desc: 'Un adolescent hésitant hérite d\'un rôle trop grand pour lui, entouré de versions ratées de lui-même. Le film est d\'une inventivité graphique folle et dit une chose simple : le saut de foi, personne ne peut le faire à ta place.',
    t: { ouv: 0.95, vst: 0.9, aud: 0.85, care: 0.9, soc: 0.85, emp: 0.85, opt: 0.85, ide: 0.85, vco: 0.2, dog: 0.1 } },
  { name: 'Drive', by: 'Nicolas Winding Refn · 2011', tag: 'Le silence et la violence', color: '#e2569b',
    desc: 'Un cascadeur qui conduit pour des braquages parle le moins possible et agit une fois pour toutes. Le film est néon, lent, presque muet, avec des explosions de brutalité qui arrivent sans prévenir.',
    t: { san: 0.95, ind: 0.95, det: 0.9, fia: 0.85, care: 0.8, soc: 0.02, inf: 0.05, com: 0.75, aff: 0.7, vhe: 0.2 } },
  { name: 'La La Land', by: 'Damien Chazelle · 2016', tag: 'Le rêve contre le couple', color: '#e05fa0',
    desc: 'Deux artistes s\'aiment et se poussent mutuellement vers leurs ambitions, ce qui finit par les éloigner. Le film est éclatant, musical, et se termine sur un « et si » d\'une justesse cruelle.',
    t: { ide: 0.9, vac: 0.9, att: 0.85, emp: 0.85, det: 0.85, vhe: 0.8, vis: 0.6, opt: 0.6, cmp: 0.6, vse: 0.2 } },
  { name: 'Snatch', by: 'Guy Ritchie · 2000', tag: 'Tout le monde arnaque tout le monde', color: '#8a8250',
    desc: 'Un diamant, un boxeur incompréhensible, et une dizaine de plans foireux qui s\'entrechoquent. Le film est rapide, verbeux, monté serré, et prend un plaisir évident à ce que rien ne se passe comme prévu.',
    t: { vst: 0.95, inf: 0.9, aud: 0.9, nat: 0.85, cmp: 0.85, ouv: 0.8, ord: 0.1, vco: 0.05, tmp: 0.1, vhe: 0.9 } },
  { name: 'Le Château ambulant', by: 'Hayao Miyazaki · 2004', tag: 'Accepter de changer de forme', color: '#3ec9c9',
    desc: 'Une jeune femme transformée en vieille dame découvre qu\'elle est plus libre ainsi, dans une maison qui marche. Le film est bancal, tendre, antimilitariste, et beaucoup plus sur l\'estime de soi que sur la magie.',
    t: { inc: 0.95, ouv: 0.9, chg: 0.8, care: 0.9, emp: 0.9, ste: 0.75, ide: 0.85, cfl: 0.1, vac: 0.3, vhe: 0.7 } },
  { name: 'Un prophète', by: 'Jacques Audiard · 2009', tag: 'Apprendre vite, en prison', color: '#5e5145',
    desc: 'Un jeune homme sans rien entre en prison et en ressort avec un réseau, une langue de plus et une place. Le film est sec, documentaire, et regarde une ascension sans jamais la célébrer.',
    t: { ouv: 0.9, det: 0.95, aff: 0.85, nat: 0.9, vig: 0.9, ind: 0.85, vac: 0.8, san: 0.8, vco: 0.15, opt: 0.3 } },
  { name: 'Les Visiteurs', by: 'Jean-Marie Poiré · 1993', tag: 'Le choc des époques', color: '#8a6f7a',
    desc: 'Un chevalier et son écuyer débarquent au vingtième siècle et n\'y comprennent rien, bruyamment. Le film tient par un décalage permanent et par des répliques passées dans la langue courante.',
    t: { vtr: 0.9, opn: 0.9, com: 0.85, soc: 0.8, auth: 0.85, vhe: 0.85, ouv: 0.15, inc: 0.15, dip: 0.2, chg: 0.05 } },
  { name: 'Le Prestige', by: 'Christopher Nolan · 2006', tag: 'L\'obsession de gagner', color: '#4a4159',
    desc: 'Deux magiciens se détruisent mutuellement pendant des années pour un tour que l\'autre ne peut pas percer. Le film est construit comme un tour de magie, avec sa promesse, son numéro et sa révélation.',
    t: { cmp: 0.98, vac: 0.95, det: 0.95, rig: 0.9, nat: 0.9, aff: 0.9, tmp: 0.8, emp: 0.15, dip: 0.1, vhe: 0.1 } },
];

window.PRISME_FILMS = { FILMS };
