/* ============================================================
   PRISME — « Si tu étais un film »
   ------------------------------------------------------------
   Même principe que les personnages et les animaux : chaque film
   est décrit par son tempérament, avec les dimensions du test.
   On ne juge pas le goût : on compare un caractère à un autre.
     name = titre, by = réalisation et année, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const FILMS = [
  { name: 'Le Parrain', by: 'Francis Ford Coppola · 1972', poster: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg', tag: 'La famille avant tout', color: '#7a2f2f',
    desc: 'Un homme qui voulait rester en dehors des affaires familiales y entre pour protéger les siens, et n\'en ressort jamais. Tout y est question de loyauté, de patience et de calcul froid, dans une lumière d\'ambre. Le film avance lentement, sûr de lui, sans jamais hausser le ton.',
    t: { att: 0.95, loy: 0.95, tmp: 0.9, san: 0.9, aff: 0.85, dom: 0.9, rig: 0.85, vtr: 0.9, vpo: 0.85, ouv: 0.15 } },
  { name: 'Pulp Fiction', by: 'Quentin Tarantino · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg', tag: 'Le désordre jubilatoire', color: '#d62828',
    desc: 'Trois histoires mélangées, des dialogues qui partent sur les hamburgers au milieu d\'une fusillade, et une structure qui se moque de l\'ordre chronologique. Le film est cool, bavard, imprévisible, et parfaitement conscient de son propre style.',
    t: { vst: 0.95, ouv: 0.9, inf: 0.9, ord: 0.05, vhe: 0.9, aud: 0.9, soc: 0.85, epi: 0.1, tmp: 0.15, san: 0.6 } },
  { name: 'Fight Club', by: 'David Fincher · 1999', poster: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg', tag: 'La colère contre soi-même',
    color: '#5a5a66',
    desc: 'Un homme qui s\'ennuie dans sa vie rangée invente une échappatoire qui devient un mouvement, puis un problème. Le film est nerveux, sarcastique, profondément méfiant envers tout ce qui ressemble à du confort. Il détruit avant de savoir ce qu\'il veut construire.',
    t: { chg: 0.95, com: 0.9, nat: 0.9, ind: 0.9, vis: 0.85, aud: 0.9, vco: 0.05, ste: 0.1, vac: 0.2, cfl: 0.9 } },
  { name: 'Matrix', by: 'Les Wachowski · 1999', poster: 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png', tag: 'Et si tout était faux ?', color: '#2f9e62',
    desc: 'Un informaticien découvre que le monde qu\'il habite est une simulation, et doit choisir entre le confort du mensonge et la dureté du réel. Le film pose une question philosophique dans un emballage d\'action, et croit très fort à la capacité d\'un individu à tout changer.',
    t: { ouv: 0.9, nat: 0.9, chg: 0.9, ide: 0.85, aff: 0.8, aud: 0.85, vsd: 0.9, inc: 0.8, vco: 0.1, opn: 0.1 } },
  { name: 'Interstellar', by: 'Christopher Nolan · 2014', poster: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg', tag: 'L\'amour à l\'échelle cosmique', color: '#1f7a8c',
    desc: 'Un père quitte ses enfants pour sauver l\'humanité, et passe le film à essayer de revenir. Ambitieux, cérébral, il déploie des équations et des trous noirs pour finir par dire quelque chose de très simple sur le lien entre deux personnes.',
    t: { tmp: 0.98, att: 0.95, aff: 0.85, ide: 0.85, det: 0.9, care: 0.9, aud: 0.85, vun: 0.8, vhe: 0.2, ste: 0.3 } },
  { name: 'Whiplash', by: 'Damien Chazelle · 2014', poster: 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg', tag: 'L\'excellence à n\'importe quel prix', color: '#c2850c',
    desc: 'Un batteur et un professeur qui le brise méthodiquement, dans une salle de répétition qui ressemble à une cage. Le film ne tranche jamais vraiment la question qu\'il pose : jusqu\'où peut-on aller pour être le meilleur ? Sec, tendu, épuisant.',
    t: { vac: 0.98, cmp: 0.95, det: 0.98, rig: 0.95, com: 0.9, ind: 0.85, emp: 0.1, vhe: 0.1, ste: 0.05, dip: 0.1 } },
  { name: 'Forrest Gump', by: 'Robert Zemeckis · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg', tag: 'La bonté qui traverse tout', color: '#57a639',
    desc: 'Un homme simple traverse trente ans d\'histoire américaine sans jamais changer de nature : il fait ce qu\'on lui dit, il court quand il faut courir, il aime la même personne toute sa vie. Le film est tendre, naïf par choix, et profondément confiant dans les gens.',
    t: { fia: 0.95, loy: 0.98, opt: 0.9, vbe: 0.9, ste: 0.9, emp: 0.85, nat: 0.05, aff: 0.15, vac: 0.2, att: 0.95 } },
  { name: 'Le Fabuleux Destin d\'Amélie Poulain', by: 'Jean-Pierre Jeunet · 2001', poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Amelie_poster.jpg', tag: 'La tendresse bricolée', color: '#57a639',
    desc: 'Une jeune femme timide décide d\'arranger discrètement la vie des autres, par petites interventions poétiques. Le film est coloré, minutieux, plein de détails inutiles et merveilleux — et il évite soigneusement de parler de ce qui fâche.',
    t: { emp: 0.9, care: 0.9, ide: 0.85, opt: 0.9, ouv: 0.8, soc: 0.4, vhe: 0.8, ind: 0.7, com: 0.05, dom: 0.1 } },
  { name: 'Intouchables', by: 'Nakache et Toledano · 2011', poster: 'https://upload.wikimedia.org/wikipedia/en/9/93/The_Intouchables.jpg', tag: 'L\'amitié qui décoince', color: '#e08700',
    desc: 'Deux hommes que tout sépare finissent par se faire un bien fou, essentiellement parce qu\'aucun des deux ne traite l\'autre avec précaution. Le film est chaleureux, drôle, et refuse obstinément le registre du pathos.',
    t: { soc: 0.95, opt: 0.9, vhe: 0.9, emp: 0.85, inf: 0.9, dip: 0.6, care: 0.85, vco: 0.15, thr: 0.15, cmp: 0.2 } },
  { name: 'La Haine', by: 'Mathieu Kassovitz · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/0/01/La_Haine_%281995_movie_poster%29.jpg', tag: 'La chute, jusqu\'ici tout va bien', color: '#3d3946',
    desc: 'Vingt-quatre heures dans une banlieue au lendemain d\'une bavure, avec trois amis qui n\'ont nulle part où aller. Le film est frontal, nerveux, en noir et blanc, et il ne propose aucune sortie — c\'est précisément son propos.',
    t: { com: 0.95, cfl: 0.95, vis: 0.95, nat: 0.9, eng: 0.85, col: 0.8, opt: 0.05, dip: 0.1, vse: 0.1, tmp: 0.1 } },
  { name: 'Les Évadés', by: 'Frank Darabont · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg', tag: 'L\'espoir, patiemment', color: '#8a6a2f',
    desc: 'Un homme condamné à tort creuse pendant vingt ans, un peu chaque nuit, sans jamais le dire à personne. Le film est calme, chaleureux, et croit que la dignité se maintient par de petites choses répétées longtemps.',
    t: { tmp: 0.98, det: 0.98, san: 0.9, ide: 0.9, fia: 0.9, opt: 0.8, rig: 0.85, ste: 0.8, com: 0.2, vst: 0.1 } },
  { name: 'Seven', by: 'David Fincher · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg', tag: 'La noirceur méthodique', color: '#46596b',
    desc: 'Deux inspecteurs face à un tueur qui suit un plan moral d\'une rigueur écœurante, dans une ville où il pleut sans arrêt. Le film est froid, sombre, extrêmement construit, et il ne laisse aucune porte ouverte.',
    t: { aff: 0.9, rig: 0.9, vis: 0.98, nat: 0.95, thr: 0.9, vig: 0.9, san: 0.75, opt: 0.02, vhe: 0.05, dog: 0.85 } },
  { name: 'Mad Max: Fury Road', by: 'George Miller · 2015', poster: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg', tag: 'La fuite en avant', color: '#e2452f',
    desc: 'Deux heures de poursuite dans le désert, presque sans dialogue, avec un sens du mouvement qui ne retombe jamais. Le film ne s\'explique pas : il fonce, et les personnages se définissent uniquement par ce qu\'ils font.',
    t: { aud: 0.98, rsk: 0.95, det: 0.95, com: 0.9, vst: 0.9, chg: 0.9, ste: 0.02, tmp: 0.15, aff: 0.15, dip: 0.1 } },
  { name: 'Into the Wild', by: 'Sean Penn · 2007', poster: 'https://upload.wikimedia.org/wikipedia/en/d/dc/Into_the_Wild_%282007_film_poster%29.png', tag: 'La liberté radicale', color: '#8a9a5b',
    desc: 'Un jeune diplômé brûle son argent et part vivre seul en Alaska, par refus total du monde qu\'on lui propose. Le film est lumineux, exalté, et finit par se demander si le bonheur compte vraiment quand il n\'est partagé avec personne.',
    t: { ind: 0.98, lib: 0.98, vsd: 0.95, aud: 0.9, ide: 0.9, chg: 0.85, col: 0.1, vco: 0.05, vse: 0.05, vac: 0.15 } },
  { name: 'Le Cercle des poètes disparus', by: 'Peter Weir · 1989', poster: 'https://upload.wikimedia.org/wikipedia/en/8/86/Dead_poets_society.png', tag: 'Penser par soi-même', color: '#7a6033',
    desc: 'Un professeur apprend à des élèves d\'un internat rigide à monter sur les tables et à lire autrement. Le film est chaleureux, romantique, et il n\'élude pas le prix que peut coûter une émancipation dans un milieu qui n\'en veut pas.',
    t: { ide: 0.95, ouv: 0.9, vsd: 0.9, emp: 0.85, care: 0.85, inf: 0.8, auth: 0.15, vco: 0.15, opn: 0.25, cfl: 0.3 } },
  { name: 'OSS 117 : Le Caire, nid d\'espions', by: 'Michel Hazanavicius · 2006', poster: 'https://upload.wikimedia.org/wikipedia/en/8/85/OSS_117%2C_Le_Caire_nid_d%27espions_poster.jpg', tag: 'L\'assurance absolue, sans fondement', color: '#d9a441',
    desc: 'Un agent secret d\'une bêtise magistrale traverse le film avec une confiance en lui que rien n\'entame. La mécanique comique repose entièrement sur l\'écart entre ce qu\'il croit être et ce qu\'il est. Léger, ciselé, increvable en soirée.',
    t: { vac: 0.9, dog: 0.95, inf: 0.9, soc: 0.85, vhe: 0.9, opt: 0.9, ouv: 0.05, emp: 0.1, rig: 0.2, thr: 0.05 } },
  { name: 'Astérix : Mission Cléopâtre', by: 'Alain Chabat · 2002', poster: 'https://upload.wikimedia.org/wikipedia/en/1/18/Mission_cleopatre_affiche.jpg', tag: 'La bonne humeur collective', color: '#e9a100',
    desc: 'Un chantier impossible, une équipe bancale, et une avalanche de répliques que tout le monde connaît par cœur. Le film tient par la générosité : chaque acteur a son moment, personne n\'écrase personne, et tout finit par un banquet.',
    t: { soc: 0.95, col: 0.9, vhe: 0.95, opt: 0.95, inf: 0.9, dip: 0.8, emp: 0.8, cmp: 0.15, com: 0.2, rig: 0.2 } },
  { name: 'Le Voyage de Chihiro', by: 'Hayao Miyazaki · 2001', poster: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png', tag: 'Le courage tranquille', color: '#3ec9c9',
    desc: 'Une enfant se retrouve seule dans un monde dont elle ne comprend pas les règles, et s\'en sort par le travail, la politesse et la fidélité à ce qu\'elle est. Le film est doux, étrange, sans véritable méchant, et il prend son temps.',
    t: { det: 0.9, fia: 0.9, care: 0.9, inc: 0.9, ouv: 0.85, emp: 0.9, ste: 0.8, com: 0.1, dom: 0.1, vpo: 0.05 } },
  { name: 'Princesse Mononoké', by: 'Hayao Miyazaki · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png', tag: 'Un conflit sans méchant', color: '#4f7942',
    desc: 'Une forêt contre une forge, et un héros qui refuse de choisir un camp parce qu\'il voit les raisons des deux. Le film est ample, violent, et se termine sans réconciliation facile : il faut vivre avec le désaccord.',
    t: { vun: 0.95, dip: 0.85, ide: 0.9, com: 0.7, ouv: 0.9, care: 0.9, epi: 0.4, dog: 0.15, opt: 0.5, tmp: 0.9 } },
  { name: 'Parasite', by: 'Bong Joon-ho · 2019', poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png', tag: 'L\'escalier social', color: '#5c7fa3',
    desc: 'Une famille pauvre s\'infiltre chez une famille riche, et la comédie bascule lentement vers autre chose. Le film est d\'une précision d\'orfèvre, drôle puis glaçant, et il n\'accorde de vraie innocence à personne.',
    t: { aff: 0.9, rig: 0.9, nat: 0.85, cmp: 0.85, vis: 0.85, aud: 0.8, ouv: 0.7, vco: 0.2, opt: 0.15, care: 0.5 } },
  { name: 'Your Name', by: 'Makoto Shinkai · 2016', poster: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png', tag: 'Le lien malgré la distance', color: '#e05fa0',
    desc: 'Deux adolescents échangent de corps sans se connaître, et finissent par se chercher à travers le temps. Le film est lumineux, sentimental sans honte, et parle surtout de ce qu\'on garde de quelqu\'un quand on ne se souvient plus de son nom.',
    t: { att: 0.95, emp: 0.9, ide: 0.9, care: 0.85, tmp: 0.8, opt: 0.8, aff: 0.2, com: 0.1, cmp: 0.1, vhe: 0.6 } },
  { name: 'Coco', by: 'Lee Unkrich · 2017', poster: 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg', tag: 'La mémoire des siens', color: '#e08700',
    desc: 'Un enfant veut faire de la musique dans une famille qui l\'interdit, et traverse le monde des morts pour comprendre pourquoi. Le film est chaleureux, coloré, et défend l\'idée qu\'on existe tant que quelqu\'un se souvient de nous.',
    t: { att: 0.95, vtr: 0.9, care: 0.9, emp: 0.9, col: 0.9, opt: 0.85, ide: 0.8, soc: 0.8, ind: 0.3, nat: 0.15 } },
  { name: 'Là-haut', by: 'Pete Docter · 2009', poster: 'https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg', tag: 'Partir quand même', color: '#4dc9ff',
    desc: 'Un vieil homme attache des milliers de ballons à sa maison pour tenir une promesse faite cinquante ans plus tôt. Le film commence par dix minutes de chagrin parfait, puis choisit l\'aventure — et l\'idée qu\'il n\'est jamais trop tard.',
    t: { att: 0.95, tmp: 0.85, det: 0.9, opn: 0.85, emp: 0.85, aud: 0.8, care: 0.85, vis: 0.6, com: 0.4, vst: 0.5 } },
  { name: 'Vice-Versa', by: 'Pete Docter · 2015', poster: 'https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg', tag: 'Faire de la place à la tristesse', color: '#9b5de5',
    desc: 'Les émotions d\'une enfant de onze ans sont des personnages, et le film explique très clairement pourquoi vouloir être joyeux en permanence ne marche pas. Intelligent, tendre, et étonnamment précis sur le fonctionnement intérieur.',
    t: { emp: 0.95, aff: 0.75, care: 0.9, ouv: 0.9, dip: 0.85, inc: 0.8, opt: 0.6, com: 0.1, cmp: 0.1, vun: 0.8 } },
  { name: 'Ratatouille', by: 'Brad Bird · 2007', poster: 'https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg', tag: 'Le talent là où on ne l\'attend pas', color: '#d62828',
    desc: 'Un rat veut cuisiner, ce qui est un problème évident, et il le fait quand même avec une exigence de chef. Le film défend une idée simple et ferme : ce n\'est pas l\'origine qui décide, c\'est ce qu\'on est capable de faire.',
    t: { ide: 0.9, det: 0.9, vac: 0.85, ouv: 0.9, rig: 0.9, fair: 0.9, aud: 0.85, vco: 0.2, opn: 0.2, cmp: 0.6 } },
  { name: 'Wall-E', by: 'Andrew Stanton · 2008', poster: 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg', tag: 'La persévérance silencieuse', color: '#c9a227',
    desc: 'Un robot range les déchets d\'une planète abandonnée depuis des siècles, seul, sans que personne lui ait dit d\'arrêter. Quarante minutes sans dialogue, une tendresse immense, et une critique sociale sous le vernis.',
    t: { fia: 0.95, det: 0.95, ste: 0.9, care: 0.9, att: 0.9, opt: 0.8, ord: 0.85, soc: 0.15, com: 0.1, vpo: 0.02 } },
  { name: 'Retour vers le futur', by: 'Robert Zemeckis · 1985', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg', tag: 'L\'énergie bricoleuse', color: '#e9a100',
    desc: 'Un adolescent et un inventeur excentrique font n\'importe quoi avec le temps et s\'en sortent de justesse à chaque fois. Le film est rapide, malin, optimiste, et construit comme une horlogerie où chaque détail sert plus tard.',
    t: { ouv: 0.9, aud: 0.9, opt: 0.9, vst: 0.9, inf: 0.85, rig: 0.8, soc: 0.8, thr: 0.25, ste: 0.15, epi: 0.1 } },
  { name: 'Rocky', by: 'John G. Avildsen · 1976', poster: 'https://upload.wikimedia.org/wikipedia/en/1/18/Rocky_poster.jpg', tag: 'Tenir debout à la fin', color: '#b5734a',
    desc: 'Un boxeur sans avenir obtient une chance absurde et ne cherche même pas à gagner : il veut seulement tenir jusqu\'au bout. Le film est modeste, tendre, beaucoup moins spectaculaire qu\'on ne s\'en souvient, et entièrement construit sur l\'effort.',
    t: { det: 0.98, eng: 0.9, opn: 0.9, att: 0.9, ide: 0.85, opt: 0.8, vac: 0.6, fia: 0.9, aff: 0.2, vpo: 0.15 } },
  { name: 'Gladiator', by: 'Ridley Scott · 2000', poster: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png', tag: 'La vengeance avec les honneurs', color: '#8b5e3c',
    desc: 'Un général trahi devient esclave, puis combattant, et remonte méthodiquement vers celui qui lui a tout pris. Le film est ample, solennel, obsédé par l\'honneur et par la dignité du devoir accompli.',
    t: { det: 0.95, loy: 0.9, att: 0.9, auth: 0.8, com: 0.85, fia: 0.9, san: 0.8, tmp: 0.8, vhe: 0.15, dip: 0.3 } },
  { name: 'Apocalypse Now', by: 'Francis Ford Coppola · 1979', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg', tag: 'La remontée du fleuve', color: '#4f5b3a',
    desc: 'Une mission simple devient une descente hallucinée où la guerre perd tout sens en même temps que ceux qui la font. Le film est lent, moite, magnifique et malade — il ne cherche ni à expliquer ni à conclure.',
    t: { vis: 0.98, nat: 0.9, inc: 0.85, aff: 0.6, ind: 0.85, epi: 0.7, opt: 0.02, ord: 0.1, dip: 0.1, tmp: 0.5 } },
  { name: 'Le Silence des agneaux', by: 'Jonathan Demme · 1991', poster: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg', tag: 'L\'analyse face à face', color: '#5b5468',
    desc: 'Une jeune recrue du FBI doit obtenir l\'aide d\'un homme qui lit en elle mieux qu\'elle-même. Le film tient presque entièrement sur des conversations, et sa tension vient de l\'intelligence, pas de l\'action.',
    t: { aff: 0.95, rig: 0.9, san: 0.85, vig: 0.9, det: 0.9, thr: 0.8, ind: 0.8, nat: 0.85, soc: 0.15, vhe: 0.05 } },
  { name: 'Shining', by: 'Stanley Kubrick · 1980', poster: 'https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg', tag: 'L\'enfermement', color: '#8a8f98',
    desc: 'Une famille garde un hôtel vide pendant l\'hiver, et l\'un d\'eux se désagrège lentement. Le film est d\'une symétrie glaçante, très lent, et son horreur vient surtout de couloirs trop grands et de silences trop longs.',
    t: { thr: 0.95, vis: 0.9, ord: 0.85, nat: 0.9, ind: 0.85, san: 0.4, com: 0.75, opt: 0.02, soc: 0.05, care: 0.15 } },
  { name: 'Alien', by: 'Ridley Scott · 1979', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg', tag: 'La peur méthodique', color: '#4a4159',
    desc: 'Un équipage de camionneurs de l\'espace découvre qu\'il n\'est pas seul à bord. Le film ne montre presque rien, avance très lentement, et fait de la survie une affaire de procédure et de sang-froid.',
    t: { thr: 0.98, vig: 0.95, san: 0.8, det: 0.9, rig: 0.85, col: 0.6, opt: 0.1, inf: 0.1, vhe: 0.05, nat: 0.85 } },
  { name: 'Terminator 2', by: 'James Cameron · 1991', poster: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png', tag: 'Apprendre à protéger', color: '#6b7280',
    desc: 'Une machine programmée pour tuer devient la seule figure fiable dans la vie d\'un gamin. Le film est un blockbuster parfaitement réglé qui parle, sans en avoir l\'air, de ce qu\'on transmet et de ce qu\'on peut réparer.',
    t: { fia: 0.95, care: 0.9, det: 0.95, ord: 0.85, tmp: 0.8, att: 0.85, aud: 0.85, chg: 0.7, vhe: 0.15, soc: 0.3 } },
  { name: 'Jurassic Park', by: 'Steven Spielberg · 1993', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg', tag: 'L\'émerveillement imprudent', color: '#57a639',
    desc: 'On peut le faire, donc on le fait — et la question de savoir si on aurait dû arrive un peu tard. Le film garde intacte sa capacité d\'émerveillement, et sa critique de la démesure technique n\'a pas vieilli.',
    t: { ouv: 0.9, vst: 0.9, aud: 0.85, opt: 0.7, thr: 0.7, care: 0.7, rig: 0.5, vis: 0.6, tmp: 0.35, dog: 0.3 } },
  { name: 'E.T. l\'extra-terrestre', by: 'Steven Spielberg · 1982', poster: 'https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg', tag: 'L\'amitié improbable', color: '#a97142',
    desc: 'Un enfant solitaire cache une créature dans sa chambre et fait tout pour la ramener chez elle. Le film est filmé à hauteur d\'enfant, tendre, et beaucoup plus triste qu\'on ne s\'en souvient.',
    t: { care: 0.95, emp: 0.95, att: 0.9, ide: 0.85, vbe: 0.9, opt: 0.75, aud: 0.7, nat: 0.3, com: 0.1, vpo: 0.02 } },
  { name: 'Les Affranchis', by: 'Martin Scorsese · 1990', poster: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg', tag: 'L\'ascension et la chute', color: '#7a4a2a',
    desc: 'Trente ans de vie criminelle racontés à toute vitesse, avec l\'euphorie d\'abord et la paranoïa ensuite. Le film est grisant, cynique, et montre très bien comment on s\'habitue à n\'importe quoi.',
    t: { vst: 0.9, vhe: 0.9, cmp: 0.85, nat: 0.85, loy: 0.7, aud: 0.9, vpo: 0.8, vco: 0.1, tmp: 0.15, rig: 0.3 } },
  { name: 'La Ligne verte', by: 'Frank Darabont · 1999', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg', tag: 'La compassion face à l\'injustice', color: '#5fa860',
    desc: 'Des gardiens de couloir de la mort découvrent que le condamné dont ils s\'occupent guérit les gens. Le film est long, lent, et déploie une immense douceur dans un endroit qui n\'en a pas.',
    t: { care: 0.98, emp: 0.95, fair: 0.9, ide: 0.9, fia: 0.9, ste: 0.85, tmp: 0.8, vis: 0.6, com: 0.2, cmp: 0.05 } },
  { name: '12 hommes en colère', by: 'Sidney Lumet · 1957', poster: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg', tag: 'Le doute raisonnable', color: '#6b8fa3',
    desc: 'Douze jurés dans une pièce surchauffée, et un seul qui demande qu\'on prenne le temps de discuter. Le film ne quitte jamais la salle et montre, argument après argument, comment une conviction collective se défait.',
    t: { aff: 0.9, fair: 0.98, rig: 0.9, dip: 0.8, ouv: 0.95, det: 0.9, ide: 0.85, dog: 0.1, com: 0.6, col: 0.75 } },
  { name: 'Le Discours d\'un roi', by: 'Tom Hooper · 2010', poster: 'https://upload.wikimedia.org/wikipedia/en/4/4a/The_King%27s_Speech_poster.jpg', tag: 'Surmonter, à voix haute', color: '#7a6a4a',
    desc: 'Un homme qui bégaie doit parler à une nation en guerre, et y arrive grâce à un professeur sans diplôme. Le film est sobre, pudique, et parle surtout d\'une amitié entre deux hommes que tout sépare.',
    t: { det: 0.9, fia: 0.9, dip: 0.85, thr: 0.8, emp: 0.85, auth: 0.7, vtr: 0.8, rig: 0.8, vhe: 0.2, aud: 0.4 } },
  { name: 'Joker', by: 'Todd Phillips · 2019', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg', tag: 'La bascule', color: '#6a3fa0',
    desc: 'Un homme méprisé par tout le monde finit par devenir le symbole qu\'il n\'avait pas cherché à être. Le film est malaisant, subjectif, et refuse de dire clairement ce qui est arrivé et ce qui a été imaginé.',
    t: { vis: 0.98, nat: 0.95, com: 0.85, ind: 0.85, chg: 0.9, cfl: 0.9, opt: 0.02, san: 0.1, dip: 0.05, care: 0.3 } },
  { name: 'Dune', by: 'Denis Villeneuve · 2021', poster: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg', tag: 'Le poids du destin', color: '#c9a227',
    desc: 'Un héritier est poussé vers un rôle prophétique qu\'il redoute, dans un monde où chaque alliance cache un calcul. Le film est lent, monumental, presque silencieux, et plus intéressé par le politique que par l\'action.',
    t: { tmp: 0.95, aff: 0.85, rig: 0.85, vpo: 0.75, nat: 0.85, vtr: 0.8, san: 0.8, thr: 0.8, vhe: 0.1, soc: 0.2 } },
  { name: 'Everything Everywhere All at Once', by: 'Daniels · 2022', poster: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg', tag: 'Le chaos, et l\'amour quand même', color: '#e05fa0',
    desc: 'Une gérante de laverie débordée traverse des milliers de versions d\'elle-même pour finir par réparer une relation avec sa fille. Le film part dans tous les sens à une vitesse folle, et atterrit sur quelque chose de très simple : la gentillesse.',
    t: { ouv: 0.98, vst: 0.95, chg: 0.9, emp: 0.9, care: 0.9, inc: 0.95, att: 0.9, ord: 0.05, epi: 0.15, dog: 0.05 } },
  { name: 'Le Loup de Wall Street', by: 'Martin Scorsese · 2013', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d8/The_Wolf_of_Wall_Street_%282013%29.png', tag: 'L\'excès sans frein', color: '#c2850c',
    desc: 'Trois heures d\'ascension, de fête et d\'arnaque, racontées par quelqu\'un qui n\'a jamais rien regretté. Le film est épuisant volontairement, très drôle, et laisse au spectateur le soin de juger.',
    t: { vpo: 0.95, vhe: 0.98, vac: 0.95, cmp: 0.9, aud: 0.95, inf: 0.9, vco: 0.02, fair: 0.05, ste: 0.05, tmp: 0.1 } },
  { name: 'Premier Contact', by: 'Denis Villeneuve · 2016', poster: 'https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg', tag: 'Comprendre avant de juger', color: '#6b8fa3',
    desc: 'Une linguiste doit apprendre à parler à des visiteurs pendant que le reste du monde prépare la guerre. Le film est calme, mélancolique, et défend l\'idée que la langue qu\'on emploie change ce qu\'on est capable de penser.',
    t: { aff: 0.9, ouv: 0.95, dip: 0.95, tmp: 0.95, emp: 0.9, san: 0.9, inc: 0.9, care: 0.85, com: 0.05, cfl: 0.05 } },
  { name: 'Gravity', by: 'Alfonso Cuarón · 2013', poster: 'https://upload.wikimedia.org/wikipedia/en/f/f6/Gravity_Poster.jpg', tag: 'La survie nue', color: '#8a8f98',
    desc: 'Une astronaute perdue dans le vide essaie simplement de rentrer, étape par étape, avec ce qu\'elle a sous la main. Le film est court, silencieux, et transforme chaque geste technique en question de vie ou de mort.',
    t: { det: 0.95, thr: 0.9, san: 0.75, ind: 0.9, rig: 0.85, vig: 0.9, vse: 0.85, soc: 0.05, com: 0.1, opt: 0.45 } },
  { name: 'Slumdog Millionaire', by: 'Danny Boyle · 2008', poster: 'https://upload.wikimedia.org/wikipedia/en/9/92/Slumdog_Millionaire_poster.png', tag: 'La vie comme réponse', color: '#e08700',
    desc: 'Un garçon des bidonvilles gagne à un jeu télévisé parce que chaque question correspond à un épisode de sa vie. Le film est rapide, coloré, dur par moments, et profondément romanesque.',
    t: { opt: 0.85, det: 0.9, att: 0.9, aud: 0.85, loc: 0.6, ide: 0.85, care: 0.85, vhe: 0.7, rig: 0.3, vpo: 0.2 } },
  { name: 'Titanic', by: 'James Cameron · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png', tag: 'Le romantisme total', color: '#1c86c9',
    desc: 'Une histoire d\'amour de quelques jours sur un bateau dont tout le monde connaît la fin. Le film assume entièrement son emphase, son ampleur et ses sentiments, sans aucune ironie — c\'est sa force.',
    t: { att: 0.95, ide: 0.9, emp: 0.9, aud: 0.85, vhe: 0.8, lib: 0.85, care: 0.85, vco: 0.15, aff: 0.15, cmp: 0.2 } },
  { name: 'Le Grand Bleu', by: 'Luc Besson · 1988', poster: 'https://upload.wikimedia.org/wikipedia/en/9/93/The_Big_Blue_poster.jpg', tag: 'L\'appel du silence', color: '#1f7a8c',
    desc: 'Deux apnéistes se poussent l\'un l\'autre toujours plus profond, jusqu\'à ce que la mer compte plus que la surface. Le film est contemplatif, un peu irréel, et parle d\'une vocation qui ne laisse pas de place au reste.',
    t: { ind: 0.9, vsd: 0.85, cmp: 0.8, san: 0.8, vis: 0.6, soc: 0.2, att: 0.5, tmp: 0.5, vco: 0.1, ide: 0.8 } },
  { name: 'Le Dîner de cons', by: 'Francis Veber · 1998', poster: 'https://upload.wikimedia.org/wikipedia/en/2/25/Le_d%C3%AEner_de_cons_%28Poster%29.jpg', tag: 'La mécanique cruelle', color: '#d9a441',
    desc: 'Un homme invite un naïf pour se moquer de lui et se retrouve pris dans une catastrophe en chaîne. Le film est une horlogerie comique impeccable, et le prétendu imbécile finit par être le seul personnage attachant.',
    t: { inf: 0.9, soc: 0.8, vhe: 0.85, care: 0.6, cmp: 0.7, rig: 0.7, aff: 0.55, nat: 0.6, dip: 0.3, vco: 0.4 } },
  { name: 'Inception', by: 'Christopher Nolan · 2010', poster: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg', tag: 'L\'architecture mentale', color: '#46596b',
    desc: 'Une équipe entre dans les rêves pour y déposer une idée, avec des règles précises et une horloge qui tourne. Le film est un puzzle méticuleux, froid, où l\'émotion reste enfermée derrière la mécanique.',
    t: { aff: 0.95, rig: 0.95, ord: 0.9, tmp: 0.85, det: 0.9, san: 0.85, thr: 0.8, vst: 0.7, soc: 0.2, vhe: 0.15 } },
  { name: 'Blade Runner 2049', by: 'Denis Villeneuve · 2017', poster: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png', tag: 'La mélancolie du faux', color: '#c2670c',
    desc: 'Un enquêteur cherche un enfant qui n\'aurait pas dû exister, et découvre surtout qu\'il n\'est pas celui qu\'il espérait être. Le film est d\'une lenteur assumée, somptueux, et parle de ce qui rend une vie vraie.',
    t: { vis: 0.9, tmp: 0.85, san: 0.9, ind: 0.9, aff: 0.8, ide: 0.7, emp: 0.75, soc: 0.1, opt: 0.15, com: 0.15 } },
  { name: 'Akira', by: 'Katsuhiro Ōtomo · 1988', poster: 'https://upload.wikimedia.org/wikipedia/en/5/5d/AKIRA_%281988_poster%29.jpg', tag: 'L\'énergie qu\'on ne contrôle plus', color: '#d62828',
    desc: 'Un adolescent reçoit un pouvoir immense et bascule en quelques jours, dans une ville au bord de l\'explosion. Le film est dense, brutal, politique, et son animation n\'a pas pris une ride.',
    t: { chg: 0.98, com: 0.95, cfl: 0.9, vis: 0.9, aud: 0.9, nat: 0.85, san: 0.1, dip: 0.05, ste: 0.05, vco: 0.1 } },
  { name: 'Old Boy', by: 'Park Chan-wook · 2003', poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Oldboykoreanposter.jpg', tag: 'La vengeance et son prix', color: '#7a2f2f',
    desc: 'Un homme enfermé quinze ans sans explication en sort pour comprendre pourquoi, et aurait mieux fait de ne pas savoir. Le film est d\'une violence stylisée et d\'une tristesse totale.',
    t: { det: 0.98, com: 0.9, nat: 0.95, ind: 0.9, vis: 0.95, cfl: 0.9, tmp: 0.6, san: 0.4, dip: 0.05, opt: 0.02 } },
  { name: 'Full Metal Jacket', by: 'Stanley Kubrick · 1987', poster: 'https://upload.wikimedia.org/wikipedia/en/9/99/Full_Metal_Jacket_poster.jpg', tag: 'La machine à fabriquer', color: '#4f5b3a',
    desc: 'Une première partie dans un camp d\'entraînement qui broie, une seconde dans une guerre qui n\'a plus de forme. Le film est froid, méthodique, et regarde le conditionnement comme un phénomène d\'ingénierie.',
    t: { auth: 0.9, ord: 0.9, rig: 0.9, com: 0.85, vis: 0.9, con: 0.85, emp: 0.1, care: 0.1, vhe: 0.1, dip: 0.05 } },
  { name: 'Le Roi Lion', by: 'Allers et Minkoff · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg', tag: 'Reprendre sa place', color: '#e9a100',
    desc: 'Un héritier fuit une faute qu\'il n\'a pas commise et doit revenir affronter ce qu\'il a laissé. Le film est ample, solennel, plein de chansons, et raconte une histoire de transmission vieille comme le théâtre.',
    t: { att: 0.9, vtr: 0.9, auth: 0.8, det: 0.8, care: 0.85, loc: 0.4, opt: 0.7, col: 0.8, vhe: 0.6, ouv: 0.4 } },
  { name: 'Toy Story', by: 'John Lasseter · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg', tag: 'La loyauté dans la boîte à jouets', color: '#2a75bb',
    desc: 'Deux jouets qui se détestent doivent s\'entraider pour rentrer, et finissent par ne plus pouvoir se passer l\'un de l\'autre. Le film est drôle, rythmé, et sérieux sur ce que signifie être remplacé.',
    t: { loy: 0.95, att: 0.9, col: 0.85, fia: 0.9, opt: 0.85, soc: 0.8, cmp: 0.5, care: 0.85, nat: 0.15, ind: 0.3 } },
  { name: 'Indiana Jones : Les Aventuriers de l\'arche perdue', by: 'Steven Spielberg · 1981', poster: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Raiders_of_the_Lost_Ark.jpg', tag: 'L\'aventure décontractée', color: '#8a6a2f',
    desc: 'Un archéologue improvise en permanence, se fait tabasser régulièrement, et s\'en sort par le culot plus que par le plan. Le film est un enchaînement de morceaux de bravoure d\'une efficacité imbattable.',
    t: { aud: 0.95, ouv: 0.85, ind: 0.85, vst: 0.9, san: 0.7, inf: 0.8, ord: 0.15, vhe: 0.8, thr: 0.3, vco: 0.2 } },
  { name: 'Braveheart', by: 'Mel Gibson · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Braveheart_film_poster.png', tag: 'La liberté criée', color: '#4f7942',
    desc: 'Un homme soulève un pays contre un empire et refuse tout compromis, jusqu\'au bout. Le film est ample, emphatique, et assume complètement son romantisme guerrier.',
    t: { lib: 0.98, ide: 0.95, com: 0.95, det: 0.95, dog: 0.9, eng: 0.95, att: 0.9, dip: 0.1, epi: 0.9, vse: 0.1 } },
  { name: 'Mommy', by: 'Xavier Dolan · 2014', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d5/Mommy-by-xavier-dolan-cannes-poster.jpg', tag: 'L\'amour qui ne suffit pas', color: '#e2569b',
    desc: 'Une mère et son fils s\'aiment violemment et se détruisent en essayant de vivre ensemble. Le film est exalté, bruyant, filmé dans un format carré qui s\'ouvre une fois — et ce moment-là suffit à tout dire.',
    t: { emp: 0.95, att: 0.98, com: 0.9, care: 0.9, san: 0.1, vis: 0.8, opt: 0.4, dip: 0.15, rig: 0.15, aff: 0.05 } },
  { name: 'Les Choristes', by: 'Christophe Barratier · 2004', poster: 'https://upload.wikimedia.org/wikipedia/en/9/9c/LesChoristes.jpeg', tag: 'Faire avec ce qu\'on a', color: '#8a9a5b',
    desc: 'Un surveillant sans ambition monte une chorale dans un internat rude, et change discrètement quelques vies. Le film est modeste, pudique, et n\'invente aucun miracle : juste de la patience.',
    t: { care: 0.95, emp: 0.9, ste: 0.9, dip: 0.85, fia: 0.9, ide: 0.8, tmp: 0.8, vac: 0.2, com: 0.15, vpo: 0.05 } },
  { name: 'Bienvenue chez les Ch\'tis', by: 'Dany Boon · 2008', poster: 'https://upload.wikimedia.org/wikipedia/en/5/55/Bienvenue_chez_les_CH%27TIS.png', tag: 'Le préjugé qui fond', color: '#e0983a',
    desc: 'Un homme muté dans le Nord contre son gré découvre qu\'il s\'y sent mieux que chez lui. Le film est généreux, populaire au meilleur sens du terme, et tient entièrement sur la chaleur de ses personnages.',
    t: { soc: 0.95, col: 0.9, opt: 0.9, emp: 0.85, opn: 0.85, dip: 0.8, vhe: 0.85, care: 0.85, nat: 0.1, cmp: 0.1 } },
  { name: 'La Grande Vadrouille', by: 'Gérard Oury · 1966', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e8/La_Grande_Vadrouille_poster.jpg', tag: 'Le duo qui râle', color: '#c9a227',
    desc: 'Deux hommes que tout oppose traversent la France occupée en se disputant sans arrêt. Le film est une mécanique comique parfaite, et l\'amitié qui finit par s\'installer entre les deux n\'est jamais dite à voix haute.',
    t: { soc: 0.9, vhe: 0.9, com: 0.7, opt: 0.85, col: 0.8, aud: 0.75, inf: 0.85, ord: 0.2, epi: 0.15, dip: 0.5 } },
  { name: 'Nausicaä de la Vallée du Vent', by: 'Hayao Miyazaki · 1984', poster: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Nausicaaposter.jpg', tag: 'Comprendre plutôt que détruire', color: '#5fa860',
    desc: 'Une jeune princesse refuse la guerre que tout le monde veut mener et va voir par elle-même ce que cache la forêt toxique. Le film est ample, écologiste avant l\'heure, et met la curiosité au-dessus de la peur.',
    t: { vun: 0.95, care: 0.95, ouv: 0.9, dip: 0.9, ide: 0.9, aud: 0.85, emp: 0.9, cfl: 0.1, com: 0.2, dog: 0.15 } },
  { name: 'Mon voisin Totoro', by: 'Hayao Miyazaki · 1988', poster: 'https://upload.wikimedia.org/wikipedia/en/0/02/My_Neighbor_Totoro_-_Tonari_no_Totoro_%28Movie_Poster%29.jpg', tag: 'La douceur, simplement', color: '#8fbf6a',
    desc: 'Deux sœurs s\'installent à la campagne pendant que leur mère est à l\'hôpital, et rencontrent des créatures qui ne leur veulent que du bien. Il ne se passe presque rien, et c\'est exactement le sujet.',
    t: { ste: 0.95, emp: 0.9, care: 0.9, opt: 0.9, att: 0.9, san: 0.9, vhe: 0.8, com: 0.02, cmp: 0.02, vpo: 0.02 } },
  { name: 'Un jour sans fin', by: 'Harold Ramis · 1993', poster: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Groundhog_Day_%28movie_poster%29.jpg', tag: 'Recommencer jusqu\'à devenir meilleur', color: '#6b8fa3',
    desc: 'Un présentateur méprisant revit la même journée jusqu\'à ce qu\'il cesse d\'en faire une farce. Le film est une comédie qui se transforme discrètement en traité moral, sans jamais faire la leçon.',
    t: { ouv: 0.9, chg: 0.6, emp: 0.85, det: 0.85, tmp: 0.8, care: 0.85, inf: 0.8, vhe: 0.7, dog: 0.2, cmp: 0.3 } },
  { name: 'Les Temps modernes', by: 'Charlie Chaplin · 1936', poster: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Modern_Times_poster.jpg', tag: 'Le petit contre la machine', color: '#7d7368',
    desc: 'Un ouvrier est broyé par une chaîne de production et s\'en échappe par la maladresse et la tendresse. Le film est muet à une époque où il n\'aurait plus dû l\'être, et c\'est encore la meilleure critique du travail à la chaîne.',
    t: { ide: 0.9, care: 0.9, vhe: 0.85, lib: 0.9, emp: 0.9, col: 0.8, auth: 0.1, vpo: 0.05, opt: 0.7, com: 0.5 } },
  { name: 'Le Fils de Saul', by: 'László Nemes · 2015', poster: 'https://upload.wikimedia.org/wikipedia/en/d/dd/Son_of_Saul_%28Saul_fia%29.png', tag: 'Tenir à un seul geste', color: '#4a4a52',
    desc: 'Dans l\'horreur absolue, un homme s\'accroche à une seule chose : enterrer dignement un enfant. Le film reste collé à son visage, floute tout le reste, et refuse le spectacle.',
    t: { det: 0.98, ide: 0.9, sanc: 0.95, ind: 0.85, vis: 0.95, care: 0.9, san: 0.5, soc: 0.05, opt: 0.05, epi: 0.9 } },
  { name: 'Spider-Man: Into the Spider-Verse', by: 'Persichetti, Ramsey, Rothman · 2018', poster: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png', tag: 'N\'importe qui peut porter le masque', color: '#e2452f',
    desc: 'Un adolescent hésitant hérite d\'un rôle trop grand pour lui, entouré de versions ratées de lui-même. Le film est d\'une inventivité graphique folle et dit une chose simple : le saut de foi, personne ne peut le faire à ta place.',
    t: { ouv: 0.95, vst: 0.9, aud: 0.85, care: 0.9, soc: 0.85, emp: 0.85, opt: 0.85, ide: 0.85, vco: 0.2, dog: 0.1 } },
  { name: 'Drive', by: 'Nicolas Winding Refn · 2011', poster: 'https://upload.wikimedia.org/wikipedia/en/1/13/Drive2011Poster.jpg', tag: 'Le silence et la violence', color: '#e2569b',
    desc: 'Un cascadeur qui conduit pour des braquages parle le moins possible et agit une fois pour toutes. Le film est néon, lent, presque muet, avec des explosions de brutalité qui arrivent sans prévenir.',
    t: { san: 0.95, ind: 0.95, det: 0.9, fia: 0.85, care: 0.8, soc: 0.02, inf: 0.05, com: 0.75, aff: 0.7, vhe: 0.2 } },
  { name: 'La La Land', by: 'Damien Chazelle · 2016', poster: 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png', tag: 'Le rêve contre le couple', color: '#e05fa0',
    desc: 'Deux artistes s\'aiment et se poussent mutuellement vers leurs ambitions, ce qui finit par les éloigner. Le film est éclatant, musical, et se termine sur un « et si » d\'une justesse cruelle.',
    t: { ide: 0.9, vac: 0.9, att: 0.85, emp: 0.85, det: 0.85, vhe: 0.8, vis: 0.6, opt: 0.6, cmp: 0.6, vse: 0.2 } },
  { name: 'Snatch', by: 'Guy Ritchie · 2000', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Snatch_ver4.jpg', tag: 'Tout le monde arnaque tout le monde', color: '#8a8250',
    desc: 'Un diamant, un boxeur incompréhensible, et une dizaine de plans foireux qui s\'entrechoquent. Le film est rapide, verbeux, monté serré, et prend un plaisir évident à ce que rien ne se passe comme prévu.',
    t: { vst: 0.95, inf: 0.9, aud: 0.9, nat: 0.85, cmp: 0.85, ouv: 0.8, ord: 0.1, vco: 0.05, tmp: 0.1, vhe: 0.9 } },
  { name: 'Le Château ambulant', by: 'Hayao Miyazaki · 2004', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Howls-moving-castleposter.jpg', tag: 'Accepter de changer de forme', color: '#3ec9c9',
    desc: 'Une jeune femme transformée en vieille dame découvre qu\'elle est plus libre ainsi, dans une maison qui marche. Le film est bancal, tendre, antimilitariste, et beaucoup plus sur l\'estime de soi que sur la magie.',
    t: { inc: 0.95, ouv: 0.9, chg: 0.8, care: 0.9, emp: 0.9, ste: 0.75, ide: 0.85, cfl: 0.1, vac: 0.3, vhe: 0.7 } },
  { name: 'Un prophète', by: 'Jacques Audiard · 2009', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d1/A_Prophet.jpg', tag: 'Apprendre vite, en prison', color: '#5e5145',
    desc: 'Un jeune homme sans rien entre en prison et en ressort avec un réseau, une langue de plus et une place. Le film est sec, documentaire, et regarde une ascension sans jamais la célébrer.',
    t: { ouv: 0.9, det: 0.95, aff: 0.85, nat: 0.9, vig: 0.9, ind: 0.85, vac: 0.8, san: 0.8, vco: 0.15, opt: 0.3 } },
  { name: 'Les Visiteurs', by: 'Jean-Marie Poiré · 1993', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c3/PosterVisituers.jpg', tag: 'Le choc des époques', color: '#8a6f7a',
    desc: 'Un chevalier et son écuyer débarquent au vingtième siècle et n\'y comprennent rien, bruyamment. Le film tient par un décalage permanent et par des répliques passées dans la langue courante.',
    t: { vtr: 0.9, opn: 0.9, com: 0.85, soc: 0.8, auth: 0.85, vhe: 0.85, ouv: 0.15, inc: 0.15, dip: 0.2, chg: 0.05 } },
  { name: 'Le Prestige', by: 'Christopher Nolan · 2006', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg', tag: 'L\'obsession de gagner', color: '#4a4159',
    desc: 'Deux magiciens se détruisent mutuellement pendant des années pour un tour que l\'autre ne peut pas percer. Le film est construit comme un tour de magie, avec sa promesse, son numéro et sa révélation.',
    t: { cmp: 0.98, vac: 0.95, det: 0.95, rig: 0.9, nat: 0.9, aff: 0.9, tmp: 0.8, emp: 0.15, dip: 0.1, vhe: 0.1 } },
  { name: 'Les Sept Samouraïs', by: 'Akira Kurosawa · 1954', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c8/Seven_Samurai_Poster.png', tag: 'Se battre pour des gens qui ne vous aiment pas', color: '#6b6250',
    desc: 'Sept hommes acceptent de défendre un village qui les méprise, pour trois bols de riz par jour. Le film prend son temps, installe chaque caractère, puis livre une bataille dans la boue où rien n\'est glorieux. La conclusion est amère : les vainqueurs, ce sont les paysans.',
    t: { care: 0.9, col: 0.9, fia: 0.9, det: 0.95, vpo: 0.15, tmp: 0.85, vac: 0.2, san: 0.8, loy: 0.9, vis: 0.6 } },

  { name: 'Le Bon, la Brute et le Truand', by: 'Sergio Leone · 1966', poster: 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg', tag: 'Trois cyniques et un trésor', color: '#b0854a',
    desc: 'Personne n\'est vraiment bon, tout le monde trahit, et le film prend un plaisir évident à faire durer chaque duel. La grandeur vient de la mise en scène plus que des personnages. C\'est de l\'opportunisme filmé comme une épopée.',
    t: { cmp: 0.95, vac: 0.9, ind: 0.9, epi: 0.05, nat: 0.9, aud: 0.9, vhe: 0.8, san: 0.8, care: 0.2, dip: 0.3 } },

  { name: '2001 : l\'Odyssée de l\'espace', by: 'Stanley Kubrick · 1968', poster: 'https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png', tag: 'Le silence et l\'immensité', color: '#5b6a7a',
    desc: 'Le film refuse d\'expliquer quoi que ce soit et laisse le spectateur devant des images qui dépassent le commentaire. Le rythme est lent au point d\'être une épreuve, et c\'est volontaire. Une œuvre pour ceux que l\'inconnu attire plutôt qu\'il n\'angoisse.',
    t: { ouv: 0.95, inc: 0.95, aff: 0.9, tmp: 0.95, rig: 0.95, soc: 0.05, epi: 0.6, san: 0.9, vst: 0.7, emp: 0.25 } },

  { name: 'Orange mécanique', by: 'Stanley Kubrick · 1971', poster: 'https://upload.wikimedia.org/wikipedia/en/7/73/A_Clockwork_Orange_%281971%29.png', tag: 'Le libre arbitre, même horrible',
    color: '#7d5ba6',
    desc: 'Un film violent qui pose une question désagréable : vaut-il mieux un homme mauvais qui choisit, ou un homme bon qu\'on a conditionné ? Rien n\'y est confortable, tout y est maîtrisé. Il dérange encore, et c\'est le but.',
    t: { lib: 0.95, ouv: 0.9, com: 0.9, aud: 0.95, sanc: 0.1, care: 0.2, chg: 0.9, cfl: 0.9, vco: 0.05, aff: 0.85 } },

  { name: 'Taxi Driver', by: 'Martin Scorsese · 1976', poster: 'https://upload.wikimedia.org/wikipedia/en/3/33/Taxi_Driver_%281976_film_poster%29.jpg', tag: 'La solitude qui tourne mal', color: '#8c4b3f',
    desc: 'Un homme seul dans une ville qu\'il méprise se persuade peu à peu qu\'il a une mission. Le film ne le juge pas et ne l\'excuse pas : il reste collé à lui. La fin, ironique, refuse de trancher.',
    t: { ind: 0.95, nat: 0.95, vis: 0.9, thr: 0.9, soc: 0.05, dog: 0.85, com: 0.85, san: 0.25, emp: 0.4, ide: 0.7 } },

  { name: 'La Liste de Schindler', by: 'Steven Spielberg · 1993', poster: 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg', tag: 'Un profiteur qui devient autre chose', color: '#5a5a5a',
    desc: 'Un homme d\'affaires opportuniste se surprend à sauver des gens, puis ne peut plus s\'arrêter. Le film est d\'une sobriété absolue et se termine sur un regret : il aurait pu en sauver plus. La transformation y est lente et sans discours.',
    t: { care: 0.95, chg: 0.85, ide: 0.85, det: 0.9, epi: 0.3, emp: 0.9, vbe: 0.9, vis: 0.75, fair: 0.9, vpo: 0.4 } },

  { name: 'Il faut sauver le soldat Ryan', by: 'Steven Spielberg · 1998', poster: 'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg', tag: 'Huit vies pour une',
    color: '#6f7263',
    desc: 'Une mission dont l\'absurdité arithmétique est discutée par ceux qui l\'exécutent, et exécutée quand même. Les vingt premières minutes sont un chaos sans héroïsme. Le film interroge la valeur qu\'on accorde à une seule personne.',
    t: { fia: 0.9, loy: 0.9, col: 0.85, care: 0.85, det: 0.95, ide: 0.7, vis: 0.7, epi: 0.7, san: 0.6, auth: 0.7 } },

  { name: 'La vie est belle', by: 'Roberto Benigni · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Vitaebella.jpg', tag: 'Protéger par le mensonge', color: '#d99b2a',
    desc: 'Un père transforme l\'horreur en jeu pour que son fils n\'en comprenne rien, et tient ce mensonge jusqu\'au bout. Le film est drôle et insoutenable dans le même mouvement. L\'optimisme y est un acte de volonté, pas une naïveté.',
    t: { opt: 0.95, care: 0.98, att: 0.95, emp: 0.9, inf: 0.9, ide: 0.9, soc: 0.85, det: 0.95, vbe: 0.95, vis: 0.4 } },

  { name: 'Le Pianiste', by: 'Roman Polanski · 2002', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg', tag: 'Survivre en se faisant tout petit',
    color: '#69707a',
    desc: 'Le personnage ne se bat pas, ne résiste pas : il se cache, et ça suffit à en faire un film. La survie y est faite d\'attente, de faim et de hasards. La musique revient à la toute fin comme une preuve d\'existence.',
    t: { san: 0.8, thr: 0.9, ind: 0.85, vis: 0.8, loc: 0.75, det: 0.9, soc: 0.1, emp: 0.8, vse: 0.85, aud: 0.25 } },

  { name: 'Django Unchained', by: 'Quentin Tarantino · 2012', poster: 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg', tag: 'La vengeance comme western',
    color: '#a83232',
    desc: 'Un homme libéré revient chercher sa femme et fait payer chaque humiliation avec un plaisir que le film ne cache pas. Bavard, drôle, violent, il assume totalement son point de vue. La justice y passe par le pistolet plutôt que par le tribunal.',
    t: { com: 0.95, det: 0.95, att: 0.9, cfl: 0.95, aud: 0.9, fair: 0.85, dip: 0.2, vhe: 0.8, eng: 0.9, ind: 0.9 } },

  { name: 'Inglourious Basterds', by: 'Quentin Tarantino · 2009', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Inglourious_Basterds_poster.jpg', tag: 'La tension dans une conversation',
    color: '#9a3b3b',
    desc: 'Les meilleures scènes sont des dialogues où personne ne bouge et où tout peut basculer sur un mot mal choisi. Le film réécrit l\'Histoire sans s\'excuser. Il repose entièrement sur la maîtrise de la parole.',
    t: { aff: 0.85, nat: 0.9, dip: 0.6, vig: 0.95, cmp: 0.9, aud: 0.9, com: 0.85, san: 0.8, rig: 0.85, chg: 0.9 } },

  { name: 'Kill Bill', by: 'Quentin Tarantino · 2003', poster: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Kill_Bill_Volume_1.png', tag: 'Une liste, et on la remonte', color: '#e0b400',
    desc: 'Une femme se réveille après des années et coche les noms un par un, sans jamais dévier. Le film mélange les genres avec une énergie folle mais la ligne reste droite. La détermination y est le seul moteur.',
    t: { det: 0.98, com: 0.95, att: 0.9, ind: 0.95, cmp: 0.9, vst: 0.9, aud: 0.95, dip: 0.05, san: 0.6, rig: 0.85 } },

  { name: 'Reservoir Dogs', by: 'Quentin Tarantino · 1992', poster: 'https://upload.wikimedia.org/wikipedia/en/0/01/Reservoir_Dogs.png', tag: 'Tout le monde se soupçonne',
    color: '#4a4a4a',
    desc: 'Un braquage raté dans un entrepôt, et une heure et demie à chercher qui a parlé. La méfiance monte jusqu\'à ce qu\'il ne reste plus personne. Huis clos, dialogues, et une brutalité sèche.',
    t: { nat: 0.98, cfl: 0.95, com: 0.9, thr: 0.95, loy: 0.6, san: 0.3, dip: 0.15, vis: 0.85, ind: 0.85, aff: 0.7 } },

  { name: 'Heat', by: 'Michael Mann · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg', tag: 'Deux professionnels qui se respectent',
    color: '#4f6275',
    desc: 'Un braqueur et un flic se ressemblent bien plus qu\'ils ne ressemblent à leurs proches, et le film le leur fait dire autour d\'un café. La rigueur du métier y remplace les liens. Chacun sait exactement ce que ça lui coûte.',
    t: { rig: 0.95, det: 0.95, ind: 0.9, aff: 0.9, cmp: 0.9, fia: 0.85, att: 0.3, san: 0.9, ord: 0.9, vac: 0.85 } },

  { name: 'Usual Suspects', by: 'Bryan Singer · 1995', poster: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg', tag: 'Celui qui raconte décide',
    color: '#5c5344',
    desc: 'Tout le film repose sur un récit fait dans un bureau de police, et la dernière minute retourne l\'ensemble. Il récompense ceux qui écoutent et punit ceux qui croient. La méfiance y est une leçon.',
    t: { nat: 0.95, aff: 0.9, inf: 0.85, ouv: 0.8, san: 0.85, vig: 0.9, dip: 0.7, fia: 0.1, cmp: 0.85, rig: 0.8 } },

  { name: 'Memento', by: 'Christopher Nolan · 2000', poster: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg', tag: 'À l\'envers, et on comprend pourquoi',
    color: '#6f6a63',
    desc: 'Le film avance en reculant parce que son personnage ne peut pas se souvenir, et le spectateur se retrouve aussi démuni que lui. C\'est un exercice de construction autant qu\'un récit. La question finale porte sur ce qu\'on choisit d\'oublier.',
    t: { aff: 0.9, rig: 0.9, ouv: 0.9, inc: 0.85, nat: 0.85, det: 0.9, tmp: 0.4, san: 0.6, thr: 0.85, ord: 0.8 } },

  { name: 'Bienvenue à Gattaca', by: 'Andrew Niccol · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/d/de/Gattaca_poster.jpg', tag: 'Tricher contre sa propre biologie',
    color: '#4e7a72',
    desc: 'Dans un monde où tout est décidé à la naissance, un homme s\'entraîne jusqu\'à l\'épuisement pour passer pour un autre. Le film est calme, froid, et profondément obstiné. Sa morale tient en une phrase : il ne gardait rien pour le retour.',
    t: { det: 0.98, ide: 0.9, vac: 0.9, ind: 0.9, rig: 0.9, chg: 0.85, fair: 0.9, aud: 0.85, san: 0.85, loc: 0.1 } },

  { name: 'Ex Machina', by: 'Alex Garland · 2015', poster: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Ex-machina-uk-poster.jpg', tag: 'Qui teste qui',
    color: '#5d7f8c',
    desc: 'Trois personnages dans une maison de verre, et un jeu de manipulation où le spectateur se trompe autant que le personnage principal. Le film est glacé, minimal, et d\'une intelligence méchante. Il ne console personne.',
    t: { aff: 0.95, nat: 0.9, ouv: 0.9, rig: 0.9, emp: 0.35, cmp: 0.9, san: 0.9, inc: 0.85, soc: 0.2, care: 0.3 } },

  { name: 'Her', by: 'Spike Jonze · 2013', poster: 'https://upload.wikimedia.org/wikipedia/en/4/44/Her2013Poster.jpg', tag: 'Aimer quelqu\'un qui n\'a pas de corps',
    color: '#d97a6c',
    desc: 'Un homme seul tombe amoureux d\'une voix, et le film le prend entièrement au sérieux. Doux, mélancolique, sans ironie. La fin ne condamne personne : elle constate simplement qu\'on ne grandit pas au même rythme.',
    t: { emp: 0.9, ouv: 0.9, att: 0.85, aff: 0.25, vis: 0.6, soc: 0.3, ide: 0.75, care: 0.85, san: 0.7, vbe: 0.85 } },

  { name: 'Eternal Sunshine of the Spotless Mind', by: 'Michel Gondry · 2004', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Eternal_Sunshine_of_the_Spotless_Mind.png', tag: 'Effacer quelqu\'un, et le regretter',
    color: '#7b93b8',
    desc: 'Deux personnes effacent leur histoire commune et la revivent à l\'envers pendant qu\'elle disparaît. Le film est bricolé, inventif, et terriblement juste sur ce que la mémoire garde. Il finit par dire oui malgré tout.',
    t: { emp: 0.9, ouv: 0.95, att: 0.9, inc: 0.85, vhe: 0.6, ide: 0.8, chg: 0.7, aff: 0.25, soc: 0.5, opt: 0.6 } },

  { name: 'Lost in Translation', by: 'Sofia Coppola · 2003', poster: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Lost_in_Translation_poster.jpg', tag: 'Deux insomnies qui se croisent',
    color: '#8e8fa8',
    desc: 'Presque rien ne se passe : deux personnes décalées se tiennent compagnie quelques jours dans un hôtel de Tokyo. Le film vit de silences et de regards. Ce qu\'ils se disent à la fin n\'est pas audible, et c\'est mieux ainsi.',
    t: { san: 0.9, emp: 0.85, soc: 0.3, tmp: 0.5, vis: 0.6, ouv: 0.85, att: 0.7, cfl: 0.05, ind: 0.8, vhe: 0.5 } },

  { name: 'Little Miss Sunshine', by: 'Dayton et Faris · 2006', poster: 'https://upload.wikimedia.org/wikipedia/en/1/16/Little_miss_sunshine_poster.jpg', tag: 'Une famille cabossée dans un van jaune',
    color: '#e8b530',
    desc: 'Chacun rate quelque chose d\'important et ils finissent quand même par danser ensemble sur une scène où ils n\'ont rien à faire. Le film se moque gentiment de la culture de la gagne. La solidarité y est bancale et totale.',
    t: { col: 0.9, att: 0.9, opt: 0.8, vac: 0.15, soc: 0.8, ouv: 0.85, vhe: 0.8, care: 0.9, cmp: 0.05, emp: 0.9 } },

  { name: 'Billy Elliot', by: 'Stephen Daldry · 2000', poster: 'https://upload.wikimedia.org/wikipedia/en/3/31/Billy_Elliot_movie.jpg', tag: 'Danser dans une ville en grève',
    color: '#c46a3f',
    desc: 'Un gamin de mineur veut faire de la danse classique, ce qui n\'arrange personne autour de lui. Le film montre la colère du père et sa capitulation sans jamais le caricaturer. L\'obstination finit par convaincre.',
    t: { det: 0.95, ide: 0.9, aud: 0.9, chg: 0.85, att: 0.85, vsd: 0.9, opt: 0.8, care: 0.85, cfl: 0.7, col: 0.8 } },

  { name: 'The Full Monty', by: 'Peter Cattaneo · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/e/ee/TheFullMonty.UKtheatricalposter.jpg', tag: 'Se mettre à nu faute de mieux',
    color: '#b2763c',
    desc: 'Des ouvriers au chômage montent un spectacle de strip-tease parce qu\'ils n\'ont plus rien d\'autre. Le film est drôle et jamais condescendant. La dignité y passe par le ridicule assumé.',
    t: { soc: 0.85, opt: 0.8, col: 0.9, vhe: 0.8, aud: 0.85, att: 0.8, vpo: 0.1, care: 0.8, epi: 0.15, com: 0.5 } },

  { name: 'Dirty Dancing', by: 'Emile Ardolino · 1987', poster: 'https://upload.wikimedia.org/wikipedia/en/0/00/Dirty_Dancing.jpg', tag: 'Un été qui change tout',
    color: '#d1566f',
    desc: 'Une jeune fille sage découvre un autre monde en apprenant à danser, et décide de ne plus se taire. Le film est franchement romanesque et assume chaque effet. Il finit par une réplique que tout le monde connaît.',
    t: { vst: 0.9, aud: 0.85, chg: 0.85, vhe: 0.85, ide: 0.8, soc: 0.85, opt: 0.85, care: 0.8, vco: 0.15, inf: 0.85 } },

  { name: 'Chantons sous la pluie', by: 'Kelly et Donen · 1952', poster: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Singin%27_in_the_Rain_%281952_poster%29.jpg', tag: 'La bonne humeur comme discipline',
    color: '#4fa0c4',
    desc: 'Une comédie sur le passage au cinéma parlant, portée par des numéros d\'une précision invraisemblable. Tout y paraît léger parce que tout y a été répété mille fois. L\'optimisme y est une esthétique.',
    t: { opt: 0.95, soc: 0.9, inf: 0.9, rig: 0.9, vhe: 0.9, det: 0.85, vst: 0.8, chg: 0.7, san: 0.7, vis: 0.1 } },

  { name: 'Cinema Paradiso', by: 'Giuseppe Tornatore · 1988', poster: 'https://upload.wikimedia.org/wikipedia/en/8/86/CinemaParadiso.jpg', tag: 'La nostalgie assumée',
    color: '#b8874a',
    desc: 'Un homme revient dans son village et se souvient du projectionniste qui lui a tout appris, y compris de partir. Le film est sentimental sans honte et magnifiquement fabriqué. La dernière scène est un cadeau posthume.',
    t: { att: 0.95, vtr: 0.9, emp: 0.9, opn: 0.85, tmp: 0.7, care: 0.9, vis: 0.5, soc: 0.75, ide: 0.8, vbe: 0.85 } },

  { name: 'Le Labyrinthe de Pan', by: 'Guillermo del Toro · 2006', poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Pan%27s_Labyrinth.jpg', tag: 'Un conte qui ne protège de rien',
    color: '#5e7a4a',
    desc: 'Une enfant invente un monde merveilleux pendant que la guerre civile se déroule à côté, et le film refuse de dire lequel est réel. La cruauté y côtoie la féerie sans transition. La désobéissance y est présentée comme une vertu.',
    t: { ide: 0.9, ouv: 0.9, lib: 0.9, care: 0.85, vis: 0.8, aud: 0.85, auth: 0.05, emp: 0.9, inc: 0.85, san: 0.55 } },

  { name: 'Portrait de la jeune fille en feu', by: 'Céline Sciamma · 2019', poster: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Portrait_of_a_Lady_on_Fire.jpg', tag: 'Regarder et être regardée',
    color: '#c46a4f',
    desc: 'Presque pas de musique, très peu d\'hommes, et une tension qui tient entièrement dans les regards. Le film prend son temps et fait confiance au spectateur. La dernière scène ne dure qu\'un plan et suffit.',
    t: { emp: 0.9, tmp: 0.9, san: 0.9, ouv: 0.9, att: 0.9, aff: 0.4, soc: 0.3, rig: 0.9, vhe: 0.6, ide: 0.85 } },

  { name: '120 battements par minute', by: 'Robin Campillo · 2017', poster: 'https://upload.wikimedia.org/wikipedia/en/a/af/120_battements_par_minute.png', tag: 'L\'urgence organisée',
    color: '#cf3b52',
    desc: 'Des militants débattent, s\'engueulent, votent, et vont mourir. Le film montre autant les réunions que les actions, et c\'est ce qui le rend juste. La colère y est collective et méthodique.',
    t: { eng: 0.98, col: 0.95, com: 0.9, ide: 0.95, care: 0.9, cfl: 0.85, chg: 0.9, fair: 0.95, tmp: 0.3, soc: 0.85 } },

  { name: 'Les Quatre Cents Coups', by: 'François Truffaut · 1959', poster: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Quatre_coups2.jpg', tag: 'L\'enfance qu\'on ne comprend pas',
    color: '#7a808c',
    desc: 'Un gamin fugue, ment, et personne autour de lui ne se demande pourquoi. Le film ne pleure jamais sur lui. Le dernier plan, face caméra, laisse la question ouverte.',
    t: { ind: 0.9, lib: 0.9, vis: 0.7, auth: 0.1, vsd: 0.9, att: 0.4, emp: 0.8, chg: 0.8, soc: 0.5, opt: 0.35 } },

  { name: 'À bout de souffle', by: 'Jean-Luc Godard · 1960', poster: 'https://upload.wikimedia.org/wikipedia/en/3/3f/%C3%80_bout_de_souffle_%28movie_poster%29.jpg', tag: 'Faire tout de travers, exprès',
    color: '#8a8a8a',
    desc: 'Montage cassé, caméra à l\'épaule, personnages qui parlent à la caméra : le film démolit les règles avec un plaisir évident. Son héros est insupportable et charmant. C\'est de la rupture pour la rupture, et ça a marché.',
    t: { chg: 0.95, ouv: 0.95, vsd: 0.95, aud: 0.9, ord: 0.05, vco: 0.05, ind: 0.9, vhe: 0.8, epi: 0.4, rsk: 0.9 } },

  { name: 'Le Samouraï', by: 'Jean-Pierre Melville · 1967', poster: 'https://upload.wikimedia.org/wikipedia/en/2/28/LeSamourai.jpg', tag: 'Le silence comme méthode',
    color: '#5f6b78',
    desc: 'Un tueur méticuleux, un imperméable, et presque aucune parole pendant près de deux heures. Tout est rituel, répétition et solitude choisie. Le film fait de la froideur un style.',
    t: { san: 0.98, rig: 0.98, ind: 0.95, ord: 0.95, soc: 0.02, aff: 0.9, emp: 0.2, vhe: 0.05, fia: 0.85, det: 0.9 } },

  { name: 'La Cité de la peur', by: 'Alain Berbérian · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/a/ac/La_Cit%C3%A9_de_la_peur.jpg', tag: 'L\'absurde à plein régime',
    color: '#e0a32a',
    desc: 'Un film qui enchaîne les vannes sans se soucier du récit et invente des répliques que la France entière cite encore. Rien n\'y est sérieux une seconde. Le non-sens y est travaillé avec une vraie rigueur.',
    t: { vhe: 0.95, inf: 0.95, soc: 0.9, ouv: 0.9, ord: 0.1, opt: 0.9, epi: 0.15, vco: 0.05, aud: 0.85, san: 0.4 } },

  { name: 'Les Tontons flingueurs', by: 'Georges Lautner · 1963', poster: 'https://upload.wikimedia.org/wikipedia/en/c/cd/Les-tontons-flingueurs.jpg', tag: 'Des truands qui parlent mieux qu\'ils ne tirent',
    color: '#9c7a45',
    desc: 'L\'intrigue est un prétexte : ce qui compte, ce sont les dialogues d\'Audiard et la scène de la cuisine. Les personnages sont des durs vieillissants avec un code d\'honneur désuet. On les regarde pour la manière, pas pour l\'histoire.',
    t: { soc: 0.9, vtr: 0.9, loy: 0.9, vhe: 0.85, inf: 0.9, opn: 0.85, com: 0.7, att: 0.85, epi: 0.3, san: 0.75 } },

  { name: 'Le Père Noël est une ordure', by: 'Jean-Marie Poiré · 1982', poster: 'https://upload.wikimedia.org/wikipedia/en/2/27/Le_p%C3%A8re_No%C3%ABl_est_une_ordure.jpg', tag: 'Le huis clos qui dégénère',
    color: '#c4483c',
    desc: 'Une permanence téléphonique un soir de Noël, et une succession de catastrophes qu\'aucun des personnages ne sait gérer. La méchanceté y est constante et hilarante. Rien ni personne n\'est épargné.',
    t: { com: 0.85, vhe: 0.9, cfl: 0.85, soc: 0.8, care: 0.25, ord: 0.1, dip: 0.15, inf: 0.9, vis: 0.7, epi: 0.2 } },

  { name: 'Qu\'est-ce qu\'on a fait au Bon Dieu ?', by: 'Philippe de Chauveron · 2014', poster: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Qu%27est-ce_qu%27on_a_fait_au_bon_dieu%3F_poster.jpg', tag: 'Les préjugés autour d\'une table',
    color: '#d08a3c',
    desc: 'Une famille bourgeoise découvre que ses quatre gendres ne correspondent à rien de ce qu\'elle espérait. Le film met tout le monde à égalité devant le ridicule. La réconciliation y passe par la moquerie partagée.',
    t: { soc: 0.9, vtr: 0.8, dip: 0.7, vhe: 0.85, opn: 0.8, ouv: 0.7, att: 0.85, cfl: 0.5, col: 0.8, opt: 0.85 } },

  { name: 'Le Prénom', by: 'de la Patellière et Delaporte · 2012', poster: 'https://upload.wikimedia.org/wikipedia/en/0/07/WhatsInANamePoster.png', tag: 'Un dîner qui déraille',
    color: '#a2554f',
    desc: 'Une blague sur un prénom fait exploser trente ans de non-dits entre amis. Tout se joue dans un salon, en temps réel, à coups de répliques. Le film montre combien la politesse tenait à peu de chose.',
    t: { com: 0.9, cfl: 0.9, soc: 0.85, inf: 0.85, aff: 0.7, att: 0.8, dip: 0.3, nat: 0.7, ouv: 0.7, vhe: 0.75 } },

  { name: 'Anatomie d\'une chute', by: 'Justine Triet · 2023', poster: 'https://upload.wikimedia.org/wikipedia/en/8/88/Anatomy_of_a_Fall_%282023%29_film_poster.jpg', tag: 'On ne saura jamais vraiment',
    color: '#6d7b8c',
    desc: 'Un procès où chaque version est plausible et où le film refuse jusqu\'au bout de donner la réponse. Ce qui est jugé, ce n\'est pas un crime mais un couple. Le spectateur est mis à la place du fils.',
    t: { aff: 0.9, inc: 0.95, ouv: 0.9, nat: 0.75, rig: 0.9, dog: 0.1, emp: 0.75, tmp: 0.7, san: 0.8, vis: 0.6 } },

  { name: 'Les Misérables', by: 'Ladj Ly · 2019', poster: 'https://upload.wikimedia.org/wikipedia/en/0/05/Les_Mis%C3%A9rables_2019_film_poster.jpg', tag: 'La cocotte-minute',
    color: '#8a6f4a',
    desc: 'Une journée dans une cité où chaque petite décision fait monter la pression d\'un cran. Le film ne désigne pas de coupable unique et finit sur une image suspendue. La tension y est la vraie protagoniste.',
    t: { cfl: 0.95, thr: 0.95, com: 0.85, vis: 0.85, nat: 0.9, eng: 0.85, care: 0.7, col: 0.8, san: 0.3, fair: 0.85 } },

  { name: 'Le Tombeau des lucioles', by: 'Isao Takahata · 1988', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg', tag: 'On sait dès la première minute',
    color: '#8c6a5a',
    desc: 'Le film annonce la fin d\'emblée et raconte quand même, ce qui rend chaque instant plus lourd. Un frère essaie de protéger sa petite sœur et n\'y arrive pas. C\'est l\'un des films les plus tristes jamais réalisés.',
    t: { att: 0.98, care: 0.95, vis: 0.95, emp: 0.95, ind: 0.8, opt: 0.05, det: 0.9, vpo: 0.05, col: 0.6, san: 0.4 } },

  { name: 'Le Vent se lève', by: 'Hayao Miyazaki · 2013', poster: 'https://upload.wikimedia.org/wikipedia/en/a/a3/Kaze_Tachinu_poster.jpg', tag: 'Faire de belles choses au mauvais moment',
    color: '#7f9ab0',
    desc: 'Un ingénieur rêve d\'avions magnifiques et les voit servir à la guerre, sans jamais renoncer à les dessiner. Le film ne l\'absout pas et ne le condamne pas. La beauté et la responsabilité y cohabitent mal.',
    t: { ide: 0.9, rig: 0.9, tmp: 0.85, aff: 0.75, vis: 0.7, ouv: 0.85, att: 0.85, det: 0.9, epi: 0.6, vac: 0.75 } },

  { name: 'Perfect Blue', by: 'Satoshi Kon · 1997', poster: 'https://upload.wikimedia.org/wikipedia/en/2/2a/Perfectblueposter.png', tag: 'Ne plus savoir qui on est',
    color: '#9b5b8a',
    desc: 'Une chanteuse change de métier et perd pied entre son image publique et elle-même. Le montage brouille volontairement le réel et le fantasme. Le film est anxiogène du début à la fin.',
    t: { thr: 0.95, nat: 0.9, inc: 0.8, vis: 0.85, aff: 0.6, ind: 0.7, san: 0.15, ouv: 0.8, emp: 0.7, chg: 0.8 } },

  { name: 'Shrek', by: 'Adamson et Jenson · 2001', poster: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Shrek_%282001_animated_feature_film%29.jpg', tag: 'L\'ogre qui refuse le conte',
    color: '#6fa83c',
    desc: 'Un film qui démonte les codes des contes de fées tout en en racontant un très classique. L\'humour est irrévérencieux, la morale sincère. Il tient debout parce qu\'il aime ce qu\'il moque.',
    t: { vhe: 0.9, ouv: 0.85, ind: 0.85, soc: 0.75, inf: 0.85, chg: 0.8, care: 0.85, vco: 0.15, opt: 0.85, com: 0.6 } },

  { name: 'Monstres et Cie', by: 'Pete Docter · 2001', poster: 'https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG', tag: 'Le rire vaut mieux que la peur',
    color: '#4fa8c8',
    desc: 'Deux employés découvrent que leur industrie entière repose sur une erreur de méthode. Le film est chaleureux, drôle, et se termine sur une porte qu\'on n\'ose pas ouvrir. L\'attachement y est le vrai sujet.',
    t: { soc: 0.9, care: 0.9, att: 0.9, opt: 0.9, vbe: 0.9, ouv: 0.85, chg: 0.8, vhe: 0.85, col: 0.85, thr: 0.25 } },

  { name: 'Le Monde de Nemo', by: 'Andrew Stanton · 2003', poster: 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg', tag: 'Un père qui doit lâcher',
    color: '#e88a2a',
    desc: 'Un poisson surprotecteur traverse un océan pour retrouver son fils et apprend en chemin à lui faire confiance. Le film est magnifique et très drôle. L\'anxiété y est traitée avec tendresse.',
    t: { care: 0.95, att: 0.95, thr: 0.9, det: 0.95, emp: 0.9, opt: 0.8, vse: 0.85, soc: 0.8, chg: 0.7, aud: 0.45 } },

  { name: 'Les Indestructibles', by: 'Brad Bird · 2004', poster: 'https://upload.wikimedia.org/wikipedia/en/2/27/The_Incredibles_%282004_animated_feature_film%29.jpg', tag: 'Ranger ses pouvoirs au placard',
    color: '#c43f3f',
    desc: 'Une famille de super-héros interdits d\'exercer s\'ennuie ferme dans une vie normale. Le film parle d\'excellence contrariée et de ce qu\'on fait de ses dons. L\'action y sert un propos très clair.',
    t: { vac: 0.9, det: 0.9, col: 0.85, att: 0.9, cmp: 0.85, ind: 0.8, aud: 0.9, chg: 0.75, lea: 0.85, vco: 0.2 } },

  { name: 'Zootopie', by: 'Howard et Moore · 2016', poster: 'https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg', tag: 'Les préjugés vus d\'en bas',
    color: '#4f9c8c',
    desc: 'Une lapine policière et un renard arnaqueur enquêtent dans une ville où chacun est assigné à son espèce. Le film est plus politique qu\'il n\'en a l\'air et ne donne pas de réponse facile. L\'obstination joyeuse y est le moteur.',
    t: { det: 0.95, opt: 0.9, fair: 0.9, ouv: 0.85, vun: 0.85, soc: 0.85, chg: 0.8, care: 0.85, dip: 0.7, vac: 0.8 } },

  { name: 'Le Géant de fer', by: 'Brad Bird · 1999', poster: 'https://upload.wikimedia.org/wikipedia/en/d/d3/The_Iron_Giant_poster.JPG', tag: 'On choisit ce qu\'on est',
    color: '#6b7f8c',
    desc: 'Une arme découvre l\'amitié et décide de ne pas être ce pour quoi elle a été construite. Le film est sobre, mélancolique, et vise juste sans effets. Sa phrase finale tient en trois mots.',
    t: { ide: 0.95, care: 0.9, vsd: 0.9, chg: 0.85, att: 0.9, emp: 0.9, vbe: 0.9, san: 0.8, auth: 0.2, vis: 0.4 } },

  { name: 'Casablanca', by: 'Michael Curtiz · 1942', poster: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg', tag: 'Le cynique qui craque',
    color: '#9a8a6a',
    desc: 'Un tenancier qui jure ne se mêler de rien finit par sacrifier ce qu\'il aime pour une cause. Les répliques sont devenues proverbiales. Le film est un modèle d\'efficacité romanesque.',
    t: { ide: 0.85, att: 0.9, dip: 0.8, san: 0.85, chg: 0.7, care: 0.85, vpo: 0.3, aff: 0.6, eng: 0.8, vhe: 0.6 } },

  { name: 'Psychose', by: 'Alfred Hitchcock · 1960', poster: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg', tag: 'Tuer son héroïne à la moitié',
    color: '#6b6b73',
    desc: 'Le film détruit ses propres règles au bout de quarante minutes et laisse le spectateur sans repère. La tension repose sur ce qu\'on ne voit pas. Il a redéfini ce qu\'un film pouvait se permettre.',
    t: { thr: 0.95, nat: 0.9, aud: 0.9, rig: 0.95, chg: 0.9, san: 0.5, vis: 0.85, ouv: 0.85, inc: 0.75, soc: 0.2 } },

  { name: 'Les Dents de la mer', by: 'Steven Spielberg · 1975', poster: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Jaws_movie_poster.jpg', tag: 'La peur de ce qu\'on ne voit pas',
    color: '#3f7a8c',
    desc: 'La machine ne marchait pas, alors le requin reste hors champ — et c\'est ce qui rend le film terrifiant. Trois hommes dans un bateau trop petit et une note de musique suffisent. La contrainte y est devenue la méthode.',
    t: { thr: 0.95, det: 0.9, col: 0.8, vig: 0.95, aud: 0.85, care: 0.8, san: 0.5, epi: 0.25, com: 0.6, inc: 0.7 } },

  { name: 'Léon', by: 'Luc Besson · 1994', poster: 'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg', tag: 'Le tueur et la gamine',
    color: '#7a6a4a',
    desc: 'Un homme qui ne sait rien faire d\'autre que son métier se retrouve responsable d\'une enfant. Le film mélange la violence et une tendresse maladroite. La plante verte est le meilleur personnage secondaire du cinéma.',
    t: { att: 0.95, care: 0.9, ind: 0.9, rig: 0.9, soc: 0.15, fia: 0.9, emp: 0.8, det: 0.95, san: 0.8, vhe: 0.3 } },

  { name: 'Trainspotting', by: 'Danny Boyle · 1996', poster: 'https://upload.wikimedia.org/wikipedia/en/7/71/Trainspotting_ver2.jpg', tag: 'Choisir la vie, ou pas',
    color: '#d9622a',
    desc: 'Un film sur l\'héroïne qui refuse de moraliser et avance à un rythme de clip. Drôle, sale, énergique, il finit par une trahison présentée comme une libération. Rien n\'y est confortable.',
    t: { vst: 0.95, vhe: 0.9, ind: 0.9, chg: 0.9, nat: 0.85, ord: 0.05, vco: 0.05, aud: 0.9, vis: 0.75, rsk: 0.95 } },
];

window.PRISME_FILMS = { FILMS };
