/* ============================================================
   PRISME — « Quelle spécialité de médecine serait la tienne ? »
   ------------------------------------------------------------
   On ne parle ni d'études, ni de concours, ni de notes : Prisme
   décrit le tempérament que chaque spécialité réclame — la tolérance
   à l'urgence, au sang, à l'incertitude, le rapport au patient, le
   goût du temps long ou du geste parfait. Aucune n'est « au-dessus ».
     name = la spécialité, by = le lieu ou le rythme de travail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const SPECIALTIES = [
  { name: 'La médecine générale', by: 'Cabinet de ville · au long cours', tag: 'Le médecin de toute la famille', color: '#4f7c5a',
    desc: 'Elle voit tout passer, du rhume à la dépression, et doit reconnaître en quinze minutes le cas grave caché parmi trente consultations banales. Elle suit les mêmes familles pendant des décennies et connaît les histoires que les dossiers ne disent pas. C\'est la médecine de la fidélité, du bon sens et de la relation qui dure.',
    t: { att: 0.95, vbe: 0.9, tmp: 0.9, fia: 0.95, emp: 0.85, soc: 0.8, ste: 0.85, vpo: 0.1, vst: 0.3, cmp: 0.15, opn: 0.75 } },
  { name: 'La médecine d\'urgence', by: 'Urgences · jour et nuit', tag: 'Tout, tout de suite, en même temps', color: '#c0392b',
    desc: 'Dix patients arrivent en même temps, personne ne ressemble à un manuel et il faut trier avant de comprendre. Le métier demande de décider vite avec peu d\'informations, puis de passer au suivant sans connaître la fin de l\'histoire. On s\'y épanouit si le chaos donne de l\'énergie plutôt que de l\'angoisse.',
    t: { san: 0.95, inc: 0.95, vst: 0.9, tmp: 0.08, ste: 0.15, rsk: 0.8, det: 0.9, ord: 0.3, col: 0.8, vse: 0.2 } },
  { name: 'Le SAMU et le SMUR', by: 'Régulation et véhicule d\'intervention · sur le terrain', tag: 'Soigner sur le bord de la route', color: '#e0533d',
    desc: 'Au centre 15, il faut juger au téléphone qui a besoin d\'une équipe ; dans le véhicule du SMUR, réanimer dans un salon, sur une autoroute ou sous la pluie. Aucun plateau technique, aucune porte à fermer : on improvise avec ce qu\'on a. Le poste attire ceux qui aiment l\'imprévu et l\'action plus que les couloirs.',
    t: { aud: 0.95, vst: 0.98, rsk: 0.92, dom: 0.8, ind: 0.8, con: 0.2, vse: 0.08, san: 0.9, chg: 0.7, inf: 0.7 } },
  { name: 'L\'anesthésie-réanimation', by: 'Bloc et réanimation · en veille permanente', tag: 'Celui qui veille pendant qu\'on dort', color: '#3a6ea5',
    desc: 'Pendant l\'opération, on ne voit que le chirurgien ; pourtant c\'est l\'anesthésiste qui tient la vie du patient, les yeux sur les moniteurs. En réanimation, il ajuste chaque organe défaillant heure par heure. Le métier exige un calme absolu, une vigilance qui ne s\'use pas et le goût de rester dans l\'ombre.',
    t: { vig: 0.98, san: 0.98, rig: 0.9, thr: 0.8, aff: 0.85, inf: 0.12, vpo: 0.2, soc: 0.3, con: 0.85, vac: 0.4 } },
  { name: 'La chirurgie cardiaque', by: 'Bloc opératoire · dix heures debout', tag: 'Arrêter un cœur pour le réparer', color: '#9b1b30',
    desc: 'On arrête le cœur, on branche la circulation extracorporelle, on répare une valve ou un pontage, puis on le fait repartir. Les journées sont longues, les enjeux maximaux et l\'erreur ne se rattrape pas. La spécialité attire des tempéraments ambitieux, endurants, qui aiment la difficulté et assument d\'être en première ligne.',
    t: { det: 0.98, vac: 0.95, vpo: 0.85, dom: 0.9, cmp: 0.9, aud: 0.85, vhe: 0.1, ste: 0.3, emp: 0.4, san: 0.9 } },
  { name: 'La neurochirurgie', by: 'Bloc · au microscope', tag: 'Au millimètre, dans le cerveau', color: '#5b3a8c',
    desc: 'Tumeurs, hématomes, moelle épinière : chaque geste se fait au microscope, dans une zone où un millimètre change une vie. Certaines interventions se déroulent patient éveillé, pour vérifier qu\'il parle encore. Il faut une précision obsessionnelle, un grand sang-froid et une vraie capacité à porter seul des décisions lourdes.',
    t: { rig: 0.98, con: 0.95, san: 0.95, aud: 0.85, vac: 0.9, ind: 0.85, soc: 0.2, inf: 0.2, vhe: 0.1, opt: 0.4 } },
  { name: 'La chirurgie orthopédique', by: 'Bloc et traumatologie · outils en main', tag: 'Le charpentier du squelette', color: '#8a6d3b',
    desc: 'Scies, vis, plaques et prothèses : c\'est la chirurgie la plus mécanique, où l\'on répare des fractures et remplace des hanches. Les résultats se voient, le patient remarche, et les problèmes ont souvent une solution concrète. On y trouve des tempéraments pratiques, directs, qui préfèrent l\'action aux longues théories.',
    t: { epi: 0.05, com: 0.85, dom: 0.8, vhe: 0.75, aff: 0.8, opt: 0.85, ide: 0.2, inc: 0.3, soc: 0.8, det: 0.85 } },
  { name: 'La chirurgie plastique et reconstructrice', by: 'Bloc · de la brûlure au visage', tag: 'Rendre une forme, rendre une vie', color: '#d4876b',
    desc: 'Greffes de peau chez les grands brûlés, reconstruction du sein après un cancer, main traumatisée, malformations de l\'enfant : l\'esthétique n\'en est qu\'une partie. Chaque cas demande d\'inventer une solution, avec un œil de sculpteur et une technique très fine. Elle convient aux créatifs exigeants qui voient le résultat avant de commencer.',
    t: { ide: 0.95, ouv: 0.9, rig: 0.9, aud: 0.8, vac: 0.85, vtr: 0.15, opn: 0.15, chg: 0.8, vse: 0.3, emp: 0.75 } },
  { name: 'La chirurgie viscérale', by: 'Bloc · urgences abdominales', tag: 'Le ventre, à toute heure', color: '#7c4a3a',
    desc: 'Appendicites, occlusions, cancers du côlon, du foie ou du pancréas : c\'est la chirurgie des gardes chargées et des nuits au bloc. Il faut de l\'endurance, des nerfs solides et la capacité d\'enchaîner une grosse intervention programmée et une urgence à trois heures du matin. Un métier d\'ouvrier infatigable autant que de technicien.',
    t: { det: 0.95, fia: 0.9, san: 0.9, loc: 0.08, vhe: 0.1, col: 0.75, vtr: 0.7, ord: 0.8, cfl: 0.7, ouv: 0.35, lea: 0.8 } },
  { name: 'La pédiatrie', by: 'Hôpital ou cabinet · enfants et parents', tag: 'Deux patients à chaque consultation', color: '#f2a93b',
    desc: 'Le patient ne sait pas dire où il a mal, et ses parents, eux, sont morts d\'inquiétude. Il faut examiner en jouant, rassurer sans mentir et repérer l\'enfant vraiment malade au milieu des fièvres banales. La pédiatrie réclame de la douceur, de l\'enthousiasme et une énergie qui ne se lasse pas des pleurs.',
    t: { care: 0.98, opt: 0.92, inf: 0.85, att: 0.9, vbe: 0.9, soc: 0.85, dom: 0.15, nat: 0.1, vis: 0.1, emp: 0.9 } },
  { name: 'La néonatologie', by: 'Soins intensifs · les tout-petits', tag: 'Veiller sur cinq cents grammes', color: '#e7b7c8',
    desc: 'Des prématurés qui tiennent dans une main, des couveuses, des alarmes et des parents suspendus au moindre chiffre. Chaque dose se calcule au milligramme près et chaque progrès prend des semaines. Il faut une patience immense, une douceur précise et la force d\'accompagner des familles dans l\'attente la plus longue de leur vie.',
    t: { ste: 0.95, vig: 0.9, care: 0.95, rig: 0.9, tmp: 0.85, inf: 0.2, cfl: 0.1, emp: 0.9, rsk: 0.1, vst: 0.25 } },
  { name: 'La gériatrie', by: 'Hôpital ou EHPAD · le grand âge', tag: 'Soigner une vie entière', color: '#8e7cc3',
    desc: 'Dix maladies à la fois, quinze médicaments qui interagissent, et une question qui dépasse la médecine : qu\'est-ce qui compte encore pour cette personne ? On y travaille lentement, avec les familles, sans victoire spectaculaire. Elle attire ceux qui respectent le grand âge et trouvent du sens loin de toute course à la performance.',
    t: { vtr: 0.85, ste: 0.9, emp: 0.9, att: 0.85, care: 0.9, vac: 0.08, vpo: 0.05, cmp: 0.05, vst: 0.2, dip: 0.85 } },
  { name: 'La psychiatrie', by: 'Hôpital ou cabinet · la parole', tag: 'Aucune radio ne montre la douleur', color: '#6c5b7b',
    desc: 'Il n\'y a ni prise de sang ni scanner pour poser le diagnostic : seulement l\'écoute, l\'observation et le temps. Le psychiatre accueille la souffrance la plus dérangeante sans juger et sans se laisser emporter. Le métier demande une curiosité profonde pour l\'humain, une vraie tolérance à l\'incertitude et une grande solidité intérieure.',
    t: { ouv: 0.95, inc: 0.95, emp: 0.9, dog: 0.05, ste: 0.85, auth: 0.2, san: 0.85, ide: 0.8, vse: 0.3, aff: 0.5 } },
  { name: 'La pédopsychiatrie', by: 'CMP et hôpital · enfants et familles', tag: 'Déchiffrer ce qu\'un enfant ne dit pas', color: '#9a86b8',
    desc: 'Autisme, troubles de l\'attention, angoisses, adolescents en crise : l\'enfant s\'exprime par le jeu, le dessin ou le comportement, et il faut travailler avec les parents, l\'école et les éducateurs. Les progrès se comptent en années. C\'est la spécialité des patients, des diplomates et des idéalistes tenaces.',
    t: { tmp: 0.95, dip: 0.9, ide: 0.85, care: 0.95, col: 0.8, dom: 0.1, cmp: 0.1, vpo: 0.1, ste: 0.85, vun: 0.8 } },
  { name: 'La cardiologie', by: 'Service et salle de cathétérisme · le cœur', tag: 'Chaque minute compte, et se mesure', color: '#b83b4a',
    desc: 'Un infarctus arrive, on débouche l\'artère à l\'aide d\'un cathéter et on pose un stent en moins d\'une heure. Le reste du temps, on suit des insuffisances cardiaques et des troubles du rythme selon des recommandations très codifiées. La spécialité convient aux esprits méthodiques et efficaces, qui aiment les décisions nettes appuyées sur des preuves.',
    t: { con: 0.9, vco: 0.8, auth: 0.75, vac: 0.85, rig: 0.9, inc: 0.2, epi: 0.2, det: 0.9, dom: 0.7, ide: 0.3 } },
  { name: 'La dermatologie', by: 'Cabinet · l\'œil sur la peau', tag: 'Tout se voit, encore faut-il regarder', color: '#e0a987',
    desc: 'Des milliers de maladies se lisent à la surface : eczéma, psoriasis, et surtout le mélanome qu\'il faut repérer parmi des centaines de grains de beauté. Le métier est très visuel, fait de mémoire des formes et de consultations nombreuses. Il convient à ceux qui cherchent un équilibre de vie solide et une médecine précise sans urgence permanente.',
    t: { vhe: 0.85, vse: 0.85, ord: 0.8, rsk: 0.15, vst: 0.25, thr: 0.2, cfl: 0.2, aff: 0.8, vig: 0.8, san: 0.8 } },
  { name: 'L\'ophtalmologie', by: 'Cabinet et bloc · au dixième de millimètre', tag: 'La précision comme seconde nature', color: '#2f8f9d',
    desc: 'Cataracte, glaucome, rétine : l\'opération de la cataracte est la plus pratiquée en France, et chacune se joue sur des structures de quelques millimètres. Tout est mesuré, instrumenté, reproductible. La spécialité attire les perfectionnistes calmes qui aiment le travail minutieux, les procédures maîtrisées et les résultats nets.',
    t: { con: 0.95, rig: 0.95, ord: 0.95, vse: 0.85, inc: 0.12, soc: 0.3, vac: 0.8, rsk: 0.2, inf: 0.2, ste: 0.8 } },
  { name: 'L\'ORL', by: 'Cabinet et bloc · oreilles, nez, gorge', tag: 'Médecin et chirurgien à la fois', color: '#4a8fb8',
    desc: 'Surdités, vertiges, sinusites, implants cochléaires, cancers de la gorge : l\'ORL consulte le matin et opère l\'après-midi, de l\'enfant au vieillard. La spécialité est touche-à-tout, dans une zone minuscule et dense. Elle séduit les indépendants polyvalents qui refusent de choisir entre la clinique et le geste.',
    t: { ind: 0.9, vsd: 0.9, ouv: 0.85, col: 0.25, vtr: 0.25, aff: 0.75, vhe: 0.65, vst: 0.75, loy: 0.3, rig: 0.8 } },
  { name: 'La radiologie', by: 'Salle d\'interprétation · devant les écrans', tag: 'Voir ce que les autres ne voient pas', color: '#5a6b7d',
    desc: 'Scanners, IRM, échographies : le radiologue lit des centaines d\'images par jour et repère le détail qui change tout. Il voit peu les patients mais oriente la plupart des diagnostics de l\'hôpital. Le poste convient aux esprits analytiques, concentrés et vigilants, que la solitude devant l\'écran ne dérange pas.',
    t: { aff: 0.95, vig: 0.92, soc: 0.1, inf: 0.1, att: 0.2, con: 0.9, san: 0.85, ind: 0.8, emp: 0.4, fia: 0.9 } },
  { name: 'La radiologie interventionnelle', by: 'Salle d\'angiographie · par l\'intérieur des vaisseaux', tag: 'Opérer sans ouvrir', color: '#1f7a8c',
    desc: 'Guidé par l\'image, on remonte un cathéter jusqu\'au cerveau pour retirer le caillot d\'un AVC, ou l\'on bouche une artère qui saigne, sans incision. La spécialité est jeune, technologique et invente ses gestes au fil des années. Elle attire les pionniers audacieux qui aiment les outils nouveaux et les frontières qui bougent.',
    t: { chg: 0.95, vst: 0.9, aud: 0.9, ouv: 0.85, vtr: 0.08, rsk: 0.85, vis: 0.1, aff: 0.85, vse: 0.2, san: 0.9 } },
  { name: 'L\'oncologie', by: 'Hôpital de jour · sur des années', tag: 'Tenir la main, tenir la ligne', color: '#7a5c8f',
    desc: 'Annoncer un cancer, construire un traitement, suivre le patient pendant des années avec ses rémissions et ses rechutes. La recherche avance vite, les décisions se prennent en équipe, et la mort fait partie du quotidien. Il faut conjuguer une grande humanité, une solidité émotionnelle réelle et la persévérance de ceux qui ne lâchent pas.',
    t: { san: 0.9, emp: 0.95, tmp: 0.9, det: 0.95, care: 0.95, vhe: 0.1, vis: 0.2, dip: 0.9, vst: 0.3, att: 0.85 } },
  { name: 'L\'hématologie', by: 'Service et laboratoire · le sang', tag: 'Des combats de longue haleine', color: '#a8323e',
    desc: 'Leucémies, lymphomes, greffes de moelle, chambres protégées pendant des semaines : c\'est une médecine lourde, qui lit ses résultats directement au microscope. Elle mêle la biologie la plus pointue et une relation très intense avec des patients longtemps hospitalisés. Elle convient aux scientifiques endurants qui ont le cœur solide.',
    t: { aff: 0.9, rig: 0.9, ouv: 0.85, tmp: 0.9, det: 0.9, inc: 0.75, vhe: 0.1, soc: 0.4, vtr: 0.2, san: 0.9 } },
  { name: 'La gynécologie-obstétrique', by: 'Salle de naissance et bloc · deux vies à la fois', tag: 'Décider vite, pour deux', color: '#c2527a',
    desc: 'Un accouchement bascule, et il faut décider d\'une césarienne en quelques minutes pour la mère et l\'enfant. Entre deux gardes, on suit des grossesses, des cancers, des parcours d\'infertilité. La spécialité demande de l\'autorité dans l\'urgence, un franc-parler assumé et un engagement réel pour la santé et les droits des femmes.',
    t: { dom: 0.85, com: 0.9, cfl: 0.8, san: 0.9, lib: 0.85, eng: 0.8, fair: 0.85, ste: 0.2, vtr: 0.2, rsk: 0.7 } },
  { name: 'La maïeutique (sage-femme)', by: 'Salle de naissance et cabinet · accompagner', tag: 'La confiance dans la naissance', color: '#e38aa6',
    desc: 'La sage-femme suit la grossesse, accompagne le travail et fait naître les enfants quand tout se passe normalement, soit la grande majorité des cas. Elle sait aussi reconnaître le moment où il faut appeler l\'obstétricien. Le métier demande une présence rassurante pendant des heures, beaucoup d\'écoute et le respect profond des choix de chaque femme.',
    t: { att: 0.95, ste: 0.9, emp: 0.95, care: 0.95, lib: 0.85, auth: 0.15, vpo: 0.05, dom: 0.25, vbe: 0.9, inf: 0.7 } },
  { name: 'La médecine légale', by: 'Institut médico-légal · la vérité des corps', tag: 'Parler pour ceux qui ne peuvent plus', color: '#3d3d4e',
    desc: 'Autopsies, mais surtout examens de victimes vivantes, de violences et d\'agressions, pour la justice. Le médecin légiste ne soigne pas : il établit des faits, rédige des rapports qui seront contestés et témoigne devant les tribunaux. Le métier réclame une froideur méthodique, un sens aigu de la justice et une méfiance professionnelle envers toutes les versions.',
    t: { fair: 0.95, aff: 0.95, san: 0.95, nat: 0.85, rig: 0.95, att: 0.1, vhe: 0.1, soc: 0.2, opt: 0.2, sanc: 0.15 } },
  { name: 'La médecine du sport', by: 'Bord de terrain · le corps en mouvement', tag: 'Remettre sur pied, et vite', color: '#2e9e5b',
    desc: 'Entorses, tendinites, commotions, bilans d\'effort : il faut remettre l\'athlète en état, souvent sous la pression d\'une échéance, sans compromettre sa santé à long terme. On travaille au bord des stades, avec les kinés et les entraîneurs. Le poste va aux énergiques, compétitifs et chaleureux, qui aiment l\'ambiance d\'une équipe.',
    t: { vst: 0.85, opt: 0.92, soc: 0.9, inf: 0.85, cmp: 0.8, vhe: 0.8, epi: 0.1, vis: 0.08, tmp: 0.3, vtr: 0.3 } },
  { name: 'L\'infectiologie', by: 'Service et avis transversaux · les microbes', tag: 'Garder une longueur d\'avance', color: '#6b8e23',
    desc: 'VIH, tuberculose, fièvres au retour de voyage, bactéries résistantes : l\'infectiologue est appelé dans tout l\'hôpital et surveille les épidémies à l\'échelle du monde. Chaque antibiotique prescrit engage l\'avenir collectif. La spécialité réunit la curiosité d\'enquêteur, la vigilance face aux menaces et une conscience très planétaire de la santé.',
    t: { ouv: 0.9, vig: 0.9, thr: 0.85, vun: 0.9, col: 0.85, opn: 0.08, inc: 0.8, aff: 0.8, vhe: 0.25, tmp: 0.85 } },
  { name: 'La santé publique et l\'épidémiologie', by: 'Agences et bureaux · la population entière', tag: 'Soigner des millions sans les voir', color: '#34699a',
    desc: 'Vaccination, dépistages, tabac, pollution, épidémies : on ne soigne personne en particulier mais on change des courbes pour tout un pays. Le travail se fait avec des chiffres, des études et des décisions politiques qui prennent des années. Il convient aux esprits systémiques, engagés pour le collectif, que l\'absence de patients ne gêne pas.',
    t: { col: 0.98, vun: 0.95, tmp: 0.95, eng: 0.85, epi: 0.8, aff: 0.9, att: 0.15, soc: 0.35, vst: 0.2, fair: 0.9 } },
  { name: 'La pneumologie', by: 'Service et consultation · le souffle', tag: 'L\'air, qu\'on ne remarque qu\'en le perdant', color: '#7fa7c9',
    desc: 'Asthme, bronchopneumopathie chronique, apnées du sommeil, cancer du poumon : le pneumologue suit des maladies longues, souvent liées au tabac, et passe beaucoup de temps à convaincre d\'arrêter. Il fait aussi des fibroscopies bronchiques et gère la réanimation respiratoire. Il faut de la constance, un franc-parler bienveillant et un sens pratique solide.',
    t: { fia: 0.9, com: 0.8, epi: 0.15, tmp: 0.8, care: 0.85, vpo: 0.15, vst: 0.3, ste: 0.8, nat: 0.35, ide: 0.3 } },
  { name: 'La gastro-entérologie', by: 'Endoscopie et consultation · le tube digestif', tag: 'Rien de ce qui est humain ne dégoûte', color: '#b5784e',
    desc: 'Coloscopies, maladies du foie, maladies inflammatoires de l\'intestin, cancers digestifs : c\'est une spécialité à la fois clinique et très technique, où l\'on enchaîne les endoscopies. On y parle sans détour de ce dont les patients ont honte. Elle convient aux bons vivants pragmatiques, à l\'aise avec le corps et dotés d\'humour.',
    t: { vhe: 0.85, sanc: 0.05, inf: 0.8, soc: 0.8, rig: 0.75, epi: 0.15, dog: 0.15, opt: 0.8, aud: 0.6, vtr: 0.4 } },
  { name: 'La néphrologie', by: 'Dialyse · une relation de dix ans', tag: 'La patience comme méthode', color: '#6a8caf',
    desc: 'Les reins ne font pas de bruit jusqu\'à ce qu\'ils lâchent ; ensuite, c\'est la dialyse trois fois par semaine, quatre heures chaque fois, ou la greffe. Le néphrologue règle des équilibres chimiques subtils et suit les mêmes patients pendant des années. La spécialité convient aux esprits calculateurs, constants et fidèles.',
    t: { tmp: 0.95, fia: 0.95, ord: 0.92, aff: 0.9, att: 0.8, vst: 0.08, rsk: 0.12, chg: 0.15, ste: 0.9, vhe: 0.3 } },
  { name: 'L\'endocrinologie', by: 'Consultation · les hormones et l\'équilibre', tag: 'Convaincre plutôt que prescrire', color: '#c9a227',
    desc: 'Diabète, thyroïde, obésité, surrénales : les traitements existent, mais tout dépend de ce que le patient fera chez lui. L\'endocrinologue passe donc sa vie à expliquer, négocier et encourager, sans jamais faire la morale. Elle attire les diplomates patients et logiques, qui préfèrent l\'influence douce au rapport de force.',
    t: { dip: 0.95, tmp: 0.9, ste: 0.85, aff: 0.8, dom: 0.15, cfl: 0.1, inf: 0.75, dog: 0.15, vse: 0.75, emp: 0.8 } },
  { name: 'La rhumatologie', by: 'Consultation · la douleur qui dure', tag: 'Prendre au sérieux ce qui ne se voit pas', color: '#a0785a',
    desc: 'Arthrose, polyarthrite, lombalgies chroniques, maladies auto-immunes : les patients souffrent souvent depuis longtemps et se sont sentis peu crus. La rhumatologue écoute, cherche, ajuste des traitements sur des années et accepte de soulager plutôt que de guérir. Elle convient aux enquêteurs bienveillants, sans esprit de compétition.',
    t: { emp: 0.9, care: 0.9, ouv: 0.8, cmp: 0.08, nat: 0.1, vst: 0.3, rsk: 0.2, loc: 0.3, tmp: 0.85, att: 0.8, vpo: 0.15 } },
  { name: 'La neurologie', by: 'Service et consultation · le cerveau', tag: 'Localiser la panne à partir d\'un symptôme', color: '#4b4f9c',
    desc: 'À partir d\'un tremblement, d\'une paralysie ou d\'un mot qui manque, le neurologue déduit l\'endroit exact de la lésion avant même l\'IRM. Parkinson, sclérose en plaques, épilepsie, AVC : beaucoup de maladies sont longues et certaines inexorables. La spécialité convient aux cerveaux analytiques et curieux, capables de lucidité face à ce qu\'on ne guérit pas.',
    t: { aff: 0.95, ouv: 0.9, rig: 0.9, ide: 0.8, inc: 0.8, soc: 0.3, inf: 0.2, vis: 0.65, opt: 0.35, vhe: 0.25 } },
  { name: 'L\'urologie', by: 'Bloc et consultation · sans tabou', tag: 'Le chirurgien des sujets gênants', color: '#3e8e7e',
    desc: 'Prostate, reins, vessie, calculs, fertilité masculine : l\'urologue opère beaucoup, souvent avec un robot chirurgical, et parle à ses patients de ce qu\'ils n\'osent dire à personne. La spécialité est technologique, rapide et plutôt décontractée. Elle attire les chirurgiens directs, à l\'aise en société, et à l\'affût des nouvelles techniques.',
    t: { chg: 0.85, sanc: 0.05, soc: 0.85, com: 0.85, vac: 0.85, aud: 0.75, dog: 0.1, vtr: 0.15, ste: 0.3, vpo: 0.65 } },
  { name: 'La médecine interne', by: 'Service de médecine · les cas que personne ne résout', tag: 'Le Sherlock Holmes de l\'hôpital', color: '#2c5f5d',
    desc: 'On lui envoie les patients que les autres spécialités n\'ont pas su expliquer : fièvre sans cause, maladie rare, symptômes qui ne collent avec rien. L\'interniste reprend tout depuis le début, sans se fier aux étiquettes déjà posées. Il faut une curiosité insatiable, une mémoire encyclopédique et le goût de contredire poliment les certitudes.',
    t: { ouv: 0.98, inc: 0.9, aff: 0.95, ide: 0.8, vsd: 0.85, com: 0.8, auth: 0.15, vco: 0.15, nat: 0.7, cfl: 0.65 } },
  { name: 'L\'anatomopathologie', by: 'Laboratoire · au microscope', tag: 'Le diagnostic final, sur une lame', color: '#8c5a8f',
    desc: 'Chaque tumeur retirée finit sur une lame, et c\'est le pathologiste qui dit ce qu\'elle est vraiment, parfois en pleine opération pendant que le chirurgien attend. Il ne voit presque jamais les patients, mais son compte rendu décide de leur traitement. Le métier convient aux observateurs silencieux, très minutieux, que le calme du laboratoire rend heureux.',
    t: { rig: 0.98, aff: 0.92, soc: 0.05, inf: 0.05, ste: 0.9, vst: 0.15, dom: 0.15, fia: 0.95, ind: 0.8, tmp: 0.8 } },
  { name: 'La biologie médicale', by: 'Laboratoire d\'analyses · derrière chaque résultat', tag: 'Des milliers de résultats justes par jour', color: '#5d8aa8',
    desc: 'Des milliers de tubes passent chaque jour dans des automates qu\'il faut valider, calibrer et contrôler selon des normes strictes. Le biologiste repère le résultat aberrant, appelle le médecin quand un chiffre est dangereux et dirige souvent son laboratoire. Le poste va aux esprits organisés et fiables, qui aiment les procédures bien tenues.',
    t: { ord: 0.95, con: 0.95, vse: 0.9, vco: 0.85, fia: 0.95, rsk: 0.05, aud: 0.1, chg: 0.2, lea: 0.65, inc: 0.15 } },
  { name: 'La génétique médicale', by: 'Consultation et laboratoire · l\'histoire des familles', tag: 'Lire l\'avenir dans l\'ADN', color: '#3f9b8f',
    desc: 'Maladies rares chez l\'enfant, cancers familiaux, test qui dira à quelqu\'un s\'il développera la maladie de son père : le généticien manie des informations qui engagent des familles entières. La discipline change à toute vitesse avec le séquençage. Elle attire les esprits pointus et curieux, tournés vers l\'avenir, attentifs aux dilemmes éthiques.',
    t: { ouv: 0.92, chg: 0.85, vis: 0.1, vtr: 0.15, fair: 0.85, aff: 0.9, ide: 0.85, tmp: 0.9, dip: 0.8, vhe: 0.2 } },
  { name: 'Les soins palliatifs', by: 'Unité de soins palliatifs · jusqu\'au bout', tag: 'Ajouter de la vie aux jours', color: '#9fb18a',
    desc: 'Quand on ne peut plus guérir, il reste à soulager la douleur, l\'angoisse, l\'essoufflement, et à accompagner les proches. On y parle de la mort sans détour et chaque journée compte pour elle-même. Le métier demande une présence tranquille, une écoute totale et un détachement complet de l\'ambition classique de victoire médicale.',
    t: { emp: 0.98, ste: 0.95, care: 0.98, tmp: 0.1, vac: 0.05, vpo: 0.05, cmp: 0.03, sanc: 0.75, dip: 0.9, vst: 0.15 } },
  { name: 'L\'addictologie', by: 'Consultation et centre de soins · sans jugement', tag: 'Partir d\'où la personne en est', color: '#b07aa1',
    desc: 'Alcool, opiacés, jeux, écrans : les rechutes font partie du chemin, et l\'addictologue ne demande pas l\'abstinence comme préalable. On réduit les risques, on négocie des petits pas et on garde le lien quoi qu\'il arrive. La spécialité convient aux esprits libres et tolérants, allergiques à la morale et optimistes par principe.',
    t: { dog: 0.05, auth: 0.08, vco: 0.1, lib: 0.9, inc: 0.9, opt: 0.85, emp: 0.9, sanc: 0.1, nat: 0.15, vun: 0.85 } },
  { name: 'La médecine du travail', by: 'Service de santé au travail · entre salariés et employeurs', tag: 'Ni pour l\'un, ni contre l\'autre', color: '#7a8b6f',
    desc: 'Visites, aménagements de poste, prévention des risques, épuisement professionnel : le médecin du travail conseille l\'entreprise et protège le salarié, deux loyautés qui s\'opposent parfois. Son indépendance est garantie par la loi, à lui de la faire respecter. Le poste va aux médiateurs fermes, attachés à l\'équité et à la prévention.',
    t: { dip: 0.95, fair: 0.95, com: 0.75, ind: 0.8, vse: 0.85, ord: 0.8, vst: 0.15, aud: 0.2, loy: 0.2, tmp: 0.85 } },
  { name: 'La médecine humanitaire', by: 'Terrains de crise · là où il n\'y a rien', tag: 'Soigner là où tout manque', color: '#d35d2a',
    desc: 'Camps de réfugiés, zones de guerre, épidémies : on soigne avec une valise de matériel, dans une langue qu\'on ne parle pas, en décidant qui passe en premier. Le confort est absent, le danger parfois réel. Cette médecine réclame un idéalisme solide, une grande capacité d\'adaptation et la volonté de s\'engager loin de toute sécurité.',
    t: { vun: 0.98, eng: 0.95, aud: 0.9, rsk: 0.9, vse: 0.05, vpo: 0.05, opn: 0.02, vst: 0.9, ide: 0.9, vhe: 0.1 } },
  { name: 'La médecine militaire', by: 'Service de santé des armées · en opération', tag: 'Médecin et soldat', color: '#556b2f',
    desc: 'Le médecin militaire suit la troupe, en caserne comme en opération extérieure, et pratique la médecine de guerre avec les moyens du front. Il obéit à une hiérarchie, partage la vie de son unité et doit rester lucide sous la menace. Le poste convient aux tempéraments loyaux, disciplinés, qui trouvent du sens dans le service et le collectif.',
    t: { loy: 0.95, auth: 0.92, vco: 0.85, col: 0.9, ord: 0.9, vtr: 0.85, lib: 0.15, san: 0.9, ind: 0.2, thr: 0.8, rsk: 0.7 } },
  { name: 'La chirurgie dentaire', by: 'Cabinet · la précision manuelle', tag: 'Chef d\'entreprise à la roulette', color: '#6aa9b8',
    desc: 'Caries, couronnes, implants, prothèses : le dentiste travaille de ses mains dans un espace de quelques centimètres, et gère souvent son propre cabinet avec ses assistantes, son matériel et ses investissements. Il faut rassurer des patients qui ont peur. La profession convient aux indépendants précis et entreprenants, qui aiment être leur propre patron.',
    t: { ind: 0.95, vsd: 0.92, rig: 0.9, ord: 0.85, vac: 0.8, vse: 0.8, col: 0.12, eng: 0.1, loc: 0.1, lea: 0.75 } },
  { name: 'L\'allergologie', by: 'Consultation · les ennemis invisibles', tag: 'Traquer ce qui déclenche tout', color: '#9ab973',
    desc: 'Pollens, arachide, venin de guêpe, médicaments : l\'allergologue enquête à partir des récits des patients, fait des tests cutanés et des tests de réintroduction sous surveillance, puis organise parfois une désensibilisation sur plusieurs années. Il faut de la méthode, de la prudence et un vrai goût du détail qui dénoue une énigme.',
    t: { vig: 0.95, thr: 0.8, rsk: 0.08, aff: 0.8, ouv: 0.75, ord: 0.85, vst: 0.25, dom: 0.2, nat: 0.7, fia: 0.85 } },
];

window.PRISME_SPECIALTIES = { SPECIALTIES };
