/* ============================================================
   PRISME — « Si tu étais un monument »
   ------------------------------------------------------------
   Même principe que les plats et les animaux : ce n'est pas le
   monument que tu préfères, c'est celui dont le tempérament
   ressemble au tien — sa façon de tenir, de se montrer ou de se
   cacher, de durer, d'étonner, de protéger ou de provoquer.
     name = le monument, by = lieu · époque, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const MONUMENTS = [
  { name: 'La tour Eiffel', by: 'Paris · 1889', tag: 'La provocation devenue emblème', color: '#7a5c45',
    desc: 'Des artistes célèbres ont signé contre elle avant même qu\'elle soit achevée, et elle ne devait rester debout que vingt ans. Elle a tenu en se rendant utile, puis en devenant indispensable. C\'est le tempérament de ceux qui dérangent d\'abord, ne s\'excusent pas, et finissent par être ce qu\'on montre en premier de la maison.',
    t: { aud: 0.92, chg: 0.9, inf: 0.85, rig: 0.85, vac: 0.85, cfl: 0.75, vtr: 0.15, vco: 0.15, opn: 0.2, vis: 0.1 } },
  { name: 'Le Mont-Saint-Michel', by: 'Normandie · VIIIe–XVIe siècle', tag: 'La forteresse qui prie', color: '#8a8f86',
    desc: 'Un rocher, une abbaye, une marée qui monte vite : il ne se laisse approcher qu\'à certaines heures. Pendant la guerre de Cent Ans, il n\'a jamais été pris. C\'est le tempérament de ceux qui ont une vie intérieure habitée et des défenses solides, qui s\'ouvrent aux visiteurs mais choisissent le moment.',
    t: { sanc: 0.95, vig: 0.9, thr: 0.8, ind: 0.85, det: 0.9, vtr: 0.9, opn: 0.85, soc: 0.2, vst: 0.2, chg: 0.1 } },
  { name: 'Le château de Versailles', by: 'Versailles · XVIIe siècle', tag: 'Le pouvoir mis en scène', color: '#c9a44a',
    desc: 'Tout y est organisé autour d\'un seul homme : le lever du roi, les jardins tirés au cordeau, la galerie des Glaces et ses trois cent cinquante-sept miroirs. Versailles ne se contente pas d\'être puissant, il veut qu\'on le voie. C\'est le tempérament de ceux qui aiment l\'ordre, la hiérarchie et le prestige, et qui ne font jamais les choses à moitié.',
    t: { vpo: 0.98, dom: 0.9, auth: 0.95, ord: 0.95, inf: 0.85, vac: 0.85, con: 0.8, emp: 0.2, fair: 0.2, vun: 0.15 } },
  { name: 'Notre-Dame de Paris', by: 'Paris · 1163–1345', tag: 'Bâtie par ceux qu\'on a oubliés', color: '#9c9486',
    desc: 'Près de deux siècles de chantier, des générations de tailleurs de pierre dont personne ne connaît le nom. Quand elle a brûlé en 2019, il a fallu cinq ans d\'efforts collectifs pour la rouvrir. C\'est le tempérament de ceux qui ne cherchent pas la signature, travaillent pour après eux et se relèvent sans bruit.',
    t: { tmp: 0.98, col: 0.9, fia: 0.9, det: 0.9, sanc: 0.85, ste: 0.9, vtr: 0.85, vac: 0.15, ind: 0.2, inf: 0.3 } },
  { name: 'L\'Arc de triomphe', by: 'Paris · 1806–1836', tag: 'La mémoire au garde-à-vous', color: '#b8ab8e',
    desc: 'Voulu par Napoléon pour célébrer ses armées, il abrite depuis 1921 la tombe du Soldat inconnu, et la flamme y est ravivée chaque soir. Il n\'oublie personne. C\'est le tempérament de ceux qui tiennent à la loyauté, aux rites et à la dette envers les anciens, et pour qui l\'hommage n\'est jamais une option.',
    t: { loy: 0.98, auth: 0.85, vtr: 0.92, fia: 0.9, tmp: 0.85, com: 0.7, vhe: 0.1, vst: 0.15, dip: 0.35, lib: 0.25 } },
  { name: 'Le Sacré-Cœur', by: 'Paris · 1875–1914', tag: 'Plus blanc après chaque pluie', color: '#e8e4da',
    desc: 'Perché sur la butte Montmartre, il domine Paris d\'une silhouette qu\'on reconnaît de partout. Sa pierre a une particularité : plus il pleut, plus elle blanchit. Longtemps discuté, il n\'a jamais changé ni d\'avis ni de place. C\'est le tempérament des convictions tranquilles et bien ancrées, que les intempéries ne salissent pas.',
    t: { sanc: 0.95, dog: 0.8, vtr: 0.9, vco: 0.85, ste: 0.85, opt: 0.8, chg: 0.1, vst: 0.15, lib: 0.25, inc: 0.2 } },
  { name: 'La pyramide du Louvre', by: 'Paris · 1989', tag: 'Le choc, en verre et en silence', color: '#8fb3c4',
    desc: 'On a crié au sacrilège : une pyramide de verre au milieu d\'un palais royal. Ieoh Ming Pei n\'a pas haussé le ton, il a fait ses calculs. Elle est devenue l\'entrée que tout le monde photographie. C\'est le tempérament des novateurs calmes, qui laissent la justesse du résultat répondre aux polémiques.',
    t: { chg: 0.88, rig: 0.9, san: 0.92, aff: 0.85, ide: 0.8, ste: 0.8, cfl: 0.15, dog: 0.15, vtr: 0.1, inf: 0.35 } },
  { name: 'Le Centre Pompidou', by: 'Paris · 1977', tag: 'Les tuyaux à l\'extérieur', color: '#2f6fb0',
    desc: 'Il a mis dehors ce que les autres cachent : l\'air en bleu, l\'eau en vert, l\'électricité en jaune, les circulations en rouge. Un musée qui ressemble à une usine et qui s\'en amuse. C\'est le tempérament de ceux qui détestent les façades, montrent comment ils fonctionnent et préfèrent un lieu vivant à un lieu impressionnant.',
    t: { chg: 0.92, lib: 0.9, vst: 0.85, ouv: 0.92, soc: 0.8, col: 0.75, vco: 0.1, auth: 0.12, vtr: 0.08, vpo: 0.2 } },
  { name: 'Le pont du Gard', by: 'Gard · Ier siècle', tag: 'Utile d\'abord, sublime ensuite', color: '#c7a978',
    desc: 'Il a été bâti pour une raison très terre à terre : amener l\'eau jusqu\'à Nîmes, sur un aqueduc qui ne descend en moyenne que de vingt-cinq centimètres par kilomètre. Ses grands blocs tiennent sans mortier depuis deux mille ans. C\'est le tempérament des gens fiables et précis, qui font leur travail parfaitement sans chercher à briller, et brillent quand même.',
    t: { fia: 0.98, rig: 0.95, aff: 0.85, tmp: 0.92, con: 0.85, san: 0.85, inf: 0.12, vpo: 0.15, vhe: 0.2, vst: 0.2 } },
  { name: 'La cité de Carcassonne', by: 'Aude · Moyen Âge, restaurée au XIXe', tag: 'Deux remparts valent mieux qu\'un', color: '#a08a6a',
    desc: 'Double enceinte, cinquante-deux tours, trois kilomètres de murailles : la Cité ne laisse rien au hasard. Restaurée par Viollet-le-Duc avec plus d\'imagination que de fidélité, elle ressemble à un château de légende. C\'est le tempérament des protecteurs méfiants et loyaux, qui gardent un peu de romanesque derrière leurs créneaux.',
    t: { vig: 0.95, vse: 0.95, thr: 0.9, nat: 0.85, loy: 0.88, opn: 0.8, ide: 0.7, rsk: 0.15, ouv: 0.25, soc: 0.35 } },
  { name: 'Le château de Chambord', by: 'Loir-et-Cher · 1519', tag: 'Un caprice royal en pierre', color: '#d6c9a8',
    desc: 'François Ier a fait bâtir un château immense, avec un escalier à double révolution où deux personnes peuvent monter sans jamais se croiser, et il n\'y a séjourné que quelques semaines en tout. Chambord existe pour le plaisir d\'exister. C\'est le tempérament des grands enthousiastes, qui voient trop grand, s\'en moquent et se lassent vite.',
    t: { vhe: 0.9, ide: 0.88, aud: 0.85, vst: 0.85, inf: 0.85, vpo: 0.75, fia: 0.2, tmp: 0.2, vse: 0.2, ord: 0.3 } },
  { name: 'Le viaduc de Millau', by: 'Aveyron · 2004', tag: 'Au-dessus des nuages, sans effort apparent', color: '#b9c3cc',
    desc: 'Une de ses piles mesure deux cent quarante-cinq mètres, son sommet dépasse la tour Eiffel, et par temps de brume il semble flotter. Rien ne dépasse, rien ne s\'agite : tout a été calculé au millimètre. C\'est le tempérament des perfectionnistes discrets, qui visent la performance absolue et la rendent légère.',
    t: { rig: 0.95, vac: 0.9, san: 0.95, aff: 0.9, cmp: 0.75, ord: 0.9, soc: 0.25, emp: 0.3, vtr: 0.12, vis: 0.1 } },
  { name: 'Les alignements de Carnac', by: 'Morbihan · Néolithique', tag: 'Trois mille pierres, zéro explication', color: '#8c8a7e',
    desc: 'Plus de trois mille menhirs dressés il y a plus de cinq mille ans, et personne ne sait vraiment pourquoi. Ils n\'ont jamais cherché à se justifier. C\'est le tempérament des gens silencieux et patients, qui ne s\'expliquent pas, s\'accommodent très bien du mystère et n\'ont aucun besoin d\'être compris pour tenir debout.',
    t: { inc: 0.95, ste: 0.95, ind: 0.85, tmp: 0.9, san: 0.85, inf: 0.05, soc: 0.2, vac: 0.08, dom: 0.1, vst: 0.2 } },
  { name: 'La grotte de Lascaux', by: 'Dordogne · Paléolithique', tag: 'Le chef-d\'œuvre dans le noir', color: '#a4582e',
    desc: 'Des taureaux, des chevaux et des cerfs peints il y a plus de dix-sept mille ans au fond d\'une grotte, là où personne ne passe. Découverte par quatre adolescents en 1940, elle a dû être refermée pour survivre. C\'est le tempérament des créatifs secrets, qui font leur plus bel ouvrage à l\'abri des regards et que trop d\'exposition abîme.',
    t: { ide: 0.98, ind: 0.85, ouv: 0.85, vsd: 0.85, emp: 0.75, thr: 0.65, soc: 0.1, inf: 0.08, vac: 0.1, vpo: 0.05 } },
  { name: 'Le phare de Cordouan', by: 'Gironde · 1611', tag: 'La veille, seul en mer', color: '#d8d2c2',
    desc: 'Planté sur un plateau rocheux à l\'entrée de la Gironde, il guide les navires depuis 1611 et abrite même une chapelle royale. Des gardiens s\'y sont relayés pendant des siècles, au rythme des marées. C\'est le tempérament de ceux qui protègent les autres de loin, sans compagnie ni applaudissements, et qui ne ferment jamais l\'œil tout à fait.',
    t: { vig: 0.95, fia: 0.95, care: 0.9, vbe: 0.85, san: 0.88, ind: 0.85, thr: 0.75, soc: 0.1, inf: 0.12, vpo: 0.1 } },
  { name: 'Le Moulin Rouge', by: 'Paris · 1889', tag: 'La fête n\'attend pas', color: '#c8202f',
    desc: 'Ouvert en 1889, l\'année de la tour Eiffel, au pied de Montmartre, il a rendu célèbre le french cancan et inspiré Toulouse-Lautrec. On y vient pour le spectacle, les plumes, le bruit et la nuit. C\'est le tempérament des bons vivants, qui aiment la foule, les paillettes et l\'instant présent, et laissent la morale au vestiaire.',
    t: { vhe: 0.98, soc: 0.95, inf: 0.92, vst: 0.9, tmp: 0.08, vco: 0.12, sanc: 0.1, ste: 0.2, rig: 0.35, cmp: 0.3 } },
  { name: 'Fort Boyard', by: 'Charente-Maritime · 1857', tag: 'Inutile, puis indispensable', color: '#8a7a5c',
    desc: 'Décidé sous Napoléon, achevé en 1857, il était déjà dépassé à son inauguration : les canons portaient désormais assez loin sans lui. Il a été prison, puis ruine, avant de devenir un jeu télévisé plein de clés et de tigres. C\'est le tempérament de ceux qui ratent leur première vocation et en trouvent une bien plus amusante.',
    t: { loc: 0.85, inc: 0.85, opt: 0.9, vst: 0.85, vhe: 0.8, aud: 0.75, ord: 0.2, rig: 0.25, tmp: 0.25, vse: 0.2 } },
  { name: 'Le château de Chenonceau', by: 'Indre-et-Loire · XVIe siècle', tag: 'Le pont plutôt que la muraille', color: '#c9c3b0',
    desc: 'Surnommé le château des Dames, il a été façonné par Diane de Poitiers puis par Catherine de Médicis, qui a posé une galerie de bal sur le pont enjambant le Cher. Pendant la guerre, cette galerie permettait de passer d\'une zone à l\'autre. C\'est le tempérament des diplomates raffinés, qui préfèrent relier les rives plutôt que défendre la leur.',
    t: { dip: 0.95, emp: 0.85, care: 0.8, att: 0.8, san: 0.85, ouv: 0.8, vbe: 0.85, cfl: 0.1, dom: 0.25, com: 0.2 } },
  { name: 'La Cité radieuse', by: 'Marseille · 1952', tag: 'Une utopie avec ascenseur', color: '#d98a3a',
    desc: 'Le Corbusier y a mis toute une ville : une rue commerçante au milieu de l\'immeuble, une école sur le toit, des appartements pensés pour une vie meilleure. Les Marseillais l\'ont surnommée la « maison du fada ». C\'est le tempérament des idéalistes à système, sûrs d\'avoir trouvé comment les autres devraient vivre.',
    t: { ide: 0.95, epi: 0.92, dog: 0.85, col: 0.88, ord: 0.9, chg: 0.9, fair: 0.8, vtr: 0.08, vhe: 0.3, inc: 0.2 } },
  { name: 'Le Palais idéal du facteur Cheval', by: 'Drôme · 1879–1912', tag: 'Trente-trois ans, une brouette', color: '#b58a5a',
    desc: 'Ferdinand Cheval, facteur dans la Drôme, a trébuché un jour sur une pierre étrange. Il a passé les trente-trois années suivantes à en ramasser d\'autres pendant ses tournées et à bâtir seul un palais qui ne ressemble à rien de connu. C\'est le tempérament des obstinés autodidactes, qui n\'attendent la permission de personne.',
    t: { det: 0.98, ide: 0.95, vsd: 0.95, ind: 0.95, tmp: 0.85, loc: 0.1, vco: 0.08, con: 0.2, soc: 0.2, vpo: 0.1 } },
  { name: 'Le Panthéon', by: 'Paris · 1790', tag: 'La reconnaissance au mérite', color: '#b3a58a',
    desc: 'Église devenue temple républicain en 1791, il accueille celles et ceux que la nation veut honorer, et le pendule de Foucault y a montré la rotation de la Terre. On n\'y entre ni par la naissance ni par la fortune. C\'est le tempérament de ceux qui croient au mérite, aux principes et à l\'exemple, et prennent les grandes causes au sérieux.',
    t: { fair: 0.92, vun: 0.85, eng: 0.85, epi: 0.8, loy: 0.8, aff: 0.8, vhe: 0.12, vst: 0.2, soc: 0.3, vpo: 0.25 } },
  { name: 'Les catacombes de Paris', by: 'Paris · fin du XVIIIe siècle', tag: 'Serein avec les ombres', color: '#5a534a',
    desc: 'À l\'entrée, une inscription prévient : « Arrête ! C\'est ici l\'empire de la Mort. » Dessous, les ossements de millions de Parisiens, rangés avec un soin presque décoratif. C\'est le tempérament de ceux que l\'obscurité n\'effraie pas, qui regardent en face ce que les autres évitent et gardent un humour un peu noir sur la condition humaine.',
    t: { san: 0.95, inc: 0.85, ind: 0.8, vis: 0.8, ord: 0.8, soc: 0.12, inf: 0.1, opt: 0.2, vhe: 0.2, thr: 0.3 } },
  { name: 'Le Lion de Belfort', by: 'Belfort · 1880', tag: 'Il n\'a pas reculé', color: '#a0463a',
    desc: 'Sculpté par Bartholdi dans le grès rouge, il rappelle les cent trois jours de siège que la ville a tenus en 1870-1871. Adossé à la falaise sous la citadelle, il a l\'air de défier quiconque approche. C\'est le tempérament des combatifs, qui ne cèdent pas un pouce, défendent les leurs jusqu\'au bout et ne cachent pas qu\'ils sont prêts à en découdre.',
    t: { com: 0.95, cfl: 0.95, det: 0.92, loy: 0.88, dom: 0.8, cmp: 0.8, rsk: 0.75, opn: 0.8, dip: 0.1, vhe: 0.15 } },
  { name: 'La tour Montparnasse', by: 'Paris · 1973', tag: 'Mal aimée, et alors ?', color: '#3d3f45',
    desc: 'Seul gratte-ciel au cœur de Paris, elle a déplu dès sa sortie de terre. Une plaisanterie tenace dit que sa vue est la plus belle de la ville, parce que c\'est le seul endroit d\'où on ne la voit pas. Elle encaisse sans broncher. C\'est le tempérament des solitaires carapacés, pragmatiques, indifférents à ce qu\'on pense d\'eux.',
    t: { ind: 0.92, san: 0.85, ste: 0.8, aff: 0.8, epi: 0.1, soc: 0.15, att: 0.15, emp: 0.3, inf: 0.2, vtr: 0.08 } },
  { name: 'Le Colisée', by: 'Rome · 80 apr. J.-C.', tag: 'Du pain et des jeux', color: '#b5835a',
    desc: 'Inauguré en l\'an 80 avec cent jours de jeux, il pouvait réunir environ cinquante mille spectateurs venus voir des gens se battre. Rien n\'y est tendre : c\'est une arène, pas un salon. C\'est le tempérament des compétiteurs nés, qui aiment la foule, le face-à-face et la victoire, et que le conflit stimule plus qu\'il ne les inquiète.',
    t: { cmp: 0.95, cfl: 0.95, com: 0.88, dom: 0.88, inf: 0.85, vst: 0.88, soc: 0.8, emp: 0.12, care: 0.12, ste: 0.2 } },
  { name: 'La tour de Pise', by: 'Pise · 1173–1372', tag: 'Le défaut devenu signature', color: '#e6dcc6',
    desc: 'Elle a commencé à pencher dès le troisième étage, et on a quand même continué à bâtir, en corrigeant un peu l\'angle, ce qui la rend légèrement courbe. Sans son défaut, personne ne la connaîtrait. C\'est le tempérament de ceux qui assument leurs travers avec bonne humeur et vivent très bien sans être parfaitement droits.',
    t: { opt: 0.9, inc: 0.88, ste: 0.8, inf: 0.8, san: 0.8, rig: 0.1, con: 0.1, ord: 0.2, vac: 0.25, dog: 0.1 } },
  { name: 'La fontaine de Trevi', by: 'Rome · 1762', tag: 'Une pièce pour revenir', color: '#5fa8b8',
    desc: 'On lui tourne le dos pour lui lancer une pièce par-dessus l\'épaule, promesse de revenir à Rome. Anita Ekberg s\'y est baignée dans La Dolce Vita. Tout y est théâtre, eau vive, marbre et sentiment. C\'est le tempérament des romantiques gourmands de beauté, qui vivent au présent et croient encore aux vœux.',
    t: { vhe: 0.95, att: 0.88, inf: 0.88, opt: 0.9, ide: 0.8, aff: 0.08, tmp: 0.15, vig: 0.15, rig: 0.3, vse: 0.3 } },
  { name: 'Le Parthénon', by: 'Athènes · Ve siècle av. J.-C.', tag: 'La mesure en toute chose', color: '#d9cfb8',
    desc: 'Ses colonnes ne sont pas tout à fait droites et ses lignes pas tout à fait horizontales : chaque courbe corrige une illusion d\'optique pour que l\'ensemble paraisse parfait. Bâti dans l\'Athènes de Périclès, il célèbre la raison et la cité. C\'est le tempérament des esprits réfléchis, qui cherchent l\'harmonie par le calcul et l\'équilibre par le débat.',
    t: { aff: 0.92, rig: 0.9, ouv: 0.85, fair: 0.85, dip: 0.8, vun: 0.8, epi: 0.75, rsk: 0.3, vhe: 0.25, dog: 0.2 } },
  { name: 'Les pyramides de Gizeh', by: 'Égypte · vers 2560 av. J.-C.', tag: 'Bâtir pour l\'éternité', color: '#d4b27a',
    desc: 'Pendant près de quatre mille ans, la pyramide de Khéops a été la plus haute construction humaine. Elle exigeait des milliers d\'ouvriers, une administration minutieuse et un seul but : rendre un roi immortel. C\'est le tempérament de ceux qui pensent en siècles, organisent tout et ne doutent pas une seconde de leur place au sommet.',
    t: { tmp: 0.99, ord: 0.95, vpo: 0.9, auth: 0.9, dom: 0.85, con: 0.85, sanc: 0.8, chg: 0.05, vhe: 0.1, vst: 0.1 } },
  { name: 'Le Sphinx de Gizeh', by: 'Égypte · vers 2500 av. J.-C.', tag: 'Le gardien qui ne dit rien', color: '#c9a36b',
    desc: 'Corps de lion, tête humaine, regard tourné vers le soleil levant : il garde le plateau de Gizeh depuis quatre millénaires et demi. Il a passé des siècles ensablé jusqu\'au cou sans rien perdre de sa contenance. C\'est le tempérament des observateurs impassibles, qui en savent plus qu\'ils n\'en disent et ne se laissent pas lire.',
    t: { san: 0.95, ste: 0.92, vig: 0.88, nat: 0.85, aff: 0.8, ind: 0.8, soc: 0.1, inf: 0.08, emp: 0.3, cfl: 0.25 } },
  { name: 'Pétra', by: 'Jordanie · Ier siècle av. J.-C.', tag: 'Le trésor derrière la faille', color: '#c9765a',
    desc: 'Pour l\'atteindre, il faut suivre une gorge étroite sur plus d\'un kilomètre, puis la façade surgit, taillée dans le grès rose. Les Nabatéens y ont bâti une riche capitale marchande, que l\'Europe a oubliée jusqu\'en 1812. C\'est le tempérament de ceux qui se méritent, gardent leurs richesses à l\'abri et réservent leur éclat à ceux qui font le chemin.',
    t: { nat: 0.88, vig: 0.85, ind: 0.88, vac: 0.85, cmp: 0.75, ide: 0.8, rsk: 0.7, soc: 0.2, inf: 0.2 } },
  { name: 'Le Taj Mahal', by: 'Agra · XVIIe siècle', tag: 'Un chagrin en marbre blanc', color: '#eee8dc',
    desc: 'L\'empereur Shah Jahan l\'a fait construire pour son épouse Mumtaz Mahal, morte en 1631, et il repose aujourd\'hui à ses côtés. Plus de vingt ans de travaux pour dire une seule chose : je n\'oublie pas. C\'est le tempérament des cœurs fidèles et intenses, qui aiment une fois pour toutes et mettent tout leur génie au service de ceux qu\'ils aiment.',
    t: { att: 0.98, vbe: 0.95, loy: 0.92, emp: 0.88, ide: 0.85, rig: 0.8, aff: 0.05, ind: 0.15, vst: 0.2, inc: 0.3 } },
  { name: 'La Grande Muraille', by: 'Chine · IIIe s. av. J.-C.–XVIIe siècle', tag: 'Tenir la ligne, quoi qu\'il coûte', color: '#8a8260',
    desc: 'Des milliers de kilomètres de murs bâtis, rebâtis et reliés pendant deux millénaires pour tenir l\'extérieur à distance. Contrairement à la légende, on ne la voit pas depuis l\'espace, mais on la voit de très loin sur terre. C\'est le tempérament des gardiens obstinés, collectifs et méfiants, pour qui la sécurité du groupe passe avant tout.',
    t: { vse: 0.98, thr: 0.92, col: 0.92, det: 0.95, nat: 0.88, tmp: 0.9, opn: 0.92, ouv: 0.1, vst: 0.1, ind: 0.2 } },
  { name: 'La Cité interdite', by: 'Pékin · 1420', tag: 'Chaque porte a son protocole', color: '#b0302a',
    desc: 'Pendant près de cinq siècles, vingt-quatre empereurs y ont vécu derrière des murs que le peuple n\'avait pas le droit de franchir. Tout y obéit à des règles : la couleur des toits, le nombre des ornements, l\'ordre des cours. C\'est le tempérament des gardiens du protocole, discrets, hiérarchiques et convaincus que chaque chose a sa place.',
    t: { con: 0.98, auth: 0.95, vco: 0.95, ord: 0.95, nat: 0.8, dip: 0.75, inf: 0.15, soc: 0.2, lib: 0.1, vst: 0.1 } },
  { name: 'Angkor Vat', by: 'Cambodge · XIIe siècle', tag: 'Changer de dieux sans s\'effondrer', color: '#7d7a5a',
    desc: 'Bâti au XIIe siècle en l\'honneur de Vishnou, il est devenu bouddhiste sans qu\'on le démolisse, et n\'a jamais été tout à fait abandonné : des moines y sont restés. Il figure aujourd\'hui sur le drapeau du Cambodge. C\'est le tempérament de ceux qui voient grand, durent longtemps et savent évoluer sans renier ce qu\'ils sont.',
    t: { tmp: 0.92, sanc: 0.88, vtr: 0.85, dip: 0.85, vac: 0.8, ouv: 0.8, vpo: 0.75, chg: 0.2, dog: 0.15, vst: 0.2 } },
  { name: 'Borobudur', by: 'Java · IXe siècle', tag: 'Monter en tournant, lentement', color: '#6f6a5e',
    desc: 'On le visite en marchant autour, étage après étage, le long de centaines de bas-reliefs qui racontent le chemin vers l\'éveil, jusqu\'aux stupas du sommet. Enseveli sous les cendres et la jungle pendant des siècles, il ne s\'en est pas plaint. C\'est le tempérament des chercheurs intérieurs, patients et sans ego, pour qui le chemin compte autant que l\'arrivée.',
    t: { ste: 0.95, san: 0.9, sanc: 0.88, tmp: 0.85, emp: 0.8, ouv: 0.8, vpo: 0.05, dom: 0.1, vac: 0.1, cmp: 0.08 } },
  { name: 'Le Pavillon d\'or', by: 'Kyoto · 1397', tag: 'La perfection qui obsède', color: '#d4a82a',
    desc: 'Un pavillon couvert de feuilles d\'or qui se reflète dans un étang parfaitement composé. Sa beauté a tant obsédé un jeune moine qu\'il l\'a incendié en 1950 ; on l\'a reconstruit à l\'identique. C\'est le tempérament des esthètes exigeants et calmes, qui soignent chaque détail, préfèrent la contemplation au bruit et ne transigent pas sur le beau.',
    t: { rig: 0.95, ord: 0.9, ide: 0.88, con: 0.88, san: 0.85, vhe: 0.75, cfl: 0.1, chg: 0.1, soc: 0.25, vst: 0.3 } },
  { name: 'Le sanctuaire Fushimi Inari', by: 'Kyoto · 711', tag: 'Mille petits gestes font un chemin', color: '#e0502a',
    desc: 'Des milliers de portiques vermillon grimpent la colline, chacun offert par une famille ou une entreprise dont le nom est gravé dessus. Aucun n\'est remarquable seul, tous ensemble sont inoubliables. C\'est le tempérament des persévérants modestes, qui croient à l\'effort régulier, à la prospérité bien gagnée et à la force du nombre.',
    t: { det: 0.92, col: 0.9, vtr: 0.88, fia: 0.88, tmp: 0.85, vac: 0.8, ind: 0.12, dom: 0.15, rsk: 0.2, vst: 0.25 } },
  { name: 'Le Machu Picchu', by: 'Pérou · XVe siècle', tag: 'Loin, haut, et parfaitement ajusté', color: '#6f8a5a',
    desc: 'Perchée entre deux sommets andins, la cité inca a échappé aux conquistadors, qui ne l\'ont jamais trouvée. Ses murs de pierres ajustées sans mortier encaissent les séismes mieux que bien des bâtiments modernes. C\'est le tempérament des indépendants qui ont besoin de hauteur et de nature, vivent à l\'écart du tumulte et construisent solide.',
    t: { ind: 0.95, vsd: 0.88, vun: 0.88, rig: 0.85, san: 0.85, soc: 0.12, inf: 0.15, vpo: 0.15, cmp: 0.2 } },
  { name: 'Chichén Itzá', by: 'Mexique · IXe–XIIe siècle', tag: 'Tout arrive à l\'heure prévue', color: '#a89a6a',
    desc: 'La pyramide de Kukulcán compte quatre-vingt-onze marches par face, trois cent soixante-cinq avec la plateforme, comme les jours de l\'année. Aux équinoxes, l\'ombre dessine un serpent qui descend l\'escalier devant des milliers de spectateurs. C\'est le tempérament des planificateurs précis, qui calculent tout et aiment que leurs effets tombent pile.',
    t: { rig: 0.95, ord: 0.95, con: 0.88, aff: 0.88, inf: 0.8, tmp: 0.8, inc: 0.1, loc: 0.15, vhe: 0.25, lib: 0.3 } },
  { name: 'Les moaï de l\'île de Pâques', by: 'Rapa Nui · XIIIe–XVIe siècle', tag: 'Tournés vers les leurs', color: '#6a5f55',
    desc: 'Presque tous les moaï tournent le dos à l\'océan : ils regardent l\'intérieur de l\'île, les villages, ceux qu\'ils sont censés protéger. Ce sont des ancêtres de pierre, pas des sentinelles face au large. C\'est le tempérament de ceux qui veillent sur leur clan, restent fidèles à leurs racines et n\'éprouvent aucun besoin d\'aller voir ailleurs.',
    t: { opn: 0.98, loy: 0.95, vtr: 0.95, vbe: 0.92, ste: 0.88, att: 0.85, ouv: 0.15, vst: 0.1, inf: 0.15, vsd: 0.3 } },
  { name: 'Le Christ Rédempteur', by: 'Rio de Janeiro · 1931', tag: 'Les bras grands ouverts', color: '#cfd6d8',
    desc: 'Vingt-huit mètres d\'envergure au sommet du Corcovado : il accueille toute la baie de Rio d\'un seul geste. Il reçoit la foudre plusieurs fois par an et garde la même posture. C\'est le tempérament des cœurs larges et confiants, qui embrassent tout le monde sans trier, gardent les bras ouverts même quand ça tape, et font du bien par leur seule présence.',
    t: { emp: 0.95, care: 0.95, att: 0.9, opt: 0.9, soc: 0.88, sanc: 0.75, nat: 0.05, vig: 0.15, cfl: 0.15, com: 0.2 } },
  { name: 'La statue de la Liberté', by: 'New York · 1886', tag: 'La torche pour ceux qui arrivent', color: '#6fa89a',
    desc: 'Cadeau de la France aux États-Unis, sculptée par Bartholdi sur une charpente d\'Eiffel, elle a salué des millions d\'immigrants arrivés par bateau. À ses pieds, des chaînes brisées que peu de gens remarquent. C\'est le tempérament des idéalistes engagés, qui défendent la liberté des autres et croient qu\'on se grandit en ouvrant sa porte.',
    t: { lib: 0.98, ide: 0.9, eng: 0.9, vun: 0.9, ouv: 0.88, opt: 0.85, opn: 0.05, nat: 0.2, auth: 0.3, vtr: 0.3 } },
  { name: 'L\'Empire State Building', by: 'New York · 1931', tag: 'Plus haut, et en un an', color: '#8a8f99',
    desc: 'Achevé en 1931 après à peine plus d\'un an de chantier, en pleine Grande Dépression, il est resté le plus haut gratte-ciel du monde pendant près de quarante ans. Ses bureaux sont d\'abord restés si vides qu\'on l\'a surnommé l\'« Empty State Building ». C\'est le tempérament des fonceurs optimistes, qui construisent vite, voient grand et remplissent plus tard.',
    t: { vac: 0.95, det: 0.92, opt: 0.92, aud: 0.9, rsk: 0.88, cmp: 0.85, loc: 0.15, vis: 0.1, ste: 0.25, vig: 0.2 } },
  { name: 'Le Golden Gate Bridge', by: 'San Francisco · 1937', tag: 'Serein dans le brouillard', color: '#c0362c',
    desc: 'Le détroit passait pour infranchissable : courants violents, vents, brouillard, séismes. Il l\'a enjambé en 1937, en orange alors que la Marine le voulait rayé de noir et de jaune, et reste là, calme, quand la brume l\'avale à moitié. C\'est le tempérament des audacieux tranquilles, à l\'aise dans l\'incertain et libres dans leur façon d\'être.',
    t: { san: 0.92, inc: 0.9, aud: 0.85, lib: 0.85, ouv: 0.85, rsk: 0.8, thr: 0.15, dog: 0.1, vtr: 0.2, vse: 0.3 } },
  { name: 'Big Ben', by: 'Londres · 1859', tag: 'À l\'heure, depuis 1859', color: '#9c7f4a',
    desc: 'Big Ben est en réalité le nom de la cloche, pas de la tour, mais personne ne corrige. Pour régler l\'horloge, on ajoute ou on retire de vieilles pièces de monnaie posées sur le balancier. C\'est le tempérament des gens réglés comme du papier à musique, ponctuels, fidèles aux usages, qui n\'aiment pas les surprises et à qui l\'on peut tout confier.',
    t: { fia: 0.98, ord: 0.95, con: 0.95, vtr: 0.9, rig: 0.88, vse: 0.88, vst: 0.08, rsk: 0.1, inc: 0.15, ide: 0.25 } },
  { name: 'Tower Bridge', by: 'Londres · 1894', tag: 'Il s\'ouvre pour laisser passer', color: '#5a7fa0',
    desc: 'Pont-levis victorien, il relève ses deux tabliers des centaines de fois par an pour laisser passer les bateaux, quitte à bloquer la circulation. On le confond souvent avec le London Bridge, et il ne s\'en offusque pas. C\'est le tempérament des arrangeants fiables, qui s\'adaptent aux besoins des autres sans rien perdre de leur allure.',
    t: { fia: 0.92, dip: 0.88, vbe: 0.85, vtr: 0.8, ord: 0.8, loc: 0.75, cfl: 0.1, dog: 0.1, vpo: 0.2, dom: 0.2 } },
  { name: 'Stonehenge', by: 'Angleterre · vers 3000–2000 av. J.-C.', tag: 'Le rendez-vous du solstice', color: '#7f8577',
    desc: 'Certaines de ses pierres ont été acheminées depuis le pays de Galles, à plus de deux cents kilomètres, avec des moyens néolithiques. L\'ensemble est aligné sur le soleil du solstice, et la foule y revient encore chaque année. C\'est le tempérament des bâtisseurs de rituels, qui rassemblent les autres autour d\'un rendez-vous commun et le font durer.',
    t: { vtr: 0.92, tmp: 0.92, col: 0.9, sanc: 0.88, det: 0.88, ord: 0.8, soc: 0.75, inc: 0.75, ind: 0.2, vac: 0.2 } },
  { name: 'La Sagrada Família', by: 'Barcelone · depuis 1882', tag: 'Mon client n\'est pas pressé', color: '#b98a5c',
    desc: 'En chantier depuis 1882, elle a occupé Gaudí jusqu\'à sa mort en 1926, et il savait qu\'il ne la verrait jamais finie. « Mon client n\'est pas pressé », aurait-il dit en parlant de Dieu. C\'est le tempérament des visionnaires au long cours, qui lancent des projets plus grands qu\'eux et acceptent de ne pas en voir la fin.',
    t: { ide: 0.98, tmp: 0.98, det: 0.92, inc: 0.88, sanc: 0.85, vst: 0.75, ord: 0.3, con: 0.2, vac: 0.2, loc: 0.2 } },
  { name: 'L\'Alhambra', by: 'Grenade · XIIIe–XIVe siècle', tag: 'Sobre dehors, somptueux dedans', color: '#b0553a',
    desc: 'Vue de loin, c\'est une forteresse de brique rouge plutôt austère. À l\'intérieur, des stucs ciselés comme de la dentelle, des bassins, des fontaines, des poèmes gravés dans les murs. C\'est le tempérament des raffinés secrets, qui ne montrent pas tout au premier regard et réservent leur richesse intérieure à ceux qui entrent vraiment.',
    t: { ide: 0.9, rig: 0.88, vhe: 0.85, ste: 0.85, att: 0.8, vig: 0.75, inf: 0.15, soc: 0.3, dom: 0.2, aff: 0.25 } },
  { name: 'Le Guggenheim de Bilbao', by: 'Bilbao · 1997', tag: 'Une ville entière relancée', color: '#a9b4bd',
    desc: 'Des vagues de titane posées au bord de la rivière d\'une ville industrielle en déclin : le musée de Frank Gehry a changé l\'image de Bilbao au point qu\'on parle depuis d\'« effet Bilbao ». C\'est le tempérament des disrupteurs flamboyants, qui misent gros, cassent les codes et parient que l\'audace attirera le monde entier.',
    t: { chg: 0.98, aud: 0.95, vst: 0.92, rsk: 0.9, inf: 0.88, vac: 0.85, vtr: 0.05, con: 0.15, vse: 0.15, vis: 0.1 } },
  { name: 'Le château de Neuschwanstein', by: 'Bavière · 1869–1886', tag: 'Un rêve pour échapper au siècle', color: '#9fb0c8',
    desc: 'Louis II de Bavière l\'a fait bâtir comme un décor d\'opéra wagnérien, loin de la cour et de la politique, et n\'y a vécu que quelques mois. Il est mort en 1886, le château inachevé, qui a plus tard inspiré Disney. C\'est le tempérament des rêveurs solitaires, nostalgiques d\'un monde qui n\'a jamais existé, qui préfèrent leur imaginaire au réel.',
    t: { ide: 0.98, ind: 0.88, vsd: 0.85, vis: 0.85, vhe: 0.75, soc: 0.1, aff: 0.1, fia: 0.2, vac: 0.15 } },
  { name: 'La porte de Brandebourg', by: 'Berlin · 1791', tag: 'Elle a vu passer l\'histoire', color: '#c2b08a',
    desc: 'Achevée en 1791, elle a vu son quadrige emporté à Paris par Napoléon puis rapatrié, s\'est retrouvée coincée derrière le Mur pendant vingt-huit ans, avant de devenir le symbole des retrouvailles. C\'est le tempérament de ceux qui encaissent les bouleversements sans perdre leur dignité et croient, au bout du compte, à la réconciliation.',
    t: { san: 0.9, ste: 0.85, fair: 0.85, vun: 0.85, opt: 0.85, col: 0.8, loc: 0.8, cfl: 0.3, vpo: 0.2, vis: 0.15, dog: 0.1 } },
  { name: 'L\'East Side Gallery', by: 'Berlin · Mur de 1961, peint en 1990', tag: 'Peindre sur la cicatrice', color: '#e0643a',
    desc: 'Le Mur devait séparer, il est devenu une toile : en 1990, cent dix-huit artistes venus de vingt et un pays ont couvert plus d\'un kilomètre de béton de fresques. Ce qui reste du mur de Berlin raconte désormais la liberté. C\'est le tempérament des insoumis créatifs, qui répondent à la contrainte par l\'expression et transforment les blessures en manifeste.',
    t: { lib: 0.98, eng: 0.9, chg: 0.9, com: 0.88, ide: 0.88, cfl: 0.85, auth: 0.08, vco: 0.08, vse: 0.25, ste: 0.25 } },
  { name: 'L\'Atomium', by: 'Bruxelles · 1958', tag: 'Le futur, vu de 1958', color: '#b8c4cc',
    desc: 'Un cristal de fer agrandi cent soixante-cinq milliards de fois, bâti pour l\'Exposition universelle et censé ne durer que six mois. Il est resté, avec ses sphères brillantes et son optimisme d\'époque sur la science. C\'est le tempérament des curieux enthousiastes, un peu geeks, convaincus que demain sera plus intéressant qu\'aujourd\'hui.',
    t: { opt: 0.95, ouv: 0.92, vst: 0.88, aff: 0.8, ide: 0.8, inf: 0.75, vis: 0.05, vtr: 0.12, dog: 0.2, thr: 0.15 } },
  { name: 'Le Manneken-Pis', by: 'Bruxelles · 1619', tag: 'Petit, insolent et très habillé', color: '#6b5a3a',
    desc: 'Une cinquantaine de centimètres de bronze, une posture peu protocolaire et plus d\'un millier de costumes offerts par le monde entier. Il ne se prend jamais au sérieux, et c\'est exactement pour ça qu\'on l\'aime. C\'est le tempérament des farceurs sympathiques, qui dédramatisent tout, se moquent des grands airs et mettent de l\'humour partout.',
    t: { opt: 0.9, vhe: 0.9, soc: 0.9, inf: 0.88, lib: 0.85, vpo: 0.05, sanc: 0.05, vco: 0.1, auth: 0.1, vac: 0.15 } },
  { name: 'Sainte-Sophie', by: 'Istanbul · 537', tag: 'Quinze siècles, plusieurs vies', color: '#b86a4a',
    desc: 'Achevée en 537 sous Justinien, elle a été cathédrale, puis mosquée, puis musée, puis de nouveau mosquée, et sa coupole semble toujours suspendue dans le vide. Chaque époque y a laissé sa trace sans effacer tout à fait la précédente. C\'est le tempérament de ceux qui traversent les changements de régime avec souplesse et gardent une grandeur intacte.',
    t: { tmp: 0.95, dip: 0.9, san: 0.88, loc: 0.85, inc: 0.85, sanc: 0.85, ouv: 0.8, dog: 0.1, dom: 0.3, vst: 0.25 } },
  { name: 'La cathédrale Saint-Basile', by: 'Moscou · 1555–1561', tag: 'Pas deux coupoles pareilles', color: '#c23a4a',
    desc: 'Élevée sur la place Rouge sous Ivan le Terrible, elle aligne des bulbes torsadés, rayés, à facettes, de toutes les couleurs, comme si chacun avait eu sa propre idée. Une légende veut même qu\'on ait aveuglé ses architectes pour qu\'ils ne refassent jamais pareille merveille. C\'est le tempérament des exubérants fidèles à leurs traditions, joyeusement excessifs.',
    t: { vst: 0.9, ide: 0.9, inf: 0.88, vtr: 0.85, vhe: 0.8, sanc: 0.8, ord: 0.15, con: 0.2, dip: 0.3, rig: 0.35 } },
  { name: 'L\'opéra de Sydney', by: 'Sydney · 1973', tag: 'Le génie qui dépasse le budget', color: '#e8e2d2',
    desc: 'Jørn Utzon a gagné le concours avec des esquisses de voiles que personne ne savait construire. Dix ans de retard, un budget multiplié par quatorze, et l\'architecte a quitté le chantier en 1966 sans jamais revoir l\'œuvre achevée. C\'est le tempérament des créatifs géniaux et ingérables, qui promettent l\'impossible et finissent par le livrer, autrement.',
    t: { ide: 0.95, aud: 0.92, vst: 0.88, chg: 0.85, inf: 0.75, fia: 0.15, vse: 0.12, con: 0.15, dip: 0.2, ord: 0.25 } },
  { name: 'Le Burj Khalifa', by: 'Dubaï · 2010', tag: 'Le record, rien d\'autre', color: '#5f7d99',
    desc: 'Huit cent vingt-huit mètres, plus haute tour du monde depuis 2010, bâtie pour être vue de partout et citée partout. Chaque étage supplémentaire est un message adressé à la concurrence. C\'est le tempérament des ambitieux qui aiment les chiffres, le prestige et la première place, et qui n\'éprouvent aucune gêne à le montrer.',
    t: { cmp: 0.98, vpo: 0.95, vac: 0.95, dom: 0.9, inf: 0.8, emp: 0.2, care: 0.2, vun: 0.15, vtr: 0.15, ste: 0.3 } },
  { name: 'Le panneau Hollywood', by: 'Los Angeles · 1923', tag: 'Une pub devenue rêve', color: '#e9e9e4',
    desc: 'En 1923, ce n\'était qu\'une réclame immobilière qui disait HOLLYWOODLAND. On a retiré les quatre dernières lettres en 1949, et en 1978 des vedettes ont financé sa reconstruction lettre par lettre. C\'est le tempérament de ceux qui rêvent de lumière, se réinventent au gré des occasions et font de n\'importe quel point de départ une histoire à raconter.',
    t: { inf: 0.95, vac: 0.9, opt: 0.88, vst: 0.85, loc: 0.8, cmp: 0.75, vtr: 0.1, sanc: 0.1, rig: 0.2, ste: 0.2 } },
  { name: 'Les moulins de Kinderdijk', by: 'Pays-Bas · vers 1740', tag: 'Les pieds au sec, ensemble', color: '#5a6f7f',
    desc: 'Dix-neuf moulins bâtis vers 1740 pour pomper l\'eau des polders et garder la terre habitable. Aucun ne suffit seul, tous tournent pour le même but, sans que personne ne réclame de gloire. C\'est le tempérament des coéquipiers solides, qui préfèrent l\'utilité commune à la reconnaissance et savent qu\'on ne tient face aux éléments qu\'à plusieurs.',
    t: { col: 0.95, fia: 0.92, ste: 0.9, vse: 0.88, care: 0.8, fair: 0.8, cmp: 0.08, vpo: 0.05, inf: 0.15, vst: 0.15 } },
  { name: 'La coupole de Florence', by: 'Florence · 1420–1436', tag: 'Le problème que personne ne savait résoudre', color: '#c2603a',
    desc: 'La cathédrale est restée sans coupole pendant des décennies : personne ne savait couvrir un tel vide. Brunelleschi a gagné le concours, gardé ses méthodes pour lui et bâti un dôme sans cintre de bois, en briques posées en arêtes de poisson. C\'est le tempérament des cerveaux solitaires et compétitifs, qui adorent l\'impossible et n\'expliquent pas leurs tours.',
    t: { aff: 0.95, det: 0.9, ind: 0.9, cmp: 0.88, rig: 0.88, aud: 0.85, nat: 0.8, soc: 0.2, dip: 0.2, col: 0.15 } },
  { name: 'Le Grand Bouddha de Kamakura', by: 'Japon · XIIIe siècle', tag: 'Rien ne l\'ébranle', color: '#4f6b62',
    desc: 'Coulé en bronze au XIIIe siècle, il était abrité dans un grand pavillon que tempêtes et raz-de-marée ont emporté plusieurs fois. Depuis 1498, il médite en plein air, sous la pluie comme sous le soleil, sans avoir l\'air d\'y prêter attention. C\'est le tempérament des sereins profonds, qui acceptent ce qui arrive et ne perdent jamais leur calme.',
    t: { san: 0.98, ste: 0.95, inc: 0.9, loc: 0.8, opt: 0.75, thr: 0.05, cfl: 0.05, vst: 0.1, vac: 0.1, dom: 0.1 } },
  { name: 'La grande mosquée de Djenné', by: 'Mali · 1907', tag: 'Refaite chaque année par toute la ville', color: '#b98a5a',
    desc: 'Entièrement bâtie en terre crue, la grande mosquée de Djenné fondrait sans soin. Alors chaque année, lors d\'une grande fête, les habitants la recouvrent ensemble d\'un nouvel enduit, dans les chants et la bonne humeur. C\'est le tempérament de ceux qui savent que rien ne dure sans entretien, et que l\'entretien, fait à plusieurs, peut être une fête.',
    t: { col: 0.98, vtr: 0.92, soc: 0.9, fia: 0.88, care: 0.85, sanc: 0.8, vhe: 0.7, ind: 0.08, vpo: 0.1, cmp: 0.08 } },
];

window.PRISME_MONUMENTS = { MONUMENTS };
