/* ============================================================
   PRISME — « Si tu étais une musique »
   ------------------------------------------------------------
   Un morceau, pas un genre. On compare le caractère du titre —
   son énergie, son rapport au temps, ce qu'il cherche à provoquer —
   au caractère de la personne, avec les dimensions du test.
   ============================================================ */
const MUSICS = [
  { name: 'Bohemian Rhapsody', by: 'Queen · 1975', tag: 'Six minutes qui changent trois fois d\'avis', color: '#c2850c',
    desc: 'Une ballade qui devient un opéra qui devient du hard rock, sans que personne n\'ait demandé l\'autorisation. Le morceau ne rentre dans aucune case et n\'a jamais essayé : c\'est de l\'ambition pure, portée par une théâtralité assumée.',
    t: { ouv: 0.95, vst: 0.9, vac: 0.9, aud: 0.95, inf: 0.9, chg: 0.9, vco: 0.05, ord: 0.2, ste: 0.1, cmp: 0.7 } },
  { name: 'Ne me quitte pas', by: 'Jacques Brel · 1959', tag: 'Tout donner, sans fierté', color: '#5b5468',
    desc: 'Un homme qui supplie, sans aucune retenue, jusqu\'à proposer de devenir l\'ombre de quelqu\'un. Brel lui-même disait que ce n\'était pas une chanson d\'amour mais une chanson de lâcheté. La sincérité y est totale et douloureuse.',
    t: { att: 0.98, emp: 0.95, vis: 0.9, ide: 0.8, ind: 0.05, vpo: 0.02, aff: 0.05, dom: 0.05, care: 0.85, san: 0.1 } },
  { name: 'Lose Yourself', by: 'Eminem · 2002', tag: 'Une seule chance, maintenant', color: '#46596b',
    desc: 'Un morceau tendu du début à la fin, construit sur l\'idée qu\'il n\'y aura pas de deuxième occasion. Le débit s\'accélère, la pression monte, et rien n\'est laissé au hasard : c\'est de la détermination mise en musique.',
    t: { det: 0.98, vac: 0.95, cmp: 0.9, eng: 0.9, aud: 0.9, thr: 0.8, ste: 0.05, vhe: 0.2, opt: 0.5, rig: 0.85 } },
  { name: 'Smells Like Teen Spirit', by: 'Nirvana · 1991', tag: 'La colère mal rangée', color: '#8a8250',
    desc: 'Un riff simple, un refrain hurlé, et des paroles volontairement illisibles : l\'énergie passe avant le message. Le morceau a défini une génération précisément parce qu\'il refusait d\'expliquer ce qu\'il voulait dire.',
    t: { com: 0.95, chg: 0.9, ind: 0.9, cfl: 0.9, nat: 0.85, vis: 0.8, vco: 0.05, ord: 0.1, dip: 0.05, vac: 0.3 } },
  { name: 'Imagine', by: 'John Lennon · 1971', tag: 'L\'utopie à voix basse', color: '#8fbf6a',
    desc: 'Un piano simple et une proposition maximale : imaginer un monde sans frontières ni possessions. Le morceau est doux, presque naïf dans sa forme, et radical dans son contenu — c\'est ce contraste qui le rend inusable.',
    t: { ide: 0.98, vun: 0.98, dip: 0.9, opt: 0.9, care: 0.9, epi: 0.9, ste: 0.8, com: 0.1, vtr: 0.05, cmp: 0.02 } },
  { name: 'Billie Jean', by: 'Michael Jackson · 1982', tag: 'La tension parfaitement tenue', color: '#3a3a44',
    desc: 'Une ligne de basse qui ne lâche jamais, une voix nerveuse, et un groove d\'une précision millimétrée. Le morceau est froid, maîtrisé, obsédant — de la tension transformée en machine à danser.',
    t: { rig: 0.95, san: 0.85, vac: 0.9, thr: 0.8, det: 0.9, cmp: 0.85, ord: 0.9, nat: 0.8, ste: 0.2, soc: 0.7 } },
  { name: 'Stairway to Heaven', by: 'Led Zeppelin · 1971', tag: 'La montée lente', color: '#8a6a2f',
    desc: 'Huit minutes qui commencent sur une guitare acoustique et finissent en mur de son, sans jamais brusquer la transition. Le morceau demande de la patience et récompense ceux qui la donnent.',
    t: { tmp: 0.98, ouv: 0.85, ide: 0.85, rig: 0.8, aud: 0.75, vst: 0.6, ste: 0.6, com: 0.2, vhe: 0.5, epi: 0.7 } },
  { name: 'Formidable', by: 'Stromae · 2013', tag: 'Le désastre en public', color: '#e2569b',
    desc: 'Un homme ivre de chagrin qui interpelle les passants, filmé en caméra cachée dans la rue. Le morceau est d\'une honnêteté gênante et transforme l\'humiliation en chanson populaire.',
    t: { emp: 0.9, vis: 0.9, att: 0.9, ide: 0.75, soc: 0.6, san: 0.05, vco: 0.1, com: 0.6, care: 0.8, aff: 0.15 } },
  { name: 'Alors on danse', by: 'Stromae · 2009', tag: 'Danser pour ne pas y penser', color: '#e9a100',
    desc: 'Un rythme entêtant et un texte qui énumère les emmerdes de la vie ordinaire. Le morceau fait danser des salles entières sur un constat plutôt sombre, et c\'est exactement le propos.',
    t: { vhe: 0.9, vis: 0.85, soc: 0.85, col: 0.8, emp: 0.8, loc: 0.75, opt: 0.3, vac: 0.2, vpo: 0.1, com: 0.4 } },
  { name: 'Mistral gagnant', by: 'Renaud · 1985', tag: 'La tendresse d\'un père', color: '#8a9a5b',
    desc: 'Un homme raconte à sa fille les bonbons de son enfance et, sans le dire, lui explique qu\'il ne sera pas toujours là. Le morceau est simple, tendre, et fait pleurer des gens qui ne pleurent jamais.',
    t: { care: 0.98, emp: 0.95, att: 0.95, vtr: 0.85, tmp: 0.8, vbe: 0.95, ste: 0.85, vpo: 0.02, com: 0.1, vac: 0.1 } },
  { name: 'Non, je ne regrette rien', by: 'Édith Piaf · 1960', tag: 'Tout assumer, y compris les erreurs', color: '#d62828',
    desc: 'Une déclaration frontale : ni le bien ni le mal du passé ne pèse, on repart de zéro. Le morceau est court, martial, et sa force tient dans un refus total de s\'excuser.',
    t: { det: 0.95, ind: 0.9, chg: 0.85, dog: 0.85, aud: 0.9, vsd: 0.9, com: 0.8, vis: 0.2, thr: 0.05, vse: 0.1 } },
  { name: 'La Bohème', by: 'Charles Aznavour · 1965', tag: 'Le souvenir d\'un temps pauvre et heureux', color: '#a97142',
    desc: 'Un peintre revient dans le quartier de sa jeunesse et ne le reconnaît plus. Le morceau est nostalgique sans amertume, et raconte que l\'on a été heureux surtout quand on n\'avait rien.',
    t: { vtr: 0.95, att: 0.9, opn: 0.9, vis: 0.7, emp: 0.85, tmp: 0.75, ide: 0.8, vac: 0.2, vpo: 0.05, chg: 0.15 } },
  { name: 'Get Lucky', by: 'Daft Punk · 2013', tag: 'Le plaisir sans arrière-pensée', color: '#c9a227',
    desc: 'Un groove élégant, une guitare souple, et aucune ambition autre que de rendre la soirée meilleure. Le morceau est solaire, décontracté, et parfaitement à l\'aise dans sa propre légèreté.',
    t: { vhe: 0.95, soc: 0.9, opt: 0.9, inf: 0.85, ste: 0.8, dip: 0.8, vac: 0.4, com: 0.05, thr: 0.05, vis: 0.1 } },
  { name: 'One More Time', by: 'Daft Punk · 2000', tag: 'La joie collective', color: '#e08700',
    desc: 'Une montée, un break qui dure trop longtemps exprès, et une explosion attendue par toute la salle. Le morceau est fait pour être vécu à plusieurs, et il le sait.',
    t: { soc: 0.95, col: 0.9, opt: 0.95, vhe: 0.95, inf: 0.9, ide: 0.7, ind: 0.1, com: 0.05, nat: 0.05, vac: 0.5 } },
  { name: 'Nothing Else Matters', by: 'Metallica · 1991', tag: 'La confiance rendue',
    color: '#5c7fa3',
    desc: 'Un groupe connu pour sa brutalité pose ses armes le temps d\'un morceau et parle de proximité. L\'arpège d\'ouverture est devenu un standard, et la retenue y est plus impressionnante que la puissance.',
    t: { att: 0.95, fia: 0.9, loy: 0.9, ind: 0.8, ide: 0.8, san: 0.75, emp: 0.8, com: 0.3, soc: 0.3, vco: 0.2 } },
  { name: 'Highway to Hell', by: 'AC/DC · 1979', tag: 'Foncer en riant', color: '#e2452f',
    desc: 'Un riff, une basse, une batterie, et aucune subtilité — c\'est tout l\'intérêt. Le morceau annonce la catastrophe avec un sourire et ne ralentit à aucun moment.',
    t: { aud: 0.95, vhe: 0.95, com: 0.85, ind: 0.85, opt: 0.8, rsk: 0.95, thr: 0.05, vse: 0.05, rig: 0.2, vco: 0.05 } },
  { name: 'Creep', by: 'Radiohead · 1992', tag: 'Se sentir de trop', color: '#6b7280',
    desc: 'Quatre accords, une voix qui craque, et l\'aveu d\'un sentiment que la plupart des gens taisent. Le morceau est d\'une simplicité désarmante et d\'une honnêteté presque insupportable.',
    t: { emp: 0.85, vis: 0.95, ind: 0.8, thr: 0.85, vac: 0.15, vpo: 0.05, dom: 0.05, soc: 0.15, att: 0.8, opt: 0.05 } },
  { name: 'Africa', by: 'Toto · 1982', tag: 'La nostalgie d\'un lieu jamais vu', color: '#e0983a',
    desc: 'Des claviers de synthèse, un refrain immense, et des paroles que personne ne comprend vraiment. Le morceau est chaleureux, un peu kitsch, et met tout le monde d\'accord depuis quarante ans.',
    t: { soc: 0.9, opt: 0.9, ide: 0.8, vhe: 0.85, ouv: 0.8, col: 0.8, ste: 0.75, com: 0.05, nat: 0.1, cmp: 0.15 } },
  { name: 'Feeling Good', by: 'Nina Simone · 1965', tag: 'Recommencer à zéro', color: '#c2670c',
    desc: 'Une voix seule, puis des cuivres qui déboulent, pour dire qu\'une nouvelle vie commence aujourd\'hui. Le morceau prend son temps, s\'impose sans crier, et déborde de puissance contenue.',
    t: { det: 0.9, ind: 0.9, chg: 0.85, san: 0.85, ide: 0.85, opt: 0.85, vsd: 0.9, dom: 0.7, thr: 0.1, vco: 0.1 } },
  { name: 'Hallelujah', by: 'Leonard Cohen · 1984', tag: 'La foi et le doute ensemble', color: '#7a6a4a',
    desc: 'Un texte à la fois sacré et charnel, repris des centaines de fois, qui n\'a jamais tranché entre l\'élévation et la chute. Le morceau est lent, grave, et laisse chacun y mettre ce qu\'il porte.',
    t: { sanc: 0.9, ide: 0.9, emp: 0.9, inc: 0.9, tmp: 0.85, vis: 0.7, aff: 0.4, dog: 0.15, com: 0.1, vhe: 0.3 } },
  { name: 'Dernière danse', by: 'Indila · 2013', tag: 'Tourner malgré la douleur', color: '#9b5de5',
    desc: 'Une mélodie qui monte, une voix qui se brise, et une danse qui tient lieu de réponse à tout le reste. Le morceau est dramatique sans honte, et c\'est pour ça qu\'il fonctionne.',
    t: { emp: 0.95, ide: 0.85, att: 0.85, vis: 0.85, det: 0.85, vhe: 0.7, san: 0.15, aff: 0.1, cmp: 0.1, care: 0.8 } },
  { name: 'Balance ton quoi', by: 'Angèle · 2018', tag: 'Dire les choses en souriant', color: '#e05fa0',
    desc: 'Un morceau pop très léger qui dit des choses très fermes, avec une ironie qui désamorce sans reculer. La forme douce rend le propos plus difficile à balayer.',
    t: { ide: 0.9, eng: 0.85, dip: 0.8, soc: 0.85, inf: 0.85, fair: 0.9, com: 0.6, opt: 0.7, cfl: 0.4, vco: 0.2 } },
  { name: 'Djadja', by: 'Aya Nakamura · 2018', tag: 'Remettre les choses au clair', color: '#e2569b',
    desc: 'Un rythme souple, une langue bien à elle, et un refus net de laisser passer un mensonge. Le morceau est direct, sûr de lui, et a imposé son vocabulaire à tout un pays.',
    t: { ind: 0.9, com: 0.85, vsd: 0.9, soc: 0.85, det: 0.85, inf: 0.85, dom: 0.75, vco: 0.15, dip: 0.3, thr: 0.15 } },
  { name: 'Bande organisée', by: 'Jul et le 13\'Organisé · 2020', tag: 'La ville en collectif', color: '#1c86c9',
    desc: 'Une quinzaine de rappeurs d\'une même ville sur un seul titre, chacun avec sa place. Le morceau est un manifeste d\'appartenance : ce n\'est pas une performance individuelle, c\'est une photo de groupe.',
    t: { col: 0.95, att: 0.95, loy: 0.9, opn: 0.9, soc: 0.85, com: 0.8, ind: 0.15, vun: 0.2, cmp: 0.6, vac: 0.7 } },
  { name: 'Wonderwall', by: 'Oasis · 1995', tag: 'La chanson qu\'on gratte au feu de camp', color: '#8a8f98',
    desc: 'Quatre accords que tout le monde connaît, un refrain flou et universel, et une mélancolie décontractée. Le morceau est devenu une sorte de patrimoine commun sans avoir rien demandé.',
    t: { soc: 0.85, opn: 0.85, ste: 0.8, att: 0.8, emp: 0.75, vhe: 0.75, ide: 0.6, vac: 0.3, rig: 0.2, com: 0.2 } },
  { name: 'Seven Nation Army', by: 'The White Stripes · 2003', tag: 'Le riff que les stades reprennent', color: '#b3001b',
    desc: 'Sept notes, une batterie sèche, et une ligne devenue un cri collectif dans tous les stades du monde. Le morceau est minimal, martial, et d\'une efficacité redoutable.',
    t: { det: 0.9, com: 0.9, col: 0.85, ind: 0.8, cmp: 0.85, rig: 0.8, aud: 0.85, dip: 0.15, vhe: 0.5, ord: 0.7 } },
  { name: 'Clair de lune', by: 'Claude Debussy · 1905', tag: 'Le calme, sans un mot', color: '#8c99a8',
    desc: 'Un piano seul, très lent, qui ne cherche à impressionner personne. Le morceau laisse de la place au silence et à celui qui écoute — c\'est une musique d\'intériorité.',
    t: { san: 0.98, tmp: 0.9, emp: 0.85, ste: 0.9, ind: 0.8, aff: 0.5, com: 0.02, cmp: 0.02, vpo: 0.02, vhe: 0.5 } },
  { name: 'Adagio pour cordes', by: 'Samuel Barber · 1936', tag: 'Le chagrin qui monte', color: '#5a6b7d',
    desc: 'Une seule phrase musicale qui s\'élève lentement jusqu\'à un sommet insoutenable, puis retombe. Le morceau est devenu la bande-son universelle du deuil, et il mérite cette réputation.',
    t: { emp: 0.95, vis: 0.9, tmp: 0.9, care: 0.9, san: 0.6, ide: 0.8, opt: 0.05, vhe: 0.05, soc: 0.1, com: 0.05 } },
  { name: 'Ode à la joie', by: 'Beethoven · 1824', tag: 'La fraternité en majesté', color: '#c9a227',
    desc: 'Un final de symphonie qui fait entrer des voix humaines là où on n\'en attendait pas, pour dire que tous les hommes deviennent frères. Composé par un homme devenu sourd, ce qui ajoute quelque chose.',
    t: { vun: 0.95, col: 0.9, ide: 0.95, opt: 0.9, det: 0.95, inf: 0.9, care: 0.85, cfl: 0.1, nat: 0.1, tmp: 0.9 } },
  { name: 'Lacrimosa', by: 'Mozart · 1791', tag: 'La gravité inachevée', color: '#5b5468',
    desc: 'Les dernières mesures qu\'un compositeur mourant a écrites de sa main, avant que d\'autres terminent à sa place. Le morceau est solennel, tremblant, et sa beauté doit beaucoup à ce qu\'il ne finit pas.',
    t: { sanc: 0.95, vis: 0.85, emp: 0.9, tmp: 0.9, vtr: 0.9, ide: 0.85, san: 0.5, vhe: 0.05, opt: 0.1, soc: 0.1 } },
  { name: 'L\'Été (Les Quatre Saisons)', by: 'Vivaldi · 1725', tag: 'L\'orage qui arrive', color: '#e2721c',
    desc: 'Une chaleur lourde, puis une tempête qui se déchaîne en quelques mesures. Le morceau est nerveux, rapide, presque agressif — très loin de la musique d\'ascenseur qu\'on en a fait.',
    t: { vst: 0.9, com: 0.85, aud: 0.85, rig: 0.9, det: 0.9, thr: 0.75, ste: 0.1, san: 0.3, cmp: 0.8, vhe: 0.6 } },
  { name: 'Time', by: 'Hans Zimmer · 2010', tag: 'La montée qui n\'en finit pas', color: '#46596b',
    desc: 'Quelques notes répétées qui s\'empilent pendant quatre minutes jusqu\'à devenir écrasantes. Le morceau ne raconte rien de précis et provoque pourtant quelque chose chez presque tout le monde.',
    t: { tmp: 0.98, det: 0.95, ide: 0.85, san: 0.8, rig: 0.9, emp: 0.8, ord: 0.9, vhe: 0.1, soc: 0.1, com: 0.15 } },
  { name: 'Now We Are Free', by: 'Hans Zimmer et Lisa Gerrard · 2000', tag: 'Rentrer enfin chez soi', color: '#8a9a5b',
    desc: 'Une voix qui chante dans une langue inventée, sur un thème de retour et d\'apaisement. Le morceau est ample, lumineux, et clôt une histoire de vengeance par quelque chose de doux.',
    t: { att: 0.9, ide: 0.9, san: 0.9, emp: 0.9, tmp: 0.85, vtr: 0.85, care: 0.85, com: 0.05, cmp: 0.05, vpo: 0.05 } },
  { name: 'Comfortably Numb', by: 'Pink Floyd · 1979', tag: 'L\'absence à soi-même', color: '#4a4159',
    desc: 'Une voix lointaine, une autre qui répond, et un solo de guitare qui dit ce que les mots ne disent pas. Le morceau décrit un engourdissement, et il prend tout son temps pour le faire sentir.',
    t: { vis: 0.9, ind: 0.9, aff: 0.7, emp: 0.8, tmp: 0.85, loc: 0.8, san: 0.6, eng: 0.15, soc: 0.1, opt: 0.1 } },
  { name: 'Another Brick in the Wall', by: 'Pink Floyd · 1979', tag: 'Refuser le moule', color: '#8a8f98',
    desc: 'Un chœur d\'enfants qui réclame qu\'on les laisse tranquilles, sur un groove implacable. Le morceau est frontal, politique, et a été interdit dans plusieurs pays — ce qui lui a plutôt bien réussi.',
    t: { lib: 0.95, com: 0.9, chg: 0.9, ind: 0.9, auth: 0.05, vco: 0.05, cfl: 0.85, eng: 0.9, vis: 0.85, col: 0.7 } },
  { name: 'Eye of the Tiger', by: 'Survivor · 1982', tag: 'Se remettre en marche', color: '#e08700',
    desc: 'Une intro de guitare devenue synonyme d\'entraînement dans le monde entier. Le morceau ne fait aucune promesse subtile : il sert à se lever et à y retourner.',
    t: { det: 0.98, cmp: 0.95, vac: 0.9, eng: 0.9, opt: 0.85, aud: 0.9, ste: 0.15, vhe: 0.4, dip: 0.15, tmp: 0.5 } },
  { name: 'Don\'t Stop Me Now', by: 'Queen · 1978', tag: 'L\'euphorie totale', color: '#f2b705',
    desc: 'Un piano lancé à toute allure, une voix qui monte sans effort, et aucune intention de ralentir. Le morceau est pure joie, sans une once de pudeur.',
    t: { vhe: 0.98, opt: 0.98, soc: 0.95, inf: 0.95, aud: 0.9, vst: 0.9, thr: 0.02, vse: 0.05, ste: 0.1, vis: 0.02 } },
  { name: 'Rolling in the Deep', by: 'Adele · 2010', tag: 'La colère qui chante juste', color: '#7a2f2f',
    desc: 'Une voix pleine, un rythme qui martèle, et une rupture transformée en avertissement. Le morceau n\'est pas triste : il est furieux, et parfaitement maîtrisé.',
    t: { com: 0.9, det: 0.9, emp: 0.85, ind: 0.85, dom: 0.8, vac: 0.8, att: 0.8, dip: 0.15, san: 0.4, vco: 0.15 } },
  { name: 'Someone Like You', by: 'Adele · 2011', tag: 'Accepter, sans y arriver', color: '#8c99a8',
    desc: 'Un piano, une voix, et quelqu\'un qui prétend souhaiter du bien à l\'autre tout en s\'écroulant. Le morceau est nu, sans production, et c\'est ce dépouillement qui le rend difficile à écouter deux fois de suite.',
    t: { emp: 0.95, att: 0.95, vis: 0.85, dip: 0.8, care: 0.85, ste: 0.7, ind: 0.3, com: 0.1, vpo: 0.02, san: 0.25 } },
  { name: 'Blinding Lights', by: 'The Weeknd · 2019', tag: 'Rouler la nuit', color: '#b5179e',
    desc: 'Des synthés des années quatre-vingt, un tempo élevé, et une solitude qui avance vite. Le morceau est brillant en surface et assez sombre en dessous — un mélange très contemporain.',
    t: { vst: 0.9, ind: 0.85, vhe: 0.85, vis: 0.7, soc: 0.6, det: 0.8, thr: 0.6, att: 0.7, ste: 0.15, opn: 0.15 } },
  { name: 'Gangsta\'s Paradise', by: 'Coolio · 1995', tag: 'Le constat sans échappatoire', color: '#4f5b3a',
    desc: 'Un chœur grave, un texte lucide sur une vie sans sortie, et aucune tentative de faire joli. Le morceau est solennel, presque liturgique, et d\'un pessimisme assumé.',
    t: { vis: 0.95, nat: 0.9, eng: 0.85, aff: 0.7, col: 0.8, com: 0.75, opt: 0.05, vhe: 0.1, tmp: 0.6, ide: 0.7 } },
  { name: 'Still D.R.E.', by: 'Dr. Dre et Snoop Dogg · 1999', tag: 'Le retour maîtrisé', color: '#3a3a44',
    desc: 'Un piano obsédant, une production impeccable, et un homme qui rappelle calmement qu\'il n\'est jamais parti. Le morceau est froid, assuré, et n\'a besoin d\'élever la voix à aucun moment.',
    t: { san: 0.9, vac: 0.9, dom: 0.9, rig: 0.9, cmp: 0.85, vpo: 0.85, det: 0.9, thr: 0.15, emp: 0.25, vhe: 0.6 } },
  { name: 'Believer', by: 'Imagine Dragons · 2017', tag: 'Transformer la douleur en carburant', color: '#e2452f',
    desc: 'Une percussion lourde, un refrain scandé, et l\'idée que ce qui fait mal a servi à construire. Le morceau est direct, motivant, et parfaitement calibré pour les salles de sport.',
    t: { det: 0.95, com: 0.9, eng: 0.85, vac: 0.85, aud: 0.85, vis: 0.6, opt: 0.7, ste: 0.15, dip: 0.2, cmp: 0.85 } },
  { name: 'Bella ciao', by: 'Traditionnel italien', tag: 'Le chant qu\'on reprend ensemble', color: '#d62828',
    desc: 'Une mélodie simple, transmissible en une écoute, portée par des générations de gens en lutte. Le morceau n\'appartient à personne et appartient à tout le monde : c\'est sa définition.',
    t: { col: 0.95, eng: 0.95, ide: 0.9, com: 0.85, loy: 0.9, lib: 0.9, opt: 0.8, vtr: 0.85, ind: 0.15, vpo: 0.1 } },
  { name: 'What a Wonderful World', by: 'Louis Armstrong · 1967', tag: 'Regarder ce qui va bien', color: '#5fa860',
    desc: 'Une voix rauque et bienveillante qui énumère des choses ordinaires et magnifiques. Enregistré en pleine période troublée, ce qui en fait moins une naïveté qu\'un choix.',
    t: { opt: 0.98, care: 0.95, emp: 0.9, ste: 0.95, san: 0.9, vbe: 0.95, vis: 0.02, com: 0.02, cmp: 0.02, tmp: 0.7 } },
  { name: 'Riders on the Storm', by: 'The Doors · 1971', tag: 'La route et la pluie', color: '#4a4a52',
    desc: 'Un clavier électrique, une pluie enregistrée, et une voix murmurée qui parle d\'un danger imprécis. Le morceau avance lentement, sans destination claire, et installe une inquiétude durable.',
    t: { thr: 0.9, ind: 0.9, aff: 0.6, vis: 0.85, nat: 0.85, san: 0.6, vst: 0.75, soc: 0.15, opt: 0.1, ste: 0.3 } },
  { name: 'Take On Me', by: 'a-ha · 1985', tag: 'L\'élan qui monte trop haut', color: '#2a75bb',
    desc: 'Un synthé reconnaissable en trois notes et une voix qui atteint un aigu impossible. Le morceau est d\'un optimisme juvénile, pressé, et toujours aussi efficace quarante ans plus tard.',
    t: { opt: 0.95, vst: 0.9, soc: 0.9, inf: 0.9, aud: 0.85, vhe: 0.9, ide: 0.7, thr: 0.1, vis: 0.05, tmp: 0.2 } },
  { name: 'Papaoutai', by: 'Stromae · 2013', tag: 'La question qu\'on n\'ose pas poser', color: '#e9a100',
    desc: 'Un rythme dansant et un texte sur un père absent, l\'un servant à faire passer l\'autre. Le morceau est un manuel de ce que la pop peut faire : danser sur ce qui fait mal.',
    t: { att: 0.95, emp: 0.9, vis: 0.85, soc: 0.85, care: 0.85, ide: 0.8, vhe: 0.75, san: 0.2, com: 0.4, aff: 0.2 } },
  { name: 'Je veux', by: 'Zaz · 2010', tag: 'Refuser ce qu\'on lui propose', color: '#e0983a',
    desc: 'Une voix éraillée, un swing léger, et une liste de choses dont elle ne veut pas. Le morceau est joyeux et frondeur, et son refus du confort matériel n\'a rien d\'agressif.',
    t: { lib: 0.95, vsd: 0.9, vhe: 0.9, soc: 0.9, opt: 0.9, ind: 0.85, vpo: 0.05, vac: 0.1, vse: 0.15, dip: 0.7 } },
  { name: 'Sweet Child O\' Mine', by: 'Guns N\' Roses · 1987', tag: 'La tendresse d\'un groupe brutal', color: '#c2850c',
    desc: 'Une intro de guitare écrite comme un exercice d\'échauffement et devenue un standard, sur un texte étonnamment doux. Le contraste entre la voix et le sujet fait tout le charme.',
    t: { att: 0.85, aud: 0.9, vhe: 0.85, ind: 0.8, inf: 0.85, com: 0.6, emp: 0.75, rig: 0.4, vco: 0.1, opt: 0.7 } },
  { name: 'L\'Aigle noir', by: 'Barbara · 1970', tag: 'Le souvenir qui revient la nuit', color: '#3a3a44',
    desc: 'Un récit onirique dont on comprend très vite qu\'il cache autre chose, dit sans jamais le nommer. Le morceau est lent, magnifique, et laisse une gêne durable.',
    t: { emp: 0.9, vis: 0.9, ide: 0.8, ind: 0.85, tmp: 0.8, inc: 0.85, san: 0.4, soc: 0.1, com: 0.1, aff: 0.25 } },
  { name: 'Survivor', by: 'Destiny\'s Child · 2001', tag: 'Continuer sans toi', color: '#b5179e',
    desc: 'Un morceau écrit en réponse aux moqueries, qui énumère tout ce qu\'elles vont faire malgré tout. L\'énergie est collective, affirmée, et la réponse est adressée directement.',
    t: { det: 0.95, ind: 0.9, col: 0.85, com: 0.85, vac: 0.9, dom: 0.85, opt: 0.8, cmp: 0.9, thr: 0.15, dip: 0.2 } },
  { name: 'Comme d\'habitude', by: 'Claude François · 1967', tag: 'La routine qui s\'effrite', color: '#7d7368',
    desc: 'Une journée ordinaire décrite dans le détail, dans un couple qui n\'existe déjà plus. Le morceau est répétitif exprès, et sa mélancolie tient entièrement dans cette répétition.',
    t: { ste: 0.9, opn: 0.9, vis: 0.85, emp: 0.85, vco: 0.8, att: 0.85, vst: 0.05, chg: 0.05, aud: 0.1, opt: 0.15 } },
  { name: 'Radioactive', by: 'Imagine Dragons · 2012', tag: 'Le réveil après la catastrophe', color: '#8a9a5b',
    desc: 'Des basses lourdes, une batterie martiale, et l\'idée qu\'un monde nouveau commence dans les ruines de l\'ancien. Le morceau est sombre et énergique à la fois.',
    t: { chg: 0.9, det: 0.9, com: 0.85, vis: 0.8, aud: 0.85, eng: 0.8, ste: 0.15, dip: 0.2, opt: 0.45, cfl: 0.8 } },
  { name: 'Petit Pays', by: 'Gaël Faye · 2013', tag: 'L\'exil et la mémoire', color: '#a97142',
    desc: 'Un homme raconte un pays qu\'il a dû quitter, avec tendresse et sans nostalgie complaisante. Le morceau est posé, précis, et porte une douleur qui ne demande rien à personne.',
    t: { att: 0.95, vtr: 0.9, emp: 0.9, vis: 0.7, tmp: 0.85, ide: 0.85, care: 0.85, san: 0.7, com: 0.2, vpo: 0.05 } },
  { name: 'Thriller', by: 'Michael Jackson · 1982', tag: 'Le spectacle total', color: '#b3001b',
    desc: 'Un morceau conçu comme un film, avec une introduction, une narration et une chorégraphie que le monde entier connaît. L\'ambition de la production dépasse largement la chanson.',
    t: { inf: 0.95, vac: 0.95, soc: 0.9, ord: 0.9, rig: 0.9, aud: 0.9, vst: 0.85, dom: 0.8, ste: 0.15, vco: 0.2 } },
];

window.PRISME_MUSICS = { MUSICS };
