/* ============================================================
   PRISME — « Si tu étais un objet du quotidien »
   ------------------------------------------------------------
   L'objet dont le caractère ressemble au tien : celui qu'on utilise
   tous les jours sans y penser, celui qu'on ne trouve jamais quand on
   en a besoin, celui qui dépanne tout le monde, celui qu'on ne prête
   à personne. Des faits exacts, de la tendresse, un peu d'humour.
     name = l'objet, by = pièce de la maison · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const OBJECTS = [
  { name: 'Le couteau suisse', by: 'Poche · 1891', tag: 'Prêt à tout, seul dans sa poche', color: '#c8102e',
    desc: 'Livré à l\'armée suisse en 1891, il cache une lame, des ciseaux, un tournevis et parfois une loupe dans quelques centimètres. On le sort pour tout, on ne le prête pour rien. C\'est le tempérament des débrouillards autonomes, qui préfèrent se sortir seuls d\'affaire et trouvent qu\'un bon plan tient toujours dans une poche.',
    t: { ind: 0.9, san: 0.85, vsd: 0.9, inc: 0.8, dog: 0.1, vco: 0.2, auth: 0.25, loc: 0.1, rsk: 0.7, ouv: 0.8 } },
  { name: 'La cafetière italienne', by: 'Cuisine · 1933', tag: 'Le rituel avant tout', color: '#6b4a3a',
    desc: 'Inventée par Alfonso Bialetti en 1933, elle n\'a presque pas changé depuis, et c\'est tant mieux. Elle chauffe tranquillement, gargouille quand c\'est prêt et remplit la cuisine d\'une odeur de dimanche. C\'est le tempérament des amoureux des rituels, qui aiment les gestes transmis, les matins sans surprise et le plaisir qui se mérite.',
    t: { vtr: 0.95, ste: 0.85, rig: 0.7, vst: 0.15, chg: 0.1, opn: 0.8, att: 0.75, inc: 0.3, aud: 0.2, vhe: 0.75 } },
  { name: 'La bouilloire', by: 'Cuisine · prête en deux minutes', tag: 'Monte vite, redescend aussi vite', color: '#d9a441',
    desc: 'Elle monte en température en deux minutes, s\'agite, fait savoir bruyamment qu\'elle est prête, puis s\'arrête net et redevient toute calme. Et tout ce qu\'elle chauffe, c\'est pour le thé des autres. C\'est le tempérament des cœurs chauds et expressifs, qui s\'emportent vite, disent ce qu\'ils ressentent et pardonnent avant qu\'on ait fini de s\'excuser.',
    t: { vbe: 0.9, care: 0.9, emp: 0.85, ste: 0.2, inf: 0.75, att: 0.85, vpo: 0.1, cmp: 0.1, rig: 0.3, com: 0.75, aff: 0.15 } },
  { name: 'Le grille-pain', by: 'Cuisine · éjection automatique depuis 1919', tag: 'Toujours à deux doigts de sauter', color: '#e07b39',
    desc: 'Le modèle qui éjecte les tartines tout seul date de 1919, et depuis, il fait sursauter tout le monde au petit-déjeuner. Il chauffe fort, brûle parfois, et n\'a jamais vraiment su attendre. C\'est le tempérament des spontanés pétillants, qui vivent dans l\'instant, aiment les surprises et préfèrent une tartine un peu trop grillée à une matinée sans relief.',
    t: { vst: 0.85, inf: 0.85, ste: 0.15, ord: 0.2, tmp: 0.1, rsk: 0.7, rig: 0.2, vhe: 0.8, san: 0.2, aud: 0.75 } },
  { name: 'Le micro-ondes', by: 'Cuisine · vers 1945', tag: 'Efficace, bip, suivant', color: '#8a9199',
    desc: 'Découvert presque par hasard par Percy Spencer vers 1945, quand une barre chocolatée a fondu dans sa poche près d\'un radar. Il ne fait ni dans la tradition ni dans la poésie : il réchauffe, bippe trois fois et passe à la suite. C\'est le tempérament des pragmatiques pressés, qui veulent que ça marche tout de suite et laissent les recettes de grand-mère aux autres.',
    t: { vtr: 0.05, tmp: 0.05, epi: 0.05, aff: 0.8, rig: 0.3, vac: 0.8, ide: 0.1, vhe: 0.6, chg: 0.75, ste: 0.2 } },
  { name: 'Le tire-bouchon', by: 'Tiroir · premier brevet en 1795', tag: 'Celui qui lance la soirée', color: '#7b1e3a',
    desc: 'Son premier brevet anglais date de 1795, et depuis, aucune fête digne de ce nom n\'a commencé sans lui. Il reste au fond du tiroir toute la semaine et devient la star du samedi soir. C\'est le tempérament des bons vivants, qui ouvrent les soirées, remplissent les verres et trouvent que la vie est trop courte pour les apéritifs sans rallonge.',
    t: { soc: 0.95, vhe: 0.95, inf: 0.9, vse: 0.15, rig: 0.15, vco: 0.2, tmp: 0.1, col: 0.75, att: 0.7, con: 0.1 } },
  { name: 'L\'ouvre-boîte', by: 'Cuisine · breveté en 1858', tag: 'Il ouvre les cœurs les plus fermés', color: '#9aa5ad',
    desc: 'La boîte de conserve existait depuis près d\'un demi-siècle quand l\'ouvre-boîte a été breveté, en 1858 : avant, on se débrouillait au marteau et au burin. Lui avance tranquillement, cran par cran, jusqu\'à ce que le couvercle cède. C\'est le tempérament des patients qui savent ouvrir les gens fermés, sans forcer, avec douceur et une obstination tranquille.',
    t: { det: 0.9, ste: 0.85, dip: 0.8, vst: 0.2, inf: 0.15, aud: 0.3, vpo: 0.1, loc: 0.3, tmp: 0.8, vac: 0.3 } },
  { name: 'La passoire', by: 'Cuisine · pleine de trous, sans regret', tag: 'Ce qui doit passer passe', color: '#b8c4c9',
    desc: 'Elle laisse filer l\'eau, garde les pâtes, et ne s\'inquiète jamais de ce qui passe à travers. On lui reproche parfois sa mémoire, mais elle retient exactement ce qui compte. C\'est le tempérament des détendus chroniques, qui ne s\'encombrent ni des détails ni des soucis, oublient les rancunes et vivent très bien avec quelques trous dans le planning.',
    t: { vig: 0.05, thr: 0.05, rig: 0.1, ord: 0.15, san: 0.85, inc: 0.85, con: 0.1, tmp: 0.15, opt: 0.85, dog: 0.05 } },
  { name: 'La boîte Tupperware sans couvercle', by: 'Placard · depuis 1946', tag: 'Toujours à la recherche de sa moitié', color: '#5fb3a1',
    desc: 'Lancées par Earl Tupper en 1946, ces boîtes vont par deux, et pourtant il y en a toujours une qui a perdu sa moitié. Elle attend au fond du placard, pleine d\'espoir, persuadée que le bon couvercle finira par revenir. C\'est le tempérament des sentimentaux fidèles, qui ne se sentent entiers qu\'à deux et laissent souvent le hasard décider des rencontres.',
    t: { att: 0.95, loc: 0.9, ind: 0.1, san: 0.2, opt: 0.3, vis: 0.7, ord: 0.2, lea: 0.1, vbe: 0.85, dom: 0.1 } },
  { name: 'L\'éponge', by: 'Évier · toujours à disposition', tag: 'Elle absorbe tout, même les émotions', color: '#f2c94c',
    desc: 'Elle absorbe tout : l\'eau, la sauce, le café renversé, et un peu l\'humeur de la cuisine. Elle rend service sans jamais se plaindre, quitte à finir un peu fatiguée. C\'est le tempérament des hypersensibles généreux, qui ressentent tout ce que ressentent les autres, évitent les disputes et ont parfois besoin qu\'on les essore gentiment.',
    t: { emp: 0.98, care: 0.95, cfl: 0.05, dom: 0.05, com: 0.1, ind: 0.15, thr: 0.75, vbe: 0.9, cmp: 0.05, aff: 0.1 } },
  { name: 'Le balai', by: 'Placard · un geste vieux comme le monde', tag: 'Il fait place nette, sans discours', color: '#a67c52',
    desc: 'Il ne connaît ni les applis ni les batteries : juste un manche, des poils et un geste qui n\'a pas changé depuis des siècles. Il passe derrière tout le monde, sans bruit, et laisse la place nette. C\'est le tempérament des travailleurs fiables et modestes, attachés aux règles et aux bonnes habitudes, qui pensent qu\'une maison tenue, c\'est déjà une forme de respect.',
    t: { con: 0.85, ord: 0.9, vtr: 0.8, vco: 0.85, vst: 0.1, inf: 0.1, ide: 0.15, fia: 0.9, vpo: 0.1, auth: 0.7 } },
  { name: 'L\'aspirateur robot', by: 'Salon · depuis 2002', tag: 'Il se cogne et repart, toujours', color: '#3d4451',
    desc: 'Le premier Roomba est sorti en 2002, et ses descendants n\'ont toujours pas compris le pied de la chaise. Il se cogne, recule, repart, et finit par tout faire, seul, pendant que tout le monde est dehors. C\'est le tempérament des obstinés autonomes, qui n\'ont besoin ni d\'aide ni d\'encouragements et gardent un optimisme presque mécanique face aux obstacles.',
    t: { det: 0.95, ind: 0.85, soc: 0.1, att: 0.15, opt: 0.85, loc: 0.1, san: 0.9, emp: 0.15, dip: 0.2, rsk: 0.6 } },
  { name: 'Le fer à repasser', by: 'Buanderie · réglé sur coton', tag: 'Pas un pli ne lui échappe', color: '#4a6fa5',
    desc: 'Il ne supporte pas un pli, ni sur une chemise ni ailleurs. Il chauffe, il insiste, et il repasse jusqu\'à ce que tout soit impeccable, même les torchons. C\'est le tempérament des perfectionnistes exigeants, qui ont une idée précise de la façon dont les choses doivent être faites et ont bien du mal à laisser une approximation tranquille.',
    t: { rig: 0.98, con: 0.95, vco: 0.8, inc: 0.05, vhe: 0.1, ord: 0.95, dog: 0.75, lib: 0.2, vac: 0.8, cfl: 0.6 } },
  { name: 'Le parapluie', by: 'Entrée · au cas où', tag: 'Toujours prêt pour l\'averse', color: '#2f4858',
    desc: 'Il reste des semaines dans l\'entrée sans servir, et le seul jour où on l\'oublie, il pleut. Il ne demande qu\'à protéger, quitte à se retourner dans le vent. C\'est le tempérament des prévoyants protecteurs, qui pensent au pire pour que les autres n\'aient pas à le faire et préfèrent emporter une précaution de trop qu\'une de moins.',
    t: { vig: 0.95, vse: 0.95, thr: 0.85, care: 0.85, rsk: 0.05, opt: 0.2, tmp: 0.85, vbe: 0.8, aud: 0.1, vst: 0.1 } },
  { name: 'Le trousseau de clés', by: 'Entrée · une clé pour chaque porte', tag: 'Qui le tient décide qui entre', color: '#b08d57',
    desc: 'Il ouvre la maison, la voiture, la cave, le bureau et une petite clé dont plus personne ne connaît la serrure. Qui le tient décide qui entre. C\'est le tempérament des gardiens responsables, qui aiment avoir les choses en main, veillent sur le groupe et assument sans hésiter le poids de décider pour tout le monde.',
    t: { lea: 0.9, vpo: 0.8, auth: 0.85, dom: 0.8, vse: 0.8, loy: 0.8, col: 0.7, vst: 0.2, lib: 0.25, inc: 0.2, ide: 0.2 } },
  { name: 'Le chargeur de téléphone', by: 'Table de nuit · jamais rendu', tag: 'Il recharge tout le monde', color: '#f5f5f0',
    desc: 'Tout le monde le cherche, tout le monde l\'emprunte, et personne ne le rend jamais. Il passe ses nuits à redonner de l\'énergie aux autres, branché au même endroit, sans rien réclamer. C\'est le tempérament des dévoués fiables, qui rechargent leur entourage, ne comptent pas ce qu\'ils donnent et oublient parfois de se garder un peu de batterie.',
    t: { vbe: 0.95, care: 0.9, fia: 0.9, vpo: 0.05, vac: 0.2, ind: 0.1, ste: 0.8, dom: 0.1, cmp: 0.05, col: 0.85 } },
  { name: 'La multiprise', by: 'Salon · six prises, zéro exclusion', tag: 'Il y a de la place pour tout le monde', color: '#f28c28',
    desc: 'Une seule prise dans le mur, et grâce à elle, six appareils peuvent vivre ensemble. Elle accueille tout le monde, quitte à frôler la surchauffe les soirs de fête. C\'est le tempérament des rassembleurs, qui présentent les gens entre eux, ne laissent personne sans place et sont au centre de tous les réseaux sans jamais s\'en vanter.',
    t: { soc: 0.95, col: 0.95, inf: 0.85, dip: 0.85, ind: 0.1, vsd: 0.2, rsk: 0.6, vig: 0.2, cfl: 0.15, att: 0.8 } },
  { name: 'La télécommande', by: 'Canapé · depuis les années 1950', tag: 'Le pouvoir, sans se lever', color: '#1f1f24',
    desc: 'Les premières sont apparues dans les années 1950, et depuis, elles déclenchent plus de disputes que les programmes eux-mêmes. Elle a tout le pouvoir, disparaît dans les coussins et ne quitte jamais le canapé. C\'est le tempérament des commandants de salon, qui aiment décider sans se lever et savent parfaitement ce qu\'ils veulent, surtout si c\'est confortable.',
    t: { dom: 0.9, vpo: 0.9, vhe: 0.9, det: 0.2, vac: 0.15, care: 0.2, vbe: 0.3, ide: 0.1, rsk: 0.2, eng: 0.05 } },
  { name: 'Le rouleau de scotch', by: 'Tiroir · depuis 1930', tag: 'Impossible d\'en trouver le bout', color: '#e8e2c8',
    desc: 'Inventé par Richard Drew chez 3M en 1930, il tient tout ce qu\'on lui confie. Le problème, c\'est de trouver le bout : on tourne, on gratte, on cherche, et il ne se laisse pas faire. C\'est le tempérament des mystérieux loyaux, discrets et méfiants au premier abord, mais qui, une fois qu\'on a trouvé le fil, ne vous lâchent plus jamais.',
    t: { nat: 0.9, inf: 0.05, soc: 0.2, loy: 0.9, att: 0.8, ouv: 0.25, vig: 0.8, dip: 0.3, ste: 0.75, vst: 0.2 } },
  { name: 'Le post-it', by: 'Bureau · depuis 1980', tag: 'Une idée, un post-it', color: '#ffe94d',
    desc: 'Né d\'une colle ratée qui ne collait pas assez, commercialisé par 3M en 1980, il a colonisé les frigos, les écrans et les bords de miroir. Une idée, un post-it ; dix idées, un mur entier. C\'est le tempérament des créatifs en effervescence, qui pensent en couleurs, notent tout sur le moment et trouvent que le désordre, c\'est de l\'inspiration en attente.',
    t: { ide: 0.9, inc: 0.8, vst: 0.85, ord: 0.25, tmp: 0.2, rig: 0.25, inf: 0.75, vtr: 0.15, dog: 0.1, chg: 0.8 } },
  { name: 'L\'agrafeuse', by: 'Bureau · pas de négociation', tag: 'Clac, et c\'est réglé', color: '#b3202a',
    desc: 'Clac. Elle ne discute pas, elle tranche, et ce qui est agrafé reste agrafé. Elle se bloque parfois, mais jamais longtemps, et elle n\'aime pas beaucoup qu\'on remette ses décisions en question. C\'est le tempérament des autoritaires francs, qui disent les choses sans détour, tiennent le cap fermement et ne s\'embarrassent pas des longues réunions.',
    t: { auth: 0.9, com: 0.9, cfl: 0.9, dom: 0.85, dip: 0.1, emp: 0.2, ste: 0.3, dog: 0.75, ord: 0.8, inc: 0.15 } },
  { name: 'Le trombone', by: 'Bureau · fin du XIXe siècle', tag: 'Il attache sans jamais blesser', color: '#a9b4c2',
    desc: 'Sa forme classique à double boucle date de la fin du XIXe siècle, et on ne l\'a jamais vraiment améliorée. Il attache sans percer, se déplie pour débloquer un tiroir ou éjecter une carte SIM, et reprend sa place sans histoire. C\'est le tempérament des diplomates souples, qui relient les gens sans les froisser et savent se tordre un peu pour arranger tout le monde.',
    t: { dip: 0.95, cfl: 0.05, dom: 0.1, ouv: 0.8, inc: 0.8, dog: 0.05, ind: 0.6, vpo: 0.1, ste: 0.8, com: 0.1 } },
  { name: 'Le stylo quatre couleurs', by: 'Trousse · 1970', tag: 'Une couleur pour chaque chose', color: '#2a6fdb',
    desc: 'Le célèbre modèle de Bic est sorti en 1970, et il reste le rêve de tous les écoliers : le bleu pour le cours, le rouge pour les titres, le vert pour les exemples. On passe autant de temps à changer de couleur qu\'à écrire. C\'est le tempérament des enthousiastes organisés, qui adorent les systèmes, les options et le petit clic d\'une journée bien rangée.',
    t: { vst: 0.85, inf: 0.8, ord: 0.85, con: 0.75, vhe: 0.75, san: 0.3, vpo: 0.2, dog: 0.2, aff: 0.35, tmp: 0.3 } },
  { name: 'La gomme', by: 'Trousse · 1770', tag: 'Tout le monde a droit à une deuxième chance', color: '#f4a6b8',
    desc: 'En 1770, le chimiste Joseph Priestley remarque qu\'un morceau de caoutchouc efface le crayon, et offre aux écoliers leur meilleure alliée. Elle rattrape les erreurs des autres en s\'usant un peu à chaque fois. C\'est le tempérament des cœurs indulgents, qui croient aux deuxièmes chances, ne gardent pas de rancune et pensent que presque tout peut se rattraper.',
    t: { care: 0.9, dog: 0.05, nat: 0.05, fair: 0.85, opt: 0.9, vis: 0.05, cmp: 0.1, vpo: 0.05, loc: 0.2, cfl: 0.1 } },
  { name: 'La calculatrice', by: 'Bureau · Pascal, 1642', tag: 'Deux et deux font quatre, point', color: '#44505c',
    desc: 'Blaise Pascal en a construit une, mécanique, en 1642, pour aider son père à faire les comptes des impôts. Depuis, elle n\'a jamais eu d\'état d\'âme : deux et deux font quatre, que ça plaise ou non. C\'est le tempérament des esprits rationnels, qui décident avec des chiffres, se méfient des élans du cœur et ont souvent raison, même quand ce n\'est pas agréable à entendre.',
    t: { aff: 0.98, rig: 0.95, emp: 0.1, att: 0.1, ide: 0.1, sanc: 0.05, epi: 0.05, con: 0.9, san: 0.9, vhe: 0.2 } },
  { name: 'Le calendrier', by: 'Cuisine · 365 cases à remplir', tag: 'Il sait déjà ce qui arrive', color: '#d4543c',
    desc: 'Accroché au mur de la cuisine, il connaît les anniversaires, les vacances, les rendez-vous chez le dentiste et le jour des poubelles. Il voit les semaines arriver avant tout le monde. C\'est le tempérament des planificateurs fiables, qui anticipent, respectent les dates et les traditions, et dorment mieux quand le mois prochain est déjà bien rempli.',
    t: { tmp: 0.95, ord: 0.95, con: 0.85, vst: 0.15, inc: 0.1, fia: 0.9, vtr: 0.7, rsk: 0.15, aud: 0.1, vse: 0.8 } },
  { name: 'Le réveil', by: 'Table de nuit · depuis 1787', tag: 'Personne ne l\'aime, tout le monde en a besoin', color: '#c0392b',
    desc: 'En 1787, l\'Américain Levi Hutchins s\'est fabriqué un réveil qui ne sonnait qu\'à quatre heures du matin, son heure de lever. Depuis, le réveil reste l\'objet le plus détesté de la maison, et le plus indispensable. C\'est le tempérament des francs et ponctuels, qui disent ce qu\'il faut entendre plutôt que ce qu\'on voudrait entendre, et tant pis pour leur popularité.',
    t: { com: 0.95, cfl: 0.9, fia: 0.95, dip: 0.1, soc: 0.3, vhe: 0.05, det: 0.9, emp: 0.2, ord: 0.85, auth: 0.7 } },
  { name: 'L\'oreiller', by: 'Chambre · muet comme une tombe', tag: 'Le confident des nuits blanches', color: '#dfe6f0',
    desc: 'Il entend les soupirs, les larmes et les grandes idées de trois heures du matin, et il ne répète jamais rien. Il se laisse retourner, cabosser, écraser, et reste doux quand même. C\'est le tempérament des confidents rêveurs, calmes et patients, qui écoutent plus qu\'ils ne parlent et gardent les secrets comme on garde un trésor.',
    t: { emp: 0.9, ste: 0.95, dom: 0.05, com: 0.05, vst: 0.1, vac: 0.1, ide: 0.8, att: 0.85, soc: 0.3, aud: 0.1 } },
  { name: 'La couette', by: 'Chambre · réglée sur dimanche', tag: 'Encore cinq minutes', color: '#e9dcc9',
    desc: 'Le matin, elle retient tout le monde, et avec beaucoup de succès. Elle ne propose ni défi ni aventure, seulement de la chaleur, du moelleux et cinq minutes de plus. C\'est le tempérament des amoureux du confort, qui savourent les plaisirs simples, se méfient des réveils ambitieux et trouvent que le bonheur ressemble souvent à un dimanche matin.',
    t: { vhe: 0.95, vse: 0.85, rsk: 0.05, vst: 0.1, det: 0.15, vac: 0.05, att: 0.85, opn: 0.75, chg: 0.1, aud: 0.05 } },
  { name: 'La bouillotte', by: 'Lit · brevetée en 1903', tag: 'La chaleur à l\'ancienne', color: '#c4553a',
    desc: 'La version en caoutchouc a été brevetée en 1903 par l\'inventeur croate Eduard Penkala, et tous les radiateurs du monde ne l\'ont jamais détrônée. Elle ne fait rien de spectaculaire : elle garde la chaleur et la rend doucement, toute la nuit. C\'est le tempérament des tendres à l\'ancienne, fidèles aux remèdes de grand-mère, qui réchauffent sans bruit.',
    t: { att: 0.95, care: 0.9, vtr: 0.9, inf: 0.1, vst: 0.1, chg: 0.05, ste: 0.9, vpo: 0.05, ouv: 0.35, opt: 0.75 } },
  { name: 'Le plaid', by: 'Canapé · à tout le monde', tag: 'Assez grand pour tout le monde', color: '#9c6b5a',
    desc: 'Il traîne sur le canapé, et dès qu\'on s\'assoit à plusieurs, il s\'étire pour couvrir tout le monde. Personne ne sait vraiment à qui il appartient, et c\'est très bien comme ça. C\'est le tempérament des partageurs chaleureux, qui pensent en groupe, veillent à ce que chacun ait sa part et font de n\'importe quel salon un endroit où il fait bon rester.',
    t: { col: 0.95, fair: 0.85, loy: 0.8, cmp: 0.05, vbe: 0.9, vhe: 0.8, cfl: 0.1, ind: 0.1, rig: 0.15, vpo: 0.1 } },
  { name: 'La bougie parfumée', by: 'Salon · figue ou bois de santal', tag: 'Elle crée l\'ambiance', color: '#c9a0dc',
    desc: 'Elle ne sert à rien d\'indispensable, et pourtant, allumée, elle change toute la pièce : la lumière baisse, le temps ralentit, et ça sent le bois ou la figue. Elle se consume doucement pour une belle soirée. C\'est le tempérament des esthètes sensibles, qui soignent les ambiances, croient à la magie des petits riens et savent transformer un soir ordinaire en moment.',
    t: { vhe: 0.9, sanc: 0.85, ide: 0.85, aff: 0.1, rig: 0.15, vac: 0.15, inf: 0.6, ste: 0.75, vpo: 0.1, epi: 0.6 } },
  { name: 'La lampe de chevet', by: 'Chambre · une lumière pour un seul', tag: 'Juste un chapitre de plus', color: '#f0c36d',
    desc: 'Elle ne s\'allume que pour un seul lecteur, à une heure où tout le monde dort, et éclaire juste ce qu\'il faut de page. Elle a assisté à des milliers de chapitres « encore un, le dernier ». C\'est le tempérament des introvertis curieux, qui préfèrent un bon livre à une grande soirée et cultivent un monde intérieur bien plus vaste qu\'on ne le croit.',
    t: { soc: 0.1, inf: 0.1, ouv: 0.9, aff: 0.75, ste: 0.85, vst: 0.3, ide: 0.7, vpo: 0.05, inc: 0.7, dom: 0.15 } },
  { name: 'Le miroir', by: 'Salle de bain · sans filtre', tag: 'Il ne ment jamais, même le matin', color: '#bcd4e6',
    desc: 'Il dit la vérité, rien que la vérité, surtout le matin. Il renvoie exactement ce qu\'on lui montre, sans flatterie ni pitié, et adore qu\'on le regarde. C\'est le tempérament des francs ambitieux, qui soignent leur image, disent ce qu\'ils voient sans enrober, et aiment autant gagner que se voir gagner.',
    t: { com: 0.95, vpo: 0.85, vac: 0.9, inf: 0.8, dip: 0.1, care: 0.25, emp: 0.25, dom: 0.75, cmp: 0.9, vbe: 0.3 } },
  { name: 'La brosse à dents', by: 'Salle de bain · en nylon depuis 1938', tag: 'Deux fois par jour, sans exception', color: '#4fc3c8',
    desc: 'Deux fois par jour, deux minutes, sans exception. La brosse à poils de nylon est apparue en 1938, et depuis, elle n\'a jamais manqué un rendez-vous. C\'est le tempérament des disciplinés sereins, qui aiment les routines propres et nettes, suivent les recommandations à la lettre et trouvent une vraie satisfaction dans les bonnes habitudes.',
    t: { sanc: 0.9, fia: 0.95, ord: 0.95, vco: 0.9, vst: 0.05, rsk: 0.05, lib: 0.15, vse: 0.85, san: 0.8, thr: 0.3 } },
  { name: 'Le sèche-cheveux', by: 'Salle de bain · depuis 1890', tag: 'Il arrive en tempête', color: '#e84a8a',
    desc: 'Le Français Alexandre Godefroy en a conçu un premier modèle pour son salon de coiffure en 1890, et il n\'a jamais appris à être discret. Il souffle fort, chauffe vite et prend toute la place dans la salle de bain. C\'est le tempérament des tempêtes joyeuses, énergiques et démonstratives, qui arrivent en trombe et laissent tout le monde un peu décoiffé.',
    t: { inf: 0.95, dom: 0.85, vst: 0.85, ste: 0.05, tmp: 0.1, san: 0.15, vpo: 0.75, rig: 0.2, vhe: 0.8, aud: 0.8 } },
  { name: 'La pince à épiler', by: 'Salle de bain · au dixième de millimètre', tag: 'Rien ne lui échappe', color: '#c9ccd1',
    desc: 'Elle voit le détail que personne ne voit, et elle ne le laisse pas passer. Précise au dixième de millimètre, elle pique un peu, mais c\'est pour la bonne cause. C\'est le tempérament des observateurs pointilleux, lucides et un rien piquants, qui repèrent l\'erreur dans le tableau, la faute dans le texte, et le disent.',
    t: { rig: 0.98, vig: 0.9, com: 0.8, emp: 0.2, inc: 0.1, soc: 0.2, aff: 0.85, care: 0.3, vhe: 0.15, dip: 0.25 } },
  { name: 'Le coupe-ongles', by: 'Salle de bain · sans retour', tag: 'Clic, et on passe à autre chose', color: '#7d8a96',
    desc: 'Il ne négocie pas, il coupe, net et sans retour. Un petit clic et c\'est fini, place à ce qui repousse. C\'est le tempérament des tranchants décidés, qui savent mettre fin à ce qui a trop duré, n\'ont pas peur des ruptures et préfèrent un changement franc à une situation qui traîne en longueur.',
    t: { com: 0.9, cfl: 0.9, det: 0.85, san: 0.8, dip: 0.15, att: 0.15, rsk: 0.75, chg: 0.95, ste: 0.2, vtr: 0.1 } },
  { name: 'La trousse de secours', by: 'Placard · complète et rangée', tag: 'Là quand ça fait mal', color: '#d62828',
    desc: 'On l\'oublie au fond du placard jusqu\'au jour où quelqu\'un se coupe, et alors elle est là, complète, rangée, prête. Pansements, compresses, désinfectant : elle a pensé à tout avant tout le monde. C\'est le tempérament des soignants calmes, qui gardent la tête froide quand ça saigne et n\'ont besoin de personne pour savoir quoi faire.',
    t: { care: 0.98, san: 0.95, vig: 0.85, fia: 0.95, vbe: 0.9, vhe: 0.15, vst: 0.2, cmp: 0.05, thr: 0.7, inf: 0.2 } },
  { name: 'La lampe torche', by: 'Tiroir · depuis 1899', tag: 'Elle passe devant dans le noir', color: '#f7b32b',
    desc: 'Le premier brevet de lampe électrique portative date de 1899. Depuis, elle attend la panne de courant ou la nuit en forêt pour montrer ce qu\'elle vaut. Quand tout s\'éteint, c\'est elle qui passe devant. C\'est le tempérament des aventuriers courageux, qui prennent la tête dans l\'obscurité et avancent vers l\'inconnu avec une confiance contagieuse.',
    t: { aud: 0.9, lea: 0.9, san: 0.85, thr: 0.2, rsk: 0.8, vst: 0.8, opt: 0.8, vse: 0.2, dom: 0.75, inc: 0.8 } },
  { name: 'La boîte à outils', by: 'Garage · une réponse à tout', tag: 'Moins de théorie, plus de réparations', color: '#d64933',
    desc: 'Marteau, pinces, niveau, vis de toutes les tailles : elle a une réponse concrète à chaque problème, et aucune patience pour les grandes théories. Elle ne demande pas pourquoi ça fuit, elle répare. C\'est le tempérament des pragmatiques autonomes, les mains dans le concret, qui préfèrent faire plutôt que discuter et règlent les choses eux-mêmes.',
    t: { epi: 0.02, aff: 0.7, fia: 0.9, ind: 0.8, vsd: 0.85, ide: 0.2, sanc: 0.1, inf: 0.2, det: 0.85, ord: 0.8 } },
  { name: 'Le mètre ruban', by: 'Garage · breveté en 1868', tag: 'La même mesure pour tout le monde', color: '#f2c12e',
    desc: 'Breveté aux États-Unis en 1868, il mesure tout avec la même exactitude, qu\'on l\'aime ou non. Au moindre relâchement, il se rembobine d\'un coup sec, et gare aux doigts. C\'est le tempérament des justes exigeants, qui veulent que tout le monde soit traité selon la même règle et n\'acceptent pas qu\'on arrondisse à son avantage.',
    t: { fair: 0.98, rig: 0.9, con: 0.85, epi: 0.1, vig: 0.7, vhe: 0.2, cfl: 0.7, ide: 0.2, vpo: 0.1, cmp: 0.3 } },
  { name: 'Le tournevis', by: 'Garage · une tête, un but', tag: 'Un seul geste, jusqu\'au bout', color: '#e0a526',
    desc: 'Il fait une seule chose, et il la fait très bien : tourner, toujours dans le même sens, jusqu\'à ce que ce soit serré. Pas de gadget, pas de fioriture. C\'est le tempérament des persévérants loyaux, simples et entiers, qui ne se dispersent pas, restent fidèles à leur méthode et finissent toujours ce qu\'ils ont commencé.',
    t: { det: 0.95, loy: 0.9, fia: 0.9, ouv: 0.15, vst: 0.1, inc: 0.2, ide: 0.15, chg: 0.05, inf: 0.2, dog: 0.7 } },
  { name: 'La clé à molette', by: 'Garage · 1892', tag: 'Elle s\'adapte à tout le monde', color: '#6c7a89',
    desc: 'Le Suédois Johan Petter Johansson l\'a brevetée en 1892, et depuis elle s\'ajuste à tous les écrous, grands ou petits. Elle ne demande pas à la vis de changer : c\'est elle qui s\'adapte. C\'est le tempérament des souples solides, qui s\'accordent à toutes les situations et toutes les personnes, sans jamais perdre leur prise ni leur calme.',
    t: { dip: 0.9, inc: 0.9, dog: 0.05, san: 0.85, ste: 0.75, ouv: 0.85, loc: 0.3, vtr: 0.2, col: 0.7, care: 0.7, vsd: 0.3 } },
  { name: 'Le scotch double face', by: 'Tiroir · des deux côtés à la fois', tag: 'Invisible, mais tout tient grâce à lui', color: '#d8d2c4',
    desc: 'Il colle des deux côtés, et c\'est bien là tout son talent : relier deux choses qui ne se seraient jamais tenues seules, en restant parfaitement invisible entre les deux. C\'est le tempérament des médiateurs discrets, fidèles à tous leurs proches à la fois, qui tiennent les familles et les équipes ensemble sans jamais se mettre en avant.',
    t: { dip: 0.95, loy: 0.9, att: 0.9, cfl: 0.05, dom: 0.05, inf: 0.2, com: 0.1, vbe: 0.85, col: 0.8, ind: 0.15 } },
  { name: 'La colle forte', by: 'Tiroir · prise instantanée', tag: 'Une goutte, et c\'est pour la vie', color: '#e63946',
    desc: 'Une goutte suffit, et c\'est pour la vie. Elle ne connaît pas les demi-mesures, colle parfois les doigts qui l\'approchent de trop près, et ne lâche plus rien. C\'est le tempérament des fusionnels fidèles, qui s\'attachent pour de bon, ont un peu de mal avec l\'idée de laisser partir, et aiment avec une intensité qu\'on ne décolle pas.',
    t: { att: 0.98, loy: 0.98, lib: 0.1, ind: 0.05, vsd: 0.1, chg: 0.02, det: 0.9, inc: 0.1, dog: 0.7, vtr: 0.7 } },
  { name: 'Le casque audio', by: 'Sac · vers 1910', tag: 'Ne pas déranger, merci', color: '#2b2d42',
    desc: 'L\'Américain Nathaniel Baldwin a fabriqué l\'un des premiers casques d\'écoute sur sa table de cuisine, vers 1910. Aujourd\'hui, c\'est le panneau « ne pas déranger » le plus clair du monde. C\'est le tempérament des indépendants dans leur bulle, qui aiment leur propre bande-son, choisissent leurs moments de compagnie et n\'ont pas besoin du monde pour passer une bonne journée.',
    t: { soc: 0.05, ind: 0.95, vsd: 0.95, col: 0.1, vhe: 0.85, vst: 0.7, loy: 0.2, auth: 0.1, dip: 0.3, att: 0.2 } },
  { name: 'Les écouteurs', by: 'Poche · en nœud dans les trente secondes', tag: 'Emmêlés, mais jamais l\'un sans l\'autre', color: '#f8f9fa',
    desc: 'Ils vont par deux, s\'emmêlent en trente secondes dans une poche, et l\'un des deux finit toujours par disparaître. Mais tant qu\'ils sont ensemble, la musique est partout. C\'est le tempérament des joyeux désordonnés, sociables et un peu tête en l\'air, qui vivent au rythme du moment et comptent sur la vie pour démêler les nœuds.',
    t: { ord: 0.05, rig: 0.1, soc: 0.75, att: 0.85, vst: 0.8, con: 0.05, inf: 0.75, tmp: 0.1, loc: 0.8, rsk: 0.6 } },
  { name: 'Le carnet', by: 'Sac · des pages pleines de rêves', tag: 'Les idées que personne n\'a encore lues', color: '#8b5e3c',
    desc: 'Il reçoit les pensées qu\'on n\'ose dire à personne, les idées de roman, les listes de rêves et les dessins dans la marge. Il ne juge jamais et garde tout. C\'est le tempérament des rêveurs indépendants, qui ont besoin d\'écrire pour savoir ce qu\'ils pensent, cultivent leur imagination et préfèrent leur propre chemin aux sentiers tout tracés.',
    t: { ide: 0.95, ouv: 0.9, aff: 0.3, soc: 0.15, vsd: 0.85, sanc: 0.6, vac: 0.15, dom: 0.1, ind: 0.8, vco: 0.15 } },
  { name: 'L\'agenda papier', by: 'Sac · rempli au stylo', tag: 'Il a résisté à tous les smartphones', color: '#3f5e4a',
    desc: 'Il a résisté aux smartphones, au cloud et aux alarmes connectées, et il en est très fier. Tout y est écrit à la main, souligné, raturé, et il ne tombe jamais en panne de batterie. C\'est le tempérament des organisés fidèles aux anciennes méthodes, qui se méfient un peu des nouveautés et trouvent qu\'un stylo bien tenu vaut toutes les applis.',
    t: { vtr: 0.9, ord: 0.95, nat: 0.8, chg: 0.05, vst: 0.1, con: 0.85, opn: 0.85, tmp: 0.85, inc: 0.15, vis: 0.8 } },
  { name: 'Le sac cabas', by: 'Épaule · réutilisable à l\'infini', tag: 'Toujours de la place pour un peu plus', color: '#7fa66b',
    desc: 'Il porte les courses, les livres de la médiathèque, le pique-nique et les affaires de piscine des enfants des autres. Il remplace des centaines de sacs plastiques et ne s\'en vante pas. C\'est le tempérament des généreux engagés, qui pensent à la planète autant qu\'à leurs proches et ont toujours de la place pour porter un peu plus.',
    t: { vun: 0.95, care: 0.85, col: 0.8, vpo: 0.05, vac: 0.2, ord: 0.3, vbe: 0.85, fair: 0.85, rig: 0.25, soc: 0.75 } },
  { name: 'La gourde', by: 'Sac · zéro plastique', tag: 'Des convictions et des autocollants', color: '#2a9d8f',
    desc: 'Elle suit partout, au bureau, en randonnée, en réunion, et rappelle à tout le monde de boire de l\'eau. Elle a des principes, et des autocollants militants plein les flancs. C\'est le tempérament des convaincus disciplinés, qui mettent leurs actes en accord avec leurs idées, tiennent le cap sur la durée et n\'hésitent pas à montrer l\'exemple.',
    t: { vun: 0.95, eng: 0.95, epi: 0.85, det: 0.85, vhe: 0.2, tmp: 0.85, dog: 0.65, chg: 0.8, vtr: 0.15, vpo: 0.1 } },
  { name: 'Le thermos', by: 'Sac · depuis 1904', tag: 'Encore chaud des heures plus tard', color: '#5c7c8a',
    desc: 'James Dewar a inventé la bouteille isotherme en 1892, et la marque Thermos l\'a rendue populaire dès 1904. Des heures plus tard, le café est encore chaud : rien ne l\'ébranle. C\'est le tempérament des stables et des fidèles, qui gardent la même chaleur quelle que soit la météo et sur qui on peut compter longtemps après que les autres ont refroidi.',
    t: { ste: 0.98, fia: 0.95, loy: 0.9, vst: 0.05, inf: 0.1, chg: 0.05, tmp: 0.9, vhe: 0.3, aud: 0.15, san: 0.9 } },
  { name: 'La valise à roulettes', by: 'Couloir · roulettes depuis 1970', tag: 'La prochaine destination, c\'est quand ?', color: '#e76f51',
    desc: 'Bernard Sadow a eu l\'idée de mettre des roulettes sous une valise en 1970, après avoir traîné ses bagages dans un aéroport. Depuis, elle roule partout, d\'un continent à l\'autre, et ne tient pas en place. C\'est le tempérament des voyageurs curieux, ouverts au monde et aux changements, pour qui la meilleure destination est toujours la prochaine.',
    t: { opn: 0.02, vst: 0.95, ouv: 0.95, vtr: 0.1, vse: 0.15, rsk: 0.85, chg: 0.85, vun: 0.75, ind: 0.75, att: 0.3 } },
  { name: 'Le briquet', by: 'Poche · une étincelle suffit', tag: 'Il met le feu aux poudres', color: '#ff5400',
    desc: 'Une étincelle, et tout s\'allume. Il n\'attend pas la permission, se transmet de poche en poche et adore mettre le feu aux conversations trop sages. C\'est le tempérament des provocateurs audacieux, qui bousculent l\'ordre établi, prennent des risques pour faire bouger les choses et préfèrent une belle flamme à une longue attente.',
    t: { aud: 0.95, chg: 0.98, rsk: 0.95, eng: 0.85, san: 0.1, vse: 0.05, vco: 0.05, com: 0.85, auth: 0.05, cfl: 0.85 } },
  { name: 'La boussole', by: 'Sac à dos · plein nord', tag: 'Elle ne perd jamais le nord', color: '#1d4e89',
    desc: 'Elle indique toujours le nord, quel que soit le chemin qu\'on prend ou la tempête qu\'on traverse. Elle ne suit pas le groupe, elle suit ses principes. C\'est le tempérament des idéalistes droits, qui savent pourquoi ils se battent, tiennent à leurs valeurs contre vents et marées et aident les autres à retrouver le cap quand ils se perdent.',
    t: { epi: 0.9, dog: 0.8, det: 0.9, ide: 0.85, loc: 0.05, inc: 0.15, dip: 0.3, vun: 0.7, fair: 0.9, sanc: 0.7 } },
  { name: 'Le dé à coudre', by: 'Boîte à couture · depuis des siècles', tag: 'Petit, patient, indispensable', color: '#b8a07e',
    desc: 'Minuscule, il protège le doigt de la couturière depuis des siècles, point après point, ourlet après ourlet. Il ne cherche pas la lumière : il est là pour que le travail soit bien fait. C\'est le tempérament des artisans humbles, patients et soigneux, attachés aux savoir-faire transmis, qui trouvent leur fierté dans le travail bien fini plutôt que dans les applaudissements.',
    t: { vtr: 0.95, rig: 0.85, ste: 0.9, inf: 0.05, dom: 0.05, vpo: 0.02, vst: 0.1, aud: 0.1, vac: 0.2, con: 0.8 } },
  { name: 'L\'épingle à nourrice', by: 'Trousse · 1849', tag: 'La solution de dernière minute', color: '#9fa8b3',
    desc: 'Walter Hunt l\'a brevetée en 1849, puis a vendu son brevet quatre cents dollars pour rembourser une dette de quinze. Depuis, elle sauve des ourlets, des bretelles et des tenues de soirée à la dernière minute. C\'est le tempérament des débrouillards imperturbables, un peu punks, qui improvisent une solution avec presque rien et ne paniquent jamais.',
    t: { san: 0.95, inc: 0.9, loc: 0.15, ord: 0.1, rig: 0.15, epi: 0.05, lib: 0.85, auth: 0.15, vco: 0.1, care: 0.7 } },
  { name: 'Le cintre', by: 'Placard · toujours d\'aplomb', tag: 'Il porte les autres sans se montrer', color: '#c2b280',
    desc: 'Il passe sa vie dans le placard à porter les affaires des autres, bien droites, sans rien demander pour lui. Il ne prend presque pas de place, et pourtant tout s\'écroule sans lui. C\'est le tempérament des soutiens discrets, stables et ordonnés, qui portent leur entourage sans le dire et trouvent normal de s\'effacer derrière ceux qu\'ils aident.',
    t: { vbe: 0.85, ord: 0.85, vpo: 0.05, inf: 0.05, dom: 0.05, ste: 0.9, fia: 0.85, soc: 0.3, vac: 0.1, lea: 0.1 } },
  { name: 'Le porte-clés', by: 'Trousseau · souvenir de vacances', tag: 'Inutile, donc indispensable', color: '#ff7eb6',
    desc: 'Tour Eiffel miniature, peluche, décapsuleur ou souvenir de vacances : il ne sert à rien de pratique, et c\'est lui qu\'on remarque en premier. Il raconte une histoire à chaque personne qui le voit. C\'est le tempérament des joyeux fantaisistes, sociables et bavards, qui collectionnent les souvenirs et les anecdotes et mettent de la couleur partout où ils passent.',
    t: { inf: 0.9, vhe: 0.8, ide: 0.75, rig: 0.1, aff: 0.1, vac: 0.1, soc: 0.9, att: 0.8, epi: 0.2, san: 0.35 } },
  { name: 'La tasse préférée', by: 'Cuisine · un peu ébréchée', tag: 'Personne d\'autre n\'y touche', color: '#e9b44c',
    desc: 'Tout le monde sait qu\'il ne faut pas y toucher. Un peu ébréchée, un dessin à moitié effacé, elle est à une seule personne, et le café n\'a pas le même goût dans une autre. C\'est le tempérament des attachés territoriaux, fidèles à leurs habitudes et à leurs objets, qui défendent leur petit monde et n\'aiment pas trop qu\'on le dérange.',
    t: { att: 0.9, loy: 0.9, vtr: 0.85, cfl: 0.75, nat: 0.75, opn: 0.9, chg: 0.05, ouv: 0.2, vst: 0.1, col: 0.25 } },
  { name: 'La poêle antiadhésive', by: 'Cuisine · depuis 1956', tag: 'Rien ne lui accroche', color: '#3a3a3a',
    desc: 'Marc Grégoire a eu l\'idée d\'appliquer du téflon sur une poêle, et Tefal est né en 1956. Depuis, rien ne lui accroche : ni l\'omelette, ni les reproches, ni les mauvaises humeurs. C\'est le tempérament des résilients détachés, qui laissent glisser les critiques, ne s\'attardent pas sur les soucis et gardent un optimisme à toute épreuve.',
    t: { san: 0.95, thr: 0.05, att: 0.1, loy: 0.2, nat: 0.1, vis: 0.05, opt: 0.9, inc: 0.85, ste: 0.85, emp: 0.25 } },
  { name: 'La cocotte-minute', by: 'Cuisine · 1953', tag: 'Attention, ça monte en pression', color: '#a4161a',
    desc: 'SEB a lancé sa Super Cocotte en 1953, et elle a conquis les cuisines de France au son de son sifflement. Elle cuit vite et fort, mais il ne faut pas oublier de relâcher la pression. C\'est le tempérament des intenses efficaces, qui accumulent jusqu\'à ce que ça siffle, disent les choses avec force et obtiennent des résultats en un temps record.',
    t: { san: 0.05, com: 0.9, cfl: 0.9, det: 0.9, vac: 0.85, thr: 0.75, ste: 0.05, tmp: 0.2, dip: 0.15, inf: 0.7 } },
];

window.PRISME_OBJECTS = { OBJECTS };
