/* ============================================================
   PRISME — « Si tu étais un organe »
   ------------------------------------------------------------
   Ce qui compte, c'est le rôle de l'organe dans le corps : celui qui
   ne s'arrête jamais, celui qui filtre, celui qui décide, celui qui
   donne l'alerte, celui qu'on oublie jusqu'au jour où il manque.
   Des faits exacts, beaucoup de tendresse, rien d'inquiétant.
     name = l'organe, by = système · un détail, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const ORGANS = [
  { name: 'Le cœur', by: 'Circulation · 100 000 battements par jour', tag: 'Il ne s\'arrête jamais pour personne', color: '#c8323c',
    desc: 'Environ cent mille battements par jour et quelque sept mille litres de sang envoyés dans tout le corps, sans une seule pause depuis la naissance. On lui prête tous les sentiments, et il les mérite. C\'est le tempérament des passionnés fidèles, qui aiment sans calcul, s\'engagent pour de bon et laissent la raison attendre son tour.',
    t: { aff: 0.05, att: 0.95, emp: 0.9, vbe: 0.95, det: 0.85, loy: 0.9, ind: 0.2, cmp: 0.15, rig: 0.3, nat: 0.15 } },
  { name: 'Le cerveau', by: 'Système nerveux · 86 milliards de neurones', tag: 'Toujours une idée d\'avance', color: '#d98aa6',
    desc: 'Deux pour cent du poids du corps, mais environ vingt pour cent de son énergie : c\'est le plus gourmand des organes, et il ne dort jamais vraiment. Il relie, compare, imagine et invente sans arrêt. C\'est le caractère des esprits curieux et analytiques, qui ont besoin de comprendre avant d\'aimer et trouvent qu\'une question vaut souvent mieux qu\'une réponse.',
    t: { aff: 0.95, ouv: 0.95, ide: 0.85, inc: 0.8, vsd: 0.85, att: 0.25, vhe: 0.2, dog: 0.1, vtr: 0.15, soc: 0.35 } },
  { name: 'Le cervelet', by: 'Système nerveux · quatre neurones sur cinq', tag: 'La précision sans le bruit', color: '#8f7bb8',
    desc: 'Il n\'occupe qu\'un dixième du volume du cerveau mais abrite environ quatre neurones sur cinq. C\'est lui qui règle l\'équilibre, la coordination et tous les gestes qu\'on finit par faire sans y penser, du vélo au piano. C\'est le tempérament des perfectionnistes discrets, qui répètent jusqu\'à ce que ce soit juste et n\'ont aucun besoin qu\'on le remarque.',
    t: { rig: 0.95, con: 0.9, san: 0.85, inf: 0.05, vpo: 0.1, soc: 0.2, vst: 0.2, ord: 0.85, dom: 0.15, epi: 0.15 } },
  { name: 'L\'hippocampe', by: 'Système nerveux · le gardien des souvenirs', tag: 'Rien de ce qui compte ne se perd', color: '#6c9ab5',
    desc: 'Nommé ainsi au XVIe siècle pour sa forme de petit cheval de mer, il transforme les moments vécus en souvenirs durables. Chez les chauffeurs de taxi londoniens, qui apprennent des milliers de rues, une partie en est même plus développée. C\'est le tempérament des nostalgiques tendres, fidèles à leurs racines, qui gardent les lettres, les photos et les dates de chacun.',
    t: { vtr: 0.95, att: 0.9, loy: 0.85, chg: 0.05, vst: 0.15, opn: 0.8, vis: 0.7, aud: 0.15, tmp: 0.35, lib: 0.3 } },
  { name: 'L\'amygdale cérébrale', by: 'Système nerveux · l\'alarme en forme d\'amande', tag: 'Elle a vu le danger avant toi', color: '#b5452f',
    desc: 'Grosse comme une amande, elle repère une menace avant même qu\'on en ait conscience et déclenche l\'alerte en une fraction de seconde. Sans elle, nos ancêtres auraient serré la main de bien des lions. C\'est le tempérament des vigilants sensibles, qui sentent venir les ennuis de loin, dorment mieux avec un plan B et préfèrent une fausse alerte à une mauvaise surprise.',
    t: { thr: 0.95, vig: 0.95, san: 0.05, inc: 0.05, rsk: 0.05, opt: 0.15, vse: 0.95, aff: 0.15, nat: 0.8, vis: 0.8 } },
  { name: 'L\'hypothalamus', by: 'Système nerveux · quatre grammes de commandement', tag: 'Le chef d\'orchestre qu\'on ne voit pas', color: '#7a5c8e',
    desc: 'Il pèse à peine quatre grammes et règle pourtant la température, la faim, la soif et le sommeil, tout en donnant ses ordres à l\'hypophyse, qui les transmet aux autres glandes. Personne ne le connaît, tout le monde lui obéit. C\'est le caractère des dirigeants calmes et discrets, qui tiennent la maison sans élever la voix et préfèrent l\'équilibre aux coups d\'éclat.',
    t: { lea: 0.9, ste: 0.85, auth: 0.85, vse: 0.85, inf: 0.1, vst: 0.15, aud: 0.2, dip: 0.8, chg: 0.15, soc: 0.3 } },
  { name: 'Le cortex préfrontal', by: 'Système nerveux · le dernier à mûrir', tag: 'Celui qui dit « attends, réfléchis »', color: '#4f6d8f',
    desc: 'Juste derrière le front, il planifie, pèse le pour et le contre et retient la main qui allait cliquer sur « acheter ». Il est l\'une des dernières régions du cerveau à terminer sa maturation, vers vingt-cinq ans. C\'est le tempérament des sages prévoyants, qui pensent à demain, savent dire non à une envie et gardent la tête froide quand tout le monde s\'emballe.',
    t: { tmp: 0.98, san: 0.9, vhe: 0.05, vst: 0.15, ord: 0.9, rsk: 0.1, aff: 0.85, vac: 0.8, loc: 0.1, inf: 0.2 } },
  { name: 'La glande pinéale', by: 'Système nerveux · la gardienne de la nuit', tag: 'Rêveuse, mystérieuse, un peu mystique', color: '#3b3566',
    desc: 'Pas plus grosse qu\'un grain de riz, cachée au centre du cerveau, elle libère la mélatonine quand vient l\'obscurité et nous dit qu\'il est l\'heure de dormir. Descartes y voyait le siège de l\'âme. C\'est le tempérament des rêveurs et des chercheurs de sens, qui s\'animent la nuit, aiment les grandes questions et croient qu\'il existe quelque chose de plus grand que soi.',
    t: { sanc: 0.95, ide: 0.95, epi: 0.8, vtr: 0.7, soc: 0.1, vac: 0.1, vpo: 0.05, aff: 0.3, cmp: 0.1, inc: 0.7 } },
  { name: 'Les poumons', by: 'Respiration · 20 000 inspirations par jour', tag: 'Grand ouvert sur le monde', color: '#8fbfd9',
    desc: 'Environ vingt mille respirations par jour et des centaines de millions d\'alvéoles déployant la surface d\'un grand appartement. Le gauche est un peu plus petit que le droit, pour laisser de la place au cœur. C\'est le tempérament des gens ouverts et généreux, qui ont besoin d\'air, de grands espaces et de nouveaux horizons, et savent faire une place aux autres.',
    t: { ouv: 0.95, vun: 0.9, opn: 0.05, vst: 0.8, emp: 0.8, dog: 0.1, nat: 0.1, vse: 0.25, cmp: 0.15, ord: 0.3 } },
  { name: 'Le diaphragme', by: 'Respiration · le métronome du souffle', tag: 'Le rythme, sans y penser', color: '#b8a47e',
    desc: 'Ce grand muscle en forme de dôme se contracte à chaque inspiration, jour et nuit, sans qu\'on ait rien à lui demander, mais il accepte aussi qu\'on le prenne en main pour chanter ou souffler les bougies. C\'est le tempérament des gens réguliers et fiables, qui avancent à leur rythme, font les choses bien sans se faire remarquer et n\'ont pas besoin de nouveauté pour être heureux.',
    t: { fia: 0.95, ste: 0.9, ord: 0.85, vst: 0.05, ide: 0.15, vpo: 0.05, inf: 0.1, aud: 0.15, eng: 0.1, chg: 0.1 } },
  { name: 'Le foie', by: 'Digestion · des centaines de fonctions', tag: 'Il encaisse tout et repousse', color: '#8b3a3a',
    desc: 'Près d\'un kilo et demi, des centaines de fonctions, et un pouvoir rare : il peut se reconstituer à partir d\'un quart de lui-même. Les Grecs le savaient déjà, puisque celui de Prométhée repoussait chaque nuit. C\'est le tempérament des bons vivants increvables, qui encaissent sans se plaindre, se relèvent de tout et voient toujours le verre à moitié plein.',
    t: { opt: 0.95, det: 0.9, vhe: 0.85, vis: 0.05, thr: 0.1, loc: 0.1, vig: 0.15, soc: 0.8, rig: 0.25, san: 0.8 } },
  { name: 'Les reins', by: 'Filtration · 180 litres par jour', tag: 'Ne garder que ce qui est juste', color: '#a0522d',
    desc: 'Gros comme un poing, ils filtrent environ cent quatre-vingts litres de plasma par jour, rendent au corps presque tout et ne laissent partir que ce qui doit partir. Et on peut très bien vivre avec un seul. C\'est le tempérament des gens intègres et exigeants, qui trient le bon du mauvais, ne transigent pas avec leurs principes et se battent pour que les choses soient justes.',
    t: { fair: 0.95, sanc: 0.85, rig: 0.9, eng: 0.8, epi: 0.75, vhe: 0.15, inc: 0.2, dip: 0.25, vun: 0.8, soc: 0.3 } },
  { name: 'L\'estomac', by: 'Digestion · un acide redoutable', tag: 'Il ne recule devant aucun plat', color: '#e07a3f',
    desc: 'Son acide chlorhydrique est si fort qu\'il attaquerait certains métaux, et il se protège en renouvelant sa paroi en quelques jours. Il s\'étire pour accueillir un repas de fête et ne demande jamais la carte. Avoir de l\'estomac, c\'est oser. C\'est le tempérament des audacieux gourmands, qui parlent franchement, prennent les défis à bras-le-corps et vivent tout de suite.',
    t: { vhe: 0.95, aud: 0.9, com: 0.85, cfl: 0.85, tmp: 0.1, dip: 0.15, vig: 0.2, rig: 0.2, rsk: 0.85, vse: 0.2 } },
  { name: 'L\'intestin grêle', by: 'Digestion · plusieurs mètres de patience', tag: 'Rien ne presse, tout finit par passer', color: '#d9a08a',
    desc: 'Replié sur plusieurs mètres, il prend des heures pour absorber tranquillement presque tout ce que nous mangeons, sans jamais se presser ni se plaindre. C\'est là que se fait le vrai travail, loin des regards. C\'est le tempérament des patients inébranlables, qui avancent pas à pas, laissent le temps faire les choses et ne se laissent pas bousculer par l\'urgence des autres.',
    t: { ste: 0.98, tmp: 0.85, aud: 0.1, rsk: 0.1, vst: 0.1, inf: 0.1, cmp: 0.1, cfl: 0.1, vac: 0.2, thr: 0.2 } },
  { name: 'Le côlon et son microbiote', by: 'Digestion · des milliers de milliards d\'habitants', tag: 'Tout seul, on n\'est rien', color: '#6b8f4e',
    desc: 'Il héberge des dizaines de milliers de milliards de bactéries, à peu près autant que nous avons de cellules, et ces minuscules colocataires digèrent, protègent et influencent même notre humeur. C\'est le tempérament des êtres profondément collectifs, qui pensent en équipe, aiment les maisons pleines et savent que chacun compte dans la réussite de tous.',
    t: { col: 0.98, soc: 0.95, vun: 0.85, ind: 0.05, vsd: 0.15, cmp: 0.1, inf: 0.85, fair: 0.8, vpo: 0.1, opn: 0.2 } },
  { name: 'Le pancréas', by: 'Digestion et hormones · deux métiers à la fois', tag: 'L\'art du dosage juste', color: '#e8c07d',
    desc: 'D\'un côté il fabrique des enzymes digestives, de l\'autre ses petits îlots, à peine deux pour cent de sa masse, dosent l\'insuline et le glucagon pour que le sucre sanguin ne monte ni ne descende trop. C\'est le tempérament des équilibristes méticuleux, qui mènent deux vies de front, mesurent tout au gramme près et détestent l\'excès dans un sens comme dans l\'autre.',
    t: { rig: 0.9, dip: 0.85, fair: 0.9, rsk: 0.1, com: 0.15, epi: 0.15, aff: 0.8, cfl: 0.2, vhe: 0.3, vac: 0.75 } },
  { name: 'La rate', by: 'Défenses · filtre du sang', tag: 'On se la dilate avec plaisir', color: '#9c4f6e',
    desc: 'Elle recycle les globules rouges fatigués, garde des défenses en réserve, et on peut pourtant vivre sans elle. Personne ne sait vraiment où elle se trouve, et on ne parle d\'elle que pour rire : se dilater la rate. C\'est le tempérament des joyeux sans ambition démesurée, qui ne se prennent pas au sérieux, fuient les plannings et préfèrent un bon fou rire à une promotion.',
    t: { vhe: 0.9, opt: 0.9, vac: 0.05, vpo: 0.05, ord: 0.1, con: 0.1, inf: 0.85, tmp: 0.1, dog: 0.1, rig: 0.15 } },
  { name: 'La vésicule biliaire', by: 'Digestion · la réserve prévoyante', tag: 'Toujours de côté, au cas où', color: '#7f9a3c',
    desc: 'Petite poche en forme de poire sous le foie, elle stocke et concentre la bile pour la libérer pile au moment du repas. Et quand on s\'inquiète, on dit qu\'on se fait de la bile. C\'est le tempérament des prévoyants un peu anxieux, qui ont toujours des provisions, un parapluie et une solution de secours, et qui s\'inquiètent pour tout le monde afin que personne n\'ait à le faire.',
    t: { thr: 0.85, vig: 0.9, vse: 0.95, rsk: 0.05, opt: 0.2, inf: 0.1, tmp: 0.85, inc: 0.1, vst: 0.1, care: 0.8 } },
  { name: 'L\'appendice', by: 'Digestion · longtemps jugé inutile', tag: 'Incompris, mais pas sans raison d\'être', color: '#a58d6f',
    desc: 'Longtemps pris pour un reste inutile de l\'évolution, ce petit tube de quelques centimètres servirait en fait de refuge aux bonnes bactéries de l\'intestin. Il a passé des siècles à être sous-estimé sans jamais changer d\'avis. C\'est le tempérament des marginaux indépendants, qui ne rentrent dans aucune case, n\'attendent pas qu\'on les comprenne et ont souvent raison trop tôt.',
    t: { ind: 0.98, vsd: 0.9, col: 0.05, soc: 0.1, vco: 0.05, auth: 0.1, chg: 0.85, nat: 0.75, att: 0.2, loy: 0.2 } },
  { name: 'La thyroïde', by: 'Hormones · le papillon du cou', tag: 'C\'est elle qui donne le tempo', color: '#e0567a',
    desc: 'En forme de papillon à la base du cou, elle règle la vitesse de tout le corps : la chaleur, le rythme du cœur, l\'énergie dépensée. Un peu trop, tout s\'accélère ; un peu moins, tout ralentit. C\'est le tempérament des gens qui mettent l\'ambiance, lancent les projets, accélèrent les autres et supportent mal que les choses restent en l\'état.',
    t: { inf: 0.9, vst: 0.9, chg: 0.9, vac: 0.8, dom: 0.75, ste: 0.1, vse: 0.2, vtr: 0.15, san: 0.3, opt: 0.85 } },
  { name: 'Les surrénales', by: 'Hormones · l\'adrénaline en quelques secondes', tag: 'Zéro à cent en un battement', color: '#e63b1f',
    desc: 'Posées sur les reins comme deux petits chapeaux, elles libèrent l\'adrénaline en quelques secondes : cœur qui cogne, muscles prêts, tout le corps en alerte pour combattre ou fuir. C\'est le tempérament des amateurs de sensations, qui vivent à fond, adorent l\'imprévu, foncent avant de réfléchir et ne se sentent jamais aussi vivants qu\'au pied du mur.',
    t: { aud: 0.95, rsk: 0.98, vst: 0.95, san: 0.1, ste: 0.05, tmp: 0.05, cfl: 0.85, vse: 0.05, rig: 0.2, ord: 0.1 } },
  { name: 'La peau', by: 'Protection · le plus grand organe', tag: 'La frontière qui protège et qui ressent', color: '#d9a47c',
    desc: 'Près de deux mètres carrés, le plus grand de nos organes, entièrement renouvelé en surface en un mois environ. Elle nous protège du monde tout en nous permettant de le toucher, de sentir le froid, la caresse, le soleil. C\'est le tempérament des protecteurs sensibles, qui font rempart pour les leurs tout en restant à fleur de peau, attentifs à tout ce qui les entoure.',
    t: { care: 0.95, loy: 0.9, vbe: 0.9, vig: 0.8, col: 0.8, cmp: 0.1, aud: 0.2, vst: 0.2, ind: 0.15, thr: 0.7 } },
  { name: 'Les yeux', by: 'Sens · un million de nuances', tag: 'Rien ne leur échappe', color: '#3f7fbf',
    desc: 'Ils distinguent des centaines de milliers de nuances et clignent une quinzaine de fois par minute, et le cerveau remet à l\'endroit l\'image qu\'ils reçoivent à l\'envers. Ils regardent avant de parler. C\'est le tempérament des observateurs et des esthètes, qui remarquent le détail que personne n\'a vu, aiment la beauté des choses et préfèrent comprendre en silence.',
    t: { ouv: 0.85, vig: 0.8, ide: 0.8, soc: 0.2, inf: 0.1, com: 0.15, dom: 0.15, san: 0.8, aff: 0.8, cfl: 0.15 } },
  { name: 'L\'oreille interne', by: 'Sens · l\'escargot de l\'équilibre', tag: 'Elle écoute, et tout tient debout', color: '#5fa89a',
    desc: 'Enroulée comme un petit escargot, la cochlée transforme les sons en signaux, tandis que le vestibule, juste à côté, veille à ce qu\'on ne perde pas l\'équilibre. Écouter et garder l\'aplomb : deux métiers dans quelques millimètres. C\'est le tempérament des diplomates attentifs, qui laissent parler les autres, apaisent les tensions et ramènent tout le monde au milieu.',
    t: { dip: 0.98, emp: 0.85, cfl: 0.05, dom: 0.05, com: 0.1, ste: 0.85, fair: 0.8, inf: 0.2, cmp: 0.1, epi: 0.2 } },
  { name: 'Le nez', by: 'Sens · 400 sortes de récepteurs', tag: 'Il a du flair, et il le sait', color: '#c98b6b',
    desc: 'Environ quatre cents types de récepteurs olfactifs, reliés directement aux zones de l\'émotion et de la mémoire : c\'est pourquoi une odeur de gâteau peut ramener d\'un coup en enfance. Avoir du nez, c\'est sentir les choses avant qu\'elles arrivent. C\'est le tempérament des intuitifs, qui se fient à leur instinct plus qu\'aux tableaux et ont rarement tort.',
    t: { aff: 0.05, inc: 0.85, ord: 0.15, rig: 0.2, epi: 0.1, vhe: 0.75, con: 0.15, ouv: 0.8, loc: 0.3, ide: 0.75 } },
  { name: 'La langue', by: 'Sens · des milliers de bourgeons du goût', tag: 'Gourmande et bien pendue', color: '#e2717d',
    desc: 'Faite de huit muscles et couverte de milliers de bourgeons du goût, elle goûte, elle parle, elle n\'arrête jamais. Et la célèbre carte des saveurs par zones est un mythe : toute la langue perçoit tout. C\'est le tempérament des bavards gourmands, qui adorent les tablées, racontent des histoires, goûtent à tout et ne gardent pas longtemps ce qu\'ils pensent pour eux.',
    t: { inf: 0.95, soc: 0.95, vhe: 0.9, com: 0.8, con: 0.1, vig: 0.15, ste: 0.3, rig: 0.15, vac: 0.3, att: 0.8 } },
  { name: 'Les cordes vocales', by: 'Voix · des centaines de vibrations par seconde', tag: 'Faites pour porter une cause', color: '#b83280',
    desc: 'Deux petits replis dans la gorge qui vibrent une à deux centaines de fois par seconde quand on parle, et bien plus quand on chante. Sans elles, pas de discours, pas de chanson, pas de coup de gueule. C\'est le tempérament des tribuns et des militants, qui prennent la parole pour défendre ce en quoi ils croient et savent entraîner une foule derrière une idée.',
    t: { eng: 0.95, lea: 0.9, inf: 0.9, epi: 0.8, ide: 0.8, com: 0.9, ste: 0.15, san: 0.3, vse: 0.2, chg: 0.8 } },
  { name: 'Les dents', by: 'Mastication · la matière la plus dure du corps', tag: 'Elles ont du mordant', color: '#e8e4d8',
    desc: 'Leur émail est la substance la plus dure du corps humain, et on en reçoit deux jeux : vingt dents de lait, puis trente-deux définitives. Elles croquent, tranchent, broient, et savent aussi faire un très beau sourire. C\'est le tempérament des compétiteurs, qui ont les dents longues, ne lâchent rien, aiment gagner et le montrent sans détour.',
    t: { com: 0.95, cfl: 0.95, cmp: 0.95, dom: 0.9, vpo: 0.8, dip: 0.05, emp: 0.25, ste: 0.15, col: 0.2, vac: 0.85 } },
  { name: 'La colonne vertébrale', by: 'Squelette · trente-trois vertèbres', tag: 'Droite dans ses bottes', color: '#8c7a64',
    desc: 'Trente-trois vertèbres empilées qui nous tiennent debout, protègent la moelle épinière et plient sans rompre. Nous avons d\'ailleurs autant de vertèbres au cou qu\'une girafe : sept. C\'est le tempérament des gens qui ont de la colonne, justement : fidèles à leurs principes, respectueux des règles et des aînés, et solides comme un pilier quand tout vacille.',
    t: { auth: 0.95, vtr: 0.9, dog: 0.8, fia: 0.9, loy: 0.9, inc: 0.1, chg: 0.05, lib: 0.2, vco: 0.9, ouv: 0.25 } },
  { name: 'Le squelette', by: 'Structure · 206 os', tag: 'La charpente de tout le reste', color: '#d8d0bd',
    desc: 'Environ trois cents os à la naissance, qui se soudent peu à peu pour n\'en compter que deux cent six chez l\'adulte, et qui se renouvellent entièrement en une dizaine d\'années. Il est la charpente sur laquelle tout le reste s\'accroche. C\'est le tempérament des organisateurs, qui posent les fondations, font des plans à long terme et aiment que chaque chose ait sa place.',
    t: { ord: 0.98, vse: 0.9, tmp: 0.9, con: 0.9, rig: 0.85, vst: 0.1, inc: 0.1, vhe: 0.2, lea: 0.75, emp: 0.35 } },
  { name: 'Les muscles', by: 'Mouvement · plus de six cents', tag: 'Moins de discours, plus d\'action', color: '#b0413e',
    desc: 'Plus de six cents muscles, près de la moitié de notre poids chez certains, du minuscule stapédien de l\'oreille au grand fessier. Ils ne pensent pas, ils agissent, et ils se renforcent à chaque effort. C\'est le tempérament des gens d\'action, pragmatiques et ambitieux, qui préfèrent faire que discuter et mesurent leur valeur à ce qu\'ils ont accompli.',
    t: { vac: 0.95, det: 0.95, cmp: 0.85, epi: 0.05, ide: 0.15, loc: 0.05, dom: 0.8, aff: 0.6, emp: 0.3, vun: 0.2 } },
  { name: 'Les tendons', by: 'Mouvement · le tendon d\'Achille en tête', tag: 'Le lien qui tient bon', color: '#c9b79c',
    desc: 'Ils relient les muscles aux os et transmettent chaque effort ; le tendon d\'Achille, le plus solide, supporte plusieurs fois le poids du corps à chaque foulée de course. Sans eux, toute la force du monde ne servirait à rien. C\'est le tempérament des fidèles, qui font le lien entre les gens, tiennent les promesses et ne cherchent jamais à briller à la place des autres.',
    t: { fia: 0.95, loy: 0.95, att: 0.85, ind: 0.1, dom: 0.1, vpo: 0.05, ste: 0.9, col: 0.8, com: 0.2, lea: 0.2 } },
  { name: 'La moelle osseuse', by: 'Fabrication · 200 milliards de globules par jour', tag: 'L\'atelier secret qui ne ferme jamais', color: '#e39a8a',
    desc: 'Cachée au cœur des os, elle fabrique chaque jour environ deux cents milliards de globules rouges, sans compter les globules blancs et les plaquettes. Personne ne la voit, tout le monde en dépend. C\'est le tempérament des généreux de l\'ombre, qui produisent, donnent et réparent sans relâche, et seraient gênés qu\'on les remercie en public.',
    t: { vbe: 0.95, care: 0.9, inf: 0.05, vpo: 0.05, soc: 0.15, vac: 0.2, ste: 0.9, det: 0.85, dom: 0.1, cmp: 0.05 } },
  { name: 'Le système immunitaire', by: 'Défenses · une mémoire à toute épreuve', tag: 'On ne touche pas aux siens', color: '#2f6f5e',
    desc: 'Il distingue ce qui fait partie de nous de ce qui n\'en fait pas, patrouille partout et se souvient des intrus pendant des années : c\'est tout le principe des vaccins. C\'est le tempérament des défenseurs loyaux et méfiants, qui gardent la maison, repèrent tout de suite ce qui cloche, n\'oublient pas un affront et montent au front dès qu\'un proche est menacé.',
    t: { loy: 0.95, nat: 0.9, cfl: 0.9, vig: 0.9, com: 0.8, opn: 0.85, ouv: 0.2, dip: 0.15, thr: 0.8, san: 0.75 } },
  { name: 'Les globules rouges', by: 'Circulation · un tour du corps par minute', tag: 'Toujours en route, jamais pour soi', color: '#d6242f',
    desc: 'Nous en avons des dizaines de milliers de milliards. Ils n\'ont même pas de noyau, pour faire plus de place à l\'oxygène, font le tour du corps en une minute environ et livrent sans relâche pendant quatre mois. C\'est le tempérament des voyageurs serviables, qui ne tiennent pas en place, vont partout où l\'on a besoin d\'eux et ne gardent rien pour eux-mêmes.',
    t: { vst: 0.9, opn: 0.05, vbe: 0.85, col: 0.85, vpo: 0.05, dom: 0.1, ord: 0.3, soc: 0.8, vse: 0.2, ind: 0.3 } },
  { name: 'Le nerf vague', by: 'Système nerveux · le grand vagabond', tag: 'Il calme tout ce qu\'il touche', color: '#7fae8e',
    desc: 'Son nom vient du latin vagus, le vagabond : parti du cerveau, il descend jusqu\'au ventre en passant par le cœur et les poumons. Il ralentit le pouls, apaise la respiration, remet le corps au repos après l\'agitation. C\'est le tempérament des apaisants, qui détendent l\'atmosphère, prennent la vie comme elle vient et savent profiter d\'un bon moment sans penser à la suite.',
    t: { thr: 0.05, san: 0.9, vhe: 0.8, cfl: 0.1, vac: 0.1, cmp: 0.05, tmp: 0.2, ord: 0.2, vig: 0.1, inc: 0.85 } },
  { name: 'Les mains', by: 'Mouvement · 27 os chacune', tag: 'Tout ce qu\'elles touchent prend forme', color: '#c68c53',
    desc: 'Vingt-sept os chacune, soit plus d\'un quart de notre squelette à elles deux, et ce pouce opposable qui a tout changé. Elles bâtissent, dessinent, réparent, jouent de la musique. C\'est le tempérament des bricoleurs et des créateurs, qui pensent avec leurs doigts, préfèrent fabriquer que commenter et ne s\'épanouissent jamais autant qu\'avec un projet entre les mains.',
    t: { ide: 0.9, vsd: 0.9, epi: 0.05, ind: 0.8, ouv: 0.8, vpo: 0.1, soc: 0.3, inc: 0.7, vco: 0.2, vac: 0.65 } },
  { name: 'Les pieds', by: 'Mouvement · 26 os chacun', tag: 'Toujours sur terre', color: '#8a6e4b',
    desc: 'Vingt-six os et trente-trois articulations chacun, pour porter tout le poids du corps pas après pas ; au bout d\'une vie, ils nous ont fait marcher l\'équivalent de plusieurs tours de la Terre. C\'est le tempérament des gens qui gardent les pieds sur terre : concrets, simples, attachés à leur coin et méfiants envers les grandes théories qui ne marchent qu\'en réunion.',
    t: { epi: 0.02, ide: 0.1, ouv: 0.3, fia: 0.85, ste: 0.8, vtr: 0.75, opn: 0.8, eng: 0.1, dog: 0.2, vhe: 0.6 } },
  { name: 'Les cheveux', by: 'Apparence · plus de cent mille', tag: 'Libres, changeants, jamais pareils', color: '#6b4226',
    desc: 'Plus de cent mille, qui poussent d\'environ un centimètre par mois, et on en perd chaque jour des dizaines sans s\'en apercevoir. On les coupe, on les colore, on les attache, on les lâche : ils changent avec nous. C\'est le tempérament des libres et des expressifs, qui aiment se réinventer, suivent leur humeur plutôt que la norme et n\'aiment pas qu\'on les coiffe au poteau.',
    t: { lib: 0.95, chg: 0.9, vst: 0.9, inf: 0.85, vtr: 0.05, con: 0.1, vse: 0.15, vco: 0.1, ste: 0.2, vhe: 0.8 } },
  { name: 'Les ongles', by: 'Apparence · trois millimètres par mois', tag: 'Impeccables jusqu\'au bout', color: '#e9b8b0',
    desc: 'Ils poussent d\'environ trois millimètres par mois sur les mains, plus lentement sur les pieds, et protègent le bout des doigts tout en leur donnant de la précision. Être quelque chose jusqu\'au bout des ongles, c\'est l\'être entièrement. C\'est le tempérament des perfectionnistes soignés, qui aiment le travail fini, les apparences tenues et les règles respectées.',
    t: { con: 0.95, vco: 0.9, ord: 0.9, rig: 0.85, vac: 0.8, vpo: 0.65, inc: 0.1, vst: 0.2, lib: 0.15, ouv: 0.25 } },
  { name: 'Les glandes lacrymales', by: 'Émotion · des larmes pour tout dire', tag: 'Le cœur au bord des yeux', color: '#7ab6d9',
    desc: 'Elles humidifient les yeux en permanence, les protègent d\'une poussière, et ce sont elles qui débordent quand l\'émotion est trop grande, de chagrin comme de joie. Pleurer d\'émotion serait propre à notre espèce. C\'est le tempérament des grands sensibles, qui ressentent tout très fort, pleurent au cinéma sans honte et ont une immense capacité à consoler les autres.',
    t: { emp: 0.98, care: 0.95, san: 0.1, aff: 0.05, com: 0.1, dom: 0.05, cmp: 0.05, thr: 0.65, vpo: 0.05, rig: 0.25 } },
  { name: 'Le nombril', by: 'Souvenir · la toute première cicatrice', tag: 'Le centre du monde, forcément', color: '#d4a373',
    desc: 'C\'est la seule cicatrice que tout le monde porte, au même endroit, depuis le premier jour. Il se trouve à peu près au milieu du corps, ce qui lui a donné une certaine idée de son importance. C\'est le tempérament des charismatiques un peu centrés sur eux-mêmes, qui aiment qu\'on les regarde, savent occuper la scène et ne voient pas bien pourquoi on parlerait d\'autre chose.',
    t: { vpo: 0.95, inf: 0.9, dom: 0.85, emp: 0.1, vun: 0.1, col: 0.1, care: 0.2, vhe: 0.85, cmp: 0.85, dip: 0.2 } },
  { name: 'Le petit orteil', by: 'Mouvement · l\'humble du bout du pied', tag: 'Petit, oublié, toujours là', color: '#e0b89a',
    desc: 'Il aide à l\'équilibre sans que personne s\'en rende compte, on ne pense à lui que lorsqu\'il rencontre le pied d\'un meuble, et il ne s\'en offusque jamais. Il ne vise rien, ne commande rien, il est simplement là. C\'est le tempérament des gens sans prétention, qui se laissent porter par la vie, rient de leurs petits malheurs et n\'ont aucune envie de diriger quoi que ce soit.',
    t: { lea: 0.05, dom: 0.05, vac: 0.05, vpo: 0.02, loc: 0.9, opt: 0.8, ste: 0.8, aud: 0.1, tmp: 0.15, eng: 0.05 } },
];

window.PRISME_ORGANS = { ORGANS };
