/* ============================================================
   PRISME — « Si tu étais une planète »
   ------------------------------------------------------------
   Les huit planètes, et avec elles les lunes, les planètes naines et
   quelques astres célèbres. Ce qui compte, c'est leur caractère :
   brûlante ou glacée, qui tourne vite ou lentement, qui reste proche
   du Soleil ou s'aventure loin. Des faits exacts, un ciel bienveillant.
     name = l'astre, by = type · un fait marquant, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const PLANETS = [
  { name: 'Mercure', by: 'Planète · une année de 88 jours', tag: 'Toujours pressée, jamais tiède', color: '#9a8f86',
    desc: 'La plus proche du Soleil boucle son année en 88 jours, un record, et passe d\'environ 430 °C le jour à moins 180 °C la nuit, faute d\'atmosphère pour garder la chaleur. Messagère des dieux, elle court sans cesse. C\'est le tempérament des esprits vifs et impatients, qui pensent plus vite que leur ombre, passent du feu à la glace en une phrase et s\'ennuient dès que ça ralentit.',
    t: { aff: 0.85, ouv: 0.85, ste: 0.05, san: 0.15, cmp: 0.8, vac: 0.8, att: 0.2, vtr: 0.15, tmp: 0.2, vse: 0.2 } },
  { name: 'Vénus', by: 'Planète · 465 °C sous les nuages', tag: 'Éblouissante de loin, brûlante de près', color: '#e8b04a',
    desc: 'L\'astre le plus brillant du ciel après la Lune, l\'« étoile du Berger », cache sous ses nuages d\'acide sulfurique la surface la plus chaude du système solaire. Elle tourne à l\'envers des autres, et si lentement que son jour dure plus que son année. C\'est le tempérament des séducteurs à contre-courant, qui brillent, aiment le plaisir et n\'ont aucune intention de tourner dans le même sens que tout le monde.',
    t: { vhe: 0.95, inf: 0.9, chg: 0.8, dip: 0.2, cfl: 0.75, con: 0.05, vco: 0.1, att: 0.7, vse: 0.2, rig: 0.15 } },
  { name: 'La Terre', by: 'Planète · la seule qu\'on sache habitée', tag: 'Elle fait vivre tout le monde', color: '#3a7bbf',
    desc: 'Couverte d\'eau aux trois quarts, protégée par son champ magnétique, placée juste à la bonne distance du Soleil : c\'est le seul endroit connu où la vie s\'est installée, et elle y a mis de la variété. C\'est le tempérament des cœurs nourriciers, qui prennent soin de tout ce qui pousse autour d\'eux, partagent sans compter et ne cherchent jamais à dominer qui que ce soit.',
    t: { care: 0.95, vun: 0.9, vbe: 0.9, col: 0.85, emp: 0.9, cmp: 0.1, vpo: 0.05, dom: 0.15, ste: 0.8, nat: 0.2 } },
  { name: 'Mars', by: 'Planète · la rouge', tag: 'Le guerrier couleur rouille', color: '#c1440e',
    desc: 'Sa poussière riche en oxyde de fer lui donne sa couleur, et les Romains y ont vu leur dieu de la guerre. Elle porte le plus haut volcan connu, Olympus Mons, près de vingt-deux kilomètres, et les robots Curiosity et Perseverance la sillonnent encore. C\'est le tempérament des combatifs, francs et intrépides, qui foncent, disent les choses en face et préfèrent un bon duel à un long compromis.',
    t: { com: 0.95, cfl: 0.95, dom: 0.85, aud: 0.9, cmp: 0.9, dip: 0.1, ste: 0.15, emp: 0.25, vpo: 0.7, care: 0.3 } },
  { name: 'Jupiter', by: 'Planète · plus de deux fois toutes les autres réunies', tag: 'Le roi qui protège sa cour', color: '#c99a6b',
    desc: 'Onze fois le diamètre de la Terre, plus massive que toutes les autres planètes réunies, et pourtant elle fait un tour sur elle-même en moins de dix heures. Autour d\'elle gravite près d\'une centaine de lunes, et on lui prête un rôle de bouclier contre les comètes. C\'est le tempérament des patriarches, protecteurs et imposants, qui tiennent leur monde, veillent sur les leurs et entendent qu\'on respecte l\'ordre établi.',
    t: { lea: 0.95, dom: 0.85, auth: 0.9, loy: 0.9, vbe: 0.8, vpo: 0.85, vse: 0.75, chg: 0.15, vst: 0.25, ind: 0.3 } },
  { name: 'Saturne', by: 'Planète · les anneaux', tag: 'L\'élégance a ses règles', color: '#d8c38f',
    desc: 'Ses anneaux sont faits de milliards de morceaux de glace, rangés avec une précision d\'horloger, et elle est si peu dense qu\'elle flotterait dans une baignoire assez grande. Les Romains l\'associaient au dieu du temps. C\'est le tempérament des êtres structurés et exigeants, qui aiment l\'ordre, les traditions et les choses faites comme il faut, quitte à paraître un peu froids aux yeux des pressés.',
    t: { ord: 0.95, rig: 0.95, con: 0.9, auth: 0.85, tmp: 0.9, vtr: 0.85, emp: 0.25, vhe: 0.15, inf: 0.2, dog: 0.7 } },
  { name: 'Uranus', by: 'Planète · couchée sur le côté', tag: 'Elle roule, les autres tournent', color: '#7fd1d9',
    desc: 'Inclinée à près de quatre-vingt-dix-huit degrés, elle roule sur son orbite au lieu de tourner comme une toupie : chaque pôle vit ainsi environ quarante-deux ans de jour, puis quarante-deux ans de nuit. Première planète découverte au télescope, par William Herschel en 1781. C\'est le tempérament des originaux, libres et inventifs, qui ne se demandent même pas comment font les autres.',
    t: { ind: 0.95, vsd: 0.95, lib: 0.95, ide: 0.85, vco: 0.05, auth: 0.05, soc: 0.25, dog: 0.1, cmp: 0.2, rsk: 0.7 } },
  { name: 'Neptune', by: 'Planète · trouvée par le calcul', tag: 'Un rêve bleu, des vents furieux', color: '#3f54ba',
    desc: 'Le Verrier l\'a trouvée sur le papier, en 1846, avant qu\'on la voie au télescope. D\'un bleu profond, elle abrite pourtant les vents les plus violents du système solaire, plus de deux mille kilomètres à l\'heure, et met 165 ans à faire le tour du Soleil. C\'est le tempérament des rêveurs lointains, idéalistes et secrets, qui vivent de grandes tempêtes intérieures derrière un calme de surface.',
    t: { ide: 0.9, epi: 0.85, vun: 0.8, tmp: 0.85, soc: 0.1, inf: 0.1, vpo: 0.05, vac: 0.15, san: 0.3, loc: 0.75 } },
  { name: 'Pluton', by: 'Planète naine · un cœur de glace', tag: 'Déclassée, mais toujours aimée', color: '#c9a88a',
    desc: 'Découverte en 1930 par Clyde Tombaugh, retirée de la liste des planètes en 2006, elle s\'est vengée en 2015 : la sonde New Horizons y a photographié un immense glacier en forme de cœur. Son année dure 248 ans. C\'est le tempérament des outsiders attachants, qui se moquent des étiquettes, restent fidèles à leurs amis et ont un grand cœur même quand on les tient à l\'écart.',
    t: { att: 0.9, loy: 0.85, ind: 0.8, vpo: 0.05, vac: 0.1, auth: 0.1, soc: 0.25, opt: 0.75, cmp: 0.15, vco: 0.2 } },
  { name: 'Cérès', by: 'Planète naine · la première trouvée', tag: 'La travailleuse de la ceinture', color: '#8c8579',
    desc: 'Repérée par Giuseppe Piazzi le premier janvier 1801, c\'est le plus gros corps de la ceinture d\'astéroïdes, et la sonde Dawn y a découvert des taches brillantes, faites de sels. Elle porte le nom de la déesse des moissons. C\'est le tempérament des bosseurs humbles et fiables, qui font tourner la maison sans se mettre en avant et préfèrent le travail bien fait aux grandes déclarations.',
    t: { fia: 0.95, ste: 0.9, vbe: 0.85, col: 0.8, vtr: 0.8, vpo: 0.05, aud: 0.15, inf: 0.1, vst: 0.15, epi: 0.1 } },
  { name: 'Éris', by: 'Planète naine · celle qui a tout déclenché', tag: 'Elle a mis la pagaille, et assume', color: '#b7b3c9',
    desc: 'Découverte en 2005, presque aussi grande que Pluton et plus massive, elle a forcé les astronomes à redéfinir le mot « planète », ce qui a coûté son titre à Pluton. On l\'a baptisée du nom de la déesse de la discorde, et ça lui va. C\'est le tempérament des provocateurs lucides, qui bousculent les idées reçues, n\'ont pas peur du conflit et ne présentent jamais d\'excuses pour avoir eu raison.',
    t: { com: 0.95, cfl: 0.95, chg: 0.9, dip: 0.05, vco: 0.05, auth: 0.1, nat: 0.8, ind: 0.9, att: 0.15, emp: 0.2 } },
  { name: 'Makémaké', by: 'Planète naine · découverte à Pâques', tag: 'Le mystique des confins', color: '#b4644a',
    desc: 'Trouvée juste après Pâques 2005, elle porte le nom du dieu créateur du peuple de l\'île de Pâques. Rougeâtre, glacée, elle met plus de trois siècles à faire le tour du Soleil, et sa petite lune n\'a été aperçue qu\'en 2016. C\'est le tempérament des contemplatifs, attachés aux mythes et au sacré, qui vivent loin du bruit et trouvent du sens là où d\'autres ne voient que du froid.',
    t: { sanc: 0.95, vtr: 0.85, ide: 0.8, soc: 0.15, vac: 0.1, aff: 0.2, inc: 0.7, loc: 0.8, vhe: 0.2, cmp: 0.1 } },
  { name: 'Haumea', by: 'Planète naine · un tour en 4 heures', tag: 'Elle tourne si vite qu\'elle en a pris la forme', color: '#e3d7c1',
    desc: 'Elle fait un tour sur elle-même en un peu moins de quatre heures, si vite qu\'elle s\'est étirée en forme d\'œuf allongé. Elle a deux lunes, un anneau découvert en 2017, et porte le nom d\'une déesse hawaïenne de la fertilité. C\'est le tempérament des tourbillons joyeux, qui ne tiennent pas en place, enchaînent les sorties et les projets, et que la vie a façonnés à force de mouvement.',
    t: { vst: 0.95, vhe: 0.85, soc: 0.9, inf: 0.85, ste: 0.05, ord: 0.05, rig: 0.1, vse: 0.1, opt: 0.85, aff: 0.3 } },
  { name: 'La Lune', by: 'Satellite · toujours la même face', tag: 'Fidèle, même dans ses humeurs', color: '#d9d6cc',
    desc: 'Elle nous montre toujours la même face, soulève les océans deux fois par jour, et s\'éloigne pourtant de près de quatre centimètres chaque année. Douze hommes y ont marché, entre 1969 et 1972. C\'est le tempérament des tendres fidèles, un peu changeants d\'humeur mais jamais de cœur, qui vivent en duo, gardent leurs secrets et restent là, nuit après nuit.',
    t: { att: 0.95, loy: 0.95, fia: 0.85, aff: 0.1, ind: 0.1, dom: 0.1, chg: 0.1, inf: 0.25, vbe: 0.9, opn: 0.75 } },
  { name: 'Phobos', by: 'Lune de Mars · « la peur »', tag: 'Elle voit venir la chute', color: '#6b5d52',
    desc: 'Cette petite lune cabossée fait le tour de Mars en sept heures et demie, plus vite que la planète ne tourne. Elle se rapproche d\'environ deux mètres par siècle et finira, dans quelques dizaines de millions d\'années, par se briser. Son nom veut dire « la peur ». C\'est le tempérament des inquiets lucides, qui voient les ennuis arriver de loin et vérifient trois fois que le gaz est bien fermé.',
    t: { thr: 0.95, vis: 0.95, opt: 0.05, san: 0.1, vig: 0.85, inc: 0.1, loc: 0.85, vse: 0.85, rsk: 0.1, vtr: 0.7 } },
  { name: 'Europe', by: 'Lune de Jupiter · un océan sous la glace', tag: 'Froide dehors, profonde dedans', color: '#c7b99a',
    desc: 'Sous sa croûte de glace striée se cache un océan d\'eau salée qui contiendrait plus d\'eau que tous ceux de la Terre. La sonde Europa Clipper, lancée en 2024, part l\'étudier de près. C\'est le tempérament des réservés au cœur immense, qui paraissent distants au premier abord et cachent une vie intérieure d\'une richesse que peu de gens prennent le temps de découvrir.',
    t: { soc: 0.1, inf: 0.1, emp: 0.9, ide: 0.85, san: 0.85, vun: 0.8, vpo: 0.05, dom: 0.1, att: 0.75, cfl: 0.15 } },
  { name: 'Io', by: 'Lune de Jupiter · 400 volcans actifs', tag: 'Sous pression, en éruption', color: '#e0c23a',
    desc: 'Pétrie par la gravité de Jupiter, elle chauffe de l\'intérieur et crache du soufre par des centaines de volcans : c\'est le corps le plus actif du système solaire, et sa surface jaune et orange ressemble à une pizza. C\'est le tempérament des volcans humains, expressifs et flamboyants, qui ne gardent rien pour eux, explosent vite, pardonnent aussi vite et rendent la vie autour d\'eux tout sauf monotone.',
    t: { san: 0.05, ste: 0.05, com: 0.9, inf: 0.9, vst: 0.85, cfl: 0.85, vhe: 0.75, ord: 0.1, vse: 0.15, aff: 0.15 } },
  { name: 'Ganymède', by: 'Lune de Jupiter · plus grande que Mercure', tag: 'Grande, mais sans en faire une histoire', color: '#8a8475',
    desc: 'C\'est la plus grande lune du système solaire, plus large que la planète Mercure, et la seule à produire son propre champ magnétique. La sonde européenne JUICE doit se mettre en orbite autour d\'elle en 2034. C\'est le tempérament des solides discrets, qui pourraient briller seuls mais préfèrent rester dans leur équipe, avec leur propre bouclier et des limites très claires.',
    t: { san: 0.9, fia: 0.85, det: 0.85, ind: 0.85, vsd: 0.85, vpo: 0.1, inf: 0.2, loc: 0.1, cmp: 0.2, col: 0.7 } },
  { name: 'Callisto', by: 'Lune de Jupiter · la plus cabossée', tag: 'Rien ne l\'ébranle vraiment', color: '#5b544c',
    desc: 'Sa surface est l\'une des plus criblées de cratères du système solaire, et elle n\'a presque pas changé depuis quatre milliards d\'années. Loin des turbulences de Jupiter, elle tourne à son rythme sans rien demander. C\'est le tempérament des stoïques tranquilles, qui ont encaissé leur part de coups, n\'en font pas un drame et gardent leur calme quand tout s\'agite autour.',
    t: { ste: 0.95, san: 0.9, chg: 0.05, vst: 0.05, soc: 0.1, inf: 0.05, rsk: 0.1, thr: 0.15, cfl: 0.1, vhe: 0.25 } },
  { name: 'Titan', by: 'Lune de Saturne · des lacs de méthane', tag: 'Un cocon sous la brume', color: '#d69b3c',
    desc: 'Enveloppée d\'une atmosphère plus épaisse que la nôtre, elle a des nuages, de la pluie, des rivières et des lacs, mais de méthane liquide. En 2005, la sonde Huygens s\'y est posée, l\'atterrissage le plus lointain jamais réussi. C\'est le tempérament des casaniers rêveurs, qui aiment leur cocon, leur plaid et leur monde intérieur, et ne laissent entrer que ceux qui ont traversé la brume.',
    t: { vse: 0.9, vhe: 0.8, soc: 0.15, rsk: 0.1, nat: 0.75, ide: 0.8, vst: 0.2, inf: 0.15, opn: 0.8, att: 0.8 } },
  { name: 'Encelade', by: 'Lune de Saturne · des geysers au pôle sud', tag: 'Petite, lumineuse, débordante', color: '#eef4f7',
    desc: 'À peine cinq cents kilomètres de diamètre, mais c\'est l\'un des corps les plus brillants du système solaire : sa glace renvoie presque toute la lumière. De son pôle sud jaillissent des geysers d\'eau qui nourrissent un anneau de Saturne. C\'est le tempérament des petits soleils, confiants et généreux, qui débordent de bonne humeur et éclaboussent tout le monde de leur joie.',
    t: { opt: 0.95, inf: 0.85, vbe: 0.9, soc: 0.85, emp: 0.8, dom: 0.1, vpo: 0.05, thr: 0.1, nat: 0.1, vis: 0.1 } },
  { name: 'Triton', by: 'Lune de Neptune · elle tourne à l\'envers', tag: 'L\'étrangère qui refuse le sens commun', color: '#b8c7c9',
    desc: 'Elle tourne autour de Neptune dans le sens contraire de la rotation de sa planète, signe qu\'elle vient d\'ailleurs et a probablement été capturée. Glacée à moins 235 °C, elle crache pourtant des geysers d\'azote, photographiés par Voyager 2 en 1989. C\'est le tempérament des solitaires frondeurs, méfiants et froids en apparence, qui ne suivent aucun courant et ne doivent rien à personne.',
    t: { vco: 0.05, con: 0.1, att: 0.1, loy: 0.1, emp: 0.2, nat: 0.85, cfl: 0.8, cmp: 0.75, soc: 0.15, col: 0.1 } },
  { name: 'Miranda', by: 'Lune d\'Uranus · un patchwork', tag: 'Faite de morceaux qui ne vont pas ensemble', color: '#a6a39b',
    desc: 'Nommée d\'après un personnage de Shakespeare, elle a une surface en patchwork, comme recollée à la hâte, et porte Verona Rupes, une falaise qu\'on estime haute de plusieurs kilomètres, peut-être une vingtaine. C\'est le tempérament des éclectiques, qui ont eu plusieurs vies, mêlent des goûts que tout oppose et assument volontiers un joyeux désordre.',
    t: { ord: 0.05, rig: 0.1, con: 0.05, ouv: 0.95, inc: 0.9, vst: 0.85, chg: 0.85, loc: 0.8, vtr: 0.1, dog: 0.1 } },
  { name: 'Le Soleil', by: 'Étoile · 99,8 % de la masse du système', tag: 'Tout tourne autour de lui', color: '#f5a623',
    desc: 'Il concentre presque toute la masse du système solaire, chauffe à quinze millions de degrés en son cœur, et sa lumière met huit minutes à nous parvenir. Tout le monde tourne autour de lui, et il ne s\'en plaint pas. C\'est le tempérament des personnalités rayonnantes, ambitieuses et optimistes, qui remplissent une pièce, entraînent les autres et assument volontiers d\'être au centre.',
    t: { inf: 0.95, opt: 0.95, vac: 0.9, dom: 0.85, vpo: 0.8, soc: 0.9, vig: 0.1, thr: 0.1, ste: 0.2, vco: 0.3 } },
  { name: 'Sirius', by: 'Étoile · la plus brillante de la nuit', tag: 'Elle brille, mais jamais seule', color: '#b9d4ff',
    desc: 'À 8,6 années-lumière, c\'est l\'étoile la plus brillante du ciel nocturne, et elle ne voyage pas seule : une petite naine blanche, Sirius B, tourne autour d\'elle. Elle a même donné son nom à la canicule. C\'est le tempérament des brillants attachés à leur duo, sociables et chaleureux, qui adorent la lumière à condition de la partager avec la personne qui compte.',
    t: { att: 0.95, vbe: 0.9, inf: 0.85, soc: 0.85, vac: 0.75, ind: 0.1, vsd: 0.2, vpo: 0.2, cfl: 0.2, loy: 0.8 } },
  { name: 'Bételgeuse', by: 'Étoile · la géante rouge d\'Orion', tag: 'Vivre fort, finir en feu d\'artifice', color: '#d4502a',
    desc: 'Placée au centre du Soleil, cette supergéante rouge avalerait les orbites de Mars, peut-être celle de Jupiter. En 2019, elle a pâli si brusquement qu\'on a cru à sa fin ; elle explosera bien un jour en supernova. C\'est le tempérament des intenses, qui vivent à fond, prennent tous les risques, se moquent de la prudence et préfèrent une vie courte et flamboyante à une vie tiède.',
    t: { aud: 0.95, rsk: 0.95, tmp: 0.05, vse: 0.05, vig: 0.05, vst: 0.9, san: 0.2, dom: 0.7, chg: 0.8, vtr: 0.1 } },
  { name: 'L\'étoile Polaire', by: 'Étoile · immobile au nord', tag: 'On peut toujours compter sur elle', color: '#e6ecf5',
    desc: 'Elle n\'est pas la plus brillante, loin de là, mais elle se tient presque exactement au-dessus du pôle Nord et semble immobile quand tout le ciel tourne. Depuis des siècles, les marins s\'orientent grâce à elle. C\'est le tempérament des repères, calmes et fiables, qui ne cherchent pas la lumière mais restent à leur place, fidèles à leurs principes, pour que les autres retrouvent leur chemin.',
    t: { fia: 0.98, ste: 0.9, san: 0.9, vbe: 0.85, lea: 0.75, epi: 0.8, chg: 0.05, inf: 0.1, vpo: 0.1, vst: 0.1 } },
  { name: 'Proxima du Centaure', by: 'Étoile · la plus proche, et invisible', tag: 'Si proche, si discrète', color: '#b3413b',
    desc: 'C\'est l\'étoile la plus proche du Soleil, à 4,2 années-lumière, et pourtant on ne la voit pas à l\'œil nu : c\'est une petite naine rouge, sujette à de violentes éruptions. Elle vivra des milliers de milliards d\'années. C\'est le tempérament des proches discrets, qu\'on oublie un peu parce qu\'ils ne font pas de bruit, loyaux sur le long terme, mais qui ont leurs coups de sang.',
    t: { inf: 0.05, vpo: 0.05, vac: 0.1, att: 0.9, emp: 0.8, san: 0.2, com: 0.75, thr: 0.7, tmp: 0.9, soc: 0.3 } },
  { name: 'La comète de Halley', by: 'Comète · de retour tous les 76 ans', tag: 'Elle part loin, mais revient toujours', color: '#9fd3e6',
    desc: 'Edmond Halley avait prédit son retour pour 1758 ; il n\'a pas vécu pour la voir, mais elle est venue au rendez-vous. Passée en 1986, attendue en 2061, elle file au-delà de Neptune entre deux visites. C\'est le tempérament des grands voyageurs indépendants, qui ont besoin de partir longtemps, loin, seuls, mais tiennent parole et reviennent exactement quand ils l\'ont promis.',
    t: { ind: 0.95, vst: 0.8, fia: 0.85, rig: 0.8, tmp: 0.9, att: 0.2, soc: 0.3, opn: 0.05, vse: 0.2, col: 0.1 } },
  { name: 'La ceinture d\'astéroïdes', by: 'Entre Mars et Jupiter · des millions de rochers', tag: 'Ensemble, mais chacun sa place', color: '#7d7166',
    desc: 'Des millions de rochers tournent entre Mars et Jupiter, et pourtant ils sont si espacés que les sondes la traversent sans rien heurter. Réunis, ils pèseraient à peine quelques pour cent de la Lune. C\'est le tempérament des gens de collectif, qui aiment la bande, les grandes tablées et l\'égalité, respectent l\'espace de chacun et n\'ont aucune envie qu\'un seul décide pour tous.',
    t: { col: 0.9, fair: 0.9, soc: 0.8, dip: 0.85, lea: 0.1, dom: 0.05, vpo: 0.05, cmp: 0.1, auth: 0.15, ste: 0.8 } },
  { name: 'Sagittarius A*', by: 'Trou noir · au cœur de la galaxie', tag: 'Invisible, et pourtant tout tourne autour', color: '#2b2233',
    desc: 'Quatre millions de fois la masse du Soleil, à vingt-six mille années-lumière d\'ici : c\'est le trou noir autour duquel tourne toute la Voie lactée. Sa première image a été publiée en 2022, une ombre cernée d\'anneau de lumière. C\'est le tempérament des puissants silencieux, froids et magnétiques, qui parlent peu, contrôlent beaucoup et exercent une attraction à laquelle on échappe mal.',
    t: { vpo: 0.95, dom: 0.95, san: 0.95, inf: 0.1, soc: 0.05, emp: 0.1, att: 0.1, nat: 0.8, aff: 0.9, care: 0.1 } },
  { name: 'La Voie lactée', by: 'Galaxie · des centaines de milliards d\'étoiles', tag: 'Il y a de la place pour tout le monde', color: '#8b7fc7',
    desc: 'Cent mille années-lumière de large et des centaines de milliards d\'étoiles ; le Soleil met environ deux cent trente millions d\'années à en faire le tour. Dans quelques milliards d\'années, elle fusionnera avec Andromède. C\'est le tempérament des esprits universels, ouverts à toutes les cultures et à toutes les idées, qui pensent à l\'échelle du monde et trouvent les frontières un peu petites.',
    t: { vun: 0.98, ouv: 0.95, opn: 0.02, inc: 0.85, dog: 0.05, tmp: 0.95, fair: 0.85, col: 0.75, vpo: 0.1, vtr: 0.15 } },
  { name: 'Une naine blanche', by: 'Étoile · ce qui reste quand le feu s\'éteint', tag: 'Toute une vie, concentrée', color: '#dfe6ee',
    desc: 'C\'est le cœur d\'une étoile qui a brûlé tout son carburant : la masse du Soleil tassée dans le volume de la Terre, si dense qu\'une petite cuillère pèserait des tonnes. Elle refroidit ensuite pendant des milliards d\'années, et c\'est le destin de notre Soleil. C\'est le tempérament des sages, qui ont beaucoup vécu, gardent l\'essentiel et n\'ont plus rien à prouver.',
    t: { aff: 0.85, vtr: 0.8, rig: 0.75, vac: 0.05, vpo: 0.05, vst: 0.1, aud: 0.1, soc: 0.25, chg: 0.15, vis: 0.75, loc: 0.75 } },
  { name: 'Une étoile filante', by: 'Météore · un grain de poussière en feu', tag: 'Un instant, et un vœu', color: '#f7e27c',
    desc: 'Ce n\'est pas une étoile du tout : un grain de poussière, souvent plus petit qu\'un grain de sable, qui s\'embrase à une centaine de kilomètres d\'altitude en entrant à toute vitesse dans l\'atmosphère. En août, les Perséides en offrent des dizaines par heure. C\'est le tempérament des romantiques de l\'instant, qui vivent le moment présent, croient aux vœux et aux coups de foudre.',
    t: { tmp: 0.02, ide: 0.9, opt: 0.9, vhe: 0.85, aff: 0.05, ord: 0.1, rig: 0.1, att: 0.75, vse: 0.15, epi: 0.6 } },
];

window.PRISME_PLANETS = { PLANETS };
