/* ============================================================
   PRISME — « Si tu étais un végétal »
   ------------------------------------------------------------
   Un végétal ne choisit pas où il pousse : tout son caractère tient
   dans la manière de s'y prendre. Pousser vite ou lentement, résister
   ou plier, s'étendre ou tenir sa place, fleurir une nuit ou mille ans.
     name = le végétal, by = famille · milieu, cat = la famille, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const PLANTS = [
  /* ---------------- Arbres ---------------- */
  { name: 'Le chêne', by: 'Arbre · forêts d\'Europe', cat: 'Arbres', tag: 'Celui sur qui on peut bâtir', color: '#6b5a2e',
    desc: 'Il met des décennies à pousser et peut dépasser le millier d\'années. Une seule de ses branches fait vivre des centaines d\'espèces d\'insectes, d\'oiseaux et de champignons. Il ne cherche pas l\'aventure, il cherche à durer : on s\'appuie sur lui sans même y penser, et c\'est exactement ce qu\'il voulait.',
    t: { fia: 0.95, san: 0.85, tmp: 0.9, vtr: 0.85, vse: 0.8, att: 0.7, opn: 0.85, chg: 0.15, vst: 0.2, rsk: 0.25, auth: 0.7 } },
  { name: 'L\'olivier', by: 'Arbre · bassin méditerranéen', cat: 'Arbres', tag: 'La paix qui a traversé les siècles', color: '#8a9a5b',
    desc: 'Gelé, brûlé, coupé au ras du sol, il repart de sa souche comme si de rien n\'était, et certains vivent depuis plus de deux mille ans. Il pousse sur des sols pauvres, se contente de peu d\'eau et donne quand même. Pas de coup d\'éclat chez lui : une résilience tranquille, et l\'art de désamorcer plutôt que de combattre.',
    t: { det: 0.9, vbe: 0.8, care: 0.75, dip: 0.85, cfl: 0.15, vtr: 0.8, tmp: 0.85, san: 0.8, cmp: 0.15, dom: 0.2, ste: 0.85 } },
  { name: 'Le séquoia géant', by: 'Arbre · Sierra Nevada', cat: 'Arbres', tag: 'L\'ambition qui voit à trois mille ans', color: '#9c4a2f',
    desc: 'C\'est le plus grand être vivant de la planète en volume, et il peut vivre plus de trois mille ans. Son écorce spongieuse, épaisse de plusieurs dizaines de centimètres, le protège des incendies, dont la chaleur aide même ses cônes à libérer leurs graines. Il vise haut, voit loin et ne se laisse pas impressionner par ce qui brûle autour.',
    t: { san: 0.95, tmp: 0.98, vac: 0.85, vpo: 0.75, lea: 0.8, det: 0.85, thr: 0.15, inf: 0.2, soc: 0.3, cmp: 0.7 } },
  { name: 'Le baobab', by: 'Arbre · savanes d\'Afrique', cat: 'Arbres', tag: 'Le grenier sous lequel on se réunit', color: '#a0785a',
    desc: 'Son tronc stocke des dizaines de milliers de litres d\'eau pour traverser la saison sèche, et ses fleurs ne s\'ouvrent que la nuit, pour les chauves-souris. Dans bien des villages, c\'est sous lui qu\'on se retrouve pour palabrer. Prévoyant, il met de côté pour les mauvais jours et il aime que sa réserve serve à tout le monde.',
    t: { vse: 0.9, vig: 0.75, tmp: 0.85, att: 0.8, col: 0.9, soc: 0.8, vbe: 0.85, rsk: 0.15, vst: 0.2, chg: 0.1 } },
  { name: 'Le saule pleureur', by: 'Arbre · bords de l\'eau', cat: 'Arbres', tag: 'Le cœur au bord de l\'eau', color: '#7fa37a',
    desc: 'Il pousse les pieds dans l\'eau, ses branches retombent jusqu\'à la frôler, et une simple branche plantée dans la terre humide suffit à refaire un arbre. De son écorce on a tiré l\'ancêtre de l\'aspirine. Il ressent tout, ne s\'en cache pas, et soulage les autres avec cette même sensibilité qui le fait pencher.',
    t: { emp: 0.95, aff: 0.05, ide: 0.75, att: 0.9, care: 0.85, san: 0.3, dom: 0.1, cmp: 0.1, opt: 0.3, thr: 0.6 } },
  { name: 'Le bouleau', by: 'Arbre · forêts du Nord', cat: 'Arbres', tag: 'Le pionnier des terres brûlées', color: '#d9d4c7',
    desc: 'Après un incendie ou une coupe, c\'est lui qui arrive le premier sur la terre nue. Il pousse vite, vit peu longtemps, et prépare le terrain pour les chênes et les hêtres qui le remplaceront. Il n\'a pas besoin qu\'on lui trace la voie : il aime les endroits où rien n\'existe encore, et il passe la main sans regret.',
    t: { aud: 0.85, chg: 0.85, vst: 0.8, ouv: 0.85, opn: 0.15, tmp: 0.2, rsk: 0.85, vtr: 0.15, vse: 0.2, lea: 0.6 } },
  { name: 'Le cerisier du Japon', by: 'Arbre · jardins du Japon', cat: 'Arbres', tag: 'La beauté qui ne dure pas', color: '#f2b5c8',
    desc: 'Sa floraison dure à peine une ou deux semaines, et tout un pays sort pique-niquer dessous pour ne pas la rater. Les Japonais y voient la beauté des choses qui passent. Il vit l\'instant avec une intensité totale, partage volontiers sa joie et ne s\'embarrasse ni de plans ni de méthode : ce qui compte, c\'est maintenant.',
    t: { vhe: 0.9, ide: 0.9, tmp: 0.05, inf: 0.75, aff: 0.15, rig: 0.15, ord: 0.2, soc: 0.75, vst: 0.7 } },
  { name: 'L\'érable à sucre', by: 'Arbre · forêts du Québec', cat: 'Arbres', tag: 'La douceur née des contrastes', color: '#c8452b',
    desc: 'Sa sève ne coule vraiment qu\'au printemps, quand les nuits gèlent et que les journées dégèlent : il faut une quarantaine de litres pour un litre de sirop. Il donne le meilleur de lui dans les périodes d\'alternance que d\'autres trouvent éprouvantes. Généreux sans esbroufe, poli, et en automne, il s\'autorise un feu d\'artifice de rouge.',
    t: { vbe: 0.85, inc: 0.8, san: 0.8, att: 0.8, ord: 0.7, dip: 0.8, vpo: 0.15, cmp: 0.2, dom: 0.25, inf: 0.6 } },
  { name: 'Le pin parasol', by: 'Arbre · côtes méditerranéennes', cat: 'Arbres', tag: 'L\'ombre qu\'on vient chercher l\'été', color: '#4e7a4a',
    desc: 'Il se déploie en ombrelle au-dessus des plages et des routes du Sud, et ses cônes mettent trois ans à mûrir leurs pignons. Pas pressé, pas inquiet, il laisse passer le vent de mer et offre de l\'ombre à qui s\'arrête. Il n\'a rien à prouver et aucune envie de concourir : il préfère que la sieste soit réussie.',
    t: { vhe: 0.85, ste: 0.85, opn: 0.7, thr: 0.1, rig: 0.25, cmp: 0.15, vac: 0.2, tmp: 0.6, care: 0.6, san: 0.8 } },
  { name: 'Le sapin', by: 'Arbre · montagnes d\'Europe', cat: 'Arbres', tag: 'La patience qui attend son tour', color: '#2f5a44',
    desc: 'Jeune, il peut attendre des décennies à l\'ombre des grands, en grandissant à peine, jusqu\'à ce qu\'une trouée lui laisse enfin la lumière. Toujours vert, toujours droit, il est aussi celui qu\'on invite chaque hiver pour la fête de famille. Il respecte l\'ordre des choses, fait ce qu\'on attend de lui et ne brûle aucune étape.',
    t: { ste: 0.9, det: 0.85, tmp: 0.95, vco: 0.8, vtr: 0.85, con: 0.8, ord: 0.85, aud: 0.2, inf: 0.25, vst: 0.15 } },
  { name: 'Le cocotier', by: 'Palmier · plages tropicales', cat: 'Arbres', tag: 'La graine qui a traversé l\'océan', color: '#2fa39a',
    desc: 'Sa noix flotte, peut dériver des semaines sur la mer et germer sur une plage à l\'autre bout de l\'océan. Son tronc souple plie sous les cyclones sans rompre. Il part sans savoir où il arrivera, s\'installe là où la vague le dépose et trouve que c\'est très bien comme ça. L\'imprévu est son terrain naturel.',
    t: { vst: 0.95, rsk: 0.9, opn: 0.02, ouv: 0.9, loc: 0.85, ind: 0.8, vse: 0.1, ord: 0.15, opt: 0.85, inc: 0.9 } },
  { name: 'Le bonsaï', by: 'Arbre cultivé · art japonais', cat: 'Arbres', tag: 'La perfection taillée au millimètre', color: '#5b6b3a',
    desc: 'Ce n\'est pas une espèce naine : c\'est un arbre ordinaire, maintenu petit par des années de taille des racines et des branches, et certains passent de génération en génération. Chaque geste compte, chaque détail est pensé. Il aime la maîtrise, la méthode et le travail bien fait, et il a une sainte horreur de l\'improvisation.',
    t: { rig: 0.95, con: 0.95, ord: 0.95, det: 0.85, tmp: 0.9, vco: 0.75, inc: 0.1, vst: 0.15, rsk: 0.1, aud: 0.15, ide: 0.6 } },
  { name: 'Le ginkgo', by: 'Arbre · origine Chine', cat: 'Arbres', tag: 'Le survivant qui ne change pas', color: '#e6c229',
    desc: 'Sa lignée existait avant les dinosaures, il résiste à la pollution des villes, et des ginkgos tout proches de l\'explosion d\'Hiroshima ont repoussé. Il perd ses feuilles d\'or presque toutes le même jour. Le monde peut bien s\'agiter : il a déjà tout vu, il ne compte pas changer, et il se passe très bien de l\'avis des autres.',
    t: { det: 0.95, ind: 0.9, dog: 0.75, chg: 0.05, ouv: 0.15, san: 0.9, vst: 0.1, vis: 0.75, tmp: 0.9, soc: 0.3 } },
  { name: 'L\'if', by: 'Conifère · cimetières et vieilles forêts', cat: 'Arbres', tag: 'Le gardien sombre', color: '#27402f',
    desc: 'Il peut vivre plus de mille ans, souvent dans les cimetières, et presque tout en lui est toxique, sauf la chair rouge de ses fruits. Il pousse dans l\'ombre, lentement, sans se soucier de plaire. Il protège ce qui lui est confié, se méfie de qui s\'approche, et préfère le silence aux grandes effusions.',
    t: { vig: 0.9, nat: 0.9, thr: 0.8, cfl: 0.7, sanc: 0.8, soc: 0.1, inf: 0.05, emp: 0.3, tmp: 0.9, ind: 0.8 } },
  { name: 'Le cyprès', by: 'Conifère · Toscane et Provence', cat: 'Arbres', tag: 'La droiture austère', color: '#34473a',
    desc: 'Il monte en colonne serrée, droit comme un i, et on le plante depuis l\'Antiquité autour des tombes et le long des allées solennelles. On l\'utilise aussi en haies coupe-vent : il se met en rang et tient la ligne. Il respecte les rites, les règles et les anciens, et le laisser-aller le met profondément mal à l\'aise.',
    t: { rig: 0.9, auth: 0.85, vco: 0.85, con: 0.9, sanc: 0.85, loy: 0.8, vtr: 0.9, vhe: 0.1, inf: 0.15, vst: 0.1, dog: 0.7 } },
  { name: 'Le figuier', by: 'Arbre · Méditerranée', cat: 'Arbres', tag: 'La générosité qui pousse n\'importe où', color: '#6d3f5b',
    desc: 'Il s\'installe dans une fissure de mur ou au bord d\'une ruine et devient vite un arbre, avec des racines qui ne demandent la permission à personne. Dans la nature, sa fleur cachée dans la figue n\'est pollinisée que par une minuscule guêpe, un duo inséparable. Il vit pour le plaisir, le partage et la liberté, pas pour l\'ordre.',
    t: { vhe: 0.9, att: 0.85, lib: 0.8, ord: 0.15, con: 0.15, soc: 0.8, rsk: 0.6, vbe: 0.75, rig: 0.2, ind: 0.65 } },
  { name: 'Le pommier', by: 'Arbre fruitier · vergers', cat: 'Arbres', tag: 'Le verger de la famille', color: '#b5392f',
    desc: 'Semez un pépin : l\'arbre qui pousse ne donnera pas la même pomme que son parent. Pour garder une variété, on la greffe, et on transmet ainsi les mêmes fruits depuis des siècles. Il est le verger qu\'on hérite et qu\'on lègue, fiable, généreux, pas très aventureux, et heureux quand toute la famille vient cueillir.',
    t: { vbe: 0.95, vtr: 0.85, fia: 0.9, att: 0.85, opn: 0.85, col: 0.7, aud: 0.2, vst: 0.2, ide: 0.3, ste: 0.8 } },
  { name: 'Le platane', by: 'Arbre · places et avenues', cat: 'Arbres', tag: 'Le citadin imperturbable', color: '#a3a86b',
    desc: 'Pollution, bitume, tailles sévères, racines coincées sous le trottoir : il encaisse tout et continue de faire de l\'ombre aux terrasses. Son écorce se détache par plaques et le laisse tacheté comme un camouflage. Il aime la foule, le bruit et les places animées, et rien de ce qui arrive en ville ne semble vraiment l\'inquiéter.',
    t: { soc: 0.9, san: 0.85, inc: 0.85, opn: 0.1, ouv: 0.75, thr: 0.1, vig: 0.2, col: 0.7, ste: 0.75, loc: 0.6 } },
  { name: 'Le tremble', by: 'Peuplier · forêts froides', cat: 'Arbres', tag: 'L\'inquiet qui ne lâche jamais les siens', color: '#b9c98a',
    desc: 'Ses feuilles, portées par une queue aplatie, frémissent au moindre souffle d\'air. Mais sous terre, ses racines relient des milliers de troncs en un seul être : en Utah, une colonie de trembles forme l\'un des plus grands organismes du monde. Il s\'inquiète de tout, sursaute souvent, et il ne se sent en sécurité qu\'au milieu des siens.',
    t: { thr: 0.95, vig: 0.9, san: 0.1, nat: 0.7, col: 0.9, emp: 0.8, loy: 0.85, opt: 0.2, aud: 0.15, ste: 0.35 } },
  { name: 'Le magnolia', by: 'Arbre · jardins du Sud', cat: 'Arbres', tag: 'L\'élégance d\'un autre âge', color: '#e8c7d8',
    desc: 'Sa famille est l\'une des plus anciennes parmi les plantes à fleurs : elle fleurissait déjà avant l\'arrivée des abeilles, pollinisée par des coléoptères. Chez beaucoup d\'espèces, ses grandes fleurs s\'ouvrent avant les feuilles. Il a des manières d\'autrefois, un goût sûr pour la beauté, et il évite soigneusement les disputes.',
    t: { vtr: 0.85, ide: 0.8, vhe: 0.8, com: 0.15, cfl: 0.1, cmp: 0.2, aff: 0.3, inf: 0.7, tmp: 0.7, dip: 0.8 } },

  /* ---------------- Fleurs ---------------- */
  { name: 'La rose', by: 'Fleur · jardins du monde entier', cat: 'Fleurs', tag: 'La passion qui a des épines', color: '#c21f4a',
    desc: 'On la cultive depuis des millénaires, on lui prête tous les sentiments, et elle se défend par ses aiguillons. Exigeante, sensible aux maladies, elle demande de l\'attention et le rend au centuple. Elle aime intensément, ne fait rien à moitié, et sait très bien piquer si on la prend mal.',
    t: { ide: 0.85, att: 0.9, com: 0.75, dom: 0.7, vpo: 0.7, vhe: 0.8, aff: 0.1, cfl: 0.7, ste: 0.2, vig: 0.6 } },
  { name: 'Le tournesol', by: 'Fleur · champs d\'été', cat: 'Fleurs', tag: 'Toujours tourné vers la lumière', color: '#f2b705',
    desc: 'Jeune, il suit le soleil d\'est en ouest et se retourne pendant la nuit pour l\'attendre au lever. Une fois en fleur, il se fige face à l\'est, là où le jour commence. Il croit que demain sera meilleur, le dit à tout le monde, et son enthousiasme a quelque chose de contagieux, même pour les plus sceptiques.',
    t: { opt: 0.98, inf: 0.9, soc: 0.85, vis: 0.02, thr: 0.05, vst: 0.6, ide: 0.6, nat: 0.1, loc: 0.6 } },
  { name: 'La lavande', by: 'Fleur · Provence', cat: 'Fleurs', tag: 'Le calme en rangs bien droits', color: '#8e7cc3',
    desc: 'Elle aime les sols pauvres, le plein soleil et la sécheresse, et on la plante en rangs impeccables. Son parfum apaise, éloigne les mites, et on en glisse des sachets dans les armoires. Elle met de l\'ordre et de la sérénité partout où elle passe, et déteste qu\'on vienne bousculer ses habitudes.',
    t: { ste: 0.95, san: 0.9, ord: 0.8, rig: 0.7, vse: 0.8, vst: 0.1, cfl: 0.1, aud: 0.15, care: 0.7, inf: 0.3 } },
  { name: 'Le coquelicot', by: 'Fleur sauvage · bords des champs', cat: 'Fleurs', tag: 'L\'éclat qui surgit où on ne l\'attend pas', color: '#e0301e',
    desc: 'Ses graines peuvent dormir des décennies dans le sol et ne germent que lorsqu\'on retourne la terre. Il surgit alors par milliers, puis ses pétales froissés tombent en un jour, et il fane aussitôt cueilli. Il ne se laisse ni domestiquer ni mettre en vase : il vit fort, vite, librement, et s\'en va comme il est venu.',
    t: { vst: 0.9, chg: 0.9, ord: 0.05, tmp: 0.05, rsk: 0.85, lib: 0.9, vse: 0.1, con: 0.1, ide: 0.7, loc: 0.7 } },
  { name: 'Le muguet', by: 'Fleur · sous-bois', cat: 'Fleurs', tag: 'Le porte-bonheur fidèle au rendez-vous', color: '#e9f0dc',
    desc: 'Il revient chaque printemps au même endroit, s\'étend doucement par ses racines, et on se l\'offre le premier mai. Derrière ses clochettes délicates, il est pourtant toxique de la racine à la baie. Discret, fidèle aux traditions et aux gens qu\'il aime, il sait aussi se protéger quand il le faut.',
    t: { vtr: 0.95, att: 0.8, fia: 0.8, inf: 0.2, dom: 0.1, vig: 0.7, opt: 0.7, ste: 0.8, vst: 0.2, sanc: 0.6 } },
  { name: 'La violette', by: 'Fleur · talus et sous-bois', cat: 'Fleurs', tag: 'La timidité qui sent bon', color: '#6a4c9c',
    desc: 'Elle se cache sous ses feuilles, au ras du sol, et produit même des fleurs qui ne s\'ouvrent jamais et se fécondent en secret. On ne la remarque qu\'à son parfum. Elle ressent beaucoup, parle peu, fuit les projecteurs et la compétition, et a un monde intérieur bien plus riche qu\'on ne l\'imagine.',
    t: { inf: 0.02, soc: 0.1, emp: 0.9, dom: 0.05, ste: 0.85, aud: 0.1, ide: 0.8, ind: 0.6, cfl: 0.05, vpo: 0.05 } },
  { name: 'L\'orchidée', by: 'Fleur · forêts tropicales et prairies', cat: 'Fleurs', tag: 'La stratège sophistiquée', color: '#b14fb5',
    desc: 'Ses graines, fines comme de la poussière, ne germent qu\'avec l\'aide d\'un champignon, et certaines espèces imitent l\'allure et l\'odeur d\'un insecte femelle pour attirer leurs pollinisateurs. Raffinée, calculée, elle obtient ce qu\'elle veut par la séduction et la finesse, mais elle a besoin d\'un environnement parfaitement réglé.',
    t: { aff: 0.85, dip: 0.85, vpo: 0.75, rig: 0.85, ind: 0.15, inc: 0.1, rsk: 0.3, vac: 0.8, soc: 0.6, ste: 0.25 } },
  { name: 'Le lotus', by: 'Fleur aquatique · étangs d\'Asie', cat: 'Fleurs', tag: 'La pureté qui sort de la vase', color: '#e79bb4',
    desc: 'Il pousse dans la boue et en ressort immaculé : ses feuilles repoussent l\'eau et la saleté. Une graine vieille de plus de mille ans a même réussi à germer. Symbole spirituel dans une bonne partie de l\'Asie, il cherche le sens plutôt que le confort ou le prestige, et garde son calme au milieu du chaos.',
    t: { sanc: 0.98, ide: 0.9, san: 0.9, ouv: 0.7, vhe: 0.15, vpo: 0.05, cfl: 0.1, epi: 0.85, tmp: 0.9, vun: 0.85 } },
  { name: 'Le nénuphar', by: 'Fleur aquatique · mares et étangs', cat: 'Fleurs', tag: 'Celui qui se laisse porter', color: '#f3e2a9',
    desc: 'Il flotte à la surface d\'une eau tranquille, s\'ouvre au soleil et se referme le soir, et Monet a passé des années à le peindre. Il ne lutte contre rien, ne cherche rien à conquérir : il suit le mouvement de l\'eau et profite du moment. Une présence apaisante, peu pressée de prendre une décision.',
    t: { ste: 0.95, loc: 0.9, rsk: 0.05, cfl: 0.05, dom: 0.05, vhe: 0.75, vst: 0.15, san: 0.85, det: 0.2, cmp: 0.05 } },
  { name: 'La tulipe', by: 'Fleur à bulbe · Pays-Bas', cat: 'Fleurs', tag: 'Le prestige qui a affolé la Bourse', color: '#e23d6a',
    desc: 'Au XVIIe siècle, en Hollande, un seul de ses bulbes a pu valoir le prix d\'une maison : on appelle cet emballement la tulipomanie. Elle a besoin d\'un vrai hiver pour fleurir, puis se dresse, nette, colorée, impossible à ignorer. Elle aime briller, gagner et être vue, et sait parfaitement ce qu\'elle vaut.',
    t: { vpo: 0.9, vac: 0.9, cmp: 0.85, inf: 0.8, rig: 0.7, vst: 0.7, vun: 0.1, care: 0.3, dom: 0.75, ord: 0.6 } },
  { name: 'La pivoine', by: 'Fleur · jardins de grand-mère', cat: 'Fleurs', tag: 'La générosité enracinée', color: '#f07fa0',
    desc: 'Plantée au bon endroit, elle peut fleurir pendant cinquante ans au même endroit, mais elle déteste qu\'on la déplace. Ses fleurs énormes, parfumées, presque trop pleines, sont un pur plaisir. Elle aime son coin, les gens qui y passent et les bonnes choses de la vie, et ne voit aucune raison de changer ce qui marche.',
    t: { vhe: 0.95, att: 0.9, opn: 0.95, chg: 0.05, vst: 0.15, inf: 0.75, rsk: 0.2, vtr: 0.7, tmp: 0.7, soc: 0.7 } },
  { name: 'L\'hortensia', by: 'Fleur · jardins de Bretagne', cat: 'Fleurs', tag: 'Le caméléon qui prend la couleur du sol', color: '#6f8fd6',
    desc: 'Chez beaucoup de variétés, la couleur de ses fleurs dépend de la terre où il pousse : bleu en sol acide, rose en sol calcaire. Il s\'accorde à son entourage, arrondit les angles et trouve sa place partout. Pas de positions tranchées chez lui : il écoute, s\'adapte et se méfie des certitudes.',
    t: { loc: 0.95, dip: 0.9, inc: 0.85, dog: 0.05, cfl: 0.05, soc: 0.8, ind: 0.15, com: 0.1, ouv: 0.8, epi: 0.2 } },
  { name: 'Le jasmin', by: 'Fleur grimpante · jardins d\'Orient', cat: 'Fleurs', tag: 'Le parfum qui s\'éveille la nuit', color: '#f5f0dc',
    desc: 'Chez plusieurs espèces, son parfum devient plus intense le soir, quand la chaleur retombe, et il grimpe discrètement le long des murs des patios. On ne le voit pas toujours, on le sent partout. Sensuel, rêveur, il suit ses envies plutôt qu\'un planning et vit ses émotions avec une intensité toute nocturne.',
    t: { vhe: 0.98, ide: 0.75, aff: 0.05, att: 0.85, vst: 0.7, ord: 0.2, rig: 0.15, soc: 0.4, con: 0.2, san: 0.4 } },
  { name: 'Le mimosa', by: 'Arbuste en fleurs · Côte d\'Azur', cat: 'Fleurs', tag: 'Le soleil en plein hiver', color: '#f7d417',
    desc: 'Arrivé d\'Australie, il fleurit en plein hiver, quand tout est gris, et s\'est si bien plu dans le Sud qu\'il y envahit des massifs entiers. Après un incendie, ses graines germent de plus belle. Il apporte la joie là où on ne l\'attendait pas, s\'installe partout avec aplomb et ne regarde jamais en arrière.',
    t: { opt: 0.95, vst: 0.85, inf: 0.85, chg: 0.75, rsk: 0.8, opn: 0.1, vis: 0.1, con: 0.2, vse: 0.2, dom: 0.6 } },
  { name: 'La glycine', by: 'Liane · façades et pergolas', cat: 'Fleurs', tag: 'L\'étreinte qui ne lâche pas', color: '#9b8ed8',
    desc: 'Elle peut mettre des années avant de fleurir, puis elle s\'enroule, s\'épaissit et devient si puissante qu\'elle tord les gouttières et soulève les tuiles. Certaines vivent plus d\'un siècle. Elle aime passionnément, fidèlement, durablement, mais son amour prend de la place, et elle a du mal à laisser respirer ce qu\'elle tient.',
    t: { att: 0.98, dom: 0.8, tmp: 0.9, det: 0.9, loy: 0.9, ind: 0.1, vpo: 0.6, dip: 0.2, lib: 0.15, cmp: 0.6 } },
  { name: 'L\'edelweiss', by: 'Fleur · haute montagne', cat: 'Fleurs', tag: 'La solitaire des sommets', color: '#e8e6dc',
    desc: 'Elle pousse là où presque rien ne pousse, sur des éboulis d\'altitude, protégée du froid et des UV par un duvet laineux. Rare, protégée, longtemps cueillie par les alpinistes comme une preuve d\'audace. Elle n\'a besoin de personne, préfère les hauteurs à la foule et considère le danger comme une partie du paysage.',
    t: { ind: 0.95, rsk: 0.9, aud: 0.9, soc: 0.1, col: 0.05, vst: 0.85, san: 0.85, att: 0.3, vsd: 0.95, vse: 0.2 } },
  { name: 'La pâquerette', by: 'Fleur sauvage · pelouses', cat: 'Fleurs', tag: 'La joie simple qui repousse toujours', color: '#f6f1e7',
    desc: 'Elle fleurit presque toute l\'année, se referme la nuit et quand il pleut, et sa rosette plaquée au sol laisse passer la tondeuse sans broncher. Personne ne la plante, personne ne la remarque, et elle s\'en moque. Elle ne cherche ni gloire ni victoire, elle se contente d\'être là, contente, et c\'est déjà beaucoup.',
    t: { opt: 0.9, soc: 0.8, ste: 0.85, vpo: 0.02, vac: 0.1, cmp: 0.05, dog: 0.05, rig: 0.2, inc: 0.7, vhe: 0.65 } },
  { name: 'Le perce-neige', by: 'Fleur à bulbe · fin d\'hiver', cat: 'Fleurs', tag: 'L\'espoir qui passe à travers la neige', color: '#dfe9ef',
    desc: 'Il fleurit à la fin de l\'hiver, parfois à travers la neige, bien avant que le printemps ne soit acquis. Sa petite clochette penchée annonce que le froid ne durera pas. Il refuse d\'attendre que les conditions soient idéales pour y croire, et il se lève le premier pour donner du courage aux autres.',
    t: { det: 0.95, opt: 0.85, vis: 0.05, aud: 0.75, eng: 0.7, ide: 0.85, san: 0.7, vhe: 0.15, loc: 0.1, chg: 0.7 } },
  { name: 'L\'iris', by: 'Fleur · berges et jardins royaux', cat: 'Fleurs', tag: 'Le port royal', color: '#4b3f9e',
    desc: 'On dit que la fleur de lys des rois de France serait un iris stylisé, et son nom vient de la messagère des dieux grecs. Il se tient droit, ses rhizomes s\'installent solidement, et il revient chaque année à sa place. Il a naturellement de l\'autorité, le sens du rang et de la loyauté, et un certain goût pour le protocole.',
    t: { auth: 0.9, vtr: 0.85, lea: 0.85, dom: 0.8, vpo: 0.8, loy: 0.85, sanc: 0.6, chg: 0.1, inf: 0.6, ouv: 0.3 } },
  { name: 'La reine de la nuit', by: 'Cactus à fleurs · forêts tropicales', cat: 'Fleurs', tag: 'Une seule nuit, mais quelle nuit', color: '#f4e9d2',
    desc: 'Cette plante grimpante de la famille des cactus ouvre ses immenses fleurs parfumées une seule nuit par an : au matin, elles sont déjà fanées. Ceux qui veulent la voir veillent exprès. Elle vit par éclats rares, secrets et intenses, se fiche des horaires, et préfère une nuit inoubliable à mille jours ordinaires.',
    t: { vst: 0.98, vhe: 0.9, tmp: 0.02, rsk: 0.85, ord: 0.05, vse: 0.05, ind: 0.85, soc: 0.15, aff: 0.1, ide: 0.8 } },

  /* ---------------- Plantes et herbes ---------------- */
  { name: 'Le cactus', by: 'Succulente · déserts d\'Amérique', cat: 'Plantes et herbes', tag: 'L\'autonomie derrière les piquants', color: '#4f8a4b',
    desc: 'Ses épines sont des feuilles transformées, son corps un réservoir d\'eau, et le saguaro met des décennies avant de faire son premier bras. Il se suffit à lui-même, se méfie de ceux qui s\'approchent trop près et ne demande rien à personne. Pas très câlin, mais capable de tenir là où tout le monde abandonne.',
    t: { ind: 0.95, soc: 0.05, att: 0.1, nat: 0.9, vse: 0.85, san: 0.9, emp: 0.2, com: 0.7, det: 0.85, tmp: 0.8, vhe: 0.1 } },
  { name: 'L\'aloe vera', by: 'Succulente · rebords de fenêtre', cat: 'Plantes et herbes', tag: 'Le soigneur discret', color: '#7fb38a',
    desc: 'On casse une feuille, on pose le gel sur la brûlure, et ça soulage : depuis l\'Antiquité on l\'utilise pour apaiser la peau. Il demande très peu d\'eau et encore moins d\'attention. Il prend soin des autres sans bruit, ne réclame aucune reconnaissance et reste parfaitement calme quand quelqu\'un a mal.',
    t: { care: 0.95, emp: 0.9, vbe: 0.9, inf: 0.1, vpo: 0.05, dom: 0.1, ste: 0.85, fia: 0.9, vac: 0.15, san: 0.8 } },
  { name: 'Le monstera', by: 'Plante d\'intérieur · forêts tropicales', cat: 'Plantes et herbes', tag: 'La star du salon', color: '#1f7a4d',
    desc: 'Ses feuilles se découpent de trous en vieillissant, il lance des racines aériennes et finit par occuper tout le coin du salon. C\'est la plante préférée des réseaux sociaux. Il a le goût de la mise en scène, aime qu\'on le regarde, prend de la place avec assurance et n\'a aucune patience pour les vieilles habitudes.',
    t: { inf: 0.95, soc: 0.9, vhe: 0.85, vac: 0.75, dom: 0.75, vpo: 0.7, aud: 0.7, ste: 0.2, vtr: 0.1, con: 0.2 } },
  { name: 'La dionée', by: 'Plante carnivore · marais de Caroline', cat: 'Plantes et herbes', tag: 'Le piège qui sait compter', color: '#9e2a2b',
    desc: 'Son piège ne se referme que si un insecte touche deux de ses poils en quelques secondes : elle compte, pour ne pas gaspiller son énergie sur une goutte de pluie. Puis elle serre et digère. Froide, patiente, calculatrice, elle observe beaucoup, ne s\'emballe jamais, et frappe au moment exact où c\'est rentable.',
    t: { aff: 0.95, vig: 0.95, nat: 0.9, san: 0.95, rig: 0.85, cmp: 0.85, emp: 0.1, care: 0.1, soc: 0.15, dom: 0.7 } },
  { name: 'La fougère', by: 'Plante à spores · sous-bois humides', cat: 'Plantes et herbes', tag: 'La vieille âme de l\'ombre', color: '#3f7a3a',
    desc: 'Elle était là bien avant les dinosaures, ne fait ni fleurs ni graines et se reproduit par des spores minuscules. Elle aime l\'ombre et l\'humidité et déroule lentement ses crosses au printemps. Elle se tient loin de l\'agitation et du paraître, fidèle à ce qu\'elle a toujours été, et pas du tout pressée.',
    t: { soc: 0.1, inf: 0.05, vst: 0.1, tmp: 0.9, ste: 0.9, vtr: 0.8, aud: 0.1, vpo: 0.05, ind: 0.7, opn: 0.8, ouv: 0.3 } },
  { name: 'La mousse', by: 'Plante sans racines · rochers et troncs', cat: 'Plantes et herbes', tag: 'La force des petits qui se serrent', color: '#6a8f3c',
    desc: 'Elle n\'a ni racines ni vaisseaux, peut sécher complètement pendant des mois et reverdir en quelques heures quand la pluie revient. Seule, elle n\'est rien ; en tapis, elle retient l\'eau de forêts entières. Elle ne cherche ni pouvoir ni premier rôle, attend son heure sans angoisse et compte sur le collectif.',
    t: { col: 0.95, rsk: 0.1, loc: 0.8, inc: 0.8, ste: 0.9, vpo: 0.02, dom: 0.02, cmp: 0.02, san: 0.85, opt: 0.7 } },
  { name: 'Le lierre', by: 'Liane · murs et vieux arbres', cat: 'Plantes et herbes', tag: 'La fidélité qui s\'accroche', color: '#2e5e3a',
    desc: 'Il grimpe grâce à de petites racines crampons mais ne vole rien à l\'arbre qui le porte : ce n\'est pas un parasite. Toujours vert, il fleurit en automne et nourrit les insectes quand tout le reste a fini, et il peut vivre plusieurs siècles. Il s\'attache pour de bon, reste quand les autres partent, et ne sait pas trop vivre seul.',
    t: { att: 0.98, loy: 0.95, fia: 0.95, ind: 0.05, tmp: 0.9, vse: 0.8, lib: 0.2, chg: 0.1, dom: 0.2, care: 0.75 } },
  { name: 'La menthe', by: 'Aromatique · jardins potagers', cat: 'Plantes et herbes', tag: 'L\'énergie qui envahit tout', color: '#3fbf7f',
    desc: 'Plantez-en un pied, et ses tiges souterraines coloniseront le potager entier en une saison : les jardiniers avisés la mettent en pot. Fraîche, vive, elle relève tout ce qu\'elle touche. Elle déborde d\'énergie, parle fort, occupe l\'espace sans demander, et se moque des plates-bandes bien alignées.',
    t: { inf: 0.9, vst: 0.85, dom: 0.85, cmp: 0.8, ord: 0.1, aud: 0.8, soc: 0.85, con: 0.1, dip: 0.2, chg: 0.7 } },
  { name: 'Le basilic', by: 'Aromatique · cuisines du Sud', cat: 'Plantes et herbes', tag: 'Le bon vivant frileux', color: '#4c9a2a',
    desc: 'Il lui faut de la chaleur, du soleil et une terre ni trop sèche ni détrempée : au premier coup de froid, il noircit. Mais bien installé, il parfume toute la cuisine. Il adore les repas qui s\'éternisent, les gens qu\'il aime autour de la table, et il préfère nettement le confort de la maison aux expéditions hasardeuses.',
    t: { vhe: 0.95, soc: 0.9, att: 0.85, san: 0.15, thr: 0.7, vse: 0.75, rsk: 0.15, opn: 0.7, inf: 0.7, emp: 0.7 } },
  { name: 'L\'ortie', by: 'Plante sauvage · friches et talus', cat: 'Plantes et herbes', tag: 'Le franc-parler qui cache un grand cœur', color: '#557a2c',
    desc: 'Ses poils piquent et brûlent au moindre contact, mais elle est nourrissante, soigne, et ses feuilles nourrissent les chenilles de plusieurs papillons. Elle pousse là où la terre est riche et dit les choses sans enrober. On s\'y frotte rarement deux fois, et pourtant, ceux qui la connaissent savent tout ce qu\'elle donne.',
    t: { com: 0.95, cfl: 0.95, dip: 0.05, care: 0.8, fair: 0.8, nat: 0.6, eng: 0.8, vco: 0.1, dom: 0.7, ide: 0.6 } },
  { name: 'Le trèfle', by: 'Plante des prairies', cat: 'Plantes et herbes', tag: 'Celui qui enrichit la terre des autres', color: '#4aa35a',
    desc: 'Grâce à des bactéries logées dans ses racines, il capte l\'azote de l\'air et fertilise le sol pour les plantes voisines. On cherche surtout sa rarissime feuille à quatre folioles, mais son vrai talent est ailleurs : améliorer la vie de ceux qui l\'entourent, sans compétition et sans rien réclamer en échange.',
    t: { vbe: 0.9, col: 0.95, cmp: 0.05, care: 0.9, fair: 0.9, vun: 0.85, dom: 0.1, vpo: 0.05, opt: 0.8, dip: 0.8 } },
  { name: 'Le pissenlit', by: 'Plante sauvage · partout', cat: 'Plantes et herbes', tag: 'La liberté qui part au vent', color: '#f2c30f',
    desc: 'Ses graines s\'envolent au moindre souffle et peuvent atterrir très loin, et un bout de racine oublié dans la terre suffit à le faire repousser. Il perce le bitume, ignore les pelouses interdites et se rit des désherbants. Personne ne lui dit où pousser : il va où le vent le porte et s\'enracine là où il décide.',
    t: { lib: 0.98, vsd: 0.95, rsk: 0.85, opn: 0.02, vse: 0.1, auth: 0.05, vco: 0.05, det: 0.85, loc: 0.75, chg: 0.8 } },
  { name: 'Le chardon', by: 'Plante sauvage · landes et pâtures', cat: 'Plantes et herbes', tag: 'La fierté qui ne se laisse pas toucher', color: '#8a5ca8',
    desc: 'Il est hérissé de piquants de la tige à la fleur, et l\'Écosse en a fait son emblème, avec une devise qui promet que nul ne le touche impunément. Les chardonnerets, eux, viennent picorer ses graines en toute confiance. Farouchement loyal envers les siens, il se méfie de tout le reste et ne recule jamais.',
    t: { nat: 0.95, loy: 0.95, com: 0.9, cfl: 0.85, vig: 0.85, opn: 0.9, dip: 0.1, soc: 0.2, emp: 0.3, auth: 0.6, ind: 0.7 } },
  { name: 'La ronce', by: 'Plante sauvage · haies et friches', cat: 'Plantes et herbes', tag: 'La conquête sans état d\'âme', color: '#4a2a3a',
    desc: 'Ses longues tiges épineuses retombent au sol, s\'y enracinent par la pointe et repartent plus loin : en quelques années, elle forme un fourré impénétrable. Elle offre des mûres à qui ose s\'y frotter. Elle avance, conquiert, ne demande pas la permission, et se soucie assez peu de ce qu\'elle écrase en chemin.',
    t: { dom: 0.95, cmp: 0.95, vpo: 0.85, det: 0.9, ord: 0.1, dip: 0.05, emp: 0.1, care: 0.15, rsk: 0.8, aud: 0.85 } },
  { name: 'La vigne', by: 'Liane · coteaux', cat: 'Plantes et herbes', tag: 'Le plaisir qui se mérite', color: '#6b1f3a',
    desc: 'Elle s\'accroche par ses vrilles, se taille chaque hiver, et les grands vins viennent souvent de ceps qui ont souffert sur des sols pauvres. Certains ceps ont plus d\'un siècle. Elle aime les plaisirs de la vie, mais ceux qu\'on a patiemment travaillés, transmis, respectés : le temps et la rigueur sont ses meilleurs ingrédients.',
    t: { tmp: 0.9, vtr: 0.9, vhe: 0.9, rig: 0.8, vac: 0.75, san: 0.7, vst: 0.25, chg: 0.15, det: 0.8, ord: 0.75 } },
  { name: 'Le gui', by: 'Plante semi-parasite · cimes des arbres', cat: 'Plantes et herbes', tag: 'Le charmeur qui vit chez les autres', color: '#c9d68a',
    desc: 'Il fait sa propre photosynthèse mais puise l\'eau et les sels minéraux de l\'arbre qui l\'héberge, et ce sont les oiseaux qui sèment ses graines de branche en branche. Les druides le cueillaient comme une plante sacrée, et on s\'embrasse encore dessous. Charmant, un peu opportuniste, il sait se rendre indispensable aux bonnes personnes.',
    t: { sanc: 0.9, fair: 0.15, care: 0.2, dip: 0.8, vhe: 0.75, vtr: 0.7, loc: 0.75, aff: 0.75, soc: 0.7, ind: 0.2 } },
  { name: 'La sensitive', by: 'Mimosa pudica · régions tropicales', cat: 'Plantes et herbes', tag: 'Celle qui se referme au moindre contact', color: '#d98fb6',
    desc: 'Effleurez une de ses feuilles : en quelques secondes, les folioles se replient et le rameau s\'affaisse. Des expériences ont montré qu\'elle cesse de se refermer quand on lui répète un choc sans danger, comme si elle apprenait à faire confiance. Elle perçoit tout, se protège d\'instinct, puis s\'ouvre à nouveau quand elle se sent en sécurité.',
    t: { thr: 0.95, emp: 0.98, san: 0.05, vig: 0.9, inc: 0.1, rsk: 0.05, aud: 0.05, att: 0.8, aff: 0.05, ide: 0.8 } },
  { name: 'Le bambou', by: 'Graminée géante · forêts d\'Asie', cat: 'Plantes et herbes', tag: 'La réussite qui plie sans rompre', color: '#7aa13a',
    desc: 'Chez certaines espèces, une jeune pousse peut grandir de près d\'un mètre par jour, et sa tige creuse plie sous la tempête sans casser. Toute une forêt de bambous peut sortir d\'un même réseau de rhizomes. Il vise vite et haut, s\'adapte à tout ce qui arrive, et avance en bloc avec les siens.',
    t: { vac: 0.95, det: 0.9, dip: 0.8, inc: 0.8, dog: 0.1, cmp: 0.8, col: 0.8, chg: 0.75, vst: 0.6, vtr: 0.3 } },
  { name: 'La tomate', by: 'Plante potagère · jardins d\'été', cat: 'Plantes et herbes', tag: 'La générosité qui a besoin d\'un tuteur', color: '#e0402a',
    desc: 'Elle réclame du soleil, de l\'eau, un tuteur et un jardinier attentif, mais une fois bien entourée, elle donne des fruits sans compter tout l\'été. Botaniquement, c\'est d\'ailleurs un fruit. Elle ne prétend pas s\'en sortir seule : elle s\'épanouit grâce aux autres, et le leur rend au centuple autour d\'une bonne table.',
    t: { vhe: 0.9, loc: 0.9, att: 0.85, ind: 0.05, vse: 0.7, opt: 0.8, soc: 0.85, vbe: 0.85, vsd: 0.15, ste: 0.7 } },
  { name: 'Le pothos', by: 'Plante d\'intérieur · bureaux et étagères', cat: 'Plantes et herbes', tag: 'L\'increvable décontracté', color: '#8bbf4a',
    desc: 'Coin sombre, arrosage oublié, déménagement, bureau climatisé : il survit à tout et continue de laisser pendre ses tiges. Une bouture dans un verre d\'eau suffit à le multiplier. Rien ne le stresse, il s\'accommode de tout le monde et de toutes les situations, et sa bonne humeur ne demande pratiquement aucun entretien.',
    t: { inc: 0.95, ste: 0.9, opt: 0.8, san: 0.9, thr: 0.05, vig: 0.1, con: 0.15, rig: 0.1, dog: 0.05, dip: 0.75, loc: 0.7 } },
];

window.PRISME_PLANTS = { PLANTS };
