/* ============================================================
   PRISME — familles politiques, tempéraments, phrases de résumé
   ============================================================ */

// Familles politiques : vecteur sur les 8 axes politiques (-1 → 1)
const FAMILIES = [
  { name: 'Communiste', tag: 'Anticapitaliste',
    v: { eco: -1, egl: -1, soc: -0.5, idn: -0.8, aut: 0.3, env: 0.3, geo: 0.3, jus: -0.5, tec: 0.1 },
    desc: 'La propriété collective des moyens de production avant tout ; l\'État comme outil de la classe travailleuse.' },
  { name: 'Socialiste', tag: 'Gauche radicale',
    v: { eco: -0.85, egl: -0.9, soc: -0.8, idn: -0.8, aut: -0.4, env: 0.6, geo: -0.1, jus: -0.8, tec: 0.3 },
    desc: 'Redistribution forte, émancipation sociale et rupture avec le néolibéralisme.' },
  { name: 'Social-démocrate', tag: 'Gauche de gouvernement',
    v: { eco: -0.4, egl: -0.5, soc: -0.5, idn: -0.5, aut: -0.1, env: 0.4, geo: -0.6, jus: -0.4, tec: -0.2 },
    desc: 'Corriger le marché par l\'État-providence, sans le renverser ; ouverture au monde et à l\'Europe.' },
  { name: 'Écologiste', tag: 'Écologie politique',
    v: { eco: -0.5, egl: -0.6, soc: -0.7, idn: -0.6, aut: -0.4, env: 1, geo: -0.4, jus: -0.6, tec: 0.5 },
    desc: 'Le vivant et les limites planétaires comme boussole ; sobriété, démocratie locale, justice sociale.' },
  { name: 'Décroissant', tag: 'Écologie radicale',
    v: { eco: -0.7, egl: -0.8, soc: -0.3, idn: -0.2, aut: -0.3, env: 1, geo: 0.3, jus: -0.5, tec: 0.9 },
    desc: 'Sortir du productivisme et du culte de la technique ; relocaliser, ralentir, réparer.' },
  { name: 'Populiste de gauche', tag: 'Souverainisme social',
    v: { eco: -0.8, egl: -0.7, soc: -0.2, idn: -0.1, aut: 0.1, env: 0.4, geo: 0.7, jus: -0.2, tec: 0.2 },
    desc: 'Le peuple contre les élites mondialisées ; protection sociale et souveraineté nationale vont ensemble.' },
  { name: 'Anarchiste', tag: 'Libertaire',
    v: { eco: -0.8, egl: -0.9, soc: -0.8, idn: -0.7, aut: -1, env: 0.6, geo: -0.2, jus: -0.9, tec: 0.3 },
    desc: 'Ni Dieu ni maître : auto-organisation, abolition des hiérarchies, méfiance envers tout pouvoir.' },
  { name: 'Libéral progressiste', tag: 'Centre',
    v: { eco: 0.5, egl: 0.4, soc: -0.4, idn: -0.5, aut: 0.1, env: 0.1, geo: -0.8, jus: 0, tec: -0.6 },
    desc: 'Liberté économique et liberté des mœurs ; Europe, innovation, réformes.' },
  { name: 'Technocrate', tag: 'Centre gestionnaire',
    v: { eco: 0.3, egl: 0.5, soc: -0.2, idn: -0.3, aut: 0.3, env: 0.2, geo: -0.7, jus: 0.1, tec: -0.7 },
    desc: 'Gouverner par la compétence et les données ; l\'efficacité plutôt que les passions.' },
  { name: 'Libertarien', tag: 'Ultra-libéral',
    v: { eco: 1, egl: 0.8, soc: -0.3, idn: -0.3, aut: -1, env: -0.4, geo: -0.3, jus: -0.1, tec: -0.8 },
    desc: 'L\'individu souverain ; l\'État réduit au strict minimum ; le marché comme espace de liberté.' },
  { name: 'Conservateur libéral', tag: 'Droite classique',
    v: { eco: 0.6, egl: 0.6, soc: 0.6, idn: 0.4, aut: 0.5, env: -0.3, geo: 0.1, jus: 0.6, tec: -0.3 },
    desc: 'Économie de marché, ordre, valeurs traditionnelles et nation ; le changement avec prudence.' },
  { name: 'Souverainiste', tag: 'National-populiste',
    v: { eco: -0.1, egl: 0.2, soc: 0.7, idn: 0.9, aut: 0.6, env: -0.3, geo: 1, jus: 0.8, tec: 0.1 },
    desc: 'La nation d\'abord : frontières, identité, autorité, protection du peuple contre l\'extérieur.' },
  { name: 'Traditionaliste', tag: 'Conservateur intégral',
    v: { eco: 0.2, egl: 0.5, soc: 1, idn: 0.7, aut: 0.7, env: 0, geo: 0.5, jus: 0.7, tec: 0.6 },
    desc: 'La transmission, la famille, le sacré et l\'enracinement contre la modernité liquide.' },
];

// Tempéraments : vecteur sur les 6 axes méta (-1 → 1)
const TEMPERAMENTS = [
  { name: 'Le Bâtisseur', v: { epi: -0.7, chg: -0.8, dem: 0, cfl: -0.7, vis: -0.6, nat: -0.3 },
    desc: 'Tu avances pierre après pierre. Ce qui marche prime sur ce qui brille, et tu crois qu\'on construit mieux ensemble que contre.' },
  { name: 'Le Tribun', v: { epi: 0.7, chg: 0.7, dem: -0.8, cfl: 0.8, vis: 0.2, nat: -0.2 },
    desc: 'Tu portes la voix du nombre. La politique est un combat, le peuple a raison, et les élites doivent rendre des comptes.' },
  { name: 'Le Gardien', v: { epi: 0.6, chg: -0.6, dem: 0.5, cfl: 0.2, vis: 0.7, nat: 0.7 },
    desc: 'Tu protèges ce qui tient encore. Le monde te semble fragile, les hommes faillibles : mieux vaut conserver que risquer.' },
  { name: 'L\'Ingénieur', v: { epi: -0.9, chg: -0.5, dem: 0.8, cfl: -0.5, vis: -0.3, nat: 0.2 },
    desc: 'Tu penses en systèmes. Les bonnes décisions viennent des bonnes données, pas des bonnes intentions.' },
  { name: 'L\'Insurgé', v: { epi: 0.4, chg: 1, dem: -0.6, cfl: 0.9, vis: 0, nat: -0.4 },
    desc: 'Tu ne réformes pas, tu renverses. Le système est le problème, et la lutte est le seul langage qu\'il comprend.' },
  { name: 'Le Sceptique', v: { epi: -0.6, chg: 0, dem: 0.1, cfl: 0.5, vis: 0.7, nat: 0.9 },
    desc: 'Tu ne crois ni aux sauveurs ni aux lendemains qui chantent. Les gens sont ce qu\'ils sont ; les institutions aussi.' },
  { name: 'L\'Utopiste', v: { epi: 0.9, chg: 0.7, dem: -0.3, cfl: -0.3, vis: -0.7, nat: -0.9 },
    desc: 'Tu vises l\'horizon. L\'humain est bon, l\'avenir est ouvert, et les principes valent mieux que les calculs.' },
  { name: 'Le Médiateur', v: { epi: -0.3, chg: -0.6, dem: -0.5, cfl: -1, vis: -0.3, nat: -0.7 },
    desc: 'Tu cherches le pont. Tes adversaires ne sont pas des ennemis, et la plupart des conflits se dénouent en parlant.' },
  { name: 'Le Prophète', v: { epi: 0.9, chg: 0.7, dem: 0.2, cfl: 0.6, vis: 0.9, nat: 0.5 },
    desc: 'Tu vois venir la chute. Il faut des principes forts et une rupture nette pour éviter le pire, quitte à déranger.' },
  { name: 'Le Diplomate', v: { epi: -0.7, chg: -0.5, dem: 0.6, cfl: -0.7, vis: 0.1, nat: 0.6 },
    desc: 'Tu négocies avec le réel. Les gens sont intéressés, les problèmes complexes : reste le compromis, et la compétence.' },
];

// Archétypes psychologiques : vecteur sur les 9 axes de personnalité (-1 → 1)
const PSYCHE_TYPES = [
  { name: 'L\'Architecte', v: { aff: 0.7, loc: -0.5, rsk: -0.4, ord: 0.9, thr: 0, col: 0, tmp: 0.8, cmp: 0.2, opn: 0.2 },
    desc: 'Tu construis le futur avec un plan. Tête froide, méthode, patience : tu préfères une fondation solide à un coup d\'éclat.' },
  { name: 'Le Funambule', v: { aff: -0.3, loc: -0.6, rsk: 0.9, ord: -0.8, thr: -0.6, col: -0.3, tmp: -0.7, cmp: 0.2, opn: -0.8 },
    desc: 'Tu avances sans filet et tu aimes ça. L\'improvisation, le risque et l\'instant présent sont ton élément naturel.' },
  { name: 'Le Veilleur', v: { aff: -0.2, loc: 0.3, rsk: -0.7, ord: 0.5, thr: 0.9, col: 0.5, tmp: 0.3, cmp: 0, opn: 0.7 },
    desc: 'Tu guettes ce qui pourrait mal tourner, pour les tiens d\'abord. Prudence, racines et vigilance : tu protèges avant de conquérir.' },
  { name: 'Le Pionnier', v: { aff: 0.2, loc: -0.9, rsk: 0.8, ord: 0.1, thr: -0.5, col: -0.5, tmp: 0.4, cmp: 0.6, opn: -0.9 },
    desc: 'Tu crois que ta vie t\'appartient et tu vas la chercher. Curiosité, audace et goût de l\'inconnu : tu ouvres des chemins.' },
  { name: 'Le Pilier', v: { aff: -0.2, loc: 0, rsk: -0.6, ord: 0.7, thr: 0.2, col: 0.8, tmp: 0.5, cmp: -0.6, opn: 0.8 },
    desc: 'On peut compter sur toi. Enraciné, fiable, tourné vers le groupe : tu tiens les murs pendant que d\'autres redécorent.' },
  { name: 'Le Franc-tireur', v: { aff: 0.3, loc: -0.7, rsk: 0.5, ord: -0.4, thr: 0.3, col: -0.9, tmp: -0.2, cmp: 0.9, opn: -0.3 },
    desc: 'Tu joues ta partie, seul et pour gagner. L\'indépendance est ta valeur cardinale, la compétition ton moteur.' },
  { name: 'L\'Éponge', v: { aff: -0.9, loc: 0.6, rsk: -0.3, ord: -0.5, thr: -0.3, col: 0.5, tmp: -0.3, cmp: -0.7, opn: -0.2 },
    desc: 'Tu absorbes ce que les autres ressentent. Le cœur avant la tête, le lien avant la performance : tu vis à hauteur d\'humain.' },
  { name: 'Le Stratège', v: { aff: 0.9, loc: -0.5, rsk: 0.2, ord: 0.6, thr: 0.4, col: -0.2, tmp: 0.8, cmp: 0.7, opn: 0 },
    desc: 'Tu penses en coups d\'avance. Analytique, lucide, un peu joueur : tu ne t\'engages jamais sans avoir calculé la sortie.' },
  { name: 'Le Jardinier', v: { aff: -0.6, loc: -0.2, rsk: -0.4, ord: 0.3, thr: -0.6, col: 0.8, tmp: 0.8, cmp: -0.9, opn: 0.3 },
    desc: 'Tu fais pousser plutôt que conquérir. Patience, coopération, souci du long terme : tu travailles pour des fruits que tu ne mangeras peut-être pas.' },
  { name: 'Le Nomade', v: { aff: -0.3, loc: 0.2, rsk: 0.5, ord: -0.7, thr: -0.7, col: -0.4, tmp: -0.6, cmp: -0.3, opn: -0.9 },
    desc: 'Tu ne tiens pas en place et tu ne t\'en excuses pas. Léger, curieux, serein : le monde est un endroit à traverser, pas à défendre.' },
  { name: 'La Sentinelle', v: { aff: 0.4, loc: 0.5, rsk: -0.8, ord: 0.8, thr: 0.9, col: 0.3, tmp: 0.4, cmp: 0.3, opn: 0.6 },
    desc: 'Tu anticipes le pire avec méthode. Ordre, prudence et lucidité sur les dangers : tu es celui qui vérifie que la porte est fermée.' },
  { name: 'Le Rêveur', v: { aff: -0.8, loc: 0.5, rsk: 0.3, ord: -0.8, thr: -0.5, col: 0.2, tmp: 0.6, cmp: -0.6, opn: -0.6 },
    desc: 'Tu vis dans l\'horizon plus que dans l\'instant. Sensible, peu attaché aux règles, ouvert : tu imagines avant de mesurer.' },
];

// Signatures : combinaisons et tensions remarquables entre dimensions.
// a = axes (-1..1), f = fondements (0..1), t = traits (0..1), s = stats (0..1)
const SIGNATURES = [
  { id: 'gauche-identitaire', test: (a) => a.eco < -0.4 && a.idn > 0.4, str: (a) => -a.eco * a.idn,
    title: 'Protéger les gens et les frontières',
    text: 'Gauche sur l\'économie, droite sur l\'identité. Les partis ont du mal à incarner ce mélange, pourtant c\'est l\'un des plus répandus dans la population : tu veux un État qui redistribue et une nation qui se garde.' },
  { id: 'liberal-integral', test: (a) => a.eco > 0.4 && a.soc < -0.4, str: (a) => a.eco * -a.soc,
    title: 'Qu\'on te laisse tranquille',
    text: 'Libéral sur l\'économie et sur les mœurs : tu veux qu\'on te fiche la paix, dans ton portefeuille comme dans ta chambre. Cohérent, et plus rare qu\'on ne le croit.' },
  { id: 'etat-fort-partout', test: (a) => a.eco < -0.4 && a.aut > 0.4, str: (a) => -a.eco * a.aut,
    title: 'Un État fort, partout',
    text: 'Dans l\'économie et dans la rue. Pour toi, l\'ordre et la redistribution ne s\'opposent pas : ce sont les deux bras d\'une même puissance publique.' },
  { id: 'libertarien', test: (a) => a.eco > 0.4 && a.aut < -0.4, str: (a) => a.eco * -a.aut,
    title: 'L\'État t\'encombre',
    text: 'Moins d\'impôts, moins de police, moins de règles : tu ne fais confiance ni à l\'État-providence ni à l\'État-gendarme. Un profil libertarien assumé.' },
  { id: 'eco-techno', test: (a) => a.env > 0.5 && a.tec < -0.3, str: (a) => a.env * -a.tec,
    title: 'Écologiste par les ingénieurs',
    text: 'Tu crois qu\'on sauvera le climat avec de la technique plutôt qu\'avec des sacrifices. Rare chez les écologistes, qui se méfient souvent du progrès : toi, tu veux les deux.' },
  { id: 'eco-critique', test: (a) => a.env > 0.5 && a.tec > 0.5, str: (a) => a.env * a.tec,
    title: 'Le problème, c\'est le mode de vie',
    text: 'Écologie et critique de la technique vont ensemble chez toi : le carbone n\'est qu\'un symptôme. C\'est toute une façon de vivre, accélérée et connectée, que tu remets en cause.' },
  { id: 'compassion-fermete', test: (a, f) => f.care > 0.65 && a.jus > 0.4, str: (a, f) => f.care * a.jus,
    title: 'Compatissant, mais ferme',
    text: 'Tu es très sensible à la souffrance, et pourtant tu veux des peines lourdes. Ce n\'est pas une contradiction : ta compassion va d\'abord aux victimes, et la sanction est ta façon de la leur rendre.' },
  { id: 'compassion-reparation', test: (a, f) => f.care > 0.65 && a.jus < -0.4, str: (a, f) => f.care * -a.jus,
    title: 'Une compassion qui va jusqu\'au coupable',
    text: 'Ta sensibilité à la souffrance s\'étend à ceux qui ont fauté : pour toi, un délinquant reste quelqu\'un à réparer, pas quelqu\'à écarter.' },
  { id: 'combattant-ouvert', test: (a, f, t) => a.cfl > 0.4 && t.dog < 0.4, str: (a, f, t) => a.cfl * (1 - t.dog),
    title: 'Combattant, mais ouvert',
    text: 'Tu vois la politique comme un rapport de force, et tu restes capable de changer d\'avis. Tu te bats pour des idées, pas contre des gens — une combinaison que tes adversaires apprécient sans le dire.' },
  { id: 'consensus-certitude', test: (a, f, t) => a.cfl < -0.4 && t.dog > 0.6, str: (a, f, t) => -a.cfl * t.dog,
    title: 'Le consensus… autour de toi ?',
    text: 'Tu prônes l\'entente et tu es sûr d\'avoir raison. Attention à l\'angle mort : le consensus que tu cherches, c\'est peut-être que les autres finissent par se rallier à ta position.' },
  { id: 'peuple-si-daccord', test: (a, f, t) => a.dem < -0.4 && t.dog > 0.6, str: (a, f, t) => -a.dem * t.dog,
    title: 'Le peuple a raison (quand il pense comme toi)',
    text: 'Tu veux rendre la décision aux citoyens, et tu es très convaincu de tes propres réponses. La question qui fâche : que fais-tu le jour où le référendum dit l\'inverse de toi ?' },
  { id: 'reformateur-eclaire', test: (a) => a.dem > 0.4 && a.chg > 0.4, str: (a) => a.dem * a.chg,
    title: 'Tout changer, par le haut',
    text: 'Rupturiste et technocrate : tu veux un bouleversement, mais mené par les compétents plutôt que par la foule. Réformateur éclairé ou despote éclairé, selon qui te regarde.' },
  { id: 'pragmatique-radical', test: (a) => a.epi < -0.4 && a.chg > 0.4, str: (a) => -a.epi * a.chg,
    title: 'Une rupture sans idéologie',
    text: 'Tu ne crois plus au système actuel, mais tu ne crois pas non plus aux grands récits qui prétendent le remplacer. Tu veux que ça change parce que ça ne marche pas — pas au nom d\'une doctrine.' },
  { id: 'principes-patients', test: (a) => a.epi > 0.5 && a.chg < -0.4, str: (a) => a.epi * -a.chg,
    title: 'Des principes forts, un chemin patient',
    text: 'Tu es réformiste par conviction, pas par tiédeur. Tes valeurs ne sont pas négociables, mais tu penses qu\'elles gagnent à s\'imposer lentement, sans casser ce qui tient.' },
  { id: 'humain-oui-epoque-non', test: (a) => a.vis > 0.4 && a.nat < -0.3, str: (a) => a.vis * -a.nat,
    title: 'Les gens sont bons, c\'est le monde qui se dégrade',
    text: 'Tu fais confiance à l\'humain mais pas à l\'époque. Ton déclinisme n\'est pas de la misanthropie : c\'est le sentiment que de bonnes personnes vivent dans un système qui les abîme.' },
  { id: 'progres-malgre-les-gens', test: (a) => a.vis < -0.4 && a.nat > 0.4, str: (a) => -a.vis * a.nat,
    title: 'Le progrès malgré les gens',
    text: 'Tu ne crois pas à la bonté humaine, mais tu crois que le monde va mieux. C\'est donc aux institutions, aux règles et à la technique que tu attribues le progrès — pas aux bonnes intentions.' },
  { id: 'loyal-universaliste', test: (a, f) => f.loy > 0.65 && a.idn < -0.4, str: (a, f) => f.loy * -a.idn,
    title: 'Loyal, mais à ta tribu choisie',
    text: 'Tu places la fidélité très haut, et pourtant tu refuses de donner la priorité à ta nation. Ta tribu, ce sont ceux que tu as choisis, pas ceux qui ont le même passeport.' },
  { id: 'loyal-identitaire', test: (a, f) => f.loy > 0.65 && a.idn > 0.4, str: (a, f) => f.loy * a.idn,
    title: 'Le groupe comme refuge',
    text: 'Ta loyauté et ton attachement identitaire se renforcent mutuellement : appartenir n\'est pas un détail, c\'est ce qui te tient debout.' },
  { id: 'liberte-pour-soi', test: (a, f) => f.lib > 0.65 && a.aut > 0.3, str: (a, f) => f.lib * a.aut,
    title: 'La liberté pour toi, l\'ordre pour les autres',
    text: 'Tu détestes qu\'on te dise quoi faire, mais tu acceptes que l\'État le dise aux autres. Tension classique — et honnête : tu n\'as sans doute jamais eu affaire à la surveillance que tu approuves.' },
  { id: 'sacre-progressiste', test: (a, f) => f.sanc > 0.6 && a.soc < -0.4, str: (a, f) => f.sanc * -a.soc,
    title: 'Un sacré sans tradition',
    text: 'Tu as un sens aigu de ce qui ne doit pas être profané, et pourtant tu es progressiste. Ce que tu tiens pour sacré n\'est pas la tradition : c\'est le corps, le vivant, la dignité.' },
  { id: 'doute-du-reel', test: (a, f, t) => t.inc > 0.6 && t.dog > 0.6, str: (a, f, t) => t.inc * t.dog,
    title: 'Tu doutes du monde, pas de toi',
    text: 'Tu supportes très bien l\'incertitude sur les faits, mais peu sur tes convictions. Une position confortable, tant que personne ne te demande sur quoi elles reposent.' },
  { id: 'reperes-sans-certitude', test: (a, f, t) => t.inc < 0.4 && t.dog < 0.4, str: (a, f, t) => (1 - t.inc) * (1 - t.dog),
    title: 'Un sol stable, sans prétendre l\'avoir trouvé',
    text: 'Tu as besoin de repères, et pourtant tu changes volontiers d\'avis. Tu cherches quelque chose de solide sous tes pieds — et tu es assez honnête pour admettre que tu ne l\'as pas encore.' },
  { id: 'militant-du-doute', test: (a, f, t, s) => t.eng > 0.65 && s.nuance > 0.4, str: (a, f, t, s) => t.eng * s.nuance,
    title: 'Militant du doute',
    text: 'Tu t\'engages beaucoup pour quelqu\'un qui nuance autant. Tes camarades doivent te trouver agaçant, tes adversaires rassurant — c\'est probablement le meilleur compliment politique qui existe.' },
  { id: 'convictions-de-spectateur', test: (a, f, t, s) => t.eng < 0.35 && s.radical > 0.4, str: (a, f, t, s) => (1 - t.eng) * s.radical,
    title: 'Des convictions de spectateur',
    text: 'Des opinions très tranchées, mais peu d\'engagement. Soit tu as renoncé à peser, soit tes convictions attendent l\'occasion qui les fera sortir du salon.' },
  { id: 'souverainiste-ouvert', test: (a) => a.geo > 0.4 && a.idn < -0.3, str: (a) => a.geo * -a.idn,
    title: 'Rapatrier la démocratie, pas fermer la culture',
    text: 'Souverainiste sans être identitaire : ce que tu veux reprendre aux institutions supranationales, c\'est le pouvoir de décider — pas le droit de choisir qui est chez lui.' },
  { id: 'patriote-europeen', test: (a) => a.geo < -0.4 && a.idn > 0.4, str: (a) => -a.geo * a.idn,
    title: 'Coopérer avec le monde en restant soi',
    text: 'Mondialiste et identitaire à la fois : tu veux les grandes alliances et la culture préservée. Le profil d\'un patriote européen, à l\'aise dans les deux échelles.' },
  { id: 'pragmatique-sensible', test: (a) => a.aff < -0.4 && a.epi < -0.4, str: (a) => -a.aff * -a.epi,
    title: 'Le cœur qui juge aux résultats',
    text: 'Tu décides avec ce que tu ressens, mais tu évalues avec ce qui marche. Un pragmatique sensible : tu ne t\'embarrasses pas de doctrine, mais tu n\'oublies jamais les visages.' },
  { id: 'tete-froide-principes-durs', test: (a) => a.aff > 0.4 && a.epi > 0.4, str: (a) => a.aff * a.epi,
    title: 'Tête froide, principes durs',
    text: 'Analytique et intransigeant sur les valeurs : tu es le genre de personne qui perd rarement un débat, et parfois un ami. Tu dois l\'entendre souvent : « tu as raison, mais… »' },
  { id: 'audace-privee-prudence-publique', test: (a) => a.rsk > 0.4 && a.chg < -0.4, str: (a) => a.rsk * -a.chg,
    title: 'Audacieux pour toi, prudent pour la société',
    text: 'Tu prends des risques dans ta vie, mais tu veux que le système change lentement. Tu sais ce qu\'un pari coûte quand on le perd — et tu ne veux pas le faire payer aux autres.' },
  { id: 'prudence-privee-revolution-publique', test: (a) => a.rsk < -0.4 && a.chg > 0.4, str: (a) => -a.rsk * a.chg,
    title: 'Prudent chez toi, révolutionnaire dehors',
    text: 'Tu évites le risque dans ta vie, mais tu veux renverser le système. Soit tu penses que le vrai risque, c\'est de ne rien changer — soit tu attends que la société prenne les risques que tu ne prends pas.' },
  { id: 'menace-den-haut', test: (a) => a.thr > 0.5 && a.aut < -0.3, str: (a) => a.thr * -a.aut,
    title: 'La menace vient aussi d\'en haut',
    text: 'Tu vois le monde comme dangereux, et pourtant tu refuses la surveillance. Pour toi, l\'État n\'est pas un rempart contre les dangers : il en fait partie.' },
  { id: 'securite-premiere-liberte', test: (a) => a.thr > 0.5 && a.aut > 0.4, str: (a) => a.thr * a.aut,
    title: 'La sécurité comme première liberté',
    text: 'Tu vois le monde comme dangereux et tu veux un État qui protège. Ta vigilance personnelle et ton autoritarisme politique sont la même intuition, vue de près et de loin.' },
  { id: 'solidaire-sans-etat', test: (a) => a.col > 0.4 && a.eco > 0.4, str: (a) => a.col * a.eco,
    title: 'Solidaire, mais pas par l\'État',
    text: 'Collectiviste dans ta vie, libéral en économie : tu crois à l\'entraide, à la famille, à la communauté — mais pas quand c\'est l\'administration qui l\'organise.' },
  { id: 'individualiste-redistributeur', test: (a) => a.col < -0.4 && a.eco < -0.4, str: (a) => -a.col * -a.eco,
    title: 'Individualiste, mais redistributeur',
    text: 'Tu tiens à ta liberté personnelle et tu veux que l\'État redistribue. Pour toi, l\'égalité des moyens est la condition d\'une vraie indépendance — pas son contraire.' },
  { id: 'long-terme-inquiet', test: (a) => a.tmp > 0.5 && a.vis > 0.4, str: (a) => a.tmp * a.vis,
    title: 'Un long-termiste inquiet',
    text: 'Tu penses loin et tu vois sombre. Ton déclinisme n\'est pas de la nostalgie : c\'est de la projection. Tu as fait le calcul et il ne te plaît pas.' },
  { id: 'ecologie-sensorielle', test: (a) => a.tmp < -0.4 && a.env > 0.4, str: (a) => -a.tmp * a.env,
    title: 'Une écologie du présent',
    text: 'Écologiste qui vit dans l\'instant : ta sensibilité au vivant est immédiate, sensorielle, pas un calcul sur 2100. Tu défends la forêt parce que tu y marches.' },
  { id: 'esprit-de-clan', test: (a) => a.cmp > 0.4 && a.col > 0.4, str: (a) => a.cmp * a.col,
    title: 'Esprit de clan',
    text: 'Compétitif et collectiviste : tu ne veux pas gagner seul, tu veux que ton équipe gagne. Redoutable en groupe, un peu tribal en politique.' },
  { id: 'contexte-mais-engage', test: (a, f, t) => a.loc > 0.4 && t.eng > 0.6, str: (a, f, t) => a.loc * t.eng,
    title: 'Le contexte décide, alors tu changes le contexte',
    text: 'Tu penses que la vie est surtout affaire de milieu et de chance, et pourtant tu t\'engages. Ce n\'est pas contradictoire : c\'est parce qu\'on ne change pas le contexte seul que tu agis à plusieurs.' },
  { id: 'merite-et-redistribution', test: (a) => a.loc < -0.5 && a.eco < -0.4, str: (a) => -a.loc * -a.eco,
    title: 'Le mérite a besoin d\'un point de départ',
    text: 'Tu crois que chacun fait sa vie, et tu veux que l\'État redistribue. Pour toi, l\'égalité des chances n\'est pas l\'ennemie du mérite : c\'est ce qui le rend possible.' },
  { id: 'curieux-conservateur', test: (a) => a.opn < -0.5 && a.soc > 0.4, str: (a) => -a.opn * a.soc,
    title: 'Explorer depuis un point fixe',
    text: 'Curieux de tout, mais conservateur sur les mœurs. Tu aimes découvrir le monde — à condition d\'avoir un chez-toi qui ne bouge pas pour y revenir.' },
  { id: 'enracine-progressiste', test: (a) => a.opn > 0.5 && a.soc < -0.4, str: (a) => a.opn * -a.soc,
    title: 'Que la société change, pas mon village',
    text: 'Enraciné et progressiste : tu veux que les mœurs évoluent, mais tu tiens à tes habitudes, ton lieu, tes visages. Le progrès, oui — le déracinement, non.' },
  { id: 'coeur-froid', test: (a, f) => a.aff > 0.5 && f.care > 0.7, str: (a, f) => a.aff * f.care,
    title: 'Ému, mais pas dupe',
    text: 'Tu es très sensible à la souffrance, et tu te méfies de tes émotions. Tu as sans doute appris que la pitié fait de mauvaises politiques — et tu la ranges pour mieux servir.' },
  { id: 'audacieux-vigilant', test: (a) => a.rsk > 0.4 && a.thr > 0.4, str: (a) => a.rsk * a.thr,
    title: 'Le risque, les yeux ouverts',
    text: 'Tu vois les dangers partout et tu prends des risques quand même. Pas de l\'insouciance : du courage, ou du fatalisme — toi seul sais lequel.' },
  { id: 'structure-rupturiste', test: (a) => a.ord > 0.5 && a.chg > 0.4, str: (a) => a.ord * a.chg,
    title: 'Renverser proprement',
    text: 'Structuré et rupturiste : tu veux remplacer le système, mais avec un plan. Les révolutions que tu imagines ont des étapes numérotées.' },
  { id: 'marche-armes-egales', test: (a) => a.egl < -0.4 && a.eco > 0.3, str: (a) => -a.egl * a.eco,
    title: 'Le marché, mais à armes égales',
    text: 'Tu fais confiance au marché, et tu veux pourtant réduire les écarts. Pour toi, la concurrence n\'est juste que si tout le monde part de la même ligne : pas d\'héritiers, pas de monopoles, pas de rentiers.' },
  { id: 'etat-du-merite', test: (a) => a.egl > 0.4 && a.eco < -0.3, str: (a) => a.egl * -a.eco,
    title: 'L\'État au service du mérite',
    text: 'Tu veux un État qui intervient, mais tu ne crois pas à l\'égalité des conditions. Pour toi, la puissance publique doit organiser le mérite — écoles, concours, ascenseur social — pas l\'effacer.' },
  { id: 'egalite-entre-nous', test: (a) => a.egl < -0.45 && a.idn > 0.4, str: (a) => -a.egl * a.idn,
    title: 'L\'égalité, entre nous',
    text: 'Très égalitaire, et attaché à l\'identité nationale. L\'égalité que tu défends est un pacte entre membres d\'une même communauté, pas un principe qui s\'étendrait au monde entier.' },
  { id: 'merite-sans-passeport', test: (a) => a.egl > 0.45 && a.idn < -0.45, str: (a) => a.egl * -a.idn,
    title: 'Le mérite n\'a pas de passeport',
    text: 'Méritocrate et universaliste : peu t\'importe d\'où l\'on vient, seul compte ce qu\'on apporte. Tu refuses à la fois les privilèges de naissance et la préférence nationale.' },
  { id: 'charite-plutot-qu-egalite', test: (a, f) => a.egl > 0.45 && f.care > 0.65, str: (a, f) => a.egl * f.care,
    title: 'La charité plutôt que l\'égalité',
    text: 'Tu es très sensible à la souffrance, et pourtant tu trouves les écarts légitimes. Tu veux qu\'on aide ceux qui tombent, pas qu\'on rabote ceux qui montent.' },
  { id: 'competitif-egalitaire', test: (a) => a.egl < -0.45 && a.cmp > 0.4, str: (a) => -a.egl * a.cmp,
    title: 'Gagner, mais sur la même ligne de départ',
    text: 'Tu aimes la compétition et tu veux l\'égalité. Ce n\'est pas contradictoire : un match n\'a de valeur que si les équipes partent à égalité.' },
  { id: 'merite-et-hasard', test: (a) => a.egl > 0.45 && a.loc > 0.4, str: (a) => a.egl * a.loc,
    title: 'Récompenser le mérite dans un monde de hasard',
    text: 'Tu trouves les écarts légitimes, et tu penses pourtant que la vie est surtout affaire de milieu et de chance. Une tension à creuser : que récompense-t-on, au juste, si le mérite pèse si peu ?' },
  { id: 'curieux-du-monde-attache-au-sien', test: (a) => a.idn > 0.45 && a.opn < -0.4, str: (a) => a.idn * -a.opn,
    title: 'Curieux du monde, attaché au sien',
    text: 'Tu aimes la nouveauté et les idées qui bousculent, et tu tiens à l\'identité de ton pays. Tu voyages volontiers — à condition que la maison reste la maison.' },
  { id: 'egalitaire-autoritaire', test: (a) => a.egl < -0.5 && a.aut > 0.4, str: (a) => -a.egl * a.aut,
    title: 'L\'égalité s\'impose',
    text: 'Tu veux réduire les écarts et tu acceptes un pouvoir fort pour y arriver. Pour toi, l\'égalité ne se négocie pas avec ceux qui en profitent : elle se décrète.' },
];

// Phrases de résumé par pôle : [léger, marqué, radical]
const AXIS_PHRASES = {
  eco: {
    L: ['tu penches vers un État qui régule et redistribue',
        'tu veux un État qui pilote l\'économie et corrige fortement les inégalités',
        'tu es franchement interventionniste : le marché doit être encadré, voire remplacé, sur l\'essentiel'],
    R: ['tu fais plutôt confiance au marché et à l\'initiative privée',
        'tu crois que la liberté économique crée la prospérité et que l\'État doit s\'effacer',
        'tu es franchement libéral : moins de règles, moins d\'impôts, le marché avant l\'État'],
  },
  egl: {
    L: ['tu es sensible aux écarts entre les gens',
        'tu es égalitariste : les inégalités de conditions sont une injustice à corriger',
        'tu es radicalement égalitariste, aucune différence de mérite ne justifie de tels écarts'],
    R: ['tu penses que les écarts peuvent être légitimes',
        'tu es méritocrate : il est juste que ceux qui apportent plus reçoivent plus',
        'tu es franchement méritocrate, l\'égalité des conditions te semble un nivellement par le bas'],
  },
  soc: {
    L: ['tu regardes plutôt les évolutions de société avec bienveillance',
        'tu es progressiste : la société doit continuer à s\'émanciper des vieux cadres',
        'tu es résolument progressiste, les traditions n\'ont pas de valeur en elles-mêmes'],
    R: ['tu tiens à certains repères et traditions',
        'tu es conservateur : ce qui a tenu mérite d\'être préservé',
        'tu es profondément conservateur, la modernité te semble dissoudre ce qui compte'],
  },
  idn: {
    L: ['tu penses d\'abord en termes d\'humanité commune',
        'tu es universaliste : les mêmes droits pour tous, d\'où qu\'ils viennent',
        'tu es radicalement universaliste, les frontières entre groupes te paraissent artificielles'],
    R: ['tu accordes de l\'importance à l\'identité et à la culture du groupe',
        'tu es identitaire : le pays doit d\'abord préserver ce qu\'il est',
        'tu places l\'identité collective au cœur de tout, l\'appartenance prime sur l\'universel'],
  },
  aut: {
    L: ['tu défends la liberté individuelle face à l\'ordre',
        'tu es libertaire : le pouvoir doit être surveillé, jamais l\'inverse',
        'tu es viscéralement libertaire, toute autorité doit se justifier'],
    R: ['tu acceptes une dose d\'ordre pour la sécurité collective',
        'tu es autoritaire : l\'ordre et la discipline sont la condition de la liberté',
        'tu es franchement autoritaire, la sécurité et l\'ordre priment sur les libertés'],
  },
  env: {
    L: ['tu privilégies plutôt la croissance et l\'abondance',
        'tu es productiviste : le développement passe avant les contraintes écologiques',
        'tu es franchement productiviste, l\'écologie te semble un frein'],
    R: ['tu accordes un vrai poids à l\'écologie',
        'tu es écologiste : les limites de la planète doivent guider les choix collectifs',
        'tu es radicalement écologiste, la sobriété n\'est pas une option mais une nécessité'],
  },
  geo: {
    L: ['tu penses que les grands problèmes se règlent au-delà des frontières',
        'tu es mondialiste : la coopération internationale et l\'Europe sont la bonne échelle',
        'tu es profondément mondialiste, la nation te semble une échelle dépassée'],
    R: ['tu tiens à ce que ton pays garde la main sur ses décisions',
        'tu es souverainiste : la nation doit reprendre ce qu\'elle a cédé',
        'tu es farouchement souverainiste, les institutions supranationales sont illégitimes'],
  },
  jus: {
    L: ['tu crois plutôt à la réinsertion qu\'à la sanction',
        'tu es réhabilitateur : le crime se prévient et se répare, il ne se venge pas',
        'tu rejettes la logique punitive, la prison telle qu\'elle existe te semble un échec'],
    R: ['tu penses que la sanction doit être plus ferme',
        'tu es punitif : la peine doit dissuader et protéger la société',
        'tu es intransigeant sur la justice, les peines doivent être lourdes et exemplaires'],
  },
  tec: {
    L: ['tu regardes le progrès technique avec confiance',
        'tu es techno-optimiste : la technologie résout plus de problèmes qu\'elle n\'en crée',
        'tu es franchement techno-optimiste, l\'innovation est le moteur de l\'histoire'],
    R: ['tu gardes une distance critique face à la technologie',
        'tu es techno-critique : chaque avancée a un prix, souvent caché',
        'tu es profondément techno-critique, la technique nous aliène plus qu\'elle ne nous libère'],
  },
  epi: {
    L: ['tu juges d\'abord sur les résultats',
        'tu es pragmatique : ce qui marche vaut mieux que ce qui est pur',
        'tu es radicalement pragmatique, l\'idéologie te semble une perte de temps'],
    R: ['tu tiens à certains principes non négociables',
        'tu es idéologue au bon sens du terme : la cohérence des valeurs prime sur l\'efficacité',
        'tu es intransigeant sur les principes, le compromis te ressemble à une trahison'],
  },
  chg: {
    L: ['tu préfères améliorer par étapes',
        'tu es réformiste : les institutions se réparent, elles ne se cassent pas',
        'tu es profondément réformiste, les grands bouleversements te font peur'],
    R: ['tu penses qu\'il faut parfois changer de cadre',
        'tu es rupturiste : le système a besoin d\'être remplacé, pas rafistolé',
        'tu es franchement révolutionnaire, seul un renversement peut apporter la justice'],
  },
  dem: {
    L: ['tu fais confiance au jugement des citoyens',
        'tu es démocrate direct : le peuple doit trancher lui-même les grandes questions',
        'tu es radicalement populaire, les élites n\'ont aucune légitimité supérieure'],
    R: ['tu penses que certaines décisions demandent de l\'expertise',
        'tu es technocrate : les questions complexes doivent revenir à ceux qui les maîtrisent',
        'tu es franchement élitiste, le grand public n\'est pas armé pour décider'],
  },
  cfl: {
    L: ['tu crois qu\'on peut s\'entendre avec ses adversaires',
        'tu es consensuel : la politique est une conversation, pas une guerre',
        'tu es profondément consensuel, le conflit te semble toujours un échec'],
    R: ['tu vois la politique comme un rapport de force',
        'tu es conflictuel : les avancées s\'arrachent, elles ne se négocient pas',
        'tu es franchement combatif, il y a des camps et il faut choisir le sien'],
  },
  vis: {
    L: ['tu regardes l\'avenir avec confiance',
        'tu es optimiste : le monde va mieux et continuera d\'aller mieux',
        'tu es résolument optimiste, le déclin est une illusion'],
    R: ['tu as le sentiment que quelque chose se dégrade',
        'tu es décliniste : le meilleur est derrière nous',
        'tu es profondément décliniste, la civilisation te semble en chute'],
  },
  nat: {
    L: ['tu fais plutôt confiance aux gens',
        'tu crois en la bonté humaine : confiance et éducation transforment',
        'tu as une foi totale en l\'humain, seules les structures le corrompent'],
    R: ['tu restes prudent sur la nature humaine',
        'tu es méfiant : sans cadre, les gens suivent leur intérêt',
        'tu es profondément méfiant, l\'homme est un loup pour l\'homme'],
  },
  aff: {
    L: ['tu écoutes un peu plus ton ressenti que tes raisonnements',
        'tu décides avec le cœur : un visage te convainc plus qu\'un tableau de chiffres',
        'tu es entièrement guidé par ce que tu ressens, l\'analyse vient après, si elle vient'],
    R: ['tu préfères raisonner avant de trancher',
        'tu décides avec la tête : les émotions sont un bruit à filtrer',
        'tu es radicalement analytique, tu te méfies de tout ce qui ne se démontre pas'],
  },
  loc: {
    L: ['tu penses que ta vie dépend surtout de toi',
        'tu es acteur de ta vie : ce qui t\'arrive vient de tes choix, échecs compris',
        'tu refuses toute excuse extérieure, chacun est l\'auteur de son destin'],
    R: ['tu accordes une place au contexte et à la chance',
        'tu te sens porté par le contexte : le milieu, l\'époque et la chance pèsent plus que la volonté',
        'tu es convaincu que le destin se joue ailleurs qu\'en soi, les vies sont surtout des circonstances'],
  },
  rsk: {
    L: ['tu préfères le sûr au prometteur',
        'tu es prudent : tu vérifies tout avant de te lancer, et tu te lances rarement',
        'tu évites le risque par principe, un tiens vaut toujours mieux que deux tu l\'auras'],
    R: ['tu acceptes volontiers une part d\'incertitude',
        'tu es audacieux : l\'ennui te pèse plus que le danger',
        'tu es un joueur : tu mises gros, et tu trouves normal de perdre parfois'],
  },
  ord: {
    L: ['tu aimes garder de la souplesse',
        'tu es improvisateur : les règles s\'adaptent aux situations, pas l\'inverse',
        'tu fonctionnes dans le désordre, tout plan te semble une cage'],
    R: ['tu apprécies un cadre et un plan',
        'tu es structuré : tu tiens tes engagements et tu veux un monde bien rangé',
        'tu as un besoin absolu d\'ordre, l\'imprévu t\'est presque douloureux'],
  },
  thr: {
    L: ['tu regardes le monde sans trop d\'inquiétude',
        'tu es serein : les dangers sont exagérés, la plupart des gens ne te veulent rien',
        'tu es d\'une tranquillité totale face au monde, au point d\'en oublier de verrouiller la porte'],
    R: ['tu gardes un œil sur ce qui pourrait mal tourner',
        'tu es vigilant : le monde est dangereux et quelqu\'un cherche toujours à profiter',
        'tu vis en état d\'alerte, la menace est partout et tu protèges les tiens en priorité'],
  },
  col: {
    L: ['tu tiens à ton indépendance',
        'tu es individualiste : ta liberté passe avant les attentes du groupe',
        'tu refuses de dépendre de qui que ce soit, le groupe est une contrainte plus qu\'un refuge'],
    R: ['tu accordes du poids à ce que tu dois aux autres',
        'tu es collectiviste : le bonheur est dans les liens, le sacrifice pour le commun est naturel',
        'tu te définis par ce que tu dois aux autres, l\'individu seul n\'a guère de sens pour toi'],
  },
  tmp: {
    L: ['tu vis plutôt dans le présent',
        'tu es ancré dans l\'instant : demain est trop incertain pour lui sacrifier aujourd\'hui',
        'tu vis entièrement au présent, les projets à long terme te paraissent des abstractions'],
    R: ['tu penses volontiers à l\'avenir lointain',
        'tu es tourné vers le long terme : tu sacrifies aujourd\'hui pour dans dix ans sans hésiter',
        'tu vis dans les décennies, tu te sens responsable devant des gens qui ne sont pas nés'],
  },
  cmp: {
    L: ['tu préfères réussir avec les autres',
        'tu es coopératif : gagner seul te laisse un goût de gêne',
        'tu refuses la logique gagnants / perdants, la compétition te semble une maladie sociale'],
    R: ['la comparaison te stimule',
        'tu es compétitif : il y a des gagnants et des perdants, et tu comptes bien être du bon côté',
        'tu vis la vie comme un tournoi, la compétition est ton principal moteur'],
  },
  opn: {
    L: ['tu es attiré par ce qui est nouveau',
        'tu es explorateur : les idées qui te bousculent te font du bien, tu changerais de vie sans peur',
        'tu as une soif d\'inconnu, tout ce qui est fixe t\'ennuie et les racines t\'étouffent'],
    R: ['tu tiens à tes repères et à tes habitudes',
        'tu es enraciné : un lieu, des visages connus, des traditions qui rassurent',
        'tu as un besoin vital de racines, la nouveauté est d\'abord une menace'],
  },
};

// Textes de comparaison entre deux profils
const COMPARE_TEXT = {
  themes: {
    eco: 'l\'économie', egl: 'les inégalités', soc: 'les mœurs', idn: 'l\'identité et l\'immigration',
    aut: 'l\'ordre et les libertés', env: 'l\'écologie', geo: 'l\'Europe et la mondialisation', jus: 'la justice',
    tec: 'la technologie', epi: 'les principes', chg: 'le rythme du changement', dem: 'qui doit décider',
    cfl: 'la place du conflit', vis: 'l\'avenir', nat: 'la nature humaine', aff: 'la façon de décider',
    loc: 'la part de la chance', rsk: 'le goût du risque', ord: 'l\'ordre et l\'organisation', thr: 'la perception du danger',
    col: 'soi et les autres', tmp: 'l\'horizon de temps', cmp: 'la compétition', opn: 'la nouveauté',
  },
  clash: {
    eco: 'Un débat sur les impôts, les salaires ou les services publics risque de vite monter en température.',
    egl: 'Vous n\'avez pas la même idée de ce qui est juste : pour l\'un, les écarts sont une injustice ; pour l\'autre, une récompense.',
    soc: 'Famille, genre, religion, mœurs : les sujets de société sont votre terrain miné.',
    idn: 'Immigration, nation, appartenance : c\'est probablement le sujet qui peut le plus vous fâcher.',
    aut: 'Police, surveillance, liberté d\'expression : vous ne placez pas le curseur au même endroit.',
    env: 'Voiture, avion, viande, croissance : l\'écologie touche au quotidien, et vous ne la vivez pas pareil.',
    geo: 'Europe, libre-échange, frontières : vous ne voyez pas la même échelle pour décider.',
    jus: 'Face à un fait divers, l\'un pensera à la victime et à la sanction, l\'autre aux causes et à la réinsertion.',
    tec: 'IA, réseaux sociaux, nucléaire : l\'un voit une promesse là où l\'autre voit un piège.',
    epi: 'L\'un juge une politique à ses résultats, l\'autre à sa fidélité aux principes : vous ne parlez pas du même critère.',
    chg: 'L\'un veut réparer le système, l\'autre le remplacer : même d\'accord sur le diagnostic, vous divergerez sur le remède.',
    dem: 'Référendum ou experts ? Vous ne faites pas confiance aux mêmes pour trancher.',
    cfl: 'L\'un cherche le compromis, l\'autre le rapport de force : ce que l\'un appelle sagesse, l\'autre l\'appelle capitulation.',
    vis: 'L\'un voit le verre à moitié plein, l\'autre la fissure dans le verre : vos lectures de l\'actualité divergeront souvent.',
    nat: 'Vous n\'avez pas la même idée de ce que les gens feraient sans règles : c\'est la racine cachée de beaucoup de vos désaccords.',
    aff: 'L\'un argumente avec des histoires, l\'autre avec des chiffres : vous risquez de trouver les arguments de l\'autre hors sujet.',
    loc: 'Face à une réussite ou un échec, l\'un parlera de choix, l\'autre de circonstances.',
    rsk: 'L\'un veut tenter, l\'autre sécuriser : dans un projet commun, c\'est à la fois une force et une source de tension.',
    ord: 'L\'un a besoin d\'un plan, l\'autre de liberté de mouvement : pas le même rapport aux règles, ni aux horaires.',
    thr: 'L\'un voit le monde comme dangereux, l\'autre comme plutôt sûr : vous ne réagirez pas pareil aux mêmes nouvelles.',
    col: 'L\'un pense d\'abord à sa liberté, l\'autre à ce qu\'il doit aux autres : pas la même idée d\'une vie réussie.',
    tmp: 'L\'un vit maintenant, l\'autre pense à dans trente ans : pas les mêmes arbitrages entre plaisir et sacrifice.',
    cmp: 'L\'un veut gagner, l\'autre gagner ensemble : méfiez-vous des soirées jeux de société.',
    opn: 'L\'un cherche la nouveauté, l\'autre ses repères : l\'un s\'ennuie là où l\'autre se sent chez lui.',
  },
  common: {
    eco: 'Sur l\'économie, vous parlez la même langue.',
    egl: 'Vous partagez la même idée de ce qu\'est une répartition juste.',
    soc: 'Sur les mœurs, vous n\'aurez pas à vous justifier l\'un devant l\'autre.',
    idn: 'Sur l\'identité et l\'immigration, sujet qui divise tant, vous êtes du même côté.',
    aut: 'Vous placez la frontière entre ordre et liberté au même endroit.',
    env: 'Vous avez le même rapport à l\'écologie, ce qui simplifie les vacances et les courses.',
    geo: 'Vous êtes d\'accord sur l\'échelle à laquelle il faut décider.',
    jus: 'Face à un fait divers, vous aurez la même réaction.',
    tec: 'Vous regardez le progrès technique avec les mêmes yeux.',
    epi: 'Vous jugez les politiques avec le même critère.',
    chg: 'Vous êtes d\'accord sur le rythme auquel il faut changer les choses.',
    dem: 'Vous faites confiance aux mêmes pour trancher.',
    cfl: 'Vous avez la même idée de ce qu\'est un bon débat.',
    vis: 'Vous lisez l\'époque de la même façon.',
    nat: 'Vous avez la même idée de ce dont les gens sont capables.',
    aff: 'Vous argumentez de la même façon : vous vous comprenez vite.',
    loc: 'Vous avez le même rapport au mérite et à la chance.',
    rsk: 'Vous avez le même rapport au risque : de bons partenaires de projet.',
    ord: 'Vous avez le même rapport aux règles et à l\'organisation.',
    thr: 'Vous percevez les dangers du monde de la même façon.',
    col: 'Vous avez le même équilibre entre soi et les autres.',
    tmp: 'Vous vivez dans le même horizon de temps.',
    cmp: 'Vous avez le même rapport à la compétition.',
    opn: 'Vous avez le même goût pour la nouveauté — ou pour les repères.',
  },
  moral: {
    care: 'Face à une image de souffrance, l\'un est bouleversé quand l\'autre reste plus distant : ce n\'est pas de l\'indifférence, c\'est une autre sensibilité.',
    fair: 'L\'un est hanté par la triche et les passe-droits, l\'autre beaucoup moins : les « profiteurs » n\'éveillent pas la même colère.',
    loy: 'La fidélité au groupe ne pèse pas pareil : ce que l\'un appelle trahison, l\'autre peut l\'appeler liberté.',
    auth: 'Le respect de la hiérarchie et des traditions n\'a pas la même valeur : un manque de respect choquera l\'un bien plus que l\'autre.',
    sanc: 'L\'un a un sens aigu de ce qui ne se fait pas, même sans victime ; l\'autre juge surtout aux conséquences.',
    lib: 'L\'un supporte mal toute contrainte, l\'autre l\'accepte plus facilement : règles sanitaires ou surveillance ne vous feront pas le même effet.',
  },
};

window.PRISME_PROFILES = { FAMILIES, TEMPERAMENTS, PSYCHE_TYPES, SIGNATURES, AXIS_PHRASES, COMPARE_TEXT };
