/* ============================================================
   PRISME — familles politiques, tempéraments, phrases de résumé
   ============================================================ */

// Familles politiques : vecteur sur les 8 axes politiques (-1 → 1)
const FAMILIES = [
  { name: 'Communiste', tag: 'Anticapitaliste',
    v: { eco: -1, soc: -0.5, idn: -0.8, aut: 0.3, env: 0.3, geo: 0.3, jus: -0.5, tec: 0.1 },
    desc: 'La propriété collective des moyens de production avant tout ; l\'État comme outil de la classe travailleuse.' },
  { name: 'Socialiste', tag: 'Gauche radicale',
    v: { eco: -0.85, soc: -0.8, idn: -0.8, aut: -0.4, env: 0.6, geo: -0.1, jus: -0.8, tec: 0.3 },
    desc: 'Redistribution forte, émancipation sociale et rupture avec le néolibéralisme.' },
  { name: 'Social-démocrate', tag: 'Gauche de gouvernement',
    v: { eco: -0.4, soc: -0.5, idn: -0.5, aut: -0.1, env: 0.4, geo: -0.6, jus: -0.4, tec: -0.2 },
    desc: 'Corriger le marché par l\'État-providence, sans le renverser ; ouverture au monde et à l\'Europe.' },
  { name: 'Écologiste', tag: 'Écologie politique',
    v: { eco: -0.5, soc: -0.7, idn: -0.6, aut: -0.4, env: 1, geo: -0.4, jus: -0.6, tec: 0.5 },
    desc: 'Le vivant et les limites planétaires comme boussole ; sobriété, démocratie locale, justice sociale.' },
  { name: 'Décroissant', tag: 'Écologie radicale',
    v: { eco: -0.7, soc: -0.3, idn: -0.2, aut: -0.3, env: 1, geo: 0.3, jus: -0.5, tec: 0.9 },
    desc: 'Sortir du productivisme et du culte de la technique ; relocaliser, ralentir, réparer.' },
  { name: 'Populiste de gauche', tag: 'Souverainisme social',
    v: { eco: -0.8, soc: -0.2, idn: -0.1, aut: 0.1, env: 0.4, geo: 0.7, jus: -0.2, tec: 0.2 },
    desc: 'Le peuple contre les élites mondialisées ; protection sociale et souveraineté nationale vont ensemble.' },
  { name: 'Anarchiste', tag: 'Libertaire',
    v: { eco: -0.8, soc: -0.8, idn: -0.7, aut: -1, env: 0.6, geo: -0.2, jus: -0.9, tec: 0.3 },
    desc: 'Ni Dieu ni maître : auto-organisation, abolition des hiérarchies, méfiance envers tout pouvoir.' },
  { name: 'Libéral progressiste', tag: 'Centre',
    v: { eco: 0.5, soc: -0.4, idn: -0.5, aut: 0.1, env: 0.1, geo: -0.8, jus: 0, tec: -0.6 },
    desc: 'Liberté économique et liberté des mœurs ; Europe, innovation, réformes.' },
  { name: 'Technocrate', tag: 'Centre gestionnaire',
    v: { eco: 0.3, soc: -0.2, idn: -0.3, aut: 0.3, env: 0.2, geo: -0.7, jus: 0.1, tec: -0.7 },
    desc: 'Gouverner par la compétence et les données ; l\'efficacité plutôt que les passions.' },
  { name: 'Libertarien', tag: 'Ultra-libéral',
    v: { eco: 1, soc: -0.3, idn: -0.3, aut: -1, env: -0.4, geo: -0.3, jus: -0.1, tec: -0.8 },
    desc: 'L\'individu souverain ; l\'État réduit au strict minimum ; le marché comme espace de liberté.' },
  { name: 'Conservateur libéral', tag: 'Droite classique',
    v: { eco: 0.6, soc: 0.6, idn: 0.4, aut: 0.5, env: -0.3, geo: 0.1, jus: 0.6, tec: -0.3 },
    desc: 'Économie de marché, ordre, valeurs traditionnelles et nation ; le changement avec prudence.' },
  { name: 'Souverainiste', tag: 'National-populiste',
    v: { eco: -0.1, soc: 0.7, idn: 0.9, aut: 0.6, env: -0.3, geo: 1, jus: 0.8, tec: 0.1 },
    desc: 'La nation d\'abord : frontières, identité, autorité, protection du peuple contre l\'extérieur.' },
  { name: 'Traditionaliste', tag: 'Conservateur intégral',
    v: { eco: 0.2, soc: 1, idn: 0.7, aut: 0.7, env: 0, geo: 0.5, jus: 0.7, tec: 0.6 },
    desc: 'La transmission, la famille, le sacré et l\'enracinement contre la modernité liquide.' },
];

// Tempéraments : vecteur sur les 6 axes méta (-1 → 1)
const TEMPERAMENTS = [
  { name: 'Le Bâtisseur', v: { epi: -0.7, chg: -0.8, dem: 0, cfl: -0.7, vis: -0.6, nat: -0.3 },
    desc: 'Tu avances pierre après pierre. Ce qui marche prime sur ce qui brille, et tu crois qu\'on construit mieux ensemble que contre.' },
  { name: 'Le Tribun', v: { epi: 0.7, chg: 0.7, dem: -0.8, cfl: 0.8, vis: 0.2, nat: -0.2 },
    desc: 'Tu portes la voix du nombre. La politique est un combat, le peuple a raison, et les élites doivent rendre des comptes.' },
  { name: 'Le Gardien', v: { epi: 0.6, chg: -0.6, dem: 0.5, cfl: 0.2, vis: 0.7, nat: 0.7 },
    desc: 'Tu protèges ce qui tient encore. Le monde te semble fragile, les hommes faillibles : mieux vaut conserver que risquer.' },
  { name: 'L\'Ingénieur', v: { epi: -0.9, chg: -0.5, dem: 0.8, cfl: -0.5, vis: -0.3, nat: 0.2 },
    desc: 'Tu penses en systèmes. Les bonnes décisions viennent des bonnes données, pas des bonnes intentions.' },
  { name: 'L\'Insurgé', v: { epi: 0.4, chg: 1, dem: -0.6, cfl: 0.9, vis: 0, nat: -0.4 },
    desc: 'Tu ne réformes pas, tu renverses. Le système est le problème, et la lutte est le seul langage qu\'il comprend.' },
  { name: 'Le Sceptique', v: { epi: -0.6, chg: 0, dem: 0.1, cfl: 0.5, vis: 0.7, nat: 0.9 },
    desc: 'Tu ne crois ni aux sauveurs ni aux lendemains qui chantent. Les gens sont ce qu\'ils sont ; les institutions aussi.' },
  { name: 'L\'Utopiste', v: { epi: 0.9, chg: 0.7, dem: -0.3, cfl: -0.3, vis: -0.7, nat: -0.9 },
    desc: 'Tu vises l\'horizon. L\'humain est bon, l\'avenir est ouvert, et les principes valent mieux que les calculs.' },
  { name: 'Le Médiateur', v: { epi: -0.3, chg: -0.6, dem: -0.5, cfl: -1, vis: -0.3, nat: -0.7 },
    desc: 'Tu cherches le pont. Tes adversaires ne sont pas des ennemis, et la plupart des conflits se dénouent en parlant.' },
  { name: 'Le Prophète', v: { epi: 0.9, chg: 0.7, dem: 0.2, cfl: 0.6, vis: 0.9, nat: 0.5 },
    desc: 'Tu vois venir la chute. Il faut des principes forts et une rupture nette pour éviter le pire, quitte à déranger.' },
  { name: 'Le Diplomate', v: { epi: -0.7, chg: -0.5, dem: 0.6, cfl: -0.7, vis: 0.1, nat: 0.6 },
    desc: 'Tu négocies avec le réel. Les gens sont intéressés, les problèmes complexes : reste le compromis, et la compétence.' },
];

// Phrases de résumé par pôle : [léger, marqué, radical]
const AXIS_PHRASES = {
  eco: {
    L: ['tu penches vers un État qui régule et redistribue',
        'tu veux un État qui pilote l\'économie et corrige fortement les inégalités',
        'tu es franchement interventionniste : le marché doit être encadré, voire remplacé, sur l\'essentiel'],
    R: ['tu fais plutôt confiance au marché et à l\'initiative privée',
        'tu crois que la liberté économique crée la prospérité et que l\'État doit s\'effacer',
        'tu es franchement libéral : moins de règles, moins d\'impôts, le marché avant l\'État'],
  },
  soc: {
    L: ['tu regardes plutôt les évolutions de société avec bienveillance',
        'tu es progressiste : la société doit continuer à s\'émanciper des vieux cadres',
        'tu es résolument progressiste, les traditions n\'ont pas de valeur en elles-mêmes'],
    R: ['tu tiens à certains repères et traditions',
        'tu es conservateur : ce qui a tenu mérite d\'être préservé',
        'tu es profondément conservateur, la modernité te semble dissoudre ce qui compte'],
  },
  idn: {
    L: ['tu penses d\'abord en termes d\'humanité commune',
        'tu es universaliste : les mêmes droits pour tous, d\'où qu\'ils viennent',
        'tu es radicalement universaliste, les frontières entre groupes te paraissent artificielles'],
    R: ['tu accordes de l\'importance à l\'identité et à la culture du groupe',
        'tu es identitaire : le pays doit d\'abord préserver ce qu\'il est',
        'tu places l\'identité collective au cœur de tout, l\'appartenance prime sur l\'universel'],
  },
  aut: {
    L: ['tu défends la liberté individuelle face à l\'ordre',
        'tu es libertaire : le pouvoir doit être surveillé, jamais l\'inverse',
        'tu es viscéralement libertaire, toute autorité doit se justifier'],
    R: ['tu acceptes une dose d\'ordre pour la sécurité collective',
        'tu es autoritaire : l\'ordre et la discipline sont la condition de la liberté',
        'tu es franchement autoritaire, la sécurité et l\'ordre priment sur les libertés'],
  },
  env: {
    L: ['tu privilégies plutôt la croissance et l\'abondance',
        'tu es productiviste : le développement passe avant les contraintes écologiques',
        'tu es franchement productiviste, l\'écologie te semble un frein'],
    R: ['tu accordes un vrai poids à l\'écologie',
        'tu es écologiste : les limites de la planète doivent guider les choix collectifs',
        'tu es radicalement écologiste, la sobriété n\'est pas une option mais une nécessité'],
  },
  geo: {
    L: ['tu penses que les grands problèmes se règlent au-delà des frontières',
        'tu es mondialiste : la coopération internationale et l\'Europe sont la bonne échelle',
        'tu es profondément mondialiste, la nation te semble une échelle dépassée'],
    R: ['tu tiens à ce que ton pays garde la main sur ses décisions',
        'tu es souverainiste : la nation doit reprendre ce qu\'elle a cédé',
        'tu es farouchement souverainiste, les institutions supranationales sont illégitimes'],
  },
  jus: {
    L: ['tu crois plutôt à la réinsertion qu\'à la sanction',
        'tu es réhabilitateur : le crime se prévient et se répare, il ne se venge pas',
        'tu rejettes la logique punitive, la prison telle qu\'elle existe te semble un échec'],
    R: ['tu penses que la sanction doit être plus ferme',
        'tu es punitif : la peine doit dissuader et protéger la société',
        'tu es intransigeant sur la justice, les peines doivent être lourdes et exemplaires'],
  },
  tec: {
    L: ['tu regardes le progrès technique avec confiance',
        'tu es techno-optimiste : la technologie résout plus de problèmes qu\'elle n\'en crée',
        'tu es franchement techno-optimiste, l\'innovation est le moteur de l\'histoire'],
    R: ['tu gardes une distance critique face à la technologie',
        'tu es techno-critique : chaque avancée a un prix, souvent caché',
        'tu es profondément techno-critique, la technique nous aliène plus qu\'elle ne nous libère'],
  },
  epi: {
    L: ['tu juges d\'abord sur les résultats',
        'tu es pragmatique : ce qui marche vaut mieux que ce qui est pur',
        'tu es radicalement pragmatique, l\'idéologie te semble une perte de temps'],
    R: ['tu tiens à certains principes non négociables',
        'tu es idéologue au bon sens du terme : la cohérence des valeurs prime sur l\'efficacité',
        'tu es intransigeant sur les principes, le compromis te ressemble à une trahison'],
  },
  chg: {
    L: ['tu préfères améliorer par étapes',
        'tu es réformiste : les institutions se réparent, elles ne se cassent pas',
        'tu es profondément réformiste, les grands bouleversements te font peur'],
    R: ['tu penses qu\'il faut parfois changer de cadre',
        'tu es rupturiste : le système a besoin d\'être remplacé, pas rafistolé',
        'tu es franchement révolutionnaire, seul un renversement peut apporter la justice'],
  },
  dem: {
    L: ['tu fais confiance au jugement des citoyens',
        'tu es démocrate direct : le peuple doit trancher lui-même les grandes questions',
        'tu es radicalement populaire, les élites n\'ont aucune légitimité supérieure'],
    R: ['tu penses que certaines décisions demandent de l\'expertise',
        'tu es technocrate : les questions complexes doivent revenir à ceux qui les maîtrisent',
        'tu es franchement élitiste, le grand public n\'est pas armé pour décider'],
  },
  cfl: {
    L: ['tu crois qu\'on peut s\'entendre avec ses adversaires',
        'tu es consensuel : la politique est une conversation, pas une guerre',
        'tu es profondément consensuel, le conflit te semble toujours un échec'],
    R: ['tu vois la politique comme un rapport de force',
        'tu es conflictuel : les avancées s\'arrachent, elles ne se négocient pas',
        'tu es franchement combatif, il y a des camps et il faut choisir le sien'],
  },
  vis: {
    L: ['tu regardes l\'avenir avec confiance',
        'tu es optimiste : le monde va mieux et continuera d\'aller mieux',
        'tu es résolument optimiste, le déclin est une illusion'],
    R: ['tu as le sentiment que quelque chose se dégrade',
        'tu es décliniste : le meilleur est derrière nous',
        'tu es profondément décliniste, la civilisation te semble en chute'],
  },
  nat: {
    L: ['tu fais plutôt confiance aux gens',
        'tu crois en la bonté humaine : confiance et éducation transforment',
        'tu as une foi totale en l\'humain, seules les structures le corrompent'],
    R: ['tu restes prudent sur la nature humaine',
        'tu es méfiant : sans cadre, les gens suivent leur intérêt',
        'tu es profondément méfiant, l\'homme est un loup pour l\'homme'],
  },
};

window.PRISME_PROFILES = { FAMILIES, TEMPERAMENTS, AXIS_PHRASES };
