/* ============================================================
   PRISME — « Si tu étais une sucrerie »
   ------------------------------------------------------------
   Pas ta préférée : celle dont le caractère ressemble au tien.
   Celle qui se partage ou qu'on cache au fond du tiroir, qui fond
   tout de suite ou qui résiste aux dents, qui pique, qui colle,
   qui dure une après-midi entière ou qui explose en une seconde.
     name = la sucrerie, by = origine ou type, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const SWEETS = [
  { name: 'Le Carambar', by: 'France · 1954', tag: 'La blague est dans l\'emballage', color: '#c8862b',
    desc: 'On le déballe autant pour la devinette que pour le caramel, et la blague est souvent si mauvaise qu\'elle en devient bonne. Il colle un peu aux dents, ne se prend jamais au sérieux et détend une salle en trois secondes. C\'est le tempérament de ceux qui préfèrent faire rire que briller.',
    t: { inf: 0.9, soc: 0.9, vhe: 0.8, rig: 0.2, con: 0.2, epi: 0.1, cmp: 0.2, vtr: 0.75, aff: 0.3, vac: 0.15, ide: 0.75 } },
  { name: 'La fraise Tagada', by: 'France · Haribo, 1969', tag: 'La douceur qui ne déçoit jamais', color: '#e8457a',
    desc: 'Rose, moelleuse, poudrée de sucre, et exactement la même depuis plus de cinquante ans. Elle ne surprend personne et c\'est précisément ce qu\'on lui demande : être là, être douce, rassurer. C\'est le caractère de ceux qui mettent tout le monde à l\'aise sans jamais créer de remous.',
    t: { opt: 0.95, att: 0.85, vse: 0.85, vst: 0.2, chg: 0.1, cfl: 0.1, aud: 0.2, soc: 0.8, vis: 0.1, dog: 0.2, care: 0.8 } },
  { name: 'Les Dragibus', by: 'France · Haribo', tag: 'Toutes les couleurs à la fois', color: '#7b4fc4',
    desc: 'Un sachet de Dragibus, c\'est un arc-en-ciel sans ordre ni hiérarchie : on pioche au hasard et chaque couleur a sa chance. Petits, ronds, faciles à partager, ils vont avec tout le monde. C\'est le tempérament curieux et un peu dispersé de ceux qui préfèrent la variété à la méthode.',
    t: { vst: 0.9, ouv: 0.9, ord: 0.15, ide: 0.8, soc: 0.8, vtr: 0.25, inc: 0.85, con: 0.15, opn: 0.1, col: 0.6 } },
  { name: 'Le crocodile Haribo', by: 'France · Haribo', tag: 'Il mord, mais il est tendre', color: '#3fae4a',
    desc: 'Il a la gueule ouverte et l\'air féroce, mais il est en gélatine vert et jaune et il fond dès qu\'on le serre un peu. Il parle fort, dit ce qu\'il pense et ne recule pas devant une dispute, puis il défend les siens jusqu\'au bout. Le faux dur par excellence.',
    t: { com: 0.9, cfl: 0.9, dip: 0.15, aud: 0.8, emp: 0.6, ste: 0.3, inf: 0.7, vbe: 0.8, san: 0.4, loy: 0.8 } },
  { name: 'Les Schtroumpfs', by: 'Haribo · d\'après Peyo', tag: 'On n\'en mange jamais un seul', color: '#3c8fd9',
    desc: 'Ils vont par dizaines, tous pareils ou presque, et personne ne songerait à en isoler un. Le village compte plus que l\'individu, le chef est le plus vieux et tout le monde met la main à la pâte. C\'est la sucrerie de ceux qui pensent d\'abord en « nous » et détestent qu\'on se hisse au-dessus des autres.',
    t: { col: 0.95, loy: 0.9, vbe: 0.9, ind: 0.15, cmp: 0.1, vpo: 0.1, fair: 0.85, care: 0.85, soc: 0.85, lea: 0.3 } },
  { name: 'Le nounours en guimauve', by: 'France · Cémoi', tag: 'Un câlin enrobé de chocolat', color: '#8a5a3c',
    desc: 'Mou, rond, habillé de chocolat, il a été inventé pour être serré contre soi autant que pour être mangé. Il n\'a aucune arête, aucune acidité, aucune intention de blesser qui que ce soit. C\'est la sucrerie des gens profondément tendres, qui consolent avant même qu\'on ait fini d\'expliquer.',
    t: { att: 0.98, care: 0.95, emp: 0.95, com: 0.1, cfl: 0.05, dom: 0.1, ste: 0.9, aff: 0.05, vpo: 0.1, cmp: 0.1 } },
  { name: 'La guimauve grillée au feu de camp', by: 'Amérique du Nord · au bout d\'un bâton', tag: 'Meilleure dehors, à la nuit tombée', color: '#e7d3a8',
    desc: 'Elle n\'a de sens qu\'au bout d\'un bâton, au-dessus des braises, entourée de gens qui racontent des histoires. Elle brûle parfois, on la mange quand même, et personne ne vérifie l\'heure. C\'est le caractère de ceux qui aiment la nature, l\'imprévu et les soirées qui ne ressemblent à aucune autre.',
    t: { vun: 0.9, soc: 0.85, vst: 0.85, rsk: 0.65, opn: 0.15, col: 0.8, ord: 0.2, vhe: 0.8, vse: 0.2, tmp: 0.2 } },
  { name: 'Le Cachou Lajaunie', by: 'France · Toulouse, 1880', tag: 'Amer, discret, fidèle à lui-même', color: '#e9c12e',
    desc: 'Une petite boîte jaune, des grains noirs minuscules, un goût de réglisse amère que la moitié du monde trouve imbuvable. Il ne fait aucun effort pour plaire et n\'a jamais changé de recette. C\'est la sucrerie des solitaires un peu pince-sans-rire, qui se méfient des modes et gardent leurs goûts pour eux.',
    t: { ind: 0.95, soc: 0.15, inf: 0.15, vco: 0.1, vtr: 0.7, nat: 0.8, com: 0.75, dip: 0.25, opn: 0.7, vst: 0.3, dog: 0.6 } },
  { name: 'Le Malabar', by: 'France · 1969', tag: 'La plus grosse bulle de la cour', color: '#f28bb8',
    desc: 'On le mâche pour le goût pendant deux minutes, puis pour les bulles pendant une heure, et le tatouage finit sur l\'avant-bras. Il est fait pour être vu, pour épater, pour inventer un nouveau jeu. C\'est le tempérament des créatifs démonstratifs, qui ont toujours une idée de plus et rarement un plan.',
    t: { inf: 0.95, aud: 0.8, rig: 0.15, tmp: 0.15, ide: 0.85, vst: 0.9, vac: 0.35, ste: 0.2, soc: 0.8, con: 0.1 } },
  { name: 'Le Mentos', by: 'Pays-Bas · Van Melle', tag: 'Calme dehors, geyser dedans', color: '#9fd8e6',
    desc: 'Tout seul, c\'est un petit bonbon blanc parfaitement sage. Plongé dans une bouteille de soda, il déclenche un geyser de deux mètres. C\'est le caractère de ceux qui ont l\'air tranquilles jusqu\'au moment où ils décident de tout changer d\'un coup, et qui adorent voir ce qui se passe quand on tente le truc.',
    t: { chg: 0.95, rsk: 0.9, vst: 0.95, ste: 0.15, san: 0.3, inc: 0.9, ord: 0.1, vse: 0.1, aud: 0.9, vig: 0.1 } },
  { name: 'Le Tic Tac', by: 'Italie · Ferrero, 1969', tag: 'Deux calories, zéro débordement', color: '#7fcf9c',
    desc: 'Minuscule, calibré, rangé dans une boîte qui fait un bruit bien reconnaissable. On le prend avant une réunion ou un rendez-vous, par précaution, pour ne rien laisser au hasard. C\'est la sucrerie des gens méticuleux et un peu réservés, qui préfèrent anticiper que s\'excuser.',
    t: { con: 0.95, rig: 0.85, soc: 0.25, inf: 0.15, vhe: 0.2, ord: 0.95, vig: 0.85, thr: 0.75, san: 0.8, vst: 0.15 } },
  { name: 'Le Chupa Chups', by: 'Espagne · 1958', tag: 'Un logo signé Dalí', color: '#f5c518',
    desc: 'Une sucette dont l\'emblème a été dessiné par un peintre surréaliste, ce qui dit à peu près tout. Il se tient comme un micro, se promène dans la bouche des rock stars et ne ressemble à rien de sérieux. C\'est le caractère des esprits libres et inventifs, qui détournent les codes par plaisir.',
    t: { ide: 0.95, ouv: 0.9, vst: 0.8, vtr: 0.2, inf: 0.8, con: 0.15, lib: 0.85, vco: 0.15, epi: 0.6, chg: 0.8 } },
  { name: 'Le sucre d\'orge', by: 'France · Moret-sur-Loing', tag: 'La recette des religieuses', color: '#e0a23a',
    desc: 'On le fabrique encore selon une recette attribuée aux religieuses de Moret, gardée depuis le XVIIe siècle. Il ne cherche pas à suivre son époque et se méfie un peu de ce qu\'elle propose. C\'est la sucrerie de ceux pour qui la transmission est un devoir et la nouveauté, une chose à prouver.',
    t: { vtr: 0.98, vco: 0.85, ste: 0.85, vst: 0.1, chg: 0.05, sanc: 0.8, opn: 0.9, inc: 0.15, vis: 0.75, auth: 0.8 } },
  { name: 'La sucette géante arc-en-ciel', by: 'Fête foraine · en spirale', tag: 'Plus grosse que la tête', color: '#ff5fa2',
    desc: 'Elle est trois fois trop grande pour être finie, et c\'est justement le but : on la choisit pour qu\'on la voie. Elle dure le temps d\'une photo et d\'un tour de manège, puis finit collée dans un sac. C\'est le tempérament de ceux qui vivent l\'instant en grand, avec une pointe de goût pour l\'effet produit.',
    t: { inf: 0.95, vhe: 0.95, tmp: 0.05, rig: 0.1, vpo: 0.7, soc: 0.85, vig: 0.1, dom: 0.7, aff: 0.1, vac: 0.3, vst: 0.85 } },
  { name: 'Les M&M\'s', by: 'États-Unis · 1941', tag: 'Fond dans la bouche, pas dans la main', color: '#d9362b',
    desc: 'Le chocolat est à l\'abri d\'une coque colorée qui ne cède pas à la chaleur des doigts. Rien ne transparaît de l\'extérieur, tout reste impeccable, même sous pression. C\'est le caractère de ceux qui gardent leurs émotions sous carapace et dont la douceur se mérite.',
    t: { aff: 0.85, san: 0.95, emp: 0.3, att: 0.3, fia: 0.8, vig: 0.8, ste: 0.75, thr: 0.6, inf: 0.6, cfl: 0.3, nat: 0.75 } },
  { name: 'Les Smarties', by: 'Royaume-Uni · 1937', tag: 'Le tube qu\'on fait tourner', color: '#f08a1c',
    desc: 'Le tube passe de main en main, on se verse deux ou trois pastilles dans la paume et on laisse le reste aux autres. Chaque couleur est une petite fête, et aucune n\'est jugée meilleure que sa voisine. C\'est la sucrerie des optimistes confiants, qui voient le bon côté de chacun et ne s\'inquiètent pas de demain.',
    t: { opt: 0.95, vis: 0.05, thr: 0.1, nat: 0.1, soc: 0.85, rig: 0.3, care: 0.8, inc: 0.8, vbe: 0.85, cmp: 0.15 } },
  { name: 'Le Kinder Bueno', by: 'Italie · Ferrero', tag: 'Toujours livré en deux', color: '#b85c2b',
    desc: 'Il arrive en deux barres, comme s\'il avait prévu d\'en offrir une. Léger, croustillant, jamais écœurant, il s\'accorde à toutes les situations sans faire de vagues. C\'est le tempérament des diplomates chaleureux, qui trouvent spontanément la part juste et le mot qui apaise.',
    t: { dip: 0.95, att: 0.85, soc: 0.75, cfl: 0.1, vhe: 0.8, com: 0.15, san: 0.8, vpo: 0.5, fair: 0.85, emp: 0.8 } },
  { name: 'L\'œuf Kinder Surprise', by: 'Italie · Ferrero, 1974', tag: 'Le chocolat compte moins que la suite', color: '#ef7d22',
    desc: 'Tout le monde sait que le chocolat n\'est qu\'un prétexte : ce qui compte, c\'est la capsule jaune et ce qu\'elle cache. Il vit pour l\'inconnu, le déballage, la découverte à monter soi-même. C\'est le caractère de ceux qui préfèrent ne pas savoir ce qui les attend, parce que c\'est tout l\'intérêt.',
    t: { inc: 0.95, vst: 0.95, ouv: 0.9, ord: 0.1, vse: 0.15, loc: 0.8, tmp: 0.1, opt: 0.85, vig: 0.15, dog: 0.1 } },
  { name: 'Le Kinder Country', by: 'Italie · Ferrero', tag: 'Le goûter qui se veut raisonnable', color: '#d9b25c',
    desc: 'Des céréales, du lait, une image de champ de blé : il a tout fait pour qu\'on le trouve sage. Il ne prend aucun risque, rassure les parents et reste bien rangé dans le cartable. C\'est la sucrerie des prudents consciencieux, qui s\'accordent un plaisir à condition qu\'il soit bien encadré.',
    t: { vse: 0.85, rig: 0.7, rsk: 0.1, vhe: 0.3, fia: 0.9, vco: 0.8, con: 0.8, aud: 0.15, sanc: 0.75, thr: 0.7, tmp: 0.7 } },
  { name: 'Le Twix', by: 'Royaume-Uni · 1967', tag: 'Gauche ou droite, il faut choisir', color: '#c9a227',
    desc: 'Deux barres identiques et, pourtant, une rivalité montée de toutes pièces entre le Twix gauche et le Twix droit. On choisit son camp, on le défend avec une mauvaise foi joyeuse et on n\'en change plus. C\'est le tempérament de ceux qui aiment appartenir à une équipe et gagner contre l\'autre.',
    t: { cmp: 0.95, loy: 0.95, dog: 0.8, com: 0.75, col: 0.85, cfl: 0.8, fair: 0.3, dip: 0.3, vpo: 0.6, opn: 0.8 } },
  { name: 'Le Mars', by: 'Royaume-Uni · 1932', tag: 'Et ça repart', color: '#8b1e1e',
    desc: 'Dense, nourrissant, pensé pour tenir jusqu\'à la ligne d\'arrivée. On ne le mange pas pour le plaisir mais pour l\'énergie, entre deux efforts, sans s\'arrêter. C\'est la sucrerie des bosseurs ambitieux, qui voient chaque pause comme un ravitaillement et chaque journée comme une course à gagner.',
    t: { det: 0.95, vac: 0.95, tmp: 0.4, dom: 0.8, cmp: 0.85, soc: 0.4, emp: 0.35, epi: 0.1, ste: 0.3, vhe: 0.3, lea: 0.8 } },
  { name: 'Le Snickers', by: 'États-Unis · 1930', tag: 'Pas lui-même quand il a faim', color: '#6b3a1f',
    desc: 'Cacahuètes, caramel, nougat : il est taillé pour calmer une faim qui menace de tourner à l\'orage. Sa publicité le dit elle-même, on n\'est pas soi-même quand on a faim. C\'est le caractère des impulsifs au sang chaud, qui s\'emportent vite, disent tout haut ce qu\'ils pensent et redescendent aussi vite.',
    t: { dom: 0.9, com: 0.9, cfl: 0.95, san: 0.1, dip: 0.1, vhe: 0.85, ste: 0.1, aff: 0.15, thr: 0.6, tmp: 0.1 } },
  { name: 'Le KitKat', by: 'Royaume-Uni · 1935', tag: 'Il impose la pause', color: '#d4202c',
    desc: 'Toute sa philosophie tient dans un slogan : faire une pause. On casse une barre, on s\'assoit, et le reste du monde peut attendre cinq minutes. C\'est le tempérament des calmes qui ne courent après rien, défendent leur tranquillité et refusent de transformer la vie en compétition.',
    t: { ste: 0.95, vhe: 0.85, vac: 0.1, tmp: 0.3, rsk: 0.15, san: 0.9, cmp: 0.05, det: 0.3, vst: 0.2, thr: 0.1, ord: 0.4 } },
  { name: 'Le Bounty', by: 'Royaume-Uni · 1951', tag: 'Celui qui reste dans la boîte', color: '#2f9e8f',
    desc: 'Dans l\'assortiment de fin d\'année, c\'est souvent le dernier survivant, et il s\'en moque. Noix de coco, goût d\'ailleurs, promesse de plage lointaine : il n\'est pas fait pour plaire à tout le monde. C\'est la sucrerie des indépendants qui rêvent d\'horizons et vivent très bien à l\'écart du groupe.',
    t: { ind: 0.9, inf: 0.2, vco: 0.1, vst: 0.8, opn: 0.1, lib: 0.9, soc: 0.35, col: 0.2, ouv: 0.85, loy: 0.2 } },
  { name: 'Le Toblerone', by: 'Suisse · Berne, 1908', tag: 'Chaque triangle à sa place', color: '#e6b422',
    desc: 'Des pyramides alignées, une boîte qui ne ressemble à aucune autre, une forme qui n\'a pas bougé depuis plus d\'un siècle. On ne le croque pas n\'importe comment : il y a une technique, et elle est la bonne. C\'est le caractère des esprits structurés, attachés à l\'ordre et assez sûrs de leurs principes.',
    t: { ord: 0.95, rig: 0.9, con: 0.9, vtr: 0.8, inc: 0.15, chg: 0.1, epi: 0.7, dog: 0.75, vse: 0.8, aud: 0.2 } },
  { name: 'Le Ferrero Rocher', by: 'Italie · Ferrero, 1982', tag: 'Servi à la réception de l\'ambassadeur', color: '#b8903a',
    desc: 'Papier doré, pyramide sur un plateau d\'argent, et une publicité qui l\'a installé dans les salons diplomatiques. Il aime le protocole, les belles occasions et l\'effet produit quand on ouvre la boîte. C\'est la sucrerie des ambitieux élégants, pour qui le statut et les apparences font partie du jeu.',
    t: { vpo: 0.95, vac: 0.9, dip: 0.85, inf: 0.8, vun: 0.2, auth: 0.8, con: 0.8, vco: 0.85, cmp: 0.75, lib: 0.3 } },
  { name: 'Le Mon Chéri', by: 'Ferrero · 1956', tag: 'Une cerise pour dire je t\'aime', color: '#a3123a',
    desc: 'Son nom est une déclaration, son emballage est rose et il cache une cerise dans de la liqueur. Il ne se mange pas pour le goûter mais pour dire quelque chose à quelqu\'un. C\'est le tempérament des romantiques, qui vivent par le cœur, offrent sans compter et n\'ont pas peur de paraître fleur bleue.',
    t: { aff: 0.05, att: 0.95, vhe: 0.85, ide: 0.85, vbe: 0.9, rig: 0.2, com: 0.2, care: 0.85, sanc: 0.4, vst: 0.6, loc: 0.6 } },
  { name: 'Le Petit Écolier', by: 'France · LU, 1897', tag: 'Premier de la classe', color: '#c0762b',
    desc: 'Une tablette de chocolat posée bien droite sur un biscuit, et un petit élève sage gravé dessus. Il fait ses devoirs, respecte les règles et ne s\'est jamais fait remarquer pour une bêtise. C\'est la sucrerie des consciencieux loyaux envers l\'institution, qui trouvent du sens dans le travail bien fait et la discipline.',
    t: { con: 0.95, vco: 0.95, auth: 0.85, fia: 0.9, aud: 0.1, chg: 0.1, vst: 0.2, rig: 0.9, det: 0.8, vpo: 0.2, ind: 0.2 } },
  { name: 'Les Pim\'s', by: 'France · LU', tag: 'Juste un, promis', color: '#f07d1a',
    desc: 'On ouvre la boîte pour en prendre un, et c\'est la boîte entière qui disparaît sans qu\'on sache très bien comment. Il ne résiste à rien et ne cherche pas à résister : la volonté attendra demain. C\'est le caractère des bons vivants qui se laissent porter par l\'instant et les circonstances, sans culpabiliser.',
    t: { vhe: 0.9, loc: 0.9, ord: 0.2, rig: 0.2, tmp: 0.1, det: 0.2, vac: 0.15, inc: 0.7, san: 0.6, dom: 0.2 } },
  { name: 'L\'Oreo', by: 'États-Unis · 1912', tag: 'Tourner, lécher, tremper', color: '#2b2b2b',
    desc: 'Personne ne mange un Oreo simplement : chacun a sa méthode, son rituel, son ordre des opérations, et il les défend. C\'est un plaisir codifié, joueur mais très organisé. C\'est la sucrerie de ceux qui ont leurs petites habitudes, les partagent volontiers et n\'en changeraient pour rien au monde.',
    t: { ord: 0.85, vhe: 0.85, inf: 0.7, vtr: 0.3, dog: 0.7, ide: 0.7, soc: 0.7, rig: 0.75, vst: 0.5, chg: 0.2 } },
  { name: 'Le Nutella à la cuillère', by: 'Italie · Alba, 1964', tag: 'Directement dans le pot', color: '#6e3b1e',
    desc: 'Le pain est une formalité inutile : la cuillère va droit au pot, debout devant le placard, à n\'importe quelle heure. Aucune règle ne résiste à l\'envie du moment. C\'est le tempérament des hédonistes assumés, qui se méfient des interdits et ne voient pas pourquoi on se priverait d\'un plaisir qui ne fait de mal à personne.',
    t: { vhe: 0.98, vco: 0.1, rig: 0.1, tmp: 0.05, vig: 0.1, lib: 0.9, con: 0.1, auth: 0.15, sanc: 0.1, ord: 0.1 } },
  { name: 'La tablette de Milka', by: 'Suisse · 1901', tag: 'Une vache violette dans un pré', color: '#8c6bb1',
    desc: 'Un chocolat au lait très doux, une vache violette et des alpages qui n\'existent que dans les publicités. Elle promet un monde paisible, sans conflit, où la nature prend soin de tout. C\'est la sucrerie des rêveurs bienveillants, qui croient à un monde plus doux et font leur part pour le rendre possible.',
    t: { care: 0.9, ide: 0.85, vun: 0.85, ste: 0.85, cfl: 0.1, dom: 0.1, vis: 0.15, opt: 0.85, att: 0.85, cmp: 0.1, sanc: 0.7 } },
  { name: 'Le carré de chocolat noir 85 %', by: 'Partout · un seul carré', tag: 'Le plaisir sous contrôle', color: '#3a2418',
    desc: 'Amer, presque austère, il se déguste un carré à la fois, lentement, et le reste de la tablette retourne au placard. Il n\'a rien à voir avec la gourmandise : c\'est une affaire d\'exigence et de maîtrise de soi. C\'est le caractère des cérébraux disciplinés, qui préfèrent la qualité à la quantité et la tête au cœur.',
    t: { rig: 0.95, vhe: 0.15, aff: 0.9, con: 0.8, soc: 0.2, det: 0.9, inf: 0.1, vst: 0.2, san: 0.9, att: 0.3 } },
  { name: 'Le macaron', by: 'France · Paris', tag: 'Parfait ou rien', color: '#e9a8c0',
    desc: 'Une collerette régulière, une coque lisse, une ganache exacte : au moindre défaut, il part à la poubelle. Il est beau, cher, fragile, et sa réputation se joue à un millimètre. C\'est le tempérament des perfectionnistes ambitieux, pour qui le détail est une question d\'honneur et l\'erreur, une vraie angoisse.',
    t: { rig: 0.95, vpo: 0.8, vac: 0.9, con: 0.9, san: 0.3, thr: 0.8, vig: 0.85, inf: 0.7, ord: 0.9, inc: 0.1 } },
  { name: 'La madeleine', by: 'France · Commercy', tag: 'Un souvenir à chaque bouchée', color: '#dcae6a',
    desc: 'Depuis Proust, elle n\'est plus tout à fait un gâteau : c\'est une porte vers l\'enfance. Elle ramène les cuisines d\'autrefois, les goûters de grand-mère, les étés qui semblaient plus longs. C\'est la sucrerie des nostalgiques sensibles, qui vivent beaucoup par le souvenir et trouvent que c\'était un peu mieux avant.',
    t: { vtr: 0.95, att: 0.9, vis: 0.85, ide: 0.8, emp: 0.85, vst: 0.1, chg: 0.05, aff: 0.1, tmp: 0.8, loc: 0.7 } },
  { name: 'Le calisson d\'Aix', by: 'France · Aix-en-Provence', tag: 'L\'élégance sans éclat', color: '#f3ead2',
    desc: 'Une fine amande de pâte de fruits confits sous un glaçage blanc, pas un gramme de trop. Il ne parle pas fort, ne cherche pas à séduire, et pourtant il ne ressemble à rien d\'autre. C\'est le tempérament des discrets raffinés, attachés à leurs racines, qui préfèrent la nuance à la démonstration.',
    t: { dip: 0.9, san: 0.85, inf: 0.15, vtr: 0.85, soc: 0.3, cfl: 0.1, rig: 0.85, vpo: 0.3, dom: 0.15, opn: 0.85 } },
  { name: 'Le nougat de Montélimar', by: 'France · Drôme', tag: 'Il ne cède pas sous la dent', color: '#f1e4c3',
    desc: 'Dur, dense, blindé d\'amandes, il résiste à la mâchoire avec une obstination tout provençale. Il ne plie pas, ne s\'excuse pas, et n\'a aucune intention de devenir plus tendre pour arranger qui que ce soit. C\'est le caractère des têtus enracinés, qui tiennent leur position même quand tout le monde pousse.',
    t: { det: 0.95, com: 0.8, dip: 0.2, cfl: 0.85, opn: 0.9, vtr: 0.8, ste: 0.8, chg: 0.1, emp: 0.4, dog: 0.7 } },
  { name: 'La praline rose', by: 'France · Lyon', tag: 'Rose vif et fière de l\'être', color: '#e5306f',
    desc: 'Une amande enrobée de sucre d\'un rose que personne n\'oserait ailleurs, et qui finit dans une tarte ou une brioche où on ne voit qu\'elle. Elle est lyonnaise, le fait savoir, et se moque du bon goût discret. C\'est le tempérament des extravertis fiers de leur coin, qui aiment qu\'on les remarque.',
    t: { inf: 0.95, aud: 0.85, vco: 0.2, opn: 0.8, loy: 0.85, vpo: 0.5, com: 0.7, soc: 0.85, vst: 0.7, dip: 0.3 } },
  { name: 'Les bêtises de Cambrai', by: 'France · Nord', tag: 'Née d\'une erreur réussie', color: '#bfe3c8',
    desc: 'Selon la légende, un apprenti confiseur aurait raté sa recette et inventé par accident le bonbon qui fait la fierté de la ville. La bêtise est devenue une spécialité. C\'est le caractère des optimistes insouciants, qui laissent la chance faire les choses et transforment volontiers un raté en bonne histoire.',
    t: { loc: 0.9, inc: 0.9, rig: 0.15, opt: 0.95, vis: 0.05, ord: 0.15, ide: 0.8, thr: 0.1, con: 0.15, dog: 0.1 } },
  { name: 'Les violettes de Toulouse', by: 'France · Toulouse', tag: 'Une fleur qu\'on ose croquer', color: '#7a4fa3',
    desc: 'Des pétales de violette cristallisés dans le sucre : c\'est moins une friandise qu\'un petit poème. Elle est fragile, délicate, un peu hors du temps, et ne supporte pas la brutalité. C\'est la sucrerie des idéalistes sensibles, qui cherchent la beauté partout et se tiennent volontiers à l\'écart du bruit.',
    t: { ide: 0.95, sanc: 0.85, vun: 0.85, soc: 0.25, inf: 0.2, vac: 0.1, com: 0.1, epi: 0.8, emp: 0.9, cmp: 0.05 } },
  { name: 'Le caramel au beurre salé', by: 'France · Bretagne', tag: 'Le sel, c\'est chez nous', color: '#c47a2c',
    desc: 'Mettre du sel dans une sucrerie : une idée bretonne, défendue avec une fierté que rien n\'entame. Il a du caractère, un goût franc, et ne renie jamais d\'où il vient. C\'est le tempérament des fidèles à leur terre, solides, loyaux envers les leurs, et qui ne se laissent pas raconter n\'importe quoi.',
    t: { opn: 0.95, loy: 0.95, vtr: 0.9, com: 0.7, aff: 0.3, det: 0.85, col: 0.8, chg: 0.25, fia: 0.9, soc: 0.8 } },
  { name: 'La pâte de fruits', by: 'France · Auvergne', tag: 'Du vrai fruit, rien d\'autre', color: '#d9483b',
    desc: 'Elle n\'a rien à cacher : du fruit, du sucre, de la patience, et une couleur qui vient du fruit lui-même. Elle ne triche pas, ne se vante pas, et préfère la qualité honnête à l\'effet. C\'est le caractère des gens intègres et sans ostentation, attachés à ce qui est authentique et respectueux de la nature.',
    t: { vun: 0.85, sanc: 0.85, fia: 0.95, vpo: 0.1, inf: 0.3, rig: 0.8, con: 0.75, vac: 0.2, dip: 0.8, emp: 0.75 } },
  { name: 'Le marron glacé', by: 'France · Ardèche', tag: 'Plusieurs jours pour une bouchée', color: '#8a5a2b',
    desc: 'Il faut des jours de trempages successifs dans le sirop pour qu\'un marron devienne glacé sans se briser. Il se garde pour les grandes occasions et se paie en conséquence. C\'est le tempérament des patients exigeants, qui visent l\'excellence sur la durée et savent qu\'un vrai résultat ne s\'improvise pas.',
    t: { tmp: 0.95, rig: 0.95, vpo: 0.7, vac: 0.75, san: 0.8, ste: 0.8, vhe: 0.7, thr: 0.6, det: 0.9, soc: 0.3 } },
  { name: 'La dragée', by: 'France · Verdun', tag: 'Baptêmes, mariages, communions', color: '#f4e9ee',
    desc: 'Elle n\'apparaît que pour les grands rites de la vie, dans de petits sachets de tulle, selon des règles de couleur que tout le monde connaît. Elle marque le passage, relie les générations et ne s\'improvise jamais. C\'est la sucrerie des gardiens des traditions, pour qui les cérémonies ont un sens profond.',
    t: { vtr: 0.95, auth: 0.85, vco: 0.95, loy: 0.85, sanc: 0.9, col: 0.85, chg: 0.05, lib: 0.15, ind: 0.15, inc: 0.15 } },
  { name: 'La chouquette', by: 'France · sachet de boulangerie', tag: 'Le petit sachet à partager', color: '#e3bf7a',
    desc: 'Un sachet en papier, une dizaine de boules de pâte à choux parsemées de sucre en grains, et tout le monde plonge la main dedans. Elle ne coûte rien, ne prétend à rien et fait plaisir à tous. C\'est le caractère des gens simples et généreux, qui partagent spontanément et se fichent complètement du prestige.',
    t: { soc: 0.9, vpo: 0.05, vac: 0.1, ste: 0.8, emp: 0.8, dom: 0.1, vhe: 0.8, rig: 0.25, vbe: 0.9, cmp: 0.05, ord: 0.2 } },
  { name: 'La meringue', by: 'Europe · blanc d\'œuf et sucre', tag: 'Légère et prête à se briser', color: '#f8f4ea',
    desc: 'Elle a besoin d\'un four très doux, d\'un air sec et de mains prudentes, sinon elle retombe ou se fend. Aérienne et craquante, elle tient pourtant debout, mais tout l\'inquiète un peu. C\'est le tempérament des sensibles sur le qui-vive, qui anticipent les dangers et avancent avec précaution.',
    t: { thr: 0.9, san: 0.15, vig: 0.9, nat: 0.75, aud: 0.15, rsk: 0.1, emp: 0.8, ide: 0.7, dom: 0.1, inc: 0.1 } },
  { name: 'Le pain d\'épices', by: 'France · Dijon', tag: 'Il se bonifie avec le temps', color: '#a8652d',
    desc: 'Du miel, des épices, une recette qui voyage depuis des siècles, et une pâte qu\'on laissait autrefois reposer des semaines. Il ne se presse jamais, ne s\'inquiète de rien et devient meilleur en vieillissant. C\'est la sucrerie des sages tranquilles, maîtres de leur destin, qui pensent en années plutôt qu\'en jours.',
    t: { tmp: 0.9, san: 0.9, vtr: 0.9, loc: 0.2, opn: 0.7, ste: 0.9, vst: 0.15, rig: 0.7, fia: 0.9, cfl: 0.3, vis: 0.6 } },
  { name: 'Le loukoum', by: 'Turquie · Istanbul', tag: 'Du sucre glace jusqu\'aux coudes', color: '#f2a0b5',
    desc: 'Moelleux, parfumé à la rose, couvert d\'une poudre qui finit partout, il se déguste lentement avec un thé, sans regarder l\'heure. Il aime la volupté, la conversation qui s\'étire et les contacts sans heurts. C\'est le tempérament des sensuels paisibles, qui prennent le temps de savourer et arrondissent les angles.',
    t: { vhe: 0.95, ste: 0.8, dip: 0.85, cfl: 0.1, ind: 0.4, inf: 0.5, rig: 0.2, tmp: 0.2, vst: 0.5, sanc: 0.3, aff: 0.1 } },
  { name: 'Le halva', by: 'Méditerranée orientale · sésame', tag: 'Dense, sobre, rassasiant', color: '#cdb38a',
    desc: 'Un bloc de sésame et de sucre qu\'on coupe au couteau, sans décor ni fantaisie, et qui tient au corps. Il n\'aime ni les grands discours ni les théories : il fait son office, sobrement, et ça suffit. C\'est la sucrerie des pragmatiques solides et peu bavards, sur qui l\'on peut compter sans avoir à le demander.',
    t: { det: 0.9, fia: 0.9, soc: 0.35, inf: 0.15, vtr: 0.85, epi: 0.05, vhe: 0.4, ste: 0.85, ide: 0.2, dom: 0.5, vst: 0.2 } },
  { name: 'La pomme d\'amour', by: 'Fête foraine · caramel rouge', tag: 'Brillante, et dure à croquer', color: '#c41a24',
    desc: 'Rouge éclatant, lisse comme un miroir, elle attire tous les regards, puis on se casse les dents sur sa carapace de sucre. Elle aime séduire mais ne se laisse pas atteindre si facilement. C\'est le tempérament des charmeurs ambitieux et un peu méfiants, qui brillent en public et gardent leurs distances en privé.',
    t: { inf: 0.9, vpo: 0.7, com: 0.6, aff: 0.4, dip: 0.4, att: 0.25, vhe: 0.7, san: 0.6, emp: 0.3, nat: 0.7, vac: 0.7 } },
  { name: 'Le bonbon à la menthe de grand-mère', by: 'Fond du sac à main', tag: 'Toujours là quand il faut', color: '#a8d8c0',
    desc: 'Il attend au fond d\'un sac, avec les mouchoirs et le pansement, pour le jour où quelqu\'un en aura besoin. Il ne sert à rien la plupart du temps, et c\'est tout l\'intérêt : on a pensé à vous d\'avance. C\'est le caractère des protecteurs prévoyants, qui s\'inquiètent pour tout le monde et prennent soin avant qu\'on le demande.',
    t: { vig: 0.95, care: 0.95, vse: 0.9, tmp: 0.9, vbe: 0.95, ord: 0.85, thr: 0.8, vst: 0.1, rsk: 0.1, att: 0.9 } },
  { name: 'Les Têtes Brûlées', by: 'France · Verquin', tag: 'Ça pique, et c\'est voulu', color: '#b6e02a',
    desc: 'Une poudre acide qui fait grimacer, qu\'on se lance en défi dans la cour pour voir qui tiendra le plus longtemps. Il n\'y a aucune raison raisonnable de s\'infliger ça, et c\'est justement ce qui plaît. C\'est le tempérament des casse-cou compétitifs, qui adorent les sensations fortes et ne reculent devant aucun pari.',
    t: { aud: 0.98, rsk: 0.95, vst: 0.95, vse: 0.05, cmp: 0.9, vig: 0.1, com: 0.85, san: 0.7, thr: 0.1, dom: 0.8 } },
  { name: 'Le Michoko', by: 'France · La Pie qui Chante', tag: 'Il s\'accroche', color: '#5a3320',
    desc: 'Du caramel enrobé de chocolat qui colle aux dents et refuse de partir : une fois qu\'il est là, il est là. Il n\'aime pas qu\'on le quitte, et il est de toutes les boîtes et de tous les goûters depuis des décennies. C\'est le caractère des fidèles attachés, qui se donnent entièrement aux leurs et ne lâchent personne.',
    t: { att: 0.95, loy: 0.95, fia: 0.85, ind: 0.1, col: 0.8, ste: 0.85, vbe: 0.95, chg: 0.1, com: 0.3, soc: 0.6 } },
  { name: 'Le Mister Freeze', by: 'Tube glacé · été de l\'enfance', tag: 'Ça fond, pas de panique', color: '#4fc3e8',
    desc: 'Il coule le long des doigts, on le mord n\'importe comment, et personne ne s\'en fait. Il coûte trois fois rien et appartient aux après-midi d\'été où rien ne presse. C\'est le tempérament des détendus sans prétention, qui ne cherchent ni à réussir ni à contrôler, et que peu de choses parviennent à inquiéter.',
    t: { san: 0.9, tmp: 0.05, vac: 0.1, rig: 0.15, inc: 0.8, vhe: 0.85, thr: 0.05, dom: 0.2, cmp: 0.1, vpo: 0.05, nat: 0.1 } },
  { name: 'Le Pez', by: 'Autriche · 1927', tag: 'Le bonbon compte moins que la tête', color: '#d84c8f',
    desc: 'Le bonbon est anecdotique : ce qui compte, c\'est le distributeur, et ceux qui les collectionnent en rangent des centaines par série. Il vit dans un monde à lui, minutieux, bien classé, un peu à part. C\'est la sucrerie des passionnés solitaires, capables d\'une précision infinie sur ce qui les intéresse.',
    t: { rig: 0.85, ord: 0.9, ind: 0.8, soc: 0.3, vtr: 0.7, vst: 0.3, con: 0.8, ide: 0.6, att: 0.3, inf: 0.25 } },
  { name: 'La pastille Vichy', by: 'France · Vichy, 1825', tag: 'Octogonale et bonne pour la santé', color: '#f2f2ef',
    desc: 'Née des sels minéraux d\'une ville thermale, vendue d\'abord comme remède, elle garde un parfum de pharmacie. Elle ne fait aucun excès, surveille la digestion et évite ce qui pourrait nuire. C\'est le caractère des prudents soucieux de leur santé, méfiants envers les écarts et fidèles à leurs bonnes habitudes.',
    t: { thr: 0.8, vig: 0.9, sanc: 0.85, vse: 0.9, vhe: 0.15, con: 0.85, vst: 0.1, rsk: 0.05, tmp: 0.85, fia: 0.85 } },
  { name: 'L\'anis de Flavigny', by: 'France · Bourgogne, abbaye', tag: 'Quinze jours pour une graine', color: '#e9e3f0',
    desc: 'Une seule graine d\'anis, enrobée couche après couche pendant des jours, dans un village où l\'on en fait depuis l\'époque des moines. Il ne se presse pas, ne fait pas de bruit et ne cherche aucune reconnaissance. C\'est la sucrerie des contemplatifs, calmes et patients, pour qui le silence et la constance ont quelque chose de sacré.',
    t: { sanc: 0.95, tmp: 0.95, soc: 0.1, ste: 0.95, vst: 0.1, inf: 0.05, vpo: 0.05, san: 0.9, det: 0.85, vtr: 0.9 } },
  { name: 'Le cannelé', by: 'France · Bordeaux', tag: 'Croûte dure, cœur tendre', color: '#7a3b12',
    desc: 'Dehors, une carapace presque brûlée qui craque sous la dent ; dedans, un cœur moelleux parfumé au rhum et à la vanille. Il faut dépasser la première impression pour le comprendre. C\'est le tempérament des réservés un peu rugueux au premier abord, profondément fiables et tendres avec ceux qu\'ils ont laissés entrer.',
    t: { com: 0.7, emp: 0.8, soc: 0.3, rig: 0.85, vig: 0.7, att: 0.8, dip: 0.3, inf: 0.2, nat: 0.7, fia: 0.9 } },
  { name: 'Le financier', by: 'France · quartier de la Bourse', tag: 'Efficace, en forme de lingot', color: '#d6a24a',
    desc: 'Pensé, dit-on, pour les hommes d\'affaires pressés du quartier de la Bourse : on le mange sans se salir les doigts, et il a la forme d\'un lingot. Il va droit au but, vise le résultat et ne s\'embarrasse pas de sentiments. C\'est le caractère des stratèges pragmatiques, qui aiment gagner et le font savoir.',
    t: { vac: 0.95, vpo: 0.85, epi: 0.1, cmp: 0.9, emp: 0.3, tmp: 0.7, rig: 0.8, lea: 0.85, vun: 0.2, care: 0.3, aff: 0.9 } },
  { name: 'Le brigadeiro', by: 'Brésil · 1945', tag: 'La fête n\'a pas commencé sans lui', color: '#4a2a1a',
    desc: 'Né, raconte-t-on, pendant une campagne électorale, il est devenu le cœur de tous les anniversaires brésiliens, roulé à la main par dizaines la veille. Il rassemble, il anime, il met tout le monde dans l\'ambiance. C\'est la sucrerie des rassembleurs enthousiastes, qui mettent leur énergie au service d\'une cause et d\'une fête.',
    t: { soc: 0.95, inf: 0.9, col: 0.85, vhe: 0.9, rig: 0.3, eng: 0.8, opt: 0.9, emp: 0.8, con: 0.2, ide: 0.7 } },
  { name: 'Le Mikado', by: 'France · LU, 1982', tag: 'Un par un, sans rien faire bouger', color: '#9b5a2a',
    desc: 'Il porte le nom d\'un jeu où l\'on retire les baguettes une à une sans faire trembler les autres. Fin, précis, jamais envahissant, il demande la main sûre et le souffle calme. C\'est le tempérament des tacticiens patients, qui avancent sans bruit, évitent les frictions et ne perdent jamais leur sang-froid.',
    t: { vig: 0.9, san: 0.9, cfl: 0.05, dip: 0.9, det: 0.7, dom: 0.15, com: 0.15, rig: 0.8, inf: 0.3, rsk: 0.2 } },
  { name: 'Le lapin de Pâques en chocolat', by: 'Europe · chasse aux œufs', tag: 'On commence par les oreilles', color: '#a0623a',
    desc: 'Il se cherche dans le jardin, en famille, au milieu des cris des plus petits, puis se partage oreille par oreille. Il est à la fois tradition et jeu, rituel et chasse au trésor. C\'est la sucrerie des gens de famille enjoués, qui aiment les rendez-vous de l\'année et y mettent toujours un peu d\'aventure.',
    t: { vtr: 0.85, col: 0.85, care: 0.85, vst: 0.8, soc: 0.85, vbe: 0.9, opt: 0.9, sanc: 0.7, cmp: 0.4, ind: 0.2 } },
  { name: 'Le chocolat du calendrier de l\'Avent', by: 'Allemagne · du 1er au 24 décembre', tag: 'Une case par jour, pas deux', color: '#b3263a',
    desc: 'Il y a vingt-quatre chocolats, et la règle est simple : une case par jour, dans l\'ordre, sans tricher. Tout le plaisir est dans l\'attente et la discipline qui la rend supportable. C\'est le caractère des patients méthodiques, qui savent différer une envie et trouvent dans la régularité une vraie satisfaction.',
    t: { tmp: 0.98, ord: 0.95, vhe: 0.2, det: 0.85, rig: 0.85, vst: 0.3, san: 0.85, inc: 0.15, con: 0.8, vtr: 0.75 } },
];

window.PRISME_SWEETS = { SWEETS };
