/* ============================================================
   PRISME — « Si tu étais une émission de télé »
   ------------------------------------------------------------
   Même principe que les plats, les films et les morceaux : ce
   n'est pas l'émission que tu regardes — Prisme ne sait pas ce que
   tu allumes le soir. C'est celle dont le tempérament ressemble au
   tien : son rythme, son rapport au conflit, à la règle, au public.
     name = l'émission, by = chaîne · genre, tag = la phrase,
     t = cibles de 0 à 1 (mêmes clés que js/characters.js)
   ============================================================ */
const TVSHOWS = [
  { name: 'Koh-Lanta', by: 'TF1 · aventure', tag: 'Tenir, et choisir avec qui', color: '#c8872e',
    desc: 'Une île, pas de confort, et des semaines à tenir en sachant que chaque conseil peut vous renvoyer chez vous. On y gagne par l\'endurance autant que par les alliances, et la loyauté y est une stratégie qui se paie. C\'est le tempérament de ceux qui encaissent sans se plaindre et qui comptent leurs alliés en silence.',
    t: { det: 0.95, san: 0.85, loy: 0.85, cmp: 0.85, vhe: 0.1, vig: 0.8, tmp: 0.75, dom: 0.7, rsk: 0.7, vse: 0.2, inf: 0.35 } },
  { name: 'Pékin Express', by: 'M6 · course', tag: 'Le sac sur le dos, le pouce levé', color: '#d9432f',
    desc: 'Un euro par jour, une langue qu\'on ne parle pas, et une voiture à arrêter au bord d\'une route inconnue. Tout se joue à deux, dans l\'improvisation et la débrouille, avec la fatigue qui fait remonter les caractères. C\'est le goût de l\'imprévu, celui des gens qui préfèrent se perdre que planifier.',
    t: { vst: 0.95, aud: 0.9, ouv: 0.9, inc: 0.9, rsk: 0.9, opn: 0.05, ord: 0.15, vse: 0.1, col: 0.7, cmp: 0.75, soc: 0.8 } },
  { name: 'L\'amour est dans le pré', by: 'M6 · rencontres', tag: 'La tendresse à la ferme', color: '#8fae5a',
    desc: 'Des agriculteurs pudiques qui cherchent quelqu\'un pour partager une vie qui commence à cinq heures du matin. Rien ne presse, on se découvre en ramassant les œufs, et les maladresses sont plus touchantes que gênantes. C\'est le tempérament de ceux qui aiment lentement, sans esbroufe, et qui tiennent à leurs racines.',
    t: { att: 0.95, vtr: 0.85, opn: 0.9, emp: 0.8, ste: 0.9, vbe: 0.9, vst: 0.2, vpo: 0.05, cfl: 0.1, inf: 0.25, aud: 0.3 } },
  { name: 'Secret Story', by: 'TF1 · téléréalité', tag: 'Chacun cache quelque chose', color: '#5b3f8c',
    desc: 'Une maison pleine de micros où chacun protège un secret et cherche à percer celui des autres. On y observe, on déduit, on bluffe, et les amitiés ont toujours un fond de calcul. C\'est le tempérament des stratèges sociaux, qui s\'amusent à lire les gens et ne montrent jamais toutes leurs cartes.',
    t: { vig: 0.9, nat: 0.85, dip: 0.8, inf: 0.8, vpo: 0.75, cmp: 0.85, vst: 0.85, thr: 0.75, fia: 0.2, emp: 0.35, sanc: 0.15 } },
  { name: 'Star Academy', by: 'TF1 · télé-crochet', tag: 'Tout le monde y croit', color: '#e2458e',
    desc: 'Un château, des cours de chant et de danse, des évaluations chaque semaine et une troupe qui se soutient tout en sachant qu\'un seul gagnera. L\'émotion est au premier plan, les larmes et les câlins aussi. C\'est l\'optimisme de ceux qui travaillent dur en rêvant grand, et qui préfèrent l\'élan collectif au cynisme.',
    t: { opt: 0.95, soc: 0.95, vac: 0.9, att: 0.85, det: 0.85, inf: 0.9, aff: 0.1, vis: 0.05, nat: 0.1, ind: 0.2, san: 0.3 } },
  { name: 'Les Marseillais', by: 'W9 · téléréalité', tag: 'Le soleil d\'abord, on verra après', color: '#f2a33a',
    desc: 'Une villa, une plage, une bande qui fait la fête et règle ses différends à voix haute avant de se réconcilier au dîner. Rien n\'est prévu au-delà du soir même, et c\'est très bien comme ça. C\'est le tempérament de ceux qui vivent au présent, fidèles à leur clan, et qui ne gardent jamais rien pour eux.',
    t: { vhe: 0.98, soc: 0.95, inf: 0.9, tmp: 0.05, rig: 0.05, con: 0.05, cfl: 0.8, loy: 0.85, aff: 0.1, vst: 0.85, ord: 0.1 } },
  { name: 'Mariés au premier regard', by: 'M6 · rencontres', tag: 'Oui, avant même bonjour', color: '#d97a8c',
    desc: 'Des inconnus se découvrent devant le maire, sur la foi d\'un calcul d\'experts, et construisent ensuite ce qu\'on bâtit d\'habitude avant. Il faut une bonne dose de confiance dans le destin et d\'appétit pour le vertige. C\'est le tempérament de ceux qui sautent d\'abord et apprennent à nager ensuite, par amour du grand saut.',
    t: { rsk: 0.9, aud: 0.9, inc: 0.85, att: 0.9, loc: 0.8, nat: 0.1, vig: 0.15, aff: 0.15, tmp: 0.7, vst: 0.8 } },
  { name: 'Un dîner presque parfait', by: 'W9 · cuisine', tag: 'Souriant à table, sévère sur la note', color: '#b5532f',
    desc: 'Cinq inconnus s\'invitent à tour de rôle, sont charmants toute la soirée et règlent leurs comptes dans le taxi du retour. On y juge la cuisine, la déco, l\'animation et un peu l\'hôte lui-même. C\'est le tempérament de ceux qui aiment recevoir et être reçus, mais qui gardent toujours un carnet de notes dans la poche.',
    t: { soc: 0.85, cmp: 0.8, com: 0.8, vhe: 0.85, fair: 0.7, inf: 0.75, dip: 0.3, nat: 0.6, cfl: 0.7, emp: 0.35, ide: 0.5 } },
  { name: 'Top Chef', by: 'M6 · cuisine', tag: 'Le geste juste sous la pression', color: '#1f2a3c',
    desc: 'Des cuisiniers déjà excellents poussés dans leurs retranchements, chronomètre en main, devant des chefs qui goûtent une bouchée et savent tout. La créativité compte, mais seulement si l\'exécution est impeccable. C\'est le tempérament des perfectionnistes ambitieux, qui aiment qu\'on les juge sur pièce.',
    t: { rig: 0.95, vac: 0.95, det: 0.95, ide: 0.85, cmp: 0.9, san: 0.8, ord: 0.85, vhe: 0.3, soc: 0.3, att: 0.35 } },
  { name: 'Le Meilleur Pâtissier', by: 'M6 · cuisine', tag: 'Un concours où l\'on s\'entraide', color: '#f0b8c4',
    desc: 'Une tente dans un jardin, des amateurs qui se prêtent la poche à douille et un jury qui encourage plus qu\'il ne tranche. On rate un glaçage, on rit, on recommence. C\'est le tempérament de ceux qui aiment bien faire sans écraser personne, pour qui la compétition n\'est qu\'un prétexte à partager un goûter.',
    t: { care: 0.9, rig: 0.8, cmp: 0.1, att: 0.85, opt: 0.9, cfl: 0.05, dip: 0.85, vpo: 0.05, ste: 0.85, vtr: 0.75, dom: 0.15 } },
  { name: 'Cauchemar en cuisine', by: 'M6 · coaching', tag: 'On ne sauve rien en chuchotant', color: '#8c1d1d',
    desc: 'Un chef débarque dans un restaurant qui coule, ouvre le frigo et dit tout ce qu\'il voit, sans filtre. Puis il retrousse ses manches et remet l\'affaire sur pied en une semaine. Derrière les éclats de voix, il y a une vraie envie d\'aider. C\'est le tempérament des sauveteurs brusques, qui préfèrent la vérité qui blesse au confort qui coule.',
    t: { com: 0.98, cfl: 0.95, dom: 0.95, lea: 0.9, chg: 0.9, dip: 0.1, ste: 0.15, care: 0.75, det: 0.9, inf: 0.6 } },
  { name: 'The Voice', by: 'TF1 · télé-crochet', tag: 'On écoute avant de regarder', color: '#c4262e',
    desc: 'Les coachs tournent le dos et ne jugent que la voix, puis se disputent les talents avec un enthousiasme sincère. Tout y est affaire d\'émotion : un frisson suffit à changer une vie. C\'est le tempérament de ceux qui cherchent ce qu\'il y a de précieux chez les autres et qui aiment les accompagner vers le haut.',
    t: { emp: 0.9, lea: 0.8, inf: 0.85, aff: 0.05, vbe: 0.85, opt: 0.85, nat: 0.1, ide: 0.8, fair: 0.8, rig: 0.35 } },
  { name: 'Nouvelle Star', by: 'M6 · télé-crochet', tag: 'Le jury qui ne fait pas semblant', color: '#231f20',
    desc: 'Un jury qui dit vraiment ce qu\'il pense, parfois avec une franchise redoutable, et qui préfère une voix singulière à une voix parfaite. On y cherche une personnalité plus qu\'un produit. C\'est le tempérament des esprits indépendants, allergiques au consensus mou, qui aiment ce qui dépasse et le disent sans détour.',
    t: { ind: 0.85, ide: 0.9, com: 0.85, chg: 0.85, vsd: 0.9, vco: 0.1, auth: 0.1, dip: 0.2, vtr: 0.1, ouv: 0.85, emp: 0.4 } },
  { name: 'La France a un incroyable talent', by: 'M6 · talents', tag: 'Tout le monde a sa chance', color: '#f4c430',
    desc: 'Un chanteur d\'opéra, un chien qui fait du skate, un magicien de huit ans et une troupe de danse de retraités, à la suite et sans hiérarchie. Il n\'y a aucune règle sur ce qu\'est un talent, et c\'est tout le charme. C\'est le tempérament de ceux qui s\'émerveillent facilement et refusent de mettre les gens dans des cases.',
    t: { ouv: 0.95, opt: 0.9, ide: 0.85, vst: 0.9, vco: 0.15, dog: 0.05, ord: 0.15, inc: 0.85, rig: 0.25, vun: 0.8, cmp: 0.4 } },
  { name: 'Danse avec les stars', by: 'TF1 · danse', tag: 'À deux, en cadence, jusqu\'au bout', color: '#9b2c6f',
    desc: 'Une personnalité qui n\'a jamais dansé et un professionnel patient répètent des semaines pour deux minutes sur le parquet. On progresse ensemble, on se blesse un peu, on se dépasse. C\'est le tempérament de ceux qui aiment apprendre par le travail, en duo, et qui trouvent de l\'élégance dans l\'effort acharné.',
    t: { det: 0.9, rig: 0.85, att: 0.85, col: 0.75, vac: 0.8, loc: 0.15, inf: 0.8, vst: 0.75, ord: 0.8, dog: 0.2, vhe: 0.65 } },
  { name: 'Questions pour un champion', by: 'France 3 · jeu', tag: 'Top, je suis…', color: '#1d5aa8',
    desc: 'Des candidats qui ont passé des années à accumuler des savoirs, et un buzzer qui récompense celui qui sait avant les autres. Le ton est courtois, le rythme soutenu, l\'humilité de rigueur. C\'est le tempérament des curieux méthodiques, qui aiment savoir pour le plaisir de savoir et qui gagnent sans fanfaronner.',
    t: { rig: 0.9, con: 0.9, san: 0.85, vtr: 0.85, ouv: 0.8, aff: 0.9, cmp: 0.7, inf: 0.2, vhe: 0.3, vst: 0.3, soc: 0.3 } },
  { name: 'Des chiffres et des lettres', by: 'France 3 · jeu', tag: 'Le mot le plus long, sans calculatrice', color: '#2d6a4f',
    desc: 'Six lettres ou sept chiffres, quarante-cinq secondes, un carnet et un crayon. Rien n\'a changé depuis des décennies et personne ne le regrette. C\'est le tempérament des esprits calmes et précis, qui trouvent dans l\'exercice régulier une forme de sérénité, et pour qui le vrai luxe est un problème bien posé.',
    t: { rig: 0.95, aff: 0.95, ste: 0.95, vtr: 0.9, chg: 0.05, vst: 0.05, inf: 0.1, soc: 0.2, con: 0.9, tmp: 0.8, dom: 0.15 } },
  { name: 'Qui veut gagner des millions ?', by: 'TF1 · jeu', tag: 'Je prends ou je m\'arrête ?', color: '#3a2a7a',
    desc: 'Quinze questions, trois jokers et à chaque palier la même question : risquer ce qu\'on a pour ce qu\'on pourrait avoir. La lumière baisse, la musique monte, et l\'on pèse chaque réponse. C\'est le tempérament des prudents qui aiment le frisson, capables de s\'arrêter au bon moment et de ne jamais regretter l\'argent qu\'ils ont gardé.',
    t: { vig: 0.85, vse: 0.85, vac: 0.85, rsk: 0.3, inc: 0.2, san: 0.75, thr: 0.75, aff: 0.8, vpo: 0.65, soc: 0.3, loc: 0.3 } },
  { name: 'Le Maillon faible', by: 'TF1 · jeu', tag: 'Au revoir, sans états d\'âme', color: '#1b1b1b',
    desc: 'Une équipe qui doit coopérer pour gagner de l\'argent et, à chaque manche, éliminer l\'un des siens. Le ton est glacial, les regards en coin, et la stratégie se cache derrière la logique. C\'est le tempérament des compétiteurs lucides, qui ne confondent jamais l\'équipe et l\'amitié, et qui assument de trancher.',
    t: { cmp: 0.98, nat: 0.9, com: 0.85, emp: 0.1, care: 0.1, col: 0.15, dom: 0.85, san: 0.85, att: 0.1, cfl: 0.85, vpo: 0.8 } },
  { name: 'N\'oubliez pas les paroles', by: 'France 2 · jeu musical', tag: 'On chante d\'abord, on gagne ensuite', color: '#e8603c',
    desc: 'Des candidats qui connaissent par cœur des centaines de chansons et les chantent avec un bonheur contagieux, musiciens derrière et public qui danse. Même le maestro qui trébuche sur un mot repart en souriant. C\'est le tempérament des joyeux fidèles, qui aiment le répertoire commun et le plaisir de le partager.',
    t: { vhe: 0.9, soc: 0.9, att: 0.85, opt: 0.9, vtr: 0.75, inf: 0.85, cmp: 0.25, nat: 0.1, vis: 0.1, dog: 0.15 } },
  { name: 'Les 12 coups de midi', by: 'TF1 · jeu', tag: 'Revenir chaque jour, encore une fois', color: '#f2c12e',
    desc: 'Un Maître de midi revient chaque jour, remet son titre en jeu et découvre case par case une étoile mystérieuse. Certains tiennent des centaines d\'émissions grâce à une régularité impressionnante. C\'est le tempérament des endurants méthodiques, qui ne cherchent pas le coup d\'éclat mais le fait d\'être là, fiables, demain aussi.',
    t: { fia: 0.95, det: 0.9, ord: 0.9, tmp: 0.85, ste: 0.9, vse: 0.8, rig: 0.85, vst: 0.15, chg: 0.1, aud: 0.2, vhe: 0.35 } },
  { name: 'Motus', by: 'France 2 · jeu', tag: 'Pourvu que ce ne soit pas la boule noire', color: '#e13a3a',
    desc: 'Un mot à trouver lettre après lettre, du jaune, du rouge, et des boules à tirer qui peuvent tout donner ou tout reprendre. On y réfléchit un peu et on s\'en remet beaucoup à la chance, dans une ambiance bon enfant. C\'est le tempérament des gens détendus, qui font de leur mieux et acceptent de bon cœur que le sort ait le dernier mot.',
    t: { loc: 0.85, opt: 0.9, cfl: 0.05, thr: 0.1, vpo: 0.1, ste: 0.8, vtr: 0.75, aud: 0.3, dom: 0.15, rig: 0.55, vhe: 0.7 } },
  { name: 'Le Juste Prix', by: 'TF1 · jeu', tag: 'Plus ? Moins ? Le prix des choses', color: '#ffb400',
    desc: 'Une machine à laver, un salon de jardin, une voiture : il faut savoir ce que valent les choses, et le crier avec le public derrière soi. Rien d\'abstrait, tout est concret et bruyant. C\'est le tempérament des pragmatiques joyeux, qui ont les pieds dans le réel, connaissent le prix du pain et vivent tout avec enthousiasme.',
    t: { inf: 0.95, soc: 0.9, epi: 0.05, vhe: 0.85, aff: 0.3, rig: 0.25, ide: 0.2, vun: 0.15, tmp: 0.2, opn: 0.7, ouv: 0.3 } },
  { name: 'Burger Quiz', by: 'Canal+ · jeu', tag: 'Les règles ? Quelles règles ?', color: '#e4312b',
    desc: 'Deux équipes, des questions absurdes, un animateur qui change les règles quand il veut et des points distribués au mérite… ou pas. Personne ne vient pour gagner, tout le monde vient pour rire. C\'est le tempérament des esprits joueurs, qui n\'aiment rien tant que le chaos bien mené et pour qui le sérieux est une option.',
    t: { vhe: 0.9, ide: 0.9, inf: 0.95, auth: 0.05, vco: 0.05, rig: 0.05, ord: 0.1, cmp: 0.2, vst: 0.9, dog: 0.05, sanc: 0.1 } },
  { name: 'Fort Boyard', by: 'France 2 · aventure', tag: 'Une clé, un gong, des tigres', color: '#3d6e8f',
    desc: 'Des épreuves dans des cellules humides, des araignées, des énigmes de vieillard barbu et une équipe qui encourage à travers les barreaux. On y va pour avoir peur et en rire après. C\'est le tempérament des audacieux enthousiastes, qui aiment les défis physiques à condition d\'avoir des complices pour les partager.',
    t: { aud: 0.95, rsk: 0.95, vst: 0.95, col: 0.85, det: 0.85, opt: 0.85, vig: 0.15, thr: 0.25, vtr: 0.65, aff: 0.25, vse: 0.15 } },
  { name: 'Intervilles', by: 'France 3 · jeu', tag: 'Pour l\'honneur du clocher', color: '#2a8f3d',
    desc: 'Deux villes s\'affrontent sur des toboggans savonnés, avec des vachettes et toute la population en tribune. On y défend les couleurs de chez soi avec une mauvaise foi délicieuse et beaucoup de bonne humeur. C\'est le tempérament des gens attachés à leur communauté, qui aiment gagner ensemble et rire surtout.',
    t: { loy: 0.98, col: 0.95, soc: 0.9, opn: 0.95, cmp: 0.85, vtr: 0.9, ind: 0.1, vhe: 0.85, rig: 0.15, ouv: 0.25 } },
  { name: 'La Carte aux trésors', by: 'France 3 · aventure', tag: 'Seul en hélicoptère au-dessus d\'une région', color: '#4e8fb8',
    desc: 'Deux candidats, chacun dans son hélicoptère, lisent des énigmes et cherchent un trésor au milieu des paysages. On gagne par l\'intuition, la culture locale et le sens de l\'orientation, sans jamais écraser l\'autre. C\'est le tempérament des explorateurs autonomes, qui aiment se débrouiller seuls et regarder les choses de haut.',
    t: { ind: 0.9, ouv: 0.85, vst: 0.85, vsd: 0.9, soc: 0.25, rsk: 0.7, col: 0.2, vpo: 0.1, inf: 0.25, ide: 0.75, dip: 0.6 } },
  { name: 'Tout le monde veut prendre sa place', by: 'France 2 · jeu', tag: 'Défendre son fauteuil', color: '#b63b2d',
    desc: 'Un champion assis sur son fauteuil voit défiler chaque jour des challengers qui n\'ont qu\'une envie : s\'y asseoir à sa place. Il faut à la fois tenir sa position et regarder venir la menace. C\'est le tempérament de ceux qui ont conquis quelque chose et le défendent pied à pied, avec un œil toujours sur le rétroviseur.',
    t: { cmp: 0.9, thr: 0.85, vig: 0.85, vpo: 0.8, dom: 0.8, vse: 0.8, cfl: 0.75, det: 0.9, col: 0.15, chg: 0.15, nat: 0.7 } },
  { name: 'Cash Investigation', by: 'France 2 · enquête', tag: 'Bonjour, on peut vous poser une question ?', color: '#c21f3a',
    desc: 'Des mois d\'enquête, des documents confidentiels et une question posée en face à celui qui ne voulait pas y répondre. On y traque les injustices sans ménager personne, avec un sens aigu de la mise en scène. C\'est le tempérament des militants du fait, que rien n\'arrête quand ils ont la conviction qu\'on leur cache quelque chose.',
    t: { eng: 0.98, com: 0.95, cfl: 0.98, fair: 0.95, nat: 0.9, vun: 0.9, auth: 0.1, dip: 0.1, vpo: 0.1, epi: 0.8, chg: 0.85 } },
  { name: 'Envoyé spécial', by: 'France 2 · magazine', tag: 'Aller voir, puis raconter', color: '#2f4f6f',
    desc: 'Des reporters partent loin ou tout près, prennent le temps de rencontrer les gens et reviennent avec un récit nuancé. On y entend plus qu\'on n\'y juge. C\'est le tempérament des curieux humanistes, qui préfèrent comprendre une situation avant d\'avoir un avis et qui accordent à chacun le droit d\'être compliqué.',
    t: { emp: 0.9, ouv: 0.9, vun: 0.9, care: 0.85, san: 0.8, tmp: 0.8, opn: 0.1, dog: 0.1, vhe: 0.2, inf: 0.3, cfl: 0.35 } },
  { name: 'Zone interdite', by: 'M6 · magazine', tag: 'Derrière la porte, il y a une histoire', color: '#6a1b2d',
    desc: 'Les coulisses des urgences, la vie des familles nombreuses, les vacances des gens pressés : on pousse les portes que tout le monde voudrait ouvrir. Le rythme est vif, les histoires concrètes et l\'on ne s\'attarde pas sur la théorie. C\'est le tempérament des curieux pragmatiques, qui veulent voir de leurs yeux comment vivent les autres.',
    t: { vst: 0.85, soc: 0.8, ouv: 0.8, epi: 0.1, eng: 0.15, rig: 0.35, inf: 0.75, tmp: 0.3, dog: 0.2, aff: 0.35 } },
  { name: 'Complément d\'enquête', by: 'France 2 · enquête', tag: 'Vérifier, puis vérifier encore', color: '#44546a',
    desc: 'Une enquête posée, qui recoupe les sources, donne la parole à chaque partie et laisse les documents parler. Le ton est grave sans être dramatique. C\'est le tempérament des sceptiques méthodiques, qui ne croient rien sur parole mais ne condamnent personne sans preuve, et qui aiment qu\'un dossier tienne debout.',
    t: { rig: 0.95, vig: 0.9, nat: 0.8, san: 0.85, fair: 0.85, aff: 0.9, eng: 0.6, inf: 0.15, vhe: 0.15, dog: 0.1, soc: 0.3 } },
  { name: 'Faites entrer l\'accusé', by: 'France 2 · faits divers', tag: 'Le mal existe, il faut le regarder', color: '#2b2b2b',
    desc: 'Une voix grave, un imperméable, et le récit minutieux d\'un crime réel, de la découverte au verdict. On y explore la part sombre des gens ordinaires avec rigueur et sans complaisance. C\'est le tempérament des vigilants, qui savent que le danger existe, lisent entre les lignes et préfèrent regarder la réalité en face.',
    t: { thr: 0.95, vig: 0.95, san: 0.9, nat: 0.85, auth: 0.75, vis: 0.8, rig: 0.8, opt: 0.15, soc: 0.15, vhe: 0.1 } },
  { name: 'Capital', by: 'M6 · économie', tag: 'Combien ça coûte, combien ça rapporte', color: '#0f6e5a',
    desc: 'Le prix des choses, les marges, les stratégies des marques et les ambitions de ceux qui réussissent. On y aime les chiffres, les courbes et les bonnes affaires, sans s\'encombrer d\'idéologie. C\'est le tempérament des esprits concrets et ambitieux, qui regardent le monde comme un marché et veulent savoir comment il tourne.',
    t: { vac: 0.95, vpo: 0.85, aff: 0.9, epi: 0.05, cmp: 0.8, vun: 0.2, care: 0.3, rig: 0.75, eng: 0.1, rsk: 0.35, vig: 0.7 } },
  { name: 'Thalassa', by: 'France 3 · mer', tag: 'Le rythme des marées', color: '#1e6f9f',
    desc: 'Un générique qu\'on reconnaît à la première note, et des heures au bord de l\'eau, avec les pêcheurs, les marins et les gardiens de phare. Rien ne presse, la mer décide. C\'est le tempérament des contemplatifs, calmes et patients, qui préfèrent l\'horizon à l\'agitation et ne cherchent à battre personne.',
    t: { ste: 0.95, vun: 0.85, san: 0.9, cfl: 0.05, vpo: 0.05, cmp: 0.1, ind: 0.75, soc: 0.2, tmp: 0.85, thr: 0.15, ouv: 0.8 } },
  { name: 'Faut pas rêver', by: 'France 3 · voyage', tag: 'Ailleurs, les gens vivent autrement', color: '#e39b3a',
    desc: 'On part à la rencontre des traditions du monde entier, des fêtes de village aux métiers oubliés, avec un regard émerveillé et respectueux. Chaque culture est présentée comme une manière légitime de vivre. C\'est le tempérament des voyageurs curieux, qui aiment la diversité des coutumes et ne jugent jamais celles des autres.',
    t: { ouv: 0.95, opn: 0.05, vun: 0.85, vtr: 0.75, emp: 0.8, vst: 0.75, dog: 0.05, vpo: 0.1, cmp: 0.1, loy: 0.3 } },
  { name: 'Des racines et des ailes', by: 'France 3 · patrimoine', tag: 'Les pierres ont une mémoire', color: '#8a6a3b',
    desc: 'Des châteaux, des cathédrales, des artisans qui restaurent des charpentes vieilles de huit siècles. On prend le temps, on filme d\'en haut, on explique chaque détail. C\'est le tempérament de ceux qui aiment ce qui dure, respectent le travail bien fait et considèrent que transmettre est aussi important qu\'inventer.',
    t: { vtr: 0.98, tmp: 0.95, opn: 0.85, rig: 0.8, chg: 0.05, vst: 0.15, sanc: 0.8, ste: 0.9, con: 0.8, aud: 0.2, vhe: 0.35 } },
  { name: 'Rendez-vous en terre inconnue', by: 'France 2 · voyage', tag: 'Arriver sans savoir, repartir changé', color: '#b2572b',
    desc: 'Une personnalité part sans connaître sa destination et vit quelques jours chez un peuple lointain, sans surplomb ni condescendance. On partage le thé, les tâches, les silences et parfois les larmes du départ. C\'est le tempérament de ceux qui s\'ouvrent entièrement à l\'autre et se laissent transformer par la rencontre.',
    t: { emp: 0.98, ouv: 0.95, care: 0.95, vun: 0.95, vpo: 0.05, dom: 0.1, nat: 0.05, opn: 0.05, aff: 0.1, vse: 0.2, att: 0.85 } },
  { name: 'Ushuaïa Nature', by: 'TF1 · nature', tag: 'La planète vaut le détour', color: '#2e7d4f',
    desc: 'Un homme en ULM, en plongée ou suspendu à une falaise pour montrer la beauté de la nature et plaider pour la protéger. Le frisson de l\'aventure sert une cause. C\'est le tempérament des idéalistes intrépides, qui vont chercher les émotions fortes au bout du monde et en reviennent avec un message.',
    t: { vun: 0.98, eng: 0.9, aud: 0.85, vst: 0.9, rsk: 0.8, sanc: 0.8, tmp: 0.9, ind: 0.8, soc: 0.3, vac: 0.3, vis: 0.6 } },
  { name: 'C\'est pas sorcier', by: 'France 3 · savoir', tag: 'Expliquer avec une maquette et un camion', color: '#f28c28',
    desc: 'Trois complices, un camion-laboratoire et des maquettes en carton pour expliquer la digestion, les volcans ou la bourse. Tout peut se comprendre si on s\'y prend bien, et la bonne humeur fait partie de la méthode. C\'est le tempérament des pédagogues enthousiastes, qui croient au progrès et aiment rendre les choses simples sans les trahir.',
    t: { ouv: 0.95, opt: 0.9, epi: 0.1, inf: 0.8, vis: 0.05, rig: 0.75, dog: 0.05, cmp: 0.1, soc: 0.75, col: 0.75, vpo: 0.05 } },
  { name: 'E=M6', by: 'M6 · savoir', tag: 'La science au quotidien, sans panique', color: '#6c63b5',
    desc: 'Pourquoi le pain rassit, comment marche un GPS, ce qui se passe dans le cerveau quand on a peur : un présentateur calme explique avec clarté, schéma à l\'appui. Pas d\'emphase, pas de dogme, juste des faits bien posés. C\'est le tempérament des esprits rationnels et posés, qui aiment comprendre comment fonctionnent les choses de tous les jours.',
    t: { aff: 0.9, rig: 0.85, ouv: 0.85, ste: 0.85, con: 0.8, vis: 0.1, inf: 0.35, soc: 0.35, sanc: 0.2, dog: 0.1, vhe: 0.3 } },
  { name: 'La Grande Librairie', by: 'France 5 · littérature', tag: 'Le temps de lire, le temps d\'écouter', color: '#6b4a2f',
    desc: 'Quelques écrivains autour d\'une table, qui parlent de leurs livres sans se couper la parole, sous l\'œil attentif d\'un animateur passionné. On y prend le temps d\'une phrase, d\'une idée, d\'un silence. C\'est le tempérament des lecteurs rêveurs, qui préfèrent la profondeur à la répartie et vivent autant dans les livres que dans le monde.',
    t: { ide: 0.95, ouv: 0.9, ste: 0.9, soc: 0.3, cmp: 0.05, dom: 0.1, inf: 0.3, tmp: 0.85, vst: 0.35, vpo: 0.1, vhe: 0.55 } },
  { name: 'Quotidien', by: 'TMC · talk-show', tag: 'L\'actualité, avec un sourire en coin', color: '#0a84c6',
    desc: 'Une équipe jeune et rapide qui décortique l\'actualité du jour, alterne les reportages sérieux et les séquences légères, et reçoit des invités du monde entier. On y est engagé sans être austère, ironique sans être méchant. C\'est le tempérament des urbains curieux, ouverts sur le monde et attentifs à ce qui change.',
    t: { inf: 0.85, ouv: 0.85, vun: 0.85, opn: 0.05, chg: 0.8, eng: 0.7, soc: 0.85, vtr: 0.15, auth: 0.15, com: 0.65, vst: 0.8 } },
  { name: 'Touche pas à mon poste', by: 'C8 · talk-show', tag: 'Tout le monde parle en même temps', color: '#e5007d',
    desc: 'Une grande table de chroniqueurs qui rient fort, s\'emportent, se réconcilient et recommencent le lendemain autour de leur animateur. Rien n\'est préparé au millimètre et c\'est précisément ce qui plaît. C\'est le tempérament des extravertis à l\'état pur, fidèles à leur bande, qui préfèrent l\'émotion vive à la réflexion posée.',
    t: { soc: 0.98, inf: 0.98, vhe: 0.85, cfl: 0.9, loy: 0.9, rig: 0.05, con: 0.05, aff: 0.05, san: 0.1, vst: 0.85, dom: 0.8 } },
  { name: 'C à vous', by: 'France 5 · talk-show', tag: 'On dîne ensemble, on parle de tout', color: '#c9a063',
    desc: 'Une table dressée, un plat qui mijote en coulisse, et des invités qu\'on interroge avec curiosité et gentillesse. Même l\'actualité difficile se discute sans hausser le ton. C\'est le tempérament des hôtes bienveillants, qui savent recevoir, poser les bonnes questions et donner à chacun l\'envie de rester pour le dessert.',
    t: { dip: 0.9, soc: 0.9, vhe: 0.8, care: 0.75, cfl: 0.15, ouv: 0.8, att: 0.8, com: 0.3, san: 0.8, dog: 0.1, ste: 0.75 } },
  { name: 'On n\'est pas couché', by: 'France 2 · talk-show', tag: 'Le samedi soir, on débat pour de vrai', color: '#20304a',
    desc: 'Des invités qui viennent présenter leur livre ou leur film et tombent sur des chroniqueurs qui les ont lus, vus, et ont un avis tranché. Les échanges peuvent être vifs, jusqu\'à tard dans la nuit. C\'est le tempérament des débatteurs passionnés, qui préfèrent une vraie discussion houleuse à un compliment convenu.',
    t: { com: 0.95, cfl: 0.95, epi: 0.8, aff: 0.85, dog: 0.7, dip: 0.15, ind: 0.8, dom: 0.8, ste: 0.1, eng: 0.75, tmp: 0.3 } },
  { name: 'Vivement dimanche', by: 'France 2 · variétés', tag: 'Un canapé rouge et que des amis', color: '#b22234',
    desc: 'Un canapé rouge, un invité d\'honneur et tous ses amis qui viennent lui dire des choses gentilles un dimanche après-midi. Rien ne dépasse, rien ne blesse, tout le monde se connaît. C\'est le tempérament des fidèles chaleureux, qui aiment les habitudes, les visages familiers et la douceur des moments où il ne se passe rien de grave.',
    t: { att: 0.95, vtr: 0.9, ste: 0.9, cfl: 0.05, dip: 0.95, soc: 0.85, com: 0.1, chg: 0.05, loy: 0.85, vst: 0.15, nat: 0.15 } },
  { name: 'Les Guignols de l\'info', by: 'Canal+ · satire', tag: 'Les puissants en latex', color: '#f7d117',
    desc: 'Des marionnettes caricaturent chaque soir les puissants, les présentateurs et les champions, sans exception ni révérence. Le rire y est une arme de démocratie, et personne n\'est à l\'abri. C\'est le tempérament des irrévérencieux, qui se méfient des pouvoirs, adorent l\'absurde et pensent qu\'une bonne blague vaut parfois un éditorial.',
    t: { auth: 0.02, com: 0.9, ide: 0.9, nat: 0.85, vco: 0.05, sanc: 0.05, lib: 0.95, chg: 0.85, dip: 0.1, vtr: 0.15, cfl: 0.8, vpo: 0.1 } },
  { name: 'Le Petit Journal', by: 'Canal+ · satire', tag: 'Montrer ce qui se passe à côté', color: '#1a1a1a',
    desc: 'On filme ce que les autres caméras coupent : le micro resté ouvert, le sourire forcé, la phrase de trop. Le ton est froidement ironique, et la seule arme est l\'image bien choisie. C\'est le tempérament des observateurs lucides, qui repèrent les décalages, restent calmes et laissent les faits faire rire tout seuls.',
    t: { vig: 0.85, san: 0.85, aff: 0.8, nat: 0.8, lib: 0.8, att: 0.25, emp: 0.35, inf: 0.7, com: 0.7, vtr: 0.15, dog: 0.1 } },
  { name: 'Taratata', by: 'France 2 · musique live', tag: 'Tout en direct, rien en playback', color: '#ad2a2a',
    desc: 'Des artistes qui jouent vraiment, en live, et qui se retrouvent pour des duos improbables devant un animateur qui connaît la musique mieux que personne. Pas de classement, pas de concours, seulement le plaisir de jouer ensemble. C\'est le tempérament des passionnés sincères, pour qui l\'authenticité compte plus que la réussite.',
    t: { vhe: 0.85, ide: 0.9, ouv: 0.85, vst: 0.8, vpo: 0.05, cmp: 0.05, vac: 0.25, rig: 0.7, col: 0.75, soc: 0.75, auth: 0.25 } },
  { name: 'Les Enfants de la télé', by: 'TF1 · archives', tag: 'Tu te souviens de ça ?', color: '#f39c34',
    desc: 'Des extraits d\'émissions anciennes, des bêtisiers et des invités qui rient d\'eux-mêmes en se revoyant avec vingt ans de moins. Rien n\'y est grave, tout y est tendre et un peu nostalgique. C\'est le tempérament de ceux qui aiment les souvenirs partagés, rient facilement de leurs propres gaffes et ne se prennent jamais au sérieux.',
    t: { att: 0.9, vtr: 0.85, vhe: 0.9, opt: 0.9, soc: 0.9, cmp: 0.05, thr: 0.05, rig: 0.15, chg: 0.1, dog: 0.1, tmp: 0.25 } },
  { name: 'Maison à vendre', by: 'M6 · immobilier', tag: 'Dépersonnaliser pour mieux vendre', color: '#4b7fa3',
    desc: 'Une maison qui ne se vend pas, une experte qui arrive, range, repeint, désencombre et remet tout en ordre pour convaincre les acheteurs. L\'émotion des propriétaires compte, mais le marché aussi. C\'est le tempérament des organisateurs pragmatiques, qui voient tout de suite ce qui cloche et savent transformer un chaos en projet.',
    t: { ord: 0.95, rig: 0.85, epi: 0.05, aff: 0.8, lea: 0.8, chg: 0.8, vac: 0.8, com: 0.7, vhe: 0.3, ide: 0.4, dip: 0.6 } },
  { name: 'Recherche appartement ou maison', by: 'M6 · immobilier', tag: 'On visite, on compare, on ne s\'emballe pas', color: '#7a8f6a',
    desc: 'Des familles avec un budget serré et une liste de critères, et un agent qui les emmène visiter trois biens en pesant chaque compromis. On réfléchit à long terme, on mesure le trajet de l\'école, on ne signe pas sur un coup de cœur. C\'est le tempérament des prudents raisonnables, qui préfèrent le bon choix au choix rapide.',
    t: { vse: 0.95, vig: 0.85, tmp: 0.9, rsk: 0.1, dip: 0.8, vst: 0.15, aud: 0.15, epi: 0.1, vbe: 0.85, inc: 0.2, aff: 0.75 } },
  { name: 'D&CO', by: 'M6 · déco', tag: 'Une semaine pour tout changer', color: '#e86f9a',
    desc: 'Une décoratrice débarque chez des gens qui se sont mis en retrait de leur propre vie et transforme leur maison en quelques jours, avec une énergie débordante. Tout est lumineux, coloré et plein de bonnes intentions. C\'est le tempérament des transformateurs optimistes, qui croient qu\'un changement de décor peut changer une vie.',
    t: { chg: 0.95, ide: 0.9, care: 0.9, opt: 0.95, vst: 0.8, vtr: 0.1, emp: 0.85, vis: 0.05, rsk: 0.65, vpo: 0.1, inf: 0.85 } },
  { name: 'Les Reines du shopping', by: 'M6 · mode', tag: 'Le budget, le thème, et le regard des autres', color: '#d63a8e',
    desc: 'Cinq candidates, un thème, un budget et une journée pour composer la tenue parfaite, puis le verdict sans complaisance des concurrentes. On s\'y complimente beaucoup et on se note sévèrement. C\'est le tempérament des stylistes compétitifs, qui aiment le plaisir de choisir, le frisson de l\'apparence et la petite piqûre de la comparaison.',
    t: { cmp: 0.9, vhe: 0.9, inf: 0.9, vpo: 0.8, com: 0.75, vst: 0.85, vun: 0.1, eng: 0.1, dip: 0.35, tmp: 0.15, aff: 0.3 } },
  { name: 'Téléfoot', by: 'TF1 · football', tag: 'Le dimanche matin, c\'est sacré', color: '#1e3f8a',
    desc: 'Les buts de la semaine, les résumés, les interviews de vestiaire et les débats sur la titularisation du numéro neuf. On y parle de son club avec une ferveur qui ne se discute pas. C\'est le tempérament des supporters fidèles, qui aiment la compétition, les rituels du week-end et les joies partagées de tout un stade.',
    t: { loy: 0.95, cmp: 0.9, col: 0.8, vtr: 0.8, soc: 0.85, vhe: 0.8, aff: 0.15, ouv: 0.3, eng: 0.1, ide: 0.25, inf: 0.75 } },
  { name: 'Stade 2', by: 'France 2 · sport', tag: 'Tous les sports, sans chauvinisme', color: '#1c6ea4',
    desc: 'Le rugby, le cyclisme, le handball, l\'escrime, tout ce qui s\'est joué le week-end, présenté avec sérieux et sans tapage. Aucune discipline n\'est plus noble qu\'une autre, et les défaites sont racontées aussi dignement que les victoires. C\'est le tempérament des sportifs dans l\'âme, attachés au fair-play et au respect de l\'effort.',
    t: { fair: 0.95, fia: 0.9, ste: 0.85, vtr: 0.8, tmp: 0.75, cfl: 0.2, vst: 0.3, inf: 0.3, ouv: 0.75, cmp: 0.55, vpo: 0.15 } },
  { name: 'Le JT de 20 heures', by: 'TF1 et France 2 · information', tag: 'Bonsoir, voici les titres', color: '#0b2545',
    desc: 'Tous les soirs à la même heure, les mêmes rubriques, un ton posé et une voix qui résume le monde en trente minutes. Pas d\'emportement, pas d\'opinion, des faits hiérarchisés et vérifiés. C\'est le tempérament des gens fiables et mesurés, qui aiment les repères, respectent les institutions et ne s\'emballent jamais.',
    t: { fia: 0.98, con: 0.95, san: 0.95, vco: 0.9, auth: 0.8, vse: 0.85, vst: 0.1, chg: 0.1, rsk: 0.1, inf: 0.3, com: 0.2, lib: 0.3 } },
  { name: 'Télématin', by: 'France 2 · matinale', tag: 'Réveiller le pays en douceur', color: '#f5b841',
    desc: 'Il est six heures trente, le café coule, et une équipe souriante enchaîne la météo, la santé, les livres et la cuisine, chronique après chronique, à la minute près. Une routine réglée comme une horloge, mais tendre. C\'est le tempérament des lève-tôt bienveillants, organisés et constants, qui aiment commencer la journée avec de bonnes nouvelles.',
    t: { ord: 0.95, ste: 0.9, opt: 0.85, fia: 0.9, cfl: 0.05, att: 0.8, rig: 0.8, vst: 0.2, dom: 0.15, care: 0.75, vis: 0.15 } },
  { name: 'Silence, ça pousse !', by: 'France 5 · jardin', tag: 'Chaque chose en son temps', color: '#5c8a3a',
    desc: 'Comment tailler un rosier, sauver une tomate, attirer les abeilles : des conseils donnés à voix basse, les mains dans la terre. Rien ne se force, tout se prépare, et le résultat arrive la saison prochaine. C\'est le tempérament des patients doux et concrets, qui préfèrent faire pousser que conquérir.',
    t: { ste: 0.95, tmp: 0.95, care: 0.85, vun: 0.8, dom: 0.05, rig: 0.7, vbe: 0.8, epi: 0.15, vst: 0.2, vpo: 0.05, inf: 0.2 } },
  { name: 'Strip-tease', by: 'France 3 · documentaire', tag: 'Sans commentaire', color: '#7d7d7d',
    desc: 'Aucune voix off, aucune musique, aucun jugement : la caméra filme des gens ordinaires dans leur vie, et laisse le spectateur se débrouiller avec ce qu\'il voit. Le résultat est souvent drôle, parfois troublant, toujours d\'une grande froideur apparente. C\'est le tempérament des observateurs silencieux, qui regardent sans intervenir et gardent leur avis pour eux.',
    t: { san: 0.9, ind: 0.9, dom: 0.05, com: 0.1, inf: 0.05, soc: 0.15, att: 0.2, eng: 0.05, vig: 0.8, ouv: 0.75, cfl: 0.15 } },
  { name: 'La Roue de la fortune', by: 'TF1 · jeu', tag: 'Laisser tourner et espérer', color: '#e6b422',
    desc: 'On lance la roue, on choisit une consonne, et tout peut basculer d\'une case « banqueroute » à une case « jackpot ». Le sort décide beaucoup, et c\'est justement ce qui amuse. C\'est le tempérament des insouciants chanceux, qui aiment jouer, profitent de ce qui vient et ne s\'attardent pas sur ce qui s\'en va.',
    t: { loc: 0.95, vhe: 0.9, opt: 0.85, rig: 0.1, tmp: 0.1, vig: 0.1, inc: 0.8, ord: 0.15, vpo: 0.5, aff: 0.4, thr: 0.05 } },
  { name: 'Tout le monde en parle', by: 'France 2 · talk-show', tag: 'Il est minuit, tout est permis', color: '#141414',
    desc: 'Un plateau noir, un animateur en costume sombre, des questions déroutantes et des invités de tous horizons réunis tard dans la nuit. On y cherche la provocation, le moment où le masque tombe. C\'est le tempérament des provocateurs curieux, qui aiment bousculer les codes, pousser les autres dans leurs retranchements et voir ce qui se passe.',
    t: { aud: 0.95, vst: 0.95, sanc: 0.05, vco: 0.05, dom: 0.8, cfl: 0.8, dip: 0.2, care: 0.2, ouv: 0.8, lib: 0.9, tmp: 0.15 } },
  { name: 'Loft Story', by: 'M6 · téléréalité', tag: 'La première fois qu\'on a osé', color: '#ff6f3c',
    desc: 'Onze jeunes gens enfermés dans un loft, filmés jour et nuit, et un pays entier qui découvre un genre nouveau. Personne ne savait comment se comporter, et c\'est ce qui rendait tout si spontané. C\'est le tempérament des pionniers insouciants, qui se lancent dans l\'inconnu sans mode d\'emploi et vivent chaque jour comme il vient.',
    t: { chg: 0.95, inc: 0.9, vst: 0.9, ord: 0.1, tmp: 0.1, vtr: 0.05, rig: 0.1, soc: 0.85, vig: 0.15, vco: 0.2, opt: 0.8 } },
  { name: 'Qui veut être mon associé ?', by: 'M6 · entrepreneuriat', tag: 'Convaincre en cinq minutes', color: '#0e4d64',
    desc: 'Des entrepreneurs présentent leur projet à des investisseurs qui mettent leur propre argent sur la table, négocient les parts et posent les questions qui fâchent. On y parle chiffres, audace et vision. C\'est le tempérament des bâtisseurs audacieux, qui prennent des risques calculés, aiment convaincre et regardent l\'avenir avec appétit.',
    t: { vac: 0.95, rsk: 0.85, aud: 0.9, vsd: 0.9, lea: 0.85, chg: 0.85, vis: 0.05, cmp: 0.8, vse: 0.15, epi: 0.15, vpo: 0.75 } },
  { name: 'Seul face à la nature', by: 'Discovery · survie', tag: 'Personne pour vous aider', color: '#5a4a2a',
    desc: 'Un homme lâché seul en pleine jungle, dans le désert ou sur un glacier, qui doit trouver de l\'eau, un abri et un chemin de retour. Il n\'y a ni équipe, ni vote, ni public, seulement la débrouille. C\'est le tempérament des solitaires coriaces, qui comptent sur eux-mêmes avant tout et gardent la tête froide quand ça tourne mal.',
    t: { ind: 0.98, soc: 0.05, san: 0.9, det: 0.95, rsk: 0.9, vhe: 0.05, col: 0.1, vsd: 0.95, att: 0.2, inf: 0.15, loc: 0.05 } },
];

window.PRISME_TVSHOWS = { TVSHOWS };
